### ISSUE TITLE
Build warnings for keyvault assembly & a few syle cleanup

### ISSUE THREAD

**Issue by scheyal** [microsoft/botframework-solutions#1000]
## Project

**Name**: Virtual Assistant

**Language**: 
C#
## Description
Building clean results with warnings about keyvault assembly (see below)
## To Reproduce
sync & build

## Expected behavior
clean build, no warnings (or errors)

## Additional context

Severity | Code | Description | Project | File | Line | Suppression State
-- | -- | -- | -- | -- | -- | --
Warning | SA1208 | Using directive for   'System' should appear before directive for   'CalendarSkill.Dialogs.Shared.Resources.Strings' | CalendarSkill | C:\workspace\botroot\solutions\solutions\Virtual-Assistant\src\csharp\skills\calendarskill\calendarskill\Models\Resources\AskParameterTemplate.cs | 2 | Active
Warning | SA1208 | Using directive for   'System.Collections.Generic' should appear before directive for   'CalendarSkill.Dialogs.Shared.Resources.Strings' | CalendarSkill | C:\workspace\botroot\solutions\solutions\Virtual-Assistant\src\csharp\skills\calendarskill\calendarskill\Models\Resources\AskParameterTemplate.cs | 3 | Active
Warning | SA1208 | Using directive for   'System.IO' should appear before directive for   'CalendarSkill.Dialogs.Shared.Resources.Strings' | CalendarSkill | C:\workspace\botroot\solutions\solutions\Virtual-Assistant\src\csharp\skills\calendarskill\calendarskill\Models\Resources\AskParameterTemplate.cs | 4 | Active
Warning | SA1208 | Using directive for   'System.Text' should appear before directive for   'CalendarSkill.Dialogs.Shared.Resources.Strings' | CalendarSkill | C:\workspace\botroot\solutions\solutions\Virtual-Assistant\src\csharp\skills\calendarskill\calendarskill\Models\Resources\AskParameterTemplate.cs | 5 | Active
Warning | SA1208 | Using directive for   'System.Text.RegularExpressions' should appear before directive for   'CalendarSkill.Dialogs.Shared.Resources.Strings' | CalendarSkill | C:\workspace\botroot\solutions\solutions\Virtual-Assistant\src\csharp\skills\calendarskill\calendarskill\Models\Resources\AskParameterTemplate.cs | 6 | Active
Warning | SA1202 | 'public' members should   come before 'private' members | VirtualAssistant.Tests | C:\workspace\botroot\solutions\solutions\Virtual-Assistant\src\csharp\tests\virtualassistant.tests\AssistantTests.cs | 174 | Active
Warning | NU1701 | Package   'Microsoft.Azure.KeyVault.Core 1.0.0' was restored using   '.NETFramework,Version=v4.6.1' instead of the project target framework   '.NETCoreApp,Version=v2.2'. This package may not be fully compatible with   your project. | Microsoft.Bot.Solutions | C:\workspace\botroot\solutions\solutions\Virtual-Assistant\src\csharp\microsoft.bot.solutions\Microsoft.Bot.Solutions.csproj | 1 |  
Warning | NU1701 | Package   'Microsoft.Azure.KeyVault.Core 1.0.0' was restored using   '.NETFramework,Version=v4.6.1' instead of the project target framework   '.NETCoreApp,Version=v2.2'. This package may not be fully compatible with   your project. | Microsoft.Bot.Solutions | C:\workspace\botroot\solutions\solutions\Virtual-Assistant\src\csharp\microsoft.bot.solutions\Microsoft.Bot.Solutions.csproj | 1 |  
Warning | NU1701 | Package   'Microsoft.Azure.KeyVault.Core 1.0.0' was restored using   '.NETFramework,Version=v4.6.1' instead of the project target framework   '.NETCoreApp,Version=v2.2'. This package may not be fully compatible with   your project. | Microsoft.Bot.Solutions | C:\workspace\botroot\solutions\solutions\Virtual-Assistant\src\csharp\microsoft.bot.solutions\Microsoft.Bot.Solutions.csproj | 1 |  
Warning | NU1701 | Package   'Microsoft.Azure.KeyVault.Core 1.0.0' was restored using   '.NETFramework,Version=v4.6.1' instead of the project target framework   '.NETCoreApp,Version=v2.2'. This package may not be fully compatible with   your project. | EmailSkill   (Skills\EmailSkill\EmailSkill) | C:\workspace\botroot\solutions\solutions\Virtual-Assistant\src\csharp\skills\emailskill\emailskill\EmailSkill.csproj | 1 |  
Warning | NU1701 | Package   'Microsoft.Azure.KeyVault.Core 1.0.0' was restored using   '.NETFramework,Version=v4.6.1' instead of the project target framework   '.NETCoreApp,Version=v2.2'. This package may not be fully compatible with   your project. | Microsoft.Bot.Solutions.Tests | C:\workspace\botroot\solutions\solutions\Virtual-Assistant\src\csharp\tests\microsoft.bot.solutions.tests\Microsoft.Bot.Solutions.Tests.csproj | 1 |  
Warning | NU1701 | Package   'Microsoft.Azure.KeyVault.Core 1.0.0' was restored using   '.NETFramework,Version=v4.6.1' instead of the project target framework   '.NETCoreApp,Version=v2.2'. This package may not be fully compatible with   your project. | PointOfInterestSkill   (Skills\PointOfInterestSkill\PointOfInterestSkill) | C:\workspace\botroot\solutions\solutions\Virtual-Assistant\src\csharp\skills\pointofinterestskill\pointofinterestskill\PointOfInterestSkill.csproj | 1 |  
Warning | NU1701 | Package 'Microsoft.Azure.KeyVault.Core   1.0.0' was restored using '.NETFramework,Version=v4.6.1' instead of the   project target framework '.NETCoreApp,Version=v2.2'. This package may not be   fully compatible with your project. | AutomotiveSkill   (Skills\AutomotiveSkill\AutomotiveSkill) | C:\workspace\botroot\solutions\solutions\Virtual-Assistant\src\csharp\skills\automotiveskill\automotiveskill\AutomotiveSkill.csproj | 1 |  
Warning | NU1701 | Package   'Microsoft.Azure.KeyVault.Core 1.0.0' was restored using   '.NETFramework,Version=v4.6.1' instead of the project target framework   '.NETCoreApp,Version=v2.2'. This package may not be fully compatible with   your project. | ToDoSkill   (Skills\ToDoSkill\ToDoSkill) | C:\workspace\botroot\solutions\solutions\Virtual-Assistant\src\csharp\skills\todoskill\todoskill\ToDoSkill.csproj | 1 |  
Warning | NU1701 | Package   'Microsoft.Azure.KeyVault.Core 1.0.0' was restored using   '.NETFramework,Version=v4.6.1' instead of the project target framework   '.NETCoreApp,Version=v2.2'. This package may not be fully compatible with   your project. | CalendarSkill   (Skills\CalendarSkill\CalendarSkill) | C:\workspace\botroot\solutions\solutions\Virtual-Assistant\src\csharp\skills\calendarskill\calendarskill\CalendarSkill.csproj | 1 |  
Warning | NU1701 | Package   'Microsoft.Azure.KeyVault.Core 1.0.0' was restored using   '.NETFramework,Version=v4.6.1' instead of the project target framework   '.NETCoreApp,Version=v2.2'. This package may not be fully compatible with   your project. | EmailSkillTest | C:\workspace\botroot\solutions\solutions\Virtual-Assistant\src\csharp\skills\emailskill\emailskilltest\EmailSkillTest.csproj | 1 |  
Warning | NU1701 | Package   'Microsoft.Azure.KeyVault.Core 1.0.0' was restored using   '.NETFramework,Version=v4.6.1' instead of the project target framework   '.NETCoreApp,Version=v2.2'. This package may not be fully compatible with   your project. | AutomotiveSkillTest | C:\workspace\botroot\solutions\solutions\Virtual-Assistant\src\csharp\skills\automotiveskill\automotiveskilltest\AutomotiveSkillTest.csproj | 1 |  
Warning | NU1701 | Package   'Microsoft.Azure.KeyVault.Core 1.0.0' was restored using   '.NETFramework,Version=v4.6.1' instead of the project target framework   '.NETCoreApp,Version=v2.2'. This package may not be fully compatible with   your project. | ToDoSkillTest | C:\workspace\botroot\solutions\solutions\Virtual-Assistant\src\csharp\skills\todoskill\todoskilltest\ToDoSkillTest.csproj | 1 |  
Warning | NU1701 | Package   'Microsoft.Azure.KeyVault.Core 1.0.0' was restored using   '.NETFramework,Version=v4.6.1' instead of the project target framework   '.NETCoreApp,Version=v2.2'. This package may not be fully compatible with   your project. | CalendarSkillTest | C:\workspace\botroot\solutions\solutions\Virtual-Assistant\src\csharp\skills\calendarskill\calendarskilltest\CalendarSkillTest.csproj | 1 |  
Warning | NU1701 | Package   'Microsoft.Azure.KeyVault.Core 1.0.0' was restored using   '.NETFramework,Version=v4.6.1' instead of the project target framework   '.NETCoreApp,Version=v2.2'. This package may not be fully compatible with   your project. | VirtualAssistant | C:\workspace\botroot\solutions\solutions\Virtual-Assistant\src\csharp\assistant\VirtualAssistant.csproj | 1 |  
Warning | NU1701 | Package   'Microsoft.Azure.KeyVault.Core 1.0.0' was restored using   '.NETFramework,Version=v4.6.1' instead of the project target framework   '.NETCoreApp,Version=v2.2'. This package may not be fully compatible with   your project. | VirtualAssistant.Tests | C:\workspace\botroot\solutions\solutions\Virtual-Assistant\src\csharp\tests\virtualassistant.tests\VirtualAssistant.Tests.csproj | 1 |  
Warning | NU1701 | Package 'Microsoft.Azure.KeyVault.Core   1.0.0' was restored using '.NETFramework,Version=v4.6.1' instead of the   project target framework '.NETCoreApp,Version=v2.2'. This package may not be   fully compatible with your project. | PointOfInterestSkillTests | C:\workspace\botroot\solutions\solutions\Virtual-Assistant\src\csharp\skills\pointofinterestskill\pointofinterestskilltests\PointOfInterestSkillTests.csproj | 1 |

**Comment by darrenj** [comment]
@scheyal - Can you raise an issue on the KeyVault issues in the botbuilder-dotnet repo as it's not us :)

**Comment by scheyal** [comment]
Filed bug 
https://github.com/Microsoft/botbuilder-dotnet/issues/1553
