### ISSUE TITLE
Linked accounts not working with any skill that needs Authentication 

### ISSUE THREAD

**Issue by aishwaryaumachandran** [microsoft/botframework-solutions#1001]
## Project

**Name**: Virtual Assistant, Skills

**Language**: C#

## Description
Linked accounts not working with any skill that needs Authentication 

## To Reproduce
1. Follow the sample : https://github.com/Microsoft/AI/blob/master/docs/virtual-assistant/linkedaccounts.md
2. Set the User ID from the Emulator on the LinkedAccount dashboard
3. Run the Virtual Assistant Solution 
4. If "my inbox" is entered on the emulator
5. The control enters the EmailSkillDialog and checks if there are any Authenticated Connections(As the Count is set to 0)
6. The program throws an exception "You must configure an authentication connection in your bot file before using this component"
7. If logout is entered on the emulator, the response is as expected (I do see the token that was retrieved from the linked account) and it displays the text "You're signed out"

## Expected behavior
It should be able to get the Authentication connections and register the dialogs to proceed further with the flow of the solution

**Comment by darrenj** [comment]
Hi,

Can you confirm the `msbot connect generic --name "Authentication"` command has been run as per the documentation in the [getting started docs]( https://github.com/Microsoft/AI/blob/master/docs/virtual-assistant/gettingstarted.md) and you see a section along these lines in your bot.config?

```
 {
            "type": "generic",
            "name": "Authentication",
            "url": "portal.azure.net",
            "configuration": {
                "Microsoft": "Azure Active Directory v2"
            }         
        }
```

Thanks

**Comment by ghost** [comment]
@darrenj so instead of Mircosoft do we need to mention Aouth connect name instead of Micrsoft in configuration

**Comment by ghost** [comment]
Also for URL do we need to mention the URL callback for linked accounts ?

**Comment by darrenj** [comment]
My auth connection is called Microsoft, it needs to match what you have, the type is what's important to VA.  The instructions are in the Skill Configuration documentation [here](https://github.com/Microsoft/AI/blob/master/docs/virtual-assistant/gettingstarted.md)

**Comment by ghost** [comment]
@darrenj I have followed the documentation.  For example my auth connection name is UN_TEST
What should be the key for that ? Is it the Application client secret key ?

        {
            "type": "generic",
            "name": "Authentication",
            "url": "portal.azure.net",
          "configuration": {
            "UN_TEST": "Azure Active Directory v2"
          },
            "id": "132"
        }

**Comment by SiddharthSunchu** [comment]
@darrenj I am one of the developers in one of the big organization. we are implementing this. Is there a way we can communicate in a private chat? I have a lot of doubts about the things related to VA and also we have been talking to a lot of Microsoft people and creating support request regarding virtual assistant but nobody is able to help us in a proper way as it is new. We are in a bit hurry to put this up. I was also talking to Garry about the google SDK for enterprise Bot.

Let me know if you know anyone whom i can contact to get full support on this.

Thank you.

**Comment by darrenj** [comment]
It looks like the documentation steps haven't been followed if your are having to manually edit the configuration file. I've run through all the steps on a fresh deployment and can confirm this is working as expected. It's actually not a linked accounts issue as your assistant/skill cannot find the authentication configuration. If it could it would prompt for authentication.

**Comment by darrenj** [comment]
Key steps to debug further are to check the documentation, then verify in the Azure Porta find your Bot registration and click settings to validate you see an Authentication Connection:

e.g.

![image](https://user-images.githubusercontent.com/33519520/55027073-6489f500-4fd2-11e9-8651-6b5ae86c5d4c.png)

If so, click on this and click Test Connection to verify it's working.

Then ensure your .bot file as the authentication connection wired up as per the documentation

**Comment by ghost** [comment]
We have already have setup the the Oauth Connection settings. We did not manually setup the authentication in .Bot file. We used msbot connect generic to configure it. But in azure portal we manually gave the aouth connection in bot service registration.

**Comment by ghost** [comment]
Thanks we got it working.  Is there any change we have to in the specific skill for the authentication. My emails is working but for calendar it says "This feature is not yet available in the Calendar Skill. Please try asking something else." Why does that happen ?

**Comment by lauren-mills** [comment]
That error occurs when your utterance triggered an intent which is in the calendar luis model but not supported yet. Not all intents in the calendar model are supported yet.

**Comment by darrenj** [comment]
@Siddharth-Microsoft  can you confirm the calendar utterance you tried? Also, any insight into what you changed to get things working?

**Comment by ghost** [comment]
@lauren-mills  Thanks for the response. whenever we ask any recent emails ? It say doesn't have any unread emails. Even after we have unread emails in my mailbox. If i send a new email than it prompts with new email ? why does that happen ?

**Comment by lauren-mills** [comment]
Can you send some screenshots from the emulator with what you're sending/receiving?

**Comment by ghost** [comment]
<img width="524" alt="Screen Shot 2019-04-01 at 12 11 31 PM" src="https://user-images.githubusercontent.com/36431516/55342788-8cb4a080-5477-11e9-9ace-3295bb8a8ac5.png">
<img width="533" alt="Screen Shot 2019-04-01 at 11 46 16 AM" src="https://user-images.githubusercontent.com/36431516/55342795-92aa8180-5477-11e9-87d9-a3b04b76a56e.png">

**Comment by ghost** [comment]
there are emails from Siddharth in that mailbox which i sent few minutes back.

**Comment by lauren-mills** [comment]
Are you using a personal outlook/hotmail account, Google, or an organizational Azure AD account?

**Comment by ghost** [comment]
I am using Organizational account.

When i asked the question few minutes back. It did respond but later it did not.

<img width="541" alt="Screen Shot 2019-04-01 at 12 16 37 PM" src="https://user-images.githubusercontent.com/36431516/55343014-2714e400-5478-11e9-90e9-ffe3a17b41b9.png">

**Comment by darrenj** [comment]
Are the emails now "read"? Perhaps try marking them unread and try again? Just a thought.

**Comment by lauren-mills** [comment]
Darren is right, the skill only shows unread emails in the "check emails" intent. @DingmaomaoBJTU, is this setting configurable?

**Comment by ghost** [comment]
@darrenj It worked . but why does it only shows unread emails ? This is how it is queried ?

**Comment by ghost** [comment]
@darrenj and @lauren-mills can we change this settings? because i want to query for read emails as well.

**Comment by darrenj** [comment]
You certainly can, within the Email skill there is a `state.IsUnreadOnly = false` property which you can set differently according to your requirement. I'll raise a task to make this behaviour configurable.

**Comment by darrenj** [comment]
@SiddharthSunchu - looks like you can say "show all email" and it will show unread...
