### ISSUE TITLE
[Enterprise Bot Template] Clear guidance on personal data handling

### ISSUE THREAD

**Issue by hansmbakker** [microsoft/botframework-solutions#1006]
**Is your feature request related to a problem? Please describe.**
Azure documentation has this page about [how to deal with personal data in Application Insights / Log Analytics](https://docs.microsoft.com/en-us/azure/azure-monitor/platform/personal-data-mgmt).

Enterprise Bot Template has an option to log conversation properties in Application Insights. The offered PowerBI template is a really convenient start to build a dashboard to analyze metrics and user feedback.

It is possible to turn off personal data logging completely (e.g. using https://github.com/Microsoft/AI/blob/master/templates/Enterprise-Template/src/csharp/EnterpriseBotTemplate/EnterpriseTemplate/Middleware/Telemetry/TelemetryQnAMaker.cs#L37) but then the PowerBI dashboard won't work anymore.

**Describe the solution you'd like**
Clear guidance how to collect feedback (find where users were not satisfied, where the `None` intent was matched, where QnA maker didn't find the right answer) and conversation metrics without breaking GDPR.

**Comment by darrenj** [comment]
Thanks for raising. The LogPersonalInformation flag just disables the utterance (question) and username from being logged. Other events are logged as usual? 

```
// Use the LogPersonalInformation flag to toggle logging PII data, text and user name are common examples
if (LogPersonalInformation)
{
  if (!string.IsNullOrWhiteSpace(text))
  {
      telemetryProperties.Add(QnATelemetryConstants.OriginalQuestionProperty, text);
  }

  if (!string.IsNullOrWhiteSpace(userName))
  {
      telemetryProperties.Add(QnATelemetryConstants.UsernameProperty, userName);
  }
}
```

**Comment by darrenj** [comment]
@hansmbakker Did that help?

**Comment by hansmbakker** [comment]
@darrenj well I meant that I already understand I can switch off logging of PII by removing `TraceEvent` calls or setting `LogPersonalInformation`.

The issue is that I'm looking for guidance from the Bot Template how to properly log information that we still need for QA purposes (users giving feedback, logging utterances that are unknown to the bot etc).

According to an admin in my IT department, information stored in Application Insights flows onwards to Log Analytics which might then be read by operations admins (who, from a role point of view, should not read the messages that the users have written). Is this correct?

Technically I understand that admins who do enough effort will still be able to get access to e.g. Cosmos DB, but then at least that won't be part of the other logs. Only people we put in the editors should read theses contents.

I can build some feedback logging in e.g. Cosmos DB, but that defeats the whole point of the Enterprise Bot Template having a nice out-of-the-box dashboard in PowerBI that I can use only to a limited extent.

So: looking for guidance and/or implementation of analytics + feedback solution that does not let messages end up in the logs for the operations department.

**Comment by darrenj** [comment]
If you moved to CosmosDB you'd have the same situation too, an operations admin could access.?

Looks like there is pretty flexible RBAC controls in Log Analytics? https://docs.microsoft.com/en-us/azure/azure-monitor/platform/manage-access

**Comment by darrenj** [comment]
Does the above RBAC controls help with your scenario?

**Comment by hansmbakker** [comment]
> If you moved to CosmosDB you'd have the same situation too, an operations admin could access.?

I agree, but according to a person in our IT dept the logs from Application Insights flow automatically into their operations monitoring solution (Log Analytics) and it would become part of what they see by default (which shouldn't be the case).

I'm still trying to figure out whether that fear is actually justified.

**Comment by darrenj** [comment]
Understood, let us know. There are controls on log analytics which appear to help with that but would be good to get validation.

Sent from my 📱
________________________________
