### ISSUE TITLE
Enhance Bot.Solutions with a speech-focused library to provide SSML formatted responses

### ISSUE THREAD

**Issue by ryanisgrig** [microsoft/botframework-solutions#1013]
**Is your feature request related to a problem? Please describe.**

Currently speak properties are populated with a series of dashes and periods to emphasize breaks, but this is not standardized. Each Skill uses their own logic for reading out lists which will make a conversational experience inconsistent to users and difficult to maintain for developers

**Describe the solution you'd like**

Use SSML as described in Speech Synthesis Markup Language (SSML) for [Speech Service](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/speech-synthesis-markup) and [W3C](https://www.w3.org/TR/2009/REC-speech-synthesis-20090303/) . These will be available in some helper functions in the Microsoft.Bot.Solutions project to enable easy use by Skills dependent on this solution.

For the Speech channel, the expectation is to use the top-level Speak property on an incoming Activity. Skills may pass an Activity, card Attachments, or a list of Prompt Options. The returned formatted string will be set or appended to the parent Activity's speak property.

#### Scenario: When reading out an Activity & it's list of card attachments, add appropriate pauses between items. Provide methods that implement the best practices for reading out lists.
|Current implementation|New implementation|
|-|-|
|`I found the following options., 1 - Starbucks., 2 - Contoso., 3 - Anchorhead.`|`I found the following options. The first option is Starbucks. The second option is Contoso. The third option is Anchorhead.`|

_Will investigate but this may not even need added breaks if we replace the number with a formatted string._

* Provide guidance for complex list readout where options should be presented like _"The first option is [option], do you want to select this ? If you want to hear the next option, please say next."_. This applies to current Skill's implementations when `readSize=1`.
* If readSize is not provided
    * listSize <= 4, readSize = listSize.
    * listSize > 4, readSize = 4.

#### Potential Scenario: Convert bolded text to a strong emphasis
|Current implementation|New implementation|
|-|-|
|`Hi, I'm **your** Virtual Assistant`|`Hi, I'm <emphasis level="strong">your</emphasis> Virtual Assistant`|

**Comment by ryanisgrig** [comment]
@Quirinevwm @rng do you have any opinions on how we should read ordinals out to a user? For example:

|Read all ordinals|
|-|
|The first is A. The option is B. The third is C. The fourth is D.|

|Highlight last option|
|-|
|The first is A. The second is B. The third is C. The last is D.|

We are tracking a known issue at Microsoft/botbuilder-dotnet#1477 where bots don't recognize when a user says "the last one," but after that's cleared we can set the right expectations with this experience.

**Comment by Quirinevwm** [comment]
@ryanlengel it differs a bit per scenario, but I would recommend to go for highlight last option on a page. Exception is for task list, users have an order in their mind and think more like a list in that.
