### ISSUE TITLE
[Enterprise Bot Template][TS] - Provide similar documentation for TypeScript template like C# version

### ISSUE THREAD

**Issue by awaemmanuel** [microsoft/botframework-solutions#1018]
**Is your feature request related to a problem? Please describe.**

The TypeScript enterprise bot template is lacking in documentation. It'll be frustrating for people new to TypeScript to use and deploy. 

**Describe the solution you'd like**

Documentation should follow the C# pattern in documentation. The C# template is well documented both on GitHub and [azure documentation](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-enterprise-template-getting-started?view=azure-bot-service-4.0)

**Describe alternatives you've considered**

Alternate solution now is to try and extrapolate knowledge from deploying C# templates and deploying other NodeJS/Typescript projects. 

**Additional context**

**Comment by Batta32** [comment]
Hi @awaemmanuel! Thank you for collaborating.
We noticed this kind of documentation inconsistency between TypeScript and C# for `Enterprise Bot Template`. In order to reduce it, we are working on having a robust parity between them.

**Comment by Batta32** [comment]
Hi @awaemmanuel! Thank you for collaborating.
As you can see in `AI\templates\Enterprise-Template\src\typescript` exists two folders.
One for a sample of an enterprise bot generated with the `generator-botbuilder-enterprise` and another for the generator itself.
Inside of the `enterprise-bot` folder you can find a [README](https://github.com/Microsoft/AI/blob/master/templates/Enterprise-Template/src/typescript/enterprise-bot/README.md) that contains the steps to use and deploy the bot.
Also, in the `generator-botbuilder-enterprise/generators/app` folder you can find a [README](https://github.com/Microsoft/AI/blob/master/templates/Enterprise-Template/src/typescript/generator-botbuilder-enterprise/generators/app/README.md) with the next steps to use the generated bot.
