### ISSUE TITLE
Store the skill's user state in seperate Cosmos DB collection

### ISSUE THREAD

**Issue by smallangi** [microsoft/botframework-solutions#1027]
Bot does store state info in Cosmos DB. This does not get deleted automatically. There are three types of state. Dialog, skill and User state. User state needs to be alive until the user exists in VA world, where as Dialog and Skill state can be deleted after the conversation is over. 

So we plan to delete Dialog and Skill state from Cosmos DB on regular basis to keep the cost lower. 
There is an OOTB option In Cosmos DB to delete the Bot State Item in a Collection after a certain period. But this will apply for each and every item in that collection. Currently User State gets stored in the same collection where Dialog and Skill state is being stored. It makes sense to store User state in seperate collection, which will help us delete Dialog and Skill state easily, which will help keep the cost lower. 
Also note that there is also an issue with Cosmos DB Collection that is created by Bot Framework(it creates Fixed type collection , which means it can only store 10GB data). 

so the ask is to store the User State in seperate collection than where Dialog and Skill state is being stored. Currently Todo skill seems to store user state.

**Comment by lauren-mills** [comment]
This is easily customized in your startup.cs class. When you initialize your user state, simply provide a different collection name. 

```
           var cosmosDbService = botConfig.Services.FirstOrDefault(s => s.Type == ServiceTypes.CosmosDB) ?? throw new Exception("Please configure your CosmosDb service in your .bot file.");
            var cosmosDb = cosmosDbService as CosmosDbService;
            var cosmosOptions = new CosmosDbStorageOptions()
            {
                CosmosDBEndpoint = new Uri(cosmosDb.Endpoint),
                AuthKey = cosmosDb.Key,
                CollectionId = "YOUR_USER_STATE_COLLECTION",
                DatabaseId = cosmosDb.Database,
            };
            var dataStore = new CosmosDbStorage(cosmosOptions);
            var userState = new UserState(dataStore);
```
