### ISSUE TITLE
Email Skill doesn't show read messages

### ISSUE THREAD

**Issue by darrenj** [microsoft/botframework-solutions#1044]
## Project

Skills

**Language**: C#

## Description
Email Skill doesn't show read messages, instead only unread messages are shown.

## To Reproduce
Mark all messages in your inbox as read and ask for emails

## Expected behavior
This behaviour should be configurable as part of a Skill, in the same way as displaySize.

## Additional context
#1001

**Comment by DingmaomaoBJTU** [comment]
Currently this behavior is asked by PM. If you want to check all read emails, you can say "show all emails". Is this OK for you or do we still need a config?

**Comment by darrenj** [comment]
Show all emails - great. Can we get that added to the skill docs please?

**Comment by DingmaomaoBJTU** [comment]
Sure~~ Will do that~
