### ISSUE TITLE
[VA] Build error because of encoding issue

### ISSUE THREAD

**Issue by angie4u** [microsoft/botframework-solutions#1059]
## Project

**Name**: Virtual Assistant

**Language**:  C#

## Description
After I download and build the latest source code, there is one build error because of the encoding issue.
Is this because of my locale setting somewhere in my Visual Studio? 

## To Reproduce
Download the latest repo and build the code using VS.

## Expected behavior
No build error

## Screenshots
![image](https://user-images.githubusercontent.com/16282358/55600578-91d75f80-5797-11e9-84a1-1fc926331619.png)
![image](https://user-images.githubusercontent.com/16282358/55600598-a7e52000-5797-11e9-9ca5-08f889df31ec.png)

## How to fix the issue
Change the source code by referencing this code: https://github.com/Microsoft/AI/blob/master/solutions/Virtual-Assistant/src/csharp/skills/automotiveskill/automotiveskilltest/Flow/VehicleSettingsTests.cs#L31
![image](https://user-images.githubusercontent.com/16282358/55600670-027e7c00-5798-11e9-9a7f-60b04845d0ef.png)

**Comment by darrenj** [comment]
Hi Angie,

Having problems reporting this, can you confirm the OS your using and region/language settings please?

**Comment by angie4u** [comment]
Hello Darren,

My OS version is like below and my language setting is ko-kr.
If you need more information, please let me know!

[cid:image002.png@01D4FE11.C8325D30]

Best Regards,
Eunji Kim


________________________________
보낸 사람: Darren Jefford <notifications@github.com>
보낸 날짜: Thursday, April 25, 2019 3:48:56 PM
받는 사람: Microsoft/AI
참조: Eunji Kim; Author
제목: Re: [Microsoft/AI] [VA] Build error because of encoding issue (#1059)


Hi Angie,

Having problems reporting this, can you confirm the OS your using and region/language settings please?

**Comment by angie4u** [comment]
I'm updating the image above

![image](https://user-images.githubusercontent.com/16282358/56879086-20d35100-6a92-11e9-805a-8c27b0a702a0.png)

**Comment by darrenj** [comment]
@angie4u Could you let me know if you see the same behavior if you clone the latest from the github repo since the latest release? I checked file encodings and couldn't repro but let me know.

**Comment by angie4u** [comment]
Okay! I will check and let you know if it still has the same issue! ;)

**Comment by angie4u** [comment]
@darrenj I downloaded the lasted release but it seems different from the previous version. Do you mean start VA project using Visual Studio template or is there other way to build project using cloned source code?  
![image](https://user-images.githubusercontent.com/16282358/58003332-8196fc00-7b1b-11e9-8701-a7a9d36e7d93.png)

**Comment by darrenj** [comment]
If you open `skills\src\csharp\Skills.sln` and build - this should enable you to see if you get the same korean encoding issue.

**Comment by darrenj** [comment]
Closing as we can't repro with matching locale settings, feel free to reopen.
