### ISSUE TITLE
Virtual Assistant: When default locale is "zh-cn", welcoming message error

### ISSUE THREAD

**Issue by angie4u** [microsoft/botframework-solutions#1060]
## Project

**Name**: Virtual Assistant,

**Language**: C#

## Description
If default locale is "zh-cn"(Chinese), it will cause welcoming message error and VA is not working properly.

## To Reproduce
Set default locale to zh-cn at settings tab
![image](https://user-images.githubusercontent.com/16282358/55622768-12b84a80-57dc-11e9-951e-8a05adbe05f4.png)

## Expected behavior
This message with chinese version
![image](https://user-images.githubusercontent.com/16282358/55622649-bd7c3900-57db-11e9-9d08-905ece3ded9f.png)

## Screenshots
![image](https://user-images.githubusercontent.com/16282358/55622611-a1789780-57db-11e9-8d5d-c8fcde79c846.png)

## Additional context
I have an customer engagement in China who has a big interest this in automotive scenario. They would like to test this scenario with Chinese.

**Comment by lauren-mills** [comment]
@ryanlengel it looks like we've lost the localized intro cards with the latest changes

**Comment by angie4u** [comment]
Thank you for your support! 👍
