### ISSUE TITLE
Virtual Assistant: include adaptive cards that give users visual feedback for every step in setting up meeting/email and is configurable for customers

### ISSUE THREAD

**Issue by Quirinevwm** [microsoft/botframework-solutions#1089]
## User Story
As ...
I want ...
so that ...

## Acceptance Criteria 
*List your requirements.*
- [ ] ...
- [ ] ...
- [ ] ...

## Resources
*Provide any screenshots or conversation mockups to support your request.*
*Learn how to mock up bot conversations with [.chat files](http://aka.ms/bfchatfile).*

## Notes
*Provide any additional information.*

**Is your feature request related to a problem? Please describe.**
Suggestion is to support the creation of a new meeting or email, by an adaptive card that shows step by step what values are gathered by the user. The showing of the card can be configurable for customers (to turn on/off: when necessary for the chosen channel). The users will be supported with visual feedback in a card per step to give them the confidence VA understood them correctly, not only support via speech. Now VA support only supports the final confirmation of the meeting/email visually. 

From: Insights from research users in productivity in customer domain. Plus visual aid provided by general assistants used on devices other than laptops/channels as skype, such as a smart speakers, home appliances etc. 

**Describe the solution you'd like**
Request simple adaptive card with gathered value per step; string of text. Users will see what VA notes also when it’s incorrect and need to make changes. 

For calendar:
•	Show participants
•	Show subject
•	Show content
•	Show date
•	Show starting time
•	Show duration
•	Show location 
For email:
•	Show recipients
•	Show subject
•	Show message

**Describe alternatives you've considered**

**Additional context**

**Comment by Dewain27** [comment]
@Quirinevwm is this still a valid request as we have redesigned the whole experience?
