### ISSUE TITLE
Virtual Assistant: confusing prompts in calendar and email

### ISSUE THREAD

**Issue by Quirinevwm** [microsoft/botframework-solutions#1090]
## Project

**Name**: 

**Language**: 

## Description
Testing VA results changes to prompts for calendar/email. 

## To Reproduce
Virtual Assistant: prompt updates in calendar/email

Calendar:
•	Current: Alright, I will send an invite to [participant alias], what is the subject of the meeting? Or you can say skip to use the default title.
**Updated (skipping default in prompt):** Alright, I have included [participant alias]; [email], what is the subject of the meeting? 

•	Current: Okay, I will send this to [name participant]: [email]. If this is not the [name participant] you were looking for, let me know.
o	**Yes/No routes wrong**

•	Current: What do you want to add in the meeting details?
**Updated:** What do you want to add as content?

•	Current: The event is on tomorrow from 8 - 8.30 AM.
**Updated:** The event is [tomorrow/date/day], from 8:00 AM till 9:00 AM
	
Email:
•	Current: What is the subject of the email? Or you can input skip to bypass it.
**Updated (skipping default in prompt):** What is the subject of the email?
 
•	Current: Would you like to see your email overview again? You can also ask me to forward, reply, delete this email for you, or show the next/previous page
**Updated:** Want to go back to the email overview? Or you can ask me to complete an action on this email.  

•	Current: Do you want to see the content of the first email? I can show any email for you, just let me know by naming out the subject or from whom.
**Updated**: Want to know the content of the first email? Let me know if you want to know the next or another email.

**Comment by darrenj** [comment]
@Quirinevwm Thanks for this, what might be easier if your willing - is for me to send you some github instructions and pointers to the language files for English so you can quickly/easily can make these changes and review all responses at the same time?

**Comment by Quirinevwm** [comment]
@darrenj yess good idea!
