### ISSUE TITLE
tslint -t vso ./src/**/*.ts   fails  on running 'yo botbuilder-enterprise'

### ISSUE THREAD

**Issue by ankurgupta325** [microsoft/botframework-solutions#1108]
## Project

**Name**: Enterprise Bot Template

**Language**:  TypeScript

## Description

Running 'yo botbuilder-enterprise' fails at below step:   

tslint -t vso ./src/**/*.ts

With this error attached:
[error.txt](https://github.com/Microsoft/AI/files/3084422/error.txt)

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! yee-bot@1.0.0 lint: `tslint -t vso ./src/**/*.ts`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the yee-bot@1.0.0 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

## To Reproduce
run  'yo botbuilder-enterprise'  to create a new enterpris_bot project

## Expected behavior
Error should not be encountered

**Comment by Batta32** [comment]
Hi @ankurgupta325! Thank you for collaborating.
We checked that there are some **TSLint** errors in the solution about `completed-docs` rule, this is a rule that was updated after the `v5.12.1` of **TSLint** which is set in the `package.json` of the `Enterprise Bot Template`.

![image](https://user-images.githubusercontent.com/11904023/56217154-1dbf7600-6039-11e9-85f9-190d7f0f4303.png)

**We will ignore that rule in the TypeScript templates.**
