### ISSUE TITLE
Get User In Email Skill is returning Bad Request

### ISSUE THREAD

**Issue by pvmraghunandan** [microsoft/botframework-solutions#1146]
## Project

**Name**: Email Skill

**Language**: C#

## Description
Get User call in Email Skill Under FindContactDialog ConfirmName Step is throwing Bad Request error message. Below is exception.

Message: The query specified in the URI is not valid. Could not find a property named 'displayName' on type 'Microsoft.Fast.Profile.Web.Models._1._0.Profile'.

URL : https://graph.microsoft.com/v1.0/users?$filter=startswith(displayName,%20'test')%20or%20startswith(givenName,'test')%20or%20startswith(surname,'test')%20or%20startswith(mail,'test')%20or%20startswith(userPrincipalName,'test')

## To Reproduce
Start capturing Fiddler and identify that this call always fails

## Expected behavior
No Errors during execution

**Comment by DingmaomaoBJTU** [comment]
Yes, this is a known issue. This only happens for MSA account and will work for AAD account. MSA account (personal account) doesn't have org users, so it will be expected to get nothing by query user with conditions. Currently as we are hard to distinct MSA account and AAD account, so we just try query catch exception if there is any.

**Comment by DingmaomaoBJTU** [comment]
This issue will not block contact finding scenario. For personal account, user will query by contact list instead of org users. Anyway, we will try to find out whether there will be a better approach to distinct MSA and AAD user.

**Comment by darrenj** [comment]
Thanks for reporting, this is a necessary operation at this time but working with graph team to simplify moving forward.

**Comment by DingmaomaoBJTU** [comment]
Tracked by issue : https://github.com/microsoftgraph/microsoft-graph-docs-contrib/issues/7212
