### ISSUE TITLE
Github - src/csharp/skills/... duplicate directories - very confusing.

### ISSUE THREAD

**Issue by mekinney** [microsoft/botframework-solutions#116]
There are both lower-case and mixed-case directory names for the calender, email, and pointofinterest skills.  I've only been messing with PointOfInterest, but appears git merges the contents of both directories into a single mixed case directory in Windows (no idea what Linux does).

This is very confusing when navigating GitHub to look at the code.

**Comment by darrenj** [comment]
Hi, Thanks. Are you referring to the root Skills directory? ToDo being the odd one out?

![image](https://user-images.githubusercontent.com/33519520/47018697-3bc12200-d14d-11e8-8711-409b9a5fcaeb.png)

**Comment by mekinney** [comment]
Yes. In GitHub it looks like this to me:
<img width="482" alt="virtualgithub" src="https://user-images.githubusercontent.com/7552362/47031530-dfe2a300-d124-11e8-91cc-6ed5fb74600a.PNG">

**Comment by lzc850612** [comment]
I'm fixing this issue with Lauren. It seems we have merged changes into the upper case folders over the last couple of days. I'm applying all the changes from there to the lowercase folders to make sure we have everything in the lowercase version and verify that it works well. Then I'll remove the upper case folders.
