### ISSUE TITLE
[EnterpriseBotTemplate][C#] Why are SetAsync SaveAsync not called in OnboardingDialog to save the UserState?

### ISSUE THREAD

**Issue by hansmbakker** [microsoft/botframework-solutions#1168]
(Not sure whether this is a question or a bug)

The [documentation on user state management](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-v4-state?view=azure-bot-service-4.0&tabs=csharp) instructs to call
 - `SetAsync` on the `IStatePropertyAccessor`
 - `SaveAsync` on the `UserState` object to save the state.

In the Enterprise Bot Template, there is the `OnboardingDialog` which has similar functionality to the sample in the documentation, but [`OnboardingDialog` neither calls `SetAsync` nor `SaveAsync`](https://github.com/Microsoft/AI/blob/master/templates/Enterprise-Template/src/csharp/EnterpriseBotSample/EnterpriseBotSample/Dialogs/Onboarding/OnboardingDialog.cs)

Can you please explain whether `OnboardingDialog` is not implemented completely, or why calling `SetAsync` and `SaveAsync` are not needed here?

**Comment by lauren-mills** [comment]
We use an AutoSaveStateMiddleware that does the saving step for us. As for setting, we get the state object first then assign to it, rather than using setAsync. It’s just another approach.

**Comment by hansmbakker** [comment]
Thank you for the explanation!

**Comment by hansmbakker** [comment]
@lauren-mills in my feedback on the Microsoft Docs about saving state in bot framework, I got the [reply that the bot frameworks developers recommend against using `AutoSaveStateMiddleware`](https://github.com/MicrosoftDocs/bot-docs/issues/1060#issuecomment-487670455). However I did not read such a warning in your comment that says:
> It’s just another approach.

I assumed that Enterprise Bot Template would advocate best practices, and I find myself confused now between your and @JonathanFingold's statement. Is this something you could clear up?

**Comment by lauren-mills** [comment]
As Jonathan stated there is a difference of opinion. This middleware was developed by the Bot Framework SDK team, is valid, and we have seen no issues with it in our usage. We use it because if the developer forgets to save the state manually, the data will not be available, which is confusing. It also clutters up the code to have to set the state manually in each dialog step. 

Regardless, we will not be changing this implementation for the next release. There are some changes to the state system coming from the SDK team, so we will update accordingly once that work is done.

**Comment by hansmbakker** [comment]
@lauren-mills I have not seen issues with it either and the idea behind the middleware (making the bot framework more foolproof to use and making the code cleaner) seems useful, but frankly speaking I would expect a template to build on best practices and [this updated comment by @JonathanFingold](https://github.com/MicrosoftDocs/bot-docs/issues/1060#issuecomment-488125279) says that it is better not to use it.

If you think this issue should be closed, feel free to close it, and at least thank you for commenting on your side of the story.

**Comment by darrenj** [comment]
Quite simply there are two approaches, the approach we have used is **not** invalid and is a supported SDK feature, the only debate is whether the developer understands the mechanism and whether there are situations that state might not be persisted in error conditions confusing a developer.

Conversely your code will then end up littered with code to retrieve/set. This model isn't needed in AspNet for session state so why should it be in a Bot? Simply there are models and this is one we feel is best suited at this time and we work closely with the SDK team to further improve this area.
