### ISSUE TITLE
Code organization: Move deployment scripts and cogntivie models outside of the bot project

### ISSUE THREAD

**Issue by gabog** [microsoft/botframework-solutions#117]
The Enterprise Template and the Virtual Assistant store the LUIS models and the DeploymentScripts in folders that are inside the Virtual Assistant project. Normally, it is nicer to put scripts and other configuration and deployment items in a folder that is not the web app for the bot.

A possible layout would look as follows:

| - Virtual-Assistant
    | - Assistant
->    **| - DevOps
-->        | - DeploymentScripts
->    | - CogntiveModels
-->        | - LUIS
-->        | - QnA**
    | - LinkedAccounts.Web
    | - Skills
        | - CalendarSkill
        | - DemoSkill
        | - EmailSkill
        | - PointofInterestSkill
        | - ToDoSkill
        | - Test
    | - TestHarnesses
        | - Assistant-ConsoleDirectLineSample
        | - Assistant-WebTest
    | - Microsoft.Bot.Solutions
  | - VirtualAssistant.sln

I think this is a cleaner separation of concerns, and allows non dev to work on deployment scripts and cognitive models outside of the source.

The dispatch tool also generates several files and the summary.html file that would be nice to keep outside of the web project for the bot.

**Comment by darrenj** [comment]
We snapped to a common structure across all templates/samples: https://github.com/Microsoft/botbuilder-dotnet/issues/834. Are you purely proposing moving them into a separate project as part of the main solution?

It's improtant to have have the scripts and cognitive models in source control as these are the foundation for deployment. e.g. moving forward the .LUIS models in the deploymentscripts will be removed and generate from LU will occur instead.

Dispatch does generate some files, we shouldn't have them checked in?

**Comment by gabog** [comment]
Hi, I am proposing we move those files into Solution Items (outside the web app csproj file), here is an example of how it would look on the file system:
![image](https://user-images.githubusercontent.com/12264946/47020182-c5112e00-d126-11e8-8df1-6250b9fb4d01.png)

And here is an example in VS:
![image](https://user-images.githubusercontent.com/12264946/47020198-d22e1d00-d126-11e8-913d-eb8ef2478255.png)

The files will be still managed in source control but will not be compiled or deployed as part of csproj.

As for the dispatch tool, I need to understand it a bit better but I think the data folder it generates is just a working folder, it does not need to be checked in (it is like the bin and obj folders). For the dispatch, I think the only files that need to be checked in are the .dispatch file, the generate LUIS model (the json file) and maybe the summary.html. 

Makes a bit more sense?

Thanks

PS: I'll post a seperate issue on this but I've struggled a lot with the dispatch tool and with making it work with relative folders.

**Comment by gabog** [comment]
Hi, it may be easier to talk about this over the phone and it would be nice to think a bit more about the lifecycle for NLP, QnA, DevOps and how to better track the models in source control. 

I definitely think these folders don’t belong inside the bot csproj, they can be a solution folder outside but not in the web project. 

On the CognitiveModels specifically, this is the lifecycle we follow today: 
1.	A dev works on LUIS in the LUIS portal. 
2.	Once he is happy with it, he publishes the model (and potentially breaks other devs environments ☹).
3.	He exports the json to folder in source control (and he normally forgets to do that 😊),
4.	He reruns the dispatcher (and also forgets to export the generated json to source control).
5.	He creates a PR for his code changes (once accepted, things start working for other devs again).

Ideally, I think that: 
1.	A developer (or NLP specialist if there’s such a thing) works on LUIS in the LUIS portal or on QnAMaker on the QnAMaker portal using the dev instance for it (or a private copy so he doesn’t break other devs).
2.	Once he is happy with it, he runs “dispatch refresh” locally and exports the latest models locally (this can be done against the staging version of the models or the dev’s private instances)
3.	Optionally, he runs LUIS Gen to create/update strongly typed classes for the models.
4.	He runs end to end tests (unit tests that hit the LUIS apps) to ensure that the hero utterances still work. 
5.	He creates a PR that contains the updated models and code (if any).
6.	CI builds the source, deploys LUIS or QnAMaker to a staging instance and runs unit and end to end tests.
7.	CD deploys the source to the target environment and promotes the models to Production. 

I am probably missing some steps, don’t know if we have all the APIs to do this and don’t have all the details sorted out but this is the general idea.

Makes sense? 

Thanks
