### ISSUE TITLE
Updated Luis resorce, still not working

### ISSUE THREAD

**Issue by ConnorBehan** [microsoft/botframework-solutions#1172]
## Description
Bot replying "Sorry, it looks like something went wrong.". I have checked my Luis subscription and my free starter key has reached its limit. I have another resource assigned to the Luis app which is F0 meaning 10,000 hits. I have used around 500 of those in the passed 2 days or so. Now, my bot has stopped replying to any messages I send and I can't seem to find out why. 

Any ideas? I have a demo in a couple of days.

**Comment by vagi8** [comment]
Did you find the solution for it. I am also facing the same issue.
