### ISSUE TITLE
Virtual Assistant deploy_bot.ps1 fails with leading hyphen in App Password

### ISSUE THREAD

**Issue by mekinney** [microsoft/botframework-solutions#1173]
## Project
Virtual Assistant

## Description
deploy_bot.ps1 fails when there is a leading hyphen in the app password.  I did not narrow the test to see if it's any underscore or a problem with the underlying utilities.

The reproduce section shows the exact command line (with unique ids truncated).  The expected section shows the exact command line after I generated a new key (with no underscore).

## To Reproduce
The following command line fails:
```
C:\Code\vp-bot\solutions\Virtual-Assistant\src\csharp\assistant>pwsh -ExecutionPolicy Bypass -File DeploymentScripts\deploy_bot.ps1 -appId "2a... Rest of App Id" -appSecret "-1Y... Rest of Password" -luisAuthoringKey "Luis key goes here..." -name "vabot-dev01" -location "westus" -locales "en-us"
Changing to project directory ...
Deploying common resources...
4.3.4
C:\Code\vp-bot\solutions\Virtual-Assistant\src\csharp\assistant\DeploymentScripts\..
Generating en-us General script ...
```

## Expected behavior
This one worked:
```
C:\Code\vp-bot\solutions\Virtual-Assistant\src\csharp\assistant>pwsh -ExecutionPolicy Bypass -File DeploymentScripts\deploy_bot.ps1 -appId "2a Rest of App Id" -appSecret "hP... Rest of Password" -luisAuthoringKey "Luis key goes here..." -name "vabot-dev01" -location "westus" -locales "en-us"
Changing to project directory ...
Deploying common resources...
With msbot 4.3.2 and later, the only AZ CLI prerequisite is having an AZ CLI version >= 2.0.53. If you have the botservice extension installed as well, please remove this via "az extension remove --name botservice".
Checking az botservice version
checking dotnet requirement
Fetching subscription account
The following services will be created by this operation:
 Service                                 Location            SKU                 Resource Group
...
```

**Comment by lauren-mills** [comment]
It looks like a hyphen instead of an underscore in your password. Since hypens have special meaning in PowerShell, they need to be escaped with a  `

**Comment by mekinney** [comment]
Yes, hyphen.  Total brain fart on typing the title.

I didn't realize you had escape hyphens in PS.  Guess this answers the question, because there's no way to fix it so that cutting and pasting secrets works.

**Comment by lauren-mills** [comment]
Another thing that might work is moving the appPassword parameter to the end of the list and adding "--%" before it. This should also escape but it needs to be at the end
