### ISSUE TITLE
Add launchSettings.json to .gitignore

### ISSUE THREAD

**Issue by gabog** [microsoft/botframework-solutions#118]
In a team development launchSettings.json is where devs normally override configuration settings to be able to run the solution locally without having to modify appsettings.json. 

It would be nice to add this file to gitignore to avoid accidently committing changes with local settings and to help devs keep their own configuration local.

This will also help contributors that work on their own branches with their own settings (I normally override the path to the bot file and my local settings in launchSettings.json.

The following line in gitignore should achieve this:
**/Properties/launchSettings.json

**Comment by darrenj** [comment]
We reviewed this change - if we don't have the launchSettings file under source control, it would be generated with a random port which is different from the deployment script which will make developer's local run fail out of the box which is important. We should still keep this file and just be sure to not include it in any changes. You can always add changes on top of it to override any settings locally.****

**Comment by gabog** [comment]
ok
