### ISSUE TITLE
Will Microsoft.Bot.Builder.Solutions nuget package become available from official nuget repository?

### ISSUE THREAD

**Issue by hansmbakker** [microsoft/botframework-solutions#1181]
**Is your feature request related to a problem? Please describe.**
Currently we need to add the myget feed to download `Microsoft.Bot.Builder.Solutions` (according to https://github.com/Microsoft/AI/issues/901)

**Describe the solution you'd like**

Download `Microsoft.Bot.Builder.Solutions` from nuget without having to add myget source

**Describe alternatives you've considered**
Move functionality like the background task functionality to the core Bot Framework nuget packages

**Comment by darrenj** [comment]
It's currently under development hence on myget, plan is to have this and other packages published ready for Build next week.
