### ISSUE TITLE
Email Subject and Calendar Title triggering interruptdialog/help

### ISSUE THREAD

**Issue by darrenj** [microsoft/botframework-solutions#119]
**Description**

E-mail Subject or Message is caught as General.Help Intent and sent to the Help InterrupterDialog. That’s not helpful and the user isn’t coached how to workaround the problem. A user should be able to say near anything and have it end up in the Subject or Message.

Calendar Title or Subject is caught as General.Help Intent and sent to the Help InterrupterDialog. That’s not helpful and the user isn’t coached how to workaround the problem. A user should be able to say near anything and have it end up in the Title or Subject.

**Expected behavior**
In scenarios when "general input" is expected we should override top level interrupts.

**Comment by lauren-mills** [comment]
For now I have disabled the Help interruption in skills until we can design a better context switching/interruption pattern that is more robust.

**Comment by darrenj** [comment]
@gabog We have stopped bubbling "help" down to the skill. Cancel scenarios are still really important to ensure things don't get stuck. We'll take a known issue for now that if you start using cancel in utterances (meeting requests for example) you'll likely trigger the cancel interruption. The Help intent needs some more training work as it was firing too often.

**Comment by lauren-mills** [comment]
This was closed by PR #131
