### ISSUE TITLE
msbot uses the Authoring Key in the Subscription key for the generated file

### ISSUE THREAD

**Issue by gabog** [microsoft/botframework-solutions#120]
The Subscription Key for the LUIS models in the .bot file generated by msbot is set to the authoring key.

msbot generates a LUIS service in azure and it should use this key instead of the authoring key in the bot file.

Also, the msbot tool generates the LUIS apps for the solution but doesn't assign the LUIS subscription key to it (it should for the above to work).

I'm not sure if the existing APIs allow to do any of this but if it doesn't it should be noted in the documentation so people don't use authoring keys for deployed bots.

**Comment by darrenj** [comment]
This is a limitation of the LUIS endpoint today meaning we can't assign this key hence the authoringKey is used which is fine (until your free amount of utterances expires). We are blocked on this waiting for a chance ~November. I'll ensure the documentation is updated

**Comment by gabog** [comment]
Understood, thanks!
