### ISSUE TITLE
PoI skill should detect and warn with a specific exception that the AzureMaps key isn't provided (see main Bot startup)

### ISSUE THREAD

**Issue by darrenj** [microsoft/botframework-solutions#121]
**Description**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by ryanlengel** [comment]
![image](https://user-images.githubusercontent.com/43043272/47112048-0cbcb600-d20a-11e8-9d01-29ee6159090b.png)
The skill catches it when you try to invoke it & returns with a trace error. Should it warn before invoking (on startup)?
