### ISSUE TITLE
Command and scopes in Virtual Assistant docs are not clearly described

### ISSUE THREAD

**Issue by ericchansen** [microsoft/botframework-solutions#1211]
## Project

**Name**: Virtual Assistant

**Language**: C#

## Description

I'm following the instructions in https://github.com/Microsoft/AI/blob/master/docs/virtual-assistant/csharp/gettingstarted.md.

The following is a quote from the documentation.

> * Click API permissions on the left-hand navigation
>   * Select Add Permission to show the permissions pane
>   * Select Microsoft Graph
>   * Select Delegated Permissions and then add each of the following permissions required for the Productivity Skills:
>     * Calendars.ReadWrite
>     * Contacts.Read
>     * Mail.ReadWrite
>     * Mail.Send
>     * Notes.ReadWrite
>     * People.Read
>     * Tasks.ReadWrite
>     * User.ReadBasic.All
>
> Next you need to create the Authentication Connection for your Bot. Ensure you use the same combination of Scopes that you provided in the above command. 

By default, User.Read is also checked. Should we leave this or uncheck it?

Also, the wording, "Ensure you use the same combination of Scopes that you provided in the above command", is confusing. What command? We didn't run a command. We interacted with the Azure Portal GUI to make some changes.

In a following step, we're asked to run

```
az bot authsetting create --resource-group YOUR_BOT_NAME --name YOUR_BOT_NAME --setting-name "YOUR_AUTH_CONNECTION_DISPLAY_NAME" --client-id "YOUR_APPLICATION_ID" --client-secret "YOUR_APPLICATION_PASSWORD" --service Aadv2 --parameters clientId="YOUR_APPLICATION_ID" clientSecret="YOUR_APPLICATION_PASSWORD" tenantId=common --provider-scope-string "Calendars.ReadWrite Mail.ReadWrite Mail.Send Tasks.ReadWrite Notes.ReadWrite People.Read User.ReadBasic.All Contacts.Read" 
```

For the `provider-scope-string`, should we only include the scopes mentioned in the documentation (as shown in the command directly above) or should we add whatever other scopes are also checked in the Azure Portal (ex. User.Read)?

## To Reproduce

Follow along with the documentation in https://github.com/Microsoft/AI/blob/master/docs/virtual-assistant/csharp/gettingstarted.md.

## Expected behavior

I expect clear descriptions of what to do.

## Screenshots

None.

## Additional context

None.

**Comment by darrenj** [comment]
Thanks, our latest release has automated all of this 😎
