### ISSUE TITLE
msbot to create the dispatch file and models

### ISSUE THREAD

**Issue by gabog** [microsoft/botframework-solutions#122]
The msbot tool generates the bot file and actually builds and deploy a dispatch luis app.
It would be nice if it would also generate the initial .dispatch file with all the LUIS models loaded in and also store the generated json for the app in the CognitiveServices folder so it can be committed and tracked in source control.

**Comment by darrenj** [comment]
Little known fact :) You can pass the bot file through a --bot parameter.

> dispatch refresh --bot DarrenVAus.bot --secret YOUR_SECRET

**Comment by gabog** [comment]
I just tried this one and the issue is that dispatch refresh --bot DarrenVAus.bot --secret YOUR_SECRET recreates the dispatch but the top level intents have now YOURBOTFILENAME in the middle and is not the same outcome as running the clone. 
For example.
after running msbot clone, the dispatch has top level intents called l_Mail, l_Calendar, etc.
after running dispatch refresh --bot, the dispatch has top level intents called l_MyBot_Mail, l_MyBot_Calendar etc. and that breaks serialization.

It would be good to have a way of doing a dispatch refresh that generates the same outcome as msbot clone.

**Comment by darrenj** [comment]
Tracked in https://github.com/Microsoft/botbuilder-tools/issues/760

**Comment by tsuwandy** [comment]
Yup, this should be handled by latest Dispatch, to be deployed to npmjs in about an hour or two today.
