### ISSUE TITLE
.bot file deprecated in SDK 4.3, is it still going to be used?

### ISSUE THREAD

**Issue by arafattehsin** [microsoft/botframework-solutions#1229]
I think I should ask this here instead of StackOverflow since it's still under development. 

I have seen the Virtual Assistant code with .bot files. However, as per the latest release SDK 4.3 for Bot Framework, .bot files have been deprecated (though still supported). 

Is it going to be changed here sooner or it will take some time?

Thanks
Arafat

**Comment by darrenj** [comment]
We will be publishing a new Virtual Assistant template (replacing the solution project you see in the repo today) tomorrow!

**Comment by arafattehsin** [comment]
Bingo! Thanks.
