### ISSUE TITLE
[botskills] CLI operation should fail if it can't find LU file

### ISSUE THREAD

**Issue by darrenj** [microsoft/botframework-solutions#1232]
When --luisFolder is passed to the CLI it uses this to find the LU files. If the CLI can't find the required LU file it should terminate the CLI and not progress.  

Right now it continues through the rest of the steps and results in a skill being added but no dispatch intent added for the Skill.

```
dispatch add --type file --name newsSkill --filePath C:\Users\darrenj\source\repos\4.4\skills\src\csharp\experimental\newsskill\Deployment\Resources\LU\news.luis --intentName newsSkill --dataFolder C:\Users\darrenj\source\repos\build\djvabuilddemo2\djvabuilddemo2\djvabuilddemo2\Deployment\Resources\Dispatch\en --dispatch C:\Users\darrenj\source\repos\build\djvabuilddemo2\djvabuilddemo2\djvabuilddemo2\Deployment\Resources\Dispatch\en\djvabuilddemo2en_Dispatch.dispatch
C:\Users\darrenj\source\repos\4.4\skills\src\csharp\experimental\newsskill\Deployment\Resources\LU\news.luis does not exist.  Please check the file path.
```

**Comment by dfavretto** [comment]
Thanks for reporting this issue! We actually have a few more in radar, I'll be creating an issue with a list of all known issues for tracking them, so you are aware of what is being work on.
