### ISSUE TITLE
[botskills] --cs parameter should not be required for list operation

### ISSUE THREAD

**Issue by darrenj** [microsoft/botframework-solutions#1236]
CLI requires `--cs` to be passed even when requesting to list connected skills, this shouldn't be required as this is just a json file check?

**Comment by dfavretto** [comment]
The need for this argument here is for assuming the path to the `skills.json` file. If you run `botskills list --cs` from the root path of your assistant, it will assume the `skills.json` file has that name and is located in the root folder. If you run with `--ts` instead, it will assume the file is located inside the `src` folder in the root folder.

We came up with these 2 options:

1. We could change the behavior to make the `--cs` and `--ts` optional if the path to the `skills.json` is present in the argument `--skillsFile <path>`.

1. Another option would be to disable the automatic assumption of the path to the `skills.json` file, making the `--cs` and `--ts` completely unnecessary in the `botskills list` command and the `--skillsFile <path>` mandatory.

Which option would you prefer?

**Comment by darrenj** [comment]
Ahhh, thanks. Perhaps a hybrid unless you think that's crazy :)  If you do some probing and find skills.json in the current directory or in .\src then you pick that unless your explicitly given a skillsFile path?

**Comment by dfavretto** [comment]
For the `list` command that would be a good approach, so I'll remove the arguments `--cs` and `--ts` and tweak the behavior to use the argument `--skillsFile <path>`, and if it's not provided, try find the `skills.json` in the root or the `./src` folders. If there's no success with any of those two possibilites, an error will be printed in the console to let the user know the path to the `skills.json` should be provided.

**Comment by SiddharthSunchu** [comment]
I'm trying to connect the assistant template with the skill template. I have the services in the assistant and the other configurations set up. 
The Skill has the Manifest file populated and I was able to validate the manifest after it was deployed. 

I have the following error when I try the "botskills connect" command: 

(node:16800) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'find' of undefined
    at Object.connectSkill (C:\Users\User\AppData\Roaming\npm\node_modules\botskills\lib\functionality\connectSkill.js:132:25)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:16800) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:16800) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
