### ISSUE TITLE
[4.4] Deployment script for VSIX shows confusing error message

### ISSUE THREAD

**Issue by lzc850612** [microsoft/botframework-solutions#1254]
## Project

**Name**: Virtual Assistant Template

**Language**: C#

## Description

When the user who's running the deploy.ps1 script hits a service quota error, the actual error that shows when running the script is:
Missing an argument for parameter 'qnaSubscriptionKey'. Specify a parameter of type 'System.String' and try again.

We need to show the proper error message

**Comment by darrenj** [comment]
Fixed with new scripts

**Comment by garypretty** [comment]
@darrenj I have just got this error when using the latest VA template which I downloaded about an hour ago - should this fix be in there already?
