### ISSUE TITLE
Suggestion for Assitant bot skills deployment steps

### ISSUE THREAD

**Issue by jthake** [microsoft/botframework-solutions#1260]
## Project

https://github.com/Microsoft/AI/blob/4.4/docs/tutorials/assistantandskilldeploymentsteps.md

It wasn't clear after installing PowerShell core how you should run it. As doesn't show in the Start Menu after install. I had to launch via File Explorer where it was installed
C:\Program Files\PowerShell\6

Also there is a step to sign into `az login` that the script fails on if not done before. Worth adding as a step first.

**Comment by darrenj** [comment]
Thanks - after install pwsh.exe is your path so Windows+R and pwsh should find it but I'll emphasise that in the docs.

az login is optional for most azure developers as they have already done this and we wanted to keep the instructions as simple as possible. Will review. Thanks!
