### ISSUE TITLE
[TS] Virtual Assistant reports NodeClient argument error

### ISSUE THREAD

**Issue by darrenj** [microsoft/botframework-solutions#1269]
Running the yeoman generator from the npmjs source generates an error.

# Repro:
- npm install -g generator-botbuilder-assistant
- yo botbuilder-assistant

```
? What's the name of your assistant? djtstest6
? What's the description of your assistant? dfdsfds fsfs
? Which languages will your assistant use? (Press <space> to select, <a> to toggle all, <i> to invert selection)Chinese,
 Deutsch, English, French, Italian, Spanish
? Do you want to change the new assistant's location? No
? Looking good. Shall I go ahead and create your new assistant? Yes
```

# Error 

```
> djtstest-6@1.0.0 build C:\d\djtstest-6
> tsc --p tsconfig.json && npm run copy-templates

src/index.ts:91:52 - error TS2345: Argument of type 'NodeClient' is not assignable to parameter of type 'StatePropertyAccessor<SkillContext>'.
  Type 'NodeClient' is missing the following properties from type 'StatePropertyAccessor<SkillContext>': delete, get, set

91         return new SkillDialog(skill, credentials, adapter.telemetryClient, skillContextAccessor, authDialog);
                                                      ~~~~~~~~~~~~~~~~~~~~~~~

Found 1 error.
```

**Comment by levi106** [comment]
The third and fourth parameters seems to be the opposite.

**Comment by Batta32** [comment]
Hi @darrenj and @levi106 ,

We updated the `botbuilder-skill` library in PR #1263 where we introduced some changes on `skillDialog.ts` and in the [constructor](https://github.com/Microsoft/AI/blob/4.4/lib/typescript/botbuilder-skills/src/skillDialog.ts#L30) itself. So the order of the parameters is correct.

In addition to this, the `generator-botbuilder-assistant` has changed the reference of the myget [registry](https://github.com/Microsoft/AI/blob/634a75de169500deb6c2e85975ad54ee2e40fe78/templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/app/templates/customAssistant/_.npmrc#L1).
It seems that it is necessary to publish the new libraries on that `registry` to solve that problem.

**Comment by levi106** [comment]
Thanks @Batta32,
My package.json was referring to version 4.3.4 of botbuilder-skills.
Isn't it necessary to update [this file](https://github.com/Microsoft/AI/blob/master/templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/app/templates/customAssistant/_package.json#L33)?

**Comment by Batta32** [comment]
It is not necessary to update the file, because the version of the libraries has not been changed. When the publish of the new libraries is finished, you should re-run `npm install` and `npm run build` in order to update your botbuilder dependencies to the new ones with the latest changes.

**Comment by levi106** [comment]
Do you mean that the latest package version is not 4.4.3 but 4.3.4?
I think it is appropriate to update version if there is any change in the library.

**Comment by darrenj** [comment]
@levi106  there will be a chance next week to snap to 4.4.3 (which only got deployed late last night). @Batta32 we did do a build after the PR was merged?

**Comment by darrenj** [comment]
We have a new build out on myget and see the same error. constructor arguments seem fine and it's just that the botbuilder-skills solution is out of sequence.

I updated package.json in my generated solution to the following

```
"botbuilder-skills": "4.4.3",
"botbuilder-solutions": "4.4.3",
```

And then hit the following which is as expected as the registry isn't registered (I can only do one at a time). When we publish these bits to myget that should resolve I think based on our conversation last week and hopefully you can add this in so the user doesn't have to specify? if so - registry is https://botbuilder.myget.org/gallery/experimental

```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://botbuilder.myget.org/F/aitemplates/npm/microsoft-bot-protocol
npm ERR! 404
npm ERR! 404  'microsoft-bot-protocol@^0.0.2' is not in the npm registry.
npm ERR! 404 Your package name is not valid, because
npm ERR! 404  1. name can only contain URL-friendly characters
npm ERR! 404 It was specified as a dependency of 'botbuilder-skills'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```
