### ISSUE TITLE
Unnecessary ',' is contained in the npm command.

### ISSUE THREAD

**Issue by levi106** [microsoft/botframework-solutions#1274]
## Project

**Name**: Virtual Assistant 

**Language**: TypeScript 

## Description

[Quickstart: Create your first Virtual Assistant (TypeScript)](https://github.com/Microsoft/AI/blob/master/docs/tutorials/typescript/virtualassistant.md#download-and-install) - Download and install 

Running step 3 will result in an error.

## To Reproduce

```cmd
C:\>npm install -g botdispatch, ludown, luis-apis, qnamaker, luisgen
npm ERR! code EINVALIDTAGNAME
npm ERR! Invalid tag name "botdispatch,": Tags may not have any characters that encodeURIComponent encodes.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\hiroyha.FAREAST\AppData\Roaming\npm-cache\_logs\2019-05-04T16_13_42_709Z-debug.log
```

## Expected behavior

The correct command is the following:

```cmd
npm install -g botdispatch ludown luis-apis qnamaker luisgen
```

**Comment by darrenj** [comment]
thanks!
