### ISSUE TITLE
Enterprise Template Documentation Bug - Main Documentation link is broken

### ISSUE THREAD

**Issue by mekinney** [microsoft/botframework-solutions#1303]
Enterprise Template

https://github.com/microsoft/AI/tree/master/templates/Enterprise-Template

Main Documention link under Get Started is broken.

The link in the readme.md is also broken:
https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-enterprise-template-getting-started?view=azure-bot-service-4.0

**Comment by darrenj** [comment]
Enterprise Template is deprecated in favour of the Virtual Assistant template (which itself is an update Enterprise Template). https://github.com/microsoft/AI/wiki/What's-new-at-Build-2019
