### ISSUE TITLE
Error with name and resourceGroup arguments in deploy.ps1

### ISSUE THREAD

**Issue by ericchansen** [microsoft/botframework-solutions#1308]
## Project

**Name**: Virtual Assistant

**Language**: C#

## Description

Arguments `name` and `resourceGroup` for `deploy.ps1` don't function as [documented](https://github.com/microsoft/AI/blob/master/docs/tutorials/assistantandskilldeploymentsteps.md).

Parameter | Description | Required
--------- | ----------- | --------
`name` | **Unique** name for your bot. By default this name will be used as the base name for all your Azure Resources and must be unique across Azure so ensure you prefix with something unique and **not** *MyAssistant* | **Yes**
`resourceGroup` | Name of the Azure Resource Group. Default value is name parameter. | No

## To Reproduce

```
.\Deployment\Scripts\deploy.ps1 -name "this-should-be-the-prefix-of-resources" -location "westus" -luisAuthoringKey "xxx" -luisAuthoringRegion "westus" -resourceGroup "this-should-be-the-resource-group" -appId "xxx" -appPassword "xxx"
```

This will create the resource group named "this-should-be-the-prefix-of-resources". It will also create a resource group named "this-should-be-the-resource-group" and the prefix of the resources will be "this-should-be-the-resource-group".

## Expected behavior

The behavior should match the documentation described [here](https://github.com/microsoft/AI/blob/master/docs/tutorials/assistantandskilldeploymentsteps.md) (and quoted above).

## Screenshots

None.

## Additional context

How should one best build a solution based off of this repo where they can continually receive upstream commits? I don't like using templates because you loose that option. I'm currently using a subtree (method described [here](https://stackoverflow.com/questions/24577084/forking-a-sub-directory-of-a-repository-on-github-and-making-it-part-of-my-own-r?noredirect=1&lq=1)) based off the virtual assistant [sample directory](https://github.com/microsoft/AI/tree/master/templates/Virtual-Assistant-Template/csharp/Sample).

**Comment by lauren-mills** [comment]
Thanks for reporting this, @ericchansen!

**Comment by ericchansen** [comment]
@lauren-mills It's my job. :smile:

Changing the resource group creation is quite simple ericchansen/AI@e13e581611554482c1ae1f17ac4d790eede6fc49.

The naming of the resources is done using the ARM template. I'm not sure if you can modify the ARM template JSON to reference a PowerShell variable. Might have to have deploy.ps1 rewrite the ARM template depending on what the user provides for $name. Anyway, I haven't had time to code something up. Thanks for looking into it!

**Comment by darrenj** [comment]
If you pull down the deploy script from the repo to update your project you should be good to go now..

**Comment by ericchansen** [comment]
@darrenj Apologies for my ignorance, but what's the standard practice for pulling new commits when using a project template (as suggested in the docs)? It seems hard to believe that anyone would want to manually update their code base with each upstream commit.

Then again, I might just be ignorant of how templates work. :smile:
