### ISSUE TITLE
Not able to access skill after it is published

### ISSUE THREAD

**Issue by aishwaryaumachandran** [microsoft/botframework-solutions#1309]
## Project

**Name**:  Skills 

**Language**: C# 

## Description
 The published skill returns an error stating "Unable to connect to the remote server".

## To Reproduce
 Run the base Skill template and connect it to the assistant template. Publish both and enter the utterance "demo dialog" 

## Expected behavior
 Must call the Sample dialog 

## Additional context
 When the assistant and the skill are running locally, the issue does not persists.

**Comment by lzc850612** [comment]
When you debug your local running Skill, can you turn on the exception in exception settings
![image](https://user-images.githubusercontent.com/4001684/57331940-9e204680-70ce-11e9-9e7b-86c182ff48fa.png)

i want to see the stack trace of the exception.

Thanks.

**Comment by aishwaryaumachandran** [comment]
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request starting HTTP/1.1 GET http://localhost:3978/api/skill/messages  
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker:Information: Route matched with {action = "SkillMessageWebSocket", controller = "Bot"}. Executing action SkillSample.Controllers.BotController.SkillMessageWebSocket (SkillSample)
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker:Information: Executing action method SkillSample.Controllers.BotController.SkillMessageWebSocket (SkillSample) - Validation state: Valid
Application Insights Telemetry: {"name":"Microsoft.ApplicationInsights.ce81f1cb9b37468285fc327fa89e6fde.Message","time":"2019-05-08T13:45:57.9469909Z","iKey":"ce81f1cb-9b37-4682-85fc-327fa89e6fde","tags":{"ai.cloud.roleInstance":"W10LT-R90GL0JF","ai.internal.sdkVersion":"dotnet:2.8.1-22898"},"data":{"baseType":"MessageData","baseData":{"ver":2,"message":"Starting listening on websocket","severityLevel":"Information"}}}
Application Insights Telemetry: {"name":"Microsoft.ApplicationInsights.ce81f1cb9b37468285fc327fa89e6fde.Event","time":"2019-05-08T13:45:57.9864325Z","iKey":"ce81f1cb-9b37-4682-85fc-327fa89e6fde","tags":{"ai.cloud.roleInstance":"W10LT-R90GL0JF","ai.internal.sdkVersion":"dotnet:2.8.1-22898"},"data":{"baseType":"EventData","baseData":{"ver":2,"name":"BotMessageReceived","properties":{"recipientId":"122","fromId":"5dd16aa5-77e7-49cb-949f-e889e82de04f","fromName":"User","recipientName":"Bot"}}}}
Application Insights Telemetry: {"name":"Microsoft.ApplicationInsights.ce81f1cb9b37468285fc327fa89e6fde.Event","time":"2019-05-08T13:45:58.3153167Z","iKey":"ce81f1cb-9b37-4682-85fc-327fa89e6fde","tags":{"ai.cloud.roleInstance":"W10LT-R90GL0JF","ai.internal.sdkVersion":"dotnet:2.8.1-22898"},"data":{"baseType":"EventData","baseData":{"ver":2,"name":"SkillWebSocketProcessRequestLatency","measurements":{"Latency":329}}}}
SkillSample Error: 0 : Transcript logActivity failed with System.AggregateException: One or more errors occurred. (Value cannot be null.
Parameter name: stringToEscape) ---> System.ArgumentNullException: Value cannot be null.
Parameter name: stringToEscape
   at System.Uri.EscapeDataString(String stringToEscape)
   at Microsoft.Bot.Builder.Azure.AzureBlobTranscriptStore.GetBlobName(IActivity activity) in d:\a\1\s\libraries\Microsoft.Bot.Builder.Azure\AzureBlobTranscriptStore.cs:line 287
   at Microsoft.Bot.Builder.Azure.AzureBlobTranscriptStore.LogActivityAsync(IActivity activity) in d:\a\1\s\libraries\Microsoft.Bot.Builder.Azure\AzureBlobTranscriptStore.cs:line 88
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.TranscriptLoggerMiddleware.<>c.<OnTurnAsync>b__3_3(Task task) in d:\a\1\s\libraries\Microsoft.Bot.Builder\TranscriptLoggerMiddleware.cs:line 122
---> (Inner Exception #0) System.ArgumentNullException: Value cannot be null.
Parameter name: stringToEscape
   at System.Uri.EscapeDataString(String stringToEscape)
   at Microsoft.Bot.Builder.Azure.AzureBlobTranscriptStore.GetBlobName(IActivity activity) in d:\a\1\s\libraries\Microsoft.Bot.Builder.Azure\AzureBlobTranscriptStore.cs:line 287
   at Microsoft.Bot.Builder.Azure.AzureBlobTranscriptStore.LogActivityAsync(IActivity activity) in d:\a\1\s\libraries\Microsoft.Bot.Builder.Azure\AzureBlobTranscriptStore.cs:line 88<---

Application Insights Telemetry: {"name":"Microsoft.ApplicationInsights.ce81f1cb9b37468285fc327fa89e6fde.Event","time":"2019-05-08T13:45:58.3628032Z","iKey":"ce81f1cb-9b37-4682-85fc-327fa89e6fde","tags":{"ai.cloud.roleInstance":"W10LT-R90GL0JF","ai.internal.sdkVersion":"dotnet:2.8.1-22898"},"data":{"baseType":"EventData","baseData":{"ver":2,"name":"BotMessageReceived","properties":{"recipientId":"122","fromId":"5dd16aa5-77e7-49cb-949f-e889e82de04f","fromName":"User","recipientName":"Bot","text":"sample dialog"}}}}
Application Insights Telemetry: {"name":"Microsoft.ApplicationInsights.ce81f1cb9b37468285fc327fa89e6fde.Event","time":"2019-05-08T13:45:58.6861003Z","iKey":"ce81f1cb-9b37-4682-85fc-327fa89e6fde","tags":{"ai.cloud.roleInstance":"W10LT-R90GL0JF","ai.internal.sdkVersion":"dotnet:2.8.1-22898"},"data":{"baseType":"EventData","baseData":{"ver":2,"name":"BotMessageSend","properties":{"recipientId":"5dd16aa5-77e7-49cb-949f-e889e82de04f","recipientName":"User","replyActivityId":"9b111860-7197-11e9-abe7-a7115e7a909d"}}}}
Application Insights Telemetry: {"name":"Microsoft.ApplicationInsights.ce81f1cb9b37468285fc327fa89e6fde.Event","time":"2019-05-08T13:45:58.9978065Z","iKey":"ce81f1cb-9b37-4682-85fc-327fa89e6fde","tags":{"ai.cloud.roleInstance":"W10LT-R90GL0JF","ai.internal.sdkVersion":"dotnet:2.8.1-22898"},"data":{"baseType":"EventData","baseData":{"ver":2,"name":"BotMessageSend","properties":{"recipientId":"5dd16aa5-77e7-49cb-949f-e889e82de04f","recipientName":"User","replyActivityId":"9b111860-7197-11e9-abe7-a7115e7a909d"}}}}
Application Insights Telemetry: {"name":"Microsoft.ApplicationInsights.ce81f1cb9b37468285fc327fa89e6fde.Event","time":"2019-05-08T13:45:59.2460737Z","iKey":"ce81f1cb-9b37-4682-85fc-327fa89e6fde","tags":{"ai.cloud.roleInstance":"W10LT-R90GL0JF","ai.internal.sdkVersion":"dotnet:2.8.1-22898"},"data":{"baseType":"EventData","baseData":{"ver":2,"name":"BotMessageSend","properties":{"recipientId":"5dd16aa5-77e7-49cb-949f-e889e82de04f","recipientName":"User","replyActivityId":"9b111860-7197-11e9-abe7-a7115e7a909d"}}}}
Application Insights Telemetry: {"name":"Microsoft.ApplicationInsights.ce81f1cb9b37468285fc327fa89e6fde.Event","time":"2019-05-08T13:45:59.2526033Z","iKey":"ce81f1cb-9b37-4682-85fc-327fa89e6fde","tags":{"ai.cloud.roleInstance":"W10LT-R90GL0JF","ai.internal.sdkVersion":"dotnet:2.8.1-22898"},"data":{"baseType":"EventData","baseData":{"ver":2,"name":"WaterfallStart","properties":{"DialogId":"SampleDialog","InstanceId":"a6e57201-39bf-49a5-900f-6b6c9795a946"}}}}
Application Insights Telemetry: {"name":"Microsoft.ApplicationInsights.ce81f1cb9b37468285fc327fa89e6fde.Event","time":"2019-05-08T13:45:59.2577794Z","iKey":"ce81f1cb-9b37-4682-85fc-327fa89e6fde","tags":{"ai.cloud.roleInstance":"W10LT-R90GL0JF","ai.internal.sdkVersion":"dotnet:2.8.1-22898"},"data":{"baseType":"EventData","baseData":{"ver":2,"name":"WaterfallStep","properties":{"DialogId":"SampleDialog","StepName":"PromptForName","InstanceId":"a6e57201-39bf-49a5-900f-6b6c9795a946"}}}}
Application Insights Telemetry: {"name":"Microsoft.ApplicationInsights.ce81f1cb9b37468285fc327fa89e6fde.Event","time":"2019-05-08T13:45:59.2961904Z","iKey":"ce81f1cb-9b37-4682-85fc-327fa89e6fde","tags":{"ai.cloud.roleInstance":"W10LT-R90GL0JF","ai.internal.sdkVersion":"dotnet:2.8.1-22898"},"data":{"baseType":"EventData","baseData":{"ver":2,"name":"BotMessageSend","properties":{"speak":"What is your name?","recipientId":"5dd16aa5-77e7-49cb-949f-e889e82de04f","recipientName":"User","replyActivityId":"9b111860-7197-11e9-abe7-a7115e7a909d","text":"What is your name?"}}}}
Application Insights Telemetry: {"name":"Microsoft.ApplicationInsights.ce81f1cb9b37468285fc327fa89e6fde.Event","time":"2019-05-08T13:45:59.6779994Z","iKey":"ce81f1cb-9b37-4682-85fc-327fa89e6fde","tags":{"ai.cloud.roleInstance":"W10LT-R90GL0JF","ai.internal.sdkVersion":"dotnet:2.8.1-22898"},"data":{"baseType":"EventData","baseData":{"ver":2,"name":"SkillWebSocketProcessRequestLatency","measurements":{"Latency":1649}}}}
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker:Information: Executed action method SkillSample.Controllers.BotController.SkillMessageWebSocket (SkillSample), returned result Microsoft.AspNetCore.Mvc.EmptyResult in 1750.1078ms.
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker:Information: Executed action SkillSample.Controllers.BotController.SkillMessageWebSocket (SkillSample) in 1812.7901ms
Application Insights Telemetry: {"name":"Microsoft.ApplicationInsights.ce81f1cb9b37468285fc327fa89e6fde.Event","time":"2019-05-08T13:45:59.7027592Z","iKey":"ce81f1cb-9b37-4682-85fc-327fa89e6fde","tags":{"ai.cloud.roleInstance":"W10LT-R90GL0JF","ai.internal.sdkVersion":"dotnet:2.8.1-22898"},"data":{"baseType":"EventData","baseData":{"ver":2,"name":"SkillWebSocketOpenCloseLatency","measurements":{"Latency":1746}}}}
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request finished in 1832.328ms 101 
The thread 0x244 has exited with code 0 (0x0).

**Comment by lzc850612** [comment]
What is the content in your Skill's appsettings.json file? Seems like you're probably missing a configuration section like this:
	"blobStorage": {
		"connectionString": "xxxxxxxx",
		"container": "transcripts"
	},

Have you followed the documentation specifically the step for deployment of the skill: https://github.com/microsoft/AI/blob/master/docs/tutorials/assistantandskilldeploymentsteps.md ? it should help you provision the resource (blob storage) and setup the appsettings.json with the proper stuff.

**Comment by aishwaryaumachandran** [comment]
Yes. I have the blobStorage details configured in the app settings

**Comment by darrenj** [comment]
Thanks - can you confirm it's present on both the calling bot and skill side please?

**Comment by darrenj** [comment]
Just re-read the symptoms, this issue only occurs when you have the bot and skill published to azure? We don't publish to azure on your behalf through our scripts, did you publish through visual studio (or similar)?

**Comment by aishwaryaumachandran** [comment]
The issue is resolved. 
The Web sockets had to be enabled on the app service configuration and it worked.

**Comment by darrenj** [comment]
Thanks for letting us know. We did include "enable websockets" in the deployment script for Skill. Did you use an existing app-service when deploying or run the deploy.ps1 script in the skill folder? (Just checking we don't have an issue on the deployment side)

**Comment by aishwaryaumachandran** [comment]
I had published to an existing app service through visual studio
