### ISSUE TITLE
Use Event Hub Model instead of AzureBlobTranscriptStore

### ISSUE THREAD

**Issue by EricDahlvang** [microsoft/botframework-solutions#1316]
AzureBlobTranscriptStore has issues.

https://github.com/microsoft/AI/search?q=AzureBlobTranscriptStore&unscoped_q=AzureBlobTranscriptStore

Event Hubs examples:
csharp: https://github.com/microsoft/BotBuilder-Samples/pull/1353

node: https://github.com/microsoft/BotBuilder-Samples/pull/1379

**Comment by lauren-mills** [comment]
Hi @ericdahlvang can you point us to more details on the issues with using Azure Blob for transcript storage? Event hubs seems like an odd choice for me unless its merely a transport mechanism for storing the transcripts in Azure Storage. Does this approach include using stream analytics?

**Comment by lauren-mills** [comment]
Ideally we can keep the cost of getting up and running to a minimum. I'd also like to consider storing transcripts in CosmosDB as an array of all the activities, since we're already using it for state

**Comment by EricDahlvang** [comment]
Hey @lauren-mills,

The suggestion to use Event Hubs is from the SDK team @cleemullins 

If the VA Template is never retrieving the transcripts, it might not be necessary to use an [ITranscriptStore](https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder/ITranscriptStore.cs)

As you suggest, a CosmosDb [ITranscriptLogger](https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder/ITranscriptLogger.cs) implementation might be sufficient.  Here is one easy way to implement a CosmosDb ITranscriptLogger: https://stackoverflow.com/a/56029167/86646
