### ISSUE TITLE
LUIS file do not get generated for skills

### ISSUE THREAD

**Issue by rexdekoning** [microsoft/botframework-solutions#1328]
## Project

**Name**: Skills

**Language**: C#

## Description
When deploying the email and calender skills using the deployment powershell script. The email.lu and calender.lu files need to be parsed to .luis files. When running the script the command ludown parse toluis etc is called but it it just returns:
undefined
Stop processing

## To Reproduce
Call the deployscript are manually run ludown with the correct parameters

## Expected behavior
.luis file to be generated

**Comment by darrenj** [comment]
We spotted an issue with the latest luisgen tool. Can you run 
```
npm install -g ludown@1.2.0
```
and try again please?

**Comment by rexdekoning** [comment]
Hi Darren, 

Thanks for your reply. Using ludown 1.2.0 the email.lu > email.luis gets parsed correctly.
