### ISSUE TITLE
P0: Demo environment for partners

### ISSUE THREAD

**Issue by ryanisgrig** [microsoft/botframework-solutions#133]
Set up a demo environment for partners to test without needing to download the source code themselves.

- [x] Deploy environment
- [x] Create shortcut at https://aka.ms/bfvirtualassistant
- [x] Authentication - using MSA
- [x] Continuous integration
- [x] Web Test & Linked Accounts - https://aka.ms/bfvirtualassistant

**Comment by ryanlengel** [comment]
Auth issues resolved & both web apps deployed
