### ISSUE TITLE
Incorrect documentation to edit cognitive models

### ISSUE THREAD

**Issue by bgawale** [microsoft/botframework-solutions#1343]
## Project

**Name**: Virtual Assistant

**Language**: C#

## Description
Documentation to integrate addition QnA (link below, refer step 3 under heading Edit your cognitive models) does not seem to be inline with solution structure of latest virtual assistant template as the solution does not contain any Shared directory under Dialogs folder. Also step 4 seems incorrect because latest solution structure does not have MainDialog.cs under Main directory. https://github.com/microsoft/AI/blob/master/docs/tutorials/csharp/customizeassistant.md#edit-your-cognitive-models

## Expected behavior
Step needs to be updated so that additional QnA KB can be easily integrated with given virtual assistant template

**Comment by bhushang19** [comment]
Note that even if you try to build the .bot file manually from cognitiveServices.json and try to follow steps, it works partially and ends up generating new Dispatch instead of amending existing one.

**Comment by BeigeBadger** [comment]
@lauren-mills does this issue also cover the fact that `.bot` files have been deprecated in favour of `appsettings.json` (C#) yet the tooling (dispatch and MSBot) still relies on the presence of a `.bot` file?

Is there a rough guide on when the documentation will be updated?

**Comment by bhushang19** [comment]
This seems to be updated now however still seems incomplete as it does not mention an approach to update the dispatch after adding or editing kb in QnA?

**Comment by darrenj** [comment]
The dispatch is updated by the update_cognitive_models script. 

https://github.com/microsoft/botframework-solutions/blob/master/docs/tutorials/csharp/customizeassistant.md#update-your-local-lu-files-for-luis-and-qnamaker
