### ISSUE TITLE
Broken documentation links

### ISSUE THREAD

**Issue by bhushang19** [microsoft/botframework-solutions#1344]
## Project

**Name**: Skills

**Language**: 

## Description
Almost all links mentioned under the section 'Restaurant Booking Skill' are broken and result in 404 on this page https://github.com/microsoft/AI/blob/master/docs/reference/skills/experimental.md

## To Reproduce
Click on any link under section 'Restaurant Booking Skill' on mentioned page

**Comment by darrenj** [comment]
Thanks. Fixed
