### ISSUE TITLE
Adding Todo skill does not refresh dispatch with utterances

### ISSUE THREAD

**Issue by bgawale** [microsoft/botframework-solutions#1345]
## Project

**Name**: Virtual Assistant, Skills

**Language**: C#

## Description
Running .\Deployment\Scripts\add_remote_skill.ps1 -botname "botassistant" -manifestUrl https://bftodoskill.azurewebsites.net/api/skill/manifest does not update the dispatch LUIS with intents

## To Reproduce
1. Create a new project using Virtual Assistant Template
2. Deploy the project using deploy script
3. Add CalendarSkill to the bot using add_remote_skill.ps1 -botname "botassistant" -manifestUrl https://bfcalendarskill.azurewebsites.net/api/skill/manifest
4. Run the project and test in emulator, everything works fine including calendar skill. Calendar intent and all utterances can also be seen in Dispatch
5. Now add todo skill using command mentioned in description, it gets executed fine however if you now visit the dispatcher - no Todo intent and relevant utterances are seen.

## Expected behavior
Dispatch should get refreshed with Todo skill and utterance

**Comment by darrenj** [comment]
Could you share the log file in the deployment folder please?

**Comment by bhushang19** [comment]
Sharing content of the log file, interestingly the Calendar.luis does exist on mentioned path.
(actualprojectpath = commented for brevity)
------------------------------------------------------------------------------------------------------------------
Exporting services for dispatch...
Exporting chitchat QnA kb...
Exporting faq QnA kb...

ERROR
Could not find a part of the path 'actualprojectpath\Deployment\Resources\Skills\en\Calendar.luis'.

------

**Comment by darrenj** [comment]
Thanks. You mention the todo skill but are passing the path for the Calendar skill? Are you actually referencing the todo skill and it's manifest?

**Comment by bhushang19** [comment]
Yes, referring todo skill and it's manifest only. Note that I was installing todo skill is on top of already installed calendar skill and could be that because script looks through installed skills or available .lu files in solution, it is generating that log entry.

**Comment by darrenj** [comment]
Very confusing :-)  I can't repro, perhaps try deleting the existing log file (to remove any logging issue) and try this:
```
add_remote_skill.ps1 -botname "botassistant" -manifestUrl https://yourtodoskill.azurewebsites.net/api/skill/manifest -luisFolder "<REPODIR>\skills\src\csharp\todoskill\todoskill\Deployment\Resources\LU\en"
```

**Comment by bhushang19** [comment]
Tried it, still results in same issue with same log entry in log file
.\Deployment\Scripts\add_remote_skill.ps1 -botname "botname" -manifestUrl https://bftodoskill.azurewebsites.net/api/skill/manifest -luisFolder "<path>\Deployment\Resources\Skills\en"

**Comment by bhushang19** [comment]
Sorry, it was me providing wrong path in dispatch file and hence it could not locate the file. Corrected the path and it works fine now. You can please close this.

**Comment by darrenj** [comment]
Great, thanks! In a future iteration we'll be able to skip having to provide the LU reference as we'll be able to "pull down" triggering utterances through the manifest which will simplify.
