### ISSUE TITLE
PowerShell deployment script for Virtual Assistant lacks adequate feedback on status of deployment

### ISSUE THREAD

**Issue by colbytimmsl** [microsoft/botframework-solutions#1348]
**Is your feature request related to a problem? Please describe.**
When comparing the current PowerShell deployment script for the Virtual Assistant bot to the msbot cmdlet that I previously used to deploy the Enterprise bot, I find that once the bot begins to deploy there are no print to console statements that provide adequate feedback on the current progress of the deployment. The msbot cmdlet however provided constant feedback on what was being deployed. Its frustrating having to go into Azure portal to view the progress of the deployment.

**Describe the solution you'd like**
I would like the new deployment script to mimic that of what occurs in the msbot cmdlet, providing feedback on what is currently being deployed. For example, if you are deploying a LUIS app, you could print "Deploying LUIS app of name: <NAME_HERE>" and then perhaps list the intents and/or entities being added to said app.

**Comment by darrenj** [comment]
Thanks - we do provide a log file in the deployment folder which does have more information. It's a balancing act as it was too verbose for many before but there is perhaps some middle ground here.

**Comment by lauren-mills** [comment]
For clarity, are you specifically looking for feedback on the Azure resource deployment? We do provide updates for LUIS, QnA, and Dispatch models, but we suppress the Azure deployment feedback in order to provide more useful errors.

**Comment by mekinney** [comment]
Jumping in here.  I personally would like to see more feedback, especially during Azure deployment.  Honestly, it appears to have locked up.  I typically remove all the piping to out-null in the deployment scripts, but new folks won't do that.  Agree it's a balance, but right now I think it's scewed towards silence.

This is from a developers perspective, not a production engineer.  They would likely make their own scripts anyway.

**Comment by lauren-mills** [comment]
There’s a PR in progress that includes the default Az CLI outputs. All it shows is “ - Running ...” until it finishes, but I’m not sure I can do any more than that with ARM deployment.
