### ISSUE TITLE
Issue creating w/ deploy.ps1 -- identifier-uris parameter required

### ISSUE THREAD

**Issue by kfprugger** [microsoft/botframework-solutions#1349]
## Project

**Name**: 

**Language**: 

## Description
When deploying, I get an error saying "'--identifier-uris' is required for creating an application"

## To Reproduce
PS C:\Users\robrakef\Source\Repos\demovassist2\demovassist2\demovassist2\Deployment\Scripts> .\deploy.ps1 -name demovassist2 -resourceGroup demovassist2-rg -location westus -appPassword "XXX" -luisAuthoringKey "XXXXX"

## Expected behavior
Script should execute and create app ids

## Screenshots
![image](https://user-images.githubusercontent.com/20729981/57642589-b0462d00-7585-11e9-8e01-1c37ffa16f5c.png)

**Comment by darrenj** [comment]
Hi - can you confirm you have the latest az CLI version? i.e. >2.0.63. The pre-reqs have a link in case not, I think that will resolve your issues (we are reliant on changes to AZ CLI)

**Comment by mekinney** [comment]
I'm a little confused by the question.  Why are you providing an appPassword without and appId?

**Comment by darrenj** [comment]
The az CLI commands used under the covers will create the application for you (and thus the appID) but **won't** auto-generate a password as it does in the portal for you. Something we're working with that time to resolve.  If for whatever reason you have to create the appid yourself then you pass both.

**Comment by mekinney** [comment]
Thanks.  Didn't realize there was a middle ground.

**Comment by kfprugger** [comment]
Confirmed. I had .54 installed. Now updated and installed. 

I can test locally, but can't test via the Web Chat blade in Azure. Should I be able to do that? is there a step I'm missing?
