### ISSUE TITLE
Documentation on new Virtual Assistant template c#

### ISSUE THREAD

**Issue by Unders0n** [microsoft/botframework-solutions#1350]
Not for the first time after new version was released i see some mess in the docs, i was using Enterprise template earlier and now seems like it was updated by virtual assistant template:
1)not quite clear how to use and deploy new Virtual Assistant, link in readme leading to general topic: https://github.com/Microsoft/AI/blob/master/docs/readme.md
2)https://github.com/microsoft/AI/blob/master/docs/reference/assistant/deploymentscripts is 404
3)in general there's few templates now - what you're recommend for case if now bot should be simple but later will need more functions, Enterprise template worked just fine for that, should i use this template now or stick with new Bot Templates https://marketplace.visualstudio.com/items?itemName=BotBuilder.botbuilderv4 ?
**UPDATE**  for point 2 correct link should be https://github.com/microsoft/AI/blob/master/docs/reference/assistant/deploymentscripts.md

**Comment by darrenj** [comment]
Not for the first time?

Link in README does go to the right place, the consolidated documents which include in the first section an overview to the template and a tutorial on how to get started.

Enterprise Template was renamed - everything you had before (and more) is included with Virtual Assistant. Some background [here](https://github.com/Microsoft/AI/wiki/What's-new-at-Build-2019) (linked at the top of the above readme).

It really depends on your goal - the base v4 templates are great to get started with the basics but for any experience you look to build you'll need to use dispatch, qna, luis, appinsights, manual deployment, etc. which we simplify for you in the template enabling you to focus on your experience rather than the foundation.

thanks for spotting the broken link, resolved

**Comment by Unders0n** [comment]
docs was frequently a trouble in botbuilder, especially when new realese comes, it was with v3 , v4, now v4.4: broken links, advices for old version, inconsistency, typos etc. Not like i'm blaming devs, you still make a great job and i really like framework, but some criticism isn't critical, right? 
As for Virtual Assistant template - i'm trying to run deploy script as from manual and getting an error:

`[DBG]: PS C:\Users\VzLOM\Documents\Visual Studio 2017\Projects\UxMastery\UxMastery\UxMastery>> .\Deployment\Scripts\deploy.ps1 -appId xxxxxxxxxxxxxxxxxxxxx -appPassword "xxxxxxxxxxxxxxxxxxxxx"
? Bot Name (used as default name for resource group and deployed resources): UxMastery
? Azure resource group region: North Europe
? LUIS Authoring Region (westus, westeurope, or australiaeast): westeurope
? LUIS Authoring Key (found at https://eu.luis.ai/user/settings): xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
> Creating resource group ...
> Deploying Azure services (this could take a while)...
ERROR: Get Token request returned http error: 400 and server response: {"error":"invalid_grant","error_description":"AADSTS700082: The refresh token has expired due to inactivity.аThe token was issued on 2018-11-01T15:12:36.5581762Z and was inactive for 90.00:00:00.\r\nTrace ID: 8670ff82-c040-4f4d-bec5-75d1f5002100\r\nCorrelation ID: 6d1a1efe-d516-4ca2-ab87-328c73512c3f\r\nTimestamp: 2019-05-14 14:16:39Z","error_codes":[700082],"timestamp":"2019-05-14 14:16:39Z","trace_id":"8670ff82-c040-4f4d-bec5-75d1f5002100","correlation_id":"xxxxxxxxxxxxxxxxxxxxxxx"}
ERROR: Get Token request returned http error: 400 and server response: {"error":"invalid_grant","error_description":"AADSTS700082: The refresh token has expired due to inactivity.аThe token was issued on 2018-11-01T15:12:36.5581762Z and was inactive for 90.00:00:00.\r\nTrace ID: 6efa6261-31bf-4776-9c4d-effe1f232100\r\nCorrelation ID: 745ab549-072b-40a9-83c1-7a2d9e86a5c3\r\nTimestamp: 2019-05-14 14:16:42Z","error_codes":[700082],"timestamp":"2019-05-14 14:16:42Z","trace_id":"6efa6261-31bf-4776-9c4d-effe1f232100","correlation_id":"745ab549-072b-40a9-83c1-7a2d9e86a5c3"}`

**Comment by darrenj** [comment]
Thanks - odd, seems like an AZ CLI issue relating to auth ids? Can you open a new powershell window and type `az login` and try again?

**Comment by Unders0n** [comment]
yeah seems like it was smth with that. Now i logged. That helped, but i got error:
! Deployment failed for resource of type Microsoft.CognitiveServices/accounts.
! Code: InvalidApiSetId.
! Message: The account type 'QnAMaker' is either invalid or unavailable in given region..
+ To delete this resource group, run 'az group delete -g UxMastery --no-wait'

But actually seems like it created all other needed resources. Btw do i still need to wire that up filling keys in config file or it can do it automatically?

**Comment by darrenj** [comment]
Great you have progress. So #1339 I've been working on an additional validation step for the deployment script. Unfortunately LUIS and QnAMaker aren't in all regions so northeurope for instance it can't find qnamaker. We'll make a change shortly to highlight this **before** creating the other resources. I would suggest you delete the resource-group and re-create following [this parameter file](https://github.com/microsoft/AI/blob/master/docs/howto/assistant/customizedeployment.md). Pass this in on your deploy powershell command.

Suggest westeurope for qnamaker, northeurope is fine for LUIS so no need to change that same for appinsights so overriding qnamaker region should be enough to fix.

Make sure you get your authoring key from this regional LUIS endpoint: https://eu.luis.ai/

https://azure.microsoft.com/en-us/global-infrastructure/services/

**Comment by Unders0n** [comment]
thanks, i guess i will go with manual deploymtn for now, but for next project i will try this aproach, there will be options for CLI to skip some resources, right?

**Comment by darrenj** [comment]
Hopefully you can try the parameter file (should be one line change) as that will create your resources and update all of the appsettings.json/cognitivemodels.json files. You then pass this on the deploy script using the `-parametersFile` settings. 

https://github.com/microsoft/AI/blob/master/docs/reference/assistant/deploymentscripts.md

As per required/not-required parameters covered [here](https://github.com/microsoft/AI/blob/master/docs/reference/assistant/deploymentscripts.md)

**Comment by Unders0n** [comment]
when i'm trying from scratch with no existing resource group (this is intended, right?) and extra parameter file you suggested i got this error:
[DBG]: PS C:\Users\VzLOM\Documents\Visual Studio 2017\Projects\UxMastery\UxMastery\UxMastery>> .\Deployment\Scripts\deploy.ps1 -parametersFile .\Deployment\Resources\parameters.template.json
? Bot Name (used as default name for resource group and deployed resources): UxMasteryChatbot
? Azure resource group region: North Europe
? Password for MSA app registration (must be at least 16 characters long, contain at least 1 special character, and contain at least 1 numeric character): xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
? LUIS Authoring Region (westus, westeurope, or australiaeast): westeurope
? LUIS Authoring Key (found at https://eu.luis.ai/user/settings): xxxxxxxxxxxxxxxxxxxxxxxxxxx
ERROR: '--identifier-uris' is required for creating an application
! Could not provision Microsoft App Registration automatically. Review the log for more information.
! Log: C:\Users\VzLOM\Documents\Visual Studio 2017\Projects\UxMastery\UxMastery\UxMastery\Deployment\Scripts\..\deploy_log.txt
+ Provision an app manually in the Azure Portal, then try again providing the -appId and -appPassword arguments. See https://aka.ms/vamanualappcreation for more information.

btw deploy_log.txt is empty

**Comment by Unders0n** [comment]
@darrenj btw side question - is .bot files are not reccomended way anymore? can't see them in project, shall i create em manually?

**Comment by darrenj** [comment]
Yes - Bot files as a approach have been deprecated by the Tools team to better align with other tooling. If you create a bot file for the emulator and paste in your appid/password you should be good to go.

https://github.com/microsoft/AI/blob/master/docs/howto/assistant/csharp/ettovamigration.md

**Comment by Unders0n** [comment]
@darrenj please also check my previos message, thanks

**Comment by darrenj** [comment]
Looks like you don't have the latest az bot cli (as per pre-reqs ;-)

Check `az -v` you should be >= 2.0.63
