### ISSUE TITLE
Issue adding skills capabilities to an existing V4 Bot

### ISSUE THREAD

**Issue by e-gonzalez** [microsoft/botframework-solutions#1356]
## Project

**Name**: Enable Bot Framework Skills on an existing v4 bot 

**Language**: Typescript 

## Description
I have an existing V4 Bot and I wanted to add a Skill capability. 
Following the steps, I should update my bot to use some Bot Framework Solutions libraries, which are related to botbuilder-solutions and botbuilder-skills packages.

However, trying to install the botbuilder-skill package a 404 error prompted (find screenshot attached) due to microsoft-bot-protocol-websocket and microsoft-bot-protocol dependencies are not available. 

How can I follow the skill configuration? 

## To Reproduce
Execute "npm i botbuilder-skills" command.

## Expected behavior
Install al the botbuilder-skill dependencies, without errors. 

## Screenshots
![image](https://user-images.githubusercontent.com/19410751/57690438-f234a900-7641-11e9-84c7-9437e9fff18d.png)

**Comment by Batta32** [comment]
Hi @e-gonzalez, thanks for contribute!

We noticed that you are using an existing Bot to add a Skill.
At this moment, those packages (`microsoft-bot-protocol` and `microsoft-bot-protocol-websocket`) are published in [myget](https://botbuilder.myget.org/gallery/aitemplates/), so if you don’t have a `.npmrc` referencing that package manager it will fail (check this [.npmrc](https://github.com/microsoft/AI/blob/master/templates/Virtual-Assistant-Template/typescript/samples/sample-assistant/.npmrc)) .

Meanwhile, you can create one or you can use [generator-botbuilder-assistant](https://botbuilder.myget.org/feed/aitemplates/package/npm/generator-botbuilder-assistant)!
