### ISSUE TITLE
Move to LUISPrompt in Confirm scenarios

### ISSUE THREAD

**Issue by darrenj** [microsoft/botframework-solutions#136]
Ensure all ConfirmYes or ConfirmNo prompts leverage LUIS (e.g. Cancel flow) and we should add a new step to Onboarding to demonstrate how we suggest LUIS is used for these types of prompts.  Once implemented we should do a pass across the Skills to ensure they are using it across the board too.

**Comment by lauren-mills** [comment]
I believe that the ConfirmPrompt is already using LUIS for yes and no. I just tested the Cancel dialog saying "sure" instead of yes and it did cancel successfully.

**Comment by darrenj** [comment]
Fair point - I didn't get a chance to go through and check. It could have been a Skill flow that wasn't doing it!  Could we do a quick search through the skills to double check and we can just close this out!

**Comment by ryanisgrig** [comment]
I'll validate through and let you know what I find

Ryan

________________________________

**Comment by ryanisgrig** [comment]
Lauren is correct, ConfirmPrompt is already setup for Yes/No entities & the skills are using them. I've got some feedback for additional entities that would be useful to pick up in these scenarios...

### Yes

| Valid | Invalid           | 
| ------------- |:-------------:|
|y| yup | 
|yes| yeah |  
|yep| yea |    
|sure| i think so |  
|ok| of course |  
|| aye |    
|| aye aye |    
|| totally |    
|| yessir |    
|| mhm|    
|| fine |    
|| alright |    
|| all right|    
|| very well |    
|| by all means |    
|| certainly |    
|| absolutely |    
|| indeed |    
|| affirmative |    
|| why not |    
|| sure|    
|| definitely |    
|| let's do it |    
|| let's do that  |
|| that would be great |
        
### No

| Valid | Invalid           | 
| ------------- |:-------------:|
|no| never | 
|nope| forget it |  
|no way| absolutely not |    
|not sure| negative |  
|| of course not |  
|| nah |    
|| not really |
|| not right now thanks |
|| not at all |
|| by no means|

**Comment by ryanisgrig** [comment]
Synced with @johnataylor, this is from [Recognizers-Text](https://github.com/Microsoft/Recognizers-Text/blob/master/.NET/Microsoft.Recognizers.Definitions/English/ChoiceDefinitions.cs). I'll provide additional English entities for Yes & No.

Tracking at #169
