### ISSUE TITLE
Telemetry missing key properties - Telemetry Initializer properties missing?

### ISSUE THREAD

**Issue by mekinney** [microsoft/botframework-solutions#1360]
## Project
**Name**: Virtual Assistant
**Language**: C#

## Description
The telemetry produced by the Virtual Assistant doesn't contain important properties as contained in the documentation.

It appears the properties that the Telemetry Initializer are supposed to create are missing.

The session_id and activityId are critical to being able to properly analyze complete conversations.

## To Reproduce
Build VirtualAssistantSample
Run
Type in something
Look at telemetry.

## Expected behavior
Luis Documentation:
![LuisTelemetry](https://user-images.githubusercontent.com/7552362/57722092-9d416480-763a-11e9-98ab-2981c68bb2e2.JPG)

Actual Luis Telemetry:
![ActualLuisTelemetry](https://user-images.githubusercontent.com/7552362/57722132-acc0ad80-763a-11e9-937a-23c397a09a0c.JPG)

QnA Documentation:
![QnATelemetry](https://user-images.githubusercontent.com/7552362/57722213-ce219980-763a-11e9-8b4b-6753c5b69d0b.JPG)

Actual QnA Telemetry:
![ActualQnATelemetry](https://user-images.githubusercontent.com/7552362/57722247-daa5f200-763a-11e9-9052-c0af0f90be60.JPG)

Note: the question and matchedQuestion properties are perfect.  Please don't make them match the documentation.  Fix the documentation.

**Comment by darrenj** [comment]
@ryanlengel, @daveta would be good if you can both review and validate SDK expected behaviour versus the docs (I suspect it's doc updates but good to validate)

@mekinney some of what your seeing is because you haven't enable sentiment on your published LUIS models.

**Comment by dmvtech** [comment]
I'm taking a look.

**Comment by NickVandenberghe** [comment]
I'm having the same problem.
The way to work around this problem is to create your own TelemetryInitializer (as far as i know).
However the problem i now stumble upon is how to get the turncontext in the initializer.
I also question myself if the conversationid would change for each conversation.

**Comment by ryanisgrig** [comment]
Closed via #1560
