### ISSUE TITLE
User Profile Store

### ISSUE THREAD

**Issue by Dewain27** [microsoft/botframework-solutions#1362]
## User Story
As ... a bot user
I want ... my preferences to be remembered by a Virtual Assistant
so that ... the experience is personalized and the conversation is concise.

## Acceptance Criteria 
*List your requirements.*
- [ ] Each skill should be able to save User settings specific to that skill (ex. News preferences in News Skill)
- [ ] VA should be able to store User settings that it can pass to skills as needed through skill slots/semantic actions
- [ ] VA should enable these settings out of the box, but should be customizable:
     - [ ] Name
     - [ ] Home location
     - [ ] Work location
- [ ] Should use UserState property
- [ ] VA Should prompt user to provide values for settings in OnboardingDialog (?)
- [ ] Approach should be aligned with SDK state plan

## Resources
*Provide any screenshots or conversation mockups to support your request.*
*Learn how to mock up bot conversations with [.chat files](http://aka.ms/bfchatfile).*

## Notes
*Provide any additional information.*
Customers are asking for a place that they can store and get the VA user's personal preferences.  This would allow for a user to store their preferences.

**Comment by darrenj** [comment]
Addressed with recent template changes
