### ISSUE TITLE
[Virtual Assistant] Router Dialog should not inherit InterruptableDialog

### ISSUE THREAD

**Issue by tiagodenoronha** [microsoft/botframework-solutions#1366]
## Project

**Name**: Virtual Assistant

**Language**: C#

## Description
On a Router Dialog, OnInterruptDialogAsync is always called before RouteAsync, making the first test of the message the responsibility of the General LUIS, which should not be.
If Router Dialog inherits from InterruptableDialog, then every first message is tested for the "Cancel", "Help" or other type of interruption before the Dispatcher can come into play.

The default solution for the Enterprise Bot Template was to put the actions in the RouteAsync method, beneath the "General" actions of the Bot.

**tl;dr;** First message the bot receives gets "scanned" via OnInterruptDialogAsync, which only calls the General LUIS, making things like a FAQ message impossible to submit, unless you train the "None" intent of the General LUIS with the FAQ.lu file.

## To Reproduce
- Deploy template.
- Send a message close to a Cancel Intent on a General LUIS, but clear FAQ intent on Dispatcher LUIS

## Expected behavior
Dispatcher would pick up the message as FAQ, and would redirect to QnAMaker.

Would love your comments on this issue, was there a reason for the change?
Am I missing something?

Thanks!

**Comment by lauren-mills** [comment]
We consolidated the EnterpriseDialog base class with MainDialog to reduce complexity, and we agreed on our side that interruptions should get the highest priority. 

One quick change you could make to enable the functionality you are looking for would be to check for an active dialog in the MainDialog OnInterruptionAsync handler before calling the general luis model.

Something like this should make it to where interruptions are only checked when there is a dialog on the stack:

```
        protected override async Task<InterruptionAction> OnInterruptDialogAsync(DialogContext dc, CancellationToken cancellationToken)
        {
            if (dc.ActiveDialog != null)
            {
                  ...
            }
```
Note, you would need to add the handler for the help, cancel, and logout intents back to the RouteAsync intent handling.

**Comment by tiagodenoronha** [comment]
Hey!

First of all thanks for the code snippet!

Not trying to be stubborn, but while I beleive in other types of dialogs the interruptions should get the highest priority, this is not the case with a Route Dialog. My understanding is that the Router Dialog is meant to call the LUIS services and direct the user's message to the correct Skill / Dialog. 

Why would should we implement interruptions in the first dialog if the next messages would all be caught by the other Dialogs?

Thanks!

**Comment by lauren-mills** [comment]
Like I mentioned before, this change was largely to reduce complexity and custom code (beyond what the SDK offers by default) in the template. That’s not to say the previous implementation doesn’t also work, and might not be preferable in some situations. The main goal of the change was to enable interruptions for help and cancel on every turn while not introducing an extra base class, and this achieves that. Now we have the handlers for help and cancel in one centralized place, instead of duplicated between main dialog and the enterprise dialog. 

There will be some more advanced features coming in the next version of the SDK that will clean this logic up as well, so keep an eye out for improvements to in the coming months.

**Comment by tiagodenoronha** [comment]
Got it! Thanks for the explanation, makes perfect sense!

I'll close the issue and await (pun intended) for the improvements!

Thanks again!
