### ISSUE TITLE
Web Chat 

### ISSUE THREAD

**Issue by kfprugger** [microsoft/botframework-solutions#1368]
## Project

**Name**: 
Virtual Assistant
**Language**: 
C#
## To Reproduce

Deploy the VA script

## Expected behavior

I would expect the Bot Service entity's Web Chat channel in Azure to work after deploying the script. Currently, it does not, it only works locally in the Emulator.

## Screenshots

![image](https://user-images.githubusercontent.com/20729981/57807695-ae1fd200-772f-11e9-9c85-93d111c7cc15.png)

**Comment by kfprugger** [comment]
EDIT: I published using right click --> publish in VS 2019, selected the ASP and web app that the script deployed for me and had no issues after VS2019 auto-restarted the ASP/Webapp for me.

**Comment by darrenj** [comment]
@kfprugger We are about to add a auto-deploy option to the deployment scripts for Virtual Assistant so you don't run into this issue moving forward. Thanks for raising.
