### ISSUE TITLE
Document what to include in source control post deployment

### ISSUE THREAD

**Issue by ericchansen** [microsoft/botframework-solutions#1372]
**Is your feature request related to a problem? Please describe.**

There's no documentation on what to include in source control post deployment.

**Describe the solution you'd like**

Documentation on what to include in source control post deployment.

**Describe alternatives you've considered**

I'm experimenting to determine what's required in source control, but I'm surprised that this isn't documented somewhere.

**Additional context**

None.

**Comment by ericchansen** [comment]
For example, a lot of files are created under `Deployment/Resources` in the template. It's not clear what must be included in the source control for someone to be able to check out the code and be able to run locally (or publish themselves to the Azure web app).

**Comment by ericchansen** [comment]
I don't want to limit the verbosity of the documentation. I think many devs would appreciate the docs covering as much ground as possible.

However, in particular, I'm not sure about the contents of the `data` folders, the `*.luis` files and the `*.qna` files.

**Comment by lauren-mills** [comment]
Hi @ericchansen, if you take a look at our gitignore, you can see the files that we exclude from our repo. 
The files you mention are all deployment related, so they are not used at runtime. I'm not sure where this information would fit in our docs, so if you have any suggestions let us know.
