### ISSUE TITLE
Skill Deployment to provide a way to reference an existing CosmosDB

### ISSUE THREAD

**Issue by darrenj** [microsoft/botframework-solutions#1375]
**Is your feature request related to a problem? Please describe.**

As a developer, I create and deploy my Virtual Assistant and then add a Skill. The Skill deployment creates a new CosmosDB rather than providing the ability to use the existing one which would reduce costs. A different collection can be used to provide separation.

**Describe the solution you'd like**
Documentation and/or deployment script/ARM template changes that enable me to change the deployment to use an existing resource rather than create a new one.

**Comment by lauren-mills** [comment]
Easy change. Just remove the cosmos resource from the ARM script and provide your own keys in app settings
