### ISSUE TITLE
Cannot post activity. Unauthorized.

### ISSUE THREAD

**Issue by gagankohli2000** [microsoft/botframework-solutions#1381]
## Project

**Name**: Calendar Skills

**Language**: c#

## Description
I have successfully deployed calendar skill solution but while running i'm getting "Cannot post activity. Unauthorized."

**Comment by darrenj** [comment]
Hi - Are you using the emulator? If so, are you using the AppId and Secret added to the appsettings.config file in your calendar skill?

**Comment by gagankohli2000** [comment]
Yes, I'm using the emulator and Appid and Secret added to appsettings.config. Is this Calendar works with google or Office365? I see settings for googleAppName, Clientid and ClientSecret.

**Comment by darrenj** [comment]
Hi,

Assuming your getting the unauthorized issue when your asking the Skill something? e.g. what meetings do I have today and it's failing when trying to show the oauthcard?  

The Calendar skill works with Google and Office 365. When the Calendar Skill is added to a Virtual Assistant Bot we create all of the authentication connection configuration for you (Office 365 only) however if you are installing/using the Calendar Skill directly this isn't done for you (it's part of the add skill functionality).

Thanks for raising as we don't have the manual steps in the latest documentation for this type of configuration. I've raised #1382 to track resolution.

**Comment by lauren-mills** [comment]
Closed by #1433
