### ISSUE TITLE
Add AADv1 support to OauthProvider

### ISSUE THREAD

**Issue by siddimore** [microsoft/botframework-solutions#1386]
**Is your feature request related to a problem? Please describe.**
Skill i work uses AAD v1 for Oauth. Currently  Microsoft.bot.solutions only support AADv2

**Describe the solution you'd like**
Add support for AADv1 in MultiproviderAuthDialog

**Comment by siddimore** [comment]
Please change the  below: 
switch (providerString)
            {
                case "Azure Active Directory":
                case "Azure Active Directory v2":
                    return OAuthProvider.AzureAD;

**Comment by darrenj** [comment]
Resolved by #1387 

Will this get pushed as part of our daily build to myget @lzc850612 ?

**Comment by xieofxie** [comment]
Will we add enums for all providers in azure (like Generic Oauth 2, Oauth 2 Generic  Provider etc.)? Or it will be revised in later release.
