### ISSUE TITLE
Enable Linked Accounts end-to-end scenario using Direct Line Speech channel

### ISSUE THREAD

**Issue by ryanisgrig** [microsoft/botframework-solutions#1388]
**Virtual Assistant & Linked Accounts app**
- [X] VA on Direct Line Speech channel sends an event for a client to consume
- [x] Linked Accounts web app adds optional boolean query string `companionApp`. If true, the linked accounts view adds a button "Complete and return to app" with a deep link to be consumed by client

**Comment by ryanlengel** [comment]
@abiemann let's port over this functionality to the white-label app
