### ISSUE TITLE
Error resolving type specified in JSON

### ISSUE THREAD

**Issue by alfredoxyanez** [microsoft/botframework-solutions#1391]
## Project

**Name**: Virtual Assistant, Skills

**Language**: C#

## Description
Email skill returns ""Error resolving type specified in JSON 'EmailSkill.Models.EmailSkillState, EmailSkill'. Path 'EmailSkillState.$type'." after asking 3 or more questions about emails. 

## To Reproduce
1. Ask about emails;
2. Input the magic code;
3. Ask about emails 3 or more times;
4. Get the error.

## Expected behavior
Get information about emails.

## Screenshots
<img width="1494" alt="Screen Shot 2019-05-21 at 9 17 33 AM" src="https://user-images.githubusercontent.com/18299052/58099344-6e327200-7ba9-11e9-9697-83b3013266eb.png">

## Additional context
Trace 1:
"Error resolving type specified in JSON 'EmailSkill.Models.EmailSkillState, EmailSkill'. Path 'EmailSkillState.$type'."

Trace 2:
"   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolveTypeName(JsonReader reader, Type& objectType, JsonContract& contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, String qualifiedTypeName)\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadMetadataProperties(JsonReader reader, Type& objectType, JsonContract& contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue, Object& newValue, String& id)\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateDictionary(IDictionary dictionary, JsonReader reader, JsonDictionaryContract contract, JsonProperty containerProperty, String id)\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)\n   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)\n   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)\n   at Microsoft.Bot.Builder.Azure.CosmosDbStorage.ReadAsync(String[] keys, CancellationToken cancellationToken) in d:\\a\\1\\s\\libraries\\Microsoft.Bot.Builder.Azure\\CosmosDbStorage.cs:line 236\n   at Microsoft.Bot.Builder.BotState.LoadAsync(ITurnContext turnContext, Boolean force, CancellationToken cancellationToken) in d:\\a\\1\\s\\libraries\\Microsoft.Bot.Builder\\BotState.cs:line 67\n   at Microsoft.Bot.Builder.BotState.BotStatePropertyAccessor`1.GetAsync(ITurnContext turnContext, Func`1 defaultValueFactory, CancellationToken cancellationToken) in d:\\a\\1\\s\\libraries\\Microsoft.Bot.Builder\\BotState.cs:line 305\n   at Microsoft.Bot.Builder.Dialogs.DialogSet.CreateContextAsync(ITurnContext turnContext, CancellationToken cancellationToken) in d:\\a\\1\\s\\libraries\\Microsoft.Bot.Builder.Dialogs\\DialogSet.cs:line 92\n   at VirtualAssistantSample.Bots.DialogBot`1.OnTurnAsync(ITurnContext turnContext, CancellationToken cancellationToken) in /Users/alfredoyanez/Desktop/ETT BOT/VirtualAssistant (Email, Calendar, Restaurant) /GenericBot/Bots/DialogBot.cs:line 39\n   at Microsoft.Bot.Builder.AutoSaveStateMiddleware.OnTurnAsync(ITurnContext turnContext, NextDelegate next, CancellationToken cancellationToken) in d:\\a\\1\\s\\libraries\\Microsoft.Bot.Builder\\AutoSaveStateMiddleware.cs:line 60\n   at Microsoft.Bot.Builder.Solutions.Middleware.EventDebuggerMiddleware.OnTurnAsync(ITurnContext turnContext, NextDelegate next, CancellationToken cancellationToken)\n   at Microsoft.Bot.Builder.Solutions.Middleware.SetLocaleMiddleware.OnTurnAsync(ITurnContext context, NextDelegate next, CancellationToken cancellationToken)\n   at Microsoft.Bot.Builder.ShowTypingMiddleware.OnTurnAsync(ITurnContext turnContext, NextDelegate next, CancellationToken cancellationToken) in d:\\a\\1\\s\\libraries\\Microsoft.Bot.Builder\\ShowTypingMiddleware.cs:line 71\n   at Microsoft.Bot.Builder.TelemetryLoggerMiddleware.OnTurnAsync(ITurnContext context, NextDelegate nextTurn, CancellationToken cancellationToken) in d:\\a\\1\\s\\libraries\\Microsoft.Bot.Builder\\TelemetryLoggerMiddleware.cs:line 109\n   at Microsoft.Bot.Builder.TranscriptLoggerMiddleware.OnTurnAsync(ITurnContext turnContext, NextDelegate nextTurn, CancellationToken cancellationToken) in d:\\a\\1\\s\\libraries\\Microsoft.Bot.Builder\\TranscriptLoggerMiddleware.cs:line 108\n   at Microsoft.Bot.Builder.BotFrameworkAdapter.TenantIdWorkaroundForTeamsMiddleware.OnTurnAsync(ITurnContext turnContext, NextDelegate next, CancellationToken cancellationToken) in d:\\a\\1\\s\\libraries\\Microsoft.Bot.Builder\\BotFrameworkAdapter.cs:line 964\n   at Microsoft.Bot.Builder.MiddlewareSet.ReceiveActivityWithStatusAsync(ITurnContext turnContext, BotCallbackHandler callback, CancellationToken cancellationToken) in d:\\a\\1\\s\\libraries\\Microsoft.Bot.Builder\\MiddlewareSet.cs:line 55\n   at Microsoft.Bot.Builder.BotAdapter.RunPipelineAsync(ITurnContext turnContext, BotCallbackHandler callback, CancellationToken cancellationToken) in d:\\a\\1\\s\\libraries\\Microsoft.Bot.Builder\\BotAdapter.cs:line 167"

**Comment by darrenj** [comment]
@DingmaomaoBJTU  - Could you take a look?

**Comment by alfredoxyanez** [comment]
I think the issue might be related to: https://github.com/microsoft/botframework-solutions/pull/1389

**Comment by alfredoxyanez** [comment]
I updated NuGet (both skills and solution) to 4.4.3.1 and that didn't fix the issue.

**Comment by darrenj** [comment]
Hold tight - we think it might be related to a change that a new package will fix (we're planning to publish today)

**Comment by darrenj** [comment]
Actually that is the latest. @DingmaomaoBJTU definitely one it would be good for you to take a look please

**Comment by DingmaomaoBJTU** [comment]
Hi @ayanez17 I set up a VA and add the email skill with latest code, but could not repro this issue. Are you using the latest code? Could you give me more information about this bug?

**Comment by darrenj** [comment]
Out of interest - @ayanez17 if you start a conversation with the Skill again within the emulator. Click restart to ensure a whole new conversation can you repro?

**Comment by alfredoxyanez** [comment]
@DingmaomaoBJTU As a reminder it breaks the third time. If I send "email" it works the first 2 times and I get a card with emails. The third time is when I get the error. Moreover, the first time you send "emails" that returns a magic code and you use that to sign in. I then ask "emails" 3 more times and it breaks the third time. @darrenj Yeah, I've tried restarting the conversation multiple time by pressing "Restart Conversation" in the bot Emulator ( Version 4.4.1 (4.4.1.58456)) I am on a Mac and we have encountered this issue in local deployment in a PC as well. The code we are using we pulled straight from the GitHub yesterday evening.

**Comment by alfredoxyanez** [comment]
@DingmaomaoBJTU  @darrenj The calendar skill does work. The thing is that after I ask "calendar" and I send the magic code I automatically  **get response about my calendar**. I can then ask about my calendar any number of times and it works. With the email skill, when I send the magic code I do not get a response in respect to the emails. I get "What else can I help you with?" and **not a response to the email**s. I then ask "emails" and it works 2 times. The third time I get the: "Error resolving type specified in JSON 'EmailSkill.Models.EmailSkillState, EmailSkill'. Path 'EmailSkillState.$type'." error

**Comment by ayanez17** [comment]
@DingmaomaoBJTU  When you send the magic code after invoking the email skill what is the response that you get ? Can you post a screenshot please?

**Comment by alfredoxyanez** [comment]
The issue was resolved by making sure that the VA was in one collection, and each and every skill had its own unique collection of CosmosDb.

**Comment by DingmaomaoBJTU** [comment]
That's great!~~~ So can I close this issue?

**Comment by DingmaomaoBJTU** [comment]
Cosmos db parsing can be wired if state schema ever changed. Could you please try to create a new cosmos db and share it on both Email and Calendar?
