### ISSUE TITLE
Could not load manifest for calendar skill

### ISSUE THREAD

**Issue by allenwux** [microsoft/botframework-solutions#1392]
Built and deployed both virtual assistant and calendar skill following the tutorial. When I'm trying to add the skill with following command:
.\Deployment\scripts\add_remote_skill.ps1 -botName "phbot" -manifestUrl https://phbotcalendar/api/skill/manifest -luisFolder "C:\Users\xiwu\Documents\GitHub\botframework-solutions\skills\src\csharp\calendarskill\calendarskill\Deployment\Resources\LU"

I got the following error:
! Could not load manifest from https://phbotcalendar.azurewebsites.net/api/skill/manifest. Please check the url and try again.

When i'm trying to browse the url, I got:
The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.

When I'm trying it in the emulator, it was trying to load the oauthConnections from appSettings which has an empty name. It throws exception. 

Did I do anything wrong?

**Comment by darrenj** [comment]
Hi - Testing a theory out, I suspect the skill isn't actually published to your Azure endpoint. We don't do this automatically for you (but we've had some feedback that it's confusing so it's been added shortly). Could you open calendar skill project and right click solution and publish to the app-service that's been created? Based on browsing to your skill I don't think the code is deployed to azure.

cc @lauren-mills if so, we should make sure the proposed "run this command to publish" or auto-publish is in the skill deployment script too.

**Comment by allenwux** [comment]
You are right! publishing the apps moved this forward. Now I see 500 instead of the original error. When I'm looking at the app log, I see:

An unhandled exception was thrown by the application.System.ArgumentNullException: Value cannot be null.Parameter name: dialogIdat Microsoft.Bot.Builder.Dialogs.Dialog..ctor(String dialogId)at Microsoft.Bot.Builder.Dialogs.OAuthPrompt..ctor(String dialogId, OAuthPromptSettings settings, PromptValidator`1 validator)....

I can send you the full callstack (too long to paste it here). I doubt if it is related to the issue I mentioned above that the name of oauthConnections is empty:

  "oauthConnections": [
    {
      **"name": "",**
      "provider": "Azure Active Directory v2"
    }
  ],

**Comment by darrenj** [comment]
Strange as manifest generation is pretty simple. OauthConnections in your bot is populated once add remote skill works so that's fine. Can you validate that the manifesttemplate.json in your skill directory is unchanged?

**Comment by allenwux** [comment]
manifesttemplate.json is not changed. I just purged everything and retried this morning.

**Comment by darrenj** [comment]
Strange, I can't repro here but will rebuild / deploy tomorrow and double check. Can you confirm the nugget package version your using for skills so I test with the right one?

**Comment by allenwux** [comment]
![image](https://user-images.githubusercontent.com/22797751/58123404-94afd780-7bc0-11e9-9b06-d79a8040f98f.png)

**Comment by allenwux** [comment]
I added "Outlook" to the appsettings:
"oauthConnections": [
{
"name": "**Outlook**",
"provider": "Azure Active Directory v2"
}
],

Now I can add the skill successfully. Then I rebuilt and redeployed the Virtual Assistant app and tested the webbot using WebChat. I got:
Me: What is my next meeting?
Bot: [File of type 'application/vnd.microsoft.card.oauth']

Does this work with Microsoft AAD? Or I should try to deploy it to my own MSDN subscription? Not sure if I have enough credit for it though...

**Comment by lzc850612** [comment]
The webchat out of devportal doesn't support OAuth card. Can you try testing in Emulator? It should give you a nice experience on OAuth.

**Comment by darrenj** [comment]
Hi - Did you add that line to the appsettings for the calendarskill or the VA bot (neither should be required but narrows issue down potentially). If you added skill to your VA Bot it will have created the auth connection for you and should match the "outlook" name created. Testing in emulator should then enable auth to work

**Comment by allenwux** [comment]
Emulator is the first thing I tried. and I got: Error: The bot is remote, but the service URL is localhost. Without tunneling software you will not receive replies.

It seems I need to configure the ngrok. Any document about how to do that?

**Comment by darrenj** [comment]
https://github.com/Microsoft/BotFramework-Emulator/wiki/Tunneling-(ngrok)

**Comment by allenwux** [comment]
Thanks! It works. Now I need some permission which I don't have in Microsoft AAD. How did you guys test it?

**Comment by darrenj** [comment]
Hi - What is the message you get when signing-in to your account? Perhaps an admin consent request? If so, your organisation may have turned on application restrictions meaning your app/bot must be approved by your administrators. This is performed in some organisations. For testing you can get your app approved, alternatively use a outlook.com/hotmail account? Internally we have a way to create demo tenants for o365 which is useful for demos.

**Comment by darrenj** [comment]
I can repro the issue you had with the manifest not being generated. It's totally fine to not have an auth connection configured in the scenario that your using the Skill from a VA. The issue appears to be that each dialog is being constructed as part of manifest generation which is causing the issue. Looking into it..
