### ISSUE TITLE
[Android App] Enable events support using Direct Line Speech channel

### ISSUE THREAD

**Issue by ryanisgrig** [microsoft/botframework-solutions#1393]
Validate that Android app can pass client events like `VA.Location` and `VA.Timezone` to a VA.

Skills need to support semantic actions for event data

**Comment by lzc850612** [comment]
Nitpick: we should use VA.Location and VA.Timezone all up since the string "IPA" should be gone from our repo.

**Comment by ryanisgrig** [comment]
The VA template currently relies on a developer manually adding in event handling. Is that the desired approach or should this be enabled OOB? If manual, we need to update the corresponding docs.

**Comment by darrenj** [comment]
Should be oob

**Comment by ryanlengel** [comment]
As a template, does it make sense to have the events OOB? A general event handler method should be OOB but I mean the specific `VA.Location`, `VA.Timezone` events

**Comment by ryanisgrig** [comment]
@lzc850612 added you so we can track the skill work needed

**Comment by lzc850612** [comment]
The work to support reading from semanticAction for CalendarSkill and POISkill has been finished. @ryanlengel we can probably close this.

**Comment by ryanisgrig** [comment]
Did you get to validate on the bfva environment? Earlier today I saw that the location bug (where it always saw a user in Tennessee) was still there.

It may be a bug on the bfva state but if the event passes through correctly then it should be overwritten and be ok ??

Sent from my??

________________________________

**Comment by ryanisgrig** [comment]
Validated and closed
