### ISSUE TITLE
[Android App] Refactor configuration settings

### ISSUE THREAD

**Issue by ryanisgrig** [microsoft/botframework-solutions#1395]
1. Merge Bot Configuration & App Configuration together, can add subheaders after if it's too many
2. Rename settings:
    * Service Key -> Speech Service Subscription Key
    * Service Region -> Speech Service Subscription Key Region
    * Bot Id -> Direct Line Speech Secret Key
    * User ID -> User From Id
    * Remove Voice Name (not used and is set by SSML from VA)
3. Rename Reset Bot to Restart Conversation

**Comment by ryanisgrig** [comment]
For the subtle variations of colors, we should consider if we want those customizable as well or just adjust based on the default color.

**Comment by abiemann** [comment]
let the user edit colors within a host config using a color picker

**Comment by ryanisgrig** [comment]
There are a couple of approaches for editing the host config that we should consider for it scaling:
1. User imports their own `hostconfig.json` into the app, it's settings are reflected throughout cards rendering.
2. User makes changes in the app for common colors that can reflect through the app & cards themselves. The colors between app resources/card host config are shared variables and reflect a consistent UI throughout the VA experience. 

If we use the second approach, should the app inherit host config or vice versa?

It's also important to highlight that we may want to allow for greater configuration like font family. @Dewain27 would we have a need for this?

**Comment by abiemann** [comment]
inherited from #1441 : allow user to customize the speech-background color

**Comment by ryanlengel** [comment]
Rename settings:

Service Key -> Speech Service Subscription Key
Service Region -> Speech Service Subscription Key Region
Bot Id -> Direct Line Speech Secret Key
User ID -> User From Id
**Remove Voice Name**


Merge Bot Configuration & App Configuration together, can add subheaders after if it's too many

**Comment by ryanisgrig** [comment]
Updated the initial comment to reflect new direction in refactoring configuration

**Comment by abiemann** [comment]
also removed directline constant from settings
