### ISSUE TITLE
Add remote skills script should allow users to add multiple skills in one command

### ISSUE THREAD

**Issue by ryanisgrig** [microsoft/botframework-solutions#1404]
**Is your feature request related to a problem? Please describe.**

When spinning up demo environments, users now have to create a Virtual Assistant bot on their own and then add the remote skills that will be used individually. In the past these were all part of the same solution and made it easier to get started. Now this involves a lot more manual steps.

**Describe the solution you'd like**

-manifestUrl parameter takes one or many skill manifest references, comma-separated

`.\Deployment\scripts\add_remote_skill.ps1 -botName "<assistant-name>" -manifestUrl 'https://calendarskill.azurewebsites.net/api/skill/manifest'`

`.\Deployment\scripts\add_remote_skill.ps1 -botName "<assistant-name>" -manifestUrl 'https://calendarskill.azurewebsites.net/api/skill/manifest,https://emailkill.azurewebsites.net/api/skill/manifest,https://todoskill.azurewebsites.net/api/skill/manifest'`

Either the script runs through each skill one at a time and waits for each to complete, or it runs through the steps one time combining manifest components (i.e. all OAuth providers/scopes).

**Additional context**

**Comment by darrenj** [comment]
@dfavretto - Could you take a look at this with botskills - our current powershell will be retired next week so would be good to explore options for this, not quite sure on best practices for adding multiple urls in one cli call

**Comment by dfavretto** [comment]
Hi @darrenj, we think that the best solution would be to add a new flag (`--noDispatchRefresh`) that would allow to add manifests/skills without changing the Dispatch model, and after that, just running the `dispatch refresh` for all the new Skills. We'll print the `dispatch refresh` command by console when the flag is present

**Comment by darrenj** [comment]
Works for me and will make things faster for sure!

**Comment by darrenj** [comment]
Resolved in #1469 within the botskills CLI (which replaces add_remote_skill)
