### ISSUE TITLE
VS 2019 Preview breaks 'yo botbuilder-assistant:skill'

### ISSUE THREAD

**Issue by EricDahlvang** [microsoft/botframework-solutions#1406]
## Project

**Name**: Skills

**Language**: TypeScript

## Description
This bug report is an fyi (in case others run into this). 

If Visual Studio 2019 Preview is installed, node-gyp cannot find MSBuild.exe

This is a known issue with node-gyp: https://github.com/nodejs/node-gyp/issues/1663

Uninstalling Visual Studio 2019 Preview fixes the issue.

## To Reproduce
Install VS 2019 preview, then run `yo botbuilder-assistant:skill`

## Expected behavior
`yo botbuilder-assistant:skill` works regardless of which versions of Visual Studio are installed.

## Screenshots
![image](https://user-images.githubusercontent.com/11055362/58200905-baa0af00-7c88-11e9-9467-0b2c5e293dfb.png)

## Additional context
Windows 10
Node 10.14.1
npm 6.4.1

**Comment by lauren-mills** [comment]
Added this to our known issues doc: https://github.com/microsoft/botframework-solutions/blob/master/docs/reference/knownissues.md
