### ISSUE TITLE
Issue with installing the Bot Framework (CLI) tool dependencies for the Virtual Assistant walkthrough

### ISSUE THREAD

**Issue by rickengle** [microsoft/botframework-solutions#1408]
## Project

**Name**: 

**Language**: 

## Description
I ran the node package manager command:
5. Download and install the Bot Framework (CLI) tool dependencies. It's important to do this even if you have earlier versions as the Virtual Assistant makes use of the latest capabilities:
npm install -g botdispatch ludown@1.2.0 luis-apis qnamaker luisgen@2.0.2 botskills

But when I run that I get 2 errors which I think relate to already having had earlier versions of the CLI installed:

PS C:\Users\ricke> npm install -g botdispatch ludown@1.2.0 luis-apis qnamaker luisgen@2.0.2 botskills
npm WARN deprecated hoek@5.0.4: This version is no longer maintained. Please upgrade to the latest version.

> luisgen@2.0.2 preinstall C:\Users\ricke\AppData\Roaming\npm\node_modules\luisgen
> node dotnetpreinstall.js

C:\Users\ricke\AppData\Roaming\npm\dispatch -> C:\Users\ricke\AppData\Roaming\npm\node_modules\botdispatch\bin\dispatch.js
C:\Users\ricke\AppData\Roaming\npm\botskills -> C:\Users\ricke\AppData\Roaming\npm\node_modules\botskills\lib\botskills.js
C:\Users\ricke\AppData\Roaming\npm\ludown -> C:\Users\ricke\AppData\Roaming\npm\node_modules\ludown\bin\ludown
C:\Users\ricke\AppData\Roaming\npm\luis -> C:\Users\ricke\AppData\Roaming\npm\node_modules\luis-apis\bin\luis.js
C:\Users\ricke\AppData\Roaming\npm\qnamaker -> C:\Users\ricke\AppData\Roaming\npm\node_modules\qnamaker\bin\qnamaker.js

> luisgen@2.0.2 install C:\Users\ricke\AppData\Roaming\npm\node_modules\luisgen
> dotnet tool install -g LUISGen

Tool 'luisgen' is already installed.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! luisgen@2.0.2 install: `dotnet tool install -g LUISGen`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the luisgen@2.0.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

What’s the best workarounds to resolving these errors so that the prerequisites can be updated properly?

## To Reproduce
npm install -g botdispatch ludown@1.2.0 luis-apis qnamaker luisgen@2.0.2 botskills

**Comment by BeigeBadger** [comment]
I ran into this issue too, the solution was to:

1. Uninstall LUISGen.
* `dotnet tool uninstall -g LUISGen`
2. Check that LUISGen was removed from your global packages.
* `npm list -g --depth 0`
3. Run the npm command again.
* `npm install -g botdispatch ludown@1.2.0 luis-apis qnamaker luisgen@2.0.2 botskills`
4. Happy days.

My understanding is that `npm install luisgen` is a wrapper around `dotnet tool install -g LUISGen` as per [this comment](https://github.com/Microsoft/botbuilder-tools/issues/746#issuecomment-443356434).

**Comment by rickengle** [comment]
Aha.  That did take care of it Matt!   But while LUISGen installed there is still the warning about hoek@5.0.4<mailto:hoek@5.0.4> being deprecated.  Does that warning matter?

PS C:\Users\ricke> npm install -g botdispatch ludown@1.2.0 luis-apis qnamaker luisgen@2.0.2 botskills
npm WARN deprecated hoek@5.0.4: This version is no longer maintained. Please upgrade to the latest version.

> luisgen@2.0.2 preinstall C:\Users\ricke\AppData\Roaming\npm\node_modules\luisgen
> node dotnetpreinstall.js

C:\Users\ricke\AppData\Roaming\npm\dispatch -> C:\Users\ricke\AppData\Roaming\npm\node_modules\botdispatch\bin\dispatch.js
C:\Users\ricke\AppData\Roaming\npm\botskills -> C:\Users\ricke\AppData\Roaming\npm\node_modules\botskills\lib\botskills.js
C:\Users\ricke\AppData\Roaming\npm\ludown -> C:\Users\ricke\AppData\Roaming\npm\node_modules\ludown\bin\ludown
C:\Users\ricke\AppData\Roaming\npm\luis -> C:\Users\ricke\AppData\Roaming\npm\node_modules\luis-apis\bin\luis.js
C:\Users\ricke\AppData\Roaming\npm\qnamaker -> C:\Users\ricke\AppData\Roaming\npm\node_modules\qnamaker\bin\qnamaker.js

> luisgen@2.0.2 install C:\Users\ricke\AppData\Roaming\npm\node_modules\luisgen
> dotnet tool install -g LUISGen

You can invoke the tool using the following command: luisgen
Tool 'luisgen' (version '2.1.0') was successfully installed.
+ luisgen@2.0.2
+ ludown@1.2.0
+ botdispatch@1.4.5
+ luis-apis@2.5.1
+ qnamaker@1.3.0
+ botskills@1.0.0
added 1 package from 1 contributor and updated 6 packages in 28.868s

Thanks,
Rick

**Comment by BeigeBadger** [comment]
Glad to hear that took care of our issue Rick.

As for the deprecation warning there isn't much we can do about it because it will be an explicit dependency of one of the packages being pulled in, so in order to not see this error an update would need to be made to the relevant packages, then a new version published.

I also get that error but don't encounter any obvious issues when running my bot. You could look into force updating that package in your global npm cache but that may have unintended side-effects.

**Comment by lauren-mills** [comment]
Seems like this is resolved. Feel free to reopen if not.
