### ISSUE TITLE
Virtual Assistant doesn't reply on any messages

### ISSUE THREAD

**Issue by vui211** [microsoft/botframework-solutions#1412]
## Project

**Name**: 
Virtual Assistant
**Language**: 
TypeScript
## Description

I've deployed assistant without any issue(all services in place) but when I try to open it from Emulator I get only welcome message. Bot doesn't respond on any message and I can't see any trace from luis or qna. 
Appsettings.json has correct appid and appPassword. 
![image](https://user-images.githubusercontent.com/23225932/58216930-80044880-7d54-11e9-857c-f7e767d5dc04.png)

What am I doing wrong? 
Thanks

## Expected behavior

Bot should reply on base messages

**Comment by darrenj** [comment]
Could you confirm the emulator version please?

**Comment by vui211** [comment]
Hi @darrenj , I use latest one.
![image](https://user-images.githubusercontent.com/23225932/58314624-065b8000-7e64-11e9-9527-3840abe5d6d6.png)

I think I found where issue can be:
Exception has occurred: Error
Error: There is no cognitiveModels value
    at MainDialog.onInterruptDialog (c:\Development\BotDev\VirtualAssistant\fs-vassistant-dev-2\src\dialogs\mainDialog.ts:86:23)

**Comment by vui211** [comment]
@darrenj ,
and this error because of locale variable. For some reasom i18next.language return "en-US" not "en".
Do you have any idea why and how to fix it ?
![image](https://user-images.githubusercontent.com/23225932/58315388-96e69000-7e65-11e9-9a8a-97f17f9138ac.png)

**Comment by vui211** [comment]
I've tried this but it doesn't have any effect
i18next.use(i18nextNodeFsBackend)
.init({
    fallbackLng: 'en',
    **load: 'languageOnly',**
    preload: [ 'de', 'en', 'es', 'fr', 'it', 'zh' ],
    backend: {
        loadPath: path.join(__dirname, 'locales', '{{lng}}.json')
    }
})
.then(async () => {
    await Locales.addResourcesFromPath(i18next, 'common');
});

**Comment by vui211** [comment]
Finally, I've fixed this issue but I think there is a bug in deployment process.
In cognitivemodels.json "defaultLocale" was set as "en-us". I've changed it to "en" and it works as expected. 

{
  "defaultLocale": "en-us", 
  "cognitiveModels": {
    "en": {
      "languageModels": [

**Comment by darrenj** [comment]
@Batta32 can you take a look?
