### ISSUE TITLE
Documentation on how to handle dynamic localisation

### ISSUE THREAD

**Issue by BeigeBadger** [microsoft/botframework-solutions#1413]
## Project

**Name**: Virtual Assistant Template

**Language**: C#

## Description
Need documentation on how localisation works as well as how a dialog could be used to set the locale at run time. I have found [this repo](https://github.com/EricDahlvang/ChooseLanguageBot) that uses v3 of the Bot Framework. [This comment](https://github.com/microsoft/botframework-sdk/issues/3799#issuecomment-346208656) from the author of the above repo says that localisation should "just work" based on the local of the message received - what if a user wants to use a language other than that they are currently running on their computer?

**Comment by stevkan** [comment]
@BeigeBadger, the default language/locale is defined in the DefaultAdapter.cs file in the Virtual Assistant:

```c#
Use(new SetLocaleMiddleware(settings.DefaultLocale ?? "en-us"));
```

If you want to give the user the option to change language, take a look at the 17.multilingual-bot [sample](https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/17.multilingual-bot) from the [BotBuilder-Samples](https://github.com/microsoft/BotBuilder-Samples) repo. It details how you can setup a simple middleware translation service that allows the user to change the language of the bot.

**Comment by BeigeBadger** [comment]
Thanks for the answer @stevkan! The middleware translation service looks really cool. At this stage I'm just looking to use the localised resource files that come packages with the Virtual Assistant Template.

In my `DefaultAdapter.cs` file I never fall through to the default case because `settings.DefaultLocale` always has a value - this is provided from the `cognitivemodels.json` file which is part of the template. The correct localised resource files are used if I set the locale through the Bot Framework Emulator, but if I try to set the locale in the code it is overridden by the emulator setting (which I'm ok with because I understand what is happening).

Is there a recommended approach for allowing the user to change their language on the fly using the resource files rather than a middleware translation service?

**Comment by darrenj** [comment]
Hi,

Changing the locale property on the Activity coming into the Assistant will automatically switch language. You can easily do this using the emulator in settings, if you for example change to de-de, it will automatically use the german responses.

![image](https://user-images.githubusercontent.com/33519520/58704046-98064880-83a2-11e9-9f5f-847ea8ac83b7.png)

The middleware referenced above covers scenarios where locale isn't provided by the end user so can fall back to a default.

You can override the locale whenever you like - you could have a userprofile middleware perhaps that pulls out the users preferred language and change the locale on the incoming activity?
