### ISSUE TITLE
[VA] add remote skill fails for assistant project

### ISSUE THREAD

**Issue by PurnaChandraPanda** [microsoft/botframework-solutions#1422]
Following the [doc](https://github.com/microsoft/botframework-solutions/blob/master/docs/tutorials/csharp/skill.md#adding-your-skill-to-an-assistant), I tried add remote skill to my virtual assistant template. However, I am stuck on the "add_remote_skill.ps1" script run.

```
PS E:\BotSamples\virtual-assistant\cs\VAbotAssistant\VAbotAssistant\VAbotAssistant> .\Deployment\Scripts\add_remote_skill.ps1 -botName "VAbotAssistant" -manifestUrl http://localhost:3979/api/skill/manifest --luisFolder "E:\BotSamples\virtual-assistant\cs\VAbotSkill\VAbotSkill\VAbotSkill\Deployment\Resources\LU\en\"
! Could not find file: E:\BotSamples\virtual-assistant\cs\VAbotSkill\VAbotSkill\VAbotSkill\Deployment\Resources\LU\en\VAbotAssistanten_Dispatch.dispatch. Please provide the dispatchName and dispatchFolder parameters.
```

Once provided dispatchName and dispatchFolder, it failed like:

```
PS E:\BotSamples\virtual-assistant\cs\VAbotAssistant\VAbotAssistant\VAbotAssistant> .\Deployment\Scripts\add_remote_skill.ps1 -botName "VAbotAssistant" -manifestUrl http://localhost:3979/api/skill/manifest --luisFolder "E:\BotSamples\virtual-assistant\cs\VAbotSkill\VAbotSkill\VAbotSkill\Deployment\Resources\LU\en\" --dispatchFolder "E:\BotSamples\virtual-assistant\cs\VAbotAssistant\VAbotAssistant\VAbotAssistant\Deployment\Resources\Dispatch\en\" --dispatchName "VAbotAssistanten_Dispatch"
! Could not find file: VAbotAssistanten_Dispatch\appsettings.json.
```

What am I missing?

**Comment by dfavretto** [comment]
Hi @PurnaChandraPanda, I see you are sending some arguments with double dash (`-`) like the `luisFolder` argument, but the PowerShell Scripts take the argument's names with only one dash, try using the command like this:
```
.\Deployment\Scripts\add_remote_skill.ps1 -botName "VAbotAssistant" -manifestUrl http://localhost:3979/api/skill/manifest -luisFolder "E:\BotSamples\virtual-assistant\cs\VAbotSkill\VAbotSkill\VAbotSkill\Deployment\Resources\LU\en\"
```

**Comment by PurnaChandraPanda** [comment]
Thank you @dfavretto for pointing out right direction! I could do the "sample dialog" test now. On a side note, I had luisgen installed, but not registered in PATH variables. So, had to reboot my machine to get things rolling. Coming to skills customization, the [doc](https://github.com/microsoft/botframework-solutions/blob/master/docs/tutorials/csharp/customizeskill.md) is kept blank. What doc or tutorial to follow if skill customization is goal?

**Comment by dfavretto** [comment]
Hi @PurnaChandraPanda, the team is actually updating the documentation, most of it is already done, but there are some documents missing. @darrenj could you possibly point the right direction here regarding customizing skills?

**Comment by darrenj** [comment]
@PurnaChandraPanda - Did you find a link to that document page or find it in the repo? I'll fix any link because as you have spotted we haven't got to that documentation page yet but @ryanlengel has been working on it.

What did you have in mind with regards to Skill Customisation? As you change the LU file you can use [these steps](https://github.com/microsoft/botframework-solutions/blob/master/docs/tutorials/csharp/customizeassistant.md) to update the LUIS model/dispatch.

**Comment by glennmusa** [comment]
The [pre-reqs download docs](https://github.com/microsoft/botframework-solutions/blob/master/docs/tutorials/csharp/virtualassistant.md#download-and-install) do not explicitly state to install the [dotnet LUISGen tool](https://www.nuget.org/packages/LUISGen/) that the npm wrapper calls and users do hit errors if it is not installed.

**Comment by darrenj** [comment]
@glennmusa - Thanks, the pre-reqs do include luisgen?

```
npm install -g botdispatch ludown@1.2.0 luis-apis qnamaker luisgen@2.0.2 botskills
```

**Comment by spurr82** [comment]
@darrenj  Hi, could you clarify for me, when we add a skill with the add_remote_skill.ps1 do we use the https://bfemailskill.azurewebsites.net/api/skill/manifest location or do we put one into our own solution and then point to that?

**Comment by darrenj** [comment]
your own one!

**Comment by spurr82** [comment]
and is that done by deploying the code found here https://github.com/microsoft/botframework-solutions/tree/master/skills/src/csharp/calendarskill/calendarskill ? there is a link on this page about deployment which is dead

**Comment by darrenj** [comment]
Fixed: https://github.com/microsoft/botframework-solutions/blob/master/docs/reference/skills/productivity-calendar.md
