### ISSUE TITLE
Hardcoding adapter type in auth dialog and couple of other code places

### ISSUE THREAD

**Issue by pvmraghunandan** [microsoft/botframework-solutions#1423]
## Project

Microsoft.Bot.Solutions

**Language**: C#

## Description

The Adapter is hard coded to BotFrameworkAdapter. We couldn't use that as we are using custom adapter built. Instead IUserTokenProvider must be a better choice. Below is code snippet.

`
var adapter = stepContext.Context.Adapter as BotFrameworkAdapter;
var tokenStatusCollection = await adapter.GetTokenStatusAsync(stepContext.Context, stepContext.Context.Activity.From.Id).ConfigureAwait(false);
`

## Expected behavior
Use IUserTokenProvider instead of adapter.

**Comment by darrenj** [comment]
@pvmraghunandan Feel free to submit a PR for the change that would unblock your situation

**Comment by pvmraghunandan** [comment]
@darrenj Done. Sent PR. https://github.com/microsoft/botframework-solutions/pull/1489
