### ISSUE TITLE
ToDo Skill throws

### ISSUE THREAD

**Issue by managedcoder** [microsoft/botframework-solutions#1425]
## Project

**Name**: Skills

**Language**: C#

## Description
When validating the Skill manifest endpoint locally (http://localhost:3980/api/skill/manifest) for latest version of the ToDo Skill a System.ArgumentNullException: 'Value cannot be null. Parameter name: dialogId' is thrown in the constructor of the ToDoSkillDialogBase class at line 54: AddDialog(new MultiProviderAuthDialog(settings.OAuthConnections));

## To Reproduce
1. Grab the latest Bot Framework Solutions and extract the source
2. Open Power Shell Core 6
3. change directory to todoskill project folder (one that hold todoskill.csproj)
4. Run command: Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass
5. Run command: .\Deployment\Scripts\deploy.ps1
6. After deploy.ps1 successfully finishes, open todoskill.csproj in Visual Studio 2019 Enterprise
7. Set Debug | Windows | Exceptions Setting to "Break When thrown" for CLR and C++
7. Set ToDoKkill as StartUp project
8. F5 (run the app) and wait for landing page to come up
9. Browse to http://localhost:3980/api/skill/manifest
10. Its at this point I see System.ArgumentNullException: 'Value cannot be null. Parameter name: dialogId' is thrown in the constructor of the ToDoSkillDialogBase class at line 54: AddDialog(new MultiProviderAuthDialog(settings.OAuthConnections));

## Expected behavior
A clean start and a skill that is ready to be tested

## Screenshots

![image](https://user-images.githubusercontent.com/17769186/58339398-8ad3e180-7e17-11e9-9bfa-d6a1c236feef.png)

## Additional context
None

**Comment by lauren-mills** [comment]
Can you check and see if settings.OAuthConnections has a value? This dialog is created based on the configured oauthSettings in appsettings.json. If there aren't any, it could cause this error.

**Comment by darrenj** [comment]
@managedcoder I think this is related to a bug we fixed last week with the MultiAuthProvider (#1392). It's OK to have the calendar skill deployed without auth configured if it's being used by a VA. Can you try updating the skills and solution nuget package references in your skill project and redeploy. Should unblock your manifest generation step.

**Comment by darrenj** [comment]
alternatively just change the auth connection name to something like "outlook" to unblock the manifest issue.

This will be fixed by #1433

**Comment by managedcoder** [comment]
@darrenj I updated skill and solution packages as suggested up to the latest published NuGet packages (4.4.4) but I still saw the exception being thrown.  Perhaps I needed to move to daily build to get that fix as described?

I then tried your other suggestion and set auth connection name to "outlook" and that worked and it no longer threw an exception.  You can close this issue as far as I am concerned.

Just so you know, I was following the instructions for adding a skill to a bot that I found [here](https://github.com/microsoft/botframework-solutions/blob/master/docs/tutorials/csharp/skill.md) which say you should validate the manifest **BEFORE** adding the skill to your assistant using add_remote_skill.ps1.  That is what I was attempting to do for the todo skill.  I mention this because the fix described in #1433 seems to say that this happens to folks who "are deploying the productivity skills on their own and not adding as a skill."  I am trying to add the skill and still saw that bug and I saw it while following the step-by-step of adding a new skill.  Just want to point that out but in case that mattered (which I don't think it does).

-Russ

**Comment by darrenj** [comment]
Your ahead of me! 4.4.3.2 of .Solutions and .Skills nuget is now live and should resolve the "out of the box" manifest generation exception which then blocked people adding the skill. Docs also updated.

**Comment by darrenj** [comment]
Let us know if you still see the issue after updating
