### ISSUE TITLE
Error with ToDo Skill when deploy.ps1 is run (but found a workaround) 

### ISSUE THREAD

**Issue by managedcoder** [microsoft/botframework-solutions#1426]
## Project

**Name**: Skills

**Language**: C#

## Description
While attempting to deploy.ps1 the ToDo skill I ran into the following error:
*[ERROR]: Nested entity references are not supported in utterance: remove task {TaskContent=go {ListType=shopping} with john this saturday}
Stopping further processing.*

## To Reproduce
1. Grab the latest Bot Framework Solutions and extract the source
2. Open Power Shell Core 6
3. change directory to todoskill project folder (one that hold todoskill.csproj)
4. Run command: Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass
5. Run command: .\Deployment\Scripts\deploy.ps1

Deployment will fail and report:
*[ERROR]: Nested entity references are not supported in utterance: remove task {TaskContent=go {ListType=shopping} with john this saturday}
Stopping further processing.*

I worked around this issue by deleting the nested entity: remove task **{TaskContent=go {ListType=shopping} with john this saturday}** in the **todo.lu** file

## Expected behavior
A clean deployment

## Screenshots

![image](https://user-images.githubusercontent.com/17769186/58342225-210b0600-7e1e-11e9-9151-08d14844e65b.png)

## Additional context
Here is the PowerShell 6 output that shows the steps taken and the error produced:

PS C:\Source\MyFirstVARHW\todoskill\todoskill> Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass
PS C:\Source\MyFirstVARHW\todoskill\todoskill> .\Deployment\Scripts\deploy.ps1
? Bot Name (used as default name for resource group and deployed resources): todoskilldeleteme
? Azure resource group region: westus
? Password for MSA app registration (must be at least 16 characters long, contain at least 1 special character, and contain at least 1 numeric character): pass@word0123456
? LUIS Authoring Region (westus, westeurope, or australiaeast): westus
? LUIS Authoring Key (found at https://luis.ai/user/settings): a2e2f5b113604b209c15a0330726babc
> Creating resource group ...
> Deploying Azure services (this could take a while)...
> Updating appsettings.json ...
Deploying cognitive models ...
> Parsing general LU file ...

     Update available 1.2.0 -> 1.3.1
     Run npm i -g ludown to update.
> Deploying general LUIS app ...
> Parsing todo LU file ...

     Update available 1.2.0 -> 1.3.1
     Run npm i -g ludown to update.
**[ERROR]: Nested entity references are not supported in utterance: remove task {TaskContent=go {ListType=shopping} with john this saturday}
Stopping further processing.
> Deploying todo LUIS app ...
! Could not deploy LUIS model. Review the log for more information.
! Log: C:\Source\MyFirstVARHW\todoskill\todoskill\Deployment\Scripts\..\deploy_cognitive_models_log.txt
! Deployment failed for LUIS app: todo**
> Done.

**Comment by lauren-mills** [comment]
I believe this is caused by having a luDown version <1.3.0. Can you try updating using `npm i -g ludown` and verify if the error is still there?

**Comment by darrenj** [comment]
Confirmed, it's important to follow the pre-reqs as part of the docs :)

![image](https://user-images.githubusercontent.com/33519520/58473818-78bcb080-8141-11e9-8acd-9cd4eaff83be.png)
