### ISSUE TITLE
Unable to add additional QnA Maker or LUIS Endpoint using steps in documentation

### ISSUE THREAD

**Issue by NathanNZ** [microsoft/botframework-solutions#1431]
## Project
Virtual Assistant Template

**Language**: C#

## Description
Additional Knowledge base is not added to the dispatch model when calling the following command

 `update_cognitive_models.ps1 -RemoteToLocal`

The documentation for adding [another QnA endpoint](https://github.com/microsoft/botframework-solutions/blob/master/docs/tutorials/csharp/customizeassistant.md#add-an-additional-knowledgebase) states to call the update_cognitive_models.ps1 script, this doesn't add the new endpoint to the dispatch model and the next step to update the MainDialog.cs file cannot be completed.

## To Reproduce
Follow the documention for adding [another QnA endpoint](https://github.com/microsoft/botframework-solutions/blob/master/docs/tutorials/csharp/customizeassistant.md#add-an-additional-knowledgebase).

Note at the end of step 2, the Luis.DispatchLuis.Intent enum does not update with the new endpoint.

## Expected behavior
Adding a new cognitive model should update the dispatch model as well. This can be tested by investigating the Luis.DispatchLuis.Intent enum as a new intent should be created.

**Comment by litofish** [comment]
Still having issues with this - the dispatch files aren't being updated by the script when trying to add an additional knowledge base

**Comment by darrenj** [comment]
Have you updated the scripts with changes? https://github.com/microsoft/botframework-solutions/blob/master/docs/howto/assistant/updatedeploymentscripts.md
