### ISSUE TITLE
Is there any documentation on generating Skill Manifest and different properties?

### ISSUE THREAD

**Issue by pvmraghunandan** [microsoft/botframework-solutions#1434]
Is there any detailed documentation on Skill manifest and description for each property? Also is there any automatic generation of skill manifest? While developing custom skill, it's very confusing on each property For example "Slots" section.

**Comment by darrenj** [comment]
Does this help?

https://github.com/microsoft/botframework-solutions/blob/master/docs/reference/skills/skillmanifest.md

**Comment by pvmraghunandan** [comment]
Thanks Darren. I will go through the link. Also is there plan to auto generate with help of some tool?

**Comment by darrenj** [comment]
Yes, we plan to support auto generate of action definitions from code in a future release, decorating code with attributes perhaps,
