### ISSUE TITLE
Getting Error When Connecting to PowerBI using API Access Key

### ISSUE THREAD

**Issue by ckalgos** [microsoft/botframework-solutions#1435]
Getting below Error When Connecting to PowerBI using AI API Access Key

A web api key can be used only when web api key name is provided.

Please suggest on how the fix the issue

**Comment by tdurnford** [comment]
Support label to be applied by member of SDK team.

**Comment by dmvtech** [comment]
@saravana13 Which authentication choice are you selecting? Please try using the Organizational Account option if possible and let me know if that works.

**Comment by dmvtech** [comment]
@saravana13 Can you confirm you are still seeing this issue when using Organizational Account?

Additionally, there were some application insight fixes made recently. Please make sure you are using the most recent merged changes. See [here ](https://github.com/microsoft/botframework-solutions/pull/1551)for more info.

**Comment by darrenj** [comment]
Let us know if you have any other questions.
