### ISSUE TITLE
[POI] Replace ActiveRoute.Directions event with OpenDefaultApp that will pass geo URI for client to consume

### ISSUE THREAD

**Issue by Dewain27** [microsoft/botframework-solutions#1443]
POI send event needs to launch the default navigation application with deep link to navigation location.

**Point of Interest Skill**
* When a user selects a route provided by the VA, it will send an event activity with necessary data required for default nav app.

Currently it sends an event `ActiveRoute.Directions` with a JSON payload of Destination and Route Directions. 

- [x] This should be replaced with a new Event:
Name: `OpenDefaultApp`
Value: `geo:latitude,longitude` (coordinates of the destination)

This simplifies integration as it is up to the client to parse how to navigate after receiving instructions from the skill.

**Android App**
- [x] Receive the `OpenDefaultApp` event and consume the parameters required to open default maps app.

**Comment by ryanisgrig** [comment]
@abiemann let's follow up one what data would be required to pass to a default navigation app.
The POI Skill gets both destination and route details, it would be great if the VA could pass on the route details as-is to a maps app.

**Comment by abiemann** [comment]
Using Google Maps:
To [display a map](https://developers.google.com/maps/documentation/urls/android-intents#display_a_map), there are 3 parameters:
latitude (required), longitude (required), zoom (optional)
zoom accepted values range from 0 (the whole world) to 21 (individual buildings)

To launch navigation, there are two approaches:
- requires an address parameter
- or latitude, longitude parameters

To display a street-view:
- latitude, longitude parameters (required). There are also optional parameters: bearing, zoom, tilt

**bearing**: indicates the compass heading of the camera in degrees clockwise from North. True north is 0, east is 90, south is 180, west is 270. Values passed to bearing will wrap; that is, 0°, 360° and 720° all point in the same direction. Bearing is defined as the second of five comma-separated values.
**zoom**: Sets the zoom level of the camera. The default zoom level is set at 0. A zoom of 1 would double the magnification. The zoom is clamped between 0 and the maximum zoom level for the current panorama. This means that any value falling outside this range will be set to the closest extreme that falls within the range. For example, a value of -1 will be set to 0. Zoom is the fourth of five comma-separated values.
**tilt**: specifies the angle, up or down, of the camera. The range is -90 through 0 to 90, with 90 looking straight down, 0 centered on the horizon, and -90 looking straight up.

**Comment by ryanisgrig** [comment]
I've updated the initial issue with more details

**Comment by ryanisgrig** [comment]
@bobokids assigned to you for triaging the POI work detailed in the first comment :)

**Comment by xieofxie** [comment]
It seems that we could not send routes to google map app. So the poi skill simply finishes after choosing the destination and leave routing to the app?

Poi's current location prompt is useless too as 'Directions are always given from the user's current location'.

And since we do not have an android channel now, the skill will behave like this for all channels.

**Comment by ryanisgrig** [comment]
While we want to demonstrate the Azure Maps routing functionality, the reality is we do not have a solution to demo that shows the turn by turn navigation that it offers. Currently all channels cannot do anything with the route data returned, so changing it to return the geo URI of the destination doesn't have an end effect.

The one channel that we *can* demonstrate maps working is on Android where the VA can refer to the default maps application installed. I think in this case the flow should be:
* User asks for a POI
* POI finds locations and user selects one
* POI offers the ETA and shows a route provided by Azure Maps
* User confirms they wish to go there, POI returns the geo URI and allows the client to actually handle the navigation.

@darrenj can you help clarify here? In this case, @abiemann  has configured the VA Chat Client to consume a geo URI and assume it is going to get directions via the user's default app.
