### ISSUE TITLE
[Android App] Wake word detection /with configurable

### ISSUE THREAD

**Issue by Dewain27** [microsoft/botframework-solutions#1444]
Application needs to have a user configurable wake word to have the assistant listen.

**Acceptance Criteria:**
- User should be able to leverage one of the pre-determined wake words in the settings of the Android Application.
- User should be able to say "Wake Word" to initiate the VA to start listening to the user's request
- Wake Word should be running as a service that is always listening for the keyword to be said
- Wake word verification should be done with cloud side KWS from Speech SDK v1.8
- 2 different wake words to choose from for the user
- English required / Use multi-language options if possible

**Sample of Implementation:**
https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/java/android/sdkdemo

**Comment by abiemann** [comment]
this issue is related to https://github.com/microsoft/botframework-solutions/issues/1445

**Comment by ryanisgrig** [comment]
Dependent on Speech Service team's improvement

**Comment by darrenj** [comment]
Let's go ahead with the public wake-word bits we have so we can show the core capability and update when improvements are received. Key to show the capabilities we have available to customers today.

**Comment by darrenj** [comment]
Merged
