### ISSUE TITLE
Cannot deploy a new assistant

### ISSUE THREAD

**Issue by e-gonzalez** [microsoft/botframework-solutions#1448]
## Project

**Name**: Virtual Assistant Deloyment

**Language**: Typescript and C#

## Description

The template "Quickstart: Create your first Virtual Assistant" is the one that correspond to this issue. I am trying to create and deploy an assistant. 
The problem arrives at the 'deply your assistant'. I have just created a a new assistant and the deployment section prompt an error.  

## To Reproduce

To reproduce the issue, you should:
     1. Verify all prerequisites are installed. 
     2. Creat a new assistant according to the instrucctions: 
               npm install -g generator-botbuilder-assistant
               yo botbuilder-assistant
     3. Deploy the assistant according to the instruccion:
               .\Deployment\Scripts\deploy.ps1

## Expected behavior

I have fill all the information and the error prompted in this last step.  

## Screenshots

![image](https://user-images.githubusercontent.com/19410751/58548801-5b074e00-820a-11e9-970f-19df88c8436e.png)

**Comment by darrenj** [comment]
Looks like QnAMaker isn't available in the Azure region you've provided. See https://github.com/microsoft/botframework-solutions/blob/master/docs/howto/assistant/customizedeployment.md for how to customise deployment for the region your using.

**Comment by e-gonzalez** [comment]
Following the link given, I am trying to deploy with westeurope region, which is available in he Azure region. However, the error persists.

**Comment by aschemel** [comment]
Hi! I'm getting the same error, any idea what can be happening? I'm also getting the InvalidApiSetId

**Comment by darrenj** [comment]
Can you both confirm the region you are trying to deploy your assistant into and share the parameters file you are using to override region?

**Comment by e-gonzalez** [comment]
The parameters file I would like to use is :
![image](https://user-images.githubusercontent.com/19410751/58690116-1c4bd200-8389-11e9-8a70-b2660efd289c.png)

The regions I am trying to deploy are 
  - Resource group region: northeurope
  - LUIS Authoring region: westeurope

On the other hand, I had also tried with the default values before changing them.

**Comment by darrenj** [comment]
I can repro the issue with the above parameters file, what's odd is you can create qnamaker with those combinations in the azure portal but we are using the same ARM template approach 

Support Team - can you take a look? @lauren-mills FYI in case you have any ideas. Validation passes and it's almost as if the parameters file is being ignored.

**Comment by lauren-mills** [comment]
I tried the ARM deployment directly in the portal (to verify its not an issue in the scripts) and it is consistent with these errors. My best guess is that westeurope is not being supported by the ARM validation process, even though it is supported in the portal. Probably best to raise this with the QnAMaker team.

**Comment by aschemel** [comment]
Hi @lauren-mills  thanks for taking a look at this, who/how can we get support from the QnA Team?

Thanks

**Comment by guru98** [comment]
I have the same problem. using Westus as region the script continue without error until it switch to the deploy_cognitive_models where it stop with an error like it take wrong paremeters. My question is have you work to some tests before release it.

**Comment by aschemel** [comment]
Hi, the same from our side, it keeps failing even when deploying in USA Regions.

**Comment by lauren-mills** [comment]
@guru98 and @aschemel can you please supply screenshots of your errors and/or your deploy_cognitive_models_log.txt files? If you made it to the deploy_cognitive_models script then your Azure deployment succeeded so it is a different issue.

**Comment by guru98** [comment]
I found the issue: in the file path, in Windows, there is name+space+surname of the user. the space broke the command. I'm not a powershell expert so if someone provide a solution is really apreciate. the issue is when the deploy  script call the deploy:cognitivr_model.ps1

**Comment by guru98** [comment]
<img width="1100" alt="ttt" src="https://user-images.githubusercontent.com/4192718/58835703-f3f8f780-8656-11e9-913f-dc43d15343fe.png">

**Comment by guru98** [comment]
deploy_cognitive_log is not generated becouse it crash eariler (line1 char1). im the screen shot after upating appsetting.json (that works succesfully) i had a write-host to see what you call ….

**Comment by aschemel** [comment]
@lauren-mills In our case, we ended up creating a new RG in West US, and deploying (per defaults) everything in it. We are Europe based, so it's not a solutions for us. We'll keep testing like this for the moment. Also I think guru98 case is a bit different.

**Comment by darrenj** [comment]
@aschemel - Thanks for confirming. We are working with the qnamaker team on why the ARM template deployment isn't working in the european regions. #1473 to track. I've validate the "workaround" in that item.

**Comment by darrenj** [comment]
@guru98 Please see #1474 - if you update your deploy.ps1 script to add single quotes around the outdir parameter I think that will fix. If you can confirm, we'll make the change.

**Comment by darrenj** [comment]
@aschemel PR #1476 updates the template.json file to reflect the latest from the QnAMaker team that the core engine of QnAMaker can only be created in westus, all other bits (that hold your kb data) can be in other regions.

**Comment by darrenj** [comment]
@guru98 PR #1476 has a proposed fix for your path issue.
