### ISSUE TITLE
Add previously asked questions to returning user intro card

### ISSUE THREAD

**Issue by darrenj** [microsoft/botframework-solutions#1460]
A user returning to a Bot may wish to perform the same types of tasks each time, to make the experience more personalised we could provide intro card buttons or suggested actions for recent questions so they can get started quickly.

**Describe the solution you'd like**

If we have middleware to store common questions (and the skill/luis intent that resolved it correctly) into the user profile store we can easily light this type old capability up. We need to be careful to not have multiple entries for the same dialog/intent hence it's key to have both utterance+intent so we can de-dupe and also age things so that after a configurable window we'll remove this and not show them.

**Comment by ryanisgrig** [comment]
@darrenj this sounds like the sample I mocked up a while back where a VA can dynamically generate some quick actions based on connected skills - is this the same?

**Comment by darrenj** [comment]
Being resolved with adaptive card redesign
