### ISSUE TITLE
Cant get the right response

### ISSUE THREAD

**Issue by D33TW0** [microsoft/botframework-solutions#1464]
i deployed the Assistent 1:1 like the manual, but the bot allways responses with the Error Response.
(It is in german because i live there (obviously))

![botemulator-chat](https://user-images.githubusercontent.com/39704877/58750031-2ce57080-848d-11e9-9158-d55ba48e1cd8.png)

The bot should response with the QnA-KnowledgeBase data but it keeps saying "Sorry, it looks like something went wrong."

![qna-KB](https://user-images.githubusercontent.com/39704877/58750057-85b50900-848d-11e9-8416-5eec3e28bd59.png)

I changed nothing in the code. I hope one of you can help me out :-)

**Comment by lauren-mills** [comment]
Looks like it can't find any German language models. If you want to deploy your luis and qna models in German, you can run the deploy_cognitive_models.ps1 script with the -languages parameter like this:

*Run this from the project directory
```
.\Deployment\Scripts\deploy_cognitive_models.ps1 -languages "de-de"
```
