### ISSUE TITLE
Mail skill deployment error missing mail.luis file. Nested entity references are not supported in utterance

### ISSUE THREAD

**Issue by gagankohli2000** [microsoft/botframework-solutions#1465]
Mail skill deployment error missing mail.luis file

Error
ENOENT: no such file or directory, stat 'C:\GitHub\botframework-solutions\skills\src\csharp\emailskill\emailskill\Deployment\Resources\LU\en\email.luis'

Upon further investigation error is due to nested entity reference not supported for - delete the email sent from {SenderName={FromRelationshipName=mary} jane}

**Comment by darrenj** [comment]
I suspect this is an issue with the pre-reqs? Can you check your ludown version?

`ludown -v`

You should have 1.3.1  - this can be installed `npm install -g ludown`

**Comment by gagankohli2000** [comment]
Thanks. It's working fine now.
