### ISSUE TITLE
Teams not rendering Adaptive Cards used in Productivity and PoI Skills

### ISSUE THREAD

**Issue by darrenj** [microsoft/botframework-solutions#1467]
## Project

Skills

## Description

When using the Productivity and PoI skills within Teams the Adaptive Cards do not render at all, the skills are still functional but lacking the visual cues that are key to certain tasks. Other channels, e.g WebChat work fine.

## To Reproduce

Use VA/Skills within Teams

## Expected behavior
- Cards to render, down-leveling if needed.

## Screenshots
![image](https://user-images.githubusercontent.com/33519520/58793485-215d8b00-85ee-11e9-9547-d58b9cdf725a.png)

## Additional context
- Working with the Teams team to ascertain the underlying issue and identifying a workaround (change the adaptive card JSONs to "down-grade" them.

**Comment by ryanisgrig** [comment]
Related to #1394

**Comment by gagankohli2000** [comment]
Hi Lauren,

Do we have timeline for next release?

Regards,
Gagan Kohli

**Comment by xieofxie** [comment]
It may be caused by the followings:
1. Rendering of svg is not fully supported everywhere. For example, [CalendarDetailContainerParticipantsLess.json](https://github.com/microsoft/botframework-solutions/blob/master/skills/src/csharp/calendarskill/calendarskill/Content/CalendarDetailContainerParticipantsLess.json) could be rendered correctly in Edge by [designer](https://adaptivecards.io/designer/), but not in Chrome(the 2nd svg is missing);
2. Teams uses adaptivecards with version less than 1.2 until when background images are full bleed.

**Comment by darrenj** [comment]
@gagankohli2000 - The way forward for now would be for you to make changes to the adaptive card JSON files in each of the skills which you'd likely do for branding purposes anyway. For example if you removed the SVG parts the cards do render. You can also use the Card Editor in Teams - App Studio to test adaptive card designs.

**Comment by darrenj** [comment]
Update - SVG rendering is not supported by Teams so we are working on adaptive card design changes to not rely on these and improve rendering in dark/light modes.

**Comment by samaea** [comment]
Hi Darren - any rough ETA on this by any chance? Or perhaps guidance on how to remove the SVG parts (assuming it's easy to do). Thanks!

**Comment by darrenj** [comment]
You can track progress on [this PR](https://github.com/microsoft/botframework-solutions/issues/1394). Search and PoI skills are updated. PR also has manual steps if you prefer to do it ahead of this.

**Comment by darrenj** [comment]
Now merged in

**Comment by kafka-yu** [comment]
> Update - SVG rendering is not supported by Teams so we are working on adaptive card design changes to not rely on these and improve rendering in dark/light modes.

Hi darrenj 
May I ask do you know if Teams has any plan to support SVG rendering?
Thanks.
