### ISSUE TITLE
VA deployment fails in Europe due to QnAMaker dependency

### ISSUE THREAD

**Issue by darrenj** [microsoft/botframework-solutions#1473]
## Project

Virtual Assistant 

## Description
When deploying Virtual Assistant in say `northeurope` deployment fails with QnAMaker not existing in the region.

![image](https://user-images.githubusercontent.com/33519520/58870392-07887a80-86b8-11e9-9183-c271a3c4c037.png)

However QnAMaker does exist in the region (northeurope and westeurope), also the template group validation step passes ahead of deployment - this step would catch things not available in region). Also executing the ARM template within Azure without our deployment scripts yields the same error.

We are investigating with the QnAMaker team, in the meantime this workaround can be used whereby VA is deployed into europe for example but QNAMaker is in US.

Use the [parameters file](https://github.com/microsoft/botframework-solutions/blob/master/docs/howto/assistant/customizedeployment.md) which already has overrides to westus for qna. You can change this file and update appInsights to be northeurope rather than US. 

Then use this parameter on the deploy file
```
.\Deployment\Scripts\deploy.ps1 -parametersFile .\Deployment\Resources\parameters.template.json
```

## To Reproduce
- Deploy VA to the westeurope region using the usual instructions.

## Expected behavior
- Deployment to work to Europe and other regions where QnAMaker is present.

**Comment by nrobert** [comment]
Thanks Darren, that's exactly what I faced yesterday and how I fixed it also!
