### ISSUE TITLE
Power BI Conversational Analytics Sample User Utterance field not dispaying in Transcript report

### ISSUE THREAD

**Issue by QuantumChar** [microsoft/botframework-solutions#1484]
## Project

**Name**: ConversationalAnalyticsSample_4_4.pbit (Conversational Analytics Power BI sample)

**Language**: N/A

## Description
When you connect Application Insights to the Power BI sample ConversationalAnalyticsSample_4_4.pbit and open the Transcript tab the User Utterance field does not display the utterances. 

## To Reproduce
Download the Power BI sample here (https://github.com/microsoft/botframework-solutions/blob/master/solutions/analytics/ConversationalAnalyticsSample_4_4.pbit). Use your Application Insights Application Id from the Portal (API Access tab under the Application Insights service). 

## Expected behavior
Once connected to the Power BI report and you navigate to the Transcripts tab, you should see the User Utterances displayed for the appropriate Bot Responses.

**Comment by ryanisgrig** [comment]
Most likely blocked by #1360
