### ISSUE TITLE
[Automotive Skill] Broaden available Vehicle Settings

### ISSUE THREAD

**Issue by darrenj** [microsoft/botframework-solutions#1486]
## User Story
As ...
I want ...
so that ...

## Acceptance Criteria 
*List your requirements.*
- [ ] ...
- [ ] ...
- [ ] ...

## Resources
*Provide any screenshots or conversation mockups to support your request.*
*Learn how to mock up bot conversations with [.chat files](http://aka.ms/bfchatfile).*

## Notes
*Provide any additional information.*

The Automotive Skill has a initial set of Vehicle Settings encoded in a YAML file located [here]. This should be reviewed and expanded with a broader set of vehicle controls based on our experience in this case.

The LUIS model and setting validation work hand in hand so should not require LUIS model changes but this can be reviewed once the YAML files are updated.

**Describe the solution you'd like**
All core vehicle settings work out of the box.

**Additional context**
See [this documentation item](https://github.com/microsoft/botframework-solutions/blob/master/docs/reference/skills/automotive.md) for information on customizing vehicle settings

**Comment by Dewain27** [comment]
@darrenj is this a duplicate of #929

**Comment by darrenj** [comment]
Not a priority
