### ISSUE TITLE
Skill deployment fails due to "Database account is not online"

### ISSUE THREAD

**Issue by BeigeBadger** [microsoft/botframework-solutions#1492]
## Project

**Name**: Skills 

**Language**: C#

## Description
Deploying Skill fails with "Database account XXXX is not online". The deploy log is also empty. I remember reading something in the last month or so, I cannot remember if it was a commit message or on a GitHub issue around the deploy script being updated to handle the fact that CosmosDB takes a while to provision, there was some kind of debounce that was added to account for this fact, perhaps the skills deployment script also needs this added.

## To Reproduce
1. Run deploy script for skill and pass in a value for the `-resourceGroup`
* i.e. deploying to an existing resource group
2. Fill out required details in prompts.
3. Deploy fails.

## Expected behavior
Deploy succeeds

## Screenshots
![https://i.imgur.com/hIg1HkU.png](https://i.imgur.com/hIg1HkU.png)

## Additional context
```
Deployment failed. Correlation ID: 2e2803c6-0a9e-4705-be55-07f374970b7c. {
  "code": "BadRequest",
  "message": "Database account xxx-yyyskill is not online\r\nActivityId: 85f21dd1-d218-487c-9861-4526162846fe, Microsoft.Azure.Documents.Common/2.4.0.0"
}
! Deployment failed. Please refer to the log file for more information.
! Log: C:\Users\mastan\Documents\repos\client\redacted\ChatBot.Skills.redacted\Deployment\Scripts\..\deploy_log.txt
+ To delete this resource group, run 'az group delete -g redacted --no-wait'
PS C:\Users\mastan\Documents\repos\client\redacted\ChatBot.Skills.redacted>
```

**Comment by darrenj** [comment]
There was an issue with QnaMaker reporting it was created before it actually was, this caused an issue as we then deployed things to QnAMaker. For cosmosdb we don't and this is actually being thrown as part of the "contained" ARM deployment of CosmosDb - we just submit an ARM deployment and away it goes. I wonder if it might have been a transient issue, if you deploy again do you reliably get the error?

Let me know, either way I can ask the CosmosDB team to take a look. I've validated it's nothing to do with `-` in the name or too long.

Also just want to check you don't have the version of the Skills VSIX from around 2 weeks ago that did have an issue with resourcegroup - it was a different issue but you can check here: https://github.com/microsoft/botframework-solutions/blob/master/templates/Skill-Template/csharp/Sample/SkillSample/Deployment/Scripts/deploy.ps1

**Comment by lauren-mills** [comment]
Closing this for now, as it seems like an intermittent service failure. If you continue to experience this error, please reopen.

**Comment by BeigeBadger** [comment]
Thanks for looking into this @darrenj. Unfortunately I'm snowed under so don't have time to investigate any further. I will re-open the issue in the future if it is still an issue.

**Comment by darrenj** [comment]
Please do - I was able to deploy in australia without any changes so hopefully just transient

**Comment by j03INTHECLOUD** [comment]
I am still seeing this issue

**Comment by a-vishar** [comment]
I am also facing this issue, 5+ failed deployments, this doesn't seem transient.

**Comment by darrenj** [comment]
Could you confirm the region you are trying to deploy to please? Changes were made to the scripts some months back to accommodate long-running deployments (further back off retries) and there were some live outages which triggered some further issues. Happy to try and repro.

Assuming you have the most recent template, if it's an older project you might want to update deployment scripts as per section in [this document](https://microsoft.github.io/botframework-solutions/virtual-assistant/handbook/deployment-scripts/)
