### ISSUE TITLE
react to additional received activity types, i.e. show dialer

### ISSUE THREAD

**Issue by abiemann** [microsoft/botframework-solutions#1497]
this ticket is written as a result of PR https://github.com/microsoft/botframework-solutions/pull/1493

This applies to:
SpeechService.onActivityReceivedEvent() - for widgets / no UI visible
MainActivity.onActivityReceivedEvent() - for when UI is visible

Feedback:

> Should we not also have the poi event hooked up here too and fire navigation deep link
> 
> Also see this event which gives you a number to dial when joining a meeting: https://github.com/microsoft/botframework-solutions/blob/master/skills/src/csharp/calendarskill/calendarskill/Dialogs/ConnectToMeetingDialog.cs#L404

**Comment by darrenj** [comment]
Resolved
