### ISSUE TITLE
Deployment fails on validation when name value has dashes.

### ISSUE THREAD

**Issue by dmvtech** [microsoft/botframework-solutions#1500]
## Project

Virtual Assistant

**Language**: C#

## Description
When running deployment script and using a name that has a dash (-) character, it will fail with the error:

`! Template is not valid with provided parameters.`
`! Error: The template deployment 'deployment_dry_run' is not valid according to the validation procedure. The tracking id is '<GUID>'. See inner errors for details. Please see https://aka.ms/arm-deploy for usage details.`

## To Reproduce
```
$appdisplayname = 'v-myassistantname'
$apppassword = 'AtLeastSixteenCharacters_0'
$resourcegroup = "v-myassistantRG"
$serviceplanloc = 'westus'

.\Deployment\Scripts\deploy.ps1 -name $appdisplayname -resourceGroup $resourcegroup -location $serviceplanloc -appPassword $apppassword -luisAuthoringKey $luisauthkey -luisAuthoringRegion $serviceplanloc ;write-host "done"
```

## Expected behavior
Either throw better error to disallow dashes in 'global' name or assert/handle for resources where dash isn't allowed (storage account)

**Comment by stepknees** [comment]
I'm getting this same error but my name doesn't contain a dash. Any idea what else could be triggering this?

**Comment by lzc850612** [comment]
Do you think the azure subscription you're deploying your VA to might have a resource limit (amount of certain types of resources allowed such as CosmosDB)? Often this error could lead to that as well.

**Comment by lauren-mills** [comment]
Just completed a deployment with dashes in the name so I suspect this is likely due to a conflict between existing services with the same name. I'm making a change in the scripts to write out the full validation error to deploy_log.txt which should give more info on these errors in the future. Stay tuned.

**Comment by tamerin-tech** [comment]
This is great! very useful! @lauren-mills is there any easy way to update the deployment scripts I'm using that were generated by a bit older VA Template (before this change for example)? For now I just created a new sample project (VA Template) and copied the new deployment scripts into my project, but maybe there's a more simple way?
