### ISSUE TITLE
"Customize your Virtual Assistant" Tutorial: document customizing the existing knowledge base

### ISSUE THREAD

**Issue by fractalcrafter** [microsoft/botframework-solutions#1502]
In the "Customize your Virtual Assistant" Tutorial, we currently describe how to add a knowledge base, but sometimes, the customization is to update the existing knowledge base (FAQ or chitchat, thus will be good to update the Tutorial to also include a section to describe how to update the existing FAQ and ChitChat and then update dispatch:
* For FAQ, this could be extracting the FAQ from their existing website, or PDF or other source (this can point to the QnAMaker extraction related documentation), and then replace the existing FAQ with the newly extracted pairs 
* For ChitChat, this could be customizing the response of the existing ChitChat questions

Or alternatively, customers may add a new knowledge base but then want to remove the existing FAQ and/or ChitChat, thus should also include documentation on how to update to remove certain knowledge source.

**Comment by ryanisgrig** [comment]
We should defer to official QnA docs for updating ChitChat/FAQ knowledge bases rather than provide our own explanation.

For changing dispatch links to KBs, unless we need to use our own scripts for it we should also defer to the official `botbuilder-tools` docs

**Comment by mbwatty** [comment]
I am having trouble following the tutorial for adding a new KB. I get stuck at 

"Update the ./src/dialogs/mainDialog.ts file to include the corresponding Dispatch intent for your new QnA source following the example provided." 

When I add the new 'else if' statement I get a cyclomatic complexity error when I try and build. 

Am I missing something here?
