### ISSUE TITLE
BotSkills problem disconnecting skill, parameter --language

### ISSUE THREAD

**Issue by FreddyAyala** [microsoft/botframework-solutions#1503]
Currently I've been trying to disconnect a skill from my chatbot using the command:

 botskills disconnect -i toDoSkill --cs

But it didn't work because my default language is french and is requesting for the dispatchName and folder, even after providing this it doesn't work.

What is is required to make it work is to add the parameter --language, that it is not recognised.

When modifying this line inside botskills-disconnect:

const language = args.language || 'fr-FR';

It correctly disconnects the skill, what we need to do is to in order to correct it is to add the argument --language

Thanks

**Comment by dfavretto** [comment]
Hi @FreddyAyala, thanks for reporting this! For some reason it was [removed accidentally](https://github.com/microsoft/botframework-solutions/commit/6849ee2539aa1af08aa8a899f195a178728c1414#diff-68e0a5335e3d1adbe0e666fdd65f0762L36), so we'll be creating a PR for adding this argument again and fixing this as soon as possible.

In the meantime, passing in the argument `--dispatchFolder` pointing to your Dispatch Folder where your `.dispatch` file is located should work successfully. Please let us know If it doesn't work or you have any other problem.
