### ISSUE TITLE
Need instruction about how to link Calendar skills to a goolge account

### ISSUE THREAD

**Issue by allenwux** [microsoft/botframework-solutions#1506]
**Is your feature request related to a problem? Please describe.**
There's no document to show how to link Calendar skill to a google account

**Describe the solution you'd like**
Need some instruction 

**Describe alternatives you've considered**
Or you can share the link if it already exists

**Additional context**

**Comment by lauren-mills** [comment]
@DingmaomaoBJTU can you (or Yue) add the instructions here or in this doc? https://github.com/microsoft/botframework-solutions/blob/master/docs/reference/skills/productivity-calendar.md

**Comment by KayMKM** [comment]
the doc has been updated: https://github.com/microsoft/botframework-solutions/pull/1527
