### ISSUE TITLE
Add support for National Clouds (US Gov, etc.)

### ISSUE THREAD

**Issue by stevengum** [microsoft/botframework-solutions#1507]
## User Story
**As a** gov customer
**I want** to deploy VA in National Cloud
**so that** I can use VA for my scenarios

## Acceptance Criteria 
*List your requirements.*

- [ ] Updated ARM templates that configure the correct environment variables for a given National Cloud
  - [ ] This is either a new parameter or a new ARM template
- [ ] C# needs to be bumped to 4.4.5 (when this is cut)
   - [ ] And use the `BotFrameworkHttpAdapter` constructor that takes an `IConfiguration` ([relevant code][new-csharp-constructor])
- [ ] Update TS to 4.5.0 (July)
   - [ ] The updated `BotFrameworkAdapter` will either taken in the necessary openIdMetadata and channelService or read it from the environment variables in the constructor.

## Resources
*Provide any screenshots or conversation mockups to support your request.*
*Learn how to mock up bot conversations with [.chat files](http://aka.ms/bfchatfile).*

## Notes
*Provide any additional information.*

The configuration in an ARM template and the `.ps` scripts don't appear to account for US Gov ([National Cloud](https://docs.microsoft.com/en-us/graph/deployments)) support.

## Additional context
DCR For BotFrameworkAdapter changes: **microsoft/botframework-sdk#5417**
C# .netcore PR with new constructor to take `IConfiguration`: **microsoft/botbuilder-dotnet#1926**

### Optional Reading:
microsoft/BotBuilder-Samples#1556
microsoft/BotBuilder-Samples#1519
microsoft/BotBuilder-Samples#1516

  [new-csharp-constructor]: https://github.com/microsoft/botbuilder-dotnet/commit/2cbdea451cb8f534e3457b09dc8f5541bda5f009#diff-b226ba3ec1af2cb2820b4ce66e56149bR22

**Comment by darrenj** [comment]
Resolved
