### ISSUE TITLE
Use ChoiceFactory when creating cards

### ISSUE THREAD

**Issue by EricDahlvang** [microsoft/botframework-solutions#1508]
## User Story
As bot developer
I want to use ChoiceFactory to create choice prompts
so that the UI experience will automatically adjust for all the different channels

## Acceptance Criteria 
*List your requirements.*
- [ ] Consistent use in VA, Skill Template, and Skills
- [ ] ...
- [ ] ...

## Resources
*Provide any screenshots or conversation mockups to support your request.*
*Learn how to mock up bot conversations with [.chat files](http://aka.ms/bfchatfile).*

## Notes
*Provide any additional information.*

**Is your feature request related to a problem? Please describe.**
Some channels do not support SuggestedActions.  ChoiceFactory will attempt to determine if the channel supports them, and if not it will create something the channel is able to render.

**Describe the solution you'd like**
Instead of creating [SuggestedActions](https://github.com/microsoft/botframework-solutions/blob/master/templates/Enterprise-Template/src/csharp/EnterpriseBotTemplate/EnterpriseTemplate/Dialogs/Main/MainResponses.cs#L89) directly, use the [ChoiceFactory](https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder.Dialogs/Choices/ChoiceFactory.cs) which will create a card based on the channel.

**Comment by xieofxie** [comment]
It is very useful. Is it possible to use the logic in ForChannel to check [ListStyle](https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder.Dialogs/Choices/ListStyle.cs)? So fallback could be used in functions like [AppendChoices](https://github.com/microsoft/botbuilder-dotnet/blob/3397372171a188821f1ef3d65d6e92bee3b30965/libraries/Microsoft.Bot.Builder.Dialogs/Prompts/Prompt.cs#L141).

**Comment by darrenj** [comment]
Merged
