### ISSUE TITLE
Deployment instructions suggestion

### ISSUE THREAD

**Issue by jwiley84** [microsoft/botframework-solutions#1509]
**Problem:** Attempting to deploy using the 'how to deploy' instructions in the various readme's.

As someone who doesn't know how to read powershell, when I attempted to deploy my bot, I wanted to avoid the powershell script; had there been any errors when running the script, I would not have known where to go looking for them. Instead, I attempted to deploy using the ARM template included with the vsix template. I ran into issue after issue because the ARM template required portions of the powershell script to be run before it was run, but there was insufficient information to outline this.

I moved over to the Bot Framework SDK's 'How to Deploy Your Bot' doc, but their doc only covers how to use the ARM template included with the bots provisioned through their vsix template; attempting to follow them but with a VA bot returns fun errors such as "Expecting value: line 1 column 1 (char 0)" and "Azure Error: InvalidTemplate
Message: Deployment template validation failed: 'The template resource 'name' at line '1' and column '197' is not valid: The template function 'RESOURCEGROUP' is not expected at this location."

There are going to be other users that might want to avoid the powershell script, and having the template.json file rely on it is going to cause problems.

**Comment by lauren-mills** [comment]
Will add this to the docs, but for right now here are the rough steps:

# Virtual Assistant: Manual Deployment Steps

1. Create MSA App Registration
    - Option 1: Create registration using az cli
    - Option 2: Create registration manually in Azure Portal
2. Deploy ARM template with parameters
    - Option 1: Deploy arm template using az cli
    - Option 2: Deploy arm template using Azure Portal
3. Update appsettings.json with configuration
    - Microsoft App Id and Password, Cosmos DB, Application Insights, Blob Storage
4. Deploy LUIS models
    - Option 1: Deploy with BF CLI tools
        - Run ludown parse
        - Run luis import command
        - Run luis train command
        - Run luis publish command
        - Run luisgen tool
        - Add configuration to cognitivemodels.json file
    - Option 2: Deploy manually to LUIS portal
        - Run ludown parse
        - Import json file into portal
        - Train
        - Publish
        - Add configuration to cognitivemodels.json file
5. Deploy QnA Maker knowledgebases
    - Option 1: Deploy with BF CLI tools
        - run ludown parse command
        - run qnamaker import command
        - run qnamaker train command
        - run qnamaker publish command
        - Add configuration to cognitivemodels.json file
6. Create Dispatch model
    - Add sources
    - Run dispatch create
    - Run luisgen tool
    - Add configuration to cognitivemodels.json file

**Comment by jwiley84** [comment]
You are awesome.
