### ISSUE TITLE
New Skill deployment issue

### ISSUE THREAD

**Issue by gagankohli2000** [microsoft/botframework-solutions#1519]
I have created a new skill using skill template but during deployment I'm getting below error

> Creating resource group ...
> Validating Azure deployment ...
! Template is not valid with provided parameters.
! Error: The template deployment 'deployment_dry_run' is not valid according to the validation procedure. The tracking id is 'aa708db9-0a99-47a6-b98a-0d577382cfc4'. See inner errors for details. Please see https://aka.ms/arm-deploy for usage details.
+ To delete this resource group, run 'az group delete -g  --no-wait'

![validating](https://user-images.githubusercontent.com/14933211/59267982-02ff2b80-8c8f-11e9-8025-51bacda56477.png)

**Comment by darrenj** [comment]
Can you share the parameters you passed to the deploy script please so we can better diagnose?

**Comment by higoorc** [comment]
Try to run Powershell as administrator and do it again.

**Comment by lauren-mills** [comment]
Can you also check the number of azure search instances you have deployed in your subscription?

**Comment by darrenj** [comment]
Let us know if you are still experiencing issues, also make sure you have the latest deployment scripts
