### ISSUE TITLE
Reply with 1 or 2 in a ConfirmPrompt doesn't work

### ISSUE THREAD

**Issue by lzc850612** [microsoft/botframework-solutions#153]
**Description**

Any time in a cancel prompt, user cannot successfully cancel using 1 or 2 as response. It also keeps adding up on the cancel prompt message.

**To Reproduce**
1. Type in 'Cancel' and send the message
2. Cancel prompt will render to ask if we confirm to cancel. The message is (1) yes or (2) no
3. Type in 1 or 2 and send the message

**Expected behavior**
succeed to cancel

**Actual behavior**
Cancellation failed. Keep getting asked whether or not to cancel, and the message keeps adding more text every time user answers with 1 or 2

**Comment by darrenj** [comment]
I think this is because cancel was going to the calendar dialog. Cancel dialog is now removed from the LU model for calendar and dispatcher so that shouldn't happen now. assistant level cancel prompt doesn't  use numbers so pretty sure that's where its coming from

**Comment by ryanisgrig** [comment]
It appears to be with [ConfirmPrompt](https://github.com/Microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder.Dialogs/Prompts/ConfirmPrompt.cs). [This](https://github.com/Microsoft/botbuilder-dotnet/pull/1024) fix was recently merged, it may be our botbuilder version.

**Comment by lauren-mills** [comment]
Now that 4.1 is out we should update all the projects and see if this is still an issue. If so, I have a fix in the Customer Support Template

**Comment by ryanisgrig** [comment]
I've updated to `4.1.5` and this works.
