### ISSUE TITLE
add channelId in functions like ResponseManager.GetResponse

### ISSUE THREAD

**Issue by xieofxie** [microsoft/botframework-solutions#1531]
**Is your feature request related to a problem? Please describe.**
suggestedActions are not supported on all channels.

**Describe the solution you'd like**
use similar mechanism in [ChoiceFactory](https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder.Dialogs/Choices/ChoiceFactory.cs).

**Additional context**
related #1508

**Comment by lauren-mills** [comment]
Our response management will soon be replaced by Language Generation (see: https://github.com/Microsoft/BotBuilder-Samples/tree/master/experimental/language-generation) so we won't add this feature. But we will be moving to choicefactory as per the linked issue.
