### ISSUE TITLE
Virtual Assistant Teams Registration

### ISSUE THREAD

**Issue by spurr82** [microsoft/botframework-solutions#1533]
How is this VA registered so it can be used in teams? I cant find any doco on this. When i click manage in Azure portal for my bot i get taken to an app reg page where it says it cannot find my app???

**Comment by darrenj** [comment]
Hi - just like any other Bot, some instructions are here: https://docs.microsoft.com/en-us/microsoftteams/platform/get-started/get-started-app-studio.  Hope that helps

**Comment by spurr82** [comment]
Hi, yeh I get that part, but dont you have to do some app registration in Azure first? there seem to be many app reg portals, in azure then in https://apps.dev.microsoft.com when i create a bot in azure it creates an app reg in https://apps.dev.microsoft.com, but when i deploy the VA it doesnt? it does it somewhere else

**Comment by darrenj** [comment]
App registration is done as part of VA when you deploy your Bot using the script, there are no further manual steps required. Note that app registration is now done inside Azure portal (Azure Active Directory - App Registrations) and the apps.dev portal is being retired.
