### ISSUE TITLE
Error when dispatcher directs to QnA and no QnA pair found

### ISSUE THREAD

**Issue by ericchansen** [microsoft/botframework-solutions#1537]
## Project

**Name**: Virtual Assistant

**Language**: C#

## Description

There's a strange bug in the framework internals when you send a message whose body is only `you`.

Here's what I think is going on. The dispatcher directs `you` to the QnA service, but the QnA service comes up empty. I don't think that situation is handled.

## To Reproduce

1. Create a new Virtual Assistant from the template.
2. Deploy.
3. Run and open the emulator.
4. Send a message that only contains the text `you`.

## Expected behavior

The bot's confused response.

## Screenshots

![image](https://user-images.githubusercontent.com/5395779/58912910-c6589080-86e0-11e9-8b8e-a2c7ce53ad09.png)

## Additional context

None.

**Comment by jwiley84** [comment]
Possibly related to this? https://github.com/microsoft/botbuilder-dotnet/issues/1903

**Comment by gabog** [comment]
Hi @lauren-mills , can you give us a repro so we can address this one in the SDK

**Comment by darrenj** [comment]
Can you confirm this is now fixed in [2038](https://github.com/microsoft/botbuilder-dotnet/issues/2038)? If so, can you point at the myget build it's in and we can validate it's resolved
