### ISSUE TITLE
Mac OSX - yo botbuilder-assistant EACCESS Issue

### ISSUE THREAD

**Issue by thegoo** [microsoft/botframework-solutions#1542]
## Project

**Name**: Virtual Assistant 

**Language**: TypeScript

## Description
When executing yo botbuilder-assistant a number of EACCESS errors are raised.  This occurs when executing the command using **sudo** or **sudo -s** commands.

## To Reproduce

- Follow pre-requisite configuration steps

- Execute command **sudo yo botbuilder-assistant**

## Expected behavior

Yeoman to execute without error.
## Screenshots
![image](https://user-images.githubusercontent.com/7401156/59454033-3781fd00-8ddf-11e9-87a2-992b9271911d.png)

**Comment by Batta32** [comment]
Hi @thegoo,

**First of all, if you are not using a node version manager, we recommend that you use [nvm](https://github.com/nvm-sh/nvm) and install the latest version of nodejs and npm.** 

These types of problems are related to the **permissions in your home directory**. To resolve your problem, try to restore the ownership of the folders related to the user's NPM to the current user:
> sudo chown -R $ (whoami) ~ / .npm

If that solution does not solve the problem, try:
> sudo npm cache clean --force --unsafe-perm

**Comment by thegoo** [comment]
Thanks for the reply @Batta32... the above did not resolve the issues.

I am closing the issue... this does not appear to be a tool issue but local environment.

Thanks for the support!
