### ISSUE TITLE
Deployment failing on Windows VS 2017

### ISSUE THREAD

**Issue by Dewain27** [microsoft/botframework-solutions#1543]
When trying to build the solution after following directions.  I get the following error:
![image](https://user-images.githubusercontent.com/18688053/59454762-69dc2c00-8dd8-11e9-8364-6d9cf6939a69.png)

Visual Studio 2017

**Comment by ryanisgrig** [comment]
@Dewain27 you set the LUIS authoring region as your authoring key. It needs to be westus, westeurope, or australiaeast.

**Comment by lauren-mills** [comment]
Figured out this is caused by the subscription having too many azure search services. Need to try in a different subscription.

**Comment by Dewain27** [comment]
New subscription fixed the issue.
