### ISSUE TITLE
Cancel doesn't check for an active dialog

### ISSUE THREAD

**Issue by lzc850612** [microsoft/botframework-solutions#155]
**Description**
User seems to be able to say 'cancel' and launch the cancel prompt in any time, even when not in a conversation, e.g. when just opened the chat window

**To Reproduce**
1. Open webchat for the bot
2. Type in 'cancel'

**Expected behavior**
Response saying the user doesn't have any conversation he's currently in to cancel

**Actual behavior**
Cancel prompt shows up asking confirmation to cancel

**Screenshots**
![image](https://user-images.githubusercontent.com/4001684/47276993-61489400-d570-11e8-86cd-9e56e61798ad.png)

**Comment by lauren-mills** [comment]
This was a test
