### ISSUE TITLE
Cannot link the Calendar Skill with my VA

### ISSUE THREAD

**Issue by samaea** [microsoft/botframework-solutions#1550]
## Project

**Name**: 

**Language**: C#

## Description
When using the botskills command to connect the newly deployed Calendar Skill to my VA Bot, it returns the following nodejs error messages:

`PS C:\Users\hussel\source\repos\Melfi-VirtualAssistant\Melfi-VirtualAssistant\Melfi_VirtualAssistant> botskills connect --botName "Melfi-VirtualAssistant-CalendarSkill" --remoteManifest "http://localhost:3980/api/skill/manifest" --luisFolder "C:\Users\hussel\source\calendarskill\calendarskill\calendarskill\Deployment\Resources\LU\en\" --cs
(node:22976) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'find' of undefined
    at Object.connectSkill (C:\Users\hussel\AppData\Roaming\npm\node_modules\botskills\lib\functionality\connectSkill.js:132:25)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:22976) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:22976) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
PS C:\Users\hussel\source\repos\Melfi-VirtualAssistant\Melfi-VirtualAssistant\Melfi_VirtualAssistant> ^C
PS C:\Users\hussel\source\repos\Melfi-VirtualAssistant\Melfi-VirtualAssistant\Melfi_VirtualAssistant> node --version
v10.15.3
PS C:\Users\hussel\source\repos\Melfi-VirtualAssistant\Melfi-VirtualAssistant\Melfi_VirtualAssistant> botskills connect --botName "Melfi-VirtualAssistant-CalendarSkill" --remoteManifest "http://melfi-virtualassistant-calendarskill.azurewebsites.net/" --luisFolder "C:\Users\hussel\source\calendarskill\calendarskill\calendarskill\Deployment\Resources\LU\en\" --cs
Missing property 'name' of the manifest
Missing property 'id' of the manifest
Missing property 'endpoint' of the manifest
Missing property 'authenticationConnections' of the manifest
Missing property 'actions' of the manifest
PS C:\Users\hussel\source\repos\Melfi-VirtualAssistant\Melfi-VirtualAssistant\Melfi_VirtualAssistant> botskills connect --botName "Melfi-VirtualAssistant-CalendarSkill" --remoteManifest "http://melfi-virtualassistant-calendarskill.azurewebsites.net/" --luisFolder "C:\Users\hussel\source\calendarskill\calendarskill\calendarskill\Deployment\Resources\LU\en\" --cs
Missing property 'name' of the manifest
Missing property 'id' of the manifest
Missing property 'endpoint' of the manifest
Missing property 'authenticationConnections' of the manifest
Missing property 'actions' of the manifest
PS C:\Users\hussel\source\repos\Melfi-VirtualAssistant\Melfi-VirtualAssistant\Melfi_VirtualAssistant> botskills connect --botName "Melfi-VirtualAssistant-CalendarSkill" --remoteManifest "http://melfi-virtualassistant-calendarskill.azurewebsites.net/api/skill/manifest" --luisFolder "C:\Users\hussel\source\calendarskill\calendarskill\calendarskill\Deployment\Resources\LU\en\" --cs
(node:4012) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'find' of undefined
    at Object.connectSkill (C:\Users\hussel\AppData\Roaming\npm\node_modules\botskills\lib\functionality\connectSkill.js:132:25)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:4012) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4012) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

## To Reproduce
1. Deploy VA using the deployment template
2. Deploy the Calendar Skill using the deployment template
3. Run the command: `botskills connect --botName "Melfi-VirtualAssistant-CalendarSkill" --remoteManifest "http://melfi-virtualassistant-calendarskill.azurewebsites.net/api/skill/manifest" --luisFolder`

## Expected behavior
To connect the Calendar Skill with the VA Bot.

## Screenshots

![Capture](https://user-images.githubusercontent.com/32162601/59471248-77260480-8e32-11e9-8c54-fbce22e264fe.PNG)

## Additional context
node version is v10.15.3

**Comment by samaea** [comment]
**Update**: resolved the error message by running `npm install -g botskills`, I assumed it was already installed. However, I am now faced with this error message:

![calendar](https://user-images.githubusercontent.com/32162601/59471912-873ee380-8e34-11e9-863b-5f647fcb416b.PNG)

**Update 2**: Issue resolved. Had to swap out the backslashes to forwardslashes when defining the --luisFolder parameter.

**Comment by samaea** [comment]
**Update 3:** Spoke too soon - I am now left with one error message which is AAD related by the looks of it:

![aad](https://user-images.githubusercontent.com/32162601/59472444-6081ac80-8e36-11e9-8094-c5916325c6de.PNG)

**Comment by Batta32** [comment]
Hi @samaea,

Could you execute it with the `--verbose` flag in order to have a more descriptive output of the issue?

Also, which `azure-cli` version do you have? Try updating it to version greater than **2.0.64**.

**Comment by samaea** [comment]
> Hi @samaea,
> 
> Could you execute it with the `--verbose` flag in order to have a more descriptive output of the issue?
> 
> Also, which `azure-cli` version do you have? Try updating it to version greater than **2.0.64**.

Thanks Batta32 - upgraded to AZ CLI 2.0.66, still no luck. 

As requested, output with the --verbose flag on:

`C:\Users\hussel\source\repos\Melfi-VirtualAssistant\Melfi-VirtualAssistant\Melfi_VirtualAssistant>botskills connect --botName "Melfi-VirtualAssistant-CalendarSkill" --remoteManifest "http://melfi-virtualassistant-calendarskill.azurewebsites.net/api/skill/manifest" --luisFolder "C:/Users/hussel/source/calendarskill/calendarskill/calendarskill/Deployment/Resources/LU/en/" --cs --verbose
Updating Dispatch
Getting intents for dispatch...
Adding skill to Dispatch
Parsing Calendar LU file...
ludown parse toluis --in C:\Users\hussel\source\calendarskill\calendarskill\calendarskill\Deployment\Resources\LU\en\Calendar.lu --luis_culture en-us --out_folder C:/Users/hussel/source/calendarskill/calendarskill/calendarskill/Deployment/Resources/LU/en/ --out "Calendar.luis"
dispatch add --type file --name calendarSkill --filePath C:\Users\hussel\source\calendarskill\calendarskill\calendarskill\Deployment\Resources\LU\en\Calendar.luis --intentName calendarSkill --dataFolder C:\Users\hussel\source\repos\Melfi-VirtualAssistant\Melfi-VirtualAssistant\Melfi_VirtualAssistant\Deployment\Resources\Dispatch\en --dispatch C:\Users\hussel\source\repos\Melfi-VirtualAssistant\Melfi-VirtualAssistant\Melfi_VirtualAssistant\Deployment\Resources\Dispatch\en\Melfi-VirtualAssistanten_Dispatch.dispatch
File: C:\Users\hussel\source\calendarskill\calendarskill\calendarskill\Deployment\Resources\LU\en\Calendar.luis added to Melfi-VirtualAssistanten_Dispatch.dispatch
Running dispatch refresh...
dispatch refresh --dispatch C:\Users\hussel\source\repos\Melfi-VirtualAssistant\Melfi-VirtualAssistant\Melfi_VirtualAssistant\Deployment\Resources\Dispatch\en\Melfi-VirtualAssistanten_Dispatch.dispatch --dataFolder C:\Users\hussel\source\repos\Melfi-VirtualAssistant\Melfi-VirtualAssistant\Melfi_VirtualAssistant\Deployment\Resources\Dispatch\en
Exporting services for dispatch...
Exporting Melfi-VirtualAssistanten_general LUIS application...
Exported LUIS app JSON is at C:\Users\hussel\source\repos\Melfi-VirtualAssistant\Melfi-VirtualAssistant\Melfi_VirtualAssistant\Deployment\Resources\Dispatch\en\data\_L_Melfi-VirtualAssistanten_general.json
Exporting chitchat QnA kb...
Exported QnA app JSON is at C:\Users\hussel\source\repos\Melfi-VirtualAssistant\Melfi-VirtualAssistant\Melfi_VirtualAssistant\Deployment\Resources\Dispatch\en\data\_Q_q_chitchat.json
Expanding kb 63fe6a04-a7a8-48b5-aa0c-e52315c057eb with word alterations
Exporting faq QnA kb...
Exported QnA app JSON is at C:\Users\hussel\source\repos\Melfi-VirtualAssistant\Melfi-VirtualAssistant\Melfi_VirtualAssistant\Deployment\Resources\Dispatch\en\data\_Q_q_faq.json
Expanding kb a3b7ab37-e58c-42bc-9f8c-3c0857e78751 with word alterations
Creating dispatch LUIS model json...
Creating training data...
WARNING: Number of samples in 'C:\Users\hussel\source\repos\Melfi-VirtualAssistant\Melfi-VirtualAssistant\Melfi_VirtualAssistant\Deployment\Resources\Dispatch\en\data\_experiments\model_001\train.txt' that were used by multiple categories: 63
WARNING: Number of samples in 'C:\Users\hussel\source\repos\Melfi-VirtualAssistant\Melfi-VirtualAssistant\Melfi_VirtualAssistant\Deployment\Resources\Dispatch\en\data\_experiments\model_001\cv5\fold000\train.txt' that were used by multiple categories: 37
WARNING: Number of samples in 'C:\Users\hussel\source\repos\Melfi-VirtualAssistant\Melfi-VirtualAssistant\Melfi_VirtualAssistant\Deployment\Resources\Dispatch\en\data\_experiments\model_001\cv5\fold000\test.txt' that were used by multiple categories: 3
WARNING: Number of samples in 'C:\Users\hussel\source\repos\Melfi-VirtualAssistant\Melfi-VirtualAssistant\Melfi_VirtualAssistant\Deployment\Resources\Dispatch\en\data\_experiments\model_001\cv5\fold001\train.txt' that were used by multiple categories: 41
WARNING: Number of samples in 'C:\Users\hussel\source\repos\Melfi-VirtualAssistant\Melfi-VirtualAssistant\Melfi_VirtualAssistant\Deployment\Resources\Dispatch\en\data\_experiments\model_001\cv5\fold001\test.txt' that were used by multiple categories: 4
WARNING: Number of samples in 'C:\Users\hussel\source\repos\Melfi-VirtualAssistant\Melfi-VirtualAssistant\Melfi_VirtualAssistant\Deployment\Resources\Dispatch\en\data\_experiments\model_001\cv5\fold002\train.txt' that were used by multiple categories: 43
WARNING: Number of samples in 'C:\Users\hussel\source\repos\Melfi-VirtualAssistant\Melfi-VirtualAssistant\Melfi_VirtualAssistant\Deployment\Resources\Dispatch\en\data\_experiments\model_001\cv5\fold002\test.txt' that were used by multiple categories: 1
WARNING: Number of samples in 'C:\Users\hussel\source\repos\Melfi-VirtualAssistant\Melfi-VirtualAssistant\Melfi_VirtualAssistant\Deployment\Resources\Dispatch\en\data\_experiments\model_001\cv5\fold003\train.txt' that were used by multiple categories: 38
WARNING: Number of samples in 'C:\Users\hussel\source\repos\Melfi-VirtualAssistant\Melfi-VirtualAssistant\Melfi_VirtualAssistant\Deployment\Resources\Dispatch\en\data\_experiments\model_001\cv5\fold003\test.txt' that were used by multiple categories: 3
WARNING: Number of samples in 'C:\Users\hussel\source\repos\Melfi-VirtualAssistant\Melfi-VirtualAssistant\Melfi_VirtualAssistant\Deployment\Resources\Dispatch\en\data\_experiments\model_001\cv5\fold004\train.txt' that were used by multiple categories: 47
WARNING: Number of samples in 'C:\Users\hussel\source\repos\Melfi-VirtualAssistant\Melfi-VirtualAssistant\Melfi_VirtualAssistant\Deployment\Resources\Dispatch\en\data\_experiments\model_001\cv5\fold004\test.txt' that were used by multiple categories: 4
Updating Melfi-VirtualAssistanten_Dispatch model...
Training Melfi-VirtualAssistanten_general...
Importing Melfi-VirtualAssistanten_Dispatch model...
Setting up intents to child services mapping for Melfi-VirtualAssistanten_Dispatch...
Add subscription key and publish child LUIS apps...
Publishing Melfi-VirtualAssistanten_general model...
Training Melfi-VirtualAssistanten_Dispatch model...
Publishing Melfi-VirtualAssistanten_Dispatch model...
Writing summary file ('test_prediction')...
{
  "authoringRegion": "westeurope",
  "culture": "en-us",
  "hierarchical": true,
  "useAllTrainingData": false,
  "dontReviseUtterance": false,
  "copyLuisData": true,
  "services": [
    {
      "intentName": "l_general",
      "appId": "9b854a32-82bb-4ecd-aeca-c774af0b9bdf",
      "authoringKey": "8ef67555f8b6459e83d4343b21b65059",
      "version": "0.1",
      "region": "westeurope",
      "type": "luis",
      "name": "Melfi-VirtualAssistanten_general",
      "id": "1"
    },
    {
      "intentName": "q_chitchat",
      "kbId": "63fe6a04-a7a8-48b5-aa0c-e52315c057eb",
      "subscriptionKey": "8836c7b5124a4b8895f3d95e5f7210c6",
      "type": "qna",
      "name": "chitchat",
      "id": "2"
    },
    {
      "intentName": "q_faq",
      "kbId": "a3b7ab37-e58c-42bc-9f8c-3c0857e78751",
      "subscriptionKey": "8836c7b5124a4b8895f3d95e5f7210c6",
      "type": "qna",
      "name": "faq",
      "id": "3"
    },
    {
      "intentName": "calendarSkill",
      "path": "C:\\Users\\hussel\\source\\calendarskill\\calendarskill\\calendarskill\\Deployment\\Resources\\LU\\en\\Calendar.luis",
      "type": "file",
      "name": "calendarSkill",
      "id": "4"
    }
  ],
  "serviceIds": [
    "1",
    "2",
    "3",
    "4"
  ],
  "appId": "e2db4d1d-d9ec-4a35-a662-83796111f27d",
  "authoringKey": "8ef67555f8b6459e83d4343b21b65059",
  "version": "Dispatch",
  "region": "westeurope",
  "type": "dispatch",
  "name": "Melfi-VirtualAssistanten_Dispatch"
}
Please review your updated dispatch model in C:\Users\hussel\source\repos\Melfi-VirtualAssistant\Melfi-VirtualAssistant\Melfi_VirtualAssistant\Deployment\Resources\Dispatch\en\Summary.html
Running LuisGen...
luisgen C:\Users\hussel\source\repos\Melfi-VirtualAssistant\Melfi-VirtualAssistant\Melfi_VirtualAssistant\Deployment\Resources\Dispatch\en\Melfi-VirtualAssistanten_Dispatch.json -cs "DispatchLuis" -o C:\Users\hussel\source\repos\Melfi-VirtualAssistant\Melfi-VirtualAssistant\Melfi_VirtualAssistant\Services
Successfully refreshed Dispatch model
Successfully updated Dispatch model
Appending 'Calendar Skill' manifest to your assistant's skills configuration file.
Successfully appended 'Calendar Skill' manifest to your assistant's skills configuration file!
Configuring bot auth settings
Checking for authentication settings ...
Configuring Azure AD connection ...
az bot authsetting list -n Melfi-VirtualAssistant-CalendarSkill -g Melfi-VirtualAssistant-CalendarSkill
az bot authsetting show -n Melfi-VirtualAssistant-CalendarSkill -g Melfi-VirtualAssistant-CalendarSkill -c Microsoft
az bot authsetting delete -n Melfi-VirtualAssistant-CalendarSkill -g Melfi-VirtualAssistant-CalendarSkill -c Microsoft
Updating appsettings.json ...
az ad app show --id 88791225-6959-4ab6-8b02-22b9241127b1
Configuring MSA app scopes ...
az ad app update --id 88791225-6959-4ab6-8b02-22b9241127b1 --reply-urls https://token.botframework.com/.auth/web/redirect --required-resource-accesses "[{'resourceAppId':'00000003-0000-0000-c000-000000000000','resourceAccess':[{'id':'b340eb25-3456-403f-be2f-af7a0d370277','type':'Scope'},{'id':'1ec239c2-d7c9-4623-a91a-a9775856bb36','type':'Scope'},{'id':'ba47897c-39ec-4d83-8086-ee8256fa737d','type':'Scope'},{'id':'ff74d97f-43af-4b68-9f2a-b77ee6968c5d','type':'Scope'}]}]"
There was an error while connecting the Skill to the Assistant:
ERROR: Updates to converged applications are not allowed in this version.`

Screenshot version for better readability:
![1](https://user-images.githubusercontent.com/32162601/59520946-04189e80-8ec3-11e9-9b5d-351ca5cb4f75.PNG)

![2](https://user-images.githubusercontent.com/32162601/59520944-04189e80-8ec3-11e9-938a-77c0c42bfe77.png)

![3](https://user-images.githubusercontent.com/32162601/59520943-04189e80-8ec3-11e9-8a1c-5641277079a9.png)

**Comment by Batta32** [comment]
Thanks @samaea, we couldn't replicate the issue during the connection using your skill remote manifest as a local one due to the authentication process worked fine and executed successfully. 

Seeing your screenshots, we noticed the process fails executing `az ad app update` and not previously in other `az` command. Try running the command directly.
If it fails, can you check the permissions of your azure subscription? Maybe you have a permissions problem with your subscription.

**Comment by darrenj** [comment]
@samaea Did you create the azure ad application for your VA manually or through deployment script? This the converged issue is often because of the supported account type setting in azure ad (which we do set for you). That said in customer az subscriptions there has been some unusual behaviour when things are locked down - can you confirm what you setting is as per below

![image](https://user-images.githubusercontent.com/33519520/59917813-e3989900-941a-11e9-89da-0392dad1e69d.png)

**Comment by samaea** [comment]
Hi Darren - FWIW, I am using my own AAD with the GA role. I had to manually create the AAD application as the deployment failed to perform that step. Interestingly enough, when I started from scratch, my VA was able to provision its own AAD app without manual intevention. Perhaps it was a bug with CLI or something?

Here is the requested screenshot of the manually created VA AAD App:

![image](https://user-images.githubusercontent.com/32162601/59983562-22943d80-9619-11e9-80bd-d19d6f77a4f1.png)

You can consider my issue resolved. :)
