### ISSUE TITLE
can't connect same skill for multi languages

### ISSUE THREAD

**Issue by xieofxie** [microsoft/botframework-solutions#1552]
## Project

**Name**: 

Virtual Assistant, Skills

**Language**: 

C#

## Description

when connect a connected skill with another language like:
```
botskills connect --botName * --remoteManifest https://*.azurewebsites.net/api/skill/manifest --luisFolder *\botframework-solutions\skills\src\csharp\emailskill\emailskill\Deployment\Resources\LU\zh --cs --language zh-cn
```
it reports
```
The skill 'Email Skill' is already registered.
```

## To Reproduce

connect en-us first.

## Expected behavior

connect successfully.

**Comment by Batta32** [comment]
Hi @xieofxie,

At this moment, the connection of the same skill for multiple languages is not supported by the `botskills` CLI tool. We have created an issue with the [Feature Request](https://github.com/microsoft/botframework-solutions/issues/1554) for implementing this functionality; you can follow up the deployment updates directly from there.

Meanwhile, as a workaround, you can create a manifest for each skill which has different languages, differentiating by the ID of you skill.
