### ISSUE TITLE
[Botskills] Connect multi languages skills

### ISSUE THREAD

**Issue by Batta32** [microsoft/botframework-solutions#1554]
**Is your feature request related to a problem? Please describe.**
Using `botskills` CLI Tool, there is no way to connect the same skill with different languages. At this moment, the tool throws an error that the skill is already connected because it matches by ID.

**Describe the solution you'd like**
Being able to connect skills with multi-languages using `botskills` CLI tool.

The Skill Manifest contains an array property named `utteranceSources`, which has a property `locale` for each `utteranceSource`. The logic of the CLI Tool could be modified to take this `locale` property in order to detect the different languages the Skill supports, enabling in this way to update the different Dispatch models for each of the locales.

For this to work, the Skill Manifest **should have** the information for all the locales it supports.

<details>
<summary>Manifest Sample with many locales (click to expand)</summary>

```
{
  "id": "sample-skill",
  "name": "sample-skill",
  "description": "This is the description of the sample-skill",
  "iconUrl": "",
  "authenticationConnections": [],
  "actions": [
    {
      "id": "sample-skill_Sample",
      "definition": {
        "description": "Trigger sample-skill",
        "slots": [],
        "triggers": {
          "utteranceSources": [
            {
              "locale": "en",
              "source": [
                "sample-skill#Sample"
              ]
            },
            {
              "locale": "es",
              "source": [
                "sample-skill#Ejemplo"
              ]
            }
          ]
        }
      }
    }
  ]
}
```
</details>

**Describe alternatives you've considered**
Have a different manifest for each language supported, modifying the Skill Id for each language, i.e. `SampleSkillEN`, `SampleSkillES`, `SampleSkillFR`.

**Additional context**
Related to #1552

**Comment by darrenj** [comment]
Addressed
