### ISSUE TITLE
Update App Insights Telemetry usage in all Skills

### ISSUE THREAD

**Issue by ryanisgrig** [microsoft/botframework-solutions#1556]
## Description

Apply the changes at #1560 to each skill:
- [x] Skill Template
- [x] Calendar
- [x] To-Do
- [x] Email
- [x] Weather
- [x] News
- [x] Search
- [x] Point of Interest
- [x] Automotive

## Expected behavior

On a VA with remote skills, the Power BI sample works out of the box with no error of missing properties (DialogInstanceId). In this case, a remote skill will log the correct dialog name and instance id.

**Comment by DingmaomaoBJTU** [comment]
@lauren-mills Seems skill template is fixed in https://github.com/microsoft/botframework-solutions/pull/1560 this pr. Could you help confirm?
