### ISSUE TITLE
Calendar Skill not getting the right date and time

### ISSUE THREAD

**Issue by Dewain27** [microsoft/botframework-solutions#156]
**Description**
When scheduling a meeting, and the date is set to "Friday" This being done on any day after Friday should be the next available Friday.  Currently, it selects the Friday of the week you are in.  I assume it does this for all days.

**To Reproduce**
1. Schedule a meeting
2. Say participants
3. Test Subject
4. Test Meeting
5.  "Friday"
6. "1:00 PM"
7.  "One Hour"
8.  "Redmond"
9.  "Yes"
10.  Now go look in calendar and the meeting invite will be on the wrong day.

I noticed if you say Next Friday on Sunday it skips the Friday to come and puts it 2 Fridays out too.  Lastly, you need to look at the time.  We should honor the time zone of the user's settings in their email account.  Currently, 1:00 PM in my test tenant is coming in at 9:00 AM due to time zone discrepancy.

**Expected behavior**
Expect that Next Friday is the next Friday available.  If on Friday I say Next Friday... it is a week out.  All other days it should be the next one available.  Also, If I say Friday it should default to the next Friday scenario.  We should not book in the past, but always in the future.  If I say Friday and set time to 1:00 PM.  If my current time, based on my valid timezone is later than 1:00 PM and it is Friday... I mean next Friday.  If it is before 1:00 PM I mean today.

**Comment by darrenj** [comment]
Can you confirm you are setting the Timezone property ahead of this scenario - docs on this are here: https://github.com/Microsoft/AI/blob/master/solutions/Virtual-Assistant/docs/virtualassistant-events.md

**Comment by Dewain27** [comment]
> Can you confirm you are setting the Timezone property ahead of this scenario - docs on this are here: https://github.com/Microsoft/AI/blob/master/solutions/Virtual-Assistant/docs/virtualassistant-events.md

This is how to get the bot to a timezone.  What is missing is that when a user links an account, this should be done as part of the skill.  You should honor the timezone with the bot from the source of the linked account.

**Comment by darrenj** [comment]
The time issue I expect to be fixed by ensuring the TimeZone property is set, the date however needs looking into.

**Comment by lauren-mills** [comment]
@KayMKM can you verify that this is fixed and close it if so? Thanks!

**Comment by KayMKM** [comment]
This issue is fixed now. But for this request:

>  If my current time, based on my valid timezone is later than 1:00 PM and it is Friday... I mean next Friday. If it is before 1:00 PM I mean today.

When current date is Friday, the result of DateTimeRecoginizer is only have last Friday and today these two dates. So we can't create the meeting to next Friday. I think this logic is fine, most of users will choose to say "next Friday" instead of "Friday" in this case.
