### ISSUE TITLE
VA Integration with QnAMaker Multi-turn/prompt

### ISSUE THREAD

**Issue by samaea** [microsoft/botframework-solutions#1565]
**Is your feature request related to a problem? Please describe.**
No QnAMaker multi-turn support for QnAMaker in VA solution.

**Describe the solution you'd like**
Include QnAMaker multi-turn/prompt support in the VA solution:- https://docs.microsoft.com/en-us/azure/cognitive-services/qnamaker/how-to/multiturn-conversation & https://github.com/microsoft/BotBuilder-Samples/tree/master/experimental/qnamaker-prompting/csharp_dotnetcore.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by lauren-mills** [comment]
Hi @samaea, we have another item to track this work here: #1888. We'll let you know once we get started.

**Comment by samaea** [comment]
Funny enough @lauren-mills, I just viewed this page to see where we are with this. Thanks for the update!

**Comment by darrenj** [comment]
Tracked in #1888 being actively worked on.
