### ISSUE TITLE
Sharepoint Skills

### ISSUE THREAD

**Issue by cheahengsoon** [microsoft/botframework-solutions#1572]
## User Story
As ...
I want ...
so that ...

## Acceptance Criteria 
*List your requirements.*
- [ ] ...
- [ ] ...
- [ ] ...

## Resources
*Provide any screenshots or conversation mockups to support your request.*
*Learn how to mock up bot conversations with [.chat files](http://aka.ms/bfchatfile).*

## Notes
*Provide any additional information.*

**Is your feature request related to a problem? Please describe.**

As a user , I like to look fro documents from SharePoint daily, I like used Microsoft Teams Bot helps me to search for Documents or related content from SharePoint.

**Describe the solution you'd like**

I would like request Search and Edit document from SharePoint.

**Describe alternatives you've considered**

None

**Additional context**

None

**Comment by darrenj** [comment]
@cheahengsoon Thanks, could you provide some user stories of the scenarios you've like to achieve? For example - As a user, I'm using Teams/WebChat/etc. and would like to find a document containing XYZ, a list of documents is shown and I can click the link to open/edit, forward to someone, etc.

**Comment by cheahengsoon** [comment]
> @cheahengsoon Thanks, could you provide some user stories of the scenarios you've like to achieve? For example - As a user, I'm using Teams/WebChat/etc. and would like to find a document containing XYZ, a list of documents is shown and I can click the link to open/edit, forward to someone, etc.

Update with feature request.

**Comment by lauren-mills** [comment]
We've discussed this, and have no plans to implement a SharePoint skill in the near future, so I'm closing the issue. If you'd like to make your own and contribute it to the repo, we will review it. Thanks!
