### ISSUE TITLE
botskills update command does not exist as documented

### ISSUE THREAD

**Issue by managedcoder** [microsoft/botframework-solutions#1582]
## Project

**Name**: 

**Language**:

**Comment by managedcoder** [comment]
Sorry, not quite used to this issue tracking UX!!!  I did not mean to open and close an empty issue... Let me net this out in the comment here:

The doc [here ](https://github.com/microsoft/botframework-solutions/blob/master/docs/howto/skills/addingskills.md#updating-an-existing-skill-to-reflect-changes-to-actions-or-luis-model) states that you can run the `botskills update` command to 
update an existing Skill to reflect changes to Actions or LUIS model but when you run that command the `update` part of the command is not recognized.  I am running botskills version 1.0.4.

**Comment by Batta32** [comment]
Hi @managedcoder,

As you said, the `update` command is part of the `botskills` cli tool documentation. However, the version [1.0.4](https://botbuilder.myget.org/feed/aitemplates/package/npm/botskills/1.0.4) does not contain that implementation yet, as this functionality is being tested before it gets published in a newer version.

Although 1.0.5 version is not published in npm, you can install the preview [1.0.5-preview24](https://botbuilder.myget.org/feed/aitemplates/package/npm/botskills/1.0.5-preview24) version executing the following command in your terminal
> npm install --global botskills@1.0.5-preview24 --registry https://botbuilder.myget.org/F/aitemplates/npm

Also, you can follow up the new version [here](https://botbuilder.myget.org/feed/aitemplates/package/npm/botskills)

**Comment by darrenj** [comment]
1.05 is now published to npm.
