### ISSUE TITLE
botskills refresh --cs command does not work as documented

### ISSUE THREAD

**Issue by managedcoder** [microsoft/botframework-solutions#1583]
## Project

**Name**: Virtual Assistant

**Language**: C#

## Description
The` botskills refresh --cs` command does not work as documented [here](https://github.com/microsoft/botframework-solutions/blob/master/docs/howto/skills/addingskills.md#refresh-connected-skills).  The doc is not clear on what type of changes to a connected skill this command will update.  Does it update changes to a skill's .lu file or changes in the luis.ai portal or simple code changes?  I assumed it was changes to the .lu file of my connected skill and when I run the command it does not update the connected skill in a way that makes those changes visible to the assistant.

Also, the doc is not clear about what directory you need to be in to properly run this command.

## To Reproduce
Create a connected skill and update the skill's .lu file and then run the command try to test your updated connected skill.

## Expected behavior
I expected the model changes to updated so they were visible from the assistant by triggering the skill with an utterance from the new intent you add to the .lu file.

**Comment by Batta32** [comment]
Hi @managedcoder,

We have updated the related documentation of the `botskills` CLI tool, and separated each command into different documents in order to make them more understandable.

You can check this PR #1688.
