### ISSUE TITLE
Implement SVG handling for adaptive Cards

### ISSUE THREAD

**Issue by abiemann** [microsoft/botframework-solutions#1584]
port the SVG-related code from Connected Car
see commit 9b1abbe2a0c5d108d5004f73742978014fce13ad

this work depends on Adaptive Card Library release > 1.2

**Comment by ryanisgrig** [comment]
Blocked by Adaptive Cards 1.2 dependency

**Comment by Dewain27** [comment]
blocked by #1803

**Comment by ryanisgrig** [comment]
Investigate the 1.2.1 release
https://search.maven.org/search?q=a:adaptivecards-android

**Comment by abiemann** [comment]
I've sent Alberto Medina Gutierrez the following email on 8/13 and CC'd Ryan and Chris:

Dear Alberto,

I've recently discovered the latest Adaptive Card library release 1.2.1 and I wanted to try it out to see if it support SVG's properly.
After updating the project to include the new library, I have found that SVG's are still not rendering in this version of the library - please see the attached images:

EXPECTED RESULT
adaptive_card_designer_vector_image_shown
I've taken the JSON from the Activity and copied it into the designer. The designer shows the SVG (white pointer) in the top-left.

ACTUAL RESULT
AdaptiveCard_1_2_1_rendered
this image shows the rendered result by the Adaptive Cards library 1.2.1

Is there anything I need to do to get the SVG to render properly ?

Regards,
Alexander


Now waiting to hear back
