### ISSUE TITLE
update_cognitive_models in Skill-Template needs update

### ISSUE THREAD

**Issue by xieofxie** [microsoft/botframework-solutions#1585]
## Project

**Name**: Skill-Template

**Language**: C#

## Description
Deployment/Scripts/update_cognitive_models.ps1 is broken. Should change dispatch add to ludown, RunLuisGen etc.

## To Reproduce
update_cognitive_models.ps1 -RemoteToLocal

## Expected behavior
update correctly.

**Comment by lauren-mills** [comment]
Consolidating in issue #1602

**Comment by xieofxie** [comment]
Thanks! Perhaps scripts in demo skills should also be synchronized too.

**Comment by lauren-mills** [comment]
Definitely. I think there's an open issue for updating the existing skills as well. If you have any more comments on bugs in the Skill Template feel free to comment on the other issue!
