### ISSUE TITLE
Adaptive Cards in Skills need to be clickable when relevant

### ISSUE THREAD

**Issue by ryanisgrig** [microsoft/botframework-solutions#1587]
**Is your feature request related to a problem? Please describe.**

In #1439 we are enabling the Adaptive Cards from a VA to be clickable, on a tablet this gives the user to not only need to use voice input to navigate through their conversation. 

**Describe the solution you'd like**

1. Investigate each Skill where Adaptive Cards are displayed and determine if it makes sense to have a card be clickable. _For example, in the Calendar Skill it may not make sense to have the overview card be clickable as it is unclear what the next step of a conversation would be there._
1. If it is determined that the card should be clickable, implement the correct Action property to the card.
    * In the Point of Interest Skill, selecting a card should send an [Action.Submit](https://adaptivecards.io/explorer/Action.Submit.html) with the appropriate data to trigger the next step of the flow. In this case, Action.Submit may have the POI's name in the data property. This data is consumed by the VA as a selection and it navigates to the next step in the dialog.
![image](https://user-images.githubusercontent.com/43043272/59667144-243faa80-91ae-11e9-95fb-4610e372fc0d.png)

**Additional context**

@Dewain27 to add more context

**Comment by bobokids** [comment]
Only URL link are actionable in Calendar/Email/Todo adaptive card.

**Comment by bobokids** [comment]
As the design https://github.com/microsoft/botframework-solutions/issues/916, we do not have actionable card. Close this item as by-design. Please reactive the issue if you have more info.

**Comment by ryanisgrig** [comment]
@bobokids reopening as the investigation is step 1, but step 2 needs to be implemented.

For the Point of Interest Skill, the cards and dialogs need to be updated to support selecting on a card and navigating to the next step. For this card, it **may** be something like:
`
    "selectAction": {
        "type": "Action.Submit",
        "title": "{PointOfInterestName}",
        "data": 1
    }
`

**Expected Outcome**: A user selects on a Point of Interest card in this carousel list and the dialog navigates to the next step, understanding that the index in data maps to that selection.
