### ISSUE TITLE
OnTurnError function inside DefaultAdapter doesn't end the current dialog

### ISSUE THREAD

**Issue by BeigeBadger** [microsoft/botframework-solutions#1589]
## Project

**Name**: Virtual Assistant

**Language**: C#

## Description
When an error is encountered during a turn the `OnTurnError ` method is called, this method logs the error and sends a message back to the user, but it doesn't end the currently active dialog, which in turn (if `EndDialogAsync` has been overridden) will clear out the bad state and pop the dialog off the stack. The consequence of the ActiveDialog not being ended means that the user can be trapped in an stage where card buttons are still active but they cannot progress due to the bad state variables. Yes some of these scenarios could be caught with validation or guard clauses but it seems like a sensible default that is missing. Unfortunately I cannot implement this functionality myself due to the way the dialogContext class is constructed - it depends on runtime values thus cannot be easily passed through to `DefaultAdapter` using dependency injection.

## Expected behavior
User is shown a message about an error being encountered, then the active dialog is ended.

**Comment by BeigeBadger** [comment]
@lzc850612 do you need any further information from my side? My main reason for wanting this is that sometimes when I'm inside a a child dialog, so my maindialog will spawn a child dialog and then partway through the waterfall steps in the child dialog the `DialogContext` seems to lose the value set for the `ActiveDialog` property and consequently hits this block inside the `OnContinueAsync` method of `RouteDialog`:

```
case DialogTurnStatus.Empty:
	await RouteAsync(innerDc).ConfigureAwait(continueOnCapturedContext: false);
	break;
```

-- source `Assembly Microsoft.Bot.Builder.Solutions, Version=4.4.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35`.

**Comment by BeigeBadger** [comment]
Insight my `MainDialog.cs` I have the `RouteAsync` method with the following code:

```
if (umbId > 0)
{
    await dc.BeginDialogAsync(nameof(DynamicWaterfallDialog), new DynamicWaterfallDialogDto { UmbracoId = umbId });
}
``` 

Which starts a new dialog. Once this dialog has started, if I type cancel I (intermittently) get the following:

![https://i.imgur.com/xbOiSLV.png](https://i.imgur.com/xbOiSLV.png)

**Comment by darrenj** [comment]
@BeigeBadger This seems like a sensible change as a "fallback" error if a developer doesn't handle locally.

Is your proposal to change the base OnTurnError handler in DefaultAdapter? If so, do you want to PR a proposed change?

```
public class DefaultAdapter : BotFrameworkHttpAdapter
    {
        public DefaultAdapter(
            BotSettings settings,
            ICredentialProvider credentialProvider,
            IBotTelemetryClient telemetryClient,
            BotStateSet botStateSet)
            : base(credentialProvider)
        {
            OnTurnError = async (turnContext, exception) =>
            {
                await turnContext.SendActivityAsync(new Activity(type: ActivityTypes.Trace, text: $"{exception.Message}"));
                await turnContext.SendActivityAsync(new Activity(type: ActivityTypes.Trace, text: $"{exception.StackTrace}"));
                await turnContext.SendActivityAsync(MainStrings.ERROR);
                telemetryClient.TrackException(exception);
            };
```

**Comment by BeigeBadger** [comment]
@darrenj yes that is my intention.

I have attempted to write this functionality myself but I've run into a sticking point which I believe (maybe incorrectly) is a design limitation that prevent me from successfully doing this.

* The way the `DialogContext` is created:
```
var dc = await _dialogs.CreateContextAsync(turnContext);
``` 

as per [here](https://github.com/microsoft/botframework-solutions/blob/master/templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Bots/DialogBot.cs#L39).

I need access to the `turnContext` (which I have) but also the collection of dialogs which make up the current dialog stack via a `DialogSet` object (which I don't have access to).

I could create my own DialogSet inside `OnTurnError` but that wouldn't work because then it wouldn't contain the stack of dialogs that were part of the flow that caused the error. I've had a poke around the `TurnContext` object as well as injecting `UserState`, and `ConversationState` but none of these seem to provide me access to a `DialogContext` or a way to end the current dialog. 

Any suggestions?

**Comment by lzc850612** [comment]
the OnTurnError is a global handling for exceptions that are not handled. it doesn't and shouldn't have access to the dialog stack, thus you can't cancel all dialogs in here. You can obviously always make sure you catch the proper exceptions and cancel the active dialog in your dialog code, but the OnTurnError method would only help you do something with the turnContext, but nothing more. This is how the botbuilder SDK is designed so I don't see a way to get around it to add this default behavior, nor does it make sense to do this, given the current design of botbuilder runtime.

**Comment by BeigeBadger** [comment]
@lzc850612 thank you for that clarification on that. Just to confirm on my side - in v4 of the SDK errors specific to dialogs, or caused by dialog code that need to be resolved by handling the errors inside each of the said dialogs? I found [this](https://desflanagan.ie/2017/09/01/bot-framework-custom-error-messages-and-exception-handling/) dated post which refers to v3 of the SDK but it is no longer applicable due to the move to .NET Core and the redesign that occurred from v3 -> v4. 

I was hoping to be able to handle the dialog errors globally using some sort of middleware as outlined [here](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-handle-user-interrupt?view=azure-bot-service-4.0&tabs=csharp#handle-unexpected-errors).

I just had another thought - I could potentially achieve this in a somewhat nicer way by creating my own class `ExceptionHandlingComponentDialog` which inherits from `ComponentDialog` and make my dialogs inherit this class. I would then provide implementations for `ContinueDialogAsync` and `ResumeDialogAsync` (I believe these are the only ones I need to care about in terms of processing dialogs - I'm not getting errors starting or ending them, and I don't do any reprompting) which are wrapped in a `try-catch` and can handle the errors and cancel the dialogs if neccessary. How does this sound to you?

**Comment by lzc850612** [comment]
Yes I think you should be able to declare your own implementation of ComponentDialog by inheriting from it and implement those override functions yourself to add additional functionalities such as exception handling.

**Comment by BeigeBadger** [comment]
Awesome. I'll give that a go and let you know how I get on. Am I able to leave this issue open until I've done this? Thanks @lzc850612 and @darrenj!

**Comment by BeigeBadger** [comment]
I managed to get this working using the following classes:

**ExceptionHandlingComponentDialog** (for all dialogs that inherited directly from `ComponentDialog`)
```
public class ExceptionHandlingComponentDialog : ComponentDialog
{
    private readonly IBotTelemetryClient _botTelemetryClient;

    public ExceptionHandlingComponentDialog(
        string dialogId,
        IBotTelemetryClient botTelemetryClient)
        : base(dialogId)
    {
        _botTelemetryClient = botTelemetryClient;
    }

    public async override Task<DialogTurnResult> ContinueDialogAsync(DialogContext outerDc, CancellationToken cancellationToken = default)
    {
        try
        {
            return await base.ContinueDialogAsync(outerDc, cancellationToken);
        }
        catch (Exception exception)
        {
            return await HandleException(outerDc, exception);
        }
    }

    public async override Task<DialogTurnResult> ResumeDialogAsync(DialogContext outerDc, DialogReason reason, object result = null, CancellationToken cancellationToken = default)
    {
        try
        {
            return await base.ResumeDialogAsync(outerDc, reason, result, cancellationToken);
        }
        catch (Exception exception)
        {
            return await HandleException(outerDc, exception);
        }
    }

    private async Task<DialogTurnResult> HandleException(DialogContext outerDc, Exception exception)
    {
        Dictionary<string, string> telemetryData = new Dictionary<string, string>();

        if (outerDc.ActiveDialog != null)
        {
            await outerDc.Context.SendActivityAsync(MainStrings.ERROR);
            await outerDc.Context.SendActivityAsync("The current dialog flow will be ended.");

            telemetryData.Add("ActiveDialog", "True");
            telemetryData.Add("ActiveDialogId", $"{outerDc.ActiveDialog.Id}");
            telemetryData.Add("State", $"{StateConversionHelper.ConvertDialogStateToString(outerDc.ActiveDialog.State)}");
        }
        else
        {
            await outerDc.Context.SendActivityAsync($"An issue was encountered.");

            telemetryData.Add("ActiveDialog", "False");
            telemetryData.Add("State", $"{StateConversionHelper.ConvertTurnStateToString(outerDc.Context.TurnState)}");
        }

        _botTelemetryClient.TrackException(exception, telemetryData);

        return await outerDc.EndDialogAsync();
    }
}
```

`StateConversionHelper` is a helper class that I wrote to extract the data I wanted out of the various state objects so that I could log it in Application Insights.

**ExceptionHandlingRouterDialog** (for all dialogs that inherit directly from `RouterDialog`)
Unfortunately due to the `RouteAsync` method of `RouterDialog` being abstract (which makes sense), meant that in order to create this I had to move a big portion of code specific to a dialog into the `ExceptionHandlingRouterDialog` class, which made it a non-generic handler. Even though I only have a single Dialog that inherits from `RouteDialog` currently, more could be added in the future and would mean a big refactor of `ExceptionHandlingRouterDialog`. So I came up with a less graceful solution - wrapping the body of my `OnEventAsync`, `RouteAsync`, `OnInterruptDialog` etc in try-catches and doing the exception handling within the Dialog itself.

**StateConversionHelper** (converts `DialogContex.ActiveDialog.State` and `DialogContext.Context.TurnState` into a string that I plug into Application Insights).

Due to `CachedBotState` being a private class inside `BotState` I had to use delicious `dynamic`s - I tried reflection and could get the type out but was getting compile errors with casting to a type that wasn't known at build time, I also tried using `PrivateObject` from MSTest but it didn't want to import, so trusty old `dynamic`s it was!

```
public static class StateConversionHelper
{
    public static string ConvertTurnStateToString(TurnContextStateCollection turnStateCollection)
    {
        StringBuilder stringBuilder = new StringBuilder();

        foreach (KeyValuePair<string, object> item in turnStateCollection)
        {
            object value = item.Value;

            if (value.GetType().Name == "CachedBotState")
            {
                dynamic botState = item.Value as dynamic;

                if (item.Key == "UserState")
                {
                    stringBuilder.Append($"{item.Key}:{botState.GetType().GetProperty("Hash")?.GetValue(botState, null)}");
                }
                else if (item.Key == "ConversationState")
                {
                    stringBuilder.Append($"{item.Key}:{botState.GetType().GetProperty("Hash")?.GetValue(botState, null)}");
                }
            }
            else
            {
                stringBuilder.Append($"{item.Key}:{value}");
            }

            stringBuilder.Append("|");
        }

        return stringBuilder.ToString();
    }

    public static string ConvertDialogStateToString(IDictionary<string, object> keyValuePairs)
    {
        StringBuilder stringBuilder = new StringBuilder();

        foreach (KeyValuePair<string, object> pair in keyValuePairs)
        {
            if (pair.Value is DialogState)
            {
                DialogState dialogState = (DialogState)pair.Value;

                foreach (DialogInstance dialogInstance in dialogState.DialogStack)
                {
                    stringBuilder.Append($"dialogId:{dialogInstance.Id},");

                    foreach (KeyValuePair<string, object> item in dialogInstance.State)
                    {
                        string state = dialogInstance.State.ToString();

                        if (item.Value is DynamicWaterfallDialogDto)
                        {
                            DynamicWaterfallDialogDto dynamicWaterfallDialogDto = (DynamicWaterfallDialogDto)item.Value;

                            stringBuilder.Append($"{item.Key}:{nameof(dynamicWaterfallDialogDto.UmbracoId)}={dynamicWaterfallDialogDto.UmbracoId};");
                        }
                        else if (item.Value is IEnumerable && item.Value.GetType() != typeof(string))
                        {
                            IEnumerable collection = item.Value as IEnumerable;
                            List<string> values = new List<string>();

                            foreach (object entry in collection)
                            {
                                values.Add(entry.ToString());
                            }

                            stringBuilder.Append($"{item.Key}:{string.Join(",", values)};");
                        }
                        else
                        {
                            stringBuilder.Append($"{item.Key}:{item.Value};");
                        }
                    }

                    stringBuilder.Append("|");
                }
            }
        }

        return stringBuilder.ToString();
    }
}
```

Maybe this will help someone in the future. Thanks again @lzc850612 and @darrenj.
