### ISSUE TITLE
Add SMS Channel to Demo Environments

### ISSUE THREAD

**Issue by Dewain27** [microsoft/botframework-solutions#1590]
As a user 
I would like to have a conversation with the Master Stable Environment VA through SMS Channel, 
so that I can easily demo the core features of the VA Master Stable Environment.

**Comment by thegoo** [comment]
@Dewain27 - to clarify, is this to demonstrate that the bot (or underlying skill) can send a text message to a specific number based off a signal/event, or that you can communicate with the VA via the SMS channel config?

**Comment by ryanisgrig** [comment]
@thegoo this is to demonstrate the Twilio channel with Virtual Assistant - I'm removing you.

**Comment by darrenj** [comment]
Update?
