### ISSUE TITLE
To do skill not responding

### ISSUE THREAD

**Issue by Quirinevwm** [microsoft/botframework-solutions#1591]
When logged-in, to do skill is not responding: getting an error message.
![image](https://user-images.githubusercontent.com/43533472/59684953-5ddada80-91db-11e9-8ac8-25ec658f2a37.png)
 
"DialogException: Code: ErrorNoPermissionsInAccessToken\r\nMessage: Exception of type 'Microsoft.Fast.Profile.Core.Exception.ProfileAccessDeniedException' was thrown.\r\n, StackTrace:    at ToDoSkill.Services.MailService.GetSenderMailAddressAsync() in

**Comment by ryanisgrig** [comment]
This occurs on personal MSA, the Contoso demo tenant does not have this issue

**Comment by DingmaomaoBJTU** [comment]
May due to todo skill lost scope "User.ReadBasic.All Mail.Send". Please ensure you have these two in your connection config~

**Comment by DingmaomaoBJTU** [comment]
And ryan is right, use personal MSA also cause this issue. You can apply a contoso account here: https://demos.microsoft.com/

**Comment by Quirinevwm** [comment]
Late reply, but thanks will test with the demo account I've set up from now on then!
