### ISSUE TITLE
Remove "do you want to hear more" type prompts from Skills

### ISSUE THREAD

**Issue by bobokids** [microsoft/botframework-solutions#1598]
## Project
Skills
C#

## Description
Skill flow update: Remove the “do you want to hear more” type prompt after every productivity interaction

## To Reproduce

Using calendar skill to get summary of todays' meeting, by end of the conversation, a prompt ask user "Do you want to hear the content of first event" and user has to answer yes or no.

## Expected behavior

Change the prompt to informational msg and allow user to switch to other dialogs.

**Comment by ryanisgrig** [comment]
This also includes the intent switching capability where a Skill will fall back to the VA for processing if it can't handle a user's utterance
