### ISSUE TITLE
Implement ActivityHandler correctly in DialogBot

### ISSUE THREAD

**Issue by ghost** [microsoft/botframework-solutions#1599]
**Is your feature request related to a problem? Please describe.**
DialogBot inherits from ActivityHandler but the OnTurnAsync method never calls it's base member. There is also the RouterDialog inherited by Main which appears to be doing much the same job as the AcitivityHandler.

**Describe the solution you'd like**
Either inherit DialogBot from IBot and cut out the unused inheritence or remove the RouterDialog and shift the bulk of the logic from Main into a _<VirtualAssistant>_Bot class.

**Describe alternatives you've considered**
Or even remove the router/handler element entirely and allow the active dialog to handle events in context such as responses to adaptive cards.

**Additional context**
Currently both the ActivityHandler and RouterDialog fail silentliy for unsupported Activities. This is particularly an issue around Teams Authentication where the events are never reaching the appropriate OAuthPrompt.

**Comment by faragab** [comment]
Sxb I vtdjv

**Comment by lauren-mills** [comment]
Internal note:
*dependent on #1854

**Comment by lauren-mills** [comment]
@joe-tossell-mando I've settled on inheriting from IBot for this iteration. As for the teams authentication event, I believe we have a fix for that in the latest version of [RouterDialog](https://github.com/microsoft/botframework-solutions/blob/28c083e287e74b06a18c8b7eacdeda1f5b19f203/lib/csharp/microsoft.bot.builder.solutions/microsoft.bot.builder.solutions/Dialogs/RouterDialog.cs#L92), but if not, you can override the OnSystemMessageAsync() method on RouterDialog to handle events of different types.
