### ISSUE TITLE
[POISkill]Should show map snapshot of where the user currently is and where the target location is to provide better info

### ISSUE THREAD

**Issue by lzc850612** [microsoft/botframework-solutions#1609]
**Is your feature request related to a problem? Please describe.**
When using POI Skill, we often get a list of locations without showing the user's location and target location in a single map. It's not informative enough to help user to make a decision on which is the one the user's looking for

**Describe the solution you'd like**
We could show a snapshot of a map with user's location as well as the target location to provide context on the location of the destination.

**Describe alternatives you've considered**

**Additional context**
We'll have to see if there's APIs that could support implementing this scenario.

**Comment by ryanisgrig** [comment]
This sounds related to #1332 where we may be able to add pins and route info on a map

**Comment by ryanisgrig** [comment]
Closing as my issue has more technical details
