### ISSUE TITLE
In Chinese mode, the duration of a meeting is not recognizable during creation of a meeting

### ISSUE THREAD

**Issue by lzc850612** [microsoft/botframework-solutions#161]
**Description**
In Chinese mode, the duration of a meeting is not recognizable during creation of a meeting

**To Reproduce**
Steps to reproduce the behavior

Open webchat for the bot
Ask 'create a meeting' in chinese
Follow through to the step of inputting duration of the meeting
Type in '1 hour' in chinese for duration

**Expected behavior**
1 hour is taken as duration of the meeting

**Actual behavior**
The bot keeps asking about the duration. the '1 hour' in chinese is not recognized

**Comment by KayMKM** [comment]
fixed.
