### ISSUE TITLE
[Skill Template] deploy.ps1 does not publish bot code to WebApp

### ISSUE THREAD

**Issue by h2floh** [microsoft/botframework-solutions#1629]
**Is your feature request related to a problem? Please describe.**
I thought the script will also publish the bot code like for the VA mother bot, but it doesn't. Took some time to figure out why the skill bot is not working after "successful" deployment.

**Describe the solution you'd like**
Include a publishing step

**Describe alternatives you've considered**
Publishing with Visual Studio Publish Wizard, creating an Azure Dev Ops based release pipeline

**Additional context**
none

**Comment by darrenj** [comment]
Resolved in #1611. The latest publish script update hadn't made it's way into the skills from the skill template! Thanks.
