### ISSUE TITLE
[Virtual Assistant Template] deploy.ps1 - Quickstart deploy with auto-generated service names

### ISSUE THREAD

**Issue by h2floh** [microsoft/botframework-solutions#1630]
**Is your feature request related to a problem? Please describe.**
Services with unique namespaces like CosmosDB, Storage Account, WebApp URL can not be used if already assigned to another azure account. Currently these values are all derived from the bot name, the deployment script asks for. Especially if you want to give your Assistant's a normal name the possibility of getting a resource conflict is high (I tried to use my son's name Ian for testing and voila a lot of conflicts). 
First conflict was discovered by the ARM validation, but the root cause was not displayed. I modified the script code to get the root cause which was **Storage Account Name** already used. [BTW I created a pull request for that already. #1626 ] 

Ok, I modified the value for Storage account. 
Next try. Validation succeeds.
Deployment fails WebApp Name Ian already used. Interestingly this is not covered by the ARM validation...
Ok WebApp Name modified as well. Don't forget to delete the RG and start over...
Again... Bot Registration... oops Bot Names have to be at least 4 characters... again
Deployment done! But I had to realize that the Bot code was not published because I modified the WebApp Name and it now differs from the Bot Name which resulted in the _publish_ script do do nothing.

For non experienced PowerShell and ARM users this can be hard to modify/identify. 

I would love seeing the deployment script running for unexperienced users just hit enter and done, even if the service names are not pretty ...

**Describe the solution you'd like**
More checks on the Service Names or using uniqueString post/prefixes for a ensured deployment. Resolving the publish Bug #1628 

**Describe alternatives you've considered**
Modify parameters and publish manually or via Azure Dev Ops Pipeline 

**Additional context**

**Comment by lauren-mills** [comment]
@h2floh Valid point on appending the unique strings to ensure safe resource names, and I'll take it as a backlog item. FYI, we had this feature before in the msbot tool and we got a lot of requests to make the service names more palatable, which is why we have the current implementation.

One note about the Bot Name is that you can use the Display Name property on the bot service to give it a nicer name, while the name of the resource itself can be something more unique.

**Comment by lauren-mills** [comment]
The updates are now in the deployment script to append a unique string to the end of the service names if not explicitly provided, and the improved validation output to the log file.
