### ISSUE TITLE
After handover to calendar skill from VA, the flow just stop without any error and without any response

### ISSUE THREAD

**Issue by ProgrammerDante** [microsoft/botframework-solutions#1634]
## Project

**Name**: Using Virtual assistance with Calendar Skill with skill template and virtual assistant template with reference to sample calendar skill project of github example

**Language**: C#

## Description

The entire thing is working in emulator. But in bot channel registration webchat (or directline)
Bot gives no response after the trace message(from app insight): <--Received a Token Request from a skill. After this trace message, there is no error or exception, but simply no response.

## Expected behavior

Bot channel registration web chat or directline to prompt oauth card.

## Screenshots

Working in Emulator
![image](https://user-images.githubusercontent.com/21333878/59921419-368a4480-944b-11e9-996b-06228e23982a.png)
Last part of the execution logged in app insight, for not working instance from directline/webchat
![image](https://user-images.githubusercontent.com/21333878/59921632-f7102800-944b-11e9-9ba6-d7c9ea18d8f1.png)
Not working instance, no respone
![image](https://user-images.githubusercontent.com/21333878/59922177-a7326080-944d-11e9-9a31-c7194ed618f8.png)

**Comment by darrenj** [comment]
Can you update your Bot.Builder.Solutions and .Skills nuget packages to the latest please, at the same time you can update Bot.Builder SDK to 4.4.5. Then apply the code change reference [here](https://github.com/microsoft/botframework-solutions/blob/master/docs/reference/knownissues.md#when-invoking-a-skill-you-may-experience-the-initial-message-being-sent-twice)

**Comment by ProgrammerDante** [comment]
Thank you, updating some of those packages from nuget manager solved it.

**Comment by FreddyAyala** [comment]
I had the same problem and the suggested corrections have worked perfectly.
