### ISSUE TITLE
Cannot compile CalendarSkill project - Error the type or namespace name 'CalendarLuis' could not be found

### ISSUE THREAD

**Issue by etiennebailly** [microsoft/botframework-solutions#1639]
## Project

**Name**: CalendarSkill

**Language**:  C#

## Description
Error during compilation of CalendarSkill project
Error	CS0246	The type or namespace name 'CalendarLuis' could not be found (are you missing a using directive or an assembly reference?)	CalendarSkill	C:\DEV\02-teams\botframework-solutions\skills\src\csharp\calendarskill\calendarskill\Dialogs\CalendarSkillDialogBase.cs	1412	Active

## To Reproduce
Compile CalendarSkill.csproj

## Expected behavior
A no error compilation

**Comment by darrenj** [comment]
Hi,

I assume this happens once you have completed deployment? Can you confirm the luisgen version you have (luisgen -v) and OS please? I have just completed a deployment and can't repro the namespace being incorrect.

The following command should generate the required file (run from the calendarskill root directory and this is what the deploy.ps1 calls.
```
luisgen deployment\resources\lu\en\calendar.luis -cs "calendarLuis" -o services
```

**Comment by darrenj** [comment]
Update - I can repro this. One of the supporting tools seems to have changed it's behaviour around casing and is resulting in a incorrectly cased type. The workaround above will resolve and we'll look into what's triggering this.

**Comment by darrenj** [comment]
Another workaround would be to rename calendar.lu to Calendar.lu. Still investigating what has caused the casing issue.

**Comment by darrenj** [comment]
We've identified the change. Until recently LUISGen wasn't being invoked as part of Skill deployment, we recently aligned the scripts and now generate the file which replaces the existing one which has a different casing. As it's auto-generated the right fix is to update the skills to use lowercase names and match what is generated.

You can workaround by running the command above or removing this line from the deploy_cognitive_models.ps1 deployment script for new deployments. 			

`RunLuisGen $lu "$($lu.BaseName)" $(Join-Path $outFolder Services)`

**Comment by Adnanamin** [comment]
I got the same issue, I executed the command shared at top but still no luck. I also rename calendar.lu to Calendar.lu but still no luck

![image](https://user-images.githubusercontent.com/10959141/60214271-adad4780-9854-11e9-8e4f-f0fd619210ec.png)

Any suggestion what should I do.
