### ISSUE TITLE
Clone services fails when creating cosmosdb

### ISSUE THREAD

**Issue by garypretty** [microsoft/botframework-solutions#164]
**Description**
Calling msbot clone services for the assistant is failing for me.  I used the following command;

**msbot clone services --name "CustomAssistant" --luisAuthoringKey XXXXX --folder "DeploymentScripts\en\msbotclone" --location "westeurope"**

clone seems to run ok for most services until it gets to cosmos and then I got the following error;

**Command failed: az cosmosdb create -n customassistant -g CustomAssistantERROR: Operation failed with status: 'BadRequestActivityId: 39afb0c2-d63e-11e8-90da-3052cbe9b11e, Microsoft.Azure.Documents.Common/2.0.0.0**

**Comment by ryanisgrig** [comment]
@garypretty , can you test with a more unique name for the bot?

**Comment by garypretty** [comment]
@ryanlengel sure. I'll test it now.

**Comment by lauren-mills** [comment]
Hi @garypretty, were you able to resolve this?

**Comment by lauren-mills** [comment]
Closing for now. Feel free to reopen as needed.
