### ISSUE TITLE
[Analytics] Not able to get skill waterfall dialog related log in VA report

### ISSUE THREAD

**Issue by DingmaomaoBJTU** [microsoft/botframework-solutions#1645]
## Project

**Name**: 
Analytics

**Language**: 

## Description

When using powerbi report connect to VA, user cannot see the detailed skill waterfall dialog data report. Only waterfall dialog in VA can be logged and analyzed. 
![image](https://user-images.githubusercontent.com/16643193/59998975-58760800-9693-11e9-947d-d71aace56a61.png)

## To Reproduce

1. Open template in botframework-solutions\solutions\analytics\ConversationalAnalyticsSample_4_4.pbit
2. Input an application insight Id of VA 
3. Have some conversation will remote skill registered in VA
4. Check the report, no related waterfall dialog status is logged for remote skill
![image](https://user-images.githubusercontent.com/16643193/59999423-827bfa00-9694-11e9-8a1a-8267f4ab9676.png)

## Expected behavior

Remote skill waterfall dialog telemetry can be logged in report.
In specific skill's application insight, you can see dialogInstanceId is logged correctly.
![image](https://user-images.githubusercontent.com/16643193/59999505-b525f280-9694-11e9-95e0-fd672a244f92.png)

**Comment by darrenj** [comment]
If you update the Skills appsettings.config to use the same ApplicationInsights InstrumentationKey as the virtual assistant does this resolve? I suspect so.

If so - there should be an additional documentation item to cover this change when you are adding a skill you control.

**Comment by lauren-mills** [comment]
@DingmaomaoBJTU were you able to resolve this?

**Comment by DingmaomaoBJTU** [comment]
Sure, I can help add doc for this~
