### ISSUE TITLE
Not able to connect skill

### ISSUE THREAD

**Issue by yuuzora** [microsoft/botframework-solutions#1648]
### #Typescript 

After recreating a fresh Skill and Virtual Assistant and connecting my Skill to my Virtual Assitant,
trying to launch the virtual Assistant fail with this error:

```
src/index.ts:50:7 - error TS2322: Type '{ "id": string; "name": string; "description": string; "iconUrl": string; "authenticationConnections": never[]; "actions": { "id": string; "definition": { "description": string; "slots": never[]; "triggers": { "utteranceSources": { ...; }[]; }; }; }[]; "msAppId": string; "endpoint": string; }[]' is not assignable to type 'ISkillManifest[]'.
  Type '{ "id": string; "name": string; "description": string; "iconUrl": string; "authenticationConnections": never[]; "actions": { "id": string; "definition": { "description": string; "slots": never[]; "triggers": { "utteranceSources": { ...; }[]; }; }; }[]; "msAppId": string; "endpoint": string; }' is not assignable to type 'ISkillManifest'.
    Types of property 'actions' are incompatible.
      Type '{ "id": string; "definition": { "description": string; "slots": never[]; "triggers": { "utteranceSources": { "locale": string; "source": string[]; }[]; }; }; }[]' is not assignable to type 'IAction[]'.
        Type '{ "id": string; "definition": { "description": string; "slots": never[]; "triggers": { "utteranceSources": { "locale": string; "source": string[]; }[]; }; }; }' is not assignable to type 'IAction'.
          Types of property 'definition' are incompatible.
            Type '{ "description": string; "slots": never[]; "triggers": { "utteranceSources": { "locale": string; "source": string[]; }[]; }; }' is not assignable to type 'IActionDefinition'.
              Types of property 'triggers' are incompatible.
                Type '{ "utteranceSources": { "locale": string; "source": string[]; }[]; }' is missing the following properties from type 'ITriggers': utterances, events

50 const skills: ISkillManifest[] = skillsRaw;
```

The skills.json seems fine (replaced my infos with *): 

`{
    "skills": [
        {
            "id": "*",
            "name": "*",
            "description": "This is the description of the *",
            "iconUrl": "http://*.azurewebsites.net/",
            "authenticationConnections": [],
            "actions": [
                {
                    "id": "*_Sample",
                    "definition": {
                        "description": "Trigger *",
                        "slots": [],
                        "triggers": {
                            "utteranceSources": [
                                {
                                    "locale": "en",
                                    "source": [
                                        "*#Sample"
                                    ]
                                }
                            ]
                        }
                    }
                }
            ],
            "msAppId": "*******************",
            "endpoint": "http://*.azurewebsites.net/api/skill/messages"
        }
    ]
}`

**Comment by Batta32** [comment]
Hi @Zack-Strife,

You are having an issue with the `skills.json` file of your generated `Virtual Assistant`. 

We are planning to update the implementation of the `ISkillManifest` interface to allow those nullable properties.
As a workaround, you can modify the generated `skills.json` file and add the `utterances` and `events` properties to the `triggers` property in the skill that you added.

![image](https://user-images.githubusercontent.com/11904023/60050259-97fa1f80-96a6-11e9-94cb-29d51f5a7459.png)

**Comment by yuuzora** [comment]
Thanks ! Worked like a charm
