### ISSUE TITLE
[VirtualAssistantClient] Android Sample app not initializing.

### ISSUE THREAD

**Issue by cshalu** [microsoft/botframework-solutions#1650]
## Project

**Virtual Assistant**

**Java Android app**

## Description
After you build and run your Android Virtual Assistant app, the app keeps on showing "Reconnecting to Server" and does not render anything on the screen except the microphone button,

## To Reproduce
1. Clone the repo
2. Build and run the Android VirtualAssistantClient app.

## Expected behavior
It should render completely and on clicking the microphone button understand the speech uttered by the user.

## Additional context
No documentation is available to understand the prerequisites and configuration that needs to be done before building the Android VirtualAssistantClient. There are no details of what features are supported in this app and what to expect when the app is run.

**Comment by darrenj** [comment]
Documentation is on it's way shortly, the app was merged as we work on it and not quite ready hence the docs.

**Comment by darrenj** [comment]
Getting started doc added in [readme.md](https://github.com/abiemann/botframework-solutions/blob/master/solutions/android/VirtualAssistantClient/readme.md)
