### ISSUE TITLE
luis_functions do not support westeurope

### ISSUE THREAD

**Issue by ghost** [microsoft/botframework-solutions#1655]
## Project

**Name**: Virtual Assistant, Skills

**Language**: C#

## Description
All luis commands need to reference the region parameter not just `luis import application` on line 18 of luis_functions.ps1 as it is used to construct the correct regional URL. It means that a westeurope authoring key is being used (I assume) against "westus" with the following error occurring:
```
Access denied due to invalid subscription key. Make sure you are subscribed to an API you are trying to call and provide the right key.
```

## To Reproduce
Run deploy / deploy_cognitive_models / luis_functions against westeurope LUIS authoring region.

## Expected behavior
Should deploy and update with errors in regions other than westus

**Comment by darrenj** [comment]
Hi Joe - Whilst the --region parameter should be passed for completeness I don't believe it's actively used for the other operations. Can I double check when your getting this error message and can I also check you've retrieve an authoring key from eu.luis.ai rather than luis.ai?

**Comment by ghost** [comment]
Hi Darren, Yes I am using an authoring key from eu.luis.ai and all of the projects that I work on are based there. As far as I can tell the authoring endpoint is constructed using the Azure Reguion:
https://github.com/microsoft/botbuilder-tools/blob/18eaf2b27f3df5bdfc8a11f36539c56651e38a21/packages/LUIS/src/luisAuthoringContext.ts#L35

Which is defaulted to westus:
https://github.com/microsoft/botbuilder-tools/blob/58a3f42b720c54015c071c2b1278a41b9a73c644/packages/LUIS/src/models/parameters.ts#L52

I imagine that the error is a result of using an eu authoring key against the defaulted westus endpoint, passing --region westeurope fixes this.

**Comment by darrenj** [comment]
Hi,

Can you help me understand more repro steps on the issue your seeing? I've just double checked an assistant deployment to europe and it deployed fine, and validated the Bot could call LUIS so struggling to repro a bit :-)  I am using C# rather than TS but checked the deployment scripts to ensure they matched.

![image](https://user-images.githubusercontent.com/33519520/60231285-9880ea80-984d-11e9-94ca-2d30c49e488a.png)

**Comment by ghost** [comment]
Yes mine does that, the deployment is fine as it passses the region, but the training fails I think. Please can you check your deploy_cognitive_models_log.txt. Mine is attached.
[deploy_cognitive_models_log.txt](https://github.com/microsoft/botframework-solutions/files/3335624/deploy_cognitive_models_log.txt)

Also please run update_cognitive_models.ps1 which reports similar errors directly to the console.

**Comment by ghost** [comment]
Attaching full output from vanilla template:
[output.txt](https://github.com/microsoft/botframework-solutions/files/3335648/output.txt)

**Comment by darrenj** [comment]
Interesting, good spot. Can you try these updates out?
[regionscripts.zip](https://github.com/microsoft/botframework-solutions/files/3337088/regionscripts.zip)

**Comment by ghost** [comment]
Still erroring, I think on line 46, I think every call to luis needs to pass region, otherwise it'll construct the wrong endpoint.
[luis_functions.zip](https://github.com/microsoft/botframework-solutions/files/3338017/luis_functions.zip)

Couple of other solutions might be:
1. Run luis init as part of the deploy_cognitive_models.ps1 and set authoring key and region their, this is then not checked in, only issues is you end up with 2 configuration points, .luisrc and cognitivemodels.json for deployment and reunning the app, which is not ideal
2. Pass around raw json config and pipe in the arguments using --stdin
[Scripts.zip](https://github.com/microsoft/botframework-solutions/files/3338269/Scripts.zip)
I've attached an example working for UpateLUIS function, same principle could be applied to QnA etc. It would require an update to the deploy_cognitive_models script to fix some casing.

**Comment by darrenj** [comment]
[deploy_cognitive_models.zip](https://github.com/microsoft/botframework-solutions/files/3339355/deploy_cognitive_models.zip)
Updated - I missed the train ones.

**Comment by ghost** [comment]
There are no references to train in that file?
Either way is this enought to triage the bug?
