### ISSUE TITLE
Update PoI skill to leverage Address and geography entities

### ISSUE THREAD

**Issue by darrenj** [microsoft/botframework-solutions#1662]
The Point of Interest skill makes use of keyword entities to find types of point of interest but doesn't make use of the `Address` and `geographyv2` entities which the LUIS model provides.

For example each of the following questions should not prompt for location (which they currently do). When calculating routing directions we do need to know the users current location which in most cases will have been provided through a location event prior to this. I'm OK at this stage for us to not offer this capability if location hasn't been provided to simplify the interaction.

- `Find a coffee shop in Seattle`

In this scenario the Skill would go straight to providing coffee shops in Seattle. If a "location" has been provided (through the event) this is **not** used to find a PoI (which it used for today) but **will** be used to calculate a route to the identified coffee shop from the provided location. If a location has not been provided we should not offer to provide routing directions (we could explore prompting for current location?). Therefore we do a straight forward poi search in seattle and provide routing from the provided location if available.

![image](https://user-images.githubusercontent.com/33519520/60140036-0ef5ed80-9765-11e9-99d5-088ba8c76c74.png)

- `Get Directions to Mt Rainier`
In this scenario the Skill would find Mt Rainier PoI (ideally not prompt for multiple options if that works) and then as above provide routing options if the location event has sent location information.
![image](https://user-images.githubusercontent.com/33519520/60140041-1917ec00-9765-11e9-9a94-50accaa162f9.png)

- `I need to go to Seatac`
Same as above
![image](https://user-images.githubusercontent.com/33519520/60140066-2cc35280-9765-11e9-8980-4d03097965cc.png)

- `I want to go to 900 bellevue way ne, Bellevue`
In this case we need to build up the address from the address entities and then as above providing routing if we have a location.
![image](https://user-images.githubusercontent.com/33519520/60140079-364cba80-9765-11e9-98e0-4da46d2f7049.png)

**Describe alternatives you've considered**

**Additional context**

**Comment by xieofxie** [comment]
Do we have design/flow for this skill? The logic in RouteDialog.cs is very confusing.. For example, if a destination has been set by find_poi, the address in route_fromxtoy will be ignored.
