### ISSUE TITLE
Point of Interest Skill - Forward Fill to get directions

### ISSUE THREAD

**Issue by darrenj** [microsoft/botframework-solutions#1663]
# Simplify conversation flow to get directions after finding a PoI

Today in the Point of Interest skill you identify a PoI and then go through a series of prompts to get driving directions to a PoI, for example - see the multiple responses below:

![image](https://user-images.githubusercontent.com/33519520/60140884-0652e680-9768-11e9-9cfc-de0594f0da7a.png)

**Describe the solution you'd like**

Enabling the user to shortcut subsequent prompts by saying "drive me to the first one" would enable us to shortcut the following prompts. The user can still say "first one" and get the prompt but could shortcut if they ask?

![image](https://user-images.githubusercontent.com/33519520/60140858-f0452600-9767-11e9-986e-0f32956b0acb.png)

**Comment by ryanisgrig** [comment]
The Azure Maps API has the potential to return an array of potential routes to a destination, but in all of my testing I have only experienced a single route returned. Currently this results in a ConfirmPrompt to ensure a user wants that route but I think if there is a single route returned that should be considered the "shortcut" and instead POI just sends the event to trigger a client to open a map (see #1443 for how the event should be configured)
