### ISSUE TITLE
Can't connect to remote skill in TypeScript VA

### ISSUE THREAD

**Issue by Basavarajsk** [microsoft/botframework-solutions#1664]
**Is your feature request related to a problem? Please describe.**
I need a calendar skill sample code for an virtual assistant in typescript.

**Comment by darrenj** [comment]
You can make use of the csharp skill from a typescript bot through the Skill Infrastructure as it's a remote call to a skill. Would this help in your scenario?

**Comment by Basavarajsk** [comment]
Hi,
Thanks for you information.
But I am unable to connect the skills using remote to VA.

**Comment by bobokids** [comment]
From Darren: A JS based VA will be able to invoke a .NET based Skill once we have the JS websocket library from the ABS team. I think the lack of library affects both invocation and JS-Skill scenarios but will clarify with Southworks.

Keep this issue in backlog.

**Comment by darrenj** [comment]
We now have a js library for StreamingExtensions that will enable us to extend skill support to JS bots. This integration work has started and we’ll update this PR with progress.

**Comment by darrenj** [comment]
PR for the JS StreamingExtensions library is here FYI: https://github.com/microsoft/botbuilder-js/pull/1081

**Comment by darrenj** [comment]
Work is tracked [here](https://github.com/microsoft/botframework-solutions/issues/2489) and targeting next release. Please keep an eye on the issue and we'll point at daily builds when available.
