### ISSUE TITLE
[Android App] Add Timezone configuration setting and send to VA using Timezone event.

### ISSUE THREAD

**Issue by darrenj** [microsoft/botframework-solutions#1678]

**Comment by ryanisgrig** [comment]
Default should take device timezone but allow user to override in settings

**Comment by abiemann** [comment]
This implementation is complete. @darrenj this is the JSON the app sends:

sendActivityAsync done: {"channelId":"directline","from":{"id":"625d6da6-1862-452b-b0ba-f2fa1ea5a7c5","name":"User"},"locale":"en-us","name":"VA.Timezone","type":"event","value":"Mountain Standard Time"}

**Comment by ryanisgrig** [comment]
@abiemann the channel should be `directlinespeech`? I'm thinking for this application if it's using that channel you shouldn't have to set it and it would run the same as the car app.
