### ISSUE TITLE
deply.ps1 errors if there are commented out section in JSON files

### ISSUE THREAD

**Issue by bfbatch** [microsoft/botframework-solutions#1682]
## Project

**Name**: Virtual Assistant

**Language**: C#

## Description
If there is commented out section in ARM template deploy script errors

## To Reproduce
comment out anything and run script

## Expected behavior
should ignore comment in JSON like the normal azure deploy scripts

## Screenshots
![Screen Shot 2019-06-27 at 3 05 22 PM](https://user-images.githubusercontent.com/38675303/60293399-1d6f1100-98ed-11e9-9c3a-0ad3c421e41c.png)

**Comment by darrenj** [comment]
JSON doesn't support comments? It's a data structure. Do you have an example whereby ARM scripts have can be commented out? We just provide the ARM template to ARM so it would seem that ARM itself doesn't like the comments?

**Comment by bfbatch** [comment]
Hi Darren,
I work with ARM pretty much exclusively. As of about 8 -12 months ago I stubbled on a git repo for property level copyIndex of an App Gateway and they were commenting each resource for ease of use (see attachment). This work just fine for Azure Resource Manager template deploy's via PS or in Azure DevOps (validation passes). The deploy.ps1 is attached that I typically deploy the templates with unless building out a release pipeline in ADO.
Having said all that, I assumed it would be the PS script that doesn't like the comment's but could be something else. 
Regards,Brian Batchelderc-850-228-5462 

    On Thursday, June 27, 2019, 05:28:49 PM EDT, Darren Jefford <notifications@github.com> wrote:  
 
 
JSON doesn't support comments? It's a data structure. Do you have an example whereby ARM scripts have can be commented out? We just provide the ARM template to ARM so it would seem that ARM itself doesn't like the comments?

**Comment by darrenj** [comment]
@bfbatch Can you attach your example file to this issue, it didn;'t come through via email.

**Comment by lauren-mills** [comment]
We use the Az CLI to deploy which it the recommended approach from Azure. Comments are not supported by the Az CLI according to the ARM documentation here: https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-authoring-templates#comments-and-metadata

> For inline comments, you can use // but this syntax doesn't work with all tools. You can't use Azure CLI to deploy the template with inline comments. And, you can't use the portal template editor to work on templates with inline comments. If you add this style of comment, be sure the tools you use support inline JSON comments.
