### ISSUE TITLE
[Linked Accounts] Disable auto sign-in and add sign out option

### ISSUE THREAD

**Issue by ryanisgrig** [microsoft/botframework-solutions#1689]
## Project

**Name**: Linked Accounts Web App

**Language**: C#

## Description

Browsers automatically sign in for linked accounts web app which makes it difficult to demo.
Users should be asked to sign in every time and have the ability to sign out.

**Comment by darrenj** [comment]
FYI - Signout should be possible through top-right, click on your username from memory. Also auto-signin may be hard to control given your logged into the intranet (and is often desirable for that reason). InPrivate mode helps for tests.

**Comment by ryanisgrig** [comment]
Good to know for logging out :)
It's possible for the Android app to open a webview in private mode
