### ISSUE TITLE
P1: Expand Yes/No entities for ConfirmPrompt

### ISSUE THREAD

**Issue by ryanisgrig** [microsoft/botframework-solutions#169]
**Is your feature request related to a problem? Please describe.**
See discussion at #136 for history. The current ConfirmPrompt is using a limited set of potential yes/no responses, we should provide additonal references that current customers have to provide for their own LUIS applications. This will be beneficial to all bots by supported additional entities at a system-level.

**Describe the solution you'd like**
Additional entities for matching both Yes & No

**Additional context**
We are looking to expand upon the EFIGS+ZH languages. Will track progress here with new entities below.

### Yes
| Valid Match | New Entities  (for review)| 
| ------------- |:-------------:|
|y| yup | 
|yes| yeah |  
|yep| yea |    
|sure| i think so |  
|ok| of course |  
|| aye |    
|| aye aye |    
|| totally |    
|| yessir |    
|| fine |    
|| alright |    
|| all right|    
|| very well |    
|| by all means |    
|| certainly |    
|| absolutely |    
|| indeed |    
|| affirmative |    
|| you bet |
|| you got it|

### No
| Currently supported by ConfirmPrompt | New Entities  (for review)| 
| ------------- |:-------------:|
|no| never | 
|nope| forget it |  
|no way| absolutely not |    
|not sure| negative |  
|| of course not |  
|| nah |    

### Yes
**Valid Match**|**New Entities  (for review)**
:-----:|:-----:
sur|absolument
sûr|certainment
ouais|sans aucun doute
oui|je pense
yep|bien
y|faisens ça
sure|oh our
approuver|yup
accepter|ok
consentir|d'accord|
ça marche|
ça marché|
allons-y|
oui s'il vous plait|
oui ce serait un grand merci|

### No
**Currently supported by ConfirmPrompt**|**New Entities  (for review)**
:-----:|:-----:
faux|en aucun cas
nan|proche
non|
pas d'accord|
pas concorder|
n'est pas|
pas ok| 
pas correct| 
pas| 
non merci|
non, c'est bon| 
pas question|
pas du tout|

## Italian
_Italian is not currently supported for choice_
### Yes
**Valid Match**|**New Entities (for review)**
:-----:|:-----:
 ||assolutamente
 ||sicuro
 ||sicuramente
 ||di sicuro
 ||credo di sì
 ||facciamolo
 ||oh sì
 ||sì per favore
 ||okk
 ||ok
 ||cosa sicura
 ||sì
 ||sì che sarebbe grande grazie
 ||perché no
 ||yep che è di destra
 ||yup

### No
**Valid Match**|**New Entities  (for review)**
:-----:|:-----:
 ||in nessun modoi
 ||vicino
 ||no
 ||no grazie
 ||no va bene
 ||assolutamente no
 ||niente affatto
 ||non proprio
 ||non in questo momento grazie

### Yes
**Valid Match**|**New Entities  (for review)**
:-----:|:-----:
wahr|absolut
ja|definitiv
jep|ich denke schon
j|lass es uns tun
sicher|machen wir das
ok|warum nicht
einverstanden|ja, bitte
sicherlich|okay
jap|sichere Sache
mache ich|
mit Sicherheit| 
oh ja|

### No
**Valid Match**|**New Entities  (for review)**
:-----:|:-----:
falsch|keineswegs
nein|nah
ne|neine, danke
nö|nein, das ist okay
nicht ok|Auf keinen Fall
nicht|Überhaupt nicht
nicht einverstanden|nicht wirklich
n|nicht gerade jetzt dank

### Yes
**Valid Match**|**New Entities  (for review)**
:-----:|:-----:
verdad|absolutamente
verdadero|seguro
sí|definitivamente
sip|eso creo
s|hagámoslo
si|vamos a hacer eso
cierto|bien
por supuesto|vale
ok|
 sí que es cierto| 
 sí que sería genial gracias| 
la verdad es que no|

### No
**Valid Match**|**New Entities  (for review)**
:-----:|:-----:
falso|de ninguna manera
no|cerca
nop|
n|
no|
ahora no gracias |
no gracias|
no está bien|
no es possible|

### Yes
**Valid Match**|**New Entities  (for review)**
:-----:|:-----:
好的|绝对
好啊|确定
好呀|确实
好嘞|我认为如此
好哇|我们来吧
没问题|让我们这样做
可以|当然可以
中|对的
好|还行
同意|肯定的事情
行|为什么不呢
是的| 那确实
是| 对啦
对| 
是的|
是的, 请|
嗯，可以|

### No
**Valid Match**|**New Entities  (for review)**
:-----:|:-----:
不行|绝非
不好|关闭
拒绝|现在不行谢谢
否定|不谢谢
不中|不没关系
不可以|不可能
不是的|一点也不
不是|没有
不对|
不| 
否| 
否的| 
不可| 
不可以的| 
不的| 
不行的| 
不可的| 
不对的| 
不可能的|

**Comment by ryanisgrig** [comment]
@lzc850612 and @elaine-chang, see the current Yes/No matching entities in [Chinese](https://github.com/Microsoft/Recognizers-Text/blob/master/.NET/Microsoft.Recognizers.Definitions/Chinese/ChoiceDefinitions.cs). Please let me know if you have any suggestions that would improve our China scenarios and I'll be sure to include them. Thanks!

**Comment by darrenj** [comment]
Thanks Ryan. It feels like the right thing to go "all in" on ConfirmPrompt and ensure it works in all scenarios as this would avoid us (and customers) having to maintain our own ConfirmYes and ConfirmNo intents for all scenarios. If so we would remove from our LUIS models - after a quick review it's only the ToDo skill that uses the General intent so safe to remove and simplifies things somewhat.  We should ensure we also remove from Enterprise Template

**Comment by darrenj** [comment]
Done some testing and updated examples from our LUIS models above which should be added. Raised priority, one to speak to John about?

**Comment by ryanisgrig** [comment]
I've added in the latest sample sets from ConfirmPrompt & our LUIS models for EFIGS+ZH above.

**Comment by fractalcrafter** [comment]
Yes - Chinese add the following:
当然可以
对的
嗯，可以
那确实
对啦

No - Chinese add the following:
否
否的
不可
不可以的
不的
不行的
不可的
不对的
不可能的

**Comment by ryanisgrig** [comment]
Thanks Elaine! I've tested all our potentials so far & updated the tables. I'll reach out to native speakers for our other languages.

Side note, would it be useful for us to have a label for multilanguage issues?

**Comment by fractalcrafter** [comment]
Great idea about starting labels for Multilanguage issues. I'd suggest labeling specific languages "Chinese, French, Italian, German, Spanish", or if it applies all those, label it "EFIGSC" or "FIGSC" as those are at least the tier 1 languages we plan to support. What do you think?

**Comment by darrenj** [comment]
Agree on a label, for new perhaps a "localisation" label will be enough - all being well we shouldn't have many issues across each language now the base localisation is done.

**Comment by ryanisgrig** [comment]
Let's start with `localisation` for now - if enough language specific issues arise we can consider individual ones.
