### ISSUE TITLE
Create meeting without Attendee name does not wait for Input

### ISSUE THREAD

**Issue by Adityagrao** [microsoft/botframework-solutions#1699]
## Project

**Name**:  Virtual Assistant - Calendar Skill

**Language**:  C#

## Description

When invoking "Schedule Meeting" without the Attendee name does not wait for the user to input the attendee name.

## To Reproduce

- Connect Calendar Skill to Virtual Assistant
- Run the Bot
- Say "Create an event", which will ask you to log in, log in
- Cancel all  dialogs by saying "Cancel" and say "yes"
- Again try to Schedule a meeting by saying "Create an Event" 

## Expected behavior

The Bot should wait for the User to input the attendee name and then search for them, and not take the previous input of "Create an Event" 
## Screenshots

![image](https://user-images.githubusercontent.com/11465032/60489628-6c88bd80-9cc2-11e9-8ce1-21e1099bf744.png)

**Comment by darrenj** [comment]
I suspect this might be related to [this issue](https://github.com/microsoft/botframework-solutions/blob/master/docs/reference/knownissues.md#when-invoking-a-skill-you-may-experience-the-initial-message-being-sent-twice).

Can you update your Virtual Assistant and Skill project to the latest Bot.Builder.Solutions and Bot.Builder.Skills packages please?

**Comment by Adityagrao** [comment]
> I suspect this might be related to [this issue](https://github.com/microsoft/botframework-solutions/blob/master/docs/reference/knownissues.md#when-invoking-a-skill-you-may-experience-the-initial-message-being-sent-twice).
> 
> Can you update your Virtual Assistant and Skill project to the latest Bot.Builder.Solutions and Bot.Builder.Skills packages please?

I am still having the same issue with the latest version 

![image](https://user-images.githubusercontent.com/11465032/60520191-9661d480-9d02-11e9-89f3-fada3fc37b2b.png)

**Comment by darrenj** [comment]
Did you make the code change to your assistant too? https://github.com/microsoft/botframework-solutions/blob/master/docs/reference/knownissues.md#when-invoking-a-skill-you-may-experience-the-initial-message-being-sent-twice

**Comment by Adityagrao** [comment]
Even after the code change had the issue, Tried reinstalling the package, Fixed the issue
