### ISSUE TITLE
QnA Maker disable/enable AzureSearch

### ISSUE THREAD

**Issue by andhdo** [microsoft/botframework-solutions#1701]
**Is your feature request related to a problem? Please describe.**

For development purposes, I have provided a virtual assistant solution, which uses the QnA cognitive component to do your business. As far as I know, this component implements (among other components):
* the cognitive component
* a webapp solution
* a blue search service

During development times, there are downtimes in which the component is not used, so I consider it unfair to pay the times when this component is active and is not used because it does not have an option to stop.

See the image below to see the azure search service costs used by QnA:

![image](https://user-images.githubusercontent.com/2402081/60523989-59b9bd00-9cb1-11e9-9547-c650714b8f60.png)

If I use a msdn license of USD150 per month to create a bot, this cost makes it impossible to use this QnA capability during a month of development.

**Describe the solution you'd like**

(1) Possibility of enabling / disabling the service during the development phase during times when this component is not used in production, or (2) an alternative to index the questions and answers during the development, (3) or a alternative to not use this component if the list of questions is not really long.

**Describe alternatives you've considered**

Provision / deprovisioning of the component with a script: but it could be a waste of time.

**Additional context**

**Comment by lauren-mills** [comment]
We have an open task to provide a development version of the arm template to reduce costs, so I will include this in that work. For now, you can override the sku parameters for these services to use the "free" tiers

**Comment by andhdo** [comment]
According the provisioned compoinents for virtual assistant: 

![image](https://user-images.githubusercontent.com/2402081/60540759-8da6d980-9cd5-11e9-8f80-32731c73ce81.png)

I was able to modify the AppServicePlan [1]; then i modified the web applications [2][3] to 1 single node and i put the luis component [4] in the F0 plan. 
However i don't know if is there any option for "sku parameters" for the azure search service. 
I'll appreciate if you can tell me how can i do this.

**Comment by lauren-mills** [comment]
I'm looking into how to change your existing search service and I'll get back to you.

You can do it during initial deployment from the powershell scripts by providing the parameters.template.json file with the following values:
```
{
  "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentParameters.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
    "qnaMakerServiceSku": {
      "value": "F0"
    },
    "qnaMakerSearchSku": {
      "value": "free"
    }
  }
}
```

**Comment by lauren-mills** [comment]
Looks like you can't change the pricing tier after deployment according to this documentation: https://docs.microsoft.com/en-us/azure/search/search-sku-tier

It's probably simplest to redeploy and provide the modified parameters.template.json file, but you could also try to create a new qna at the lower tier in the resource group. You would have to deploy your knowledgebases and add the configuration to the cognitivemodels.json file manually though.

**Comment by andhdo** [comment]
Understood. Thanks for your help. As soon as possible i'll execute the test over another subscription ('cause now my account has a zero balance).

**Comment by lauren-mills** [comment]
I'll close this for now, but feel free to reopen if you run into any issues.
