### ISSUE TITLE
[ToDo] Input hints appear incorrectly set

### ISSUE THREAD

**Issue by ryanisgrig** [microsoft/botframework-solutions#1704]
## Project
**Name**: Skills
**Language**:  C#

## Description

Feedback from self-host program:

"wakeword should not be required on 2nd turn. I see this in the Todo dialog. I have to say Computer even though this is a response to something the bot asks me. we should automatically start listening in this case and not require wakeword"

## To Reproduce

Run through the ToDo flow and validate that the correct InputHints are being returned with activities

## Expected behavior

Skill should use the appropriate input hints:
AcceptingInput - clients will use wakeword to trigger
ExpectingInput - bot prompts user and starts listening immediately
IgnoringInput - mic will be closed so bot can continue speaking

**Comment by ssss141414** [comment]
Thanks for your feedback.
    After our discussion, we think that most inputHints are correct. And we changed inputHints of WelcomeMessage and DidntUnderstandMessage from AcceptingInput to ExpectingInput.
    If you think there still exists some flows with wrong inputHints, please tell us your dialog.

**Comment by bobokids** [comment]
merged.
