### ISSUE TITLE
Skill workflow not started after Authentication code typed in

### ISSUE THREAD

**Issue by gjovanov** [microsoft/botframework-solutions#171]
**Description**
After a user logs in for certain skill (e.g. calendar skill with op "Create new meeting"), it's requested to enter the code from the OAuth dialog and when the received code is entered, it is being handled by the "general" LUIS which returns "None" as an intent and it doesn't continue with the meeting creation workflow.

**To Reproduce**
1. Type in name and location
2. Type in "Create new todo"
3. Enter the OAuth code, received from the Authentication dialog
4. Nothing happens (no todo creation workflow is started)
 
**Expected behavior**
After the code is auth entered, to continue to the skill workflow. It works from the individual skill .csproj, but not from the VirtualAssistant.csproj.

**Screenshots**
![image](https://user-images.githubusercontent.com/2255435/47372928-76016500-d6f3-11e8-8d03-a5aebb4dd3b5.png)

**Additional context**
N/A

**Comment by darrenj** [comment]
Thanks @gjovanov. Could you confirm the emulator version your using, we've seen a few issues with earlier versions but would be good to repro with the emulator your using to check what's going on

**Comment by gjovanov** [comment]
This is the version @darrenj 
![image](https://user-images.githubusercontent.com/2255435/47414121-e43c3b00-d778-11e8-956e-f0f4b83d5901.png)

However, pls note the same happens in the deployed version, which is just an .htm file with an iframe to a Direct Line channel

**Comment by gjovanov** [comment]
BTW I also debugged locally and in the CalendarSkillDialog.cs:
![image](https://user-images.githubusercontent.com/2255435/47414479-bacfdf00-d779-11e8-8c9e-3d3aaa7532ab.png)
after in the if statement it's entered, it renders the OAuth card and it's expecting an event (tokens/response). But actually it never receives such an event, but instead it handles the code input as "message" and in the EventPromt.cs:
![image](https://user-images.githubusercontent.com/2255435/47414656-244fed80-d77a-11e8-8281-3028621b3376.png)

Doesn't come at all to result.Succeeded = true

So the CalendarSkillDialog.TokenReponseValidator():
![image](https://user-images.githubusercontent.com/2255435/47414814-932d4680-d77a-11e8-965f-ea9b831fa148.png)

Returns false and herewith the whole process ends.

**Comment by lauren-mills** [comment]
I have a fix for this issue in PR. The issue was related to a missing step in the SkillDialog to convert the magic code to a TokenResponse and forward that to the skill.

**Comment by darrenj** [comment]
@gjovanov - Thanks for raising, let us know if this helps. Appreciate the heads up!
