### ISSUE TITLE
ResponseManager.GetCardResponse should inject more

### ISSUE THREAD

**Issue by xieofxie** [microsoft/botframework-solutions#1710]
**Is your feature request related to a problem? Please describe.**

When you use it, it only injects [Body[0]](https://github.com/microsoft/botframework-solutions/blob/e0c2e28d79900eb79a632160b38693d01ad400b5/lib/csharp/microsoft.bot.builder.solutions/microsoft.bot.builder.solutions/Responses/ResponseManager.cs#L184) into the container.

**Describe the solution you'd like**

Inject all bodies or convert the card to a Container to keep the backgroundImage of Adaptive Card etc.

**Describe alternatives you've considered**

**Additional context**

**Comment by darrenj** [comment]
@xieofxie  - Do you want to propose a PR to GetCardResponse to add the behaviour you would like?

**Comment by xieofxie** [comment]
Sure, I would like to work on this.

**Comment by lauren-mills** [comment]
Seems like this is closed by the PR. Reopen if needed.

**Comment by DingmaomaoBJTU** [comment]
This issue is found by #1711, but not yet resolved. xieofxie will handle this.
