### ISSUE TITLE
[JS VA] Not able to process OAuth request in skill

### ISSUE THREAD

**Issue by yuuzora** [microsoft/botframework-solutions#1715]
#Typescript 

I built a skill wich connect to an external platform and ask to sign in via OAuth2, it's working pretty well.

The problem comes when I launch this skill with the Virtual Assistant, the dispatch works correctly and the skill is able to recognize the intent etc...
Everything just stop at this line, no error, nothing : 
`sc.beginDialog('uniqueOauthPromptId');`

After further investigation, it has come to my attention that working with a skill and working with a skill FROM the virtual assistant implies working with two differents adapter 

So, the OauthPrompt seems to relies a lot on the adapter and doesn't seems to work with an SkillHttpBotAdapter adapter.

Is my way of doing the Oauth call is wrong and I should do it in the virtual assistant or is it just a bug ?

**Comment by darrenj** [comment]
Hi Zack,

We are waiting on an updated Websockets adapter for JS Skill support which should unblock skill invocation and also ensure Auth works (currently only supported by the BotFramework Adapter). This may not be an option for you but a C# VA should work fine - you can add a typescript based skill to it and see it all working end to end (@dfavretto and team can confirm if that combination works as expected).

We are expecting the updated library any day and will get the packages/generator updated. In the meantime you can test your Skill directly using Emulator and other channels which may unblock you too?

**Comment by yuuzora** [comment]
I'll stick to testing my skill directly on the emulator until it's fixed then ! 
Thanks for the quick answer

**Comment by Batta32** [comment]
Hi @Zack-Strife,

We are migrating the latest changes to the TypeScript libraries (`botbuilder-skills` and `botbuilder-solutions`). However, we are expecting the changes in the WebSocket adapter for JS to implement that functionality in the libraries.

In the meantime, you can use a Virtual Assistant in C# as @darrenj said!

**Comment by xieofxie** [comment]
If it is authed in VA, you have to modify function GetAuthenticationProvider in library Solutions manually. It will throw Exception for OAuth 2 now.. See #1386

**Comment by darrenj** [comment]
Work is tracked [here](https://github.com/microsoft/botframework-solutions/issues/2489) and targeting next release. Please keep an eye on the issue and we'll point at daily builds when available.
