### ISSUE TITLE
Fix stylecop references through repository

### ISSUE THREAD

**Issue by ryanisgrig** [microsoft/botframework-solutions#1718]
## User Story
As bot developer
I want a consistent stylecop approach
so that the code is standard and easily consumable and clear

## Acceptance Criteria 
*List your requirements.*
- [ ] ...
- [ ] ...
- [ ] ...

## Resources
*Provide any screenshots or conversation mockups to support your request.*
*Learn how to mock up bot conversations with [.chat files](http://aka.ms/bfchatfile).*

## Notes
*Provide any additional information.*

## Project
**Name**: All code base

## Description

Fix the Stylecop references throughout the repository to ensure they are only set for projects where it would be required (templates, skills, etc.). Currently it's very difficult to run some projects locally without setting up the specific rulesets.

Currently other solutions used for demos through a bunch of errors where a ruleset is missing. 
`Could not find rule set file "C:\Users\{user}\source\repos\AI\solutions\linkedaccounts\BotBuilder-DotNet.ruleset".`
Either we should include the ruleset everywhere or fix the settings so it only looks for a ruleset in projects we publish.

**Comment by darrenj** [comment]
@lzc850612 The props file should address this? Perhaps it’s not being found in the parent folders of Solutions?

**Comment by darrenj** [comment]
Update? I think this was resolved?
