### ISSUE TITLE
Please update your Microsoft.Client.Web project

### ISSUE THREAD

**Issue by TiagoBrenck** [microsoft/botframework-solutions#1721]
## Project

**Name**: Microsoft.Client.Web

**Language**: C#

## Description
We have updated the Token Cache Providers classes on the project https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/Microsoft.Identity.Web/Client/TokenCacheProviders

We highly recommend you to apply this changes on your repo because the previous cache provider classes had a problem with Guest users account. The PR with the recommend changes is this one https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/pull/121

Thanks

**Comment by ryanisgrig** [comment]
Thanks @TiagoBrenck - good timing as I had other changes to update on that solution today ;)
