### ISSUE TITLE
Wrong version of botbuilder-skills when generating a skill in TS  

### ISSUE THREAD

**Issue by rahulbabulal** [microsoft/botframework-solutions#1737]
## Project

**Name**: Skills Template

**Language**: TypeScript

## Description
When following the instructions to generate a skill using steps in [Typescript  generator] (https://github.com/microsoft/botframework-solutions/blob/master/docs/tutorials/typescript/skill.md)  it results in a start up error , after running
` npm run start
`
Here is the error.
`> tsc --p tsconfig.json && npm run copy-templates
./../../../../../../skill/node_modules/botbuilder-skills/lib"' has no exported member 'manifestGenerator'.
Found 1 error.`
 

Upon some troubleshooting I found that the issue is because of wrong version of 'botbuilder-skills' in package json.
The version using a default generator is 
`"botbuilder-skills": "^1.0.0-preview64",`  which is not correct.

Updating this  to 
`"botbuilder-skills": "^1.0.6-preview77",` fixes the issue.   

Please update the generator to have the right version.

**Comment by Batta32** [comment]
Hi @rahulbabulal,

We identified that issue and fixed it in PR #1658. Also, it is included in the generator's version greater than `1.0.5` but it isn't available in npm yet. You can check the package history [here](https://botbuilder.myget.org/feed/aitemplates/package/npm/generator-botbuilder-assistant).

As workaround, you can use the [sample-skill](https://github.com/microsoft/botframework-solutions/tree/master/templates/Virtual-Assistant-Template/typescript/samples/sample-skill) of the repo.

Another alternative is to use the latest preview of the generator following this steps:
1. Uninstall your generator executing `npm uninstall -g generator-botbuilder-assistant`
1. Install the latest preview version of the generator, executing `npm install -g generator-botbuilder-assistant@1.0.6-preview42 --registry https://botbuilder.myget.org/F/aitemplates/npm`

**Comment by rahulbabulal** [comment]
@Batta32  Thanks for following up and the sharing the details.   I will try your recommended steps next time I generate a new skill.    

Appreciate the quick turn around.

**Comment by rahulbabulal** [comment]
@Batta32   I closed the issue, let me know if we need to leave it open for your internal tracking.

**Comment by Batta32** [comment]
Nice @rahulbabulal, there is no need to leave this issue open, feel free to re-open if you have a similar issue.
