### ISSUE TITLE
Deploy.ps1 needs to quote parameters to external commands

### ISSUE THREAD

**Issue by Dan-Albrecht** [microsoft/botframework-solutions#1739]
## Project

**Name**: Virtual Assistant

**Language**: PowerShell

## Description
Deploy.ps1 doesn't quote parameters to the az command and this leads to script failures when some of the arguments contain special characters.

## To Reproduce
```PowerShell
.\Deployment\Scripts\deploy.ps1 -name Repro -location WestUS2 -appPassword "abcDEF123()#thisBreaksMe" -luisAuthoringKey "abc123" -luisAuthoringRegion westus
```

## Expected behavior
No errors

## Actual behavior
```
#thisBreaksMe was unexpected at this time.
ConvertFrom-Json : Conversion from JSON failed with error: Unexpected character encountered while parsing value: C. Path '', line 0, position 0.
At C:\Users\Dan\Source\Repos\MyAssistant1\MyAssistant1\MyAssistant1\Deployment\Scripts\deploy.ps1:88 char:20
+         $appId = ($app | ConvertFrom-Json) | Select-Object -ExpandPro ...
+                          ~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [ConvertFrom-Json], ArgumentException
+ FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.Commands.ConvertFromJsonCommand

! Could not provision Microsoft App Registration automatically. Review the log for more information.
! Log: C:\Users\Dan\Source\Repos\MyAssistant1\MyAssistant1\MyAssistant1\Deployment\Scripts\..\deploy_log.txt
+ Provision an app manually in the Azure Portal, then try again providing the -appId and -appPassword arguments. See https://aka.ms/vamanualappcreation for more information.
```

## Additional context
Note the ```#thisBreaksMe was unexpected at this time.``` at the start of the error message.

**Comment by skimming** [comment]
seems like a similar issue is occuring when global modules are being referenced: 
> Creating resource group ...
> Validating Azure deployment ...
> Deploying Azure services (this could take a while)...
> Updating appsettings.json ...
> Deploying cognitive models ...
> Initializing dispatch model ...
> Parsing general LU file ...
internal/modules/cjs/loader.js:605
    throw err;
    ^

Error: Cannot find module **'C:\Users\Samuel'**
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
    at Function.Module._load (internal/modules/cjs/loader.js:529:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:775:12)
    at startup (internal/bootstrap/node.js:300:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:826:3)
> Deploying general LUIS app ...
! Could not deploy LUIS model. Review the log for more information.
! Log: C:\proj2\botbuilder\sample-assistant\deployment\scripts\..\deploy_cognitive_models_log.txt
! Could not create LUIS app. Skipping dispatch add.
