### ISSUE TITLE
ListToSpeechReadyString should support more

### ISSUE THREAD

**Issue by xieofxie** [microsoft/botframework-solutions#1745]
**Is your feature request related to a problem? Please describe.**

Inside it, [ListToSpeechReadyString](https://github.com/microsoft/botframework-solutions/blob/5cec33e5be13369a4aa55733522bd4d1d48f2742/lib/csharp/microsoft.bot.builder.solutions/microsoft.bot.builder.solutions/Responses/SpeechUtility.cs#L90) only supports a maximum of 5 selectionStrings.

**Describe the solution you'd like**

More dynamic or throw an exception when unsupported?

**Describe alternatives you've considered**

Use something like 'x items more'.

**Additional context**

**Comment by ryanisgrig** [comment]
@Quirinevwm to provide feedback on how many max options should be read out.  This scenario is taking a list of objects and converting it into a speech-friendly output.
When this was designed I believe I made it a max 5 based on recommended guidelines (an Assistant should not be reading out "the first is X....the second is Y....the tenth is Z"), if we keep this guideline I would be ok with throwing an exception for any number higher. It's more complex to have this be multi-language and dynamically understand the semantics on how to read out a list.

**Comment by bobokids** [comment]
not a common issue. let us revisit if there is real requirement.
