### ISSUE TITLE
Explore Maluuba List Selection/Phonetic library for our skill scenarios

### ISSUE THREAD

**Issue by darrenj** [microsoft/botframework-solutions#175]
## User Story
As ...
I want ...
so that ...

## Acceptance Criteria 
*List your requirements.*
- [ ] ...
- [ ] ...
- [ ] ...

## Resources
*Provide any screenshots or conversation mockups to support your request.*
*Learn how to mock up bot conversations with [.chat files](http://aka.ms/bfchatfile).*

## Notes
*Provide any additional information.*

**User story**
As a user of a Virtual Assistant out of the box I can provide more free-form responses to questions from all skills - the one on 5th avenue in response to a poi response,  "the email from lauren", etc. Ideally pushed into base level prompts so everything benefits

Top of mind to experiment on would be:

Email: Where we return an email summary, explore how this could enable:
•	The one from Ted
•	Text in the subject line

Calendar: Where we show upcoming meetings
•	What’s the last meeting
•	First meeting
•	The one with Lauren

PoI: Show a list of POIs
•	The one on 5th avenue
•	4th one

**Comment by ryanisgrig** [comment]
Duplicate of #78

**Comment by Dewain27** [comment]
@darrenj is this still a valid need?

**Comment by darrenj** [comment]
Addressed as part of adaptive and no language support for open sourced phonetic library.
