### ISSUE TITLE
Converting LUIS Json to LU 

### ISSUE THREAD

**Issue by neetgupta7** [microsoft/botframework-solutions#1750]
How can i convert json file for LUIS into .lu file? Or it has to be done manually.

**Comment by darrenj** [comment]
Hi

The [ludown tool](https://github.com/Microsoft/botbuilder-tools/tree/master/packages/Ludown) can do this for you: `ludown refresh -i YourFile.json'

**Comment by neetgupta7** [comment]
Thank You
