### ISSUE TITLE
update ChoiceDefaults of ConfirmPrompt 

### ISSUE THREAD

**Issue by xieofxie** [microsoft/botframework-solutions#1751]
**Is your feature request related to a problem? Please describe.**

No support for Italian as in VA.

ChoiceDefaults should be 'public' to ease situations when one wants to send culture-aware confirm via other ways like clicking on pictures, cards etc.

**Describe the solution you'd like**

Add Italian Choices.

Mark ChoiceDefaults public.

**Describe alternatives you've considered**

N/A.

**Additional context**

N/A.

**Comment by ryanisgrig** [comment]
Prompts are dependent on the @microsoft/recognizers-text repository: https://github.com/microsoft/Recognizers-Text

https://github.com/microsoft/Recognizers-Text/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+italian

**Comment by xieofxie** [comment]
The function RecognizeBoolean is used with a culture argument, so I am afraid if one types yes in a Chinese locale, it will not work. What I need here is something like [Boolean.ToString](https://docs.microsoft.com/en-us/dotnet/api/system.boolean.tostring?view=netframework-4.8#System_Boolean_ToString_System_IFormatProvider_), however, this function 'does not reflect culture-specific settings'.

**Comment by xieofxie** [comment]
Oops.. issue is opened in wrong project..
