### ISSUE TITLE
[Android App] Detect when connectivity is unavailable and queue messages for the VA

### ISSUE THREAD

**Issue by ryanisgrig** [microsoft/botframework-solutions#1753]
## User Story
As ...
I want ...
so that ...

## Acceptance Criteria 
*List your requirements.*
- [ ] ...
- [ ] ...
- [ ] ...

## Resources
*Provide any screenshots or conversation mockups to support your request.*
*Learn how to mock up bot conversations with [.chat files](http://aka.ms/bfchatfile).*

## Notes
*Provide any additional information.*

Detect when connectivity is not available and queue up questions which are then sent once connectivity is restored. Android OS seems to  have a [Connectivity Manager](https://developer.android.com/training/monitoring-device-state/connectivity-monitoring) to help with this.

This will enable us to talk to scenarios when a device is occasionally disconnected (e.g. car) and how we are able to queue things and then resume.

Showing an indicator that the app is "offline" would be helpful too.

We can then demo with plane mode on/off.  

This will require some investigation on what is functionally possible first, as well as UX design to determine how many messages from a user should be queued. For example, if the following is queued up:
1. "Who is Bill Gates?"
2. "What's on my calendar?"
3. "Find me a coffee shop!"

Should the VA really respond with all:
1. Bill Gates is ....
2. Here are your meetings ...
3. Here are some points of interest ...

or just respond to the last question?

**Comment by abiemann** [comment]
The following will be implemented:
1. Show in the main app when connectivity *to the bot* is lost
2. Broadcast an event to widgets when connectivity is lost and regained
~~3. Buffer most recent audio files of last request and auto re-send when connectivity is gained~~ see #2152 the client would just request "repeat that"

**Comment by abiemann** [comment]
SpeechSDK also needs a callback for when the connection is re-established
for now, send a Cancel (silent/back channel) when bot is reconnected. see #2153
