### ISSUE TITLE
Caching of LUIS recognition result is gone in Virtual Assistant template

### ISSUE THREAD

**Issue by hansmbakker** [microsoft/botframework-solutions#1759]
## Project

**Name**: Virtual Assistant
**Language**: C#

## Description
In Enterprise Bot Template, the LUIS recognition result was cached for improved speed and less costs. This was done by [putting the LUIS result in the turnstate](https://github.com/microsoft/botframework-solutions/blob/529d2cc05f6f0fda68380347d95c0eb042b4c7fa/templates/Enterprise-Template/src/csharp/EnterpriseBotTemplate/EnterpriseTemplate/Dialogs/Shared/EnterpriseDialog.cs#L42-L52).

While migrating to the Virtual Assistant Template, I see that this code is not present in [`OnInterruptDialogAsync(...)`](https://github.com/microsoft/botframework-solutions/blob/b181fd590c5c8b6e12f357088f66e2c5cbd56528/templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Dialogs/MainDialog.cs#L292) anymore

## To Reproduce
See code pointers in description

## Expected behavior
No unneccessary LUIS calls

**Comment by hansmbakker** [comment]
@lauren-mills / @darrenj I see you put it on the backlog, thank you.

Would it be possible for you to give a statement whether this change was intended or not, independent from a possible fix?

**Comment by darrenj** [comment]
Templates help provide a starting point - once generated you have the code to further extend/improve. Any reason why you can’t just add the code to store in a location of your choosing?

We aligned/simplified things with the VA template and in all reality the `General` LUIS model won’t be used subsequently that often. Your **own** LUIS model that you choose to add/extend you may wish to store for later use depending on your scenario.

For example in the Skill Template which does have a custom LUIS model ready for your use does do this [here](https://github.com/microsoft/botframework-solutions/blob/master/templates/Skill-Template/csharp/Sample/SkillSample/Dialogs/SkillDialogBase.cs#L141)

**Comment by darrenj** [comment]
Closing as this isn't something we feel is necessary for the Virtual Assistant out of the box. As you add your own LUIS models you can certainly add this as needed but the General model is pretty straight forward. Open to feedback if you feel differently.
