### ISSUE TITLE
BF Composer VA sample

### ISSUE THREAD

**Issue by ryanisgrig** [microsoft/botframework-solutions#1765]
## User Story
As ... a bot developer
I want ... a sample of the Virtual Assistant using the BF Composer
so that ... I can bootstrap everything needed to deploy/test dialogs and compose with skills/coded dialogs and QnA.

## Acceptance Criteria 
*List your requirements.*
- [ ] ...
- [ ] ...
- [ ] ...

## Resources
*Provide any screenshots or conversation mockups to support your request.*
*Learn how to mock up bot conversations with [.chat files](http://aka.ms/bfchatfile).*

## Notes
*Provide any additional information.*
Provide sample for Conversation Designer based projects enabling bootstrapping of everything needed to deploy/test dialogs and compose with skills / coded dialogs and QnA.

**Comment by Dewain27** [comment]
Blocked until Designer is completed
