### ISSUE TITLE
End-to-end performance review and tuning 

### ISSUE THREAD

**Issue by ryanisgrig** [microsoft/botframework-solutions#1768]
## User Story
As ... a bot developer
I want ... to understand where time is spent in operations
so that ... I can identify bottlenecks and appropriately tune my Virtual Assistant.

## Acceptance Criteria 
*List your requirements.*
- [ ] ...
- [ ] ...
- [ ] ...

## Resources
*Provide any screenshots or conversation mockups to support your request.*
*Learn how to mock up bot conversations with [.chat files](http://aka.ms/bfchatfile).*

## Notes
*Provide any additional information.*

**Comment by Dewain27** [comment]
@darrenj could you please add details to the description around the following information:

- Overall goal of effort
- What metrics do we want to track?
- Is this automated test?
- Is this a recurring action or one time effort?

**Comment by darrenj** [comment]
Performance reviews underway
