### ISSUE TITLE
Enterprise Assistant Solution Accelerator - Teams Integration

### ISSUE THREAD

**Issue by ryanisgrig** [microsoft/botframework-solutions#1770]
**Is your feature request related to a problem? Please describe.**

Virtual Assistant/Bot Framework deeply integrated in teams, addressing known issues around authentication, SSO, cards (pushing changes into SDK) and taking advantage of more advanced features (e.g. tabs/notifications). Goal is Teams to “just work” and enables us to harness global Teams ecosystem for customer deployment.

**Comment by Dewain27** [comment]
Broken into multiple Issues #1804 #1803 #1788

**Comment by aishwaryaumachandran** [comment]
Any possible timeline for Teams integration ?

**Comment by lzc850612** [comment]
We're working with Microsoft Teams organization to determine what is needed. We've also broken it into the three issues #1804 #1803 #1788 to track our potential work to realize this. You can still use the bot in Teams channel while we work on these.
