### ISSUE TITLE
Skill Toggling for VA

### ISSUE THREAD

**Issue by lzc850612** [microsoft/botframework-solutions#1774]
## User Story
As ... a bot owner
I want ... conditionally enable the skills that are connected to my Virtual Assistant
so that ... I can control the experience for different markets and segments

## Acceptance Criteria 
*List your requirements.*
- [ ] Per user group (i.e. region, segment) I want to enable or disable skills through configuration
- [ ] If a user sends an utterance for a skill that is not enabled for their region or segment, they should get a "do not understand" message

## Resources
*Provide any screenshots or conversation mockups to support your request.*
*Learn how to mock up bot conversations with [.chat files](http://aka.ms/bfchatfile).*

## Notes
*Provide any additional information.*
Design how to enable Skills to be toggled on/off for groups of users, regions, locales, etc. enabling fine grained control of a globally deployed assistant.

**Comment by Dewain27** [comment]
Please connect with MCS EAP on how this has been done for automotive customers already in the field.
