### ISSUE TITLE
1P Skill Interop

### ISSUE THREAD

**Issue by lzc850612** [microsoft/botframework-solutions#1777]
## User Story
As ...
I want ...
so that ...

## Acceptance Criteria 
*List your requirements.*
- [ ] ...
- [ ] ...
- [ ] ...

## Resources
*Provide any screenshots or conversation mockups to support your request.*
*Learn how to mock up bot conversations with [.chat files](http://aka.ms/bfchatfile).*

## Notes
*Provide any additional information.*

Further work with CCI, Xiaolice and Cortana on interop scenarios

**Comment by Dewain27** [comment]
@darrenj are there any specific work items that are known at this time?

**Comment by ryanisgrig** [comment]
Closing as this doesn't have defined development work
