### ISSUE TITLE
Conversational Design Integration work (with Design Team and Speech Team)

### ISSUE THREAD

**Issue by lzc850612** [microsoft/botframework-solutions#1779]
## User Story
As ...
I want ...
so that ...

## Acceptance Criteria 
*List your requirements.*
- [ ] ...
- [ ] ...
- [ ] ...

## Resources
*Provide any screenshots or conversation mockups to support your request.*
*Learn how to mock up bot conversations with [.chat files](http://aka.ms/bfchatfile).*

## Notes
*Provide any additional information.*

**Comment by Dewain27** [comment]
@darrenj please provide more details as to the requirements and expectations of this Issue.

**Comment by ryanisgrig** [comment]
Close as this will be related per Skill
