### ISSUE TITLE
Test and adopt new testing approaches from SDK team as part of VA, Skills and Templates

### ISSUE THREAD

**Issue by Dewain27** [microsoft/botframework-solutions#1783]
## User Story
As ...
I want ...
so that ...

## Acceptance Criteria 
*List your requirements.*
- [ ] ...
- [ ] ...
- [ ] ...

## Resources
*Provide any screenshots or conversation mockups to support your request.*
*Learn how to mock up bot conversations with [.chat files](http://aka.ms/bfchatfile).*

## Notes
*Provide any additional information.*

**Comment by darrenj** [comment]
Could you review latest testing work from Gabo in SDK to explore what changes we need to make for this?
