### ISSUE TITLE
Single sign-on via WebChat

### ISSUE THREAD

**Issue by ryanisgrig** [microsoft/botframework-solutions#1784]
**Is your feature request related to a problem? Please describe.**

Ensure SSO “just works” across WebChat

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ryanisgrig** [comment]
See Web Chat [SSO Enterprise Sample](https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/19.a.single-sign-on-for-enterprise-apps) & [SSO Intranet Sample](https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/19.b.single-sign-on-for-intranet-apps)

**Comment by ryanlengel** [comment]
@Dewain27 if this is closed can you explain how we have measured completeness? If this is referring to the single webchat demo environment you've used then that does not meet the criteria of a SSO Web Chat:
* It's a regular web chat, not the SSO Enterprise Sample I linked above
* It is only enabled for one environment, not the daily/weekly/release environments
* There is no CI/CD pipeline enabled for it

Can you clarify if I'm misunderstanding the intent of this issue? I'm confused as to what is "done" here. Thanks!

**Comment by ryanisgrig** [comment]
@Dewain27 if this is closed can you explain how we have measured completeness? If this is referring to the single webchat demo environment you've used then that does not meet the criteria of a SSO Web Chat:
* It's a regular web chat, not the SSO Enterprise Sample I linked above
    * Does the Sample meet your expectations @darrenj?
* It is only enabled for one environment, not the daily/weekly/release environments
* There is no CI/CD pipeline enabled for it

Can you clarify if I'm misunderstanding the intent of this issue? I'm confused as to what is "done" here. If there's an offline discussion about this it will help to put in the notes when closing an issue. Thanks!
