### ISSUE TITLE
Enterprise notifications

### ISSUE THREAD

**Issue by ryanisgrig** [microsoft/botframework-solutions#1785]
**Is your feature request related to a problem? Please describe.**

Enable enterprise-wide notifications delivered through Enterprise Assistant / Teams.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Dewain27** [comment]
@lzc850612  determine if there is any additional work that is needed here beyond #1378

**Comment by lzc850612** [comment]
No additional work on top of #1378 so closing this
