### ISSUE TITLE
Linked Accounts Android App support

### ISSUE THREAD

**Issue by ryanisgrig** [microsoft/botframework-solutions#1786]
Surface how a linked accounts experience can be added to an Android app alongside the web version.

**Comment by Dewain27** [comment]
@ryanlengel provide @abiemann with information and solution for connecting to application in a more secure fashion.

**Comment by Dewain27** [comment]
@darrenj We need to design how we get this to work through security review.

**Comment by ryanisgrig** [comment]
Blocked by #1767

**Comment by Dewain27** [comment]
Will resolve as part of #1789
