### ISSUE TITLE
Enable Authentication via Direct Line Speech channel

### ISSUE THREAD

**Issue by Dewain27** [microsoft/botframework-solutions#1789]
## User Story
As ... bot user
I want ... to  be able to log into my Direct Line VA with my AAD credentials
so that ... I do not have to log in again with the same account and access AAD authenticated skills, such as calendar.

## Acceptance Criteria 
*List your requirements.*
- [ ] The Android App requires the following properties for configuration/settings for Sign On to be offered: (Configuration File is where these settings should be set)
     - [ ] Direct Line Secret 
     - [ ] AAD Oauth Redirect Uri 
     - [ ] AAD Oauth Client Id
     - [ ] Microsoft App Id
     - [ ] Microsoft App Password
- [ ] If required fields above are not populated by the developer, then Sign On is not displayed in the UI of Android application and Anonymous is used as the authenticated user.
- [ ] "Sign in" is shown on the side bar. If the user is already signed in, it says "Sign out"
![image](https://user-images.githubusercontent.com/43043272/70104655-92104f00-15f3-11ea-80a2-0ce93dcd5398.png)   
- [ ] User can have a conversation with the bot anonymous or authenticated, but if it is anonymous (User not Signed On) they should expect to see error messages when a skill tries to log in
- [ ] Obtain the refresh token with "Authorization Code Grant" flow and store on Android device (**encrypted?**)
- [ ] Android Application should maintain the token and refresh before token expatriation
- [ ] User's AAD credentials should be passed from client to the VA to authenticate user with bot token service
-[ ] Should follow the same pattern as #1788 
- [ ] User ID option needs to be removed from the settings file/UI. If the user is unauthenticated, a random guid is assigned to the from.id.

## Resources
*Provide any screenshots or conversation mockups to support your request.*
*Learn how to mock up bot conversations with [.chat files](http://aka.ms/bfchatfile).*

**Mock up TBD**

## Notes
*Provide any additional information.*

@ryanlengel: Investigate SSO web chat sample for required Azure app info, config settings, business logic of authenticating to API endpoint: https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/19.a.single-sign-on-for-enterprise-apps

See these notes on token to use: https://github.com/microsoft/botframework-solutions/issues/1789

**Comment by ryanisgrig** [comment]
Use the Linked Accounts logic for Direct Line token exchange: https://github.com/microsoft/botframework-solutions/blob/master/samples/csharp/clients/linkedaccounts.web/Controllers/HomeController.cs

Ideal flow:
1. Unauthenticated user has a user id like "directlinespeech|{random guid" which is used in the From properties. User asks "what meetings do I have today?"
2. Bot tells user they have to link their account.
3. User clicks sign-in (passing their current user id), links their account with the bot, and auth pop-up closes. 
4. User asks again "what meetings do I have today?"
5. Bot uses that same user id and looks up to see if token is stored in the Azure Bot Service (existing logic), it finds it and can access their personal data. Bot replies with their meetings.

**Comment by bobokids** [comment]
Code merged in.
