### ISSUE TITLE
Adaptive Cards 1.2 Support

### ISSUE THREAD

**Issue by Dewain27** [microsoft/botframework-solutions#1803]
## User Story
As ... a bot developer
I want ... to use Adaptive Cards 1.2 when it is available on supported channels like Teams
so that ... I can take advantage of the latest UI features

## Acceptance Criteria 
*List your requirements.*
- [ ] ...
- [ ] ...
- [ ] ...

## Resources
*Provide any screenshots or conversation mockups to support your request.*
*Learn how to mock up bot conversations with [.chat files](http://aka.ms/bfchatfile).*

## Notes
*Provide any additional information.*

When Teams has released 1.2 support for Adaptive Cards.  The VA solution accelerator should be updated to support 1.2 features.

**Comment by xieofxie** [comment]
I could keep an eye on skill samples for this.

**Comment by litofish** [comment]
Libs need to be updated to 1.2 to also support cards in skills that use new adaptive card features.

**Comment by tommyJimmy87** [comment]
Hi @Dewain27, do you have already an idea when MS Teams will release the version 1.2 of adaptive cards ? Also I guess would be very cool to have the integration of the React Custom Library in the VA as well.

**Comment by ryanisgrig** [comment]
From reviewing VA/Skills they are all referencing v1.2+ of Adaptive Cards. Closing this issue.
