### ISSUE TITLE
Add Tabs / Notifications Support in Teams Channel

### ISSUE THREAD

**Issue by Dewain27** [microsoft/botframework-solutions#1804]
## User Story
As ...
I want ...
so that ...

## Acceptance Criteria 
*List your requirements.*
- [ ] ...
- [ ] ...
- [ ] ...

## Resources
*Provide any screenshots or conversation mockups to support your request.*
*Learn how to mock up bot conversations with [.chat files](http://aka.ms/bfchatfile).*

## Notes
*Provide any additional information.*

Add Tabs / Notifications Support in Teams Channel

**Comment by Dewain27** [comment]
@darrenj  can you please look at this feature and provide more details to how you would like Tabs / Notifications to be leveraged for this Issue?

**Comment by darrenj** [comment]
Support through BF SDK for Teams
