### ISSUE TITLE
Adaptive Context Switching

### ISSUE THREAD

**Issue by Dewain27** [microsoft/botframework-solutions#1805]
## User Story
As ... bot user
I want ... to be able to switch between dialogs and skills based on intent
so that ... I can complete more complex tasks

## Acceptance Criteria 
*List your requirements.*
- [ ] Enable the following scenarios:
     - [ ] Dialog-to-dialog context switching
     - [ ] Skill-to-skill context switching, resuming first conversation after switch
     - [ ] Skill-to-skill context switching with a queue of future tasks to complete
- [ ] Allow current dialog to decide if context switch should be allowed

## Resources
*Provide any screenshots or conversation mockups to support your request.*
*Learn how to mock up bot conversations with [.chat files](http://aka.ms/bfchatfile).*
[skill_to_skill_queue.chat.txt](https://github.com/microsoft/botframework-solutions/files/3628248/skill_to_skill_queue.chat.txt)
[skill_to_skill_queue_2.chat.txt](https://github.com/microsoft/botframework-solutions/files/3628249/skill_to_skill_queue_2.chat.txt)
[skill_to_skill_with_resume.chat.txt](https://github.com/microsoft/botframework-solutions/files/3628250/skill_to_skill_with_resume.chat.txt)
[dialog_to_dialog.chat.txt](https://github.com/microsoft/botframework-solutions/files/3628251/dialog_to_dialog.chat.txt)
[skill_to_skill_cancellation.chat.txt](https://github.com/microsoft/botframework-solutions/files/3628252/skill_to_skill_cancellation.chat.txt)

## Notes
*Provide any additional information.*
*Dependent on #903

**Comment by darrenj** [comment]
Merged

**Comment by alexrecuenco** [comment]
Wait, what happened with this. Where is the solution that was created as part of this story? I can't find it in botframework-solutions

Sorry for the inconvenience.
