### ISSUE TITLE
template.json contains hard-coded values

### ISSUE THREAD

**Issue by sachabruttin** [microsoft/botframework-solutions#1812]
## Project

**Name**: Virtual Assistant

**Language**: C#

## Description
The deployment template file contains hard-coded values that force the creation of resources in westus2 instead of either the Resource Group location or the value passed in parameter. 

## To Reproduce
Run deploy.ps1 in an RG in westeurope. Application Insights and CS QnAMaker are created in westus2.

## Expected behavior
Resources must be created according to the parameters. The default value must be the RG location.

**Comment by darrenj** [comment]
This is by design, qna maker core services are only available in westus : https://github.com/microsoft/botframework-solutions/blob/master/docs/reference/knownissues.md#qnamaker-cant-be-entirely-deployed-in-a-region-other-than-westus

**Comment by sachabruttin** [comment]
I agree for qna maker, but Application Insights can be deployed in any location. 
I just tried to create a qna maker in west europe from the Azure Portal and all resources except the the CS are in west europe. 

So if we fix the deployment.json file more resources will be created correctly and as soon as qna maker will be available outside of US then it will be correctly created.

![image](https://user-images.githubusercontent.com/2523409/61039558-443e4480-a3cf-11e9-9120-febde7142f2d.png)
