### ISSUE TITLE
Linked Accounts Example inside Typescript Virtual Assistant link not working

### ISSUE THREAD

**Issue by andhdo** [microsoft/botframework-solutions#1824]
#### What project is affected?
botframework-solutions

#### What language is this in?
Typescript

#### What happens?
linked accounts "link" not wirking in the generated example or a similar one to test authentication feature of virtual assistant.

#### What are the steps to reproduce this issue?
Generated a new project using the scaffold utility (generator-botbuilder-assistant).
Then the steps of [linked accounts reference](https://github.com/microsoft/botframework-solutions/blob/master/docs/howto/assistant/linkedaccounts.md) are made in the azure-ad configuration of portal.azure.com, adding a new one registration. 

However the target application does not exists and is not known where the linked application exists to be modified: 

![image](https://user-images.githubusercontent.com/2402081/61085692-6c09c880-a420-11e9-826b-e10efdadc0eb.png)

MicrosoftAppId, password were configured and the bot is running; 
![image](https://user-images.githubusercontent.com/2402081/61085553-0ddce580-a420-11e9-80de-2d2f4ef3419e.png)

#### What were you expecting to happen?
A clear example of authentication enabled in virtual assistant and ready to work; 

#### Any screenshots or additional context?
seems not be clear if you need to create a new skill to enable authentication in virtual assistant or a way to test graph api classes generated by the scaffold of the bot. 
simple examples works but not in the virtual assistance context. Looks like Linked accounts were the perfect example to see this working but it does not have the source code of the counterpart.

**Comment by Batta32** [comment]
Hi @andhdo,

You are right that the correct link of the `Linked Accounts` is the one you [mentioned](https://github.com/microsoft/botframework-solutions/blob/master/docs/howto/assistant/linkedaccounts.md).

About the button of `Linked Accounts` in the `Intro Card` of the Virtual Assistant, we noticed that action was removed for `en` and not in the rest of the languages. 
@darrenj, should we remove that action in the `Intro Card` of the rest of the languages or add it in the `en` one?

**Comment by darrenj** [comment]
Yes we should remove to be inline with C# - it's not something everyone needs to configure so didn't make sense to have it front and center. Linked Accounts is only needed typically for voice first scenarios where you can't authenticate in the usual "inline" way

**Comment by Batta32** [comment]
Hi @darrenj,

The inconsistence of the Intro Cads happens in both, C# and TypeScript. The only language which doesn't contain that action is `en`. 

We will create a PR fixing this for C# and TypeScript, removing the `Linked Accounts` action for all the cards in all languages.
