### ISSUE TITLE
CustomAdapter Design for speech streaming

### ISSUE THREAD

**Issue by lzc850612** [microsoft/botframework-solutions#1837]
## User Story
As ...
I want ...
so that ...

## Acceptance Criteria 
*List your requirements.*

## Resources
*Provide any screenshots or conversation mockups to support your request.*
*Learn how to mock up bot conversations with [.chat files](http://aka.ms/bfchatfile).*

## Notes
*Provide any additional information.*

With Directline Speech channel, we need to find out how to support the CustomAdapter approach with speech streaming capability.

**Comment by darrenj** [comment]
Addressed
