### ISSUE TITLE
[Botskill CLI] Add additional QnA services

### ISSUE THREAD

**Issue by h2floh** [microsoft/botframework-solutions#1860]
#### What is the solution you are looking for?
It would be great if like the skill connect command (updating LUIS dispatch in Mother Bot) there would be a command to add additional QnA Makers to the motherbot and automatically update the dispatch LUIS module.

#### What alternatives have you considered?
(Workaround exists in modify xyz_Dispatch.dispatch and xyz_Dispatch.json under Depoyment/Resourches/Dispatch manually)

**Comment by lauren-mills** [comment]
The botskills tool is just for adding/removing skills. If you want to deploy an additional QnA Maker knowledgebase for VA this is what I'd recommend:

1. Create the kb in the qnamaker.ai portal,
2. Add the config for your kb directly to your cognitivemodels.json
3. Run  `.\Deployment\Scripts\update_cognitive_models.ps1 -RemoteToLocal` to pull down the .lu file for your kb and update dispatch/DispatchLuis.cs

**Comment by h2floh** [comment]
@lauren-mills sounds great! Thanks

**Comment by lauren-mills** [comment]
I'll close this for now, but if you run into any issues with that flow please reopen.
