### ISSUE TITLE
[Predefined Skills] LUIS auto generated code of deployment script breakes build

### ISSUE THREAD

**Issue by h2floh** [microsoft/botframework-solutions#1861]
#### What project is affected?
POI, TODO, MAIL Skill

#### What language is this in?
C#

#### What happens?
Error occured for pre-defined Mail TODO and POI Skill. The deployment script changes the Name of the LUIS classes from upper-case e.g. EmailLuis to emailLuis which breaks following builds.

There seems some inconsistencies between the GitHub Version of the LUIS classes and the autogenerated versions within the deployment script. We didn't debugged it, just changed the class names back to upper-case style.

#### What are the steps to reproduce this issue?
Download the Skill Solutions. Build the skill Projects (should succeed). Run the deployment script. Try to build the Projects again (should fail).

#### What were you expecting to happen?
Running the deployment script and afterwards build the Project again without any errors.

**Comment by lauren-mills** [comment]
I've recently made some updates to these files to fix this behavior. I have this PR out right now #1869 that should fix POI

**Comment by lauren-mills** [comment]
Closed by #1869 

Please reopen if you continue to have this issue.
