### ISSUE TITLE
[TODO Skill] Build breakes after first deployment

### ISSUE THREAD

**Issue by h2floh** [microsoft/botframework-solutions#1862]
#### What project is affected?
TODO Skill

#### What language is this in?
C#

#### What happens?
In case of the TODO Skill the Entity ShopContent exists in the LUIS class and is used by the Dialogs. But since it is not included in the .lu file after first deployment and Auto Regeneration of the LUIS class the build breaks because it is then missing.

#### What are the steps to reproduce this issue?
ShopContent Entity in Todo Skill not in .lu file -> publish -> gen luis class -> build Brakes

#### What were you expecting to happen?
After deploying the skill to run a rebuild of the project without any Errors.

**Comment by ssss141414** [comment]
Please update your code. Now we don't have Entity ShopContent in LUIS class and .lu file.

https://github.com/microsoft/botframework-solutions/blob/master/skills/src/csharp/todoskill/todoskill/Services/ToDoLuis.cs
