### ISSUE TITLE
[Botskill CLI] botskill connect fails for released version 2.0.67 of Azure CLI

### ISSUE THREAD

**Issue by h2floh** [microsoft/botframework-solutions#1863]
#### What project is affected?
VA / Skills

#### What language is this in?
C# (TS may be affected too)

#### What happens?
The Azure CLI in Version 2.0.67 delivers the bot command group 0.2.2 preview which seems to have a bug while executing the botskill connect operation. All work while/after AAD Rights assignment was skipped. 

We targeted the problem only because one developer had an old CLI Verion 2.0.64 with bot command Group 0.2.0 installed where the command ran without and problems.

#### What are the steps to reproduce this issue?
Install Azure CLI Release 2.0.67, try to connect any Skill to VA Bot.

Current Release 2.0.68 seems to deliver the same preview bot command group!

#### What were you expecting to happen?
botskill connect to be run successful with latest release version of Azure CLI

**Comment by Batta32** [comment]
Hi @h2floh,

Thanks to identify that **breaking change** introduced in the [2.0.67](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/release-notes-azure-cli.md#june-18-2019) version of `azure-cli`.

We were researching about, finding the meaning of the **PREVIEW** status [here](https://github.com/Azure/azure-cli/blob/dev/doc/authoring_command_modules/authoring_commands.md#preview-commands-and-arguments), taking into account that was included in the [bot command group](https://github.com/Azure/azure-cli/blame/dev/src/azure-cli/azure/cli/command_modules/botservice/commands.py#L81) as you mentioned.

Also, we will update the [Prerequisites section](https://github.com/microsoft/botframework-solutions/blob/master/docs/howto/skills/botskills.md#prerequisites) of the `botskills` cli tool mentioning to use the version lower that `2.0.66` preferably, and adding a warning during the execution.

Finally, we will continue researching to find out a properly solution for this.

**Comment by h2floh** [comment]
Hi @Batta32,

I don't know why preview command groups are included in a release version. I would like to see a more modular Azure CLI where you can up and downgrade individual command groups. But that is off Topic here. 

Thanks for checking and adding the warnings!

**Comment by Batta32** [comment]
Hi @h2floh,

Thanks for identifying this issue, we created #1965 to fix this!

Once it's merged, this issue will be closed, so feel free to reopen it if you are still having the issue (remember that those changes will be published in the next [preview](https://botbuilder.myget.org/feed/aitemplates/package/npm/botskills) release)
