### ISSUE TITLE
KeyVault integration for Virtual Assistant

### ISSUE THREAD

**Issue by hansmbakker** [microsoft/botframework-solutions#1866]
#### Is your feature request related to a problem? Please describe. 
Virtual Assistant switched from .bot files to appSettings.json and cognitiveModels.json.
One of the benefits of this is that it becomes easier to store secrets in KeyVault.

Quote from the Enterprise Bot Template migration guide:
> [This also enables you to leverage standard approaches such as KeyVault](https://github.com/microsoft/botframework-solutions/blob/master/docs/howto/assistant/csharp/ettovamigration.md#bot-file-deprecation)

For appSettings.json that is easy to do, and the nesting of appSettings properties can be done by using `--` as a separator. See https://docs.microsoft.com/en-us/aspnet/core/security/key-vault-configuration?view=aspnetcore-2.2#use-managed-identities-for-azure-resources.

#### What is the solution you are looking for?
However, due to the setup in cognitiveModels.json (the LUIS and QnA models are an array of objects, instead of a dictionary) **it seems that the secrets in cognitiveModels.json cannot easily be moved to KeyVault**, I only want KeyVault to store e.g. the LUIS `authoringKey` and `subscriptionKey`, not all the `appId` and `version`. I do not want to store the whole array of models.

**I'm looking for the way how the Virtual Assistant team envisioned getting the secrets relevant to cognitiveModels from KeyVault and combining it with the rest of the settings**

**Comment by hansmbakker** [comment]
It turns out that upon reading further down, the way how to use arrays in KeyVault is explained at https://docs.microsoft.com/en-us/aspnet/core/security/key-vault-configuration?view=aspnetcore-2.2#bind-an-array-to-a-class, so I'll try that now and close the issue.

**Comment by darrenj** [comment]
Let us know how you get on, adding documentation on how to set this up is on our list so any examples you end up having would be great - feel free to also submit a PR with an outline if you like.

**Comment by hansmbakker** [comment]
I ran into unpredictable IConfiguration behavior and was wondering why the configuration is done in the Startup constructor rather than in Program.cs as explained in the asp.net core documentation? Also see #1879.
