### ISSUE TITLE
StampNotFound

### ISSUE THREAD

**Issue by BillStrait** [microsoft/botframework-solutions#1882]
#### What project is affected?
Virtual Assistant Template

#### What language is this in?
C# - but it's with the deploy.ps1 script, so it may be agnostic.

#### What happens?
Transient issue, when deploying the project I sometimes get an exception from azure "StampNotFound." This exception isn't handled in the code, and no solutions are presented. 

#### What are the steps to reproduce this issue?
Not sure - possibly caused by deleting an application registration from Azure Active Directory and creating a new one with the same name (IE: Completely redeploying the application.)

#### What were you expecting to happen?
It would be nice for the script to recognize this issue and suggest a solution. Some more specific information about what exactly failed could aid in troubleshooting, if nothing else.

#### Can you share any logs, error output, etc.?
PS C:\users\straitb\source\repos\AnotherVATest\AnotherVATest\AnotherVATest> luis --version
2.6.0
PS C:\users\straitb\source\repos\AnotherVATest\AnotherVATest\AnotherVATest> qnamaker --version
1.3.1
PS C:\users\straitb\source\repos\AnotherVATest\AnotherVATest\AnotherVATest> .\Deployment\Scripts\deploy.ps1
? Bot Name (used as default name for resource group and deployed resources): AnotherVATest
? Azure resource group region: Central US
? Password for MSA app registration (must be at least 16 characters long, contain at least 1 special character, and contain at least 1 numeric character): redacted
? LUIS Authoring Region (westus, westeurope, or australiaeast): westus
? LUIS Authoring Key (found at https://luis.ai/user/settings): redacted
\> Creating resource group ...
\> Validating Azure deployment ...
\> Deploying Azure services (this could take a while)...
Deployment failed. Correlation ID: 51f84705-b822-4159-b841-7df550cb0720. {
  "error": {
    "code": "StampNotFound",
    "message": "SKU 'standard' cannot be provisioned in 'centralus' at this time RequestId: 00f713d7-14fc-4ef1-80e7-49dfcfe5203e",
    "target": null,
    "details": null
  }
}
! Deployment failed. Please refer to the log file for more information.
! Log: C:\users\straitb\source\repos\AnotherVATest\AnotherVATest\AnotherVATest\Deployment\Scripts\..\deploy_log.txt
\+ To delete this resource group, run 'az group delete -g AnotherVATest --no-wait'
PS C:\users\straitb\source\repos\AnotherVATest\AnotherVATest\AnotherVATest>

deploy_log.txt is empty.

**Comment by BillStrait** [comment]
Actually, just confirmed it happens when using a different name for the app.

PS C:\users\straitb\source\repos\BillsVATest\BillsVATest\BillsVATest> luis --version
2.6.0
PS C:\users\straitb\source\repos\BillsVATest\BillsVATest\BillsVATest> qnamaker --version
1.3.1
PS C:\users\straitb\source\repos\BillsVATest\BillsVATest\BillsVATest> .\Deployment\Scripts\deploy.ps1
? Bot Name (used as default name for resource group and deployed resources): BillsVATest
? Azure resource group region: Central US
? Password for MSA app registration (must be at least 16 characters long, contain at least 1 special character, and contain at least 1 numeric character): 8YvSQDoh7XNdQr-.K7S0qTcuNwssiK@?
? LUIS Authoring Region (westus, westeurope, or australiaeast): westus
? LUIS Authoring Key (found at https://luis.ai/user/settings): 2074d1478ccf491083d8a8c3172915a8
\> Creating resource group ...
\> Validating Azure deployment ...
\> Deploying Azure services (this could take a while)...
Deployment failed. Correlation ID: 218d8b1e-9ae4-444d-b49a-34b2abea79df. {
  "error": {
    "code": "StampNotFound",
    "message": "SKU 'standard' cannot be provisioned in 'centralus' at this time RequestId: fab34e6c-2737-41fb-85d2-b114f207920d",
    "target": null,
    "details": null
  }
}
! Deployment failed. Please refer to the log file for more information.
! Log: C:\users\straitb\source\repos\BillsVATest\BillsVATest\BillsVATest\Deployment\Scripts\..\deploy_log.txt
\+ To delete this resource group, run 'az group delete -g BillsVATest --no-wait'
PS C:\users\straitb\source\repos\BillsVATest\BillsVATest\BillsVATest>

**Comment by BillStrait** [comment]
Just confirmed it is not tied to creating an application with the same name.

PS C:\users\straitb\source\repos\BillsVATest\BillsVATest\BillsVATest> luis --version
2.6.0
PS C:\users\straitb\source\repos\BillsVATest\BillsVATest\BillsVATest> qnamaker --version
1.3.1
PS C:\users\straitb\source\repos\BillsVATest\BillsVATest\BillsVATest> .\Deployment\Scripts\deploy.ps1
? Bot Name (used as default name for resource group and deployed resources): BillsVATest
? Azure resource group region: Central US
? Password for MSA app registration (must be at least 16 characters long, contain at least 1 special character, and contain at least 1 numeric character): redacted
? LUIS Authoring Region (westus, westeurope, or australiaeast): westus
? LUIS Authoring Key (found at https://luis.ai/user/settings): redacted
\> Creating resource group ...
\> Validating Azure deployment ...
\> Deploying Azure services (this could take a while)...
Deployment failed. Correlation ID: 218d8b1e-9ae4-444d-b49a-34b2abea79df. {
  "error": {
    "code": "StampNotFound",
    "message": "SKU 'standard' cannot be provisioned in 'centralus' at this time RequestId: fab34e6c-2737-41fb-85d2-b114f207920d",
    "target": null,
    "details": null
  }
}
! Deployment failed. Please refer to the log file for more information.
! Log: C:\users\straitb\source\repos\BillsVATest\BillsVATest\BillsVATest\Deployment\Scripts\..\deploy_log.txt
\+ To delete this resource group, run 'az group delete -g BillsVATest --no-wait'
PS C:\users\straitb\source\repos\BillsVATest\BillsVATest\BillsVATest>

**Comment by BillStrait** [comment]
And confirmed running the command a second time _might_ fix it. Maybe the issue resolved itself. I have no way to know.

**Comment by lauren-mills** [comment]
Hi, taking a look at the error, it appears that Azure is complaining about one of your services not being available in the centralus region. If you take a look at the listed log file, it might give you more information. This is the expected behavior of the script when Azure throws an error.

**Comment by BillStrait** [comment]
The log is empty, as I mentioned above. Running the script a few more times with the same parameter eventually worked. It's not clear to me what this error is, but it does seem to be coming from azure. 

What I'm asking for is a little more clarity from the deploy script to give me some hint of what it's trying to do when the error is thrown - be it in the deploy_log or in the console.

**Comment by lauren-mills** [comment]
It appears to me to be a transient failure with Azure Search. We show all the information we get back from the Azure CLI in terms of errors, so I don't know of anything else we could do in the script to give you more information than you're seeing here. Also, we don't get any feedback from the Azure CLI on which service its trying to deploy when it fails.

**Comment by BillStrait** [comment]
Alright, I'll withdraw this. Thanks!
