### ISSUE TITLE
"Summary Skill" is needed to show basic infromations directly without ask for each Productivity skills one by one

### ISSUE THREAD

**Issue by xhr0804** [microsoft/botframework-solutions#1891]
When the user want's to know what he should pay attentions today such as to-do item, meetings, or emails, he need to ask each of the Productivity skills to see it. He may want to 
 create an adaptive card that shows the user's meetings, todos and also some other custom things the user can do without ask each of them.

Implement a simple event driven experience for each of the productivity skills. When VA trigger the event, each Skill will pass an Acitivity with summary information about meetings/todos/emaill. VA then show an Adaptive Card with all informations.

**Comment by lauren-mills** [comment]
This feature will be solved by this work: #1892
