### ISSUE TITLE
[Skills] Enable action invocation for Skills

### ISSUE THREAD

**Issue by darrenj** [microsoft/botframework-solutions#1892]
# Overview

Our Skill capability is focused on utterance driven invocation whereby a caller (Bot) takes an utterance and through an NLU dispatcher (trained with triggering utterances for each skill) identifies a matching skill and forwards said utterance to the remote skill to process. The skill is then responsible for performing it's own NLU work, entity extraction and invoking a given action/method.

An addition invocation pattern is required whereby the caller wants to explicitly invoke an action in a remote skill and optionally provide slots (parameters) to be passed to bootstrap a conversation either with everything needed to perform an operation (book a meeting) or at least partially slot-fill.

## Action invocation for Skills

The [Semantic Action Type](https://github.com/microsoft/botframework-obi/blob/master/protocols/botframework-activity/botframework-activity.md#semantic-action-type) defines a data structure that enables you to express the ID (action name), entities (slots) along with state (start/continue/end).

Proposed approach would be to extend SkillDialog to accept a SemanticAction object as part of the DialogOptions enabling a specific Skill and Action to be invoked along with supporting parameters like follows

**Individual slot per data item**
```csharp
slots.Add("title", new Entity { 
    Properties = JObject.FromObject(new KeyValuePair<string, string>("Text", "meeting title here”))});
slots.Add("content", new Entity {
    Properties = JObject.FromObject(new KeyValuePair<string, string>("Text", "meeting content here”))});
```

**Complex types in slots**
```csharp
var meetingRequest = new MeetingRequest();
meetingRequest.Title = "meeting title here";
meetingRequest.Content = "meeting content here";
meetingRequest.Attendees = "darren@contoso.com";
meetingRequest.StartDate = "01/01/2019";
meetingRequest.StartTime = "10:00";

slots.Add("complexObject", new Entity { 
Properties = JObject.FromObject(dummyObject)});
```

**Invoke the `bookMeeting` action passing the slots**
```csharp
SemanticAction skillInvocation = new SemanticAction("bookMeeting", entities);
var result = await dc.BeginDialogAsync("bookMeeting", slots);
``` 

## Start, Continue and End

We use EndofConversation activity type internally within the Skill implementation to indicate when a Skill has completed processing. For this type of Skill invocation it's important to set state to `done` as per the semantic action spec so the caller in this type of invocation flow knows when a skill has completed.

In addition `begin` and `continue` are also defined which the SkillDialog should populate.

We should retire the EndOfConverstation technique (only used internally within the Skill lib) in favor of this approach and align the approach regardless of invocation. Alternatively Skills could still indicate this but the SkillAdapter could apply this semanticaction data on responses automatically?

## Mapping Actions to Intent Handlers within a Skill

An action is logically identical to how we process intents it’s just that we don’t have to use LUIS to identify the intent as the action provides this explicitly. A skill action could be triggerable via an utterance (LUIS) or an action being provided, alternatively a developer could feasibly only expose an action through direct action invocation and not provide an NLU triggering mechanism.

Ideal direction would be for action names to be fully qualified URIs - e.g. http://bfpoiskill.azurewebsites.net/api/skill/{actionName} and we then configure Route handlers which will invoke the appropriate dialog automatically thus avoiding more switch statements like we do with Intents today.

A Skill developer could then decorate dialog classes with a [Action(Name=“ActionName”)] attribute along with ActionParameter attributes and then auto-gen most if not all of the manifest reducing manual (error prone manifest editing)

RouterDialog will need changes to support activities with blank activity.text and just SemanticAction present triggering something like a `OnSemanticAction` handler which will then bypass Interrupt/LUIS activities.

## Action responses

The manifest schema is being updated to support action response definition enabling us to define data responses that can be returned from an action on an Activity (in addition to the usual Activity payload).

This would use the same SemanticAction property as defined above.

For example this response definition in the manifest

```json
"response":
{
    "name": "issueId",
    "types": [ "string" ]
}
````

Would result in the following being returned on the SemanticAction whether it was triggered by utterance or action.

```csharp
Dictionary<string,Entity> entities = new Dictionary<string, Entity>();
Entity bugId = new Entity("string");
bugId.Properties.Add("value","1234");
entities.Add("bugId", bugId);

SemanticAction action = new SemanticAction("https://bugfilingbot.example.org/bugs/file", entities);
action.State = "done";
````

```json
{
   "id":"https://bugfilingbot.example.org/bugs/file",
   "entities":{
      "issueId”:{
         "type":"string",
         "value":"1234"
      }
   },
   "state":"done"
}
```

**Comment by guru98** [comment]
This is a great improvement: first you suggested that skills can be invoked by events but there are not example about that. Second this allow to offer a single pattern for different type of interactions: chat(typing) vs card that allow different type of navigation depending from client and context (e.g. driving in a car). Also this approach could allow to resolve the utterance at virtual assistant level and forward the result to a skill without further request to luis at skill level. Question i note that you already have an implementation of semanticaction in the code. Is this approach already usable in same way?

**Comment by darrenj** [comment]
@guru98 Working on it, will update the work item with a preview drop once it’s ready.
