### ISSUE TITLE
Implement improved UI interface

### ISSUE THREAD

**Issue by Dewain27** [microsoft/botframework-solutions#1913]
Implement new UI interface provided by UX Design Team

- [x] Replace app icon
- [x] Add left/right margins on the conversation canvas in landscape mode
- [x] Replace colorAccent #2f2f2f
- [x] Replace colorAccentNight #e6e6e6
- [x] Replace color_action_outline #0078d4

**Comment by Dewain27** [comment]
Blocked needing the UI design review from UX Design Team

**Comment by Dewain27** [comment]
Working with UI development team to get assets and new experience for Widget-based control

**Comment by ryanisgrig** [comment]
UI Fabric for Android: https://developer.microsoft.com/en-us/fabric#/get-started/android
