### ISSUE TITLE
Virtual Assistant template does not generate necessary files

### ISSUE THREAD

**Issue by threeyay** [microsoft/botframework-solutions#1923]
#### What project is affected?
Virtual Assistant template
#### What language is this in?
C#
#### What happens?
When creating a project using the virtual assistant template, 
When creating the project with the template, it does not create the Deployment\Resources\LU\en\general.luis,
Deployment\Resources\QnA\en\chitchat.qna, and
Deployment\Resources\QnA\en\faq.qna,
files.
The deploy_cognitive_models_log.txt file says these files are not found but they were not created in the first place.

I also get a "cannot find module" error. Appears to not break at space in the path variable. 

#### What are the steps to reproduce this issue?
following
https://github.com/microsoft/botframework-solutions/blob/master/docs/tutorials/csharp/virtualassistant.md
instructions.
#### What were you expecting to happen?
Create and deploy a bot using Virtual assistant template
#### Can you share any logs, error output, etc.?
I pasted the files from another project created in my organization. 
#### Any screenshots or additional context?
![image](https://user-images.githubusercontent.com/2426456/61678656-d424ac80-ad46-11e9-8559-1f88aa8db133.png)

**Comment by jwiley84** [comment]
Those files are created as part of the deployment process:

```
$id = $lu_file.BaseName
    $outFile = "$($id).qna"
    $outFolder = $lu_file.DirectoryName

    # Parse LU file
    Write-Host "> Parsing $($id) LU file ..."
    ludown parse toqna `
        --in $lu_file `
        --out_folder $outFolder `
        --out $outFile
```

How are you deploying the bot?

**Comment by CoHealer** [comment]
Hi @threeyay, can you please acknowledge?

**Comment by nathanlindorff** [comment]
I've just run into the same or similar issue running the Virtual Assistant on macos.

There are a couple of issues with the deploy scripts related to paths. 

In deploy_cognitive_models.ps1, when it tries to parse the .lu file it is failing for both luis and qna maker. 

The generated code is:
```
ludown parse toluis `
        --in $lu_file `
        --luis_culture $language `
        --out_folder $outFolder `
        --out $outFile       
```

Adding some debug output: 
```
    Write-Host "> lu_file $($lu_file)"
    Write-Host "> language $($language)"
    Write-Host "> outFolder $($outFolder)"
    Write-Host "> outFile $($outFile)"
```
Outputs:
```
> lu_file general.lu
> language en-us
> outFolder /Users/<username>/Documents/<Path to project>/deployment/Resources/LU/en
> outFile general.luis
```

If i change the generated code to 

```
$inFile = "$($lu_file.DirectoryName)/$($lu_file.BaseName).lu"
ludown parse toluis `
        --in $inFile `
        --luis_culture $language `
        --out_folder $outFolder `
        --out $outFile    
```

The code then succeeds in parsing.

I need to do likewise for the QnA but i suspect a similar fix will fix it. (not suggesting my hack is good or robust powershell btw!)

**Comment by jwiley84** [comment]
I will bring it up with the script author tomorrow that it doesn't work as expected on MacOS. Thank you for letting us know.

**Comment by nathanlindorff** [comment]
I just realised ludown has a `--lu_folder` option that would be far better than my poor string join

**Comment by jwiley84** [comment]
Hi @threeyay, @nathanlindorff It looks like the .ps1 files have been updated. Can you go ahead and test them for me again? I ran them today, using the most up-to-date version of everything, and have had no issues.

**Comment by nathanlindorff** [comment]
@jwiley84 What is the best way to update the template? As far as i can see npm hasn't been updated yet.

**Comment by jwiley84** [comment]
Since what's we're mostly concerned with is the powershell deployment files, I would simply replace those from this repo, and then rerun your deployment.

**Comment by CoHealer** [comment]
@nathanlindorff , do you still require assistance?

**Comment by nathanlindorff** [comment]
My apologies, i haven't had a chance to properly test it just yet. I will let you know later today

**Comment by nathanlindorff** [comment]
I have tested it with the preview 65 as per #2007  and it no longer has issues reading the .lu files.

**Comment by jwiley84** [comment]
I see that you were working with Martin and Darren on the above mentioned thread. Are we good to go to close this?

**Comment by nathanlindorff** [comment]
I can't speak for the OP (@threeyay) but I have no objections as my issues have been solved. Thanks!

**Comment by darrenj** [comment]
For future reference here are the steps to update deployment scripts (which did address space/path issues previously) https://microsoft.github.io/botframework-solutions/reference/virtual-assistant/deploymentscripts/#how-do-i-update-my-local-deployment-scripts-with-the-latest
