### ISSUE TITLE
OnInterruptDialogAsync should be redesigned?

### ISSUE THREAD

**Issue by xieofxie** [microsoft/botframework-solutions#1924]
#### Is your feature request related to a problem? Please describe. 

If any input is identified as General, it could not be used as input. For example, 'help me' is not a valid email title.

#### What is the solution you are looking for?

Prompt before any interrupt intent and forward directly if cancelled by user.

#### What alternatives have you considered?

If it is worth doing, it could be split into several issues:

* forward interrupt message if cancelled by user
* redesign the interrupt handling flow for VA with skills: could we trigger help in skill without triggering help in VA?
* show help related to current dialog: if in find poi dialog, provide help about this instead of a general one for poi skill

**Comment by ryanisgrig** [comment]
@darrenj for comment

**Comment by darrenj** [comment]
A Virtual Assistant implementation can choose to remove the Help interruption and leave just cancel if required especially if it causes issues. Top level intent interruption is key but there are open input scenarios such as meeting titles that have potential to cause false positives with interruptions. 

A change was expected in the .NET SDK to enable a dialog to be consulted before being interrupted. This would enable the Skill in this case to say No, I’m accepting general input and don’t want to have say Help interrupt. I’ve followed up with the SDK team for an update on consultation.
