### ISSUE TITLE
Telefonica customer story link broken

### ISSUE THREAD

**Issue by aamalhot** [microsoft/botframework-solutions#1925]
[Telefonica customer story](https://customers.microsoft.com/en-us/story/telefonica-media-telco-cognitive-services-azure) link on Bot Framework [website](https://dev.botframework.com/) is broken.

![image](https://user-images.githubusercontent.com/53205984/61682696-4dfd6b80-ad30-11e9-9d50-5097448f45ec.png)

![image](https://user-images.githubusercontent.com/53205984/61682716-64a3c280-ad30-11e9-949c-521231e6ddbe.png)

**Comment by lauren-mills** [comment]
Hi @aamalhot, this is not the right place to raise this issue. Please raise it here on the bot-docs repo: https://github.com/MicrosoftDocs/bot-docs
