### ISSUE TITLE
Create Sample VA implementation that supports custom events.

### ISSUE THREAD

**Issue by Dewain27** [microsoft/botframework-solutions#1931]
Create sample VA demo environment that supports Automotive Skill and sends events for setting the following items:

- Defroster On
- Defroster Off
- Passenger Seat Heat On
- Passenger Seat Heat Off
- Driver Seat Heat On
- Driver Seat Heat Off
- Driver Temperature (Set / Turn Up / Turn Down)
- Passenger Temperature (Set / Turn Up / Turn Down)

Turn Up and Down should increment the setting plus 5 or minus 5

Additional Utterances should include:
- I am hot (Turn Down Driver Temperature)
- I am cold (Turn Up Driver Temperature)
- Set Temperature (Set both to {integer})

Sample environment should include all available skills.

**Comment by ryanisgrig** [comment]
Is this item just for the Android VA environment connected to all skills with the Auto skill supporting these events?

Or for a custom VA implementation with those events?

**Comment by ryanlengel** [comment]
@Dewain27 need clarification on above, thanks!
