### ISSUE TITLE
Unable to find 'AuthenticationResponses' in '...\bot\node_modules\botbuilder-solutions\lib\resources'

### ISSUE THREAD

**Issue by andhdo** [microsoft/botframework-solutions#1932]
Try to enable authentication for skill using botframework VA (virtual assistant) template for typescript; 
then, it tries to get some resources inside this node library, but failed and throws the following error: 
`
 throw THIS_IS_APPLICATION_INSIGHTS_RETHROWING_YOUR_EXCEPTION; // Error originated somewhere else in your app
                        ^

Error: Unable to find 'AuthenticationResponses' in '...\bot\node_modules\botbuilder-solutions\lib\resources
`
error starts in index.ts inside this lines:
`
    const skillDialogs: SkillDialog[] = skills.map((skill: ISkillManifest): SkillDialog => {
        const authDialog: MultiProviderAuthDialog|undefined = buildAuthDialog(skill, botSettings);
`
then it tries to use botframework-solutions library to load some resources with a class called `ResponseManager`, and failing in its constructor, at line: 
`
30                  this.loadResponses(resourceName, resource);
`

below the full stack trace: 

`
...\bot\node_modules\applicationinsights\out\AutoCollection\Exceptions.js:34
                        throw THIS_IS_APPLICATION_INSIGHTS_RETHROWING_YOUR_EXCEPTION; // Error originated somewhere else in your app
                        ^

Error: Unable to find 'AuthenticationResponses' in '...\bot\node_modules\botbuilder-solutions\lib\resources'
    at ResponseManager.loadResponses (...\bot\node_modules\botbuilder-solutions\lib\responses\responseManager.js:187:23)
    at ...\bot\node_modules\botbuilder-solutions\lib\responses\responseManager.js:22:18
    at Array.forEach (<anonymous>)
    at new ResponseManager (...\bot\node_modules\botbuilder-solutions\lib\responses\responseManager.js:19:27)
    at new MultiProviderAuthDialog (...\bot\node_modules\botbuilder-solutions\lib\authentication\multiProviderAuthDialog.js:20:32)
    at buildAuthDialog (...\bot\lib\index.js:140:24)
    at ...\bot\lib\index.js:89:28
    at Array.map (<anonymous>)
    at Object.<anonymous> (...\bot\lib\index.js:88:33)
    at Module._compile (internal/modules/cjs/loader.js:756:14)

`
dependencies are listed below: 
`
    "dependencies": {
        "@microsoft/microsoft-graph-client": "^1.3.0",
        "@microsoft/microsoft-graph-types": "^1.5.0",
        "azure-cognitiveservices-contentmoderator": "^4.0.0",
        "botbuilder": "^4.4.0",
        "botbuilder-ai": "^4.4.0",
        "botbuilder-applicationinsights": "^4.4.0",
        "botbuilder-azure": "^4.4.0",
        "botbuilder-core": "^4.4.0",
        "botbuilder-dialogs": "^4.4.0",
        "botbuilder-skills": "^4.4.6",
        "botbuilder-solutions": "^4.4.6",
        "botframework-config": "^4.4.0",
        "botframework-connector": "^4.4.0",
        "botframework-schema": "^4.4.0",
        "dotenv": "^6.0.0",
        "i18next": "^15.0.6",
        "i18next-node-fs-backend": "^2.1.1",
        "ms-rest-azure": "^2.5.0",
        "path": "^0.12.7",
        "restify": "^7.2.1"
    },
    "devDependencies": {
        "@types/documentdb": "1.10.5",
        "@types/dotenv": "^6.0.0",
        "@types/i18next-node-fs-backend": "^0.0.30",
        "@types/node": "^10.10.1",
        "@types/restify": "^7.2.4",
        "@typescript-eslint/eslint-plugin": "^1.10.2",
        "@typescript-eslint/eslint-plugin-tslint": "^1.10.2",
        "@typescript-eslint/parser": "^1.10.2",
        "copyfiles": "^2.1.0",
        "eslint": "^5.16.0",
        "mocha": "^6.1.4",
        "mocha-junit-reporter": "^1.22.0",
        "nock": "^10.0.6",
        "nodemon": "^1.18.4",
        "nyc": "^14.1.1",
        "replace": "^1.0.0",
        "rimraf": "^2.6.2",
        "tslint": "^5.12.1",
        "tslint-microsoft-contrib": "^6.0.0",
        "typescript": "^3.2.2"
    },
`

it looks like is trying to find a resource in the wrong directory, because the resources are present in 
`node_modules\bot-builder-solutions\lib\authentication\resources\AuthenticationResponses.json`; however it tries to locate thos resource in `node_modules\bot-builder-solutions\lib\resources\AuthenticationResponses.json`

**Comment by Batta32** [comment]
Hi @andhdo, 

Thanks for identifying this issue, we created #1939 to fix this!

Once it's merged the Pull Request, this issue will be closed, so feel free to reopen it if you are still having the issue (remember that those changes will be published in the next release, which should be **4.4.7**).
