### ISSUE TITLE
Document how a developer can change the default chitchat personality

### ISSUE THREAD

**Issue by Dewain27** [microsoft/botframework-solutions#1936]
As a developer, I should be able to select the personality that I want deployed as part of my deployment.

**Comment by lauren-mills** [comment]
Since the personalities come from QnA Maker, I think this should be an additional documentation item in the Customize your Virtual Assistant tutorial.

**Comment by lauren-mills** [comment]
Added in the customize VA tutorial here: https://microsoft.github.io/botframework-solutions/virtual-assistant/tutorials/customize-assistant/csharp/4-edit-your-cognitive-models/
