### ISSUE TITLE
Power BI report - date range issue

### ISSUE THREAD

**Issue by lee-borlace** [microsoft/botframework-solutions#1944]
#### What project is affected?
Analytics / Power BI report

#### What language is this in?
N/A

#### What happens?
When refreshing the report one day a lot of the previous data suddenly dropped off.

Looks like it's due to this line in the EventTelemetry data source definition : `#"timespan"="P7D"`. It restricts the report to only show 7 days data regardless of other factors. I'm guessing something behind the scenes in App Insights has been fixed and that it was just ignoring this parameter previously, but has now started honouring it. Can this param be removed?

#### What are the steps to reproduce this issue?
Refresh a Power BI report which is already loaded with historical telemetry. All but the last 7 days' data drops off.

#### What were you expecting to happen?
Keep showing previous data

**Comment by CoHealer** [comment]
@dmvtech, please assist.

**Comment by dmvtech** [comment]
I'm looking into this.

**Comment by dmvtech** [comment]
@leeroy79 Can you explain more about where you are seeing `#"timespan"="P7D"`? I don't see that listed in the EventTelemetry fields.

![Annotation 2019-07-30 132504](https://user-images.githubusercontent.com/43397658/62165153-a9040500-b2d2-11e9-8dd1-ec29c65a59f2.png)

**Comment by lee-borlace** [comment]
It's when you go to the EventTelemetry data source's Advanced Editor mode, on the line that starts with this : 

```",#"x-ms-app"="AAPBI"```

**Comment by dmvtech** [comment]
Discussion with @ryanlengel. He will take over as he has more insight and will be able to work on resolution.

**Comment by ryanisgrig** [comment]
Thanks @leeroy79, I'm removing that line from the template.
