### ISSUE TITLE
Bot Solutions nuget package - CompleteAsync is never called when single turn dialogs end

### ISSUE THREAD

**Issue by hansmbakker** [microsoft/botframework-solutions#1946]
This is a bug in Virtual Assistant that was fixed in Enterprise Bot template before. [The fix](https://github.com/microsoft/botframework-solutions/pull/644) is not applied in [RouterDialog in the nuget package](https://github.com/microsoft/botframework-solutions/blob/master/lib/csharp/microsoft.bot.builder.solutions/microsoft.bot.builder.solutions/Dialogs/RouterDialog.cs) and therefore the bug exists in Virtual Assistant.

I'm opening this new issue to keep track of it. The original bug is #643 .

**Comment by Dewain27** [comment]
@lauren-mills can you take a look at this one?

**Comment by lauren-mills** [comment]
Hi @hansmbakker, we've added this bug to our backlog and will let you know once we get started on it.

**Comment by hansmbakker** [comment]
👍
