### ISSUE TITLE
ToDo & Email .luis files break dispatch refresh due to missing entities

### ISSUE THREAD

**Issue by ryanisgrig** [microsoft/botframework-solutions#1949]
#### What project is affected?
ToDo and Email Skills

#### What language is this in?
C#

#### What happens?
A VA can add all of the remote skills, but when it needs to run the dispatch refresh command (referencing .luis files) is fails.

#### What are the steps to reproduce this issue?
* Add remote skills with `botskills connect`
* Run `dispatch refresh`, which will error.

#### What were you expecting to happen?
Dispatch model should have refresh successfully

#### Can you share any logs, error output, etc.?
```
Exporting services for dispatch...
Exporting {BotName}en_General LUIS application...
Exported LUIS app JSON is at D:\a\1\s\templates\Virtual-Assistant-Template\csharp\Sample\VirtualAssistantSample\Deployment\Resources\Dispatch\en\data\_L_{BotName}en_General.json
Exporting ChitChat QnA kb...
Exported QnA app JSON is at D:\a\1\s\templates\Virtual-Assistant-Template\csharp\Sample\VirtualAssistantSample\Deployment\Resources\Dispatch\en\data\_Q_q_ChitChat.json
Expanding kb with word alterations
Exporting Faq QnA kb...
Exported QnA app JSON is at D:\a\1\s\templates\Virtual-Assistant-Template\csharp\Sample\VirtualAssistantSample\Deployment\Resources\Dispatch\en\data\_Q_q_Faq.json
Expanding kb with word alterations
Creating dispatch LUIS model json...
Creating training data...
Updating {BotName}en_Dispatch model...
Training {BotName}en_General...
Importing {BotName}en_Dispatch model...

ERROR
Failed importing latest version of {BotName}en_Dispatch app
```

#### Any screenshots or additional context?

**Email** is missing the entity "Message.Any"
**ToDo** is missing the entity "TaskContent.Any"

**Comment by Batta32** [comment]
Hi @ryanlengel,

We noticed that this issue is similar to #1884, since the `botskills refresh` command internally executes `dispatch refresh`, and the **output error** is the same.

We have some quick questions for narrowing the possible causes:
- Can you check that you are using the latest version of `botdispatch` (execute `dispatch -v` in your terminal)? If it's not the [latest](https://www.npmjs.com/package/botdispatch), we recommend you to download it:
>npm uninstall --global botdispatch
npm install --global botdispatch

- Can you share the dispatch execution command that you are trying to run? Which arguments are you passing?
- Can you share with us the `.dispatch` file you are using?

**Comment by ryanisgrig** [comment]
@Batta32 - I think this is the same issue as #1884, I've narrowed it down that the refresh commands are successful without these two skills added.

Dispatch version is `1.5.1` and this error occurs on my local machine as well as with an Azure DevOps build agent. 

Cmd: `dispatch refresh --dispatch .\Deployment\Resources\Dispatch\en\bfva_deven_Dispatch.dispatch --dataFolder .\Deployment\Resources\Dispatch\en\data`     

I've attached a sample dispatch (identifying information removed) that should be relative to the VirtualAssistantSample project. 
[Dispatch.txt](https://github.com/microsoft/botframework-solutions/files/3432563/Dispatch.txt)

**Comment by ryanisgrig** [comment]
@Batta32 I am removing you and reassigning to the Skills team, @tsuwandy has assisted with investigating and found both `.luis` files are missing entities. I have updated the first comment with clarification.

**Comment by DingmaomaoBJTU** [comment]
Seems all patten.any entities stop working with ludown parse (1.3.2). I log a issue: https://github.com/microsoft/botbuilder-tools/issues/1225 to track.

**Comment by DingmaomaoBJTU** [comment]
To unblock current work, please use npm install -g ludown@1.3.1 to downgrade.
