### ISSUE TITLE
botskills connect fails when ludown tool has an update

### ISSUE THREAD

**Issue by lauren-mills** [microsoft/botframework-solutions#1963]
#### What project is affected?
botskills

#### What language is this in?
typescript

#### What happens?
When the ludown tool has an update available, the botskills tool errors out

#### What are the steps to reproduce this issue?
Install ludown version 1.3.1, then run the botskills connect command

#### What were you expecting to happen?
botskills connect should run even if the user has an outdated version of ludown. In this case, the latest version of ludown has a regression that prevents certain skills from being added correctly, so we need to be able to use 1.3.1

#### Any screenshots or additional context?
![image](https://user-images.githubusercontent.com/27976702/61975883-2e1faf00-af9f-11e9-8967-d7b2d293a130.png)

**Comment by Batta32** [comment]
Hi @lauren-mills,

We have been researching about the behavior of the external messages (like `ludown` execution) and we noticed that the comparison between the user version and the latest version available in npm is handled by [`process.stderr`](https://github.com/microsoft/botbuilder-tools/blob/master/packages/Ludown/lib/ludown.js#L15), thus the tool catches it as an error.

We created microsoft/botbuilder-tools#1226 to track this issue.

As a workaround, you can upgrade the latest version of `ludown` like following
>npm uninstall -g ludown
npm install -g ludown@latest

**Comment by ryanisgrig** [comment]
@Batta32 we are currently blocked on a full deployment of our demo environments because of the issue found in #1949. Is there any workaround for us to use a lower version of both `botskills` and `ludown` where it would still run without breaking from that error?

**Comment by dfavretto** [comment]
@ryanlengel we created #2021 to allow the use of a previous version of `LUDown`, and now the `Update available` message won't break the `Botskills` process.
Let me know if there's anything else I can help you with!

**Comment by Batta32** [comment]
Hi there!
We solved this issue in #2021 merged in `next`, and @darrenj moved to `master` in #2038
