### ISSUE TITLE
botskills refresh does not update skill manifest

### ISSUE THREAD

**Issue by lauren-mills** [microsoft/botframework-solutions#1964]
#### What project is affected?
botskills

#### What language is this in?
typescript

#### What happens?
When running botskills refresh against a skill that has an updated manifest, the skills.json config is not updated

#### What are the steps to reproduce this issue?
Update skill manifest with new action, then run botskills refresh

#### What were you expecting to happen?
I expected the updated manifest to be stored in skills.json

**Comment by Batta32** [comment]
Hi @lauren-mills,

If you have updated the `skillManifest` of your related `Skill` and you want to reflect those changes in your `skills.json`, you should use the [update command](https://github.com/southworkscom/botframework-solutions/blob/master/docs/howto/skills/botskills.md#update-a-connected-skill) for that, is the one that will re-connect the selected skill.

Example of the update command:
> botskills update --botName <YOUR_BOT_NAME> --remoteManifest "http://<YOUR_SKILL_MANIFEST>.azurewebsites.net/api/skill/manifest" --luisFolder <YOUR_LUIS_FOLDER_PATH> --cs

For further documentation of the update command, please check [this](https://github.com/southworkscom/botframework-solutions/blob/master/tools/botskills/docs/update.md).
