### ISSUE TITLE
Custom dispatch intents removed by botskills connect

### ISSUE THREAD

**Issue by BillStrait** [microsoft/botframework-solutions#1969]
#### What project is affected?
Virtual Assistant Template/botskills connect

#### What language is this in?
C#
#### What happens?
If you manually add an intent to DispatchLuis.cs and later add a skill through botskills, the manually added intent will be removed from DispatchLuis.cs and from your luis model. 

#### What are the steps to reproduce this issue?
Create a new VA template. Add an intent to the dispatch model. Then add a skill (calendar, in this case.)

#### What were you expecting to happen?
I was expecting my existing intents to survive, maybe an alert if there's an obvious conflict. 

#### Can you share any logs, error output, etc.?
n/a

It's possible I'm violating the intended design pattern, but creating a new skill for trivial intents seems like overkill.

**Comment by lauren-mills** [comment]
Hi @BillStrait, the dispatchLuis.cs class is driven by the .dispatch file and dispatch tool, so manually adding intents directly in without updating those files could result in this behavior. If you are trying to add new intents for your assistant, I would recommend updating the General LUIS model instead, then running the `update_cognitive_models.ps1 -RemoteToLocal` script to preserve any changes made in the luis.ai portal locally in source control. That way, your custom intents will not be overwritten by either the dispatch tool or botskills tool. Hope that helps!

**Comment by BillStrait** [comment]
Thanks Lauren, I realized I was probably using the wrong LUIS and am verifying it works for me as we speak. My mistake. Thanks!
