### ISSUE TITLE
handle potential race condition

### ISSUE THREAD

**Issue by xieofxie** [microsoft/botframework-solutions#1977]
#### Is your feature request related to a problem? Please describe. 

Since the dialog state is loaded in the beginning and saved in the end, it might happen (very rarely) that while TokenEvents.TokenResponseEventName is being processed, user cancels the dialog and this operation goes faster. Then when the event ends, state will be restored by its saving. 

#### What is the solution you are looking for?

Queue requests for same channel id + conversation id. For channel id + user id, it is developer's
not sdk's responsibility to handle race conditions.

**Comment by Dewain27** [comment]
@lzc850612  can you look into this one?

**Comment by lzc850612** [comment]
@xieofxie, i believe this is already the case. if you look at the ConversationState code in SDK, it's using channel id + conversation id to construct the storage key.

**Comment by xieofxie** [comment]
@lzc850612 It happens when messages from same channel id + conversation id are processed asynchronously. For example: message 1 received (load status 1) -> message 2 received (load status 1) -> message 2 is processed -> message 2 ended (save status 1.2) -> message 1 is processed -> message 1 ended (save status 1.1 which overwrites 1.2). It might be more confusing if the overwriting is by something not sent by user like TokenEvents.TokenResponseEventName.

**Comment by lghinet** [comment]
this problem can also be found on 

```
 await @adapter.ContinueConversationAsync(_appId, convRef, async (context, token) =>
                {
                   ....
                   await _bot.OnTurnAsync(context, token);
                }, cancellationToken);
```

when you are trying to resume conversation, on another thread, when you receive an external event,

**Comment by darrenj** [comment]
I believe this has now been addressed with persisting state right when you change it rather than through autosave middleware
