### ISSUE TITLE
skill could use remote configuration

### ISSUE THREAD

**Issue by xieofxie** [microsoft/botframework-solutions#1978]
## User Story
As ... a developer
I want ... to use my own storage/keys in skills
so that ... it is better controlled

## Acceptance Criteria 
*List your requirements.*
- [ ] ... expose configurable settings (like cosmos db, app insight, api keys etc.) in skill manifest
- [ ] ... send these settings when calling a skill from VA
- [ ] ... skill uses these settings instead of ones in appsettings.json

## Resources
*Provide any screenshots or conversation mockups to support your request.*
*Learn how to mock up bot conversations with [.chat files](http://aka.ms/bfchatfile).*

No conversation mockup needed.

## Notes
*Provide any additional information.*

#### Is your feature request related to a problem? Please describe. 

Just like oauth, storage(cosmosDB etc.)/functional(azureMapsKey etc.) keys should also be able to retrieve from VA. If not, when multiple VAs use same skill, same user/conversation id may be actually different ones in different VAs.

#### What is the solution you are looking for?

<del>Something like IRemoteUserTokenProvider.</del>

**Comment by Dewain27** [comment]
@xieofxie  we have added to the backlog, but not on our immediate road map.   Let us know the customer scenarios that are impacted currently.

**Comment by lauren-mills** [comment]
@xieofxie please fill out the User Story, and requirements list for this to be considered for the backlog. Thanks

**Comment by xieofxie** [comment]
@lauren-mills ok~

**Comment by darrenj** [comment]
A Skill Manifest purely describes what is required for a client to invoke a Skill so shouldn't provide sensitive information like this. For the skill scenarios we have today I don't see an issue and user when deploying VA/Skills can override deployment resources and ensure shared ones are used?
