### ISSUE TITLE
bot secret error 

### ISSUE THREAD

**Issue by NicuAhmadi** [microsoft/botframework-solutions#198]
**Description*
Everything was working fine on my bot deployment and associated services. After a computer restart; I attempted to rebuilt and re run my solution. This time I got the following error:
$exception	{System.Exception: You are attempting to perform an operation which needs access to the secret and --secret is incorrect.
   at Microsoft.Bot.Configuration.BotConfiguration.ValidateSecret(String secret) in D:\a\1\s\libraries\Microsoft.Bot.Configuration\BotConfiguration.cs:line 416
   at Microsoft.Bot.Configuration.BotConfiguration.Decrypt(String secret) in D:\a\1\s\libraries\Microsoft.Bot.Configuration\BotConfiguration.cs:line 312
   at Microsoft.Bot.Configuration.BotConfiguration.LoadAsync(String file, String secret) in D:\a\1\s\libraries\Microsoft.Bot.Configuration\BotConfiguration.cs:line 139
   at Microsoft.Bot.Configuration.BotConfiguration.Load(String file, String secret) in D:\a\1\s\libraries\Microsoft.Bot.Configuration\BotConfiguration.cs:line 155
   at VirtualAssistant.Startup.ConfigureServices(IServiceCollection services) 
I re-verified the content of appsettings.json and the secret is correct.

**Comment by lauren-mills** [comment]
Hi, @NicuAhmadi which project are you trying to build? The Enterprise Bot Template?

**Comment by lauren-mills** [comment]
Here are a few things you can do to help troubleshoot this error:
1. Do you have multiple .bot files included in your project? If so, verify the secret you are using in appsettings.json matches the .bot you are using
3. Try opening the .bot file in the emulator. It should prompt for your secret and tell you if it is incorrect
2. Try running this msbot CLI command:
` msbot secret clear --bot YOUR_BOT_FILE_PATH --secret YOUR_SECRET `
If you get an error, the secret for the .bot file might be incorrect and you can find the correct secret in your Azure Web App App Settings tab. If you successfully clear, remove the secret from appsettings.json and try again

**Comment by NicuAhmadi** [comment]
- No, I only have a single .bot file . I had isolated an env't all together to run Virtual-Assistant solution. After several hours of debugging due to issues outlined here as well https://github.com/Microsoft/botbuilder-tools/issues/596   I was able to get my system running and had left it in the running state before the restart 
- I get an error from running that command or the msbot list command 
Error: You are attempting to perform an operation which needs access to the secret and --secret is incorrect.
I used the portal to generate a new secret and still got hte same error 
- Note that per my understanding there's a difference between  "appPassword" and "secret". One refers to what you see / get on the portal while the other is what you input in the appsettings.json and generated after deployment. 


One more thing: note that I did not change anything on my end. Simply came back the next day to run few scenarios and nothing was working..

**Comment by lauren-mills** [comment]
@NicuAhmadi sorry for the confusion, I was referring to the botFileSecret that is added to the web app settings when you run msbot clone, not the Microsoft App Password. You should be able to find it here: 
![image](https://user-images.githubusercontent.com/27976702/47686782-34146b00-db9a-11e8-82bd-d1e69ddbf1a3.png)
I'm curious to see if this value is the same as the one you are using. As far as I know nothing has changed that would affect the BotConfiguration package.

**Comment by NicuAhmadi** [comment]
Thank you @lauren-mills . I verified and the value is the same

**Comment by lauren-mills** [comment]
Were you able to open the file in the emulator? * Without the project running

**Comment by NicuAhmadi** [comment]
Assuming you mean locally.. I was and still am able to open the file in the emulator.. However, I can't utilize it.. as I get "can't send" error messages.. ( since my IIS throws an exception )

**Comment by lauren-mills** [comment]
I'd like to get the emulator to reprompt to for your secret, since otherwise it will cache an already authorized .bot file. One way to trigger this is to rename your .bot file and reopen it in the emulator. Would you mind trying that? You can change the name back after the test. 

Have you published your bot? Is the published version also broken?

**Comment by NicuAhmadi** [comment]
@lauren-mills  Is the rename of the bot enough or do I need to re-generate passcodes etc? Also I'm assuming I need to rename across..  
I did verify that I'm running the latest version of bot emulator. However, in chasing the issue, I noticed that the secret in bot emulator is encrypted ( with the encryption check mark on as well ) ..  Not sure if that has anything to do with it... 
Published version is working fine...

**Comment by lauren-mills** [comment]
If you have a published version working, let's ignore the renaming step.

One thing you can do is open the Azure App Service where the bot is running, and scroll in the sidebar to the Development Tools section, and select Advanced Tools.
![image](https://user-images.githubusercontent.com/27976702/47732693-f6f4bb00-dc23-11e8-93d2-b65cb247c560.png)

Click "go", then open Debug console > CMD to browse the hosted files.

Open the site/wwwroot folder and find your .bot file, and appsettings.json files.

Try copying the contents of these files into your local version and testing again.

**Comment by lauren-mills** [comment]
@NicuAhmadi were you able to get your local version working?

**Comment by NicuAhmadi** [comment]
@lauren-mills  I have not done above yet.. I'll do so tonight and update you. I'm starting to wonder that the fastest option to resolve at this point may be for me to replicate all over...  ( I'll give that a try over the weekend if tonight debugging does not yield anything )

**Comment by NicuAhmadi** [comment]
@lauren-mills  Just tried doing above.. Files published were from 10/27 .. so a day older than my problem.. Same issue.. And furthermore ( I don't think related to this activity ) published version also stopped working..
Rather than spin cycles and not having anything working; I'm going to see if I can recreate the issue and if so what the steps are.. I'll keep you posted.. I should be able to do this day after tomorrow

**Comment by lauren-mills** [comment]
@NicuAhmadi I'm closing this for now. If you continue to have similar issues please reopen.
