### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by hansmbakker** [microsoft/botframework-solutions#1980]
While the [releases on github](https://github.com/microsoft/botframework-solutions/releases) are nice and they include a list of improvements / fixes, they are a kind of aggregation of all parts of this repo. Also they are not tied to a specific version of a component they seem more like rollup changelogs?

Now I see in Visual Studio that there is an update available for `Microsoft.Bot.Builder.Solutions`  from 4.5.1 to 4.5.3 (so probably a bugfix release) but I cannot find any specific changelog for this library, nor do I see another way to find out what changed between these versions.

I would like to have a way to see what was improved between versions, for the versioned Nuget packages.

**Comment by Dewain27** [comment]
@hansmbakker you can find the release notes here:
https://github.com/microsoft/botframework-solutions/releases

If you want details as to each, then you will need to click further in on each item.

**Comment by hansmbakker** [comment]
@Dewain27 that is exactly my point - the release notes that you link to are not sufficient as they are a periodic rollup instead of release notes per Nuget package version.

They are issue-centric rather than version-centric.
Also they are quickly outdated since they are only updated now and then: there is several months between your "0.4" and "0.5" release and these version numbers do seem not link to anything else. So they confuse me.

My feature request was to provide better release notes that solve these issues.

In my opinion this issue is not solved by posting the link to something I referred to as not sufficient. Could you please reopen this issue?
