### ISSUE TITLE
[Point of Interest] "Find the nearest X" should return results for only one of that POI

### ISSUE THREAD

**Issue by ryanisgrig** [microsoft/botframework-solutions#1986]
#### Is your feature request related to a problem? Please describe. 
When a user says something like "find the nearest coffee shop", the POI Skill returns a list of POIs rather than a single entity which would be expected based on the question.

#### What is the solution you are looking for?
The POI Skill's LUIS application would recognize descriptors like "nearest", "closest", etc., that the API should only return one result rather than the default set.

**Comment by xieofxie** [comment]
If this should be applied, should routing return only one result for fastest/shortest?
