### ISSUE TITLE
[VA] Support "Stop" intent

### ISSUE THREAD

**Issue by ryanisgrig** [microsoft/botframework-solutions#1989]
## User Story
As ... bot developer
I want ... the VA to be able to handle the "Stop" intent when I say "stop talking"
so that ... I can add custom functionality when a user wants to stop.

## Acceptance Criteria 
*List your requirements.*
- [ ] VA should implement "Stop" intent from General model. 
- [ ] There should be no default behavior, but a comment that explains how to use the intent

## Resources
*Provide any screenshots or conversation mockups to support your request.*
*Learn how to mock up bot conversations with [.chat files](http://aka.ms/bfchatfile).*

## Notes
*Provide any additional information.*

#### What happens?
After asking "where is the nearest starbucks?" there is a long readout, if you then say "Computer, shut up" It just sends the same activity back and begins reading the card again. This should be a cancel event or maybe a new event that just says to stop playing audio.

#### What are the steps to reproduce this issue?
User: "shut up"/"stop talking"/"quit it"/ etc.
VA: *match query to General intent* and return irrelevant answer

#### What were you expecting to happen?
VA should map to cancel intent or return an event activity that can be consumed by clients to stop playing audio

**Comment by darrenj** [comment]
Addressed
