### ISSUE TITLE
Cannnot change the Text and Title for Authentication Card using MultiProviderAuthDialog

### ISSUE THREAD

**Issue by premaarya** [microsoft/botframework-solutions#1990]
## User Story
As bot developer
I want to customize the fields on the OAuth Prompt in the MultiAuthProviderDialog
so that I can provide a good experience for my bot users

## Acceptance Criteria 
*List your requirements.*
- [ ] ...
- [ ] ...
- [ ] ...

## Resources
*Provide any screenshots or conversation mockups to support your request.*
*Learn how to mock up bot conversations with [.chat files](http://aka.ms/bfchatfile).*

## Notes
*Provide any additional information.*

#### Is your feature request related to a problem? Please describe
When using the Virtual Assistant Template, cannot change the Title and Text displyed in the card, the text is : "Login with {0}", connection.Nam

#### What is the solution you are looking for?

I need the disply the text  Sign-in using your `"organization account"` in the authentication prompt

#### What alternatives have you considered?
Used the prompt options, still the card shown default values.
`sc.PromptAsync(nameof(MultiProviderAuthDialog), promptOptions)`

#### Is there any other context you can provide?
upgraded to 4.5.1 version. Still same default prompts.

**Comment by lauren-mills** [comment]
Hi @premaarya we have added this feature to our backlog. We will let you know once we get started on it!

**Comment by lauren-mills** [comment]
In the 4.6.0 version of the Microsoft.Bot.Builder.Solutions package, you can provide OAuthPrompt settings to the MultiProviderAuthDialog to override the default text and title: https://github.com/microsoft/botframework-solutions/blob/ec8b46c9755125b85e3f94dd6924704ecf99d007/sdk/csharp/libraries/microsoft.bot.builder.solutions/Authentication/MultiProviderAuthDialog.cs#L31
