### ISSUE TITLE
P0: (To Do) Add outlook tasks support

### ISSUE THREAD

**Issue by darrenj** [microsoft/botframework-solutions#20]

**Comment by Dewain27** [comment]
@darrenj Just to verify this is to add Outlook Tasks support not replace OneNote Task support.  Is that Correct?

**Comment by feich-ms** [comment]
@Dewain27, I'm working on the feature of adding Outlook task support. @darrenj, I suggest we support both OneNote and Outlook tasks, but need to ask users to choose a primary one when first triggerring the skill.

**Comment by Dewain27** [comment]
I have spoken to BMW and believe that I have them convinced to move to the Graph API.  We may be able to cancel OneNote for To Do List but will need to keep capture a memo.  I will have confirmation of this next week.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________
