### ISSUE TITLE
Ask to play artist and send to Spotify

### ISSUE THREAD

**Issue by Dewain27** [microsoft/botframework-solutions#2005]
Create VA skill capable of capturing an Artist Name and passing it down Spotify music service launching the Spotify app in a deep link.

**Comment by ryanisgrig** [comment]
v1
* User says "play artist"
* Skill returns Spotify URI that opens (and installs) address with a radio station
    * *return deeplink from https://developer.spotify.com/documentation/web-api/reference/object-model/*

https://developer.spotify.com/design/link/
