### ISSUE TITLE
Only the first name is picked up when utterance containing multiple personName is given

### ISSUE THREAD

**Issue by Adityagrao** [microsoft/botframework-solutions#2010]
### Minimal steps to reproduce
- Add personName as an Entity
- Use the utterance "Create a meeting with John and Ben"
- Use the utterance "Create a meeting with Ben and John"

### Any log messages given by the failure
> 
![image](https://user-images.githubusercontent.com/11465032/62136566-fd72a900-b301-11e9-9c1f-7cf2f25ffaf1.png)

![image](https://user-images.githubusercontent.com/11465032/62136609-14b19680-b302-11e9-815f-b37edb6bf545.png)

### Expected/desired behavior
> Expected both to give personName Ben and Jhon

**Comment by darrenj** [comment]
Thanks for raising this, we'll take a look. @bobokids - Let's raise with the Carina team and also explore why the person pre-built entity wasn't used as I suspect this will resolve.

**Comment by bobokids** [comment]
We used the pre-built person name entity here. I will check with Carina team.

**Comment by bobokids** [comment]
Issue logged to LUIS team.

**Comment by bobokids** [comment]
Use LUIS bug to track this issue. Close this one.

**Comment by Adityagrao** [comment]
I still don't see this issue fixed in LUIS
