### ISSUE TITLE
re-use same MsaApp for another bot?

### ISSUE THREAD

**Issue by tamerin-tech** [microsoft/botframework-solutions#2014]
#### Is your feature request related to a problem? Please describe. 
I would like to deploy a new bot, but don't have permission to create new Microsoft App. I need to re-use existing app

#### What is the solution you are looking for?
allow re-use same app

#### What alternatives have you considered?
if it's not possible I'll have to apply for those permissions but it's a longer process... and I might need to repeat this again later couple of times...

#### Is there any other context you can provide?
if I specify an existing app I get this error:
Deployment failed. Correlation ID: <GUID>. {
  "error": {
    "code": "InvalidBotData",
    "message": "Bot is not valid. Errors: MsaAppId: MsaAppId is already in use.. "
  }
}

**Comment by lauren-mills** [comment]
You will need a separate app registration for each bot. It’s a requirement of the Azure Bot Service. You can reuse older ones, but another bot cannot be active with that id.
