### ISSUE TITLE
Problem when bot and Luis are on different regions

### ISSUE THREAD

**Issue by tamerin-tech** [microsoft/botframework-solutions#2016]
#### What project is affected?
VA

#### What language is this in?
C#

#### What happens?
Bot communication fails when trying to use Luis dispatcher (general)

#### What are the steps to reproduce this issue?
I tried to deploy a sample bot (VA template) on a resource group on westeurope, while used the Luis authoring keys for westus

#### What were you expecting to happen?
I specified the Luis key correctly for that region (westus) and specified the region (westeurope) for the resources group, so I assume it should work with those settings

#### Can you share any logs, error output, etc.?
PowerShell:
_! Could not assign subscription key automatically. Review the log for more information._
_! Log: ...\..\deploy_cognitive_models_log.txt_
_+ Please assign your subscription key manually in the LUIS portal._

from ...\..\deploy_cognitive_models_log.txt:
_The region (westeurope) is not valid._

_LUIS Command Line Interface - ┬⌐ 2018 Microsoft Corporation_

_Assigns a LUIS Azure account to the application._

_Usage:_
_luis add appazureaccount --in accountToAdd.json --appId <string>_

#### Any screenshots or additional context?
here are my deployment parameters:
_.\Deployment\Scripts\deploy.ps1 -name temptemp -location **westeurope** -appPassword <PASSWORD> - -luisAuthoringKey <LUIS-KEY-US> -luisAuthoringRegion **westus**_

**Comment by darrenj** [comment]
I think this is fixed in the latest deployment scripts. If you follow [these instructions](https://github.com/microsoft/botframework-solutions/blob/master/docs/howto/assistant/updatedeploymentscripts.md) to update your scripts and try again this should resolve the issue.

**Comment by tamerin-tech** [comment]
hi @darrenj , I just tried this today with the recent scripts...

**Comment by lauren-mills** [comment]
Hi @tamerin-tech, I believe I found the bug. Can you try updating lines 154 and 270 in deploy_cognitive_models.ps1 to use the $luisAccountRegion instead of $luisAuthoringRegion and let me know if it works as expected? You can run the deploy_cognitive_models.ps1 script directly, you don’t have to do the full Azure deployment again.

**Comment by lauren-mills** [comment]
Ok, I think I've figured out the issue. It seems like LUIS keys can only be assigned to apps in specific authoring regions. For example, LUIS keys for US regions (centralus, eastus), can only map to LUIS apps that were authored in westus, and LUIS services deployed in Europe can only map to LUIS apps that were authored in westeurope. 

So, by running the script with a westeurope resource group, and a westus authoring key, you'll hit this error.

This is what it shows in the LUIS portal when I try to assign a westeurope key to a westus app:
![image](https://user-images.githubusercontent.com/27976702/62734427-dee56f80-b9dd-11e9-8fb0-a6effc3f47d2.png)
