### ISSUE TITLE
Cancel Intent should not ask to confirm

### ISSUE THREAD

**Issue by Dewain27** [microsoft/botframework-solutions#2031]
## User Story
**As a** bot user
**I want** the bot to say "OK" instead of asking if I want to cancel
**so that** the experience is simpler and faster

## Acceptance Criteria 
*List your requirements.*
- [ ] ...
- [ ] ...
- [ ] ...

## Resources
*Provide any screenshots or conversation mockups to support your request.*
*Learn how to mock up bot conversations with [.chat files](http://aka.ms/bfchatfile).*

## Notes
*Provide any additional information.*

**Comment by darrenj** [comment]
I think this should be left to the bot owner to decide. The current implementation ensures we don't just cancel (and risk loosing state/date) if it's been triggered incorrectly. Perhaps this is better served by a documentation item about interruption behaviour and how to change

**Comment by ryanisgrig** [comment]
I think for out-of-the-box capabilities it would be better to **not** prompt the user for a confirmation and instead just cancel. I have yet to have a demo scenario where it hasn't caused more friction to trudge through the cancel dialog while simultaneously demonstrating navigating between skills.

If a bot owner wants to be safer, we can add a note in documentation that highlights a prompt dialog that can achieve this.

**Comment by darrenj** [comment]
Resolved
