### ISSUE TITLE
App ID and App Secret Error with the New VA deployment

### ISSUE THREAD

**Issue by rajmsft** [microsoft/botframework-solutions#2040]

**Comment by rajmsft** [comment]
I have followed the instruction to create a new Virtual Assistant with the Market Place Virtual Assistant Template and have managed to deploy it to Azure. I had to use appID and Password as parameter as the deployment could not register the app even though I used PowerShellas an administrator.
However after it is published and all ther esources are created and appseetings is updated, I get appID Password error when I run it in the emulator.
Please see attached screen sheet.
![botbug](https://user-images.githubusercontent.com/23537831/62476914-87d96380-b76d-11e9-8f8e-bc99122d4fcb.jpg)

**Comment by stevkan** [comment]
@rajmsft, to help me better assist you, could you please complete the seven questions in the default system post?

**Comment by rajmsft** [comment]
What project is affected? - The Virtual Assistant Template
What language is this in? C#
What happens? I am able to deploy using deploy.ps1 but always get an error for wrong appId and passowrd
What are the steps to reproduce this issue? Creat a new project with the latest Enterprise Template, run powershell 6.2 as admin,run deploy script with -aapID and -appPassword parameters (Otheriwse it fails), the bot is published; Run using Emulator, No screens and error with wormg App ID and password
What were you expecting to happen? The launch scree with menus
Can you share any logs, error output, etc.?emulator erroe has been attached

Any screenshots or additional context?

**Comment by stevkan** [comment]
Are you deploying _and_ publishing the bot? I need to verify this hasn't changed, however my last understanding is that those are two distinct steps in the current incarnation of the "deployment" process.

**Comment by rajmsft** [comment]
Steven

Some more developments:


  1.
I had to use password (16 character long and avoided certain character & and @)
  2.
 I had to make sure the project directory does not have spaces
  3.
 Now I created the project with the template and used the deployment script .\deployment\scripts\deploy.ps1
  4.
It hangs at publishing

[cid:ee57fc3a-8a1f-49b4-971e-032acdbea66f]

Raj


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by rajmsft** [comment]
I also ran the publish script separately .\deployment\script\publish.ps1

On the portal test web chat -  this is what I get
[cid:a70d8c89-ad4e-48c1-993e-d9bcd4d83a84]


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by darrenj** [comment]
Hi @rajmsft,

You have run into a few things (spaces in paths, escaping) that I'm pretty sure were fixed a little while back in the deployment scripts. If you created your project a little while back or haven't updated the template please follow [these instructions](https://microsoft.github.io/botframework-solutions/reference/virtual-assistant/deploymentscripts/#how-do-i-update-my-local-deployment-scripts-with-the-latest) to update your deployment scripts.

Also make sure you have AZ CLI updated as well - that can be the root of some publishing problems (we just use the standard publishing.

You can then run publish directly as per:

```
deployment\scripts\publish.ps1 -name BOT_NAME -resourceGroup RESOURCE_GROUP_NAME
```

Would be good to know your AZ CLI version too (az-v)

**Comment by darrenj** [comment]
One further thing (before the above if possible). If you are creating the App Id manually - please ensure the tenant setting is correct as per [this item](https://microsoft.github.io/botframework-solutions/reference/knownissues/#my-microsoft-app-registration-could-not-be-automatically-provisioned). This is required for Azure Bot Service to validate appid/secret. This is highlighted as part of deployment when it cannot create the AppId for you (and points you at https://aka.ms/vamanualappcreation)

**Comment by lauren-mills** [comment]
I'd like to add here that the "bot's Microsoft App Id or Password is incorrect" error in the emulator is a direct string match check between the "microsoftAppId" parameter in appsetting.json and what was provided in the emulator when connecting. 

One way to validate this is to create a .bot file using this link and double check that the appId matches what's in appsettings.json:
![image](https://user-images.githubusercontent.com/27976702/63371895-d116df00-c339-11e9-82b2-b559d903250c.png)

**Comment by CoHealer** [comment]
@rajakomsft, do you still require assistance? We need activity on the thread in order to keep the issue open.

**Comment by rajmsft** [comment]
I will test the template again and confirm.

Raj

**Comment by stevkan** [comment]
Closing the issue due to a lack of activity and a (potential) solution was provided.

If the problem persists, please feel free to reopen the issue.
