### ISSUE TITLE
Can't find the "update deployment scripts" how-to

### ISSUE THREAD

**Issue by tamerin-tech** [microsoft/botframework-solutions#2045]
Hi,
I noticed that the documentation was deleted, could you please explain where can I find again information how to maintain my deployment scripts up to date?

previously it was on: https://github.com/microsoft/botframework-solutions/blob/master/docs/howto/assistant/updatedeploymentscripts.md

Thanks!

**Comment by lauren-mills** [comment]
This doc was combined with the overall deployment reference here: https://github.com/microsoft/botframework-solutions/blob/master/docs/reference/assistant/deploymentscripts.md#how-do-i-update-my-local-deployment-scripts-with-the-latest
