### ISSUE TITLE
Wrong error on deployment script (publish.ps1)

### ISSUE THREAD

**Issue by tamerin-tech** [microsoft/botframework-solutions#2046]
Hi,
I'm trying to re-deploy a bot, everything went fine but I get this error:

> ..
> > Creating resource group ...
> > Validating Azure deployment ...
> > Deploying Azure services (this could take a while)...
> > Updating appsettings.json ...
> > Deploying cognitive models ...
> > Initializing dispatch model ...
> > Parsing General LU file ...
> > Deploying General LUIS app ...
> ! Could not deploy LUIS model. Review the log for more information.
> ! Log: ...MainBot\Deployment\Scripts\..\deploy_cognitive_models_log.txt
> > Setting LUIS subscription key ...
> ! Could not create LUIS app. Skipping dispatch add.
> > Parsing Chitchat LU file ...
> ...
> 

Then checking in the deploy_cognitive_models_log.txt I found this:

> 
> xxx_Dispatch.dispatch created
> 
> An application with the same name (xxx_General) already exists.
> 
> LUIS Command Line Interface - ┬⌐ 2018 Microsoft Corporation
> 
> Imports an application to LUIS, the application's structure should be included in in the request body.
> 
> Usage:
> luis import application --in jSONApp.json --appName <string>
> 

It seems that the application already exists, so I could not figure out whether the error message means there's something I need to fix (delete the Luis app before re-deployment?)
or whether everything was fine and the error message is just wrong?

Thanks

**Comment by lauren-mills** [comment]
If you're just trying to republish the app, use the publish.ps1 script instead of deploy.ps1. Deploy will try to reprovision all your azure resources and LUIS models and will run into these conflicts. If you want to update your luis models based on your local files, run the update_cognitive_models.ps1 script.

**Comment by tamerin-tech** [comment]
thanks @lauren-mills , but I noticed also a problem in the publish.ps1 script. No errors appears if I provide wrong details, all I get is:
> Publishing to Azure ...

but checking the **publish_log.txt**,  I found:

_ERROR: ResourceNotFound - The Resource 'Microsoft.Web/sites/..._

I would expect the publish script to warn me if something went wrong....
Thanks!

**Comment by lauren-mills** [comment]
Ok, I'll add this to the backlog to update the error handling in the publish script.
