### ISSUE TITLE
Summary skill based on Action integration

### ISSUE THREAD

**Issue by bobokids** [microsoft/botframework-solutions#2057]
## User Story
As ...
I want ...
so that ...

## Acceptance Criteria 
*List your requirements.*
- [ ] ...
- [ ] ...
- [ ] ...

## Resources
*Provide any screenshots or conversation mockups to support your request.*
*Learn how to mock up bot conversations with [.chat files](http://aka.ms/bfchatfile).*

## Notes
*Provide any additional information.*

#### Is your feature request related to a problem? Please describe. 
Create the summary skill based on new action support.

**Comment by lauren-mills** [comment]
@darrenj - can you please update the user story, requirements, and mockup for this
