### ISSUE TITLE
LG support in skills

### ISSUE THREAD

**Issue by bobokids** [microsoft/botframework-solutions#2058]
## User Story
As ... bot user
I want ... I want to use LG in the skills
so that ... I can easily manage my bot responses better

## Acceptance Criteria 
*List your requirements.*
- [ ] Should be implemented in the following skills (ordered by priority:
     - [ ] Weather (dependent on updating Weather Skill to use prebuilt model #2160 )
     - [ ] POI
     - [ ] Calendar
     - [ ] Email
     - [ ] To Do

## Resources
*Provide any screenshots or conversation mockups to support your request.*
*Learn how to mock up bot conversations with [.chat files](http://aka.ms/bfchatfile).*

## Notes
*Provide any additional information.*

**Comment by xieofxie** [comment]
POI in https://github.com/microsoft/botframework-solutions/pull/2026 now
