### ISSUE TITLE
Creation of the Virtual Assistant duplicate some classes

### ISSUE THREAD

**Issue by tommyJimmy87** [microsoft/botframework-solutions#2059]
When I create the Virtual Assistant or also the skills I have some .ts file duplicated with the _ as prefix in the file, i.e. _dialogBot.ts. And when I run the bot it' s going to crash because of duplicated Classes. 

Is there some reason why are being created ?

**Comment by Batta32** [comment]
Hi @tommyJimmy87,

Thanks for reporting this issue.

In which _OS_ are you executing the generator?

Those files with the `_` prefix that you mentioned, are recognized as **template files** by `yeoman`,  which replaces their name, location or any placeholder inside those files.

As a workaround, you can delete those files with the `_` prefix and build the project, meanwhile we will research about it.

**Comment by tommyJimmy87** [comment]
Hi @Batta32  ,

Thanks, yes I already deleted them. :) 

Currently I'm developing with `MacOS High Sierra` , version: `10.13.4`. 
The `yeoman` version is : `3.1.0`
And the `botbuilder-assistant` generator's version is : `v1.0.5`

**Comment by iMicknl** [comment]
I did face the same issues this week, with the latest versions retrieved from npm (public). Also on macOS.

**Comment by Batta32** [comment]
Hi @tommyJimmy87, @iMicknl!

We noticed that this issue is related to **macOS** and we are researching about it.

Meanwhile, you can use the [samples](https://github.com/microsoft/botframework-solutions/tree/master/templates/Virtual-Assistant-Template/typescript/samples) instead of using the generator, because it's a solution created using the generator 😊.

**Comment by tommyJimmy87** [comment]
@Batta32 Do you think I have to migrate to the samples ? I mean if is just the duplicates I can just delete them  if there are no other problem (after deleting the duplicates the skill or the va looks working), but if you think that could have other issue I will use the samples.

**Comment by Batta32** [comment]
@tommyJimmy87, if you want to keep using your generated Virtual Assistant and Skill it's okay, both workarounds are correct, just to consider that if you are blocked you can try with the available samples. 

Also, we narrowed the issue to the `wildcard search` that in _Windows_ and _macOS_ are different, we are implementing a fix for this changing the functionality of file's replacement with `_` prefix.

If you find another issue using macOS, please don't hesitate to create a new issue 😊.

**Comment by Batta32** [comment]
Hi there!
We solved this issue in #2111 merged in `master`.

Tomorrow a **new preview version** (`1.0.6-preview71`) of the `generator-botbuilder-assistant` will be published in `myget`, you can download and test it!
> npm uninstall --global generator-botbuilder-assistant
npm install --global generator-botbuilder-assistant@1.0.6-preview71 --registry https://botbuilder.myget.org/F/aitemplates/npm

**Comment by tommyJimmy87** [comment]
@Batta32 
Hi,

For the problem I had that version solved the issue, but now I have other errors now with tslint :) .
I guess is still not a very stable version.

**Comment by Batta32** [comment]
Hi @tommyJimmy87

We published a new stable version of the `generator-botbuilder-assistant` (version 1.0.6) in `myget`!

>npm install -g generator-botbuilder-assistant@1.0.6 --registry https://botbuilder.myget.org/F/aitemplates/npm
