### ISSUE TITLE
Azure Virtual Assistant

### ISSUE THREAD

**Issue by schinna** [microsoft/botframework-solutions#2068]
#### Just followed the steps based on the below link and NPM run start throw errors
https://github.com/microsoft/botframework-solutions/blob/master/docs/tutorials/typescript/virtualassistant.md

#### What are the steps to reproduce this issue?
https://github.com/microsoft/botframework-solutions/blob/master/docs/tutorials/typescript/virtualassistant.md

#### What were you expecting to happen?

NPM should work to start the bot and respond 

#### Can you share any logs, error output, etc.?

error

va-bot@1.0.0 build C:\BotFx\virtualAssistant\va-bot
> tsc --p tsconfig.json && npm run copy-templates

> va-bot@1.0.0 copy-templates C:\BotFx\virtualAssistant\va-bot
> copyfiles --up 1 "./src/**/*.json" "./lib"

C:\BotFx\virtualAssistant\va-bot\node_modules\botbuilder-azure\lib\cosmosDbStorage.js:36
            throw new Error('The settings service Endpoint is required.');
            ^

Error: The settings service Endpoint is required.
    at new CosmosDbStorage (C:\BotFx\virtualAssistant\va-bot\node_modules\botbuilder-azure\lib\cosmosDbStorage.js:36:19).js:36:19)
    at new DefaultAdapter (C:\BotFx\virtualAssistant\va-bot\lib\adapters\defaultAdapter.js:45:25)
    at Object.<anonymous> (C:\BotFx\virtualAssistant\va-bot\lib\index.js:76:17)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! va-bot@1.0.0 start: `npm run build && node ./lib/index.js NODE_ENV=development`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the va-bot@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Log Details**

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\ChinnaS\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@6.10.2
3 info using node@v8.15.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle va-bot@1.0.0~prestart: va-bot@1.0.0
6 info lifecycle va-bot@1.0.0~start: va-bot@1.0.0
7 verbose lifecycle va-bot@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle va-bot@1.0.0~start: PATH: C:\Users\ChinnaS\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\BotFx\virtualAssistant\va-bot\node_modules\.bin;C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin;C:\Program Files\Common Files\Microsoft Shared\Microsoft Online Services;C:\Program Files (x86)\Common Files\Microsoft Shared\Microsoft Online Services;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Sennheiser\SoftphoneSDK\;C:\Program Files (x86)\WebEx\Productivity Tools;C:\Program Files (x86)\Symantec\VIP Access Client\;C:\Program Files\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft Visual Studio 10.0\Common7\IDE\PrivateAssemblies\;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\ManagementStudio\;C:\Program Files\dotnet\;C:\Users\ChinnaS\AppData\Roaming\npm\node_modules\@angular\cli\bin;C:\Program Files\nodejs;C:\Program Files\nodejs\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Git\cmd;C:\WINDOWS\system32\config\systemprofile\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files (x86)\PowerShell\6\;C:\Users\ChinnaS\AppData\Local\Microsoft\WindowsApps;C:\Users\ChinnaS\AppData\Local\Programs\Microsoft VS Code\bin;C:\Program Files\dotnet;C:\Users\ChinnaS\.dotnet\tools;C:\Users\ChinnaS\AppData\Roaming\npm\node_modules\@angular\cli\bin;C:\Program Files\nodejs;C:\Users\ChinnaS\AppData\Roaming\npm;C:\Users\ChinnaS\AppData\Local\Programs\Fiddler;C:\Users\ChinnaS\AppData\Local\GitHubDesktop\bin
9 verbose lifecycle va-bot@1.0.0~start: CWD: C:\BotFx\virtualAssistant\va-bot
10 silly lifecycle va-bot@1.0.0~start: Args: [ '/d /s /c',
10 silly lifecycle   'npm run build && node ./lib/index.js NODE_ENV=development' ]
11 silly lifecycle va-bot@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle va-bot@1.0.0~start: Failed to exec start script
13 verbose stack Error: va-bot@1.0.0 start: `npm run build && node ./lib/index.js NODE_ENV=development`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\ChinnaS\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:326:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\ChinnaS\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:915:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid va-bot@1.0.0
15 verbose cwd C:\BotFx\virtualAssistant\va-bot
16 verbose Windows_NT 10.0.16299
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\ChinnaS\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v8.15.0
19 verbose npm  v6.10.2
20 error code ELIFECYCLE
21 error errno 1
22 error va-bot@1.0.0 start: `npm run build && node ./lib/index.js NODE_ENV=development`
22 error Exit status 1
23 error Failed at the va-bot@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by schinna** [comment]
Any help ?

**Comment by stevkan** [comment]
Are you able to post your appsettings.json file (hiding/removing any passwords and keys)?

**Comment by schinna** [comment]
is it empty

{
  "microsoftAppId": "",
  "microsoftAppPassword": "",
  "appInsights": {
    "appId": "",
    "instrumentationKey": ""
  },
  "blobStorage": {
    "connectionString": "",
    "container": ""
  },
  "cosmosDb": {
    "authkey": "",
    "collectionId": "",
    "cosmosDBEndpoint": "",
    "databaseId": ""
  },
  "contentModerator": {
    "key": ""
  }
}

**Comment by schinna** [comment]
got it.. I could fix the issue. 

Also deployed latest builds 
1. npm install --save botbuilder
2. npm install --save botbuilder-azure
3. SDK 4.5
4. syntax error in deploy_cognitive_models

**Comment by schinna** [comment]
also deployed
