### ISSUE TITLE
After auth warning on Direct Line Speech channel, bot does not respond to further queries

### ISSUE THREAD

**Issue by ryanisgrig** [microsoft/botframework-solutions#2073]
#### What project is affected?
Virtual Assistant solution (likely Solutions/Skill libary)

#### What language is this in?
C#

#### What happens?
VA on Direct Line Speech channel does not respond after giving user the special "token could not be retrieved" warning when needing to authenticate.

#### What are the steps to reproduce this issue?
On the Direct Line Speech channel (Kona), invoke a skill with with auth and then try to invoke another skill after. Trace activities will be returned showing that LUIS was invoked but no dialog happens. I believe something happened to the conversation state.

#### What were you expecting to happen?
User can continue conversation after auth warning.

#### Can you share any logs, error output, etc.?
```
User: how far is mount rainier
Bot: It's around 120 miles to Mount Rainier. You're looking at 4 hours and 21 minutes to drive there via WA-410 and Stevens Canyon Rd with traffic.
User: how about mount st helens
Bot: It's around 190 miles to Mount St Helens. You can drive there via I-5 S and WA-503 in 5 hours and 35 minutes with traffic.
User: send an email
Bot: A token could not be retrieved for Outlook, please link your account to your Assistant and try again
User: what is 1 + 1
User: cancel
User: what is 1 + 1
User: cancel
User: what is 1 + 1
```

**Comment by lauren-mills** [comment]
@lzc850612 assigning you to decide where this should go.

**Comment by lzc850612** [comment]
Should likely cancel the remote skill dialog so VA can handle other requests. Adding into the backlog.
