### ISSUE TITLE
Error with TodoSkill deployment (via deploy.ps1)

### ISSUE THREAD

**Issue by PurnaChandraPanda** [microsoft/botframework-solutions#2074]
I get the same error for TodoSkill deployment as described in https://github.com/microsoft/botframework-solutions/issues/1426. 

PS E:\BotSamples\virtual-assistant\cs\TodoSkill1\todoskill> ludown -v
1.3.2

PS E:\BotSamples\virtual-assistant\cs\TodoSkill1\todoskill> .\Deployment\Scripts\deploy.ps1
..
..
> Creating resource group ...
> Validating Azure deployment ...
> Deploying Azure services (this could take a while)...
> Updating appsettings.json ...
> Deploying cognitive models ...
> Parsing General LU file ...
> Deploying General LUIS app ...
> Setting LUIS subscription key ...
> Parsing ToDo LU file ...
> Deploying ToDo LUIS app ...
! Could not deploy LUIS model. Review the log for more information.
! Log: E:\BotSamples\virtual-assistant\cs\TodoSkill1\todoskill\Deployment\Scripts\..\deploy_cognitive_models_log.txt
> Setting LUIS subscription key ...
! Could not create LUIS app. Skipping dispatch add.
! No QnA Maker Subscription Key provided. Skipping knowledgebases.
> Publishing to Azure ...
> Done.

The log file indicates the following in terms of deployment failure.

```
Cannot find the entity extractor "TaskContent.Any" in the specified application version.
```

Ask
=============
I tried multiple times with different deployments each time, and ended up with similar outcome. It seems to be a genuine issue. Can someone please share some thoughts what can be done to overcome this problem?

**Comment by lauren-mills** [comment]
Hi, this is related to a known bug in the 1.3.2 version of the ludown tool. They've fixed the issue, but a new version hasn't been published yet. To work around this issue in the meantime, you can install the preview build of the ludown tool following these instructions: https://botbuilder.myget.org/feed/botbuilder-tools-daily/package/npm/ludown#nightly-builds

**Comment by PurnaChandraPanda** [comment]
thank you - i would try .. is the problem still there in 1.3.1?

**Comment by PurnaChandraPanda** [comment]
I tried the nightly build. It's been helpful. Any idea when the next public preview or GA version of "ludown" be available?

**Comment by lauren-mills** [comment]
No, I'm not sure what their release schedule is. The 1.3.1 version works with To Do, but there's another issue in the botskills tool not handling old versions well. Its also being actively worked on.

**Comment by lauren-mills** [comment]
Closing this for now since you were able to get it working.

**Comment by lauren-mills** [comment]
FYI - ludown version 1.3.3 with this fix has been published to npm.
