### ISSUE TITLE
Proactive messaging doesn't work with streaming

### ISSUE THREAD

**Issue by tamerin-tech** [microsoft/botframework-solutions#2079]
We are using proactive messaging, this is working well while the client is using normal DirectLine (without streaming).
Now we have a new client on Android, that requires the streaming enabled option for the channel.

Our proactive code is very similar to the one explained in the documentation here: https://github.com/microsoft/botframework-solutions/blob/master/docs/howto/assistant/csharp/proactivemessaging.md

But it fails on turnContext.SendActivityAsync (the callback from 
ContinueConversationAsync...) as the endpoint does not accept https nor http. (clearly because the endpoint accepts only websocket)

So I tried to replace the adapter with a new object from type: WebSocketEnabledHttpAdapter
but then it fails on SendActivityAsync (not implemented exception).

Any ideas how to send proactive message on streaming channel for an android client?

Thanks
Ron

**Comment by lzc850612** [comment]
The DL speech channel does not support opening up a websocket to connect to the client proactively. So I'd say proactive in Speech Streaming scenario is just not supported. I suggest you contact the DL speech folks to check on their plan to support this.

**Comment by lauren-mills** [comment]
Closing, since this is not supported by the channel.
