### ISSUE TITLE
New Chit Chat causes issues with dispatcher routing

### ISSUE THREAD

**Issue by Dewain27** [microsoft/botframework-solutions#2080]
When you load the new Chit Chat files and plugs this into a VA deployment, the dispatcher is trained to all of the questions and answer pairs.  This results in 6000+ items trained in the dispatcher.  The issue is that a skill with a manifest does not have this level of training typically and you end up with the dispatcher believing that all questions should be routed to the Chit Chat QnA Maker.

Example:  Chit Chat trains a lot of “Who is…”  (Who is your daddy?, Who is your creator?, and etc.).  A customer will have things like “Who is the primary contact for marketing?”  dispatch believes due to the abundance of training for Chit Chat that it owns the questions of “Who is….”   The way that we train a LUIS skill does not require all the training that was done for the dispatcher and this is causing confusion at the dispatch level.

**Comment by lauren-mills** [comment]
The new dispatch features should help with this but we need to verify.

**Comment by mekinney** [comment]
FYI, I agree that chitchat is overly trained relative to the rest of a VA.  This is true for both skills and any FAQ you might add.  Honestly, I typically remove chitchat and integrate a much smaller chitchat (with all "how, what, etc." type questions removed) into the faq.  This minimizes dispatch confusion between a faq and chitchat.

**Comment by lauren-mills** [comment]
This is dependent on us testing and implementing the new dispatch autoactivelearning features.

**Comment by darrenj** [comment]
Dispatch team have confirmed Active learning features with dispatch tool to address this. Will reopen if we see recurrence of this.
