### ISSUE TITLE
Reopen issue #1835 / not a way to reopen

### ISSUE THREAD

**Issue by andhdo** [microsoft/botframework-solutions#2084]
#### What project is affected?
https://github.com/microsoft/botframework-solutions/issues/1835
i don't have a way to reopen the issue, so i'm creating it to the refrenced issue become solved.
#### What happens?
issue were not solved really, because of the reasons commented inside. 

#### REASONS

- response indirectly forwards to the [PROGRAMATIC WAY](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-authentication?view=azure-bot-service-4.0&tabs=aadv2%2Cjavascript%2Cbot-oauth) already mentioned in the issue,
- thus, you are not using the authentication mechanism used by VA in the skills: you are building a new one. 
- it was tested in typescript, and does not work: (1:doing the configuration of bot-registration, thent 2: adding aad service provider registration with permissions of graph api, and 3: correlating bot-registration with aad-registration of the previous step, and 4: adding the appsettings configuration). practically the VA is still working without authentication following the [manual steps indicated]
(https://github.com/microsoft/botframework-solutions/blob/next/docs/reference/skills/manualauthsteps.md).
- I do not want to use a skill because it is an additional cost that would be paid for a bot that does not intend to use other pre-built elements; i just want to enable the Assistant to authenticate against the azure AD. As far as i know when you create a new skill, you can activate the authentication; why not to document this strategy to enable a local authentication scenario?, or please clarify if you can only use the programmatic way to add authentication to virtual assistant. Thanks

**Comment by lauren-mills** [comment]
reopened original issue.
