### ISSUE TITLE
'luisgen' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by JPaulPunzalan** [microsoft/botframework-solutions#2093]
Hi Team,

I re-installed .NET Core SDK (2.2.401 x64) and installed LuisGen but I still keep getting the same error.

`'luisgen' is not recognized as an internal or external command,
operable program or batch file.`

Please see the screenshot below.
![image](https://user-images.githubusercontent.com/14859857/62776304-c1e39600-badc-11e9-9920-083b4a5ef30c.png)

Kindly advise. Thanks a lot!

**Comment by Batta32** [comment]
Hi @JPaulPunzalan,

We had the same issue which we solved following this steps:
1. Execute `dotnet tool uninstall --global luisgen`
1. Execute `npm install --global luisgen`
1. At this point, the installation shall need to add the following environment variable, if don't have it you will see the next similar command: `setx /M Path "C:\Users\<YOUR_USER>\.dotnet\tools"`. If this happens execute that command replacing the placeholder `<YOUR_USER>` with your **username**, go back to the first step and start again.
1. Reopen your terminal
1. Try to invoke the `luisgen` tool

We hope it’s helps you!

**Comment by JPaulPunzalan** [comment]
Hi Everyone,

It is fixed. Thanks a lot!
