### ISSUE TITLE
Error to display OAuth Card in Web Chat

### ISSUE THREAD

**Issue by angie4u** [microsoft/botframework-solutions#210]
**Project**
Vistual Assistant Bot - Error to display OAuth Card in Web Chat which is embedded in Azure portal

**Description**
Error to display OAuth Card in Web Chat which is embedded in Azure portal

**To Reproduce**
1. Clone Code and deploy and run 
2. Deploy it to Azure Bot Service 
3. Chat the bot by using Web Chat which is embedded in Azure portal
4. type "email to me"
5. Bot do not properly display the OAuth Card

**Expected behavior**
Bot should display the Sign-in card and then user can type their credentials

**Screenshots**
![image](https://user-images.githubusercontent.com/16282358/47832968-be97dd00-dddb-11e8-89a1-bf60242902e8.png)

**Additional context**
I found a link which is maybe related to this issue on Github
https://github.com/Microsoft/BotBuilder/issues/4632

**Comment by lauren-mills** [comment]
Hi @angie4u, the web chat in the "Test in Web Chat" tab of the Azure portal is out of date and does not support oauth cards. The latest web chat information can be found here: https://github.com/Microsoft/BotFramework-WebChat

**Comment by darrenj** [comment]
Alternatively please use the [Emulator](https://github.com/Microsoft/BotFramework-Emulator/releases
) and open the Bot file we create for you in your project directory

**Comment by ghost** [comment]
Hi @darrenj, 

Emulator is not an alternative for me to test the bot to a big number of users. Is there is a description how to authenticate to ADv2 via CDN or Web Chat. If I use CDN it opens a browser and ask for "Please enter this validation code into the chat window to complete the sign-in". In Emulator works perfect, but I need the bot in a browser. Please give advice.

**Comment by lauren-mills** [comment]
@David201406 the authentication code is used for channels that do not support sending the token back via an event. You should be able to paste the code back in to the conversation to finish authenticating. Does that not work for you?

**Comment by ghost** [comment]
@lauren-mills  No, if I enter the code in the chat, I get an error. 

![image](https://user-images.githubusercontent.com/24620337/49391716-b9a4b100-f72c-11e8-9bbe-e6bff7004703.png)

**Comment by lauren-mills** [comment]
@David201406 thanks for the screenshot. Would you mind trying this same flow in the emulator and sending me the stack trace from the trace message? You should be able to see it in the bottom right window when the error occurs. Another option is to look at your appInsights log in the Azure portal for exceptions. Either of those will help me a lot in figuring it out.

**Comment by lauren-mills** [comment]
Sorry, I just saw in your previous comment that you can't repro in the emulator. If you have appInsights set up for your published app please try that otherwise let me know.

**Comment by ghost** [comment]
@lauren-mills I startet the chatbot in the emulator and it worked fine, I could sign in and send emails. Afterwards, in Chrome and Edge even after restart the PC I could send email without the need to sign in. I started even in Azure the App Service. I still could send email from the chatbot without sign in. So I guess, that somewhere and somehow the Token is saved. But how can I reset everything, to try to reproduce the issue.

**Comment by lauren-mills** [comment]
You should be able to type "logout" to clear your token cache

**Comment by ghost** [comment]
Entering "logout" I get "OAuthPrompt.SignOutUser(): not supported by the current adapter |    at EmailSkill.MainDialog.OnLogout(DialogContext". Is there a other possibility to clear the token Cache?

**Comment by darrenj** [comment]
Hi David,

Logout isn't a scenario we currently support at the VA level but we do have a reset user event to trigger the flow we envisage. You can try this by typing this into your conversation:

/event:{Name:"IPA.ResetUser"}

https://github.com/Microsoft/AI/blob/master/solutions/Virtual-Assistant/docs/virtualassistant-events.md



Sent from my 📱
________________________________

**Comment by ghost** [comment]
[Exception.zip](https://github.com/Microsoft/AI/files/2641234/Exception.zip)
Entering /event:{Name:"IPA.ResetUser"} AND reboot of PC helped to clear the token Cache.

I could reproduce the issue (see above screenshot). I attach the current used SkillDialog.cs and the ExceptionLog of AppInsight.

**Comment by ghost** [comment]
I discovered. I need to refresh the HTML page and restart the conversation. Afterwards it works sending an email.
