### ISSUE TITLE
Analytics: does not load telemetry - access to the resource is forbidden

### ISSUE THREAD

**Issue by PurnaChandraPanda** [microsoft/botframework-solutions#2105]
I have my virtual assistant running. I see a few transcripts generated in Table Storage. Downloaded the latest ".pbit" analytics file - mapped to the VA application insights ID. However, it fails at [EventTelemetry] phase stating - "Access to the resource is forbidden". Can you please share thoughts what is wrong over here?

![image](https://user-images.githubusercontent.com/18218128/62950584-f4a3cc00-be05-11e9-8337-2a101a0d6d25.png)

**Comment by dmvtech** [comment]
Hi @PurnaChandraPanda, which option did you use to authenticate in PowerBI?

**Comment by dmvtech** [comment]
You should be logging in with Organizational Account

![image](https://user-images.githubusercontent.com/43397658/63109224-882be880-bf3d-11e9-9714-355864938533.png)

**Comment by PurnaChandraPanda** [comment]
I have the .pbit file downloaded to my desktop from [here](https://github.com/microsoft/botframework-solutions/tree/master/solutions/analytics). And, just double clicked that file to get it opened in "powerbi desktop". Then, it asked me to appinsights application id, which was provided. Then, I just get that forbidden error.

**Comment by dmvtech** [comment]
I have witnessed this same behavior before. For me, it was when I tried to use another login other than Org account. The thing is, I don't know how to _**reset it**_ to prompt for Org auth _again_. I'll look around for anything on how to clear that in PowerBI. You might be able to try uninstalling Power BI desktop and re-installing, if that is not going to impact you to do so.

**Comment by PurnaChandraPanda** [comment]
I uninstalled powerbi desktop and installed it again. This time, have tried "organizational account" as in screenshot and logged in. I could see data for all data table such as EventTelemetry, Interactions, SessionDuration, but not FlowAggregates. I see number of rows in FlowAggregates as zero. So, for dialog related flow capture, do i need to add some other explicit logging method?

**Comment by dmvtech** [comment]
Glad you got past the authentication part. I have no idea regarding the FlowAggregates. 

Would you please open a new issue in this repo so that we can track it separately? I'm going to close this one as solved.
