### ISSUE TITLE
[botskills] az output type "table" breaks auth configuration steps

### ISSUE THREAD

**Issue by lauren-mills** [microsoft/botframework-solutions#2107]
#### What project is affected?
botskills cli

#### What language is this in?
typescript 

#### What happens?
When the az cli default output is set to 'table', the connect command fails on "az bot authsettings list"

#### What are the steps to reproduce this issue?
1. run `az configure` to set the output to table
2. run botskills connect on a skill with authsettings

#### Notes
You can add `--output json` to any az cli commands to set the output type to json for just that command.

**Comment by Batta32** [comment]
Hi @lauren-mills, thanks for reporting this issue!

It's seems to be a similar issue to #1906 which was fixed by #1940 which updates the `az commands` of the `deployment scripts`.

We will add it to our backlog!
