### ISSUE TITLE
Update demo environments to support a multi-language VA

### ISSUE THREAD

**Issue by lauren-mills** [microsoft/botframework-solutions#2108]
Fulfill additional requirements for demo environments

- [x] Enable Teams channel for stable/test/dev
- [x] Virtual Assistant web chat for stable/test/dev
- [x] Experimental Music Skill build (en/zh)
- [x] Experimental Music Skill release
- [x] Experimental Restaurant Booking Skill build (en/zh)
- [x] Experimental Restaurant Booking Skill release
- [x] Experimental Weather Skill build (en/zh)
- [x] Experimental Weather Skill release
- [x] Deploy Chinese language models for VA/Skills (related to #1959)
- [x] Add additional skills to VAs

**Comment by ryanisgrig** [comment]
Blocked via botskills multilanguage capabilities at #2131

**Comment by ryanisgrig** [comment]
Unblocked by Botskills CLI, this is in-progress.
