### ISSUE TITLE
 WebSocketServer within the SkillWebSocketBotAdapter should be cached

### ISSUE THREAD

**Issue by EricDahlvang** [microsoft/botframework-solutions#2119]
#### What project is affected?
Virtual-Assistant and Skills

#### What language is this in?
dotnet

#### What happens?
Since the SkillDialog is transient, and the SkillWebSocketTransport is created within the SkillDialog, the websocket is closed every time the turn finishes.  SkillWebSocketTransport should be cached and re-supplied to the constructor of the SkillDialog in order to ensure the underlying socket remains open.

crude example:
```cs
static ConcurrentDictionary<string, SkillWebSocketTransport> _skillSocketTransports = new ConcurrentDictionary<string, SkillWebSocketTransport>();

...

            // Register skill dialogs
            services.AddTransient(sp =>
            {
                var userState = sp.GetService<UserState>();
                var skillDialogs = new List<SkillDialog>();

                foreach (var skill in settings.Skills)
                {
                    var authDialog = BuildAuthDialog(skill, settings, appCredentials);
                    var credentials = new MicrosoftAppCredentialsEx(settings.MicrosoftAppId, settings.MicrosoftAppPassword, skill.MSAappId);

                    SkillWebSocketTransport transport = null;
                    if(!_skillSocketTransports.TryGetValue(skill.Id, out transport))
                    {
                        transport = new SkillWebSocketTransport(skill, credentials, telemetryClient);
                        _skillSocketTransports.TryAdd(skill.Id, transport);
                    }

                    skillDialogs.Add(new SkillDialog(skill, credentials, telemetryClient, userState, authDialog, transport));
                }

                return skillDialogs;
            });
```

#### What were you expecting to happen?
The WebSocket should not be re-created every time the Skill is invoked.  There also needs to be some changes on the Skill side, to ensure the WebSocketServer within the SkillWebSocketBotAdapter is cached.  Both sides of the socket need to remain open until explicitly closed (normal socket pipeline processing a message should not be closing the socket).

#### Can you share any logs, error output, etc.?
I ran into this issue while working with the v3botskillprototype: https://github.com/microsoft/BotBuilder-Samples/compare/darrenj/v3botskillprototype

**Comment by EricDahlvang** [comment]
I looked into this some more, and it isn't the `SkillWebSocketTransport` that should be cached, but the `WebSocketClient` (which is created inside the [SkillWebSocketTransport](https://github.com/microsoft/botframework-solutions/blob/master/lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/SkillWebSocketTransport.cs#L51) ).  However, the current implementation has the turn context coupled to the `SkillCallingRequestHandler`.  These need to be decoupled in order to properly process messages without re-creating the websocket on every call.

**Comment by lzc850612** [comment]
Right now the supported model is that we open up a websocket, send over the activity, and listen on it until all the responses are back for that turn, and close up the websocket. We do not support reusing a websocket connection for multi-turn dialog right now. It is however in our roadmap to support that in the future but with no target milestone.

**Comment by lauren-mills** [comment]
This will not be fixed according to SDK team.
