### ISSUE TITLE
Use ISet for IWhitelistAuthenticationProvider::AppsWhitelist

### ISSUE THREAD

**Issue by xieofxie** [microsoft/botframework-solutions#2139]
#### Is your feature request related to a problem? Please describe. 

For better performance for Contains function.

**Comment by Dewain27** [comment]
@xieofxie please put more detail into this Feature Request.  We will need this to properly classify the request.

**Comment by xieofxie** [comment]
For current next branch, only AppsWhitelist's Contains function is used. It seems that AppsWhitelist will be used as a validator for AppId and ISet has better performance than IList in checking existence, uniqueness, add, remove specific AppId etc.

**Comment by lzc850612** [comment]
You have a good point. I think if we want to maximize performance, we should just use HashSet<T> instead of the interface to make sure we have the performance gain otherwise there's no guarantee of it since developers can implement this interface however they want.
