### ISSUE TITLE
VA not canceling skill dialog fully

### ISSUE THREAD

**Issue by litofish** [microsoft/botframework-solutions#2148]
#### What project is affected?
Virtual assistant

#### What language is this in?
CSharp

#### What happens?
When I cancel in the middle of a skill dialog within a VA it goes through all of CancelDialog, but then when I try to invoke a new dialog it is still stuck in the previous dialog. I've tried with a number of skills and it seems to only happen when you cancel in the middle of a prompt that uses a prompt validator. 

![cancel_error](https://user-images.githubusercontent.com/39777667/63196260-b4249800-c029-11e9-9abd-b6fd7977ea99.PNG)

#### What are the steps to reproduce this issue?
In a VA, start a skill dialog and cancel in the middle of the dialog.

**Comment by lzc850612** [comment]
This will be fixed by #2135 . There's a PR out #2136

**Comment by Dewain27** [comment]
Duplicate see above for details

**Comment by Kumar3010** [comment]
Hi,
we have the below scenario:-
1. Identify the skill intent and open dialog a. bot prompts to enter user some input
2. user enters a text pertaining to another skill intent
3. we want the control to go to that skill and have the execution complete
4. once the above step is done we want execution to resume from dialog a.
is there any sample to refer to.
thanks,

**Comment by xieofxie** [comment]
We have fallback but it is unable to resume when it is another skill https://github.com/microsoft/botframework-solutions/pull/2076.
@DingmaomaoBJTU

**Comment by Kumar3010** [comment]
Hi @xiefoxie,
do we have to write any code in virtual assistant to handle the fallback envent or oneventsasync would take care.
thank you

**Comment by xieofxie** [comment]
@Kumar3010 SkillIntentRecognizer is needed in VA as the pr https://github.com/microsoft/botframework-solutions/pull/2076.

It is not in current branch now as this function is being redesigned https://github.com/microsoft/botframework-solutions/pull/2665. But if you modify your VA and skill as the #2076, it should work.

**Comment by xieofxie** [comment]
@Kumar3010  It is being removed now https://github.com/microsoft/botframework-solutions/pull/2672, maybe you should wait~

**Comment by Kumar3010** [comment]
@xieofxie - could you please let us know when this fallback event would be available. we have tried using semanticactions to pass data to the VA but unable to handle or get this in the VA. any sample would be highly appreciated.
