### ISSUE TITLE
AZURE Service is not getting started

### ISSUE THREAD

**Issue by YammanureSreekanth** [microsoft/botframework-solutions#2151]
#### What project is affected?
MS-BOT
#### What language is this in?

Node js and Typescript

#### What happens?
We checkout the Typescript sample from below 

https://github.com/microsoft/botframework-solutions/tree/master/templates/Virtual-Assistant-Template/typescript/samples/sample-assistant

and when we try running it in the local, server is getting starting. But getting 'HTTP Error 500.1001 - Internal Server Error' in AZURE service.

#### What are the steps to reproduce this issue?
1. Check out code from below 
https://github.com/microsoft/botframework-solutions/tree/master/templates/Virtual-Assistant-Template/typescript/samples/sample-assistant
2. Build and Release to AZURE service.
3. Try to access the service.

#### What were you expecting to happen?
AZURE service should be accessible.
#### Can you share any logs, error output, etc.?
HTTP Error 500.1001 - Internal Server Error
The page cannot be displayed because an internal server error has occurred.
#### Any screenshots or additional context?
![azure_service_log](https://user-images.githubusercontent.com/24246902/63247604-11675600-c283-11e9-8cfd-b329bbbaebc7.jpg)

Additionally, 

Once we checkout from https://github.com/microsoft/botframework-solutions/tree/master/templates/Virtual-Assistant-Template/typescript/samples/sample-assistant we tried in local and server is getting started. So we created AZURE service and deployed but the server is not getting started. So we made a few changes to startup

- in package.json   
"start": "node ./lib/index.js NODE_ENV=production", - Here removed the npm run build task. 
We have given build as another task to generate the lib folder with .js files
- web.config
![web config](https://user-images.githubusercontent.com/24246902/63248044-21cc0080-c284-11e9-9494-61dbe37db8c9.jpg)

With this code changes, we are seeing above mentioned exceptions. 

Could you please assist me on this error.

**Comment by darrenj** [comment]
Just to check - can you confirm you ran through the deployment steps [here](https://microsoft.github.io/botframework-solutions/tutorials/typescript/create-assistant/1_intro/)?

**Comment by YammanureSreekanth** [comment]
Yes.

**Comment by Batta32** [comment]
Hi @SreekanthOAuth, thanks for reporting this issue!

Have you tried locally following this steps? (Using [sample-assistant](https://github.com/microsoft/botframework-solutions/tree/master/templates/Virtual-Assistant-Template/typescript/samples/sample-assistant)). With this, we can ensure that the sample is running correctly.

1. Execute `npm install` to install the dependencies
1. Execute `npm run build`
1. Execute `deploy.ps1` to deploy the services
1. Execute `npm run start`
1. Open **BotFramework Emulator**, if you don't have it, please download it [here](https://github.com/microsoft/BotFramework-Emulator#download)
1. Add a bot configuration using http://localhost:3979/api/message as `Endpoint URL`, a `bot name`, your `appId` and `appPassword`
1. Check the communication with the **Virtual Assistant Sample**

If you face with an issue during the execution, don't hesitate to ask us sharing the error!

**Comment by YammanureSreekanth** [comment]
Hi Batta32, Yes did the same. In my local server is starting. However, the problem is after our deployment the AZURE service is not getting started.

**Comment by darrenj** [comment]
I've just run a few build and deployment end to end and validated it works to double check.

When your deploy.ps1 script finished it would have advised you to run something along these lines

```
.\deployment\scripts\publish.ps1 -name djtsdeploy1 -resourceGroup djtsdeploy1
```

Assuming you did run that, one issue might be that `npm run build` hasn't been run **after deployment** which updates the appsettings file which is deployed? We can get docs updated to emphasise this.

I reproed a similar problem to yours which running npm run build resolved.

**Comment by YammanureSreekanth** [comment]
Hi Darrenj, Yeah I ran publish.ps1 also.

I have added the build as a task to build pipeline.
![build_pipeline (2)](https://user-images.githubusercontent.com/24246902/63488838-fccace00-c4cd-11e9-9ffc-f5db26a06267.jpg)

You mean do we need to add **npm run build**  task in release pipeline also?

If so, could you please suggest me how to do that.

**Comment by Batta32** [comment]
Exactly @SreekanthOAuth! You should add a **build task** before the publish execution in order to update the `appsettings.json` and `cognitivemodels.json` with the correct keys.

Here you can see an example to execute `npm run build` in the `sample-assistant`:

![image](https://user-images.githubusercontent.com/11904023/63528377-305f2580-c4d9-11e9-9f48-bfea4d7fbf7c.png)

The reason is that after the execution of the **deploy.ps1**, the `appsettings.json` and `cognitivemodels.json` are updated with the resources' keys in the `src` folder but not in the `lib` which contains the transpiled files.
Before executing `publish.ps1`, it's needed to run `npm run build` in order to have the package deployed up to date and ready to be tested in Azure.

**Comment by darrenj** [comment]
In case it's helpful we have some early CI examples [here](https://github.com/microsoft/botframework-solutions/tree/master/yaml/typescript)
