### ISSUE TITLE
Top Level Intent needed for "Repeat That"

### ISSUE THREAD

**Issue by Dewain27** [microsoft/botframework-solutions#2152]
## User Story
As ... a bot user
I want ... to ask my Virtual Assistant to repeat what it just said
so that ... if I misheard it I can hear it again

## Acceptance Criteria 
*List your requirements.*
- [ ] Handle the "Repeat" intent as an interruption
- [ ] Need to store the previous set of activities since last user message
- [ ] Walk the SDK team through the proposal to verify approach

## Resources
*Provide any screenshots or conversation mockups to support your request.*
*Learn how to mock up bot conversations with [.chat files](http://aka.ms/bfchatfile).*
[repeat.chat.txt](https://github.com/microsoft/botframework-solutions/files/3628307/repeat.chat.txt)

## Notes
*Provide any additional information.*
- General.LU has a `Repeat` intent 
- Should previous activities be stored in conversation state on each turn?
- We could use a middleware to accomplish this

**Comment by darrenj** [comment]
Already in place within VA, see [here](https://github.com/microsoft/botframework-solutions/blob/master/templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Deployment/Resources/LU/en/General.lu#L276). Is the ask to implement an activity replay as part of the top-level interrupt pattern?

**Comment by darrenj** [comment]
Delivered in last release
