### ISSUE TITLE
Top Level Cancel more dynamic

### ISSUE THREAD

**Issue by Dewain27** [microsoft/botframework-solutions#2153]
## User Story
As ...
I want ...
so that ...

## Acceptance Criteria 
*List your requirements.*
- [ ] ...
- [ ] ...
- [ ] ...

## Resources
*Provide any screenshots or conversation mockups to support your request.*
*Learn how to mock up bot conversations with [.chat files](http://aka.ms/bfchatfile).*

## Notes
*Provide any additional information.*

Top-level Cancel should be able to take responses that handle:

* Cancel with No Response
* Cancel with Confirmation
* Cancel with Validation

The skill should be able to pass back to the top level the Cancel Type it would like and the top level should honor that request.  There should be a default that is set at the top level if just cancel comes back.

**Comment by ryanisgrig** [comment]
Related to #2031

**Comment by ryanisgrig** [comment]
Closing as this will be supported in #2031
