### ISSUE TITLE
Analytics: no records in FlowAggregates

### ISSUE THREAD

**Issue by PurnaChandraPanda** [microsoft/botframework-solutions#2155]
In reference to https://github.com/microsoft/botframework-solutions/issues/2105#issuecomment-522779621, I could see data for all data table such as EventTelemetry, Interactions, SessionDuration, but not FlowAggregates. I see number of rows in FlowAggregates as zero. So, for dialog related flow capture, do i need to add some other explicit logging method? I am talking about Virtual assistant template bot service app here.

**Comment by darrenj** [comment]
Out of interest - did you create your VA project from a recent template or using one created previously? There is a [known issue](https://microsoft.github.io/botframework-solutions/reference/knownissues/#telemetry-gaps--flowaggregate-errors-in-the-powerbi-template) with older templates but these changes have been incorporated in new templates.

**Comment by PurnaChandraPanda** [comment]
This is a new template downloaded 2 to 3 days back, but not finding records in FlowAggregates.

**Comment by ryanisgrig** [comment]
Assigned to Support to assist, this does not occur on our instance which uses both VA/Skills. Is there any particular error (like bad query, missing column etc.) the FlowAggregates table gives you or is it just empty?

**Comment by PurnaChandraPanda** [comment]
I don't see any error. It is just that number of rows in FlowAggregates table is zero.

**Comment by jwiley84** [comment]
Investigating!

**Comment by jwiley84** [comment]
Ok, well I can definitely repro this

![image](https://user-images.githubusercontent.com/17333688/63727955-e6e34300-c816-11e9-9c7f-361114fd285a.png)

I'm going to have to get with someone who has successfully populated this table and see what I *should* be getting.

**Comment by jwiley84** [comment]
Hi @PurnaChandraPanda!

Can you try something for me? 

Head to the 'Edit Queries' on the PowerBI desktop:

![image](https://user-images.githubusercontent.com/17333688/64282122-8c7a6e80-cf09-11e9-9e22-7a2a238832e7.png)

On the screen that pops up, on the left side, if you have a folder that says 'Query Errors - 3/18...', you can delete the whole folder (and both the errors inside it). 

![image](https://user-images.githubusercontent.com/17333688/64282409-36f29180-cf0a-11e9-984a-8a029d6a3e7a.png)


Next, click on the 'FlowAggregates' table, in the list on the left. Once that's selected, click 'Advanced Editor' in the toolbar:

![image](https://user-images.githubusercontent.com/17333688/64282956-5a6a0c00-cf0b-11e9-86b0-c8e16b58a2d5.png)


In the NEW window, select all the code, and replace it with the following:

```
let
    Source = #"Interactions",
    #"Added Conditional Column" = Table.AddColumn(Source, "DialogStatusId", each if [DialogStatus] = "Started" then 0 else if [DialogStatus] = "Done" then 2 else if [DialogStatus] = "Canceled" then 3 else 1),
    #"Grouped Rows" = Table.Group(#"Added Conditional Column", {"DialogInstanceId"}, {{"StartTime", each List.Min([Time]), type datetimezone}, {"EndTime", each List.Max([Time]), type datetimezone}, {"InteractionCount", each Table.RowCount(_), type number}, {"DialogId", each List.Max([DialogId]), type text}, {"Locale", each List.Max([Locale]), type text}, {"DialogStatusId", each List.Max([DialogStatusId]), type number}}),
    #"Added Custom" = Table.AddColumn(#"Grouped Rows", "FlowDuration", each Duration.TotalSeconds([EndTime]-[StartTime])),
    #"Added Conditional Column1" = Table.AddColumn(#"Added Custom", "DialogStatus", each if [DialogStatusId] = 0 then "Started" else if [DialogStatusId] = 1 then "Abandoned" else if [DialogStatusId] = 2 then "Done" else if [DialogStatusId] = 3 then "Canceled" else null),
    #"Duplicated Column" = Table.DuplicateColumn(#"Added Conditional Column1", "StartTime", "StartTime - Copy"),
    #"Renamed Columns" = Table.RenameColumns(#"Duplicated Column",{{"StartTime - Copy", "Date"}}),
    #"Changed Type1" = Table.TransformColumnTypes(#"Renamed Columns",{{"Date", type date}}),
    #"Filtered Rows" = Table.SelectRows(#"Changed Type1", each [DialogInstanceId] <> null),
	#"Filtered Rows1" = Table.SelectRows(#"Filtered Rows", each [DialogInstanceId] <> "00000000-0000-0000-0000-000000000000")
in
    #"Filtered Rows1"
```


After you've clicked 'Done', on the right side of the previous screen is 'Query Settings'. In the 'Applied Steps' block, there's a line that says 'Changed Type1'. 

![image](https://user-images.githubusercontent.com/17333688/64283735-df095a00-cf0c-11e9-8127-d922f3068f25.png)

When you click this, there might be something on the table, though the DialogInstanceId might say 'null'. 

![image](https://user-images.githubusercontent.com/17333688/64283747-e3ce0e00-cf0c-11e9-953c-ef91e6d14f23.png)

Please let me know the results, whether there is something, or even if there isn't.

**Comment by jwiley84** [comment]
Also, do you have a skill attached to your VA bot?

**Comment by PurnaChandraPanda** [comment]
@jwiley84  I see data in "change type1". I do not have skill attached in VA now. There may be the cases of transaction where dialogs are not initialized. In that case, it would not show up in [FlowAggregates]. Can you please confirm?

**Comment by jwiley84** [comment]
AFAIK, in order for there to be a flow, there has to be dialog. The problem I'm seeing is that the dialoginstanceid is null. The final two steps of the query (Filtered Rows and Filter Rows1) filter out if that field is null or blank, which explains why your table is empty. It does NOT however, explain why that field is null or empty, so I'm going to do some more digging.

**Comment by jwiley84** [comment]
So, digging into the power bi template shows that 'dialoginstanceid' is populated from CustomEvents.CustomDimensions.InstanceId. My own VA bot does not have this in the application insights:

![image](https://user-images.githubusercontent.com/17333688/65187729-67b1eb00-da21-11e9-8b8a-e88163848c50.png)


I'm not sure why, or what triggers that field to be populated, but I'm going to reach out to a different team to see what I'm missing.

**Comment by jwiley84** [comment]
Hi @PurnaChandraPanda 

My colleague got back to me. That field is populated by client data, and is a catch all, which would explain why I don't see it. I'm going to fiddle with the Power BI template, and see if I can get it to not call on that data, or use a different field as the key to link the tables together. If not all clients send the data that an entire table is hinging on, then there is no reason we should be using that data.

**Comment by CoHealer** [comment]
@PurnaChandraPanda do you still require assistance with this issue?

**Comment by PurnaChandraPanda** [comment]
This issue can be closed. I got my open query answered.
