### ISSUE TITLE
add score for RouteAsync like OnInterruptDialogAsync

### ISSUE THREAD

**Issue by xieofxie** [microsoft/botframework-solutions#2157]
## User Story
As ...
I want ...
so that ...

## Acceptance Criteria 
*List your requirements.*
- [ ] ...
- [ ] ...
- [ ] ...

## Resources
*Provide any screenshots or conversation mockups to support your request.*
*Learn how to mock up bot conversations with [.chat files](http://aka.ms/bfchatfile).*

## Notes
*Provide any additional information.*

#### Is your feature request related to a problem? Please describe. 

When score is low, it is inaccurate.

#### What is the solution you are looking for?

Similar to OnInterruptDialogAsync

**Comment by lauren-mills** [comment]
So when it gets a low score, are we saying it would return the none intent instead?

**Comment by xieofxie** [comment]
Yes, I would suggest so. While route and interrupt are somehow different as route faces a much broader utterance than general or certain skill (so lower score is expected?) and interrupt does need more confidence to be invoked.
If a score is added, it might be lower than interrupt.

**Comment by darrenj** [comment]
@lauren-mills addressed with recent changes?
