### ISSUE TITLE
[Weather Skill] Update to use the Weather pre-built domain

### ISSUE THREAD

**Issue by darrenj** [microsoft/botframework-solutions#2160]
## User Story
As ... a bot developer
I want ... the Weather Skill to use the prebuilt weather domain by LUIS
so that ... I don't have to manage the knowledge of common weather tasks

## Acceptance Criteria 
*List your requirements.*
- [ ] Remove GetForecast entity
- [ ] Add Weather.QueryWeather prebuilt entity
- [ ] GetForecast mapping logic should be refactored to QueryForecast entity
- [ ] Add Weather.CheckWeatherValue prebuilt entity
- [ ] Add Weather.CheckWeatherTime prebuilt entity
- [ ] Add Weather.ChangeTemperatureUnit prebuilt entity
- [ ] Add Weather.GetWeatherAdvisory prebuilt entity

## Resources
*Provide any screenshots or conversation mockups to support your request.*
*Learn how to mock up bot conversations with [.chat files](http://aka.ms/bfchatfile).*
https://docs.microsoft.com/en-us/azure/cognitive-services/luis/luis-reference-prebuilt-domains#weather

## Notes
*Provide any additional information.
Update the Weather Skill to use the more fully featured [Weather Pre-Built Domain](https://github.com/microsoft/luis-prebuilt-domains/tree/master/PrebuiltModels/Weather) which is also localised to multiple languages. 
This will enable the Weather skill to be offered as a more fully featured non-experimental skill.

Most prebuilt intents can be unused but enabled to help drive further skill refinement.

**Comment by ryanisgrig** [comment]
I believe when this was created there were bugs in the botbuilder tools that prevents publishing with the prebuilt domain, but the manual LUIS app created is using the same intent that comes with that domain to prepare for this.
