### ISSUE TITLE
Move items in solutions directory to samples

### ISSUE THREAD

**Issue by ryanisgrig** [microsoft/botframework-solutions#2161]
#### Is your feature request related to a problem? Please describe. 
We are setting the wrong expectations by having more advanced sample projects under a directory called "solutions" when in fact they should be viewed as samples.

#### What is the solution you are looking for?
Refactor to
```
\samples
    \analytics
        powerBi
    \android
        \virtualAssistantClient
        \eventCompanionApp
    \assistants
        \hospitalitySample
    \linkedaccounts
    \solutions
        \enterpriseNotifications
    \testharnesses
```

**Comment by lauren-mills** [comment]
Also, combine into fewer slns where possible
