### ISSUE TITLE
[Documentation] Broken Links

### ISSUE THREAD

**Issue by nroach** [microsoft/botframework-solutions#2162]
#### What project is affected?
[microsoft/botframework-solutions](https://github.com/microsoft/botframework-solutions)

#### What language is this in?
Markdown

#### What happens?

- On [Page Known Issues? - PLEASE READ!](https://github.com/microsoft/botframework-solutions/issues/1477) the link to [Known Issues](https://github.com/microsoft/botframework-solutions/blob/master/docs/reference/knownissues.md) results in a 404 not found.
- On Page [What's new at Build 2019](https://github.com/microsoft/botframework-solutions/wiki/What's-new-at-Build-2019), the [Heading Images](https://raw.githubusercontent.com/microsoft/AI/master/docs/media/skill-icon.png) for Skills Icons are broken links (404 not found).
- On Page [What's new at Build 2019](https://github.com/microsoft/botframework-solutions/wiki/What's-new-at-Build-2019) the link to [Virtual Assistant Template](https://aka.ms/convaivatemplate) uses a link shortener that no longer resolves properly, and redirects to the main microsoft website instead of a template specific page.
- On Page [What's new at Build 2019](https://github.com/microsoft/botframework-solutions/wiki/What's-new-at-Build-2019) the link to [these steps](hhttps://aka.ms/convaietmigration) uses a link shortener that no longer resolves properly, and redirects to the main microsoft website instead of a migration specific page.

#### What are the steps to reproduce this issue?
follow links listed above

#### What were you expecting to happen?
links should resolve to original locations, instead of resulting in 404 or redirects.

#### Can you share any logs, error output, etc.?
yes

#### Any screenshots or additional context?
yes, if not reproducible.  was reproducible for me on multiple systems.

**Comment by lauren-mills** [comment]
Links have been updated. Thanks for reporting!
