### ISSUE TITLE
Create Demo Scripts

### ISSUE THREAD

**Issue by Dewain27** [microsoft/botframework-solutions#2165]
## User Story
As ... bot user
I want ... to see sample transcripts of using the VA
so that ... I can easily refer others to understand how to showcase it's capabilities

## Acceptance Criteria 
*List your requirements.*
- [ ] ...
- [ ] ...
- [ ] ...

## Resources
*Provide any screenshots or conversation mockups to support your request.*
*Learn how to mock up bot conversations with [.chat files](http://aka.ms/bfchatfile).*

## Notes
*Provide any additional information.*
Demo Scripts for the following scenarios:

* Audio only
* Threaded Conversation
* Connected Vehicle Demo
* Echo Show-like Experience

**Comment by xieofxie** [comment]
Many transcripts would have images (both in skill itself or hosted on 3rd parties), should we convert all of them to data uri (quality may go down)?

Or leave 3rd parties one as it is, convert ones in skill to raw.githubusercontent.com?

Or leave 3rd parties one as it is, leave ones in skill in localhost (so when user runs the skill, they could view it)?

@Dewain27 @elaine-chang What do you think?

**Comment by xieofxie** [comment]
It seems that converting to jpg data uri is enough for transcripts..
Just note it is VA..

**Comment by darrenj** [comment]
addressed
