### ISSUE TITLE
Modify update_cognitive_models script to support build pipeline requirements

### ISSUE THREAD

**Issue by lauren-mills** [microsoft/botframework-solutions#2171]
## User Story
**As** bot developer
**I want** the update_cognitive_models script to be able to create a dispatch from my config if it doesn't exist
**so that** I can use it in my CI/CD pipeline

## Acceptance Criteria 
*List your requirements.*
- [ ] ...
- [ ] ...
- [ ] ...

## Resources
*Provide any screenshots or conversation mockups to support your request.*
*Learn how to mock up bot conversations with [.chat files](http://aka.ms/bfchatfile).*

## Notes
*Provide any additional information.*

**Comment by darrenj** [comment]
Addressed
