### ISSUE TITLE
Make deploy.ps1 optional

### ISSUE THREAD

**Issue by BillStrait** [microsoft/botframework-solutions#2174]
#### Is your feature request related to a problem? Please describe. 
The deployment scripts have been a struggle here for months. Maybe I'm just not clever enough to use them, or maybe they're not clever enough to account for various hurdles in place at my organization. The deploy_cognitive script could still be used for AI setup/updates, but doing the entire deployment through scripting doesn't seem viable here.

#### What is the solution you are looking for?
A simple, step by step, manual deployment guide. Azure command line tools seems to be an endless struggle at my organization, and it doesn't look like it'll get better.

#### What alternatives have you considered?
I'm about to begin the process of forging my own path for deployment by manually performing the actions the script takes, but I predict something will break the intended patch flow in the future. 

#### Is there any other context you can provide?
The ARM has put the following requirements in place that have resulted in meetings that may/may not have gotten the access I need to use this tool: manually create app ids and password, deleting the old bot and deploying a new one, updating app id for Skype for Business integration. 

I'm about 12 hours into trying to use the parameters.template.json file, and it's not working with no indication as to why. 

I appreciate the ideas behind the new approach, but for me/my organization, it has proven unwieldy. The previous versions of the framework were not difficult to deploy, and the ask for security and infrastructure were a lot easier to articulate. I'm not sure why we're fixing the unbroken.

**Comment by lauren-mills** [comment]
Hi @BillStrait - I have a rough list of steps here, and this item is already in the backlog to add to the official docs. Hope it helps!

https://github.com/microsoft/botframework-solutions/issues/1509

**Comment by lauren-mills** [comment]
As for your comments around complexity and ease of deployment, etc. The Virtual Assistant template is by design a more complicated solution including many pre-built language models and dependencies on external services. If you'd like something simpler there are other bot framework templates and samples I can point you to that reduce complexity, but have fewer features.

**Comment by BillStrait** [comment]
Thanks Lauren. I'll have to look into what "Deploy ARM template using Azure Portal" means in practice, but maybe I can get where I'm going that way. I'm pretty sure I just want "Create an App and give it X y and Z permissions in Azure AD. Create LUIS for handling intents, put name, id and key in cognitive_services.json. Create another application in LUIS for dispatch .... " 

The complexity seems to be around deploying the various models, and maybe configuration of the application in AAD (which doesn't seem to work correctly in my environment, but it proceeds without error). 

The end goal for us is access to skills. I, like the person in #1509, am not great with Powershell and in my instance I had many errors to overcome, most that were unrelated to the actual problem (permissions issues, in my scenario). If I get time I'll try to get bug reports/solutions in for those as a method of understanding powershell/Azure CLI better. 

The complexity isn't what's stopping the show for me. From the bot side of things I (mostly) understand it and can work with it. I found the deployment process to be a little... inflexible. I'm not sure I'll ever get it to deploy at the office via the script, but I can deploy fine at home to my personal Azure account. 

If I had a list of every permission the deploying user, and every permission the app needed to run that I could take to Security and Infrastructure teams up front, I might have had more success with this script. That seems like a herculean task from where I sit, but maybe you know of a better way.

**Comment by darrenj** [comment]
Hi Bill,

Out of interest, had you previously used msbot and associated tools for deployment? The move towards ARM is to bring us inline with the rest of the Azure Services to have a consistent way of performing deployment and give people full control over deployment if they so wish - e.g. to choose different pricing tiers, regions, use existing resources, etc.

In case it helps there are some guides on ARM [here](https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-overview) and [here](https://channel9.msdn.com/Series/Building-Infrastructure-in-Azure-using-Azure-Resource-Manager/Introduction-to-Azure-Resource-Manager).

The deploy.ps1 is to collect configuration information/region/etc. and bootstrap ARM for you, then kick off the cognitive model work. We did have this as manual steps early in Enterprise Template but it ended up being error prone hence the automation approach which then enables CI/CD.

Some organisations do restrict what you can create hence the ability to provide a resourceGroupName, AppId and Password provided by say your admin/security team. If you can share the deployment log files (in your deployment folder) that could help us to understand what issues your running into as our telemetry shows the approach is working more broadly - but happy to help refine it further.

If it helps there is a simpler way to get started through [Bot Builder Samples](https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore) and [CoreBot](https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/13.core-bot) specifically. This still uses ARM but doesn't have all of the additional capabilities of Virtual Assistant which might be a better fit for you?  Manual deployment steps [here](https://docs.microsoft.com/en-gb/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0)

**Comment by BillStrait** [comment]
Hey Darren,

I did not use any tools for deployment previously. I simply published after creating the required resources via the GUI. In my private set up I had this working with Dev Ops CI/CD. Professionally deployment was manual via Visual Studio. 

I'll take at the resources you provided. Thanks.

**Comment by lauren-mills** [comment]
Closing this since the issue is already tracked in #1509.
