### ISSUE TITLE
[Calendar] Calendar Skill "Find an Event by Time" supported scenario not implemented

### ISSUE THREAD

**Issue by lshade** [microsoft/botframework-solutions#2177]
## User Story
As a ... bot user
I want ... to find when/where/who/what of a meeting in a more complex context
so that ... I can have complex conversation

## Acceptance Criteria 
*List your requirements.*
- [ ] Support the meeting search of specific condition
- [ ] Return time/location/duration/attendee of the meeting

## Resources
*Provide any screenshots or conversation mockups to support your request.*
*Learn how to mock up bot conversations with [.chat files](http://aka.ms/bfchatfile).*

User says:
      - What day is Lego Land scheduled for?
      - Where is my meeting with Kayla?
      - Who am I meeting at 10 AM tomorrow?
      - What’s the duration of my 4 PM meeting?

## Notes
*Provide any additional information.*

#### What project is affected?

Calendar Skill

#### What language is this in?

C#

#### What happens?

After deploying the Calendar Skill and trying the utterance "What day is Lego Land scheduled for?" from the ["Find an Event by Time" supported scenario](https://microsoft.github.io/botframework-solutions/reference/skills/productivity-calendar/), the bot responds with "You have 1 event planned for today, it is with..." instead of when the Lego Land meeting is on my calendar.

#### What are the steps to reproduce this issue?

Add a "Lego Land" meeting to your calendar and try the utterance "What day is Lego Land scheduled for?" in a deployed Calendar Skill.

#### What were you expecting to happen?

I was expecting the skill to tell me when the meeting is on my calendar, but it responded with the general overview of my schedule for today.

**Comment by michelle9bah** [comment]
Hi, have you already solved this problem?

**Comment by KayMKM** [comment]
fixed
