### ISSUE TITLE
Versioning for skills

### ISSUE THREAD

**Issue by rggammon** [microsoft/botframework-solutions#2180]
#### Is your feature request related to a problem? Please describe. 
I am helping out with Salem's project - there is a need for a skill versioning story, and we are operating under the belief that the manifest will have a version field. There also seems to be an expectation of a privacyPolicy field.

#### What is the solution you are looking for?
A versioning story for skills, and feedback on whether privacy policy should be part of the manifest, or perhaps tied to the AAD app registration of the skill.

#### What alternatives have you considered?
Version could also go in the url. Privacy policy link could come from AAD.

#### Is there any other context you can provide?
Thank you for your feedback! If you have other ideas on how versioning should work, I would love to hear it.

Recall that we are using skills in an event-triggered way & authored into dialogs. We do not trigger skills by utterance unfortunately. We expect that the skill developer will want to run 2 skills side by side, while the bot author updates dialogs in the bot over to the new skill.

**Comment by darrenj** [comment]
Thanks Ryan - we're actually about to update the manifest schema in partnership with the SDK team so this will be part of that. Sorry for the confusion!
