### ISSUE TITLE
[BotSkills] Incorrect error message when missing microsoftAppId

### ISSUE THREAD

**Issue by DingmaomaoBJTU** [microsoft/botframework-solutions#2182]
#### What project is affected?
[BotSkills]
#### What happens?
When connect to a skill without microsoftAppId using botskills tool, an incorrect error message prompt like this:
There was an error while connecting the Skill to the Assistant:
StatusCodeError: 500 - "Value cannot be null.\r\nParameter name: appId"

#### What are the steps to reproduce this issue?
1. Publish a skill with microsoftAppId = ""
2. Connect to this skill using: 
botskills connect --botName bfva-dev --remoteManifest "***" --luisFolder ..\..\..\..\..\Resources\LU\en\ --cs --noRefresh

#### What were you expecting to happen?
Prompt the right error message "Value cannot be null.\r\nParameter name: microsoftAppId"

**Comment by Batta32** [comment]
Hi @DingmaomaoBJTU, thanks for reporting this issue!

Can you provide us the following information?
- The execution log
- A capture of your terminal with the `botskills connect` command

Also, we created PR #1983 adding the `msaAppId` attribute for `ISkillManifest` interface but it was merged in `next`. We will cherry pick the commit into `master`. We will try to reproduce the error and get back to you later.

**Comment by Batta32** [comment]
@DingmaomaoBJTU, can you check the version of `botskills` that you are using? We tried to reproduce the issue (`botskills` version 1.0.9 from [npm](https://www.npmjs.com/package/botskills)) using a `skillManifest` without the `microsoftAppId` which we connected to a `Virtual Assistant` and finished successfully.

![image](https://user-images.githubusercontent.com/11904023/63621406-37b22c00-c5ca-11e9-873c-1f56c7e53ba1.png)

![image](https://user-images.githubusercontent.com/11904023/63621412-3da80d00-c5ca-11e9-8ea4-3da2837d6950.png)

**Comment by darrenj** [comment]
No repro
