### ISSUE TITLE
[Skills] Calendar skill refactoring per user feedback

### ISSUE THREAD

**Issue by bobokids** [microsoft/botframework-solutions#2183]
## User Story
As ...
I want ...
so that ...

## Acceptance Criteria 
*List your requirements.*
- [ ] #2399 
- [ ] #2398 
- [ ] #2397
- [ ] #2396
- [ ] #2395
- [ ] #2394
- [ ] #2393
- [ ] #2316

## Resources
*Provide any screenshots or conversation mockups to support your request.*
*Learn how to mock up bot conversations with [.chat files](http://aka.ms/bfchatfile).*

## Notes
*Provide any additional information.*

#### Is your feature request related to a problem? Please describe. 
We gather user feedback and tune the flow accordingly.

#### What is the solution you are looking for?
1. Handling cases like "book a meeting with my manager"

<more to come>

**Comment by ryanisgrig** [comment]
@bobokids will you keep this issue for all "user feedback" items that we collect or is this for the scenario named so far? I'll have more items to add next week

**Comment by bobokids** [comment]
@ryanlengel yes, we can use this item for more user feedback.

**Comment by bobokids** [comment]
[https://github.com/microsoft/botframework-solutions/issues/2177](url)

**Comment by bobokids** [comment]
[https://github.com/microsoft/botframework-solutions/issues/2316](url)

**Comment by bobokids** [comment]
#2399 #2398 #2397 #2396 #2395 #2394 #2393 #2316

**Comment by lauren-mills** [comment]
There seems to be a lot of overlap between the individual works items here, for example #2394 and #2397 seem to be the same. It would be good to consolidate where possible.

**Comment by bobokids** [comment]
Tracked by individual issues.
