### ISSUE TITLE
Provider user with available Skills/commands

### ISSUE THREAD

**Issue by darrenj** [microsoft/botframework-solutions#2199]
## User Story
As ... a bot developer
I want ... to provide context on the Virtual Assistant's connected Skills
so that ... my users can learn what their VA can help them with

## Acceptance Criteria 
*List your requirements.*
- [ ] Add support utterances like "what can you do"
- [ ] If a user triggers the LUIS utterance above, respond in conversation with capabilities
- [ ] Add support for a client to send an event activity to trigger a similar reponse
- [ ] If a client triggers the event above, return an event back with enough context for the client to present this to a user

## Resources
*Provide any screenshots or conversation mockups to support your request.*
*Learn how to mock up bot conversations with [.chat files](http://aka.ms/bfchatfile).*

## Notes
*Provide any additional information.*

When you launch the Android App you don't receive an Intro Card to introduce the user. We should explore a Speech friendly introduction for first time?

Additionally, it's hard for a user to know what the VA/Skills can do. Perhaps we have an option on the flyout panel for suggested questions. Something on the canvas (i.e. intro card as above).

**Comment by ryanisgrig** [comment]
I think an introduction would be acceptable on a brand new user (it should remain brief), but returning users there are a couple of options:
1. Nothing
2. Visual change on UI but no speech

Would a client get the suggested questions as an event activity from the VA?

**Comment by Dewain27** [comment]
Please add support to the utterance of "What can you do?"

**Comment by chschrae** [comment]
Ideally this would be an event like activity that the client could ask for, that way the client app could request it programmatically whenever they feel necessary.

**Comment by ryanisgrig** [comment]
FYI @emivers8, this seem related to FTUE

**Comment by darrenj** [comment]
@emivers8 Yes - this is part of the onboarding, ongoing experience of discovering what a Bot can do and when it's updated how you let the user know.
