### ISSUE TITLE
[POI] Support scenario where user can search for different POIs than results shown

### ISSUE THREAD

**Issue by ryanisgrig** [microsoft/botframework-solutions#2212]
## User Story
As ...
I want ...
so that ...

## Acceptance Criteria 
*List your requirements.*
- [ ] ...
- [ ] ...
- [ ] ...

## Resources
*Provide any screenshots or conversation mockups to support your request.*
*Learn how to mock up bot conversations with [.chat files](http://aka.ms/bfchatfile).*

Support conversations like:
User: find a coffee shop
Skill: here are some coffee shops
User: find a pharmacy
Skill: here are some pharmacies
User: find a KEYWORD
Skill: here are some KEYWORD

## Notes
*Provide any additional information.*
The POI Skill should be more flexible in continually searching for new POIs if a user asks without being stuck on what they uttered previously.

**Comment by lauren-mills** [comment]
@ryanlengel - please update the user story and requirements
