### ISSUE TITLE
VA.Timezone slot should use a relative UTC integer instead of timezone name

### ISSUE THREAD

**Issue by ryanisgrig** [microsoft/botframework-solutions#2220]
## User Story
As ...
I want ...
so that ...

## Acceptance Criteria 
*List your requirements.*
- [ ] ...
- [ ] ...
- [ ] ...

## Resources
*Provide any screenshots or conversation mockups to support your request.*
*Learn how to mock up bot conversations with [.chat files](http://aka.ms/bfchatfile).*

## Notes
*Provide any additional information.*

#### Is your feature request related to a problem? Please describe. 
It is unclear what timezone names should be sent with the VA.Timezone event and it leaves room for error to use a formatted string. For example, on the US east coast it is currently Eastern Daylight Time but that does not work (Eastern Standard Time does).

#### What is the solution you are looking for?
VA.Timezone event should use a positive/negative integer relative to the UTC timezone. For example, Eastern DaylightTime:-4.

**Comment by KayMKM** [comment]
@ryanlengel As your example, there are many timezone are in UTC-4. So it is hard to convert UTC-4 to user's timezone without his location. And according to my understanding, if convert it to a UTC-4 timezone in US, but the user is in a location that is not using summer time. It will be wrong time when summer time changed.

**Comment by darrenj** [comment]
Update?
