### ISSUE TITLE
[Future] Use Adaptive Card templating library if appropriate

### ISSUE THREAD

**Issue by ryanisgrig** [microsoft/botframework-solutions#2228]
## User Story
As ... a bot developer
I want ... to use the official Adaptive Cards 2.0 templating methods
so that ... I have a consistent pattern of separating the visual and data layers of my cards

## Acceptance Criteria 
*List your requirements.*
- [ ] Validate that LG card templates matches the feature set of Adaptive Cards templates
- [ ] Replace implementation in Calendar Skill
- [ ] Replace implementation in Email Skill
- [ ] Replace implementation in To Do Skill
- [ ] Replace implementation in Point of Interest Skill
- [ ] Replace implementation in Hospitality Skill
- [ ] Replace implementation in Automotive Skill
- [ ] Replace implementation in Search Skill
- [ ] Replace implementation in Weather Skill
- [ ] Replace implementation in Events Skill

## Resources
*Provide any screenshots or conversation mockups to support your request.*
*Learn how to mock up bot conversations with [.chat files](http://aka.ms/bfchatfile).*

## Notes
*Provide any additional information.*
#### Is your feature request related to a problem? Please describe. 
Each Skill has their own unique variables that are filled in Adaptive Cards, in the 2.0 release they are targeting a templating language that enables the separation of data from the view of a card.
They are targeted to release an alpha library of the templating language that is compatible with Adaptive Card 1.1. Skills should use this library so we can provide early feedback and clean up our code to a standardized format.

#### What is the solution you are looking for?
See the feasibility of the templating language library on the future branch.

#### Is there any other context you can provide?
[Templating language overview](https://github.com/microsoft/AdaptiveCards/issues/2448)
[.NET templating alpha library PR](https://github.com/microsoft/AdaptiveCards/pull/3239)

**Comment by darrenj** [comment]
Update?
