### ISSUE TITLE
Create a Widget that looks like the conversation UI

### ISSUE THREAD

**Issue by Dewain27** [microsoft/botframework-solutions#2237]
## User Story
As ... a bot user
I want ... a widget of my conversation with my VA
so that ... I can put it side by side with widgets from the Event Companion app that easily show a conversation's actions being fulfilled

## Acceptance Criteria 
- [ ] UI honors app setting of only showing the Responses or the full Conversation view
- [ ] UI is responsive and resizes to the size of the widget
- [ ] UI includes a Mic Button that is active to enable the voice conversation, but does not include the typing interface
- [ ] UI supports dark and light mode options
- [ ] UI uses the color settings from the setting within the main application
- [ ] UI renders adaptive cards the same as in the main application

## Resources
*Provide any screenshots or conversation mockups to support your request.*
*Learn how to mock up bot conversations with [.chat files](http://aka.ms/bfchatfile).*

**Widget sample where user has light background with full conversation showing.**
![image](https://user-images.githubusercontent.com/43043272/65731932-8563fd80-e07c-11e9-888b-3915ac01db40.png)

**Widget sample of bot response**
![image](https://user-images.githubusercontent.com/43043272/65731991-b2181500-e07c-11e9-91b8-b6b0925f364d.png)

**Widget sample of user request**
![image](https://user-images.githubusercontent.com/43043272/65732059-f4415680-e07c-11e9-8bb9-3b836681b284.png)

## Notes
*Provide any additional information.*
Widget should look just like the application UI.   Application will need to honor the dark / light mode setting.  Adaptive Cards should render as well.

Receive/Response widgets should also honor the bubble/text colors selected in settings.

**Comment by Dewain27** [comment]
@ryanlengel please review the requirements and let me know if you have any additional questions or feel that any clarity is not provided.

**Comment by darrenj** [comment]
Let's not re-create webchat canvas!!
