### ISSUE TITLE
problems deploying luis model - todo skill

### ISSUE THREAD

**Issue by tamerin-tech** [microsoft/botframework-solutions#2254]
#### What project is affected?
I'm trying to deploy the recent TODO skill sample as is, everything seems fine but then I get

> 
> ! Could not deploy LUIS model. Review the log for more information.
> ! Log: ...\todoskill\Deployment\Scripts\..\deploy_cognitive_models_log.txt
> > Setting LUIS subscription key ...
> ! Could not create LUIS app. Skipping dispatch add.

in the log file I see:

> The apps - Import application Operation under LUIS Programmatic APIs v2.0 API is not supported with the current subscription key and pricing tier LUIS.S0.

I did the same couple of weeks ago and it went fine. was something changed?

I notice that in the deployment script for luis it uses the same key for authoring and as subscription key, it that correct?

>     $luisApp = (luis import application `
>         --appName $appName `
>         --authoringKey $luisAuthoringKey `
>         --subscriptionKey $luisAuthoringKey `
>         --region $region `
>         --in "$(Join-Path $outFolder $outFile)" `
>         --wait) 2>> $log | ConvertFrom-Json

**Comment by lauren-mills** [comment]
Hi @tamerin-tech, I can confirm that using the authoringKey for both fields during import is correct, we apply the Azure Subscription Key after we import. 

I've assigned support to help troubleshoot further.

**Comment by tamerin-tech** [comment]
Hi @lauren-mills , @dmvtech , we can close this issue. it seems to work now when I follow the instructions of https://github.com/microsoft/botframework-solutions/issues/2074
Thanks anyway

**Comment by zzhang115** [comment]
this issue maybe you already create a Luis App in "https://www.luis.ai/applications", you can delete them if needs, then issue solved.
