### ISSUE TITLE
Virtual Assistant - Attachment Prompt does not move to next step in the Waterflow Steps

### ISSUE THREAD

**Issue by ktmanikanta** [microsoft/botframework-solutions#2259]
Hi,
I have created a sample project using Virtual Assistant Template and in OnboardingDialog, I have added an AttachmentPrompt, in the existing Waterfall Steps. However, after attaching the document, it is not moving to next step. The same code works fine in Enterprise Bot Template.

Pasting below my code. After PromptForImage step, the control does not go to ProcessImage step.
```
    public class OnboardingDialog : ComponentDialog
    {
        private static OnboardingResponses _responder = new OnboardingResponses();
        private IStatePropertyAccessor<OnboardingState> _accessor;
        private OnboardingState _state;

        public OnboardingDialog(
            BotServices botServices,
            UserState userState,
            IBotTelemetryClient telemetryClient)
            : base(nameof(OnboardingDialog))
        {
            _accessor = userState.CreateProperty<OnboardingState>(nameof(OnboardingState));
            InitialDialogId = nameof(OnboardingDialog);

            var onboarding = new WaterfallStep[]
            {
                AskForName,
                PromptForImage,
                ProcessImage,
                FinishOnboardingDialog,
            };

            // To capture built-in waterfall dialog telemetry, set the telemetry client
            // to the new waterfall dialog and add it to the component dialog
            TelemetryClient = telemetryClient;
            AddDialog(new WaterfallDialog(InitialDialogId, onboarding) { TelemetryClient = telemetryClient });
            AddDialog(new TextPrompt(DialogIds.NamePrompt));
            AddDialog(new AttachmentPrompt(DialogIds.ImagePrompt));
        }

    

        public async Task<DialogTurnResult> AskForName(WaterfallStepContext sc, CancellationToken cancellationToken)
        {
            _state = await _accessor.GetAsync(sc.Context, () => new OnboardingState());

            if (!string.IsNullOrEmpty(_state.Name))
            {
                return await sc.NextAsync(_state.Name);
            }
            else
            {
                return await sc.PromptAsync(DialogIds.NamePrompt, new PromptOptions()
                {
                    Prompt = await _responder.RenderTemplate(sc.Context, sc.Context.Activity.Locale, OnboardingResponses.ResponseIds.NamePrompt),
                });
            }
        }

        private async Task<DialogTurnResult> PromptForImage(WaterfallStepContext sc, CancellationToken cancellationToken)
        {
            return await sc.PromptAsync(DialogIds.ImagePrompt, new PromptOptions()
            {
                Prompt = await _responder.RenderTemplate(sc.Context, sc.Context.Activity.Locale, OnboardingResponses.ResponseIds.PromptForImage),
            });
        }

        private async Task<DialogTurnResult> ProcessImage(WaterfallStepContext sc, CancellationToken cancellationToken)
        {
			_state = await _accessor.GetAsync(sc.Context, () => new OnboardingState());
			await _responder.ReplyWith(sc.Context, OnboardingResponses.ResponseIds.HaveNameMessage);
            return await sc.NextAsync(_state.Name);
        }

        public async Task<DialogTurnResult> FinishOnboardingDialog(WaterfallStepContext sc, CancellationToken cancellationToken)
        {
            _state = await _accessor.GetAsync(sc.Context, () => new OnboardingState());
            var name = _state.Name = (string)sc.Result;
            await _accessor.SetAsync(sc.Context, _state, cancellationToken);

            await _responder.ReplyWith(sc.Context, OnboardingResponses.ResponseIds.HaveNameMessage, new { name });
            return await sc.EndDialogAsync();
        }

  

        private class DialogIds
        {
            public const string NamePrompt = "namePrompt";
            public const string ImagePrompt = "imagePrompt";
        }
    }
```

**Comment by xieofxie** [comment]
Yeah, it is very interesting.. Virtual Assistant uses the RouterDialog from Microsoft.Bot.Builder.Solutions and it starts to check whether text is IsNullOrEmpty from 4.4(#1271) and this check is removed by another reason recently (#2069).

While Enterprise Bot Template uses the RouterDialog in its own folder.

When uploading an attachment, text is empty. So it works in Enterprise Bot Template and does not work in VA.

If you would like to use VA, I would suggest to copy the RouterDialog.cs from master and modify the [line](https://github.com/microsoft/botframework-solutions/blob/9d5ae31848252fc408fbc6098f49ac3b59c74117/lib/csharp/microsoft.bot.builder.solutions/microsoft.bot.builder.solutions/Dialogs/RouterDialog.cs#L55) to skip check.

Or wait until the fix is released.

@lauren-mills What's your idea?

**Comment by ktmanikanta** [comment]
I just remembered that I have added the below lines (In Bold) in RouterDialog.cs of Enterprise Bot Template in OnContinueDialogAsync method when I was working back on 5 months ago. 

 switch (activity.Type)
                {
                    case ActivityTypes.Message:
                        {                            
                            if (activity.Value != null)
                            {
                                await OnEventAsync(innerDc).ConfigureAwait(false);
                            }
                            else if (!string.IsNullOrEmpty(activity.Text))
                            {
                            --
                            --
                            }
                            **else if (activity.Attachments != null && activity.Attachments.Count > 0)
                            {
                                await innerDc.ContinueDialogAsync().ConfigureAwait(false);
                                break;
                            }**

Thanks @xieofxie and @lauren-mills. I will copy RouterDialog.cs and add the above fix again until the fix is released.

**Comment by lauren-mills** [comment]
Thanks, @ktmanikanta! We have a work item here to redesign RouterDialog based on some other feedback we've received so please track it here #2263

**Comment by darrenj** [comment]
Router Dialog is updated - please checkout the changes and let us know if you have any other questions.

**Comment by AntonFLB** [comment]
Hello,

i am using the latest version of the bot framework and getting following error:
- uploading an attachment over an AttachmentPrompt dialog
- error occurs in: GeneralLuis.cs at line 65 (JsonConvert.DeserializeObject<GeneralLuis>(JsonConvert.SerializeObject(result))) cause of result.Text is a null value

Thats so far logical, cause i send the attachment without any text input. Any help will be nice.

Thanks,
Anton

**Comment by xieofxie** [comment]
I am afraid you have to modify the code to skip Luis for empty texts.. In [sdk](https://github.com/microsoft/botbuilder-dotnet/blob/e0dd518bb3446d010551bf4a7d38d4e5e6cfcd9c/libraries/Microsoft.Bot.Builder.AI.LUIS/LuisRecognizer.cs#L348), it will return Empty intent for empty text instead of None intent, so it could not be recognized. It may [not change](https://github.com/microsoft/botbuilder-dotnet/issues/2174) any way..

**Comment by AntonFLB** [comment]
Hi xieofxie,

thanks for advice, i will do so for the moment. It fixed the issues, but cost a lot of time and nerves.
I hope in V5 it will be better. The circumstance that a new Dialog Type "AttachmentPrompt" is available but the MessageType of it is also "message" is a little bit confusing.

Thanks again :)
Anton
