### ISSUE TITLE
Adding .netframework v4 (4.7.1) as a skill to virtual assistant bot framework

### ISSUE THREAD

**Issue by RajaniJillaGit** [microsoft/botframework-solutions#2260]

**Comment by daveta** [comment]
Hi @RajaniJillaGit : Thanks for reporting the issue!  I've assigned to our solutions team and they will respond shortly.

**Comment by lauren-mills** [comment]
HI @RajaniJillaGit , this is likely a package version issue. Can you let me know which version of the skills and solutions packages you're installing? Thanks!

**Comment by RajaniJillaGit** [comment]
Hi Lauren, 

Both skills and solutions package versions are 4.5.3.

**Comment by lauren-mills** [comment]
Thanks @RajaniJillaGit! I've added our Support team to help troubleshoot further.

**Comment by lauren-mills** [comment]
HI @RajaniJillaGit - sorry for the late response here. We just pushed out some new package versions for Skills and Solutions packages. If you're still having this issue, can you try them out and let me know if it helps at all?

**Comment by darrenj** [comment]
Let us know if you still have problems on this issue.
