### ISSUE TITLE
Adaptive Cards integration

### ISSUE THREAD

**Issue by ryanisgrig** [microsoft/botframework-solutions#2261]
- [x] A user should be able to interact with the clickable containers/columns on Adaptive Cards
**Currently only a root-level select action is enabled**
- [x] Default card appearance should be transparent and use the background of the bot bubble color
*Right now it is always white, no matter the `app:cardBackgroundColor` set on item_adaptive_card.xml*
- [x] Replace the `hostconfig.json` with empty {} to use default values
- [x] Investigate and potentially replace the HorizontalScrollView/LinearLayout implementation that allows for carousel Adaptive Cards with a RecyclerView (https://www.android-examples.com/android-horizontal-recyclerview-cardview/), not sure if this is causing an issue with the current rendering.
- [x] Adaptive Cards should be rendered in separate bubbles from their related text. This will let us scale the card view independent of related messages. See the BF Emulator for an example of how this looks
![image](https://user-images.githubusercontent.com/43043272/64044156-00d49c80-cb1b-11e9-9f6d-76b0d9ebd6aa.png)

**Comment by chon219** [comment]
Opened another issue #2356 
Closing this one.
