### ISSUE TITLE
Skills not reporting FlowAggregate data when using websockets

### ISSUE THREAD

**Issue by negativeeddy** [microsoft/botframework-solutions#2262]
#### What project is affected?
Skills template

#### What language is this in?
C#

#### What happens?
The skills dialogs report the waterfallsteps but they are missing the ActivityId and ConversationID columns

#### What are the steps to reproduce this issue?
Create a VA with a skill (v4.5.1) and execute a skill dialog.
run this query in app insights

customEvents
| project 
ActivityId = customDimensions.activityId,
ReplyActivityId = customDimensions.replyActivityId , 
operation_Name = operation_Name ,
ConversationId = session_Id ,
Text =    customDimensions.text,
EventName = name, 
Time = timestamp, 
DialogStepName = customDimensions.StepName,
Date = timestamp,
DialogInstanceId = customDimensions.InstanceId,
DialogId = customDimensions.DialogId 
| where EventName startswith "Waterfall"
| order by Time desc 

#### What were you expecting to happen?
All columns have data (except the ReplyToActivityId it should be populated if ActivityId is not)

#### Can you share any logs, error output, etc.?

ActivityId | ReplyActivityId | operation_Name | ConversationId | EventName | Time | DialogStepName | Date | DialogInstanceId | DialogId
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
null | null | GET Bot/SkillMessageWebSocket | |WaterfallStep | 2019-08-30T19:57:26.2893741Z | DoGameStep | 2019-08-30T19:57:26.2893741Z | 715e1037-18ff-4a93-98e0-c2994c2bdd74 | GameFlow
null | null | GET Bot/SkillMessageWebSocket | |WaterfallStart | 2019-08-30T19:57:26.2892744Z | null | 2019-08-30T19:57:26.2892744Z | 715e1037-18ff-4a93-98e0-c2994c2bdd74 | GameFlow
null | null | GET Bot/SkillMessageWebSocket | |WaterfallStep | 2019-08-30T19:57:26.2150099Z | PlayGame | 2019-08-30T19:57:26.2150099Z | a3a5de2f-87bc-44ee-a199-9215a07f9cb4 | PlayGameDialog
null | null | GET Bot/SkillMessageWebSocket || WaterfallStep | 2019-08-30T19:57:26.1973326Z | PromptForGameName | 2019-08-30T19:57:26.1973326Z | a3a5de2f-87bc-44ee-a199-9215a07f9cb4 | PlayGameDialog
null | null | GET Bot/SkillMessageWebSocket | |WaterfallStart | 2019-08-30T19:57:26.1970418Z | null | 2019-08-30T19:57:26.1970418Z | a3a5de2f-87bc-44ee-a199-9215a07f9cb4 | PlayGameDialog

#### Any screenshots or additional context?
This is not the know issue. The Botservices, startup, and appsettings have all been updated. Also, if I hit the skill directly, the data flows in properly like this

ActivityId | ReplyActivityId | operation_Name | ConversationId | EventName | Time | DialogStepName | Date | DialogInstanceId | DialogId
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
LWra0Z4V7ZvLB41ogFmqe4-f\|0000004 | null | POST Bot/BotMessage | LWra0Z4V7ZvLB41ogFmqe4-f | WaterfallComplete | 2019-08-30T18:53:08.2644359Z | null | 2019-08-30T18:53:08.2644359Z | b9c43f9f-c790-45a8-b6a0-8237a07d851b | ListGamesDialog
LWra0Z4V7ZvLB41ogFmqe4-f\|0000004 | null | POST Bot/BotMessage | LWra0Z4V7ZvLB41ogFmqe4-f | WaterfallStep | 2019-08-30T18:53:06.8894769Z | ShowGames | 2019-08-30T18:53:06.8894769Z | b9c43f9f-c790-45a8-b6a0-8237a07d851b | ListGamesDialog
LWra0Z4V7ZvLB41ogFmqe4-f\|0000004 | null | POST Bot/BotMessage | LWra0Z4V7ZvLB41ogFmqe4-f | WaterfallStart | 2019-08-30T18:53:06.8894463Z | null | 2019-08-30T18:53:06.8894463Z | b9c43f9f-c790-45a8-b6a0-8237a07d851b | ListGamesDialog
LWra0Z4V7ZvLB41ogFmqe4-f\|0000000 | null | POST Bot/BotMessage | LWra0Z4V7ZvLB41ogFmqe4-f | WaterfallComplete | 2019-08-30T18:50:38.7649182Z | null | 2019-08-30T18:50:38.7649182Z | a77fa506-e3b1-4ebd-8111-3ff1f2cd6f1e | ListGamesDialog
LWra0Z4V7ZvLB41ogFmqe4-f\|0000000 | null | POST Bot/BotMessage | LWra0Z4V7ZvLB41ogFmqe4-f | WaterfallStep | 2019-08-30T18:50:38.4769264Z | ShowGames | 2019-08-30T18:50:38.4769264Z | a77fa506-e3b1-4ebd-8111-3ff1f2cd6f1e | ListGamesDialog
LWra0Z4V7ZvLB41ogFmqe4-f\|0000000 | null | POST Bot/BotMessage | LWra0Z4V7ZvLB41ogFmqe4-f | WaterfallStart | 2019-08-30T18:50:38.4505018Z | null | 2019-08-30T18:50:38.4505018Z | a77fa506-e3b1-4ebd-8111-3ff1f2cd6f1e | ListGamesDialog

**Comment by lauren-mills** [comment]
@negativeeddy - You said this had something to do with how the telemetry client is initialized, right? Do you have any more details? I think we'll need to get the SDK team involved to solve this

**Comment by ericmaino** [comment]
Agreed this appears to be more of a Framework issue. The TelemetryBotIdInitializer depends on the HttpContext which rightfully does not exist on a web socket response. 

You will see this in the following file around line 33. 

https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/integration/Microsoft.Bot.Builder.Integration.ApplicationInsights.Core/TelemetryBotIdInitializer.cs

The telemetry initialization is not an issue, though the bug the code was working around appears to have been addresses in a more recent release.

**Comment by lauren-mills** [comment]
We just verified that our demo environment, which is connecting to skills using websockets is correctly logging dialog data for our skills. 

**Edit**: seeing that same issue now.

**Comment by lauren-mills** [comment]
Fix for this is in next branch, and new doc explaining workaround for this is here: https://microsoft.github.io/botframework-solutions/help/knownissues/#skill-dialog-telemetry-is-not-showing-up-in-the-power-bi-dashboard
