### ISSUE TITLE
Better translation in library required

### ISSUE THREAD

**Issue by xieofxie** [microsoft/botframework-solutions#2265]
## User Story
As ...
I want ...
so that ...

## Acceptance Criteria 
*List your requirements.*
- [ ] ...
- [ ] ...
- [ ] ...

## Resources
*Provide any screenshots or conversation mockups to support your request.*
*Learn how to mock up bot conversations with [.chat files](http://aka.ms/bfchatfile).*

## Notes
*Provide any additional information.*

#### Is your feature request related to a problem? Please describe. 

Some of the translations are wrong in library.

#### What is the solution you are looking for?

Translating manually.

#### Is there any other context you can provide?

While lu files are machine-translated, it might be better translating strings in library manually.

**Comment by lauren-mills** [comment]
@xieofxie - can you add some more detail about which files need to be fixed? Thanks

**Comment by xieofxie** [comment]
@lauren-mills - For [example](https://github.com/microsoft/botframework-solutions/blob/next/lib/csharp/microsoft.bot.builder.solutions/microsoft.bot.builder.solutions/Feedback/FeedbackResponses.zh.resx), here [dismiss](https://dictionary.cambridge.org/dictionary/english/dismiss) is translated to "to remove someone from their job, especially because they have done something wrong" in Chinese, not "to decide that something or someone is not important and not worth considering".

I am afraid this might be a general issue in all translated strings in the library and we might check all of them carefully (well only ones in library are necessary, utterances or strings in skills might not worth the effort).

And do we need to set some flag to indicate some strings have been translated manually? So we could add new strings like machine-translated(no flag) -> when resource is available -> translate ones with no flag.

**Comment by darrenj** [comment]
Elaine - can you add this to you list, gathering all the LG response files and identifying resource(s), service(s), people that could help review and update LG responses?
