### ISSUE TITLE
deploy.ps1 file not found error when deploying azure resource

### ISSUE THREAD

**Issue by Robotbae** [microsoft/botframework-solutions#2271]
#### What project is affected?
Virtual Assistant

#### What language is this in?
Typescript 

#### What happens?
When running PS script deploy.ps1, I am able to create a resource but script fails at deploying azure resource and notes that ERRRNO2 file not found 

#### What were you expecting to happen?
Move on to the following step after deployment

**Comment by lauren-mills** [comment]
@robotbae - I've added our support team to help with further troubleshooting. Thanks.

**Comment by dmvtech** [comment]
@robotbae Can you share the full command for deployment you are running? Are you passing in all parameters, letting it prompt for parameters or using a parameters file? Can you also share the deploy_log.txt?

**Comment by Robotbae** [comment]
Sure so deploy_log.txt is : 

ERROR: Deployment '09052019114357' could not be found.
ERROR: Deployment '09052019114357' could not be found. 


The error message on Ps6 is : ERRNO2 could not find file …… template.json 
I open ps6, I cd to my project file and run  ./Deployment/Scripts/deploy.ps1

I am using it via letting it prompt for parameters e.g. LUIS region, LUIS token, name location, appPassword just as following https://microsoft.github.io/botframework-solutions/tutorials/typescript/create-assistant/4_provision_your_azure_resources/

**Comment by Robotbae** [comment]
Hello - the fix that was silly but much needed was repairing Azure cli. Script somehow worked after in terms of deploy. Now the error is npm run start 


Will add a new question and close this one
