### ISSUE TITLE
document link is broken

### ISSUE THREAD

**Issue by tamerin-tech** [microsoft/botframework-solutions#2272]
I tried to add the todo skill from the samples, I got this error:
Could not configure authentication connection automatically.
There was an error while executing the following command:
        az bot authsetting list -n bldemo -g bldemo${err}
You must configure one of the following connection types MANUALLY in the Azure Portal:
        Azure Active Directory v2
For more information on setting up the authentication configuration manually go to:
https://github.com/microsoft/botframework-solutions/blob/master/docs/howto/assistant/linkedaccounts.md#authentication-configuration

but the documentation link is broken...

**Comment by lauren-mills** [comment]
Thanks, @tamerin-tech we'll fix this link.

To get around this error, try providing the --resourceGroup parameter on the botskills connect command.

**Comment by dfavretto** [comment]
Hi @tamerin-tech,

The link was changed in #2015 to point to https://aka.ms/vamanualauthsteps, which resolves to the actual documentation. You can see this change [here](https://github.com/microsoft/botframework-solutions/blame/master/tools/botskills/src/utils/authenticationUtils.ts#L22).
The latest version ([1.0.9](https://www.npmjs.com/package/botskills/v/1.0.9)) already has this change implemented.

**Comment by darrenj** [comment]
Thanks all - please reopen if you need any more help.
