### ISSUE TITLE
[Docs] Getting LUIS Auth Key is confusing and could be started clearer

### ISSUE THREAD

**Issue by managedcoder** [microsoft/botframework-solutions#2274]
I was looking at the intro doc for creating a VA bot [here](https://microsoft.github.io/botframework-solutions/tutorials/csharp/create-assistant/1_intro/) where I see a bullet that says, "Once signed in replace your name in the top right hand corner.".  This is confusing and perhaps not worded well.  Shouldn't it say something like "Once signed in, click your initials in the uppermost righthand corner of the page (i.e. LUIS Profile menu option)"

-Russ

**Comment by lauren-mills** [comment]
Thanks, @managedcoder, we'll rephrase this.
