### ISSUE TITLE
Enterprise Bot Template Exception with Web Chat

### ISSUE THREAD

**Issue by brazierdavid** [microsoft/botframework-solutions#228]
**Project**
Enterprise Bot Template

**Description**
In Web Chat, after waking it up with "hi", get the welcome card and "What is your name?" then "Sorry, it looks like something went wrong.". 

**To Reproduce**
Created a new bot from the Enterprise template (4.0.5.29), works fine in emulator (development and production), but in Web Chat, after waking it up with "hi", get the welcome card and "What is your name?" then immediately (without waiting for input) "Sorry, it looks like something went wrong.". 

**Expected behavior**
As per behaviour in emulator, should wait for input after "What is your name?".

**Additional context**
I have found this is due to a MissingMemberException exception at the first line of OnboardingDialog.AskForEmail where it retrieves the state:

`_state = await _accessor.GetAsync(sc.Context); `

One odd thing is that the AskForName method is called before this and successfully gets the (empty) state, but then doesn't actually wait for a response.

Stack trace:
System.MissingMemberException: Property not set and no default provided. at Microsoft.Bot.Builder.BotState.BotStatePropertyAccessor`1.d__7.MoveNext() at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at EnterpriseBot.OnboardingDialog.d__8.MoveNext() in C:\dev\EnterpriseBot\EnterpriseBot\Dialogs\Onboarding\OnboardingDialog.cs:line 62 ...

**Comment by lauren-mills** [comment]
I'll check this out.

**Comment by lauren-mills** [comment]
In the short-term, if you change that line to this, it should keep it from breaking. I'd be curious to see how it responds though and if it is able to save the values in state.

` _state = await _accessor.GetAsync(sc.Context, () => new OnboardingState());`

**Comment by moonplanter** [comment]
I'm also having this error and have tried the change mentioned. It does move the 'Something went wrong error' to appear after I have entered my name rather than when I enter 'Hi'.

**Comment by ivlaevski** [comment]
I have the same problem. Tried to work around...
If you start the conversation with 'cancel' (if you have dialog interrupt implemented) it goes out to the main dialog and works fine... until you enter any other dialog that tries to get the state.
The problem may related to OnStartAsync override in MainDialog : RouterDialog not being triggered until message is received.
Using ngrok and connecting to the production environment with the emulator - the problem disappears.

**Comment by lauren-mills** [comment]
How are you testing with webchat? Are you using the test panel in the portal or creating your own?

**Comment by ivlaevski** [comment]
I was using version 4.1.1 of the components. 
Tried to update to 4.1.5 and it's not working at all - messages are crashing the application
Trying to find a reason - created a new project into new environment - [22:46:15]POST201directline.startConversation
[22:46:16]Refresh access token failed with status code: 401

The webchat was the standard one from channels:
`<iframe src='https://webchat.botframework.com/embed/Angelique?s=YOUR_SECRET_HERE'  style='min-width: 400px; width: 100%; min-height: 500px;'></iframe>`

**Comment by ivlaevski** [comment]
Maybe this is a different issue, but in connection the the above post:
After executing:
`msbot clone services --name "Angelique" --luisAuthoringKey "..." --folder "DeploymentScripts\msbotClone" --location "westus" --appId "1c147b6e-." --appSecret "qmn..."`
Infrastructure was created. But when I called:
`msbot list --bot Angelique.bot --secret "M14p3..."`
the appId was reported as a different one (something starting with "fb3a391e-") 
After I changed all appId-s back to the initial one - it all works on Emulator - both local and production

It still not works with webchat or with test panel in Azure.
(web chat is recording issues: There was an error sending this message to your bot: HTTP status code Forbidden)

**Comment by ivlaevski** [comment]
![image](https://user-images.githubusercontent.com/3420183/48444671-40551680-e79d-11e8-9731-41856dea6bb5.png)
This defenetly is a different issue - the appId is wrong and I can't change it - I don't have an application with this is.
This is why the comunication fails

**Comment by lauren-mills** [comment]
I was able to reproduce the issue and I'm debugging now. 

@ivlaevski would you mind opening a separate issue for the appId problem? It seems like a bug in the deployment process that we may need to forward to the botbuilder tools team

**Comment by GraniteStateHacker** [comment]
I'm actively fighting with the original issue now, exactly as described...  Onboarding state is fine in the emulator, but not in webchat.   Happy to help if I can.

**Comment by lauren-mills** [comment]
Ok, after debugging I was able to fix things on my end by moving to the new version of webchat (found at [https://github.com/Microsoft/botframework-webchat](https://github.com/Microsoft/botframework-webchat) using the following code:

```
    <div id="webchat"></div>
    <script src="https://cdn.botframework.com/botframework-webchat/preview/botchat.js"></script>
    <script>
        var bot = window.WebChat.createDirectLine({ secret: 'YOUR_DIRECTLINE_SECRET' });
        window.WebChat.renderWebChat({
            directLine: bot
        }, document.getElementById('webchat'));

        // This code sends an event which triggers the ConversationUpdate message
        bot.postActivity({
            from: { id: "default-user"},
                name: 'startConversation',
                type: 'event',
                value: ''
            })
            .subscribe(function (id) {
                console.log('trigger "startConversation" sent');
            });
    </script>
```

And by changing all instances of  `_state = await _accessor.GetAsync(sc.Context);` in the OnboardingDialog to ` _state = await _accessor.GetAsync(sc.Context, () => new OnboardingState());`

Can one of you try these changes out and see if they work for you?

**Comment by GraniteStateHacker** [comment]
I'll take a crack at it right now.  Thanks!

**Comment by GraniteStateHacker** [comment]
The old webchat used a token that looks different from your secret.  Where does one acquire such a secret?

**Comment by lauren-mills** [comment]
You go to the channels tab in the Azure Portal and add the Directline channel. It uses that secret

**Comment by GraniteStateHacker** [comment]
Ok... same token, just looked radically different to me... guess it should.  :)

Tried updating the client side code...  I like how it kicks the bot to start the conversation.  

I'm a little leery of whipping up an empty state object at the point were this does, but it seems to get us past the error...  thanks!

**Comment by ivlaevski** [comment]
![image](https://user-images.githubusercontent.com/3420183/48448632-53b9af00-e7a8-11e8-97bd-6f3903b566f5.png)
It's not keeping the state - there is no error, but no data also.

**Comment by ivlaevski** [comment]
I will try this approach also... For now what i see is that it keeps the state until browser refresh - I don't know how shall it behaive, but after refresh it is asking for Name - it dosn't remember me.

**Comment by lauren-mills** [comment]
@ivlaevski that is to be expected. The web chat experience does not persist across sessions unless the driving web page configures a specific user id. If you have more questions about how to extend webchat they have a very active repo with documentation of a lot of scenarios here: https://github.com/Microsoft/botframework-webchat. I'm sure they'd be happy to help with specifics!

**Comment by lauren-mills** [comment]
These bugs are resolved in the latest version of the Enterprise Template in the marketplace and in the EnterpriseBotSample here: https://github.com/Microsoft/AI/tree/master/templates/Enterprise-Template/src/csharp/EnterpriseBotSample

Closing for now, we can reopen if needed.

**Comment by jawand** [comment]
@lauren-mills can you point out what is changed in the above mentioned template. As we are using old template and cannot afford to move to this one right now. and we need this fix. 

Thanks

**Comment by EricDahlvang** [comment]
@ivlaevski Expanding on @lauren-mills answer, you can generate a unique .userId and cache it in a cookie:

```js

    <script src="https://cdn.botframework.com/botframework-webchat/master/webchat.js"></script>
    <script>

        function getUserId() {
            function getCookieUserId() {
                var name = "cachedUserId=";
                var decodedCookie = decodeURIComponent(document.cookie);
                var ca = decodedCookie.split(';');
                for (var i = 0; i < ca.length; i++) {
                    var c = ca[i];
                    while (c.charAt(0) == ' ') {
                        c = c.substring(1);
                    }
                    if (c.indexOf(name) == 0) {
                        return c.substring(name.length, c.length);
                    }
                }
                return "";
            }
            function setCookie(value, days) {
                var expires = "";
                if (days) {
                    var date = new Date();
                    date.setTime(date.getTime() + (days * 24 * 60 * 60 * 1000));
                    expires = "; expires=" + date.toUTCString();
                }
                document.cookie = "cachedUserId=" + (value || "") + expires + "; path=/";
            }
            function s4() {
                return Math.floor((1 + Math.random()) * 0x10000)
                    .toString(16)
                    .substring(1);
            }

            let cookieUserId = getCookieUserId();
            if (!cookieUserId) {
                cookieUserId = s4() + s4() + '-' + s4() + '-' + s4() + '-' + s4() + '-' + s4() + s4() + s4();
                setCookie(cookieUserId, 365);
            }

            return cookieUserId;
        }

        let dl = window.WebChat.createDirectLine({ secret: 'YOUR_DIRECTLINE_SECRET' });
        let userId = getUserId();

        window.WebChat.renderWebChat({
            userID: userId,
            directLine: dl
        }, document.getElementById('webchat'));


        dl.postActivity({
            from: {
                id: userId,
                name: 'User'
            },
            name: 'startConversation',
            type: 'event',
            value: ''
        })
            .subscribe(function (id) {
                console.log('trigger "startConversation" sent');
            });


    </script>
```

Note: since this user.id is generated client side, and stored in a cookie, other measures should be taken to ensure it is secure.  Better yet would be to generate the user.id server side, and embed it in the token retrieved while exchanging the secret for a token.  Please refer to this blog post for a deeper explanation and examples: https://blog.botframework.com/2018/09/25/enhanced-direct-line-authentication-features/
