### ISSUE TITLE
Disambiguation based on LUIS scores

### ISSUE THREAD

**Issue by Dewain27** [microsoft/botframework-solutions#2280]
## User Story
As ... bot user
I want ... to be able to choose which skill I meant when my utterance is ambiguous
so that ... I don't get routed to the wrong skill

## Acceptance Criteria 
*List your requirements.*
- [ ] If intent scores do not hit a high enough threshold, or if the score for multiple intents is very close, prompt the user to decide which skill to route to
- [ ] Make score threshold configuration in appsettings.json for the VA bot
- [ ] Use the name and description from the skill manifest to generate the UI
- [ ] After user selects a skill, route the original utterance to the skill they selected
- [ ] Log disambiguation telemetry (so it can be used for improvement)
- [ ] Create visualization in the PBI dashboard to view disambiguation data

## Resources
*Provide any screenshots or conversation mockups to support your request.*
*Learn how to mock up bot conversations with [.chat files](http://aka.ms/bfchatfile).*

[disambiguation.chat.txt](https://github.com/microsoft/botframework-solutions/files/3628104/disambiguation.chat.txt)

## Notes
*Provide any additional information.*

**Comment by darrenj** [comment]
ADO will track this

**Comment by ppn494** [comment]
@lauren-mills  I am looking to implement intent disambiguation using luis scores in our current implementation using bot framework. Can you please clarify if this issue is already addressed in the code? Thanks!

**Comment by ppn494** [comment]
@darrenj  - Can you please help me with my question? thanks.
