### ISSUE TITLE
[POI] clear guidance on actions "Call", "Show directions"

### ISSUE THREAD

**Issue by xieofxie** [microsoft/botframework-solutions#2292]
## User Story
As ...
I want ...
so that ...

## Acceptance Criteria 
*List your requirements.*
- [ ] ...
- [ ] ...
- [ ] ...

## Resources
*Provide any screenshots or conversation mockups to support your request.*
*Learn how to mock up bot conversations with [.chat files](http://aka.ms/bfchatfile).*

## Notes
*Provide any additional information.*

#### Is your feature request related to a problem? Please describe. 

It is not very clear that user should respond after the card appears.

#### What is the solution you are looking for?

Something like:

* Replace card button with suggested actions
* Add a fallback function there. So if user is confused, could use other skills

**Comment by ryanisgrig** [comment]
Closing - this is a good design principle and we will open further issues with this in mind.
