### ISSUE TITLE
[POI] find balance between verbosity and conciseness in speak

### ISSUE THREAD

**Issue by xieofxie** [microsoft/botframework-solutions#2293]
## User Story
As ...
I want ...
so that ...

## Acceptance Criteria 
*List your requirements.*
- [ ] ...
- [ ] ...
- [ ] ...

## Resources
*Provide any screenshots or conversation mockups to support your request.*
*Learn how to mock up bot conversations with [.chat files](http://aka.ms/bfchatfile).*

## Notes
*Provide any additional information.*

#### Is your feature request related to a problem? Please describe. 

Very verbose or lost information sometimes.

For example, when provide choices for locations.

#### What is the solution you are looking for?

Something like:

* Find some way to shorten the description of locations
* Set a maximum limit on words to speak

**Comment by ryanisgrig** [comment]
Closing - this is a good design principle and we will open further issues with this in mind.
