### ISSUE TITLE
[Docs] link is broken

### ISSUE THREAD

**Issue by tamerin-tech** [microsoft/botframework-solutions#2294]
the readme.md file on CalendarSkill points to a wrong url

https://github.com/microsoft/botframework-solutions/tree/master/skills/src/csharp/calendarskill/calendarskill

to (missing)
https://github.com/microsoft/botframework-solutions/blob/master/docs/reference/skills/productivity-calendar.md

**Comment by ryanisgrig** [comment]
Thanks @tamerin-tech, we'll fix this link!
