### ISSUE TITLE
[ITSM] make use of number of result to redesign go forward/previous etc.

### ISSUE THREAD

**Issue by xieofxie** [microsoft/botframework-solutions#2298]
## User Story
As ... a user
I want ... to have better instructions 
so that ... it is more natural

## Acceptance Criteria 
*List your requirements.*
- [ ] ... show instructions based on number of searched results
- [ ] ...
- [ ] ...

## Resources
*Provide any screenshots or conversation mockups to support your request.*
*Learn how to mock up bot conversations with [.chat files](http://aka.ms/bfchatfile).*

Screenshots are in pr #2375 now.

## Notes
*Provide any additional information.*

**Comment by lauren-mills** [comment]
@xieofxie please add the user story, requirements, and mockups (if conversation will change)

**Comment by xieofxie** [comment]
@lauren-mills added~
