### ISSUE TITLE
Calendar skill skip CollectAttendee step when answering twice with unrecognizable contact

### ISSUE THREAD

**Issue by lzc850612** [microsoft/botframework-solutions#230]
**Project**
Virtual Assistant

**Description**
In Calendar skill, CreateEvent scenario, when asked for participant, the dialog continues after you answer with unrecognizable contact twice when it should keep asking

**To Reproduce**
user: schedule a meeting
bot: who are the participants?
user: lauren
bot: I cannot find the contact your are looking for right now. Please include more details, do you want to try again?
user: lauren
bot: Alright, I will send this to , what is the subject of the meeting?

**Expected behavior**
the bot should keep asking if the contact is unrecognizable

**Screenshots**
![image](https://user-images.githubusercontent.com/4001684/47959192-56432a00-df9a-11e8-946d-438a38e78bce.png)

**Additional context**
This could be a common issue in all scenarios

**Comment by KayMKM** [comment]
fixed in #216
