### ISSUE TITLE
[Botbuilder-Solutions][Typescript] MultifactorProviderAuthDialog, but got 1 return

### ISSUE THREAD

**Issue by Robotbae** [microsoft/botframework-solutions#2303]
#### What project is affected?
Typescript 
Botbuilder-Solutions 
Using https://microsoft.github.io/botframework-solutions/tutorials/typescript/create-assistant/5_run_your_assistant/

#### What language is this in?
Typescript 

#### What happens?
Following updating the Authkey to AuthKey casing issue, there is one error I have not managed to get around.

src/index.ts:161:24 - error TS2554: Expected 2 arguments, but got 1.

161                 return new MultiProviderAuthDialog(oauthConnections);
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  node_modules/botbuilder-solutions/lib/authentication/multiProviderAuthDialog.d.ts:14:64
    14     constructor(authenticationConnections: IOAuthConnection[], appCredentials: MicrosoftAppCredentials);
                                                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    An argument for 'appCredentials' was not provided.


Found 1 error.

#### What are the steps to reproduce this issue?

#### What were you expecting to happen?
Expected a localhost endpoint  would be produce to test the VA 

#### Can you share any logs, error output, etc.?
Above 

#### Any screenshots or additional context?

![image](https://user-images.githubusercontent.com/50206076/64349374-bbb6db80-cfee-11e9-9e3a-6d8e259b8a47.png)

![image](https://user-images.githubusercontent.com/50206076/64349443-e43ed580-cfee-11e9-9548-1a2cd9779ed3.png)

**Comment by Batta32** [comment]
Hi @Robotbae, we recently solved those issues in #1943! 

We recommend you to use the **samples** of the repository:
- [sample-assistant](https://github.com/microsoft/botframework-solutions/tree/master/templates/Virtual-Assistant-Template/typescript/samples/sample-assistant)
- [sample-skill](https://github.com/microsoft/botframework-solutions/tree/master/templates/Virtual-Assistant-Template/typescript/samples/sample-skill)

Also, you can use the `generator-botbuilder-assistant` version 1.0.6 published in myget executing the following command:
>npm install -g generator-botbuilder-assistant@1.0.6 --registry https://botbuilder.myget.org/F/aitemplates/npm

**Comment by Robotbae** [comment]
Cheers @Batta32. 

For anyone else out there who created a folder already and deployed your Azure resource - the main files you gotta move things around e.g. what original ones were : 
AppSettings
CognitiveModels 
Package
Package-lock

NPM install 
NPM start

**Comment by Batta32** [comment]
Awesome @Robotbae !

Also, you should move the `.dispatch` file which is inside of `<YOUR_VA>\deployment\resources\Dispatch` folder created after deployment

**Comment by Robotbae** [comment]
Ah gotcha - cheers again!!
