### ISSUE TITLE
Docs for Samples have links broken

### ISSUE THREAD

**Issue by Dewain27** [microsoft/botframework-solutions#2308]
Currently, the docs for samples and Android Application docs are now have broken links.

https://github.com/microsoft/botframework-solutions/tree/master/solutions/android/VirtualAssistantClient

**Comment by Dewain27** [comment]
Another Example: https://github.com/microsoft/botframework-solutions/tree/master/samples/EnterpriseNotification

**Comment by ryanisgrig** [comment]
Next branch has the latest work and will feature samples all moved under the samples directories.
These will have aka.ms shortcut links.
