### ISSUE TITLE
Virtual Assistant configuration can only be run once

### ISSUE THREAD

**Issue by digitaldias** [microsoft/botframework-solutions#231]
**Project**
Virtual Assistant

**Description**
To continue working with Virtual Assistant on a different laptop, the new laptop should be able to obtain all configuration by running the  assistant again. What happens instead is the deployment script fails on "resource already exists". 

**To Reproduce**
Run the deployment script successfully. Then run it again. 

**Expected behavior**
The deployment script should not re-create any azure resource, but instead leverage them.

**Comment by ryanisgrig** [comment]
Hi @digitaldias, it sounds like you are just trying to access the same bot resources on multiple machines. If that's the case, you do not have to run a redeploy script to access your bot. Instead, you can copy both `appsettings.development.json` & `YOURBOT.bot` to your second laptop. These will point to the resource you have previously deployed.

**Comment by digitaldias** [comment]
Still, it would be nice to know if the script, when run a second time, should 
* Fail?
* Reset current resources to their default/scripted values
* Ignore the existing resources and continue to the next step

**Comment by ryanisgrig** [comment]
Transferred to Microsoft/Botbuilder-tools#780 for tracking as this is an MSBot issue.
