### ISSUE TITLE
[Hospitality] LateCheckOutDialog doesn't use time from ExtendStayDialog

### ISSUE THREAD

**Issue by xieofxie** [microsoft/botframework-solutions#2314]
## User Story
As ...
I want ...
so that ...

## Acceptance Criteria 
*List your requirements.*
- [ ] ...
- [ ] ...
- [ ] ...

## Resources
*Provide any screenshots or conversation mockups to support your request.*
*Learn how to mock up bot conversations with [.chat files](http://aka.ms/bfchatfile).*

## Notes
*Provide any additional information.*

#### Is your feature request related to a problem? Please describe. 

![Untitled](https://user-images.githubusercontent.com/2876650/64401212-7d7af400-d0a2-11e9-9e0b-4cc5be002664.png)

#### What is the solution you are looking for?

Consider it.

**Comment by lauren-mills** [comment]
This is fine to work on, but just remember this is a sample skill, and when a customer wants to use it, it would need to be customized anyway, so prioritize accordingly.
