### ISSUE TITLE
Calendar Skill - Get Events for General Timeframe

### ISSUE THREAD

**Issue by thegoo** [microsoft/botframework-solutions#2320]
#### What is the solution you are looking for?

As a user I require the ability to retrieve an event from my calendar by saying "show me my schedule for this afternoon," such that I can see any event from that period.

Calendar skill should support the ability to search for events for general timeframes like morning, afternoon, evening, night, etc.

**Comment by KayMKM** [comment]
This feature is implemented. In this case, it is a bug of LUIS that the model labelled "this afternoon" as "From time" and "To time" together. will fix the logic of handling these entities.

**Comment by darrenj** [comment]
Merged. Will be part of next weeks release (merged into master)
