### ISSUE TITLE
Calendar Handoff to POI Skill

### ISSUE THREAD

**Issue by thegoo** [microsoft/botframework-solutions#2321]
#### What is the solution you are looking for?

As a user I require the ability to select an event and launch the POI skill such that I can get retrieve navigation directions to the event.

Ability to handoff the event location to the POI skill and provide navigational capabilities.

**Comment by darrenj** [comment]
You can do this through the semanticaction work - i.e. find a location and then within your hosting bot trigger a follow-up action. Skills team have some examples
