### ISSUE TITLE
German wording for "Skills" in new user greeting

### ISSUE THREAD

**Issue by ppaltmann** [microsoft/botframework-solutions#2322]
The wording for "Skills" in the NewUserGreeting looks weird for a German user especially in the context of IT
<img width="529" alt="greeting_german_old" src="https://user-images.githubusercontent.com/452317/64489637-c8893880-d255-11e9-993d-0a9b7555aa9f.png">

This is how it should be - as skills are worldwide know to the community: 
<img width="527" alt="greeting_german_new" src="https://user-images.githubusercontent.com/452317/64489668-1f8f0d80-d256-11e9-8b49-c23068c7ef08.png">

#### What project is affected?
Templates & Samples

#### What language is this in?
C#
TypeScript

**Comment by lauren-mills** [comment]
Thank you for raising (and fixing!) this 😊
