### ISSUE TITLE
Determine how to support speech-only scenarios (no UI)

### ISSUE THREAD

**Issue by xieofxie** [microsoft/botframework-solutions#2324]
## User Story
As ... a bot developer
I want ... a design pattern to ensure that the speak property of activities provides enough context to a conversation when no UI will be present
so that ...  my users can use their Virtual Assistant without needing visual clues

## Acceptance Criteria 
*List your requirements.*
- [ ] ...
- [ ] ...
- [ ] ...

## Resources
*Provide any screenshots or conversation mockups to support your request.*
*Learn how to mock up bot conversations with [.chat files](http://aka.ms/bfchatfile).*

## Notes
*Provide any additional information.*

Speak-only scenario is different from showing something with speakings.
All needed information must be provided via speak in this scenario.
Device/channel could set a flag or something and skills are updated step-by-step to handle it.
Related #2293

**Comment by ryanisgrig** [comment]
I don't think this required a flag, as using the channelid "directlinespeech" indicates this.
I'm also unconvinced we need to develop separate logic for speech versus text based bots, but that's a deeper discussion :)

**Comment by lauren-mills** [comment]
I'm adding this to the backlog to work with the Design team on how we should handle these scenarios all up.

**Comment by darrenj** [comment]
Em is looking at this
