### ISSUE TITLE
[Docs] Escaping characters in appsettings.json password - No connection to bot possible 

### ISSUE THREAD

**Issue by ppaltmann** [microsoft/botframework-solutions#2332]
If you are using a password which is using characters which need to be escaped e.g. 

> \\

you can't connect to the bot with the password in the appsettings.json to the Bot Emulator. You need to be aware to not just copy & paste the password from the file as mentioned in the documentation. 

**Initial password**
> qnw5{-R/9\F#ZR6e

**Password in appsettings.json**
**I can't even paste the password into GitHub as it removes the escaped characters...**

![Screen Shot 2019-09-09 at 16 34 39](https://user-images.githubusercontent.com/452317/64539998-c55a7f00-d31f-11e9-804f-70b04ff6cdd8.png)

**Is this an issue with current documentation? If yes, please provide the link.**
https://microsoft.github.io/botframework-solutions/tutorials/csharp/create-assistant/5_run_your_assistant/

The documentation should be updated to mention that or checks should be put in place to inform the developer that the password will be escaped.

**Comment by ppaltmann** [comment]
FYI @Dewain27

**Comment by ryanisgrig** [comment]
Thanks @ppaltmann - will include this doc update in our next release!
