### ISSUE TITLE
Sample Virtual Assistant Deployment: Folder structure is not proper

### ISSUE THREAD

**Issue by urdurgaprasad** [microsoft/botframework-solutions#2336]
#### What project is affected?
botframework-solutions - Sample Virtual Assistant (Typescript)

#### What language is this in?
English

#### What happens?
Bot builder deployment script generating lib and node modules folders in root directory where package.json, tsconfig.json and web.config files are located.  Where as part of publish command it has been referred project directory as root directory\src. With this, required package.json, lib folders, web.config files are missing and unable to start sample bot in web client post deployment. 

Also please confirm, web.config should refer index.js or index.ts?

#### What are the steps to reproduce this issue?
Followed instructions specified in link https://microsoft.github.io/botframework-solutions/tutorials/typescript/create-assistant/1_intro/  for typescript VA sample.

**Comment by urdurgaprasad** [comment]
@lauren-mills , @Batta32 This issue has been marked for backlog. Could you please help me with workaround to install type script based sample virtual assistant with proper directory structure to proceed in the mean time?

**Comment by dfavretto** [comment]
Hi @urdurgaprasad,

Investigating the _deployment.ps1_ and _publish.ps1_ files, we discovered [the final message](https://github.com/microsoft/botframework-solutions/blob/a6ec2bf75233ced6e391653487ec52eff373be1a/templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/app/templates/sample-assistant/deployment/scripts/deploy.ps1#L208) after the deployment, gives indications on running the _publish.ps1_ script using the variable `$projDir` as the value for the parameter `projFolder`, which has [the path to the `src` folder](https://github.com/microsoft/botframework-solutions/blob/a6ec2bf75233ced6e391653487ec52eff373be1a/templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/app/templates/sample-assistant/deployment/scripts/deploy.ps1#L13), and this is a mistake.

We'll be updating the _deployment.ps1_ script to fix this message, and in the meantime, you can omit that parameter, as **it will default** to your project path correctly, thus publishing correctly.

Let us know if this works for you! 😊

**Comment by urdurgaprasad** [comment]
@dfavretto It worked, thank you.  One more observation,  luis_functions.ps1 referring to .luis files where as in repository structure we have .lu files only. Same with qna_functions.ps1.

One query, why we are maintaining two different folders i.e. src and lib with almost same replica of files?

**Comment by dfavretto** [comment]
Hi @urdurgaprasad,

Regarding the `.luis` files in `luis_functions.ps1`, if you observe the `deploy_cognitive_models.ps1` script, [it gets all the `.lu` files](https://github.com/microsoft/botframework-solutions/blob/4bb9291c984a882cc5e921857e35f4ee4f11e805/templates/Virtual-Assistant-Template/typescript/samples/sample-assistant/deployment/scripts/deploy_cognitive_models.ps1#L136) from the `deployment/resources/LU/{langCode}` folder, and sends it as parameter.
Inside the `luis_functions.ps1` script, these files [are processed](https://github.com/microsoft/botframework-solutions/blob/4bb9291c984a882cc5e921857e35f4ee4f11e805/templates/Virtual-Assistant-Template/typescript/samples/sample-assistant/deployment/scripts/luis_functions.ps1#L10) with the [`ludown` tool](https://github.com/microsoft/botbuilder-tools/tree/master/packages/Ludown), which creates `.luis` files from the `.lu` files. The same happens in `qna_functions.ps1` script, where the `.lu` files [are processed](https://github.com/microsoft/botframework-solutions/blob/4bb9291c984a882cc5e921857e35f4ee4f11e805/templates/Virtual-Assistant-Template/typescript/samples/sample-assistant/deployment/scripts/qna_functions.ps1#L9) to get `.qna` files.

For the two different folders, this is the way TypeScript works, you have your `src` folder where all your `.ts` files are located, and before running your code, you _transpile_ your TypeScript code into JavaScript code (using the command `npm run build`), and in turn it gets executed using Node. The `.js` files, which are located inside the `lib` folder, are autogenerated, so it's not advisable to edit them.

If you want to interiorize deeper on how TypeScript works, you can check the [official documentation](https://www.typescriptlang.org/docs/home.html).

**Comment by urdurgaprasad** [comment]
@dfavretto Thank You for the detailed explanation. It is very helpful.

In my machine, this .lu to .luis conversion is failing with error in resolving the path . In my machine, my user id is created as 'Durga Prasad'.Because of the space with in the user id, unable to resolve the path and not creating .luis file. Any suggestion on how this can be resolved by overriding the path ?

**Comment by dfavretto** [comment]
@urdurgaprasad let us check this out, we'll do some testing using a Virtual Assistant with spaces in the path and we'll reach you later

**Comment by Batta32** [comment]
@urdurgaprasad we came up with some questions:
- Which OS are you using?
- Which terminal are you using? (PowerShell, Command Line, Bash)
- Are you using the latest version of the `generator-botbuilder-assistant`? Today we published the **1.0.6** in [npm](https://www.npmjs.com/package/generator-botbuilder-assistant)!
> npm install -g generator-botbuilder-assistant

In our case, we tested with the following environment:
- Windows 10
- PowerShell 6
- Version 1.0.6 generator-botbuilder-assistant

We executed the deploy script adding a `Write-Host` to print the `lu path` which is used by the `DeployLUIS` method, and noticed that finished successfully even though the paths contains some spaces.
However, executing the `ludown parse toluis` command separately, an error raises.

![image](https://user-images.githubusercontent.com/11904023/64819427-8ed16e00-d584-11e9-804d-d09f6148b194.png)

As a workaround, you can execute the `ludown parse toluis` command adding the quotes in the paths like follows, replacing the `<PLACEHOLDERS>`:
> ludown parse toluis --in "<PATH_TO_THE_LU_FILE>" --outFolder "<PATH_TO_LU_FOLDER>" --luis_culture "<SPECIFIC_CULTURE>"

**Comment by urdurgaprasad** [comment]
@Batta32  Please find the requested information below:

- Which OS are you using? : Windows 10 Pro 64 bit
- Which terminal are you using? (PowerShell, Command Line, Bash) : PowerShell 6.2.2
- Are you using the latest version of the generator-botbuilder-assistant? Today we published the 1.0.6 in npm!:  Yes, using bot builder 1.0.6

Error while running deploy script:

![image](https://user-images.githubusercontent.com/38963266/64833402-7a509e00-d5a3-11e9-8796-931380c05d8d.png)

and when I looked at log below is the message:
"ENOENT: no such file or directory, open 'D:\***\***\Chatbot\Source\va-sample-dev\Deployment\resources\LU\en\general.luis'"

Below is the error while connecting skill to existing virtual assistant:
![image](https://user-images.githubusercontent.com/38963266/64833159-7cfec380-d5a2-11e9-83d5-18184389c378.png)

**Comment by urdurgaprasad** [comment]
@Batta32 In your case, your user name created as "MartinBattaglino" where as mine is "Durga Prasad" with space between. 

So, my doubt is these scripts are referring libraries located in path 
C:\Users\Durga Prasad\AppData\Roaming\npm, and because of space, path is breaking and unable to execute scripts properly.

**Comment by Batta32** [comment]
Hi @urdurgaprasad, 

We just understood what you meant, it wasn't an issue related to how the `deploy.ps1` script or `botskills cli tool` was using the paths internally, but probably about the location of your `npm` installation which contains the executed libraries.

Try changing the location of the `npm` installation to the `C hard disk`.

Also, here you have some links to review:
- [How to change npm globally installation path](https://stackoverflow.com/questions/41181400/how-to-change-npm-globally-installation-path)
- [How to npm install to a specified directory?](https://stackoverflow.com/questions/14469515/how-to-npm-install-to-a-specified-directory)
- [Issue with blank spaces in path](https://github.com/coreybutler/nvm-windows/issues/41)

**Comment by urdurgaprasad** [comment]
@Batta32 Below link helped to resolve the issue. Thank you all for your support. 

https://blog.jsinh.in/change-default-nodejs-npm-and-npm-cache-directory-on-windows/#.XYHT1ihKhPZ

**Comment by Batta32** [comment]
Awesome @urdurgaprasad!

We will close the issue because you could make it work! Feel free to reopen if you have a similar issue.
