### ISSUE TITLE
"Login With Outlook" prompt not working in ms Teams

### ISSUE THREAD

**Issue by lucascrandle** [microsoft/botframework-solutions#2345]
#### What project is affected?
Calendar Skill
#### What language is this in?
C#
#### What happens?
After following the tutorial, I added my virtual assistant with Calendar skill to teams, but the Login with outlook prompt and button doesn't work. I click the button but it doesn't open a browser or anything.
(I can hover-over the button to get the url and manually put that in a browser which works fine.)

#### What are the steps to reproduce this issue?
Following the tutorial to create a skill and add it to an assistant, then try to use the Calendar Skill
#### What were you expecting to happen?
The Login button to open a browser window.
#### Can you share any logs, error output, etc.?
None that I can see
#### Any screenshots or additional context?
![image](https://user-images.githubusercontent.com/16657988/64640042-2abd7700-d3d7-11e9-9239-a978f83456b4.png)

**Comment by lauren-mills** [comment]
HI @lucascrandle, there are additional steps you need to take to configure your bot for teams. Please follow this tutorial to get it set up: https://microsoft.github.io/botframework-solutions/tutorials/enable-teams/1_intro/

**Comment by lucascrandle** [comment]
The integration with teams is overall working fine. Just this button on the login prompt won't open in a browser like a user would expect.
I have to manually type in that url to get it to work.

**Comment by lucascrandle** [comment]
Just tried it in the web browser of teams as well and it won't open up a browser link there either. I see this in the console of the browser:

```
angular.min.js:112 2019-09-10T18:40:29.283Z Failed to get app entitlement for botId 28:****************
(anonymous) @ angular.min.js:112
e.logMessage @ msteams-web-ng1-services.min.js:1
e.error @ msteams-web-ng1-services.min.js:1
(anonymous) @ msteams-web-common.min.js:1
f @ angular.min.js:126
(anonymous) @ angular.min.js:126
$eval @ angular.min.js:141
$digest @ angular.min.js:138
m.$digest @ msteams-web-ng1-services.min.js:1
$apply @ angular.min.js:141
(anonymous) @ angular.min.js:268
dispatch @ jquery.min.js:1
y.handle @ jquery.min.js:1

msteams-web-ng1.min.js:1 Uncaught (in promise) No app definition found
```

**Comment by xieofxie** [comment]
@lucascrandle Hi, do you set up "token.botframework.com" in Valid domains?

If so, you might encounter something that I met yesterday. I do the followings:
1. create a new app(bot) and it should work
2. add the app to some test teams/chat to refresh it and it somehow worked today (why?)

**Comment by lucascrandle** [comment]
Ahh OK I see where I went wrong. I failed to see the part in the tutorial that requires the bot to be packaged as an app before it will work. 

I did that, added the url to the valid domains, and the button works now.

Thanks @xieofxie  and @lauren-mills
