### ISSUE TITLE
Teams reports Bad Request for Handoff activity

### ISSUE THREAD

**Issue by xieofxie** [microsoft/botframework-solutions#2350]
#### What project is affected?

Here: https://github.com/microsoft/botframework-solutions/blob/4e8e75dc49e0ed3064178bb2add1186de75610ba/lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/SkillCallingRequestHandler.cs#L80

#### What language is this in?

C#

#### What happens?

If testing skill from VA in Teams, this throws Bad Request when skill sends Handoff activity.

#### Any screenshots or additional context?

Use a try catch so always call _handoffActivityHandler?

**Comment by lauren-mills** [comment]
What is the behavior in Teams? Does it continue working, or does it break and throw an error? If you have any screenshots that would help.

We can report this up to the service team as needed.

**Comment by xieofxie** [comment]
@lauren-mills if you modify the code to this and finish a skill in VA in Teams, you would get the following exception:
![c](https://user-images.githubusercontent.com/2876650/64953602-c8bcb000-d8b5-11e9-87cb-b35833efe2a7.png)
![e](https://user-images.githubusercontent.com/2876650/64953606-cb1f0a00-d8b5-11e9-9ae3-f66cdd5caa5f.png)
So if you don't try-catch here, the _handoffActivityHandler will be skipped and VA will not finish.

I also notice the unused result. Should it be sent back after _handoffActivityHandler?

**Comment by lauren-mills** [comment]
Ok, thanks!

I think we can add some temporary code in the skill dialog to convert any handoff activities to endOfConversation activities for Teams until Teams supports this activity type. Since the request to change to handoff came from the BF service team we should align to their standard. I'll add this to the backlog and prioritize it for the next release.

**Comment by lauren-mills** [comment]
Just to verify, this happens when you connect to the skill directly, and when you connect to the skill through the VA bot, right?

**Comment by xieofxie** [comment]
@lauren-mills endOfConversation does not work in Teams either and we skipped them manually before. It happens only when connecting to our skills through the VA bot now since also skipped in directly connection scenario like here (it used to be endOfConversation event):https://github.com/microsoft/botframework-solutions/blob/498720926859a79d98d97905ad4d900ac830afc7/skills/src/csharp/pointofinterestskill/pointofinterestskill/Dialogs/MainDialog.cs#L137

**Comment by lauren-mills** [comment]
Discussions are ongoing in the SDK team around whether we will use Handoff of EoC going forward. Waiting to resolve this until a decision is made

**Comment by darrenj** [comment]
Handoff will be swapped back to End of Conversation (@gabog ) in the SDK port of Skills so closing this for now.

**Comment by xieofxie** [comment]
As of 
![image](https://user-images.githubusercontent.com/2876650/67364302-e0b4dd00-f5a1-11e9-8965-c083791887fb.png), when one sends Handoff or EndOfConversation to Teams channel, it will throw 'BadRequest'. So we had better not send them.
