### ISSUE TITLE
Remove unnecessary call of CompleteAsync

### ISSUE THREAD

**Issue by xieofxie** [microsoft/botframework-solutions#2355]
#### What project is affected?

VA, Skills

#### What language is this in?

C#

#### What happens?

Since https://github.com/microsoft/botframework-solutions/pull/2344, CompleteAsync should be removed from MainDialog::RouteAsync.

Or it might be double called for one-turn dialog.

**Comment by xieofxie** [comment]
After all are changed to latest libraries..

**Comment by xieofxie** [comment]
@lauren-mills This applies to 0.6 templates. Maybe we should update them.

**Comment by lauren-mills** [comment]
closed by #2371
