### ISSUE TITLE
allow user to remove conversation/user state from db

### ISSUE THREAD

**Issue by xieofxie** [microsoft/botframework-solutions#2358]
#### Is your feature request related to a problem? Please describe. 

In Teams, conversation id and user id could not be changed for a bot. So if dialog/model is changed and db fails to deserialize, nothing could be done to recover it.

#### What is the solution you are looking for?

Just like cancel, provide something to remove states and propagates it to skills.

**Comment by ryanisgrig** [comment]
@xieofxie, would this be covered by the `VA.ResetUser` event?

**Comment by lauren-mills** [comment]
Might be able to use Cosmos TTL to clear old states after a specified period.

**Comment by xieofxie** [comment]
@ryanlengel, I only find doc about this, do I miss something?

I am also afraid that this could not be handled within bot since it would fail before turn starts when some serialized class is renamed (handled in middleware perhaps?).

It is also important to pass this to skill from VA if the above happens.

**Comment by darrenj** [comment]
Do you want to propose some defensive exception handling to catch this error and correct the siutation so we can review?

**Comment by xieofxie** [comment]
@darrenj, OK, I will create an example to demonstrate this.

**Comment by xieofxie** [comment]
@darrenj The example: use CosmosDbStorage in POI skill and 
1. Connect it with emulator saying 'is there a coffee shop in town?';
2. Stop the skill and rename PointOfInterestSkillState to PointOfInterestSkillState2 to mock that developer has changed the code. Then start the skill again;
3. Continue in the emulator with 'New York'. Here user will be blocked forever if conversation id can't be changed (like in Teams) because the bot failed in deserialization of bot state and then bot logic will never be run.

However the bot state is deserialized in sdk and so it couldn't be caught precisely in solutions library.

Or a general reset approach could be addressed in OnTurnError function like this https://github.com/microsoft/botframework-solutions/commit/39a10427b2f856e54f2dbe605049641aff888dc3. Do you think this fix is applicable? Thanks~
