### ISSUE TITLE
URLs in first conversation give 404

### ISSUE THREAD

**Issue by paragppp** [microsoft/botframework-solutions#238]
**Project**
Virtual Assistant

**Description**
When the initial conversation initiates, the links for  "Linked Accounts" or "Skills" are referencing to customassistant and getting 404

**To Reproduce**
After clicking on  "Linked Accounts" or "Skills", we get 404

**Expected behavior**
The respective page should open for  "Linked Accounts" or "Skills"

**Comment by lauren-mills** [comment]
Closed by #237
