### ISSUE TITLE
[Calendar] Support natural slot filling in the conversation 

### ISSUE THREAD

**Issue by xhr0804** [microsoft/botframework-solutions#2394]
## User Story
As a ... bot user
I want ... to fill slots in a natural way rather than in a fix pattern
So that ... I can have more natural and complex conversation

User: create a meeting with John
Bot: when is the meeting?
<at this point, user can say:
what's the weather tomorrow -> switch to other skill (#2399)
show my meetings this afternoon -> switch to other intent in the skill (#2316)
add Jeff to the meeting as well -> update other slot (#2394)
book a meeting at 4pm for 2 hours -> update more slots (#2394)
skip this one -> allow user to ignore a slot

## Acceptance Criteria 
Enable following scenario
- [ ] support customized prompt dialog
- [ ] extract proper title/location/duration/time/name in prompt dialog

## Resources
*Provide any screenshots or conversation mockups to support your request.*
*Learn how to mock up bot conversations with [.chat files](http://aka.ms/bfchatfile).*

User: book a meeting with Graham
Bot: Okey, I will add Graham. Do you want to add any other participants?
User: No
Bot: Ok, what is the subject of the meeting?
User:Oh, I want to add another participant
Bot: Ok, who will join?
User: Lucy
Bot: Sure.

## Notes
*Provide any additional information.*
The intent flow of the calendar skill such as "create a meeting" runs serially, the user can not change the slots flexibly. 
For example, I've added some attendees into the meeting, and the CreateMeetingDialog now ask me for the Title. However, I suddenly find that I need to add another attendee, but the skill cannot support the scenario flexibly.

**Comment by lauren-mills** [comment]
@xhr0804 I rearranged your user story to keep it concise and moved the additional context to the notes   😊

**Comment by darrenj** [comment]
Merged
