### ISSUE TITLE
[Calendar] Support meeting selection by title fuzzy-matching

### ISSUE THREAD

**Issue by KayMKM** [microsoft/botframework-solutions#2395]
## User Story
As a ... bot user
I want ... to select meeting by fuzzy matching the meeting title
so that ... I can have more natural conversation

when user choose a meeting in a list, need fuzzy match the title. now it can only choose the meeting title that contains the keyword.
![image](https://user-images.githubusercontent.com/19773357/65137976-d2bceb00-da3c-11e9-98a2-9510587cc561.png)

## Acceptance Criteria 
- [ ] Title extraction from utterance
- [ ] Fuzzy matching support

## Resources
```
user=megan
bot=calendarbot

bot: you have 3 events for today.
[Attachment]
bot: do you want to hear the content of the first meeting? I can read out any event for you, just let me know by providing the subject, time or attendees.

user: show the "website review"

bot: here is the meeting detail:
[Attachment]
```

## Notes
*Provide any additional information.*

**Comment by darrenj** [comment]
Merged
