### ISSUE TITLE
[Skills] Change to open question for some yes/no prompt

### ISSUE THREAD

**Issue by KayMKM** [microsoft/botframework-solutions#2398]
## User Story
As a ...
I want ...
so that ...

there are some confirmation steps in the end of an action. like the question "Do you want to show the overview again?". user may want to jump to other dialog and do not need to answer "no" to the question. so we should change the prompt to an open question so user can switch dialog easier.

## Acceptance Criteria 
- [ ] ...
- [ ] ...

## Resources
for example, "Do you want to show the overview again?" change to "Do you want to show the overview again? Or you can ask me to create, update, or join an event."

## Notes
*Provide any additional information.*

**Comment by darrenj** [comment]
Merged
