### ISSUE TITLE
[Calendar] Support skill switching in the prompt dialog

### ISSUE THREAD

**Issue by xhr0804** [microsoft/botframework-solutions#2399]
## User Story
As a ... bot user
I want ... to switch to other skill when in a prompt dialog
So that ... I can have more natural and complex conversation 

User: create a meeting with John
Bot: when is the meeting?
<at this point, user can say:
1. what's the weather tomorrow  -> switch to other skill (#2399)
2. show my meetings this afternoon -> switch to other intent in the skill (#2316)
3. add Jeff to the meeting as well -> update other slot (#2394)
4. book a meeting at 4pm for 2 hours -> update more slots (#2394)
5. skip this one -> allow user to ignore a slot
>

## Acceptance Criteria 
Enable following scenario
- [ ] support customized prompt dialog
- [ ] extract proper title/location/duration/time/name in prompt dialog
- [ ] skill-skill switch, and allow resume or not from previous skill 

## Resources
*Provide any screenshots or conversation mockups to support your request.*
*Learn how to mock up bot conversations with [.chat files](http://aka.ms/bfchatfile).*

## Notes
*Provide any additional information.*

**Comment by lauren-mills** [comment]
Please provide the user story and the requirements checklist.

**Comment by darrenj** [comment]
Merged
