### ISSUE TITLE
EBT deprecation plan

### ISSUE THREAD

**Issue by lauren-mills** [microsoft/botframework-solutions#2405]
## User Story
As ... bot developer
I want ... to know which template I should be using
so that ... am not on outdated source code

## Acceptance Criteria 
*List your requirements.*
- [ ] Should clearly show in VS and marketplace that EBT is deprecated and VA template is recommended

## Resources
*Provide any screenshots or conversation mockups to support your request.*
*Learn how to mock up bot conversations with [.chat files](http://aka.ms/bfchatfile).*

## Notes
*Provide any additional information.*

**Comment by darrenj** [comment]
We'll remove at GA time
