### ISSUE TITLE
Document how to add QnA to a skill

### ISSUE THREAD

**Issue by lauren-mills** [microsoft/botframework-solutions#2408]
## User Story
As ... bot developer
I want ... to know how to implement QnA Maker in a skill
so that ... I can use QnA Maker in a skill

## Acceptance Criteria 
*List your requirements.*
- [ ] Adding QnA to a skill (including requirement for using Dispatch)
- [ ] How to use metadata (e.g. have different responses for different countries)

## Resources
*Provide any screenshots or conversation mockups to support your request.*
*Learn how to mock up bot conversations with [.chat files](http://aka.ms/bfchatfile).*

## Notes
*Provide any additional information.*

**Comment by badhonkundu** [comment]
@darrenj 
Is this closed considering it is not possible to add a QnAmaker to a skill or is it documented somewhere? We have a use case where we need to add a QnA maker to a skill. Could you please guide if this a achievable today?
