### ISSUE TITLE
Enable intent switch in VA

### ISSUE THREAD

**Issue by lauren-mills** [microsoft/botframework-solutions#2409]
## User Story
As ... bot developer
I want ... to be able to switch between skills and top-level intents mid-conversation
so that ... the flow is more flexible

## Acceptance Criteria 
*List your requirements.*
- [ ] Default behavior in VA should support top-level intent switch using lib changes from 0.6
- [ ] VA implementation should automatically pull in the different top-level intents based on BotServices configuration (no hard-coded intent/model names)
- [ ] Update documentation with any changes (current docs in reference/skills/best practices 

## Resources
*Provide any screenshots or conversation mockups to support your request.*
*Learn how to mock up bot conversations with [.chat files](http://aka.ms/bfchatfile).*

## Notes
*Provide any additional information.*

**Comment by darrenj** [comment]
merged
