### ISSUE TITLE
When user inputs "cancel," the "Yes / No" button set appears before the bot asks "Are you sure you want to cancel?"

### ISSUE THREAD

**Issue by rng** [microsoft/botframework-solutions#241]
**Project**
Virtual Assistant

**Description**
To escape "Sorry, something went wrong trying to communicate with the skill. Please try again." user types "cancel" to exit. When this happens, the two buttons "Yes" and "No" appear first. Only after I select "Yes" did the question "Are you sure you want to cancel?" comes up.

**To Reproduce**
Type cancel
Select "Yes"

**Additional context**
Trying it out on the demo instance https://compulim.github.io/botframework-virtual-assistant-demo/?locale=en-us

**Comment by lauren-mills** [comment]
This is probably caused by an async problem in the Cancel dialog

**Comment by lauren-mills** [comment]
I'm not able to repro this. I'll close for now, and reopen if we're able to see it again.
