### ISSUE TITLE
Add personName entity recognition to onboarding dialog

### ISSUE THREAD

**Issue by rng** [microsoft/botframework-solutions#242]
## User Story
As ... a bot user
I want ... natural language understanding to recognize my name from an utterance like "my name is X"
so that ... my Virtual Assistant experience can be personalized.

## Acceptance Criteria 
*List your requirements.*
- [ ] Should extract the personName entity from the users utterance
- [ ] Entity and intent should be added to the General LUIS model
- [ ] Should support EFIGS+C languages

## Resources
*Provide any screenshots or conversation mockups to support your request.*
*Learn how to mock up bot conversations with [.chat files](http://aka.ms/bfchatfile).*

## Notes
*Provide any additional information.*
Bot asks me my name and saves the value in state. It is not yet using LUIS to determine that the entire string I entered is not my name.

**Comment by lauren-mills** [comment]
Request for more robust onboarding. Since this is a placeholder for customers to modify with their custom logic, we will evaluate this against the backlog going forward.

**Comment by darrenj** [comment]
Update to use personName pre-built entity and port to ET

**Comment by lauren-mills** [comment]
After looking at this, it might require more work than just adding the entity, because none of our models are trained for the "intermediate" responses from the user. "I'm rachel" or "my name is rachel" get routed to different models at the dispatch level because General isn't trained to handle them yet. Moving to Vanadium.

**Comment by hansmbakker** [comment]
_moved to https://github.com/Microsoft/AI/issues/539_

**Comment by lauren-mills** [comment]
Blocked by lack of support for personName LUIS entity in supported languages.

**Comment by darrenj** [comment]
Incorporated in new onboarding design work
