### ISSUE TITLE
[POI] Utterance like "find the nearest Starbucks" incorrectly routes to General LUIS model

### ISSUE THREAD

**Issue by Dewain27** [microsoft/botframework-solutions#2424]
#### What project is affected?
Android App
#### What happens?
Asking "Find the nearest Starbucks" routes to the General LUIS model
![image](https://user-images.githubusercontent.com/18688053/65512898-76454a00-deda-11e9-8f14-fb2df85b048d.png)
![image](https://user-images.githubusercontent.com/43043272/65791161-015e5400-e116-11e9-9378-490eab502f07.png)

#### What are the steps to reproduce this issue?
![image](https://user-images.githubusercontent.com/43043272/65791090-d5db6980-e115-11e9-9282-399298fa21fe.png)

#### What were you expecting to happen?
The Point of Interest Skill should return just the nearest Starbucks and offer contact/navigation options

#### Can you share any logs, error output, etc.?
see above
#### Any screenshots or additional context?
see above

**Comment by ryanisgrig** [comment]
This occurs on the emulator as well - reassigning to Skills as it is an LU training issue

**Comment by xieofxie** [comment]
It may be caused by the changes of intent names. Does redeployment fix this?

Is there a pointOfInterestSkill intent in the dispatch model of VA?

**Comment by ryanisgrig** [comment]
Yes the intent is in the dispatch model, and now on BFVA (Test) the query in question routes to None.
![image](https://user-images.githubusercontent.com/43043272/68703479-96d76b00-053f-11ea-85f9-991b435ced4b.png)

**Comment by xieofxie** [comment]
@ryanlengel Oops, after some testing, I found it is caused by too many None utterances. So I reduce them in this pr https://github.com/microsoft/botframework-solutions/pull/2696
