### ISSUE TITLE
[Bing Search Skill] Adaptive Cards don't render on Android SDK

### ISSUE THREAD

**Issue by Dewain27** [microsoft/botframework-solutions#2425]
#### What project is affected?
Android App
#### What happens?
When you ask a "Who is.... " question the response comes back, however the adaptive card is not rendering properly.  See image below:
![image](https://user-images.githubusercontent.com/18688053/65513696-059f2d00-dedc-11e9-8025-4eab1e7cf50b.png)

You also get two what else can I help you with responses as well.

#### What are the steps to reproduce this issue?
Using the Android App 9/21 you get a poorly rendered adaptive card back when you ask "Who is Barack Obama?"

#### What were you expecting to happen?
I expected to get a properly rendered adaptive card back in the feed.
#### Can you share any logs, error output, etc.?
See above
#### Any screenshots or additional context?
This renders correctly on other channels
![image](https://user-images.githubusercontent.com/43043272/65732418-b1807e00-e07e-11e9-928d-e65050057f29.png)

**Comment by ryanisgrig** [comment]
Moving to Skills project - this renders well on other channels.
