### ISSUE TITLE
[Template] Cancel response should have ignoringInput hint so that a mic doesn't open

### ISSUE THREAD

**Issue by Dewain27** [microsoft/botframework-solutions#2426]
## User Story
As ... a VA user
I want ... to say cancel and have it leave the mic closed
so that ... it doesn't start listening to me when I'm not interested in talking to it

## Acceptance Criteria 
*List your requirements.*
- [ ] Cancel response uses `ignoringInput` for `inputHint`

## Notes
*Provide any additional information.*

#### What project is affected?
Android App
#### What happens?
When you say cancel and you get a "There is nothing to cancel" the Mic reopens.
#### What are the steps to reproduce this issue?
Say cancel at the top level to initiate the cancel with "There is nothing to cancel" response.  The mic will then reopen
#### What were you expecting to happen?
After saying cancel you should always close the mic

**Comment by ryanisgrig** [comment]
@lauren-mills we have a couple items related to template/demo sample behavior:
#2031
#1989

**Comment by darrenj** [comment]
merged
