### ISSUE TITLE
Refactor VSIX projects into one solution

### ISSUE THREAD

**Issue by lauren-mills** [microsoft/botframework-solutions#2427]
## User Story
As ... bot developer
I want ... one vsix installer for VA and Skill templates
so that ... I do not have to maintain and install multiple VSIXs for my project

## Acceptance Criteria 
*List your requirements.*
- [ ] Combine VA and Skill templates into one installer
- [ ] Update skill template in marketplace to show as deprecated and redirect to Virtual Assistant Template

## Resources
*Provide any screenshots or conversation mockups to support your request.*
*Learn how to mock up bot conversations with [.chat files](http://aka.ms/bfchatfile).*

## Notes
*Provide any additional information.*

**Comment by darrenj** [comment]
Delivered in 0.8
