### ISSUE TITLE
[Calendar] support checking availability 

### ISSUE THREAD

**Issue by bobokids** [microsoft/botframework-solutions#2433]
## User Story
As ... bot user
I want ... to check if someone is available at specific time
so that ... I can get more complex conversation

User: 
- do I have meeting at 5pm?
-  is Tom free at 5pm

## Acceptance Criteria 
*List your requirements.*
- [ ] enable checking availability
- [ ] ...
- [ ] ...

## Resources
*Provide any screenshots or conversation mockups to support your request.*
*Learn how to mock up bot conversations with [.chat files](http://aka.ms/bfchatfile).*

## Notes
*Provide any additional information.*

**Comment by KayMKM** [comment]
Seems we need a more detailed design. There are some scenarios and my proposal:

1. user ask for a time point 
user: "am/is I/someone free/busy when 5 pm"
[find contact logic]
option 1: bot: you/someone are free at 5 pm
option 2: bot: you/someone have meetings from 4 pm to 6 pm
option 3: if user ask for himself will show the meeting list at that time. if user ask for others will show option 2.
2. user ask for a time range
user: "am/is I/someone free/busy on Wednesday"/"when am I free/busy on Wednesday"
[find contact logic]
option 1(bot answer all the free period in response):
bot: you/someone are free from 10 am to 12 pm, 1 pm to 2:30 pm, 4 pm to 6 pm.
option 2: show a card about free time
option 3: if user ask for himself will show the meeting list. if user ask for others will show option 1 or 
3. user ask without time
user: "when am I free/when is someone free"
[find contact logic]
option 1: show the schedule of today
option 2: show the schedule of one week
(the logic of showing is same with scenario 2)

**Comment by KayMKM** [comment]
done
