### ISSUE TITLE
[Docs] Provide information on downloadable Direct Line Speech client

### ISSUE THREAD

**Issue by ryanisgrig** [microsoft/botframework-solutions#2438]
## User Story
As ... a bot developer
I want ... a simple app to use the Direct Line Speech 
so that ... I can validate how my VA behaves on this channel and view activity logs for debugging

## Acceptance Criteria 
*List your requirements.*
- [ ] Update doc references with Kona client information

## Resources
*Provide any screenshots or conversation mockups to support your request.*
*Learn how to mock up bot conversations with [.chat files](http://aka.ms/bfchatfile).*

## Notes
*Provide any additional information.*

**Comment by darrenj** [comment]
Done in last release
