### ISSUE TITLE
Unit test for VA-Skill interactions

### ISSUE THREAD

**Issue by xieofxie** [microsoft/botframework-solutions#2440]
## User Story
As ... a developer
I want ... to make sure VA-Skill are interacted correctly
so that ... unit tests for their interactions should be provided

## Acceptance Criteria 
*List your requirements.*
- [ ] ... Test for calling skill from VA
- [ ] ... Test for canceling skill in VA
- [ ] ... Test for sending events (like VA.Location) that are used in skill to VA
- [ ] ... Test for oauth prompt
- [ ] ... Test for fallback

## Resources
*Provide any screenshots or conversation mockups to support your request.*
*Learn how to mock up bot conversations with [.chat files](http://aka.ms/bfchatfile).*

A draft implementation based on VA sample is provided in [hualxie/vaskilltest branch](https://github.com/microsoft/botframework-solutions/blob/hualxie/vaskilltest/templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample.Tests/SkillTests.cs)

However it faces the following shortcomings now:
* MockDispatchLuis & MockMainDialog have to be provided as VA does not have skill intents
* Could not overwrite SkillWebSocketAdapter's _authenticator directly (reflection is used)
* Skills are started as local servers so that certain ports should not be used

## Notes
*Provide any additional information.*

**Comment by darrenj** [comment]
Tracked part of test envrionment work
