### ISSUE TITLE
[Android] VA Client sample is unable to establish new conversations with VA after a long period of time

### ISSUE THREAD

**Issue by ryanisgrig** [microsoft/botframework-solutions#2445]
#### What project is affected?
Virtual Assistant Client sample

### What language is this in?
Android

#### What happens?
After having the VA Client installed on my tablet after several days (with the latest available APK), I am unable to start any new conversations with the VA endpoint. When I click the microphone the listening animation appears but it does not use an audio indicator and only sometimes goes into thinking (where it hangs).

To resolve this I had to uninstall the existing app, reinstall the same APK and conversations with the VA worked as expected.

#### What are the steps to reproduce this issue?
Leave app installed on tablet and return to it later (it has been several days for myself)

#### What were you expecting to happen?
I can return to the VA Client later and engage with the VA. Even if something went wrong with an existing conversation, after clicking "New conversation" I would expect it to work correctly.

**Comment by bobokids** [comment]
Not easy to repro. We updated the restart logic so user can recover if get into the issue. https://github.com/microsoft/botframework-solutions/issues/2567.

**Comment by bobokids** [comment]
Close this issue. Please reactivate it if we can still repro.
