### ISSUE TITLE
always keep to Geo URI scheme

### ISSUE THREAD

**Issue by xieofxie** [microsoft/botframework-solutions#2446]
## User Story
As ... user/dev
I want ... to keep consistency about scheme
so that ... all latitude/longitude pair should use [Geo URI scheme](https://en.wikipedia.org/wiki/Geo_URI_scheme)

## Acceptance Criteria 
*List your requirements.*
- [ ] ... POI: https://microsoft.github.io/botframework-solutions/reference/skills/pointofinterest/
- [ ] ... Use doc to make sure any happened later
- [ ] ...

## Resources
*Provide any screenshots or conversation mockups to support your request.*
*Learn how to mock up bot conversations with [.chat files](http://aka.ms/bfchatfile).*

## Notes
*Provide any additional information.*

**Comment by lauren-mills** [comment]
@xieofxie Please add some more details about the changes needed.
