### ISSUE TITLE
[Skills] Update transcripts in documentation with latest transcripts. Calendar for example doesn't show any adaptive card responses at all!

### ISSUE THREAD

**Issue by darrenj** [microsoft/botframework-solutions#2454]
Calendar Skill for example doesn't show any adaptive card responses at all and seems quite out of date. Transcript list is [here](https://microsoft.github.io/botframework-solutions/reference/skills/transcripts/).

Also make sure additional skills e.g. ITSM are covered too.

Ideally also add a screenshot or two to each Skill page in the documentation too to brighten up the page and make it easier to understand the capabilities (e.g. https://microsoft.github.io/botframework-solutions/reference/skills/productivity-calendar/)

**Comment by lauren-mills** [comment]
Should be done right before next release.

**Comment by bobokids** [comment]
@darrenj Please review the transcripts here https://microsoft.github.io/botframework-solutions/skills/samples/transcripts/.

**Comment by bobokids** [comment]
We will re-visit the issue if there are more concern on the transcript.
