### ISSUE TITLE
publish script does not show errors

### ISSUE THREAD

**Issue by tamerin-tech** [microsoft/botframework-solutions#2455]
I tried to publish using the following script
.\Deployment\Scripts\publish.ps1

The output was:
> Publishing to Azure ...
and nothing more

Later I found out in the log file that it failed
WARNING: Getting scm site credentials for zip deployment
ERROR: ResourceNotFound - The Resource 'Microsoft.Web/sites/...
under resource group '...' was not found.

it would be nice if the script will inform about problems

**Comment by lauren-mills** [comment]
Hi @tamerin-tech is this from the latest script here? https://github.com/microsoft/botframework-solutions/tree/master/templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Deployment/Scripts

I added some additional output that should be showing these errors now in the last release. Please let me know if you're still not seeing them after updating to the latest.

**Comment by tamerin-tech** [comment]
Hi @lauren-mills , thanks, after updating the scripts the error appears more clearly. Closing this issue
