### ISSUE TITLE
Add Enterprise Template documentation for adding a new qnamaker instance

### ISSUE THREAD

**Issue by darrenj** [microsoft/botframework-solutions#246]
**Is your feature request related to a problem? Please describe.**
A developer wants to add an extra QnAMaker kb to a ent template based bot, unclear about how to do this beyond what we provide out of the box.

**Describe the solution you'd like**
Update to the "customise the template" docs to show how can add a new QnAMaker instance, refresh the model and new router handler (like adding a LUIS model)

**Additional context**
"It was hard to figure out how to add a second QnA KB.  The templates nicely set things up, but going beyond the template you are dumped out on your own.  We made need more a FAQ of next steps."

**Comment by kevintupper** [comment]
Would love to know how to add a second QnA Kb.   I added one using MSBot.  It successfully added it to all .bot file and to the LUIS dispatcher and model.  But running the bot gives me an exception in TelemetryLuisRecognizer.cs on line 131 when it tries to recognize any input.

**Comment by darrenj** [comment]
Can you try using LuisGen to recreate the Dispatch.cs file based on the LUIS model for your new dispatcher? `solutions\Virtual-Assistant\src\csharp\assistant\Dialogs\Shared\Resources\Dispatch.cs`

That might address your exception. You also need to then add an additional QnA handler in `solutions\Virtual-Assistant\src\csharp\assistant\Dialogs\Main\MainDialog.cs`

**Comment by kevintupper** [comment]
I did not use LuisGen to recreate Dispatch.cs, but I did manually adjust Dispatch.cs and added the new QnA handler to the MainDialog.   ALL GOOD!!!

Successfully added a new QNA kb to the Enterprise Bot.   

Thank you for your help.

**Comment by darrenj** [comment]
Great, thanks for letting us know. Have added this to the Virtual Assistant docs and will port to Enterprise Template Docs
