### ISSUE TITLE
botframework-solutions/templates/CustomerSupportTemplate Error

### ISSUE THREAD

**Issue by arunprasathv** [microsoft/botframework-solutions#2460]
@lauren-mills @ryanlengel 

https://github.com/microsoft/botframework-solutions/blob/master/templates/Customer-Support-Template/CustomerSupportTemplate/CustomerSupportTemplate

I'm running this project, I'm unable to process the message as OnTurnAsync gets executed every time the message is being entered in the BOT, 

 var result = await dc.ContinueDialogAsync();  -- **is always Empty.** 

and  **turnContext.Activity.Type is showing as message **. and it doesn't process any dialog and no response in the bot, just blank. like when I want to see OrderStatusCard it doesn't execute the RouteAsync in MainDialog. 

Do I need to run  **await dc.BeginDialogAsync(nameof(MainDialog));** everytime the message is being typed ?  I tried but it doesn't work either, it shows message like - I am happy to help. Can you provide the order number? (if i execute await dc.BeginDialogAsync(nameof(MainDialog)) in debug mode by steping through) and if I enter order number nothing happens. 

What am I missing here?  What should happen when turnContext.Activity.Type == message ?  

I'm not using TelemetryClient.

Please help to resolve this issue. 

**_My Code below - CustomerSupportTemplate  and Startup.cs_**   

using System;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Bot.Builder;
using Microsoft.Bot.Builder.Dialogs;
using Microsoft.Bot.Schema;
 

namespace  EnterpriseBot
{
    /// <summary>
    /// Main entry point and orchestration for bot.
    /// </summary>
    public class CustomerSupportTemplate : IBot
    {
        private IBotServices _services;
        private readonly ConversationState _conversationState;
        private readonly UserState _userState;
        private DialogSet _dialogs;

        /// <summary>
        /// Initializes a new instance of the <see cref="CustomerSupportTemplate"/> class.
        /// </summary>
        /// <param name="botServices">Bot services.</param>
        /// <param name="conversationState">Bot conversation state.</param>
        /// <param name="userState">Bot user state.</param>
        public CustomerSupportTemplate(IBotServices botServices, ConversationState conversationState, UserState userState)
        {
            _conversationState = conversationState ?? throw new ArgumentNullException(nameof(conversationState));
            _userState = userState ?? throw new ArgumentNullException(nameof(userState));
            _services = botServices ?? throw new ArgumentNullException(nameof(botServices));
            

            _dialogs = new DialogSet(_conversationState.CreateProperty<DialogState>(nameof(CustomerSupportTemplate)));
            _dialogs.Add(new MainDialog(_services, _conversationState, _userState));
        }

        /// <summary>
        /// Run every turn of the conversation. Handles orchestration of messages.
        /// </summary>
        /// <param name="turnContext">Bot Turn Context.</param>
        /// <param name="cancellationToken">Task CancellationToken.</param>
        /// <returns>A <see cref="Task"/> representing the asynchronous operation.</returns>
        public async Task OnTurnAsync(ITurnContext turnContext, CancellationToken cancellationToken)
        {
            var dc = await _dialogs.CreateContextAsync(turnContext);
            var result = await dc.ContinueDialogAsync();
           // await dc.BeginDialogAsync(nameof(MainDialog));

            if (result.Status == DialogTurnStatus.Empty)
            {
                if (turnContext.Activity.Type == ActivityTypes.ConversationUpdate)
                {
                    var activity = turnContext.Activity.AsConversationUpdateActivity();

                    // if conversation update is not from the bot.
                    if (!activity.MembersAdded.Any(m => m.Id == activity.Recipient.Id))
                    {
                        await dc.BeginDialogAsync(nameof(MainDialog));
                    }
                }
            }
        }
    }
}

**Startup.cs**

  public void ConfigureServices(IServiceCollection services)
        {
services.AddBot<CustomerSupportTemplate>(options =>
            {
                // Catches any errors that occur during a conversation turn and logs them to AppInsights.
                options.OnTurnError = async (context, exception) =>
                {
                    await context.SendActivityAsync("Sorry, it looks like something went wrong.");
                    await context.SendActivityAsync(new Activity(type: ActivityTypes.Trace, text: $"Error: {exception.Message} | {exception.StackTrace}"));
                };
            });
}

public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {

            //isProduction = env.IsProduction();
            app.UseBotFramework();
            app.UseMvc();
            app.UseDefaultFiles();
            app.UseStaticFiles();
            }

**Comment by lauren-mills** [comment]
Hi @arunprasathv,it is correct for OnTurnAsync to run every turn, but you don't need to call BeginAsync on MainDialog every turn.

Once MainDialog has been started, this line `await dc.ContinueDialogAsync();` passes any incoming activity to MainDialog. 

Once its in MainDialog, if you have started another dialog, like OrderStatusDialog, the message will not come into the RouteAsync method of MainDialog, but will go straight into the OrderStatusDialog. RouteAsync only gets called when no children dialogs of MainDialog have been started. 

 This logic happens inside the RouterDialog base class at line 29.

**Comment by lauren-mills** [comment]
Closing for now. Please reopen as needed.
