### ISSUE TITLE
Introduction card not shown in Teams or FaceBook Messenger

### ISSUE THREAD

**Issue by darrenj** [microsoft/botframework-solutions#2461]
#### What project is affected?

Virtual Assistant

#### What language is this in?

C#

#### What happens?

Introduction card behaviour is not consistent across channels. For example:
- Intro card is not shown when a user using FaceBook messenger starts a conversation
- Intro card is only show to a user in Teams after the first message

#### What are the steps to reproduce this issue?

- Deploy VA
- Add Teams / FB Channel and start a conversation. Observe that no card is shown.

#### What were you expecting to happen?

- Intro card to be shown as per other channels

#### Any screenshots or additional context?

![image](https://user-images.githubusercontent.com/33519520/66055926-3dd2eb00-e52e-11e9-809e-dab7ebed223e.png)

![image](https://user-images.githubusercontent.com/33519520/66056099-81c5f000-e52e-11e9-875c-d203bac4aa09.png)

**Comment by lauren-mills** [comment]
This needs more investigation to identify if/how each channel tells the bot the conversation has started. If we do not receive an activity from the channel letting us know the conversation has begun, we might not be able to send an intro card before the user messages us.

**Comment by darrenj** [comment]
Would you be able to validate this is still an issue? Thanks
