### ISSUE TITLE
Weather Skill - Ability to Select and Confirm Current or Desired Location

### ISSUE THREAD

**Issue by thegoo** [microsoft/botframework-solutions#2465]
## User Story
As a user I require the ability to confirm the location I am searching such that I am provided the appropriate weather forecast for the desired location.

## Acceptance Criteria 
*List your requirements.*
- Provide ability to select/confirm location when multiple locations have the same name; ex.: Athens, GA vs. Athens, OH vs. Athens, Greece.
- Provide additional data to disambiguate locations with the same names; ex.: display postal zip code of location such that the user can select/confirm the appropriate location.
- Weather forecast details reflect the location the user selects/confirms.

## Resources
Below is a sample conversation mock up:
user=Jesse
bot=WeatherBot

bot: Hi! I can provide you with a weather forecast for your location.  Where are you?

user: What is the weather in Flemington?

bot: I found two locations that match Flemington:
[Suggestions=Flemington, NJ 08822|Flemington, PA 17745]

user: Flemington, NJ

bot: Here is the weather for Flemington, NJ:
[Attachment=weather.json adaptivecard]

## Notes
Displaying the postal zip code is useful to disambiguate locations within the same state.  For instance, there are multiple Franklin Townships in NJ.  The postal zip code would allow the user to select their Franklin Township.

**Comment by darrenj** [comment]
Elaine - can you review/prioritise accordingly?
