### ISSUE TITLE
Weather Skill - Add Additional Location Data to Forecast Overview Card

### ISSUE THREAD

**Issue by thegoo** [microsoft/botframework-solutions#2466]
## User Story
As a user I want additional location details on the weather forecast overview such that I am confident I am viewing the location I desire.

## Acceptance Criteria 
*List your requirements.*
- Display location state, province, etc.
- Display location country
- Display location zip code
- Display other relevant details

**Comment by darrenj** [comment]
Elaine - can you review/prioritise accordingly?

**Comment by xieofxie** [comment]
Weird.. Bot seems to work wrongly.
