### ISSUE TITLE
Weather Skill - Initial Intent Re-prompts for Location

### ISSUE THREAD

**Issue by thegoo** [microsoft/botframework-solutions#2467]
#### What project is affected?
Weather Skill
#### What language is this in?
C#
#### What happens?
When conversation is initiated with the weather skill by asking "What is the weather for *location*?", the skill will reply asking for location.
#### What are the steps to reproduce this issue?
- Open Bot Framework Emulator & load bot file w/weather skill
- Ask the question, "What is my question for *location*?"
- Observe that the skill replies asking you to provide the location.
#### What were you expecting to happen?
Weather forecast details will be provided for the location I initiated the conversation with.
#### Can you share any logs, error output, etc.?
Having issues w/ngrok, will provide transcript from emulator if resolved prior to triage or confirmation of bug.  Sorry!
#### Any screenshots or additional context?
See above re: ngrok issues,

**Comment by lauren-mills** [comment]
The current implementation uses a very simple approach with the geography LUIS entity, We should retest with the full LUIS prebuilt domain to verify this is resolved.

**Comment by lauren-mills** [comment]
@thegoo, can you provide an example of the exact utterance with a location that didn't work so we can verify this is resolved?

**Comment by thegoo** [comment]
@lauren-mills - sorry, try "What is the weather in Athens?"

I'm trying to get ngrok working again right now to repro and get the transcript.

**Comment by thegoo** [comment]
@lauren-mills - closing.  I am unable to repro using various cities and utterance structures - "what is" vs. "what's".
