### ISSUE TITLE
Email Skill - Time of Message Not Displaying User Local Time

### ISSUE THREAD

**Issue by thegoo** [microsoft/botframework-solutions#2468]
#### What project is affected?
Email Skill
#### What language is this in?
C#
#### What happens?
On the message overview card, the message received time is not accurate to user locale.
#### What are the steps to reproduce this issue?
- Open Bot Framework Emulator & open bot file w/email skill
- Initiate conversation to view overview card or ask to see new messages
- Observe that the message receive time is not the user locale time.
#### What were you expecting to happen?
The message receive time would reflect my current locale (EST).

#### Any screenshots or additional context?
![image](https://user-images.githubusercontent.com/7401156/66158595-3118ca80-e5f4-11e9-8012-6f63010aed13.png)

**Comment by lauren-mills** [comment]
Needs to be investigated to see if there is a reproducible issue with timezone here.

**Comment by thegoo** [comment]
@lauren-mills - updated issue context w/screenshot from emulator.

**Comment by DingmaomaoBJTU** [comment]
If you are using standalone email skill, please send an message like "/event:{ "Name": "VA.Timezone", "Value": "Pacific Standard Time" }" in emulator to set your timezone.
