### ISSUE TITLE
Email Skill - Ability to Add Recipients to CC or BCC

### ISSUE THREAD

**Issue by thegoo** [microsoft/botframework-solutions#2469]
## User Story
As a user I require the ability to add recipients to the CC or BCC such that I have similar experience to email client authoring capabilities.

## Acceptance Criteria 
*List your requirements.*
- Provide ability to select to add recipient to "To", "CC", or "BCC"

## Notes
Envision this would occur following the step where the skill confirms the individual's email.  Subsequent step would then prompt to ask if they want them added to "To", "CC", or "BCC".

**Comment by AbhishekHumagain** [comment]
Does the bot framework handle multiple to, cc, bcc now on email channel?
