### ISSUE TITLE
Email Skill - View Email Options

### ISSUE THREAD

**Issue by thegoo** [microsoft/botframework-solutions#2470]
## User Story
As an Email Skill admin I require the ability to configure or provide options where to view email such that the end user has an optimal user experience.

## Acceptance Criteria 
*List your requirements.*
- Provide the ability to configure the email skill to view the email via web client; i.e.: outlook.com
- Provide the ability to configure the email skill to launch the default mail client on the device

## Notes
The configuration would determine what the experience is when the end user clicks "View" in the message overview.

**Comment by lauren-mills** [comment]
@thegoo, I think we need the mockup in order to scope this correctly. We're also not sure if this should be an Admin function, or just a user preference on how this should be rendered. 

We can discuss further once we have the mockups.

**Comment by darrenj** [comment]
@thegoo Can you provide more background on the customer scenario/need to help @elaine-chang prioritise this accordingly?
