### ISSUE TITLE
Email Skill - Ability to Flag Emails as Low Importance

### ISSUE THREAD

**Issue by thegoo** [microsoft/botframework-solutions#2471]
## User Story
As a user I require the ability to mark messages I am authoring as low priority such that I have similar email authoring experience as I would from an email client.

## Acceptance Criteria 
*List your requirements.*
- Provide the ability to flag email as low priority
- Email is delivered to recipients as low priority

**Comment by lauren-mills** [comment]
@thegoo It seems like marking an email as High importance is more relevant than marking it as low importance. I'm not sure that Outlook enables marking something as Low importance. Can you verify?

**Comment by thegoo** [comment]
@lauren-mills - Verified in Outlook.

![image](https://user-images.githubusercontent.com/7401156/66152762-2ce6b000-e5e8-11e9-9266-9d950f524f20.png)

Thanks!

**Comment by darrenj** [comment]
@thegoo Can you provide more background on the customer scenario/need to help @elaine-chang prioritise this accordingly?
