### ISSUE TITLE
VirtualAssistant - Unable to Connect to Skill - "Skill Error: DialogContext.ContinueDialogAsync"

### ISSUE THREAD

**Issue by urdurgaprasad** [microsoft/botframework-solutions#2472]
#### What project is affected?
Referred Virtual Assistant and Sample Skill shared in Github repository. 

#### What language is this in?
English

#### What happens?
On Invoking skill, bot is reading input from user and responding with error ""Skill Error: DialogContext.ContinueDialogAsync(): Can't continue dialog. A dialog with an id of 'SkillSample' wasn't found."

#### What are the steps to reproduce this issue?
Connect sample skill with virtual assistant. 
From emulator, invoke the sample skill with utterance sample dialog. 
Type value for name and click on enter. 
VA throws error message, Instead of child bot responding with greening message.

#### What were you expecting to happen?
Child bot should respond with greeting message.

#### Can you share any logs, error output, etc.?
"Skill Error: DialogContext.ContinueDialogAsync(): Can't continue dialog. A dialog with an id of 'SkillSample' wasn't found. | at Microsoft.Bot.Builder.Dialogs.DialogContext.ContinueDialogAsync(CancellationToken cancellationToken)
 at Microsoft.Bot.Builder.Solutions.Dialogs.RouterDialog.OnContinueDialogAsync(DialogContext innerDc, CancellationToken cancellationToken)
 at Microsoft.Bot.Builder.Dialogs.ComponentDialog.ContinueDialogAsync(DialogContext outerDc, CancellationToken cancellationToken)
 at Microsoft.Bot.Builder.Dialogs.DialogContext.ContinueDialogAsync(CancellationToken cancellationToken)
 at Microsoft.Bot.Builder.Dialogs.DialogExtensions.RunAsync(Dialog dialog, ITurnContext turnContext, IStatePropertyAccessor`1 accessor, CancellationToken cancellationToken)
 at SkillSample.Bots.DialogBot`1.OnTurnAsync(ITurnContext turnContext, CancellationToken cancellationToken) in D:\a\1\s\Bots\DialogBot.cs:line 39
 at Microsoft.Bot.Builder.Skills.SkillMiddleware.OnTurnAsync(ITurnContext turnContext, NextDelegate next, CancellationToken cancellationToken)
 at Microsoft.Bot.Builder.Solutions.Middleware.EventDebuggerMiddleware.OnTurnAsync(ITurnContext turnContext, NextDelegate next, CancellationToken cancellationToken)
 at Microsoft.Bot.Builder.Solutions.Middleware.SetLocaleMiddleware.OnTurnAsync(ITurnContext context, NextDelegate next, CancellationToken cancellationToken)
 at Microsoft.Bot.Builder.TelemetryLoggerMiddleware.OnTurnAsync(ITurnContext context, NextDelegate nextTurn, CancellationToken cancellationToken)
 at Microsoft.Bot.Builder.TranscriptLoggerMiddleware.OnTurnAsync(ITurnContext turnContext, NextDelegate nextTurn, CancellationToken cancellationToken)
 at Microsoft.Bot.Builder.MiddlewareSet.ReceiveActivityWithStatusAsync(ITurnContext turnContext, BotCallbackHandler callback, CancellationToken cancellationToken)
 at Microsoft.Bot.Builder.BotAdapter.RunPipelineAsync(ITurnContext turnContext, BotCallbackHandler callback, CancellationToken cancellationToken)

#### Any screenshots or additional context?

![image](https://user-images.githubusercontent.com/38963266/66099837-10a62d00-e56e-11e9-9e4d-4723f79233e3.png)

**Comment by urdurgaprasad** [comment]
Below is the VA error message in direct line channel.

![image](https://user-images.githubusercontent.com/38963266/66099567-f455c080-e56c-11e9-81f5-2a057ae408a6.png)

Tried sample skill directly both in emulator and direct line and it is working fine.
![image](https://user-images.githubusercontent.com/38963266/66099603-15b6ac80-e56d-11e9-9452-02826dbc9247.png)


Sample skill throwing error in web chat.

![image](https://user-images.githubusercontent.com/38963266/66099623-236c3200-e56d-11e9-9713-2e9f5141e962.png)

**Comment by urdurgaprasad** [comment]
@jwiley84, could you please let us know if you have any update on this or need additional details from my side?

**Comment by urdurgaprasad** [comment]
@lauren-mills @CoHealer @jwiley84  Could you please share if you have any update on this issue?

**Comment by xieofxie** [comment]
Hi, @urdurgaprasad  for the first problem "'SkillSample' wasn't found", I suggest you check the following:
1. Does it add a SkillDialog with skill.Id = "SkillSample" [here](https://github.com/microsoft/botframework-solutions/blob/21b876f969cd2fdd11810334083f3f133629d41b/templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Startup.cs#L108)? If not, your skills.json lacks the needed information, you need to ```botskills connect``` again.
2. Then it should add the above skillDialog to MainDialog [here](https://github.com/microsoft/botframework-solutions/blob/21b876f969cd2fdd11810334083f3f133629d41b/templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Dialogs/MainDialog.cs#L59). So it will find the SkillSample dialog.

For the second problem "Sample skill throwing error in web chat.". It is normal since web chat could not render handoff event which indicates the end of a skill's conversation.

**Comment by urdurgaprasad** [comment]
@xieofxie Thank you for the response, please find my answers below.

1) [Durga] In the VA skills.json file, it has reference for skill id i.e. "id": "SkillSample". If you see the screenshots I shared, VA is connecting to child bot/skill and prompted for initial message from dialog. Issue is after user responds to dialog prompt.

2) [Durga] As I answered about, child bot/skill is getting connected initially. Also, code snippets are matching with code in my local.

**Comment by xieofxie** [comment]
@urdurgaprasad My mistake.. I thought "What is your name?" is from VA.

In the log, it seems that SkillSample is not found in Skill. However, it should be a dialog in VA. Did you modify something?

**Comment by urdurgaprasad** [comment]
@xieofxie "What is your name?" prompt is coming from sample skill. 

VA is able to find SkillSample as per the LUIS trace , trigger the dialog from SkillSample, and loosing context after the prompt. Let me know for any additional details.

I didn't modify any thing in the VA :(.

**Comment by xieofxie** [comment]
@urdurgaprasad OK, it seems that your VA and skill use the same cosmosDb and it will cause error like this.

CosmosDb is used to store ConversationState (dialog state in it), UserState etc. For skill and va, they will use same key for same conversation. So when they use same cosmosDb, the following happens:

* VA receives "sample dialog" and starts SkillSample dialog
* Skill receives "sample dialog" and starts SampleDialog, then saves its dialog state to cosmosDb
* VA ends its turn and saves its dialog state to comosDb (overwrite the above one)
* VA receives "Durga" and reads dialog state from cosmosDb, so it continues SkillSample dialog as saved
* Skill receives "Durga" and reads dialog state from cosmosDb, however, it does not have SkillSample dialog

Each bot should use its own cosmosDb and I think it will fix the error.

**Comment by urdurgaprasad** [comment]
@xieofxie , you are right..currently am using same cosmosDB for VA and skill.

Let me try with different cosmosDB and comeback to you.

Thank you for the response.

**Comment by urdurgaprasad** [comment]
@xieofxie sample skill dialog flow working fine after creating seperate cosmosDB account. 

Is there any way, we can use same cosomosDB for multiple skills?

**Comment by xieofxie** [comment]
@urdurgaprasad If you really want to do so, you could override GetStorageKey of [ConversationState](https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder/ConversationState.cs) and [UserState](https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder/UserState.cs). For example, add appId as part of the key..
