### ISSUE TITLE
[ITSM] skill - dispatch model issue

### ISSUE THREAD

**Issue by SethuSP** [microsoft/botframework-solutions#2473]
#### What project is affected?
ITSM skill project

#### What language is this in?
cs

#### What happens?
When creating the resources, the training cognitive models fails as the dispatch model is getting failed due to duplicate utterence removal

#### What are the steps to reproduce this issue?
Try to deploy the resources using deploy.ps1. The 

#### What were you expecting to happen?
Provisioning and training of LUIS apps without fail

#### Can you share any logs, error output, etc.?

Updating ITSMSkillBoten_Dispatch model...
WARNING: some intents do not have any utterances due to duplicate removal, they are l_KnowledgeShow,l_TicketClose,l_TicketCreate,l_TicketShow,l_TicketUpdate
Training ITSMSkillBoten_General...
Training ITSMSkillBoten_ITSM...
Training ITSMSkillBoten_KnowledgeShow...
Training ITSMSkillBoten_TicketClose...
Training ITSMSkillBoten_TicketCreate...
Training ITSMSkillBoten_TicketShow...
Training ITSMSkillBoten_TicketUpdate...
Importing ITSMSkillBoten_Dispatch model...
Setting up intents to child services mapping for ITSMSkillBoten_Dispatch...
Add subscription key and publish child LUIS apps...
Publishing ITSMSkillBoten_General model...
Publishing ITSMSkillBoten_ITSM model...
Publishing ITSMSkillBoten_KnowledgeShow model...
Publishing ITSMSkillBoten_TicketClose model...
Publishing ITSMSkillBoten_TicketCreate model...
Publishing ITSMSkillBoten_TicketShow model...
Publishing ITSMSkillBoten_TicketUpdate model...
Training ITSMSkillBoten_Dispatch model...

ERROR
Training failed

**Comment by darrenj** [comment]
Hi,

I've taken a quick look and think there might be a mistake with the deploy_cognitive_models.ps1 script in that it's forcing use of dispatch which is not needed. 

You could perhaps prove this theory by modifying your `deployment/scripts/deploy_cognitive_models.ps1` and changing this line at the top:

```
	[switch] $useDispatch = $true,
```

to
```
	[switch] $useDispatch,
```

**Comment by darrenj** [comment]
We  have a pull request to make this change, let us know if you are still having issues.
