### ISSUE TITLE
[POI] When a user searches for a POI by keyword, return unique results back

### ISSUE THREAD

**Issue by ryanisgrig** [microsoft/botframework-solutions#2474]
## User Story
As ... a bot user
I want ... the POI Skill to return unique POIs to if I search for generic categories
so that ... I don't have to sort through results of the same POI

## Acceptance Criteria 
*List your requirements.*
- [ ] If a user searches for a category, return unique POIs back
- [ ] If a user searches for a specific POI brand, return multiple locations
- [ ] If a user searches for the nearest specific POI brand, return a single location

## Resources
*Provide any screenshots or conversation mockups to support your request.*
*Learn how to mock up bot conversations with [.chat files](http://aka.ms/bfchatfile).*

user: find a coffee shop
bot: I found the following
[Attachment=pointofinterestoverview.json adaptivecard with 3 unique coffee shops: Starbucks, Coffeeshop B, Coffeeshop C]

user: find a starbucks
bot: I found the following
[Attachment=pointofinterestoverview.json adaptivecard with 3 unique coffee shops: Starbucks, Starbucks, Starbucks]

user: find the nearest starbucks
bot: I found the following
[Attachment=pointofinterestoverview.json adaptivecard with the nearest Starbucks]

user: find a starbucks
bot: I found the following

## Notes
*Provide any additional information.*

**Comment by xieofxie** [comment]
Hi, @ryanlengel 
Since category and brand are interchangeable in utterances, it is quite complicated to identify new ones (from my point of view).

To simplify the scenario, we could use list entity for categories and treat everything else as brands.

Or search the keyword twice as category and as brand and compare their matching scores to generate best results.

What do you think?

**Comment by ryanisgrig** [comment]
Hey @xieofxie, sorry for the delay. Yes I think the former (using list entity) makes more sense. I think searching twice and comparing may introduce undesired performance issues.
