### ISSUE TITLE
[Docs] Virtual Assistant Architecture diagram on architecture.md is broken

### ISSUE THREAD

**Issue by rjgmail88** [microsoft/botframework-solutions#2478]
**Please describe your request**
After navigating to [here](https://github.com/microsoft/botframework-solutions/blob/b4e8d92f565463ad177c6622eb3ad3ae5f492afb/docs/_docs/reference/virtual-assistant/architecture.md) I see Virtual Assistant Architecture link is going nowhere. It give 404 no found error. 

**Is this an issue with current documentation? If yes, please provide the link.**

https://github.com/microsoft/botframework-solutions/blob/b4e8d92f565463ad177c6622eb3ad3ae5f492afb/docs/_docs/reference/virtual-assistant/architecture.md

**Comment by lauren-mills** [comment]
Hi @rjgmail88, our docs are now being published from this repo to a GitHub pages site, so some of the links won't work when you're viewing in GitHub. You can view this doc on the published site here: https://microsoft.github.io/botframework-solutions/reference/virtual-assistant/architecture/

**Comment by lauren-mills** [comment]
Closing, since the link to the doc site should resolve this.
