### ISSUE TITLE
[TypeScript] Enable use of WebSocket for communication with VA/Skill

### ISSUE THREAD

**Issue by dfavretto** [microsoft/botframework-solutions#2480]
## User Story
As ...a developer
I want … to implement [_BotBuilderStreamingExtension_](https://github.com/microsoft/botbuilder-js/tree/master/libraries/botbuilder-streaming-extensions) in the **TypeScript** Samples
so that … I can use _WebSocket_ to connect with the VA or Skill.

## Acceptance Criteria 
*List your requirements.*
- [ ] Deploy a VA with the _Direct Line Speech_ (_DLS_) channel enabled and successfully connect and communicate to the VA with a _DLS Client_
- [ ] Have a VA communicate with a Skill using _WebSocket_ instead of _HTTP_
- [ ] Re-enable the scenario of cross-connecting between different coding languages (i.e. **TypeScript** VA with a **C#** Skill; **C#** VA with a **TypeScript** Skill)

## Resources
*Provide any screenshots or conversation mockups to support your request.*
*Learn how to mock up bot conversations with [.chat files](http://aka.ms/bfchatfile).*

There's a first implementation in [_BotBuilder-Samples/experimental/Echo-Bot_](https://github.com/microsoft/BotBuilder-Samples/tree/master/experimental/directline-speech/javascript_nodejs/02.echo-bot). This is a basic implementation of the _WebSocket_ functionality.

## Notes
*Provide any additional information.*
At the moment, the _BotBuilderStreamingExtension_ library is published to [_MyGet_](https://botbuilder.myget.org/feed/botbuilder-v4-js-daily/package/npm/botbuilder-streaming-extensions) as it's not a stable version yet, and some issues may arise during the implementation.

**Comment by Batta32** [comment]
I'll close this issue because it will be tracked [here](https://github.com/microsoft/botframework-solutions/issues/2489).
