### ISSUE TITLE
[Analytics] ConversationID

### ISSUE THREAD

**Issue by tiagodenoronha** [microsoft/botframework-solutions#2481]
#### What project is affected?
Virtual Assistant Template

#### What language is this in?
C#

#### What happens?
The ConversationID is always using the same value. I'm using the webchat component to interact with the ChatBot, do I need to pass some value there?

#### What are the steps to reproduce this issue?
Deploy a Virtual Assistant Template and talk to him a bit!

#### What were you expecting to happen?
A new ConversationID to be generated

#### Can you share any logs, error output, etc.?
What would be helpful?

#### Any screenshots or additional context?
![imagem](https://user-images.githubusercontent.com/27889458/66253880-9ab8e600-e766-11e9-9860-3e909789b555.png)

**Comment by lauren-mills** [comment]
Are you using your own webchat implementation, or are you testing in the Azure Portal?

**Comment by tiagodenoronha** [comment]
Using the default webchat here: https://github.com/microsoft/BotFramework-WebChat#how-to-use with the only difference that I'm passing an UUID as the userID.

Should I follow up with the webchat team?

**Comment by lauren-mills** [comment]
@tiagodenoronha possibly. I've assigned the Support team to take a look first, and they can transfer it over to the web chat repo, if needed.

**Comment by tiagodenoronha** [comment]
Thanks! I'll wait and try to debug on my side as well!

**Comment by tiagodenoronha** [comment]
Managed to fix it on my side. Got a weird error, dunno why, but I redeployed the environment and the chatbot and now we're all ok!
