### ISSUE TITLE
issue when using MultiProviderAuthDialog in core bot

### ISSUE THREAD

**Issue by mouhannadali** [microsoft/botframework-solutions#2495]
#### What project is affected?
Microsoft.Bot.Builder.Solutions.Authentication
#### What language is this in?
c#
#### What happens?

I have implement MultiProviderAuthDialog in the core-bot template for authentication using GenericOauth2 
when I try to use resulting token, I get an exception that the token is invalid.
I have test the connection in Azure portal:
![image](https://user-images.githubusercontent.com/17967903/66478771-65c8ce00-ea9b-11e9-8b39-99d6ab49ee01.png)

and the resulting token is working properly.
However, I start to debug MultiProviderAuthDialog.cs  and the issue was because of line 343:
 var tokenProvider = context.Adapter as IUserTokenProvider;
                if (tokenProvider != null)
                {
                    return await tokenProvider.GetTokenStatusAsync(context, userId, includeFilter, cancellationToken).ConfigureAwait(false);

when ever this step is executed the resulting token is not valid anymore.

**Comment by darrenj** [comment]
Apologies for the delay @mouhannadali. Can you share a little more on the scenario? What channel/adapter are you using to test the Bot and which SDK version are you using?

IUserTokenProvider is supported by the base Adapter to provide authentication scenarios, the same as OAuthPrompt so just double checking your scenario to try and repro as the interface should be implemented on the adapter.

**Comment by mouhannadali** [comment]
Hi @darrenj, I am using base Adabter SDK V4. I am not sure you will be able to reproduce because I am using GenericOauth2. 
what might help if you can give me some information what is happening at this step: Line 345
return await tokenProvider.GetTokenStatusAsync(context, context.Activity.From.Id, includeFilter, cancellationToken).ConfigureAwait(false);

because for some reason, every time  this line is executed, my token is not valid any more

**Comment by lauren-mills** [comment]
@mouhannadali the GetTokenStatus method is exposed by the Microsoft.Bot.Builder lib to get all the current oauth connections for the user from the Azure Bot Service token service. 

There is a little more detail in the method summary here: https://github.com/microsoft/botbuilder-dotnet/blob/14dc8aba63f3bb5a2783ce53772ac1802dee4cbb/libraries/Microsoft.Bot.Builder/IUserTokenProvider.cs#L66

Here is the implementation in BotAdapter: https://github.com/microsoft/botbuilder-dotnet/blob/e1fa19c1ddf3459e90500d5791e0101a368ed2c4/libraries/Microsoft.Bot.Builder/BotFrameworkAdapter.cs#L816

And here is the implementation of UserToken.GetTokenStatusAsync: https://github.com/microsoft/botbuilder-dotnet/blob/8ec0da2852c0d8565d3d49c35ee963b818fe29ba/libraries/Microsoft.Bot.Connector/UserTokenExtensions.cs#L100

It appears that it is just making an API call to the service to get the tokens, so there might be something happening on the service side that's corrupting your token.

Have you verified you are able to log in with your oauth connection through an OAuthPrompt?

**Comment by mouhannadali** [comment]
Hi, thanks for the update. yes I am able to log in through an OAuthPrompt. As you said, it looks like something happening on the service side that's corrupting token.
