### ISSUE TITLE
[Docs] advanced conversational analytics link broken

### ISSUE THREAD

**Issue by rjgmail88** [microsoft/botframework-solutions#2498]
**Please describe your request**

I am looking at this [architecture document](https://microsoft.github.io/botframework-solutions/reference/virtual-assistant/architecture/) and looks like it has a broken link for advanced conversational analytics which goes [here](https://github.com/microsoft/botframework-solutions/blob/master/samples/analytics/ConversationalAnalyticsSample_4_6_1.pbit) 

**Is this an issue with current documentation? If yes, please provide the link.**
https://github.com/microsoft/botframework-solutions/blob/master/samples/analytics/ConversationalAnalyticsSample_4_6_1.pbit

**Comment by ryanisgrig** [comment]
@rjgmail88 this doc points to https://aka.ms/botPowerBiTemplate, which is in fact the correct URL (the Power BI `.pbit` file). In our next release this will point to a tutorial on how to download and set up the Power BI dashboard.

**preview screenshots**
![image](https://user-images.githubusercontent.com/43043272/66183418-bbc9eb80-e62d-11e9-83eb-511ed8737613.png)
![image](https://user-images.githubusercontent.com/43043272/66183432-c7b5ad80-e62d-11e9-8e0d-e07e2c384271.png)
![image](https://user-images.githubusercontent.com/43043272/66183449-d0a67f00-e62d-11e9-965a-161b44988de3.png)
