### ISSUE TITLE
[Docs] Missing html page title & icon

### ISSUE THREAD

**Issue by christopheranderson** [microsoft/botframework-solutions#2500]
**Please describe your request**

This is a nit. Currently the docs don't set the title attribute and the favicon link doesn't exist, so you get a non-helpful looking tab on most browsers. See below:

![image](https://user-images.githubusercontent.com/2252976/66518908-1aaebb00-ea9b-11e9-9ecc-6961aa699edf.png)

Simplest solution would be to add a title with "Bot Framework Solutions" to the head section for default.html and tutorial.html: https://github.com/microsoft/botframework-solutions/blob/master/docs/_layouts/default.html#L6 & add a favicon to the repo. 

If you're using jekyll (kinda looks like it), you can use [`page.title` in the metadata section](https://jekyllrb.com/docs/variables/#page-variables) to do it on a page by page basis and provide a more helpful title.

**Is this an issue with current documentation? If yes, please provide the link.**

Yes - all pages (from what I can tell after clicking through a few of them)

**Comment by ryanisgrig** [comment]
Agreed, we'll implement this in our next release. Thanks!
