### ISSUE TITLE
virtual assistant template -  Could not deploy automatically to Azure.

### ISSUE THREAD

**Issue by Hari-c4** [microsoft/botframework-solutions#2501]
I tried to run deploy.ps1 script in powershell. All the resources have been created in the azure portal but in the last step while "Publishing to Azure" an error occurs, here is the error

! Could not deploy automatically to Azure. Review the log for more information.
! Error: ERROR: az: error: unrecognized arguments: Assistant\eva-test\eva\eva\eva\eva\code.zip
! Log: C:\Hari\Work\AI\virtual Assistant\eva-test\eva\eva\eva\eva\Deployment\Scripts\..\publish_log.txt

![deployment-issue](https://user-images.githubusercontent.com/56388643/66557907-510a3a00-eb70-11e9-8dbd-9ae2d3b59974.jpg)

Here is what I found in publish_log.txt

Microsoft (R) Build Engine version 16.3.0+0f4c62fea for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

ERROR: az: error: unrecognized arguments: Assistant\eva-test\eva\eva\eva\eva\code.zip
usage: az [-h] [--verbose] [--debug]
          [--output {json,jsonc,table,tsv,yaml,none}] [--query JMESPATH]
          {webapp} ...

**Comment by xieofxie** [comment]
May be caused by space in "Virtual Assistant". And your password is in screenshot..

**Comment by Hari-c4** [comment]
> May be caused by space in "Virtual Assistant". And your password is in screenshot..

Thanks.Its working now.
