### ISSUE TITLE
[Android] Remove speech/bot config from the settings page

### ISSUE THREAD

**Issue by ryanisgrig** [microsoft/botframework-solutions#2506]
## User Story
As ... an Android app user
I want ... to only have the bot endpoint/speech key configured in backend
so that ... I don't break my configuration (especially if I don't know the endpoint of the bot I am testing against)

## Acceptance Criteria 
*List your requirements.*
- [ ] Remove speech key from settings page
- [ ] Remove speech region from settings page
- [ ] Remove direct line speech key from settings page

## Resources
*Provide any screenshots or conversation mockups to support your request.*
*Learn how to mock up bot conversations with [.chat files](http://aka.ms/bfchatfile).*

## Notes
*Provide any additional information.*
As the Android app is distributed to users they should not be expected to configure their own speech key or bot endpoint, that would be included in the application configuration itself.

**Comment by darrenj** [comment]
How would someone with an Android app installed be able to update things without rebuilding the app? Provided there is a "on device" way of changing configuration I think we're good otherwise the configuration provided a non-recompile way of changing things when testing.

**Comment by ryanisgrig** [comment]
@darrenj in that case that is fine, it's just if we leave these as available settings we run the risk of someone downloading a demo application, deleting the key to a bot endpoint they don't know, and being unable to reconnect.
