### ISSUE TITLE
Make SendActivityAsync Trace optional in SkillDialog

### ISSUE THREAD

**Issue by xieofxie** [microsoft/botframework-solutions#2520]
## User Story
As ... a dev
I want ... to better performance
so that ... do not send unnecessary messages

## Acceptance Criteria 
*List your requirements.*
- [ ] ... Make SendActivityAsync ActivityTypes.Trace optional in SkillDialog
- [ ] ...
- [ ] ...

## Resources
*Provide any screenshots or conversation mockups to support your request.*
*Learn how to mock up bot conversations with [.chat files](http://aka.ms/bfchatfile).*

## Notes
*Provide any additional information.*

**Comment by darrenj** [comment]
I believe these are filtered about by the adapter(s) if the Emulator channel isn't being used - i.e. they are only sent when using the Emulator.

**Comment by xieofxie** [comment]
I see.. it is here https://github.com/microsoft/botframework-solutions/blob/21b876f969cd2fdd11810334083f3f133629d41b/lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/SkillWebSocketBotAdapter.cs#L124 thanks~
