### ISSUE TITLE
Cannot open Power BI report template.

### ISSUE THREAD

**Issue by abditimer** [microsoft/botframework-solutions#253]
**Project**

Enterprise Bot Template

**Description**

After downloading the PBI report, as instructed in the docs, the file has an error that does not allow me to open it.

**To Reproduce**

1. Download the .pbi file from: AI/templates/Enterprise-Template/src/csharp/EnterpriseBotTemplate/Bot Framework/PowerBI/
2. Open the file locally using my desktop PBI

**Expected behavior**

I expected it to open and ask for an App Id as instructed in the docs.

**Screenshots**

**Additional context**

**Comment by lauren-mills** [comment]
Hi @abditimer do you have a screenshot of the error?

**Comment by darrenj** [comment]
@abditimer Do you have [PowerBI desktop](https://powerbi.microsoft.com/en-us/desktop/) installed?

**Comment by NobinJoseRad** [comment]
I had no issues opening the Power BI report. I guess you need to update the PBI Desktop to latest version.

**Comment by abditimer** [comment]
I've done some more investigating - I believe it is an issue with the version of PBI I have. Another work colleague opened the file successfully.
