### ISSUE TITLE
[Docs]  You can view your Feedback in the "Feedback tab of the Conversational AI Dashboard"

### ISSUE THREAD

**Issue by infact** [microsoft/botframework-solutions#2533]
**Please describe your request**

**Is this an issue with current documentation? If yes, please provide the link.**
https://microsoft.github.io/botframework-solutions/howto/virtual-assistant/feedback/

You can view your Feedback in the "Feedback tab of the Conversational AI Dashboard".Could you please add some more detail. Where is this  "Feedback tab of the Conversational AI Dashboard" ?

**Comment by lauren-mills** [comment]
We can add a screenshot of where to find this tab.
