### ISSUE TITLE
Integrating News Skill with VA 

### ISSUE THREAD

**Issue by Adityagrao** [microsoft/botframework-solutions#2535]
#### What project is affected?
C# SDK 4.5.3
#### What happens?
The news skills work Independently but when connected with the VA, the handoff is successful but the news skill bot does not reply, please see the screenshots attached

#### Any screenshots or additional context?

When the News skill is called from the VA Bot
![image](https://user-images.githubusercontent.com/11465032/66894676-a92cba80-f00e-11e9-96c1-4ce0c0db14ec.png)

When the News skill is Independent
![image](https://user-images.githubusercontent.com/11465032/66894773-e3965780-f00e-11e9-8d0c-318a008fcf88.png)

**Comment by xieofxie** [comment]
Hi, @Adityagrao  since skills are updated to 4.5.4, please update solutions and skills to 4.5.4 in VA too.
