### ISSUE TITLE
AssistantSpeechsimpleApp- Namespace name SpeechBotConnector could not be  found

### ISSUE THREAD

**Issue by diana-RC** [microsoft/botframework-solutions#2538]
#### What project is affected?
AssistantsimplespeechApp 
#### What language is this in?
c#
#### What happens?
I am trying to enable speech for virtual assistant from the following document 
https://microsoft.github.io/botframework-solutions/tutorials/enable-speech/4_integrate_speech_channel/

#### What are the steps to reproduce this issue?
I am trying to build this application after changing the secret keys. I am using Visual Studio 2109, .NetCore SDK 3.0, .Net Framework 4.8. I have added some NuGet packages but it didn.t help

#### What were you expecting to happen?
It should build without errors. When I first load the assistantsimplespeechapp.sln file it is asking me to install windows10 sdk core and i have installed it. And as soon as the program is loaded it throws this error

#### Can you share any logs, error output, etc.?
Error	CS0246	The type or namespace name 'SpeechBotConnector' could not be found (are you missing a using directive or an assembly reference?)	
Error	CS0103	The name 'BotConnectorConfig' does not exist in the current context	assistant-SimpleSpeechApp

#### Any screenshots or additional context?
![assistant-simplespeechapp-screenshot1](https://user-images.githubusercontent.com/55460938/66937128-cecdba00-f036-11e9-9640-aee91c015988.PNG)

Please help
Thanks in advance

**Comment by xieofxie** [comment]
hi @diana-RC, the package is here https://www.nuget.org/packages/Microsoft.CognitiveServices.Speech/1.5.1, could you try uninstall and install it again? It seems that 1.5.1 is required

**Comment by diana-RC** [comment]
Great! It solved my issue. Thank you @xieofxie. thanks a lot

> hi @diana-RC, the package is here https://www.nuget.org/packages/Microsoft.CognitiveServices.Speech/1.5.1, could you try uninstall and install it again? It seems that 1.5.1 is required
