### ISSUE TITLE
Deploy script fails if the 31st character of the name is a "-"

### ISSUE THREAD

**Issue by lucascrandle** [microsoft/botframework-solutions#2539]
#### What project is affected?
Virtual Assistant
#### What language is this in?
English
#### What happens?
If the name of the resource happens to have a "-" at the 31st character, then the database account name will have a "-" at the end of it, and make the database account creation fail.

The database account name can contain a "-", but can't end with it. Also, it has a 31 character limit, so the template.json does a substring and puts the "-" at the end of the name.
#### What are the steps to reproduce this issue?
try the deployment script with resource name "123456789123456789123456789123-anything"
#### What were you expecting to happen?
It not to fail :) Maybe do a substring to 29 characters and put a dummy "db" on the end of all db accounts created this way. Like this:
    "cosmosDbAccountName": "[concat(toLower(take(replace(parameters('cosmosDbName'), '_', ''), 29)), 'db')]",
#### Can you share any logs, error output, etc.?
Deployment failed. Correlation ID: 3b735c3b-36d5-492a-9e81-e072d166267d. {
  "code": "BadRequest",
  "message": "The character '-' at index 30 is not allowed in the DatabaseAccount name\r\nActivityId: da0e8a2f-281c-4027-87cd-9ac1985b19e4, Microsoft.Azure.Documents.Common/2.7.0"
}
! Deployment failed. Please refer to the log file for more information.
#### Any screenshots or additional context?
![image](https://user-images.githubusercontent.com/16657988/66944054-6bce2a00-f01a-11e9-9beb-c03ef0f2f45a.png)
![image](https://user-images.githubusercontent.com/16657988/66944112-8ef8d980-f01a-11e9-9c41-9c3cba74a263.png)

**Comment by lauren-mills** [comment]
Hi @lucascrandle, thanks for reporting this! I've added it to our backlog for a future release. 

If you'd like to get it in sooner, we'd be happy to take a PR with this change.

**Comment by lucascrandle** [comment]
Thanks @lauren-mills, I modified my local template file for now. A future release is fine.

**Comment by darrenj** [comment]
Resolved with latest deployment scripts
