### ISSUE TITLE
Merge Cognitive-Services-Direct-Line-Speech-Client and assistant-SimpleSpeechApp

### ISSUE THREAD

**Issue by xieofxie** [microsoft/botframework-solutions#2540]
## User Story
As ... anyone
I want ... to unify speech client
so that ... it is easier

## Acceptance Criteria 
*List your requirements.*
- [ ] ... Mention https://github.com/Azure-Samples/Cognitive-Services-Direct-Line-Speech-Client in doc
- [ ] ... Or update https://github.com/microsoft/botframework-solutions/tree/master/samples/clients/csharp/assistant-SimpleSpeechApp
- [ ] ...

## Resources
*Provide any screenshots or conversation mockups to support your request.*
*Learn how to mock up bot conversations with [.chat files](http://aka.ms/bfchatfile).*

## Notes
*Provide any additional information.*

**Comment by darrenj** [comment]
Good spot but this is already addressed in the new docs :-)
