### ISSUE TITLE
[Skills] Advanced contextual history related experience improvement based on multi-turn conversation

### ISSUE THREAD

**Issue by DingmaomaoBJTU** [microsoft/botframework-solutions#2541]
## User Story
As ...
I want ...
so that ...

## Acceptance Criteria 
**Auto Suggestion** #2542
Goal: Provide using TIPS for user when: 
- [x] Onboarding  item 
- [x] Bot could not understand what user wants
- [ ] Dynamic hint to help user shorten slot filling process
Based on:
1.	User input history
2.	Common phrase for VA/Skills (source from usage data)
3.	Prebuilt LUIS file with utterance and entity

Example scenario:
[On boarding]
> Suggestions:  user history data + common used utterance data

Auto suggestion when bot not understand
> User: show email
> Bot: email list
> User: fooorward this email
> Bot: Sorry, I don't understand, do you mean "forward an email"?

---
**Personal info:** #2543
Goal: Extract user personal information based on user input and resolve context with user personal information/API, like:
- [x] User relative contact name, like my wife, my manager, my parents, my team
- [ ] User basic information, like my home, my email, my workplace
Base on:
1.	API, i.e. Msgraph [my manager/somebody's manager/my team] -- by skill level injection
2.	Customer collection information [my home address, my wife] -- by fallback flow and information storage
 
Additional fallback flow: confirm waterfall
•	Confirm user information which cannot be resolved, like "who is your wife?" "where is your home address?" "who is your manager?" "what is your team alias?"  -- save to user state

Example scenario:
User information (my ***) from Graph API
> User: send an email to **my manager**
> Bot: is this Jim who you want?
> User: yes
> Bot: OK, got it. I have already add Jim to the recipient list. Who else do you want to add?
 
User information with fallback
> User: send an email to **my wife**
> Bot: who is your wife
> User: Megan
> Bot: is this Megan who you want?
> User: yes
> Bot: OK, got it. I have already add Megan to the recipient list. Who else do you want to add?
---
**Anaphora:** #2434
Goal: Anaphora resolution based on context. Resolve things like:
- [x]  [Pronoun] e.g. Add **Tom** to the meeting recipients. Also send an email to **him**.
- [ ] [Demonstrative] e.g. Show me **the first email**. And forward **this one**.
- [ ] [Definite Description] e.g. Book a meeting at the **same time** and **same location tomorrow**.

Example scenario:
Pronoun
> User: Book a meeting with Lily.
> Bot: I have add Lily to the recipient list. Who else do you want to add?
> …
> Bot: Done.
> User: Also forward this email to her.
---
**Sentiment** #2623
Goal: Change bot behavior based on user sentiment.
https://azure.microsoft.com/en-us/updates/sentiment-v3-preview/

Example scenario:
> User: I feel sad, please play a song for me.
> Bot: (Play a comfort song)
---

**Design**
Framework Design:
![image](https://user-images.githubusercontent.com/16643193/66975319-ba3e0000-f0d0-11e9-90ab-505ff33bc52f.png)

To enable contextual history, the skill should do the following:
1.	Let the contextual lib process/save its input, e.g. using SkillContextualMiddleware or save it manually
2.	Resolve contextual information with resolvers in contextual lib, e.g. SkillContextualWaterfall, UserContextManager with customized context resolver, UserStateContextResolver and UserHistoryContextResolver
 
Contextual middleware:
Actions can be injected to this middleware to customize what steps should be taken during process. Will include the following:
1.	GetSentimentAction to analysis user sentiment (Sentiment)
2.	CachePreviousTriggerIntentAction to remember user behavior (Auto Suggestion)
3.	CacheCoreferenceResolutionInformationAction to do Anaphora resolution (Anaphora resolution)
 
SkillContextualWaterfall:
This is a default waterfall to resolve user context with UserContextManager, when cannot resolve target context, will prompt to ask user and save related values as fallback behavior.
 
UserContextManager:
It will resolve user context with different resolvers. Skill can inject its own resolver if they want to customize, and also provide UserStateContextResolver and UserHistoryContextResolver as default resolver.
For a resolver, it will support the following:
1.	Resolve related contacts like my manager, my wife
2.	Resolve address
3.	Resolve email
4.	Anaphora resolution
….
The resolve priority will be like:
1.	Check the injection
2.	Check user state
3.	Check user history

**Comment by lauren-mills** [comment]
Adding @emivers8 and @darrenj to take a look at and comment on this design.
