### ISSUE TITLE
[Skills] Auto suggestion based on contextual history

### ISSUE THREAD

**Issue by DingmaomaoBJTU** [microsoft/botframework-solutions#2542]
**Goal:**
Provide using TIPS for user when: 
1.	Onboarding  item 
2.	Bot could not understand what user wants
3.	Dynamic hint to help user shorten slot filling process
Based on:
1.	User input history
2.	Common phrase for VA/Skills (source from usage data)
3.	Prebuilt LUIS file with utterance and entity 
 
**Scenarios:**
- [ ] **Scenario 1 : (onboarding)**
As a user, When I am onboarding the skills or VA, I want a more user friendly bot. so I want the bot could auto suggest me how I start the conversation.
Bot can say something like "Hello, <user name>, I am <skill name>. How may I help you"
Option 1:
The bot could do auto suggestion as a tip like say 'Help' for more suggestions.
Following  will be auto suggested  in  "choicinput" ("adaptive card" later)
 
- Your history
<list out 3~5 items>
 
-Skill List
<Available skills> &  Common question (3~5 items per skill)
 
User can click or speak one item and proceed the conversation.
 
Option2:
The bot could do auto suggestion by default ranking 
-First 3 items are user history data
-Last 3 items are randomized common questions for skill 
 
Feature requirement
- Get current user history data from cosmosDB
- Get all user data from app insight and analyze the data per skill for common questions
•	Provide a tool for VA administrator to poll user data in App Insight and find pattern for most useful utterance per skill  
 
 
- [ ] **Scenario 2: (Unrecognized intent)**
As a user, I don't know how to communicate with the bot if I am a new user. If I input something wrong, bot could auto suggest and teach me how to ask the correct question, that will make things more efficient.
So when I input or say something like "I want...", the bot could answer me like following.
"sorry, I don't understand you, do you mean 'I want to book the meeting?'".
 
Feature requirment
- no match intent in skill, serch for similarity of the utterance (bettween user input and common used utterance in skills ) , based on treashhold to auto suggest to end user
•	First to suggest similarity utterance
•	Second to suggest top utterance (if no similarity )
-no match intent in va, fallback to scenario 1 (user data & common questions for skill)
 
- [ ] **Scenario 3 : (Multi turn)** 
If my question is more similar as specific intent, bot could auto suggest like " do you mean ' I want to book the meeting at 2pm today in meeting room greatwall'".
The goal is to minimize the turn counts and clarify the entity slot filling.
 
Feature requirment
•	Provide the tip (pattern based on intent and entity from luis file)

**Comment by lauren-mills** [comment]
Adding @emivers8 and @darrenj to take a look at and comment on this design.
