### ISSUE TITLE
Editorial Improvement: Change login box wording to "Sign in to your Office 365 account"

### ISSUE THREAD

**Issue by fractalcrafter** [microsoft/botframework-solutions#2557]
#### What are the steps to reproduce this issue?
Any utterance that will trigger email or calendar or todo skill. 

#### What were you expecting to happen?
"Login with Outlook" should be rephrased to "Sign in to your Office 365 account"

#### Any screenshots or additional context?
![image](https://user-images.githubusercontent.com/25210203/67242772-170c2400-f40b-11e9-9e35-4fd28ea4bce2.png)
`

**Comment by darrenj** [comment]
Explore options within each of the productivity skills

**Comment by pavolum** [comment]
Text has been changed in linked PR to be 'Sign in to your {0} account' as opposed to "Login with {0}" where {0} is this connection setting name chosen by the developer when they link authentication to their bot (https://microsoft.github.io/botframework-solutions/skills/handbook/authentication/#manual-authentication)

It us up to the developer to call their connection setting name 'Office 365' to render the desired UX outlined in this bug.
