### ISSUE TITLE
Feedback Editorial Improvement: Update neutral response to "Thanks, I appreciate your feedback."

### ISSUE THREAD

**Issue by fractalcrafter** [microsoft/botframework-solutions#2558]
#### What were you expecting to happen?
Thumb down reaction response of "Thank you for your feedback!" is not appropriate. We've agreed to update to "Thanks, I appreciate your feedback." 

#### Any screenshots or additional context?
 ![image](https://user-images.githubusercontent.com/25210203/67243147-cba64580-f40b-11e9-98b8-dcdacd497190.png)
![image](https://user-images.githubusercontent.com/25210203/67243151-cea13600-f40b-11e9-9bf4-82cd94e0afff.png)

**Comment by pavolum** [comment]
Fix has been implemented in #2980
