### ISSUE TITLE
Integrating virtual assistant with Direct Line Speech Channel

### ISSUE THREAD

**Issue by diana-RC** [microsoft/botframework-solutions#2564]
#### What project is affected?
I have enabled the speech in the Virtual assistant following this document
https://microsoft.github.io/botframework-solutions/tutorials/enable-speech/4_integrate_speech_channel/

#### What language is this in?
c#   . I have created all the resource in westeurope region and Speech instance as westUs2
#### What happens?
When I run the assistant-Simple Speech App sometimes first time it is speaking the right answer and after that it is saying "what else I can help you with". Sometimes from the beginning it is saying "what else I can help you with"
#### What are the steps to reproduce this issue?
I have deleted the Completed value(what else I can help you with) in  the Response/Main/MainString.resx . But still I am getting Virtual assistant response as "what else I can help you with".
Sometimes I can hear skipping the exact answer eg: If I ask what is your name? It is saying" My name" and then skipping to "what else I can help you with". 
#### What were you expecting to happen?
The virtual assistant should answer the Q and A 
#### Can you share any logs, error output, etc.?
And also the direct line speech App screen is not refreshing. It is showing my first question always.

#### Any screenshots or additional context?
![assistant-simplespeechapp-screenshot2](https://user-images.githubusercontent.com/55460938/67299564-bc46fb00-f4e4-11e9-9c8f-1ec2a35440d9.PNG)

**Comment by ryanisgrig** [comment]
Hi @diana-RC,

I've got a couple of suggestions:
1. We are going to deprecate this speech app in our next release in favor of the [Cognitive Services Direct Line Speech Client](https://github.com/Azure-Samples/Cognitive-Services-Direct-Line-Speech-Client), so I would recommend migrating over to that for better analytics and features.
2. It is recommended that all of your resources are in the same region, there is likely some latency using a West US speech key with West Europe bot resources.
3. The completed response is triggered at [line 289 of the MainDialog](https://github.com/microsoft/botframework-solutions/blob/master/templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Dialogs/MainDialog.cs#L289), you should just have to comment that out and no longer hear that from your VA.

**Comment by diana-RC** [comment]
Hi @ryanlengel ,

Thank u for the suggestion.
For the first suggestion:
I have tried Cognitive Service Direct Line Speech Client following this below document
https://docs.microsoft.com/bs-latn-ba/azure/cognitive-services/speech-service/tutorial-voice-enable-your-bot-speech-sdk

I have tried it with the echo bot and I have followed all the steps and have created all the resources as said in the document. The Direct line speech client is actually saying "Hello and Welcome". And when I press the microphone and if I speak something it is raising an exception in 
ProduceConsumerStream.cs  line 110

Below is the error it is showing

System.ObjectDisposedException
  HResult=0x80131622
  Message=Cannot access a closed Stream.
  Source=mscorlib
  StackTrace:
   at System.IO.__Error.StreamIsClosed()
   at System.IO.MemoryStream.set_Position(Int64 value)
   at DLSpeechClient.ProducerConsumerStream.Write(Byte[] buffer, Int32 offset, Int32 count) in C:\Users\diana\Cognitive-Services-Direct-Line-Speech-Client\DLSpeechClient\ProducerConsumerStream.cs:line 110
   at DLSpeechClient.MainWindow.<>c__DisplayClass40_1.<Connector_ActivityReceived>b__4() in C:\Users\diana\Cognitive-Services-Direct-Line-Speech-Client\DLSpeechClient\MainWindow.xaml.cs:line 362
   at System.Threading.Tasks.Task.Execute()


After I press continue , I get a echo text response not voice response. As you have advised I have created all the resource in westeurope.

I exactly want the Voice activated virtual assistant with a wake word. But I couldn't find any document.
Please Help


Please advice
 
For the second suggestion,
I have commented that line but eventhough I am getting the same response "What else I can help you with". I have not changed anything in the code.
And if I create a Speech instance in west europe I am getting 401 error. So I have created Speech instance in westus2.

**Sorry I am unable to attach the screenshots it is saying something went really wrong, and we can't process that file. If you can provide me your email so that I will send it as an email.

Thank you 
Pls help

**Comment by diana-RC** [comment]
Hi @ryanlengel ,

Thank u for the suggestion.
For the first suggestion:
I have tried Cognitive Service Direct Line Speech Client following this below document
https://docs.microsoft.com/bs-latn-ba/azure/cognitive-services/speech-service/tutorial-voice-enable-your-bot-speech-sdk

I have tried it with the echo bot and I have followed all the steps and have created all the resources as said in the document.
I have attached screenshots of my screen in which i don't get any echo response through voice and text. But the echo bot works fine in Bot Emulator.
As I have created speech instance in west europe region but I am getting a 401 error. So I have created the speech instance in westus2. 

I exactly want the Voice activated virtual assistant with a wake word. But I couldn't find a way.
Please Help


Please advice
 
For the second suggestion,
I have commented that line but eventhough I am getting the same response "What else I can help you with". I have not changed anything in the code.
And here also if I create a Speech instance in west europe I am getting 401 error. So I have created Speech instance in westus2.

**Comment by ryanisgrig** [comment]
For any issues on the Direct Line Speech Client, you should raise those at https://github.com/Azure-Samples/Cognitive-Services-Direct-Line-Speech-Client/issues.

Direct Line Speech is only enabled in West US 2, so there will be latency issues if you are connecting to a West Europe bot. Other regions will be available soon.

For wake word scenarios, please refer to the [scenario availability](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/scenario-availability) to see what platforms this is currently supported on.

**Comment by diana-RC** [comment]
Hi ryanlengel,

Thank you for the reply. I have raised issue to the corresponding team as you suggested.
Thank you for the pointers to see what platforms. Want to know can I integrate the virtual assistant in Azure Kinect DK , any pointers is greatly appreciated. If yes any document to start of with?

Thanks in advance 






> For any issues on the Direct Line Speech Client, you should raise those at https://github.com/Azure-Samples/Cognitive-Services-Direct-Line-Speech-Client/issues.
> 
> Direct Line Speech is only enabled in West US 2, so there will be latency issues if you are connecting to a West Europe bot. Other regions will be available soon.
> 
> For wake word scenarios, please refer to the [scenario availability](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/scenario-availability) to see what platforms this is currently supported on.

**Comment by ryanisgrig** [comment]
I don't know of any existing docs to integrate the Azure Kinect DK with a bot, ideally you just need to capture the audio from the Kinect and send over to your bot.

**Comment by diana-RC** [comment]
Thank you Ryanlengal for your inputs.
Thanks a lot for all of your inputs

> I don't know of any existing docs to integrate the Azure Kinect DK with a bot, ideally you just need to capture the audio from the Kinect and send over to your bot.
