### ISSUE TITLE
Events not being consumed on Direct Line Speech

### ISSUE THREAD

**Issue by Dewain27** [microsoft/botframework-solutions#2568]
#### What project is affected?
Virtual Assistant Sample

#### What language is this in?
C#

#### What happens?a
Client sends Location Event to Direct Line Speech, however Direct Line Speech does not send to the Bot State properly.

#### What are the steps to reproduce this issue?

1. Use VA POI Skill through Direct Line Speech
2. Send in Location Event to Bot
3. Ask for Starbucks near me
4. Bot asks for your location

#### What were you expecting to happen?
Expect Bot to have location from Location Event

**Comment by xieofxie** [comment]
I rolled back in this pr https://github.com/microsoft/botframework-solutions/pull/2579.

@ryanlengel It looks like we have three names now: VA.Location in VA event, Location in skill event and location in skill slot. Will we unify them?

**Comment by ryanisgrig** [comment]
The skill slot location is separate from an event name and is simply used as a description.
I think that it is confusing to have a different VA.Location in the VA and Location in the Skills, but if we are going to consolidate them it should be after this upcoming release. Truthfully there isn't anything to distinguish the difference between VA.Location and Location, other than the name, so I don't think they need to be different.

@lzc850612 I think we discussed this a while back when finding this discrepancy, so please chime in if I'm incorrect.

**Comment by darrenj** [comment]
Resolved?
