### ISSUE TITLE
handle space in botskills

### ISSUE THREAD

**Issue by xieofxie** [microsoft/botframework-solutions#2573]
#### What project is affected?

botskills

#### What language is this in?

ts

#### What happens?

[Here](https://github.com/microsoft/botframework-solutions/blob/08713f706ba1d3bae9471d2b4b721a58eb62de4c/tools/botskills/src/utils/childProcessUtils.ts#L50) simply joins the arguments, thus does not handle space in arguments (e.g. for id in authenticationConnections).

**Comment by Batta32** [comment]
Hi @xieofxie! Thanks for reporting the issue.

Can you provide a more detailed description with the `Repro Steps`?

**Comment by xieofxie** [comment]
My fault.. I didn't notice that web portal and az cli have different requirements for connection name.
