### ISSUE TITLE
botskills connect should not remove 'Azure Active Directory v2' connections

### ISSUE THREAD

**Issue by xieofxie** [microsoft/botframework-solutions#2574]
## User Story
As ... a dev
I want ... to keep existing 'Azure Active Directory v2' connections when botskills connect
since that ... their scopes may not overlap

## Acceptance Criteria 
*List your requirements.*
- [ ] ... keep existing 'Azure Active Directory v2' connections
- [ ] ... merge scopes if having connections with same name 
- [ ] ...

## Resources
*Provide any screenshots or conversation mockups to support your request.*
*Learn how to mock up bot conversations with [.chat files](http://aka.ms/bfchatfile).*

## Notes
*Provide any additional information.*

**Comment by lauren-mills** [comment]
@xieofxie can you elaborate on the problem you're running into? I think the botskills connect command combines the existing scopes with the new one it adds, but if you're finding something different, let us know

**Comment by xieofxie** [comment]
My fault.. But I wonder why we keep connection based on type instead of name?
In some cases, calendar skill and email skill might be using different connections for different scopes/accounts?
