### ISSUE TITLE
HandOff no longer works in the Teams channel

### ISSUE THREAD

**Issue by weskroesbergen** [microsoft/botframework-solutions#2577]
#### What project is affected?
Virtual Assistant Skills

#### What language is this in?
C#

#### What happens?
With Bot Solutions / Skills 4.5.4, the skill bots no longer handoff to calling bot when using the Teams channel, as the Teams channel does not support the handOff activity, and the Skill adapter no longer handles endOfConversation

#### What are the steps to reproduce this issue?
Update Bot.Builder.Skills and Bot.Builder.Solutions to 4.5.4 in any Skill and trigger a skill in a Teams conversation.

**Comment by lzc850612** [comment]
This is fixed by #2522 . the fix will be out early November in 4.6
