### ISSUE TITLE
WebChat test harness crashes when PoI event returned.

### ISSUE THREAD

**Issue by darrenj** [microsoft/botframework-solutions#259]
**Project**
Virtual Assistant

**Description**
It would appear the event returned by the PoI skill (which the web-app detects and should set the panel on the right) causes the browser page to crash.

**To Reproduce**

- Ask Find Starbucks
- Click Find a Route

![image](https://user-images.githubusercontent.com/33519520/48241358-6177ca80-e38b-11e8-891a-595dd734b40c.png)

**Expected behavior**
Event to be processed by webchat and address is set on the right panel.

**Comment by compulim** [comment]
This should be resolved in the latest interface.
