### ISSUE TITLE
[Botskills] Unexpected warning message when an external command fails

### ISSUE THREAD

**Issue by Batta32** [microsoft/botframework-solutions#2602]
#### What project is affected?
Botskills CLI Tool

#### What language is this in?
TypeScript

#### What happens?
When an external command fails, the tool shows an `UnhandledPromiseRejectionWarning` which is weird as console output.

#### What are the steps to reproduce this issue?
**Having a Virtual Assistant and a Skill deployed**
1. Using the following command to connect the Virtual Assistant to the Skill
> botskills connect --botName "<NON-EXISTENT_VA>" --localManifest "<PATH_TO_MANIFEST>" --ts
2. Replace the placeholder `<NON-EXISTENT_VA>` with a `botName` which doesn't exist.
3. Execute the `connect` command
4. Check the execution output which contains the `UnhandledPromiseRejectionWarning`

#### What were you expecting to happen?
The end-user should not see that warning, which needs to be handled correctly by the tool.

#### Can you share any logs, error output, etc.?
\-

#### Any screenshots or additional context?
The warning **doesn't block the workflow** of the tool and one scenario detected to reproduce the issue is when the `botName` doesn't exist.

_UnhandledPromiseRejectionWarning appears when the botName doesn't exist_
![image](https://user-images.githubusercontent.com/11904023/67715109-f104f780-f9a7-11e9-8216-93f793aa2be3.png)

**Comment by darrenj** [comment]
Has this been addressed?

**Comment by Batta32** [comment]
Hi @darrenj, we will **close** the issue as it doesn't show up anymore because the authentication process has been deprecated in the latest version of botskills.
