### ISSUE TITLE
[botskills] warn when scope is not recognized

### ISSUE THREAD

**Issue by xieofxie** [microsoft/botframework-solutions#2627]
## User Story
As ... anyone
I want ... to find scope error easily
so that ... it is easy to fix

## Acceptance Criteria 
*List your requirements.*
- [ ] ... warn (or error?) when scopes are not in `scopeMap in AuthenticationUtils`
- [ ] ...
- [ ] ...

## Resources
*Provide any screenshots or conversation mockups to support your request.*
*Learn how to mock up bot conversations with [.chat files](http://aka.ms/bfchatfile).*

## Notes
*Provide any additional information.*

**Comment by Batta32** [comment]
Hi @xieofxie, thanks for reporting this issue!
Can you provide the repro steps in order to validate that scenario?

We will keep you up with any progress.

**Comment by xieofxie** [comment]
@Batta32 case 1: user uses wrong separator instead of ',' in scopes, then the user could know it should be corrected;
case 2: new scope is defined and the user uses it, so that the user could be warned that botskills is not updated.

**Comment by Batta32** [comment]
Hi @xieofxie, we solved this issue in PR #2658 !
Feel free to reopen if you have a similar issue.
