### ISSUE TITLE
Error in Creating new Project under Virtual Studio 2019 Using the Virtual Assistant Template

### ISSUE THREAD

**Issue by MersGitHub** [microsoft/botframework-solutions#2635]
#### What project is affected?

Virtual Assistant

#### What language is this in?

C

#### What happens?

After installing all prerequisites for the Azure Bot Virtual Assistant on my laptop, I have selected on Visual Studio 2019 new project. On the windows that new project select opened, I have selected the Virtual Assistant Template which guide with another windows the configuration of the new project with the Virtual Assistant template. Using the default configuration provided, I selected the Create action (versus go back). 

I then encountering errors windows in the process of creating it under Virtual Studio. 

#### What are the steps to reproduce this issue?

Select New Project under Visual Studio (File / New / New project)
On the next Windows, Select Virtual Assistant Template, and then select NEXT
Leave the default settings and select CREATE

Then errors windows from Visual Studio are generated 

#### What were you expecting to happen?

Create in Visual Studio the expected Virtual Assistant for the next installation step.

#### Can you share any logs, error output, etc.?

Can not find any details on the errors encountered, other than the sympatie error pop-up.

#### Any screenshots or additional context?

[While creating a Bot Instance -error encountered but project successfull .docx](https://github.com/microsoft/botframework-solutions/files/3798043/While.creating.a.Bot.Instance.-error.encountered.but.project.successfull.docx)

**Comment by lauren-mills** [comment]
Hi @MersGitHub can you let me know which version of the .net core sdk you have installed?

**Comment by MersGitHub** [comment]
Hello Lauren-Mills

My version is: .NET Core SDK 2.1.802 (x64)
and my .NET Core Runtime - 2.0.0 (x86)

**Comment by MersGitHub** [comment]
Sorry  correction  .Net Core Runtime - 3.0.0 (x86)

**Comment by lauren-mills** [comment]
Can you try downloading version 2.2? https://dotnet.microsoft.com/download/dotnet-core/2.2

We are working to update to 3.0 in our next release, but we have not upgraded yet, so there may be a compatibility issue.

**Comment by MersGitHub** [comment]
Hello Laurent-mills,

I have uninstalled my previous .Net (SDK and Runtime).

And I now have the following .Net Core on my laptop:

- Microsoft .Net Core Runtime - 2.2.7 (X86)
- Microsoft .Net Core Runtime 2.2.7 - Windows Server Hosting
- Microsoft .Net Core Runtime  - 2.2.7 (X64)

I have retried creating the Virtual assistant via the template and encountered the same error behaviour reported previously.

Note: I have tried to rerun the NPM Install command from the installation procedure and I have encountered an error stating that the install needed the Dotnet SDK 2.1 to be installed. Please see the attached screen print of the PowerShell window.

![Screen print of a need for  Docnet SDK 2 1 ](https://user-images.githubusercontent.com/35462596/68130523-7c6f1300-fee9-11e9-8dd7-e6457982cac7.png)

**Comment by MersGitHub** [comment]
Update

I have installed - Microsoft .Net Core SDK 2.2.402(X86).

I still encountering the same error behaviour

**Comment by lauren-mills** [comment]
For the npm install, can you try this instead?
```
npm install -g botdispatch ludown luis-apis qnamaker luisgen
```

**Comment by MersGitHub** [comment]
Hello Laurent-mills,

Same result

![Screen print of a need for  Docnet SDK 2 1  - Take 2 ](https://user-images.githubusercontent.com/35462596/68144731-438f6800-ff02-11e9-964e-8ce528d1d896.png)

**Comment by lauren-mills** [comment]
Can you run `dotnet --info` and send me the output? Also, can you send the output of `node -v`?

**Comment by MersGitHub** [comment]
Laurent-mills,

Here is the result output of those two commands.

![Dotnet AND Node commands execution output ](https://user-images.githubusercontent.com/35462596/68148266-a0425100-ff09-11e9-8820-d11f311ea6f9.png)

**Comment by MersGitHub** [comment]
Complement

![Conttrol Panel - installed programs - for  Net prooducts ](https://user-images.githubusercontent.com/35462596/68148449-04fdab80-ff0a-11e9-999b-2139fc19c437.png)

**Comment by lauren-mills** [comment]
Ok, I went through and updated to .net core 3.0, then installed .net 2.2.7 from the link above and got things working on my end. Installing 3.0 should include the 2.1 versions you need for the npm install to complete, and 2.2 should enable VS to load the projects. Please try installing both versions and let me know if it helps at all.

We'll be working to update our projects to use .net 3.0 in the coming weeks, so I'll update this once that work is done.

**Comment by MersGitHub** [comment]
Hello laurent-mills and thank you for your assistance

The npm install went OK.

Creation of the VA failed again with same behaviour.

Here is what is installed.

![Conttrol Panel - installed programs - after installed  Net v3 0 SDK and  Net 2 2 7 Core Runtime ](https://user-images.githubusercontent.com/35462596/68217602-e43c6100-ffb0-11e9-9a8c-8b85924cfe14.png)

**Comment by MersGitHub** [comment]
Complement

![Dotnet --info result - Nov 5, 2019](https://user-images.githubusercontent.com/35462596/68218092-c4f20380-ffb1-11e9-8865-1a5071d1f708.png)

**Comment by MersGitHub** [comment]
Complement 2 - Visual Studio - associated products

![Visual Studio - associated products - Nov 5_ 2019](https://user-images.githubusercontent.com/35462596/68219080-63cb2f80-ffb3-11e9-9c8f-37b5fc8170b3.png)

![Visual Studio - associated products - take 2 - Nov 5_ 2019](https://user-images.githubusercontent.com/35462596/68219096-69287a00-ffb3-11e9-9b34-70c548551493.png)

**Comment by MersGitHub** [comment]
Hello laurent-mills,

I "gust" feeling tell me that the issue is associated with my Visual Studio and not the .Net Core. But I might be totally in the field...

**Comment by MersGitHub** [comment]
Hello laurent-mills,

Hope you are doing well. Can you come back to me with directions to follow to make it work? 

Thank you

**Comment by MersGitHub** [comment]
Hello Laurent-Mills,

I have installed all .net 227 from above. And it shows in the DotNet --info command output. 
Is this install is what you had when it worked on your machine? 

Please note that I have excluded my Visual Studio 2019 from the error equation. 

![Dotnet 227 installed (Core and Runtime) - Nov 6_ 2019](https://user-images.githubusercontent.com/35462596/68339876-64e38600-00b3-11ea-8618-3d79ed94afec.png)

**Comment by lauren-mills** [comment]
It looks like you installed the 2.2 runtime, instead of the 2.2 sdk. Can you try installing the SDK instead?

**Comment by MersGitHub** [comment]
Good morning Laurent-Mills,

Here is what I have now: .Net 2.2 SDK and the .Net Runtime 2.2.7.  And that I have replaced Visual Studio 2019 by 2017. The errors are still being generated but with a bit more info. Perhaps it would mean something to you 
![Error VS 2017 with more info - Nov 13 2019](https://user-images.githubusercontent.com/35462596/68770594-71586900-05f4-11ea-9488-a06e133687dd.png)

And here is my Dotnet --info
![Dotnet --info result - Nov 12, 2019](https://user-images.githubusercontent.com/35462596/68770623-7fa68500-05f4-11ea-987d-518cdf4fbf19.png)

**Comment by MersGitHub** [comment]
Additional Info.

![Control Panel -   Net 2 2 7 Core Runtime  and  Net Core SDK 2 2 _ Nov 13 2019 ](https://user-images.githubusercontent.com/35462596/68771913-ea58c000-05f6-11ea-8293-b7fb6c86d223.png)

**Comment by MersGitHub** [comment]
Hello Lauren-Mills,

Thinking that perhaps something was wrong on my workstation, I have created an Azure VM with WIndows 10 and Visual Studio 2019. I then followed the VA C-Sharp dependencies on the Virtual Machine fresh from history. 

    https://microsoft.github.io/botframework-solutions/virtual-assistant/tutorials/create-assistant/csharp/2-download-and-install/

I have now .Net 2.2.402 SDK, and the .Net runtime 2.2.7, Node v12.13.0, MSPowerShell, MS CLI V2.0.76.

And Imagine what?  

 ==˃ The same error behaviour occurred on that fresh Virtual Machine than the one on my workstation.   

It must then be with the instructions that I am following from that URL procedure.

Waiting now for your directives as I did what I could to make it work.

Thank you for your assistance

![MersVABOTVM_Dotnet_info 19Nov2019](https://user-images.githubusercontent.com/35462596/69168768-4626bb80-0ac5-11ea-809a-7da6888f8bcb.png)

**Comment by MersGitHub** [comment]
Hello Lauren-Mills,

My creation of the Azure Bot Virtual Assistant ... Finally worked!! 

With these middleware product installed!

Note: It is what you had written 15 days ago that I could not do on my workstation

"Ok, I went through and updated to .net core 3.0, then installed .net 2.2.7 from the link above and got things working on my end.."

Wow what an try and error experience...

Thank you for your assistance and cooperation, Lauren-Mills

![Control Panel -  Finally working Bot VA _ Nov 19 2019 at 15_06 (EST) ](https://user-images.githubusercontent.com/35462596/69182196-87779500-0ade-11ea-9e05-9bc83e22af68.png)
