### ISSUE TITLE
References to Botskills CLI Documentation - 404 [Docs]

### ISSUE THREAD

**Issue by HowdySys** [microsoft/botframework-solutions#2659]
/skills/handbook/add-skills-to-a-virtual-assistant/

References to Botskills CLI Documentation are not up to date - 404
From https://microsoft.github.io/botframework-solutions/skills/handbook/add-skills-to-a-virtual-assistant/

Thanks!

**Comment by ryanisgrig** [comment]
Thanks @HowdySys, the correct link is https://microsoft.github.io/botframework-solutions/help/reference/botskills/

I will take care of this for the next release.
