### ISSUE TITLE
Bot Framework Solutions in the Tutorial: Connect to a sample the link to samples code is broken 404 [Docs]

### ISSUE THREAD

**Issue by lobigm** [microsoft/botframework-solutions#2663]
Hello, in the https://microsoft.github.io/botframework-solutions/skills/tutorials/add-prebuilt-skill/1-intro/ 
the link to the sample code is broken, i'm trying to get ToDo skill for test, can i get the link to the repository?, i need the TodoSkill c# code.

Thanks in advance.

**Comment by ryanisgrig** [comment]
Thanks @lobigm, the correct URL is https://github.com/microsoft/botframework-solutions/tree/next/skills/csharp (points to next branch). I will update the docs in our next release.
