### ISSUE TITLE
[Virtual Assistant] Specify dispatch version in update_cognitive_models.ps1

### ISSUE THREAD

**Issue by EdwinOtten** [microsoft/botframework-solutions#2673]
## User Story
As *a developer*
I want *to run update_cognitive_models.ps1 without errors*
so that *I can update my luis dispatch model*

## Acceptance Criteria 
*List your requirements.*
- running *update_cognitive_models.ps1* doesn't throw errors

## Resources
I noticed others also used the `--version` argument to solve certain version issues: https://github.com/Microsoft/botbuilder-tools/issues/1127

## Notes
When running the *update_cognitive_models.ps1* script it sometimes throws an error on the `dispatch refresh` command:
```
Failed importing latest version of redacted_Dispatch app
```
This does not always occur, but somehow it helps to add the *optional* `--version` argument. As far a I know, the deployed version of a dispatch model is always called "Dispatch", so it could just as well be set to that specifically.

## Suggested action
I'd like to suggest adding `--version "Dispatch"` in *update_cognitive_models.ps1* to make it less likely to throw errors.

I commited the suggested change on a fork: https://github.com/microsoft/botframework-solutions/compare/master...EdwinOtten:patch-2

**Comment by lauren-mills** [comment]
@edwinotten can you link the issue this resolves for you? The original link seems unrelated. Thanks!

**Comment by EdwinOtten** [comment]
@lauren-mills Sorry, I accidentally linked to an unrelated issue. I wanted to mention https://github.com/Microsoft/botbuilder-tools/issues/1127

**Comment by darrenj** [comment]
Updated
