### ISSUE TITLE
[Docs] The aka.ms/vamanualappcreation link leads to a 404

### ISSUE THREAD

**Issue by victorp13** [microsoft/botframework-solutions#2680]
**Please describe your request**
The deploy.ps1 scripts (there are a couple in this repo) contain a URL to find more information on manual app creation process. This is an aka.ms shortcut URL: https://aka.ms/vamanualappcreation. This leads to a 404 page however in the documentation.

**Is this an issue with current documentation? If yes, please provide the link.**
Yes, the deploy.ps1 scripts have the https://aka.ms/vamanualappcreation URL in them, and this URL gives a 404 currently. 
The current aka.ms shortcut leads to:
https://microsoft.github.io/botframework-solutions/reference/knownissues/#my-microsoft-app-registration-could-not-be-automatically-provisioned
but should probably lead to:
https://microsoft.github.io/botframework-solutions/help/known-issues/#my-microsoft-app-registration-could-not-be-automatically-provisioned

**Comment by ryanisgrig** [comment]
Thanks @victorp13! I've updated our aka.ms link
