### ISSUE TITLE
Calendar Skill - Find Attendee Availability

### ISSUE THREAD

**Issue by kensimpson** [microsoft/botframework-solutions#2690]
## User Story
As user
I want to schedule a meeting with someone based upon our mutual availability
so that I don't have to consult Outlook to find availability or accidentally block over another meeting

## Acceptance Criteria 
*List your requirements.*
- When scheduling a meeting, after listing duration of the meeting, bot prompts user with suggested windows of shared availability to choose from
- Availability is determined by 8AM-6PM local time zone of the user you are querying
- Local time zone is defined as local time at user's AAD location
- Availability to override if you want to disregard availability and schedule the meeting anyway

## Resources
*Provide any screenshots or conversation mockups to support your request.*
*Learn how to mock up bot conversations with [.chat files](http://aka.ms/bfchatfile).*

## Notes
*Provide any additional information.*

**Comment by xhr0804** [comment]
PR #2661 is to support check availability, seems this is related to it? @KayMKM 
And pr #2655 may support the feature of time constraint.

**Comment by lauren-mills** [comment]
Hi @kensimpson, we do have a simple implementation of this in the PR listed above, but for the additional features you've requested we will add this to the backlog to go through design and mockups. We will post any updates here. Thanks!

**Comment by darrenj** [comment]
Merged into Next as part of the above PRs
