### ISSUE TITLE
"Automated Deployment" link broken

### ISSUE THREAD

**Issue by rng** [microsoft/botframework-solutions#27]
**Description**
"Automated Deployment" link in Feature-Description table in README.md is broken.

**To Reproduce**
1. Go to 'https://github.com/Microsoft/AI/blob/master/solutions/Virtual-Assistant/docs/README.md'
2. Click on 'Automated Deployment'
3. See error

**Expected behavior**
404 Github page appears, url:
https://github.com/Microsoft/AI/blob/master/solutions/Virtual-Assistant/docs/,/virtualassistant-createvirtualassistant.md

**Additional context**
There is probably an extra "," in the file path; https://github.com/Microsoft/AI/blob/master/solutions/Virtual-Assistant/docs/virtualassistant-createvirtualassistant.md works :)

**Comment by lauren-mills** [comment]
Fixed.
