### ISSUE TITLE
WebSocket error while connecting VA to Sill (both developed using C#)

### ISSUE THREAD

**Issue by sowsan** [microsoft/botframework-solutions#2702]
I have a skill created and published to azure (https://inventoryskill.azurewebsites.net/api/skill/manifest )

Both Skill and VA are developed using the latest project template with C#. 

It was successfully connected to my virtual assistant using botskills cli . When assistant handing off to the skill it's failing with the below error. I have added the assistant app id in to the white list and it look like a websocket related error. I have enabled websocket for the skill web app bot and both VA and skill bots are in standard pricing plan.

Any idea how to fix ? 

More detailed stack trace below.
:" at System.Net.WebSockets.WebSocketHandle.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options) at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken) at Microsoft.Bot.StreamingExtensions.Transport.WebSockets.WebSocketClient.ConnectAsync(IDictionary`2 requestHeaders) at Microsoft.Bot.Builder.Skills.SkillWebSocketTransport.ForwardToSkillAsync(SkillManifest skillManifest, IServiceClientCredentials serviceClientCredentials, ITurnContext turnContext, Activity activity, Action`1 tokenRequestHandler, Action`1 fallbackHandler) at Microsoft.Bot.Builder.Skills.SkillDialog.ForwardToSkillAsync(DialogContext innerDc, Activity activity) at Microsoft.Bot.Builder.Skills.SkillDialog.ForwardToSkillAsync(DialogContext innerDc, Activity activity) at Microsoft.Bot.Builder.Skills.SkillDialog.OnBeginDialogAsync(DialogContext innerDc, Object options, CancellationToken cancellationToken) at Microsoft.Bot.Builder.Dialogs.ComponentDialog.BeginDialogAsync(DialogContext outerDc, Object options, CancellationToken cancellationToken) at Microsoft.Bot.Builder.Dialogs.DialogContext.BeginDialogAsync(String dialogId, Object options, CancellationToken cancellationToken) at MyAssistant2.Dialogs.MainDialog.RouteAsync(DialogContext dc, CancellationToken cancellationToken) in C:\Users\sowmyans\source\repos\MyAssistant2\MyAssistant2\MyAssistant2\Dialogs\MainDialog.cs:line 94 at Microsoft.Bot.Builder.Solutions.Dialogs.RouterDialog.OnContinueDialogAsync(DialogContext innerDc, CancellationToken cancellationToken) at Microsoft.Bot.Builder.Dialogs.ComponentDialog.ContinueDialogAsync(DialogContext outerDc, CancellationToken cancellationToken) at Microsoft.Bot.Builder.Dialogs.DialogContext.ContinueDialogAsync(CancellationToken cancellationToken) at Microsoft.Bot.Builder.Dialogs.DialogExtensions.RunAsync(Dialog dialog, ITurnContext turnContext, IStatePropertyAccessor`1 accessor, CancellationToken cancellationToken) at MyAssistant2.Bots.DialogBot`1.OnTurnAsync(ITurnContext turnContext, CancellationToken cancellationToken) in C:\Users\sowmyans\source\repos\MyAssistant2\MyAssistant2\MyAssistant2\Bots\DialogBot.cs:line 39 at Microsoft.Bot.Builder.Solutions.Middleware.EventDebuggerMiddleware.OnTurnAsync(ITurnContext turnContext, NextDelegate next, CancellationToken cancellationToken) at Microsoft.Bot.Builder.Solutions.Middleware.SetLocaleMiddleware.OnTurnAsync(ITurnContext context, NextDelegate next, CancellationToken cancellationToken) at Microsoft.Bot.Builder.Solutions.Feedback.FeedbackMiddleware.OnTurnAsync(ITurnContext context, NextDelegate next, CancellationToken cancellationToken) at Microsoft.Bot.Builder.ShowTypingMiddleware.OnTurnAsync(ITurnContext turnContext, NextDelegate next, CancellationToken cancellationToken) at Microsoft.Bot.Builder.TelemetryLoggerMiddleware.OnTurnAsync(ITurnContext context, NextDelegate nextTurn, CancellationToken cancellationToken) at Microsoft.Bot.Builder.TranscriptLoggerMiddleware.OnTurnAsync(ITurnContext turnContext, NextDelegate nextTurn, CancellationToken cancellationToken) at Microsoft.Bot.Builder.BotFrameworkAdapter.TenantIdWorkaroundForTeamsMiddleware.OnTurnAsync(ITurnContext turnContext, NextDelegate next, CancellationToken cancellationToken) at Microsoft.Bot.Builder.MiddlewareSet.ReceiveActivityWithStatusAsync(ITurnContext turnContext, BotCallbackHandler callback, CancellationToken cancellationToken) at Microsoft.Bot.Builder.BotAdapter.RunPipelineAsync(ITurnContext turnContext, BotCallbackHandler callback, CancellationToken cancellationToken)"

**Comment by Kumar3010** [comment]
you have to enable websocket setting in azure portal

**Comment by sowsan** [comment]
Thanks. As I have mentioned, its enabled in the Azure portal for both skill & VA.

**Comment by sowsan** [comment]
@Kumar3010  sorry, i was configuring the websocket on a different webapp :) . Thanks again. it's working now.
