### ISSUE TITLE
Typescript Virtual Assistant template publish of bot (via publish.ps1) does not run npm install

### ISSUE THREAD

**Issue by nathanlindorff** [microsoft/botframework-solutions#2709]
There seems to be some sort of a compatibility issue between the publish script (publish.ps1) and the latest azure cli. 

az cli zip deploy seems to be explicitly setting SCM_DO_BUILD_DURING_DEPLOYMENT to false on the appsettings of the web app, regardless of if it is already set to true. 

#### What project is affected?
Virtual Assistant Template (Typescript) deployment scripts 

#### What language is this in?
Powershell / Typescript

#### What happens?
Code.zip is deployed to the web app, but does not run as npm install has not been run during the deployment.

#### What are the steps to reproduce this issue?
Run Deployment script (deploy.ps1) and then publish script (publish.ps1)

#### What were you expecting to happen?
Bot to be deployed, npm install run, and the bot to be functional.

#### Can you share any logs, error output, etc.?
Output in publish.txt:

```
WARNING: Getting scm site credentials for zip deployment
WARNING: Setting ENABLE_ORYX_BUILD to false
WARNING: Setting SCM_DO_BUILD_DURING_DEPLOYMENT to false
WARNING: Starting zip deployment. This operation can take a while to complete ...
WARNING: Deployment endpoint responses with status code 202
```

#### Any screenshots or additional context?
I've also raised an issue (https://github.com/Azure/azure-cli/issues/11246) on the Azure cli repo, as I suspect it is probably the cli that is breaking things.

This exact application is running in our dev subscription. I've deployed to it multiple times over the last months, but now i'm trying to deploy it to our production subscription and things are failing. I did upgrade my az cli within the last couple of days, which is why I suspect that has been at least part of the issue.

**Comment by nathanlindorff** [comment]
I got a reply from the az cli team in https://github.com/Azure/azure-cli/issues/11246 stating that it was an issue introduced in a recent release and was due to be fixed in an upcoming one, so happy for this issue to be closed.

**Comment by dfavretto** [comment]
Hi @nathanlindorff! We validated publishing the Virtual Assistant with **az-cli v2.0.75** and **az-cli v2.0.76**, and it worked perfectly with the **v2.0.75**.

![image](https://user-images.githubusercontent.com/23645105/69376342-e4af4a00-0c88-11ea-86e5-42e67f8b5f38.png)

We are closing this issue. Feel free to reopen it if you keep having problems to publish the Virtual Assistant.
