### ISSUE TITLE
[Docs] The link to BI Template looks wrong

### ISSUE THREAD

**Issue by managedcoder** [microsoft/botframework-solutions#2737]
/solution-accelerators/tutorials/view-analytics/1-intro/

I tried to download the Power BI template at bottom of page through the link "•Download the Virtual Assistant analytics Power BI template" and I get a .zip file, not the .pbit file advertised in the link.

**Comment by lauren-mills** [comment]
Hi @managedcoder , when I click the link the .pbit downloads. What browser are you using?

**Comment by managedcoder** [comment]
Ah!  I was viewing it in IE 11.  Just tried it in Edge and it works fine.  You can close this issue.  Thanks for that.
