### ISSUE TITLE
[Virtual Assistant Template] Support .Net Core 3

### ISSUE THREAD

**Issue by marcasmar94** [microsoft/botframework-solutions#2743]
Does the virtual assistant template currently support .net core 3? If not, when will it be updated? 
I can't seem to find a place to keep track with updates related to .Net Core 3 and the Bot Framework.

Thank you

**Comment by lauren-mills** [comment]
Hi @marcasmar94, we released our updated template with .net core 3.0 support last week. Please refer to the VS marketplace to update it. Thanks!
