### ISSUE TITLE
broken links 

### ISSUE THREAD

**Issue by turbozapekanka** [microsoft/botframework-solutions#2754]
to skills examples
https://microsoft.github.io/botframework-solutions/skills/samples/experimental/

also example screenshot shows Chinese restaurant as first but user asked for the second option
https://microsoft.github.io/botframework-solutions/assets/images/skills-restaurant-transcript.png

**Comment by ryanlengel** [comment]
@elaine-chang @Dewain27 given that each experimental skill now has it's own page, does it make sense that the experimental overview page has those same details?

**Comment by ryanisgrig** [comment]
Thanks @turbozapekanka, these links are correctly referenced on the skill pages themselves now (i.e. [restaurant booking skill](https://microsoft.github.io/botframework-solutions/skills/samples/restaurant-booking/).

@elaine-chang  assigning to you for direction on the content of the Experimental Skills overview. It currently has duplicate content from each skill page.
