### ISSUE TITLE
There was an error while connecting the Skill to the Assistant: Error: Some of the cultures provided to connect from the Skill are not available or aren't supported by your VA. Make sure you have a Dispatch for the cultures you are trying to connect, and that your Skill has a LUIS model for that culture

### ISSUE THREAD

**Issue by diana-RC** [microsoft/botframework-solutions#2757]
#### What project is affected?
Virtual Assistant and point of Interest skill
#### What language is this in?
csharp
#### What happens?
There was an error while connecting the Skill to the Assistant:
Error: Some of the cultures provided to connect from the Skill are not available or aren't supported by your VA.
Make sure you have a Dispatch for the cultures you are trying to connect, and that your Skill has a LUIS model for that culture
#### What are the steps to reproduce this issue?
I have updated the botskills and current version is botskills 1.0.10
And also Tried the Botskills connect without languages "en-us"
#### What were you expecting to happen?
Connect the skill to VA through Botskill command
#### Can you share any logs, error output, etc.?
![botskillconnection-error](https://user-images.githubusercontent.com/55460938/69677459-eb7bf980-109a-11ea-89c6-cf3568c30dc6.PNG)
![skill-manifest](https://user-images.githubusercontent.com/55460938/69677569-1e25f200-109b-11ea-98c2-7490d65c5330.PNG)

#### Any screenshots or additional context?
![emulator-output](https://user-images.githubusercontent.com/55460938/69677719-73620380-109b-11ea-806e-5a4627a30a27.PNG)

Please help. Thank you

**Comment by xieofxie** [comment]
@diana-RC Hi, since skill uses en-us in cognitivemodels now 
![image](https://user-images.githubusercontent.com/2876650/69691103-e5bcfd00-1108-11ea-9357-a731ee5ad25a.png)
VA should also uses this
![image](https://user-images.githubusercontent.com/2876650/69691115-f2415580-1108-11ea-9363-b03bbb726712.png)
I don't know if VSIX has been updated yet, but you could use [VA directly here](https://github.com/microsoft/botframework-solutions/tree/master/templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample).

Related https://microsoft.github.io/botframework-solutions/skills/tutorials/create-skill/csharp/6-add-your-skill/

**Comment by diana-RC** [comment]
@xieofxie  Hi, If I update the cognitivemodels.json(from "en" to "en-us") in VA then my bot is not responding. Please find the attachment for reference. Please help. Thank you
![cognitivemodelchanged](https://user-images.githubusercontent.com/55460938/69722282-a5f91400-110e-11ea-90cc-b6165178eb19.PNG)
![VA-notresponding](https://user-images.githubusercontent.com/55460938/69722289-a8f40480-110e-11ea-8c7e-2ebc28ce546d.PNG)

**Comment by Batta32** [comment]
Hi @diana-rc, thanks for reporting this issue!

Are you using the **latest version** of the [Virtual Assistant Sample](https://github.com/microsoft/botframework-solutions/tree/master/templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample) which contains the method [GetCognitiveModels()](https://github.com/microsoft/botframework-solutions/blob/master/templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Services/BotServices.cs#L68)? This method is used to get your cognitiveModels that most closely matches your locale (i.e. en-us with en-uk ). See [here](https://github.com/microsoft/botframework-solutions/blob/master/templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Dialogs/MainDialog.cs#L261).

We are validating the current behavior of [botskills@1.0.10](https://www.npmjs.com/package/botskills/v/1.0.10) and get back to you later.

**Comment by Batta32** [comment]
@diana-rc, looking at your last screenshot, we noticed that the resources are deployed in `en` but as [botskills@1.0.10](https://www.npmjs.com/package/botskills/v/1.0.10) contains the multilanguage functionality will search for `en-us` and that error will raise.

We followed these steps being in _master_ branch, using the C# solutions and tested locally:
1. Deploy the [Virtual Assistant Sample](https://github.com/microsoft/botframework-solutions/tree/master/templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample) following this [documentation](https://microsoft.github.io/botframework-solutions/virtual-assistant/tutorials/create-assistant/csharp/4-provision-your-azure-resources/)
1. Once it has finished, check that the `cognitiveModels` file contains the specific culture like `en-us`. Also all the resources should contain the specific culture in the name (e.g `mbvacstesten-us_Dispatch` and `mbvacstesten-us_General`)
1. Deploy the [Skill Sample](https://github.com/microsoft/botframework-solutions/tree/master/templates/Skill-Template/csharp/Sample/SkillSample) following this [documentation](https://microsoft.github.io/botframework-solutions/skills/tutorials/create-skill/csharp/4-provision-your-azure-resources/)
1. Run the Skill Sample
1. Browse the `/api/skill/manifest` of your Skill so you can check that the locale contains a specific culture like `en-us`
1. Go to the Virtual Assistant Sample folder 
1. Execute the `botskills connect` command
> botskills connect --remoteManifest "<SKILL'S URL>/api/skill/manifest" --luisFolder "<LU FOLDER PATH>" --cs
8. Check that the connection finished successfully

### Additional Context
_cognitiveModels file after the deployment of a Virtual Assistant with the resources in en-us_
![image](https://user-images.githubusercontent.com/11904023/69750000-7821c880-112a-11ea-8b56-985da92e8832.png)

_Dispatch deployed in en-us_
![image](https://user-images.githubusercontent.com/11904023/69750040-91c31000-112a-11ea-9c1d-85197a76e6d7.png)

_LU folder with en-us files_
![image](https://user-images.githubusercontent.com/11904023/69750057-9a1b4b00-112a-11ea-8251-bd2dab84e476.png)

_Skill Manifest with the locale in en-us_
![image](https://user-images.githubusercontent.com/11904023/69750067-a0a9c280-112a-11ea-8402-538a08682dd2.png)

_Botskills connect command executed_
> botskills connect --remoteManifest "http://localhost:3978/api/skill/manifest" --luisFolder "C:\Git\botframework-solutions\templates\Skill-Template\csharp\Sample\SkillSample\Deployment\Resources\LU" --cs

_Successful connection between Virtual Assistant Sample and Skill Sample_
![image](https://user-images.githubusercontent.com/11904023/69750087-a8696700-112a-11ea-940f-a64c2f038385.png)

We hope this helps you and we will be attentive to your response😊.

**Comment by diana-RC** [comment]
@Batta32 Hi Batta, thanks a lot for the detailed explanation. Sure will update you soon after redeploying. Quick question
1. I have found there is a big difference between the codes which I have in my VA MainDialog.cs and the latest version of MainDialog.cs. I have attached my MianDialog.cs for your reference. 
2. Should I change the whole MainDialog.cs and also update the Botservices.cs with GetCognitiveModels()? 
3.And then redeploy my VA and skills?
4. If I do so will my assistant and already added skills(weather,Bingsearch,newskill and Phoneskill) will work as expected

[MainDialogcs.txt](https://github.com/microsoft/botframework-solutions/files/3898483/MainDialogcs.txt)


awaiting for your reply. Thank you

**Comment by Batta32** [comment]
@diana-rc, the structure of the Virtual Assistant Sample has changed with the updates of the _next_ branch; so if you were using the sample before that merge, it's totally different now. We can't assure you that everything will work if you only update the `MainDialog` and the `BotServices`.

For example, the specific culture functionality with the fallback to root language was introduced in the PR #2368 which allows you to handle many cultures like `en-us`, `en-uk`, `en` at the same time. Also, to accept those changes in the connection of the VA - Skill, we updated the Botskills CLI Tool in PR #2131. 

As a **workaround** for the connection, you can use [botskills@1.0.9](https://www.npmjs.com/package/botskills/v/1.0.9) which doesn't contain those changes and you can keep your Virtual Assistant and Skill. In this case, you should use the two letter cultures for the connection and the deployment. 
> npm uninstall -g botskills
npm install -g botskills@1.0.9

**Comment by diana-RC** [comment]
@Batta32 thank you once again for guidance. I will try using botskills@1.0.9 and use two letter cultures for the connection and deployment. If I am unsuccessful, I will go for the latest VA and Botskills@1.0.10.
Thank you

**Comment by diana-RC** [comment]
@Batta32 thanks a lot . I have installed botskills 1.0.9 and I have added the skill successfully.
Thank you so much

**Comment by Batta32** [comment]
Awesome @diana-RC! I will close this, feel free to reopen if you have a similar issue 😊
