### ISSUE TITLE
need relationship between commit and version of botskills

### ISSUE THREAD

**Issue by xieofxie** [microsoft/botframework-solutions#2758]
## User Story

Botskills has been updated to [1.0.10](https://www.npmjs.com/package/botskills/v/1.0.10) and does it contain https://github.com/microsoft/botframework-solutions/pull/2131? 

No clue is found about this. Or just use daily build then..

## Acceptance Criteria 
*List your requirements.*
- [ ] ... provide some clue about this
- [ ] ...
- [ ] ...

## Resources
*Provide any screenshots or conversation mockups to support your request.*
*Learn how to mock up bot conversations with [.chat files](http://aka.ms/bfchatfile).*

## Notes
*Provide any additional information.*

**Comment by Batta32** [comment]
Hi @xieofxie, [botskills@1.0.10](https://www.npmjs.com/package/botskills/v/1.0.10) contains #2131 - [Botskills] Implement multilanguage functionality.

We will update the botskills documentation providing the correct steps to use the latest version of the tool.

**Comment by lauren-mills** [comment]
@xieofxie - do you have a proposed solution to this issue? You've mentioned it before regarding the libs and templates as well. Open to ideas.

**Comment by xieofxie** [comment]
@lauren-mills In DevOps, there is a Tag sources option, maybe we could try it
![image](https://user-images.githubusercontent.com/2876650/69773158-fafb5f80-11cc-11ea-8bad-d20b391768eb.png)
