### ISSUE TITLE
Virtual Assistant Template deployment script stuck at "Initializing Dispatch model"

### ISSUE THREAD

**Issue by mohandivraniya** [microsoft/botframework-solutions#2763]
## Tool
Name: [Dispatch]
Version: 0.6
OS: Windows Server 2016 Data center

## Describe the bug
Virtual Assistant Template deployment script stuck at "Initializing Dispatch model"

## To Reproduce
1. Download and install all [prerequisites](https://microsoft.github.io/botframework-solutions/virtual-assistant/tutorials/create-assistant/csharp/2-download-and-install/) from 
2. Create a new project in Visual Studio 2019 using Virtual Assistant Template
3. Create an authoring LUIS application in Azure Portal
4. Run Deploy.ps1 with all the parameters.

## Expected behavior
It should create required cognitive services and dispatch models.

**Comment by lauren-mills** [comment]
Hi, @mohandivraniya, can you run `dispatch -v` and let me know what version of the dispatch tool you have installed? Also, can you look in the `Deployment` folder and see if you have a deploy_cognitive_models_log.txt and let me know what it says?

**Comment by mohandivraniya** [comment]
Hi,
Apologies for late reply.
Version of dispatch is 1.6.2.
I debugged the script and noticed following issues with PowerShell:

1. It expects that .lu files are available at "Deployment/Scripts/Resources/LU/en-us". However, Resources folder is parallel to Scripts folder and not a child folder of it.
2. It adds extra ".." in the path. I am not sure why these are needed. 

I moved Resources folder inside Scripts folder and fixed .. path formation.
It worked after that.

**Comment by lauren-mills** [comment]
Were you running the script from the project directory, or the Deployment/Scripts directory? All the scripts were written with the assumption that you are running them from the root project directory.

**Comment by mohandivraniya** [comment]
Hi,

I was running it from project directory and from vs code PowerShell extension. 

An update on this issue:

Today, I again ran that script from PowerShell 6. It worked from there for Azure services, LUIS, QnA deployment. But stuck at bot web app publishing. I couldn't find any error logs.

**Comment by lauren-mills** [comment]
@mohandivraniya - If the published bot is working, even though the script looks like it stuck, it completed. There's just an issue with the script output not ending correctly that I'm working on. Does your published bot work?

**Comment by mohandivraniya** [comment]
Yes, the published bot works as expected. while going through publish.ps1 script, I noticed that it uses folder netcoreapp2.2 to publish bot to azure. Shouldn't it be netcoreapp3.0 ?

**Comment by lauren-mills** [comment]
Yes, it should. I'm working on an update to the scripts to fix it (among other updates).

**Comment by darrenj** [comment]
The latest deployment scripts have addressed this thanks for letting us know.
