### ISSUE TITLE
Add Azure Resource Tags to VA Assistant and VA Sill Arm Templates

### ISSUE THREAD

**Issue by managedcoder** [microsoft/botframework-solutions#2764]
## User Story
As a developer or admin
I want to pass 2 resource tags (e.g. "Department" and "Bot") and their corresponding values to the deploy.ps1 scripts (or specify in Arm Template) for both the Assistant and Skill templates 
so that developers and assistants can conditionally have resource tags associated with every resource that is created during deployment.

Note: It should be conditional since there is a limit of 50 tags per resource so need to make sure we don't blindly take up 2 tags when tags aren't requested. 

## Acceptance Criteria 
*List your requirements.*
- [ ] ...
- [ ] ...
- [ ] ...

## Resources
*Provide any screenshots or conversation mockups to support your request.*
*Learn how to mock up bot conversations with [.chat files](http://aka.ms/bfchatfile).*

## Notes
Right now, developers and admins who are required to deploy to Resource Groups, due to permissions and policy where they work, have the various component of the VA Template solution thrown in with all the other resource in that Resource Group.  In those cases, things are locked down to Resource Groups, that's how lots of shops work and those Resource Groups are shared with lots of other groups and projects and they get quite messy.  In these cases, its super hard to determine what got created by the VA template and then tag things  by hand and there is risk in missing components.  Clean up in this scenario without tags is also hard since its not as simple as just delete the Resource Group that only contains the bot.  

Here is a link to Resource Tags and mentions the 50 per resource limit which is why setting a tag should only be done if the tags are passed to deploy.ps1 or specified in Templates themselves.

https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-using-tags

**Comment by lauren-mills** [comment]
So if I understand correctly, you want the ARM template to tag all the resources it creates with those two tags, which can be overridden via the ARM template parameters, correct?

**Comment by managedcoder** [comment]
Correct.  The reason for 2 parametric tags is one for an organizational tag (like “HR” or “Finance”) and the other would be for the bot itself (i.e. “Edgar HR Bot” which is separate from “Ava Helpdesk Bot” in the same company).  These tags can be used for lots of things but two scenarios there will be particularly useful with are 1) cleaning up failed attempts of deploying a bot and 2) determining ongoing operating cost of bot.   Regarding cleanup, there are lots and lots of reasons that perfectly correct deployment scripts fail as customers are initially deploying bot (they only have permission for some of the services that need to be deployed in a VA Template bot, etc.).

-Russ

**Comment by managedcoder** [comment]
Also, in case this did not come across in the ask, it would be nice if the tag name and the tag value were parametric so that I could pass in both rather than have the ARM templated hardcod the name of both.  So it would look something like deploy.ps1 --tag1Name "Division" --tag1Value "Finance" --tag2Name "Bot" --tag2Value "Edgar Finance Bot"

**Comment by lauren-mills** [comment]
I was planning on adding them to the parameters file, so it doesn't clutter up the script itself. Does that work?

**Comment by managedcoder** [comment]
Yes, that works

**Comment by lauren-mills** [comment]
Tried a couple of different ways, but I don't think it will let me conditionally add a tag based on a parameter. I can have a tag with a default name and value, that can then be overridden, but if I add one, there will be a tag on each of the resources regardless of if the user wants one. Thoughts?

**Comment by managedcoder** [comment]
Have you tried to default them to null?  If you default to null (or set to null) then I don’t think it creates a tag but I have not look at this in a while so I could be off base.

**Comment by lauren-mills** [comment]
It fails validation for me when its null.

**Comment by managedcoder** [comment]
Ok, then what makes the most sense to me is a single tag that defaults to the concatenation of the bot name and value of teh “suffix” parameter from template.json file.  If I wanted to put additional information like organizational division info I could still use that single tag and using something like a “namespace”, for example,  something like “Finance.EdgarBot.DevTest” or I could simply search for all the ARM tag occurrences in the ARM template and add extra tags everywhere a tag exists in the finished work you do.

-Russ

**Comment by darrenj** [comment]
Merged
