### ISSUE TITLE
Use different QnA services for different languages when deploying

### ISSUE THREAD

**Issue by xieofxie** [microsoft/botframework-solutions#2765]
## User Story

Currently, in deploy_cognitive_models.ps1 same QnA service is used for multiple languages.
However, `For all the knowledge bases in a QnA Maker resource, they all must be in the same language`.

## Acceptance Criteria 
*List your requirements.*
- [ ] ... Update scripts
- [ ] ...
- [ ] ...

## Resources
*Provide any screenshots or conversation mockups to support your request.*
*Learn how to mock up bot conversations with [.chat files](http://aka.ms/bfchatfile).*

## Notes
*Provide any additional information.*

Related https://github.com/MicrosoftDocs/azure-docs/issues/43539

**Comment by lauren-mills** [comment]
The issue here is that this drastically increases the cost of deploying our services due to the expense of the Azure Search service. That is why we have not done this yet.

**Comment by prakul-bansal** [comment]
Thanks for the feedback @xieofxie 

The APIs are still supporting multiple languages for KB in a service to maintain backward compatibility. However as mentioned in the [document](https://docs.microsoft.com/en-us/azure/cognitive-services/qnamaker/how-to/language-knowledge-base) here, we don't recommend to create KB in multiple languages in the same QnA Maker service as it might result in inconsistency of results and would also impact the relevance.
We have added this to our product backlog and will update our documentations to reflect the same. Thanks

**Comment by darrenj** [comment]
@Dewain27 can you work with the QnAMaker team to formalise a (cost effective) way of having multiple qna instances with the same azure search service. May require working with Azure Search team as well
