### ISSUE TITLE
.Resx files are not available in Virtual Assistant Template version 4.6.1

### ISSUE THREAD

**Issue by mohandivraniya** [microsoft/botframework-solutions#2770]
Documentation mentions that you can edit .resx files to customize responses.
However, there are no .resx files with version 4.6.1 of Virtual Assistant template.

The documentation is at below url:

https://microsoft.github.io/botframework-solutions/virtual-assistant/tutorials/customize-assistant/csharp/3-edit-responses/

**Comment by lauren-mills** [comment]
Updated the doc to reference the LG file syntax.
