### ISSUE TITLE
Virtual assistant template multi-language deployment fails

### ISSUE THREAD

**Issue by turbozapekanka** [microsoft/botframework-solutions#2776]
I'm using unmodified Virtual assistant template and trying to deploy two languages with the following steps:

Used these instructions to create, build and also installed required npm packages:
https://microsoft.github.io/botframework-solutions/virtual-assistant/tutorials/create-assistant/csharp/2-download-and-install/

Trying to deploy using this command:
**./Deployment/Scripts/deploy.ps1 -name "MyAssistant1" -location "northcentralus" -appPassword "xxx" -luisAuthoringKey "xxx" -luisAuthoringRegion "westus" -parametersFile "./Deployment/Resources/parameters.template.json" -languages "en-us,es-es"** 

Below is the result:
![image](https://user-images.githubusercontent.com/20775323/70188289-e845c680-16b5-11ea-815e-3f2037ef2ae5.png)
Note it also outputs "Done." in the end but using black color so it's not visible.

Deployment fails - MyAssistant1**es-es**_General  luis model is not created:
![image](https://user-images.githubusercontent.com/20775323/70187678-715bfe00-16b4-11ea-9a3a-befdd8749c1e.png)

See also log attached
[deploy_cognitive_models_log.txt](https://github.com/microsoft/botframework-solutions/files/3924267/deploy_cognitive_models_log.txt)

Bot is not functioning when trying to test in web chat in Azure portal. Returns "Send failed" error on any input.

**Comment by turbozapekanka** [comment]
It looks like there are two separate issues:
First one is related to Cognitive services deployment - it fails when **multiple languages** are deployed.

Second one is related to App publishing - the deployed app is not working and shows
"HTTP Error 500.30 - ANCM In-Process Start Failure" error:
![image](https://user-images.githubusercontent.com/20775323/70256612-5f2e9e00-174e-11ea-9194-ce105ad9c82e.png)

It might be related to .NET Core version mismatch - the template uses 3.0 but I noticed deployment scripts still reference 2.2

**Comment by turbozapekanka** [comment]
Please disregard the second issue.
I figured out it was related to the fact that I didn't deploy CosmosDb and that's why the App was not working. After I recompiled the code to use memory storage it works.

So it's only multiple languages deployment issue.

**Comment by jwiley84** [comment]
Hi @turbozapekanka! 

I will attempt a repro of this today!

**Comment by turbozapekanka** [comment]
@jwiley84 were you able to repro?

**Comment by dhinag** [comment]
@jwiley84 @turbozapekanka I get the same deployment error "ANCM In-Process Start Failure". It is related to .net core 3.0. I installed .net core 3.0 as extension in the azure app service and also in my local dev environment and tried publishing it, but still the same error.

**Comment by turbozapekanka** [comment]
@dhinag read above about "ANCM In-Process Start Failure" error. If you use unmodified template and use parameters.template.json for deployment it will fail because of not deployed CosmosDB and Storage accounts. You need to either deploy these two (which can be easily enabled in the mentioned json template) or find commented code and change it to use Memory.

**Comment by dhinag** [comment]
@turbozapekanka It turns out I was mixing up my foldernames and ended up deploying the wrong solution. But, wanted to highlight that the cosmosdb is getting deployed with the out of the box scripts and it is working without any changes to my startup.cs.

**Comment by turbozapekanka** [comment]
@jwiley84 any update?

**Comment by turbozapekanka** [comment]
This change fixes the issue https://github.com/microsoft/botframework-solutions/pull/2799
