### ISSUE TITLE
Adaptive card couldn't send any text back to bot

### ISSUE THREAD

**Issue by mohandivraniya** [microsoft/botframework-solutions#2779]
#### What project is affected?
Virtual Assistant

#### What language is this in?
C#

#### What happens?
When bot starts, a new user intro card (Adaptive Card) is rendered. There is no way to send a text back to bot from one of the actions rendered on card. I want to send a text back to bot. I can open an url with Action.OpenUrl, however couldn't send a text back. I looked at the documentation of AdaptiveCard json, however couldn't find anything related to this.

#### What were you expecting to happen?
I am expecting that user is able to send a text to bot from Adaptive Card action.

**Comment by lauren-mills** [comment]
This blog post has a section on how to use submit actions in adaptive cards to post a message back to the bot: https://blog.botframework.com/2019/07/02/using-adaptive-cards-with-the-microsoft-bot-framework/
