### ISSUE TITLE
[Personality Chat Dataset Update] Update to use the latest multi-language dataset

### ISSUE THREAD

**Issue by fractalcrafter** [microsoft/botframework-solutions#2786]
## User Story
As ...a virtual assistant developer
I want ...to leverage the latest multi-language personality chat datasets to be used in my Virtual Assistant
so that ...I get the best quality multi-language chitchat capabilities out of box from Bot Framework virtual assistant solution. 

## Acceptance Criteria 
*List your requirements.* 
Update to use the latest dataset for the following language in Virtual Assistant solution 
https://github.com/Microsoft/BotBuilder-PersonalityChat/tree/master/CSharp/Datasets
- [ ] English 
- [ ] Chinese
- [ ] German
- [ ] Spanish
- [ ] French
- [ ] Italian

Update documentation to inform customers that these personality chat datasets in our VA solution is updated.

**Comment by xieofxie** [comment]
Hi @elaine-chang which personality(professional, caring etc.) should we use? Or we only update document and provide tools so the user could choose themselves? Thanks~

**Comment by fractalcrafter** [comment]
For the base assistant, we should use the **professional** one (in multi-language), but for the hospitality assistant we would use the **caring** one. We have documentation for customers to change to or add additional ones they'd like. Thanks!
