### ISSUE TITLE
[Personality Chat Dataset] Update Hospitality Assistant Sample to use the Caring dataset

### ISSUE THREAD

**Issue by fractalcrafter** [microsoft/botframework-solutions#2787]
## User Story
As ...a virtual assistant developer of a hospitality assistant
I want ...to leverage the latest caring personality chat datasets to be used in my hospitality assistant 
so that ...I get the best quality multi-language caring capabilities out of box hospitality assistant

## Acceptance Criteria 
*List your requirements.*
Update to use the latest Caring personality dataset for the following language in Virtual Assistant solution
https://github.com/Microsoft/BotBuilder-PersonalityChat/tree/master/CSharp/Datasets
- [ ]  English
- [ ] Chinese
- [ ] German
- [ ] Spanish
- [ ] French
- [ ] Italian

Update documentation for hospitality asistant sample to indicate this new update:
https://microsoft.github.io/botframework-solutions/solution-accelerators/assistants/hospitality-assistant/

**Comment by xieofxie** [comment]
@elaine-chang Should we update ones already in original Chitchat? For example special ones like "What's your name" "My name is the Virtual Assistant! Nice to meet you :)".

**Comment by ryanisgrig** [comment]
@xieofxie I've updated the Hospitality VA With the latest VirtualAssistantsSample, you're free to update the KB whenever

**Comment by xieofxie** [comment]
@elaine-chang I just add several examples to indicate the update. Please help to update documents about caring chitchat dataset.

@ryanlengel Hotel Faq is removed now, should we remove examples part from document?
