### ISSUE TITLE
[Multilanguage] General LUIS model deployment fails due to unsupported entity

### ISSUE THREAD

**Issue by ryanisgrig** [microsoft/botframework-solutions#2796]
#### What project is affected?
Virtual Assistant template

#### What language is this in?
LUIS models

#### What happens?
In French, Italian, Spanish, and Chinese the General LUIS model deployment fails because the `personName` entity is not supported in those languages, but carried over from

#### What are the steps to reproduce this issue?
Run deployment scripts with all languages

#### What were you expecting to happen?
All LUIS models deploy successfully

**Comment by xhr0804** [comment]
The personName entity can be supported in English and Chinese, but can't support in the Fr/It/Es/De.
In the previous ludown version, this tool can automatically filter the unsupported entity in each language. But in the latest version, it may cause problem.
I have submit a PR which fixes the .lu file directly to solve this problem.

**Comment by ryanisgrig** [comment]
@xhr0804 I have found another issue with just the Chinese language models: "Labels cannot have two overlapping children of the same parent."

**Comment by ryanisgrig** [comment]
Assigning @lauren-mills as she's fixed this on an in progress branch
