### ISSUE TITLE
Proactive Notification on Emulator Not working

### ISSUE THREAD

**Issue by Adityagrao** [microsoft/botframework-solutions#2798]
#### What project is affected?
Bot Framework SDK 4.5.1
#### What language is this in?
C# 
#### What happens?
I am using Proactive Notification with Emulator and Running the Function App as a Console App and trying to execute a Notification When the Bot is Published and is accessed via WebChat the Console App works and I see the notification in the WebChat,
When I try to do the same with the emulator the Notification is not received. 
#### What are the steps to reproduce this issue?

```
attachmentLayout: "list"
channelId: "emulator"
entities:
from : 
**id: "53864a20-1b1e-11ea-9c90-9d1f02a14323"**
inputHint: "acceptingInput"
localTimestamp: "2019-12-10T07:26:05+00:00"
locale: "en-US"
recipent :
replyToId: "4f7ca8c1-1b1e-11ea-9c90-9d1f02a14323"
serviceUrl: "http://localhost:50816"
speak: "Hi, I am Maisy. Now that I am up and running, Let us begin your Magical Business Journey."
timestamp: "2019-12-10T07:26:05.250Z"
type: "message"
```

If this is the JSON payload I am using the From ID in my EventDataType UserId variable.

I also tried changing the UserID in Emulator(4.6.0) and tried that in UserId which does not seem to work also
#### What were you expecting to happen?
Expecting to see the notification on the Emulator 
#### Can you share any logs, error output, etc.?

Console App which mimics the Function App 

```CS
using Microsoft.Bot.Connector.DirectLine;
using System;
using System.Threading.Tasks;

namespace EventHandler
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
            SendEventToBot();
        }

        public static async void  SendEventToBot()
        {
            // read from user preference store to determine where to send notifications
            EventDataType eventData = new EventDataType();

            // Post the message to the Bot

            // Connect to the DirectLine service
            var client = new DirectLineClient("----------xxx------------");
            var conversation = client.Conversations.StartConversation();
           // var conversation = await client.Conversations.StartConversationAsync();

            // Use the text passed to the method (by the user)
            // to create a new message
            var userMessage = Activity.CreateMessageActivity() as Activity;
            userMessage.Text = eventData.Message;
            userMessage.Type = ActivityTypes.Event;
            userMessage.Name = "BroadcastEvent";
            userMessage.Value = eventData;
            userMessage.From = new ChannelAccount("user1");

            var response = await client.Conversations.PostActivityAsync(conversation.ConversationId, userMessage);

        }
    }
}

```

I am using this setup as it's easy to test and add more features to the Proactive Notification.

**Comment by lzc850612** [comment]
Thanks for raising this issue. So in order for the Proactive Notification to work, the bot that'll receive the notification which will then send the message to the user is the cloud-hosted one. When you're using an emulator, you wouldn't be able to receive the notification because you're connected to the local bot which the Directline API (the code that sends the notification to the bot) doesn't have any idea about. One thing you could use to fix this is to use ngrok for your local hosted bot and change the bot's endpoint setting to be the ngrok URL. This way the Directline API will be able to send the message to your local bot with the help of ngrok tunneling and you would be able to see the notification in emulator.

**Comment by Adityagrao** [comment]
@lzc850612 
I think it would be great if the same can be updated in the documentation  in the Proactive Notification Docs  [here](https://microsoft.github.io/botframework-solutions/solution-accelerators/tutorials/enable-proactive-notifications/4-virtual-assistant/)

**Comment by darrenj** [comment]
Thanks @Adityagrao - @lzc850612  can you PR the doc change so we can close this? Thanks
