### ISSUE TITLE
(PlayMusic) Identify Artist / Song / Album / Genre of Music Play Request

### ISSUE THREAD

**Issue by Dewain27** [microsoft/botframework-solutions#28]
There is currently not a skill that will allow a user to request to play a song / artist / album / or Genre of Music.  This is a typically needed use case for many device types.

Solution should allow for a user to state:
Play "Genre" music
Play "Song" by "Artist"
Play "Song"
Play "Album"
Play "Album" by "Artist"

The solution will need to provide disambiguation of multiple and return an Event much like the POI Find skill that would allow the skill to launch with context the music service / app of choice

**Additional context**
This skill is not to stream the music, but to find the appropriate information to then send to the host to allow music the correct music to be passed to a backend service API.

**Comment by darrenj** [comment]
Replaced by #929
