### ISSUE TITLE
Enterprise Template created Bot isn't responding when added to Teams

### ISSUE THREAD

**Issue by darrenj** [microsoft/botframework-solutions#280]
**Project**
Enterprise Template

**Description**
Transferred from [Docs Issue](https://github.com/MicrosoftDocs/bot-docs/issues/493)

Hey, I've created a bot using Enterprise template. I deployed to Azure and able to get a reply using web channel.
However after enabling the Teams channel I've copied the AppID to Ms teams but unable to get any reply. Normal echo bot (v4) is able to get reply in Teams. I wish to know if there is any knows compatibility issues.

**To Reproduce**
Create a Bot from Enterprise Bot and connect to Teams

**Expected behavior**
It works as per webchat and other channels

**Comment by ivlaevski** [comment]
#228 is a result of the same behavior - start conversations is not triggered and service is crashing.

**Comment by ivlaevski** [comment]
same behavior is to observe with Skype channel.
it's not working in Azure Test your bot pane also.

**Comment by ryanisgrig** [comment]
I'm running locally from Teams to my bot and I'm unable to get to `OnStartAsync` in the MainDialog. I can observe that the dialogs are added with each message sent over, but MainDialog is not actually triggered.

**Comment by ryanisgrig** [comment]
Actually I'm not sure that with Teams/Skype the bot is ever hitting `await dc.BeginDialogAsync(nameof(MainDialog))`. The first time I sent a message to my Teams bot, `OnTurnAsync` of `EnterpriseBot.cs` was triggered adding both bot and user to the conversation. With each subsequent message sent, `OnTurnAsync` is not hit but the EnterpriseBot constructor is (explains my earlier comment).

**Comment by NobinJoseRad** [comment]
Thank you for the explanations. Is there any resolution to this issue or Teams is not supported for the Enterprise Template?

**Comment by ryanisgrig** [comment]
@NobinJoseRad this is still under investigation, stay tuned.

**Comment by NobinJoseRad** [comment]
thank you so much.. Will watch this space..

**Comment by NobinJoseRad** [comment]
Just to update that I've tried to update the dll to 4.1.5.. no change..

**Comment by ivlaevski** [comment]
May the problem be in the connection (responsiveness) of CosmosDB - how the code will act if conversation state is not found? May be this is why it enters the constructor instead of OnTurn... 
( I'm relaing on #228 )

**Comment by NobinJoseRad** [comment]
thanks @ivlaevski  for the pointer. However I am thinking the responsiveness of cosmos db should be the same regardless of channels..

**Comment by NobinJoseRad** [comment]
Hoping to have a solution..

**Comment by ryanisgrig** [comment]
We've published the latest template (with a fix for this) to the marketplace. PR #320 shows the changes, and you can compare your existing ET bot with the [Enterprise sample](https://github.com/Microsoft/AI/tree/master/templates/Enterprise-Template/src/csharp/EnterpriseBotSample).
