### ISSUE TITLE
404 on https://microsoft.github.io/botframework-solutions/skills/samples/experimental

### ISSUE THREAD

**Issue by rmthurman** [microsoft/botframework-solutions#2806]
404 on https://microsoft.github.io/botframework-solutions/skills/samples/experimental

**Comment by lauren-mills** [comment]
@rmthurman we now have individual docs for each of the experimental skills that you can find in the side nav under Skills > Samples > Experimental Skills. Can you let me know where you originally found this link so I can update/remove it?

**Comment by darrenj** [comment]
@ryanlengel I did a search across the repo ([example](https://github.com/microsoft/botframework-solutions/search?q=skills%2Fsamples%2Fexperimental&unscoped_q=skills%2Fsamples%2Fexperimental)) and found a few references which don't have a good place to update too it seems. We have [this page](https://microsoft.github.io/botframework-solutions/overview/skills/) which covers the more formalised skills but not an equivalent page summarising each experimental skill beyond the nav on the left hand side.

Could we look at creating a page like the above for experimental which we can update these 404 broken links too?

**Comment by darrenj** [comment]
Addressed
