### ISSUE TITLE
Find Email Flow doesn't let you escape by saying none

### ISSUE THREAD

**Issue by darrenj** [microsoft/botframework-solutions#281]
**Project**
Skills

**Description**
Saying "None" when prompted for which email to read generates a series of errors.

**To Reproduce**
- Say Find Email
- Say None when prompted with "Which email do you want more details on?"

![image](https://user-images.githubusercontent.com/33519520/48329455-caff0f80-e5fd-11e8-9db6-95f581c73fb4.png)

**Expected behavior**
The email flow to finish. Test with other variations on "no" (e.g. confirmno prompt as used by other skills)

**Comment by DingmaomaoBJTU** [comment]
Not repro now.
