### ISSUE TITLE
[Docs]  The Experimental Skills link returns 404

### ISSUE THREAD

**Issue by mscherotter** [microsoft/botframework-solutions#2814]
/overview/skills/

The Experimental Skills link on this page returns 404 when clicked.

**Comment by ryanisgrig** [comment]
Thanks @mscherotter, this card has been removed as that page was split into docs for individual skills.
For now you can access these on the side bar: 
![image](https://user-images.githubusercontent.com/43043272/70824414-12bf1000-1d97-11ea-9764-e347d5d2db6a.png)
