### ISSUE TITLE
[Docs] NewUserGreeting.json does not exist

### ISSUE THREAD

**Issue by zipswich** [microsoft/botframework-solutions#2819]
/virtual-assistant/tutorials/customize-assistant/csharp/2-edit-your-greeting/

NewUserGreeting.json described in the document cannot be found in a virtual assistant project created on 2019-12-14 with all the latest packages.

**Comment by lauren-mills** [comment]
The .json for this attachment can now be found in the MainResponses.lg language generation file. Adding this to the backlog to update the documentation.

**Comment by zipswich** [comment]
Thanks. [The instructions](https://microsoft.github.io/botframework-solutions/virtual-assistant/tutorials/create-assistant/csharp/1-intro/) helped a lot at the [Global AI Boot Camp](https://globalai.community/global-ai-bootcamp/united-states-boston) last weekend.  This is where we got stuck near the end.

**Comment by darrenj** [comment]
Updated - good spot!
