### ISSUE TITLE
[Botskills] Allow for chaining multiple skills to connect in a single command

### ISSUE THREAD

**Issue by ryanisgrig** [microsoft/botframework-solutions#2821]
## User Story
As ... a build developer
I want ... to chain connecting skills to my VA
so that ... my pipeline scripts can be efficient

## Acceptance Criteria 
*List your requirements.*
- [ ] Blocked by #1872, which requires a local LU file. After this is complete, we should only need to know a manifests endpoint and the languages
- [ ] Accept a comma-seperated string of remote manifest URLs that will be run against each language specified

## Resources
*Provide any screenshots or conversation mockups to support your request.*
*Learn how to mock up bot conversations with [.chat files](http://aka.ms/bfchatfile).*

Current state:
![image](https://user-images.githubusercontent.com/43043272/70929722-93287f80-1fe8-11ea-9e25-e7a5c7243676.png)

## Notes
*Provide any additional information.*

Currently, if a user adds multiple skills to a bot they need a `botskills connect` for each skill which can be tedious as more are added and need to be maintained

##### Adding some multilanguage skills and other English only
`botskills connect --remoteManifest "{skill_1},{skill_2}"  --cs  --languages 'en-us,es-es,zh-cn'`
`botskills connect --remoteManifest "{skill_3},{skill_4}"  --cs --languages 'en-us'`

**Comment by xieofxie** [comment]
Or save them in variable groups? Then use a for loop as a work around

**Comment by ryanisgrig** [comment]
That's also an option, either will be inhibited by the luisFolder requirement we currently have. I think this will be a common enough issue that it should be baked in rather than fixing with a custom script.

**Comment by peterinnesmsft** [comment]
Moving this to internal backlog for further tracking.
