### ISSUE TITLE
Typescript code version of ITSM skill

### ISSUE THREAD

**Issue by zap7** [microsoft/botframework-solutions#2833]
## User Story
Please provide a typescript version of the ITSM skill asap.
## Acceptance Criteria 
ITSM skill which provides an ability to log a service desk ticket to ServiceNow using the Typescript programming language. This skill should easily be added to the Virtual assistant as other skills do.

## Resources
*Provide any screenshots or conversation mockups to support your request.*
*Learn how to mock up bot conversations with [.chat files](http://aka.ms/bfchatfile).*

## Notes
*Provide any additional information.*

**Comment by darrenj** [comment]
We don't have any plans to create a typescript only version, the c# one is an experimental version to showcase the options to generate feedback on future steps. With the planned updates to the typescript virtual assistant you'll soon be able to call a C# skill from typescript so you could perhaps go that route when ready?
