### ISSUE TITLE
[Automotive] Cognitive model deployment errors

### ISSUE THREAD

**Issue by ryanisgrig** [microsoft/botframework-solutions#2834]
#### What project is affected?
Automotive Skill

#### What language is this in?
C#

#### What happens?
1. The Settings LUIS app has the error: `Labels cannot have two overlapping children of the same parent.
`
1. There is a SettingsDispatch LUIS app in source code, is this expected for this Skill or an accidental check in?

#### What are the steps to reproduce this issue?
Run the deploy_cognitive_models script

#### What were you expecting to happen?
Successful deployment of all cognitive models

**Comment by bobokids** [comment]
Issue 1: not repro with cli 4.7.
Issue 2: does @darrenj know the reason?

**Comment by ryanisgrig** [comment]
Thanks @bobokids, I was still on 4.6.
@darrenj thoughts on the latter? If not then it can probably be removed, our previous demo environment doesn't utilize this.

**Comment by bobokids** [comment]
@darrenj so we just remove the SetttingDispatch part?

**Comment by darrenj** [comment]
I can't repro this now?
