### ISSUE TITLE
[Skills] Manifest templates need to support multilanguage capabilities

### ISSUE THREAD

**Issue by ryanisgrig** [microsoft/botframework-solutions#2837]
#### What project is affected?
- Calendar
- Email
- To Do
- Point of Interest

#### What language is this in?
C#

#### What happens?
Running `botskills connect --languages 'en-us,de-de,it-it,fr-fr,es-es,zh-cn'` on the productivity/poi skills in source for all languages fails as only English is shown out of the box.

#### What are the steps to reproduce this issue?
Run above command on the demo environments

#### What were you expecting to happen?
`botskills connect` successfully finds all the languages deployed

**Comment by darrenj** [comment]
New manifests added with all languages provided
