### ISSUE TITLE
Ensure the {Dialog}Responses.json files have localised versions for EN, FR, DE, IT, ES and ZH

### ISSUE THREAD

**Issue by darrenj** [microsoft/botframework-solutions#284]
**Project**
Skills

**Description**
The Skills currently have EN and ZH responses provided as part of the source-code. We need to track a work-item to add FR, DE, IT and ES variations. The base level Virtual Assistant has completed this localisation and it's important that the Skills provide this.

The Translator can be used to create the first variant with human translators then providing fixup and we could explore a simple tool to go through all the JSON files and do this for you. First step would be the MT versions

**To Reproduce**
Observe the ZH and EN only files
![image](https://user-images.githubusercontent.com/33519520/48350405-ea1c9200-e63b-11e8-876e-a5d6e7e23c1f.png)

**Expected behavior**
EN,FR, IT, DE, ES and ZH versions of all responses

**Comment by lauren-mills** [comment]
Moving to Vanadium.

**Comment by bobokids** [comment]
in PR review
