### ISSUE TITLE
Virtual Assistant Deployment fails (The specified app service plan was not found.)

### ISSUE THREAD

**Issue by turbozapekanka** [microsoft/botframework-solutions#2841]
#### What project is affected?
Virtual assistant template

#### What language is this in?
C#

#### What happens?
Deployment fails with "The specified app service plan was not found." error.
_Note: The same deployment with exactly the same parameters worked last week, I was able to deploy on Dec 11 2019._

#### What are the steps to reproduce this issue?
Follow the instruction to deploy the bot: https://microsoft.github.io/botframework-solutions/virtual-assistant/tutorials/create-assistant/csharp/1-intro/

I used the following parameters:
_./Deployment/Scripts/deploy.ps1 -name "MyAssistant1" -location "southcentralus" -appPassword "xxx" -luisAuthoringKey "xxx" -luisAuthoringRegion "westus" -parametersFile "./Deployment/Resources/parameters.template.json" -languages "en-us"_

#### What were you expecting to happen?
The deployment completes successfully.

#### Can you share any logs, error output, etc.?
[deploy_log.txt](https://github.com/microsoft/botframework-solutions/files/3988693/deploy_log.txt)

#### Any screenshots or additional context?
![image](https://user-images.githubusercontent.com/20775323/71261955-3ee11080-2304-11ea-9d94-4838b40f1a02.png)

**Comment by lauren-mills** [comment]
Hi @turbozapekanka, this is a known issue with QnA Maker. Take a look at this issue for the workaround: https://github.com/microsoft/botframework-solutions/issues/2762#issuecomment-562240133

**Comment by turbozapekanka** [comment]
Thanks, that comment helped.

**Comment by damaca** [comment]
I posted the same question in https://github.com/microsoft/botframework-solutions/issues/2762 also...so ¿which one (configuration) is the good one to use?

**Comment by lauren-mills** [comment]
@damaca - The change I mentioned is the "correct" way according to the QnA Maker and App Service teams. Even though the old way works in some regions, its best to make the change in case the Azure services in those regions are also updated.

**Comment by bruno-petroveski** [comment]
Hi all!
Sorru, but I have exactly the same problem, but I didn't understand what I should do to fix it. Could someone, please, explai men what I should do to be able to solve this and deploy this chatbot?
tks

**Comment by bruno-petroveski** [comment]
Hi!
I found the solution on the link you commented, thank you very much!
