### ISSUE TITLE
The Enable Speech page is broken[Docs]

### ISSUE THREAD

**Issue by anniexudan** [microsoft/botframework-solutions#2848]
/virtual-assistant/tutorials/customize-assistant/csharp/5-next-steps/
404 page not found in the 'Enable Speech' section

**Comment by xieofxie** [comment]
Thanks~ It is here https://microsoft.github.io/botframework-solutions/clients-and-channels/tutorials/enable-speech/1-intro/
Fix is on the way.

**Comment by darrenj** [comment]
Merged - thanks for letting us know!
