### ISSUE TITLE
Review all response InputHints to ensure acceptingInput and expectingInput is correct

### ISSUE THREAD

**Issue by darrenj** [microsoft/botframework-solutions#285]
**Project**
Skills

**Description**
Ensure that all responses in the appropriate JSON files have the right InputHint. See [this](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-add-input-hints?view=azure-bot-service-3.0) for more information.

All use of expectingInput should be reviewed followed by another pass to ensure prompts are all set to expectingInput apart from "holding" messages like "looking into it" which should use ignoringInput.

**To Reproduce**
For example this response sets inputHint to expectingInput rather than acceptingInput. An error condition like this is the end of the dialog flow and the microphone shouldn't be added.
```
 "EventCreationFailed": {
    "replies": [

      {
        "text": "Event creation failed",
        "speak": "Event creation failed"
      },
      {
        "text": "Something went wrong, try again please.",
        "speak": "Something went wrong, try again please."
      },
      {
        "text": "It seems the event could not be created, please try again later.",
        "speak": "It seems the event could not be created, please try again later."
      },
      {
        "text": "Creation of the event failed, please try again.",
        "speak": "Creation of the event failed, please try again."
      },
      {
        "text": "An error occured with creating the event.",
        "speak": "An error occured with creating the event."
      }
    ],
    "inputHint": "expectingInput"
  },
```

**Expected behavior**
expectingInput is **only** used on prompts, ignoring input for transient "waiting messages" and "acceptingInput" when you've finished something.

**Comment by feich-ms** [comment]
@darrenj Hi Darren, How to set inputHint for a AdaptiveCard response?

**Comment by darrenj** [comment]
@feich-ms You can go ahead and set the InputHint directly on the Activity that you add the AdaptiveCard too.

e.g. on the replyToConversation object

```
var replyToConversation = sc.Context.Activity.CreateReply(DeleteEventResponses.MultipleEventsStartAtSameTime);
                    replyToConversation.AttachmentLayout = AttachmentLayoutTypes.Carousel;
                    replyToConversation.Attachments = new List<Microsoft.Bot.Schema.Attachment>();                    

                    var cardsData = new List<CalendarCardData>();
                    foreach (var item in events)
                    {
                        var meetingCard = item.ToAdaptiveCardData(state.GetUserTimeZone());
                        var replyTemp = sc.Context.Activity.CreateAdaptiveCardReply(CalendarMainResponses.GreetingMessage, item.OnlineMeetingUrl == null ? "Dialogs/Shared/Resources/Cards/CalendarCardNoJoinButton.json" : "Dialogs/Shared/Resources/Cards/CalendarCard.json", meetingCard);
                        replyToConversation.Attachments.Add(replyTemp.Attachments[0]);
                    }
```

**Comment by feich-ms** [comment]
Changes of ToDo/Email/Calendar skills are merged so close this issue.
