### ISSUE TITLE
[Virtual Assistant Template] mainDialog not working for message events

### ISSUE THREAD

**Issue by nestoralonsovina** [microsoft/botframework-solutions#2861]
#### What project is affected?
botbuilder-solutions
#### What language is this in?
Typescript
#### What happens?
The bot seems to be unable to resolve the promise on routerDialog.js
`        const status = await this.onInterruptDialog(innerDc);
`
when the event is a message
#### What are the steps to reproduce this issue?
I've just replaced the onboardingdialog with an OAuth dialog
#### What were you expecting to happen?
direct to route
#### Any screenshots or additional context?
<img width="502" alt="Screenshot 2020-01-08 at 16 03 00" src="https://user-images.githubusercontent.com/21134673/71988715-b08bea80-3230-11ea-9df4-83d997ac20be.png">

**Comment by DiegoCardozo94** [comment]
Hi @nestoralonsovina, thanks for reporting this issue!

1. Can you provide the necessary repro steps to reproduce your scenario?
1. Are you using the [sample-assistant](https://github.com/microsoft/botframework-solutions/tree/master/templates/Virtual-Assistant-Template/typescript/samples/sample-assistant) of `master` branch?
1. Which version are you using of botbuilder-solutions? Can you check if it's [botbuilder-solutions@4.4.9](https://www.npmjs.com/package/botbuilder-solutions/v/4.4.9) which is the latest of `npmjs`?

Currently, we are migrating the latest changes of [0.7Beta Release](https://github.com/microsoft/botframework-solutions/releases/tag/v0.7-beta) to the TypeScript solutions (including [botbuilder-solutions](https://github.com/microsoft/botframework-solutions/tree/master/sdk/typescript/libraries/botbuilder-solutions) library)

Thank you,
Diego

**Comment by nestoralonsovina** [comment]
> Hi @nestoralonsovina, thanks for reporting this issue!
> 
> 1. Can you provide the necessary repro steps to reproduce your scenario?
> 2. Are you using the [sample-assistant](https://github.com/microsoft/botframework-solutions/tree/master/templates/Virtual-Assistant-Template/typescript/samples/sample-assistant) of `master` branch?
> 3. Which version are you using of botbuilder-solutions? Can you check if it's [botbuilder-solutions@4.4.9](https://www.npmjs.com/package/botbuilder-solutions/v/4.4.9) which is the latest of `npmjs`?
> 
> Currently, we are migrating the latest changes of [0.7Beta Release](https://github.com/microsoft/botframework-solutions/releases/tag/v0.7-beta) to the TypeScript solutions (including [botbuilder-solutions](https://github.com/microsoft/botframework-solutions/tree/master/sdk/typescript/libraries/botbuilder-solutions) library)
> 
> Thank you,
> Diego

We're using the master branch of the virtual assistant template (it's the same as the one generated 2-3 weeks ago with yeoman I suppose) and version 4.4.9 of botbuilder-solutions

Steps to reproduce the bug are difficult to give, and one of the reasons I was a bit reluctant to open this issue. It suddenly appeared two days ago, I've tried creating a template for scratch and simply copy-pasting the config files (appsettings.json and cognitivemodels.json) and it still does not work, with the error appearing on the same spot.

We're running the bot locally with the botframework emulator (with ngrok), both on Windows and macOS, we've also tried to deploy the bot and it persists on the web chat and teams. 

I think this is all the information I can give you, and maybe you have something to say about how we could fix it.

Thanks,
Nestor

**Comment by nestoralonsovina** [comment]
After deactivating the following middlewares: 
`this.use(new TranscriptLoggerMiddleware(transcriptStore));`
`this.use(new ShowTypingMiddleware());`
An error finally shows on the botframework emulator:

<img width="1114" alt="Screenshot 2020-01-09 at 09 35 53" src="https://user-images.githubusercontent.com/21134673/72051805-39a03180-32c4-11ea-8fb1-80119bf47a75.png">

I'm still looking for the source. What it seems strange to me it's that the problem is with LUIS intentions, and the code never reaches the route method of the mainDialog.
I would love to hear any feedback that you might have.

Thanks,
Nestor

**Comment by nestoralonsovina** [comment]
We've finally arrived at an incompatibility between two intentions in LUIS, therefore I close the issue since it's not related to the template.

Thanks.
