### ISSUE TITLE
ludown and luisgen are now replaced by BF CLI, will BOTSKILLS be updated?

### ISSUE THREAD

**Issue by rvallireply** [microsoft/botframework-solutions#2866]
Hello,
how do we connect skills now that the current botskills seems obsolete?
Thanks

**Comment by lauren-mills** [comment]
Hi @rvallireply - The botskills tool will be moving to the bf cli in the future but for now it is still the correct way to connect skills to your VA.

**Comment by rvallireply** [comment]
Sorry, but the botskills command is giving me an error while connecting

```
Error: The execution of the ludown command failed with the following error:
[ERROR] line 195:0 - line 195:1: syntax error: invalid input '@' detected. Expecting one of this - end of file, model description, new line, QnA definition, Intent definition, Entity definition, Import statement
```
and

```
[ERROR] line 209:2 - line 209:3: syntax error: invalid input '-' detected. Expecting one of this - end of file, model description, new line, QnA definition, Intent definition, Entity definition, Import statement

```
And that is trying to connect a skill to a bot where both taken individually work perfectly, only trying to connect them via "botskills connect" I have multiple of this error for the command 

```
ludown parse toluis --in "C:\Users\...\source\repos\Itsmskill_IT\Deployment\Resources\LU\it-it\ITSM.lu" --luis_culture it-it --out_folder "C:\Users\...\source\repos\Itsmskill_IT\Deployment\Resources\LU\it-it" --out ITSM.luis
```


for lines like the following in the ITSM.lu file

```
> # Phrase list definitions
@ phraselist ticket_create_phrase(interchangeable) = 
	- aggiungere, aggiunto, creare, creato, aprire, aperto, segnalare, segnalato
```


Why is ludown giving me these errors if the botskills connect is still meant to use it?

**Comment by rvallireply** [comment]
solved: I had to relaunch a ludown refresh and the lu file got created correctly. Then I was able to connect the skill with botskills connect.
