### ISSUE TITLE
[Docs] clarification on continuous deployment steps

### ISSUE THREAD

**Issue by sowsan** [microsoft/botframework-solutions#2881]
/solution-accelerators/tutorials/enable-continuous-deployment/3-configure-pipeline/

It's not clear that, what is the username, password to be passed. Is it supposed to be the botAppId as userName? Also, along with the screenshots if you can provide some samples of script and details mentioned in the doc would be helpful. Also, a copy of the YAML file of the release pipeline. Thanks!

**Comment by darrenj** [comment]
Apologies for the confusion - it's the username/password for your Azure tenant.

**Comment by darrenj** [comment]
Doc update when you get a moment to clarify the username/password. Thanks

**Comment by Batta32** [comment]
@darrenj, we created #3151 updating the Continuous Deployment documentation.

Also, we will be updating the documentation of CI and CD to integrate the latest changes of the solutions in the YAML files and the Release configuration.

@sowsan - If you have any feedback, don't hesitate to point it in the PR 😊.
