### ISSUE TITLE
Calendar Skill to include suggested actions

### ISSUE THREAD

**Issue by Dewain27** [microsoft/botframework-solutions#2890]
## User Story
As a user I want 
I want to be suggested the actions that I can take in the next step
so that I can better understand potential options in the dialog

## Acceptance Criteria 
*List your requirements.*
- [ ] Show me my calendar actions should use suggested actions to allow visual guidance to the user

## Resources
![image](https://user-images.githubusercontent.com/18688053/72559520-95d9f700-386a-11ea-810e-48f18fa25758.png)

## Notes
I recommend that we go through the entire dialog and where appropriate add suggested actions to assist in guiding the user through the dialog effectively.

**Comment by emivers8** [comment]
Suggested actions are included in the adaptive card redesign, currently in progress, which will directly address this issue. We're on track to get updates in the code within the next couple months.
