### ISSUE TITLE
[Docs] Experimental Skills Menu Item not working

### ISSUE THREAD

**Issue by Dewain27** [microsoft/botframework-solutions#2892]
/solution-accelerators/assistants/enterprise-assistant/

The menu on the left for Experimental Skills is not functioning

![image](https://user-images.githubusercontent.com/18688053/72561094-0c2c2880-386e-11ea-8bca-bfd3fceb1618.png)

**Comment by ryanisgrig** [comment]
Observed the URI is 
![image](https://user-images.githubusercontent.com/43043272/72566129-24994480-3868-11ea-9b52-37b0be380078.png)

Other menus do not have the title in them
![image](https://user-images.githubusercontent.com/43043272/72566150-2ebb4300-3868-11ea-9206-5f119b7f0252.png)

**Comment by xieofxie** [comment]
It should be fixed in https://github.com/microsoft/botframework-solutions/pull/2886

**Comment by darrenj** [comment]
Fixed in next

![image](https://user-images.githubusercontent.com/33519520/73162385-95045900-40e5-11ea-8f54-502c09233869.png)
