### ISSUE TITLE
Azure DevOps YML import fails for Pipeline\<project name>.yml file

### ISSUE THREAD

**Issue by managedcoder** [microsoft/botframework-solutions#2899]
#### What project is affect
Virtual Assistant project

#### What language is this in?
C# but perhaps others if they have a YML pipeline file

#### What happens?
In Azure DevOps, when I try to import the .yml file that was created by the Visual Studio 2019 C# Virtual Assistant project template from the Pipeline folder, I get the following JSON Error: "The exported JSON is not valid or is not compatible with the current product version. Try exporting and importing again."

#### What are the steps to reproduce this issue?
Create a Azure DevOps project, go to Pipelines in left nav then click down arrow next to "+ New" which is over the list of pipelines (or it might be an empty list if you haven't added a pipeline yet).  Finally, browse to Pipeline folder in your VA project on local disk and import the .yml file and you  should see the error.

#### What were you expecting to happen?
A successful import

#### Can you share any logs, error output, etc.?
"The exported JSON is not valid or is not compatible with the current product version. Try exporting and importing again."

#### Any screenshots or additional context?
![image](https://user-images.githubusercontent.com/17769186/72733747-7abb0000-3b66-11ea-843c-97fe2132d9dc.png)

**Comment by Batta32** [comment]
Hi @managedcoder, thanks for reporting the issue! 
We managed to reproduce the pipeline's issue using the `.yml` file from Virtual Assistant in C#.

![image](https://user-images.githubusercontent.com/11904023/73189557-5a111e00-4103-11ea-8da2-d9e73730867a.png)

We will be reviewing the `.yml` files and get back to you later 😊.

**Comment by Batta32** [comment]
@managedcoder, we noticed that the file you are trying to import is a `.yml` while the one it's needed should be a `.json` file.

![image](https://user-images.githubusercontent.com/11904023/73192677-2258a500-4108-11ea-94c0-7141868c606a.png)

If you want to **use** the `.yml` files you should follow these [steps](https://microsoft.github.io/botframework-solutions/solution-accelerators/tutorials/enable-continuous-integration/csharp/4-configure-build-steps/).
However, to **transform** a `.yml` to a `.json` one, there are many online tools to achieve it (e.g [onlineyamltools](https://onlineyamltools.com/convert-yaml-to-json)).

@lauren-mills - should we add the `.json` files in addition to the `.yml` ones in the [Pipeline](https://github.com/microsoft/botframework-solutions/tree/master/templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Pipeline) folder?

**Comment by darrenj** [comment]
I think adding the json files might be a good idea!

**Comment by Batta32** [comment]
We will keep this issue open while we are researching about the .JSON files for the import of a new pipeline.
