### ISSUE TITLE
[POI] Call POI Event Action

### ISSUE THREAD

**Issue by Dewain27** [microsoft/botframework-solutions#29]
## User Story
As ...
I want ...
so that ...

## Acceptance Criteria 
*List your requirements.*
- [ ] ...
- [ ] ...
- [ ] ...

## Resources
*Provide any screenshots or conversation mockups to support your request.*
*Learn how to mock up bot conversations with [.chat files](http://aka.ms/bfchatfile).*

## Notes
*Provide any additional information.*

POI Skill today offers Event for Find a Route, however we should also add the Event for Call the POI.  This is a common need in many devices that have ability to call.

Adaptive Cards will need to be updated as well as LUIS and Dialog to allow you to do actions as "Navigate to the first one" or "Call the second one"

**Comment by darrenj** [comment]
Now possible with FourSquare data, if so we should also show number on adaptive card enabling it to "just work" on richer canvases? @ryanlengel

**Comment by ryanisgrig** [comment]
Yes adding a url with `tel:NUMBER` should be interpreted with an OS's native dial app.

**Comment by ryanisgrig** [comment]
Should this be linked to the Android app development where it would call a native dialer?

**Comment by Dewain27** [comment]
@ryanlengel you may want to check with @lauren-mills on how this might relate to #242

**Comment by ryanisgrig** [comment]
Seems related to the Phone Skill PR at #1659

**Comment by ryanisgrig** [comment]
Closed via #2209
