### ISSUE TITLE
Update script claims prediction resource regions are invalid

### ISSUE THREAD

**Issue by ryanisgrig** [microsoft/botframework-solutions#2906]
#### What project is affected?
Deployment scripts

#### What language is this in?
Powershell/CLI

#### What happens?
Using the new authoring and prediction resources on my LUIS apps, I am unable to run the cognitive models script with my correct regions. My apps use the following:
Authoring resources: westus
Prediction resource: westus2

When running the script with both regions set as "westus", the process is successful. However, when running these cognitive models against a bot they hit an Unauthorized error.

When running the script with authoring as "westus" and prediction as "westus2", the process is unsuccessful. However, I am correctly authorized to hit my apps and can continue conversations with my bot.

#### What are the steps to reproduce this issue?
Update apps with prediction resources in an "invalid" region (that is now technically valid).

#### What were you expecting to happen?
I should be able to 

#### Can you share any logs, error output, etc.?
When using prediction region as "westus2", the update log looks like:
```
AZ CLI passes minimum version. Current version is 2.0.78
Invalid region
Region is required
```

#### Any screenshots or additional context?

LUIS apps
**Authoring resources**
![image](https://user-images.githubusercontent.com/43043272/72838240-c93ecc00-3c44-11ea-9a84-c651bb532a24.png)

**Prediction resources**
![image](https://user-images.githubusercontent.com/43043272/72838230-bfb56400-3c44-11ea-8d45-3d3527bb128b.png)

**Comment by darrenj** [comment]
@lauren-mills is this resolved?

**Comment by peterinnesmsft** [comment]
Confirmed with @lauren-mills offline that this is resolved.
