### ISSUE TITLE
CICD Issue on deployment process on powershell script

### ISSUE THREAD

**Issue by jiangsheng-msft** [microsoft/botframework-solutions#2907]
Hi,

One of my customer raised an issue about Virtual Assistant continuous deployment:

I am following the virtual assistant template in the bot framework solutions.  https://microsoft.github.io/botframework-solutions/solution-accelerators/tutorials/enable-continuous-deployment/3-configure-pipeline/

In the CICD especially the last portion of update cognitive models script, the template itself just provides a powershell ready from the VA, now I didn't modify the script, I just stay as it is, upon checking the logs, the path the pipeline powershell looking was 'en' where instead it should 'en-us' folder name.

I'm not an expert in the powershell even the loop portion itself, but what I understand it seems the powershell loop cannot execute loop in the  array with variable name of dashline.

Looking forward any alternate or  updates of the shell script.

**Comment by ryanisgrig** [comment]
Hi @jiangsheng-msft,

Can you confirm the version of the VA solution you are running off of? We now use "xx-xx" for localization and it's possible that this was created off an older version, then updated scripts to the newer one.

**Comment by CurlyBytes** [comment]
Hi @ryanlengel ,

I did ask the help of a lot of developers in the community we update the code from appsettings.json and cognitivemodel.json from en to en-us and the dialogs

![MicrosoftTeams-image (22)](https://user-images.githubusercontent.com/55616292/73920148-cd830e80-48ff-11ea-95b6-c8ec1c8b2e9b.png)

so we update the code itself to this one and the methods
![MicrosoftTeams-image (23)](https://user-images.githubusercontent.com/55616292/73920661-ce687000-4900-11ea-9d59-d8e0ed5f621a.png)

and it is running now properly. By the way is there a transition documentation of version on each update in the bot?

**Comment by darrenj** [comment]
Transition documentation can be found here - feedback welcome.

![image](https://user-images.githubusercontent.com/33519520/73939971-76227580-48e2-11ea-8c5f-0641af003f02.png)

**Comment by CurlyBytes** [comment]
Okay thanks you may now close this ticket,

by theway when will be the final GA of skills and Virtual Assistant Template? thanks

**Comment by darrenj** [comment]
March!
