### ISSUE TITLE
MS team channel is not responding.

### ISSUE THREAD

**Issue by YammanureSreekanth** [microsoft/botframework-solutions#2912]
#### What project is affected?
MS Teams channel

#### What language is this in?
Typescript

#### What happens?
We are in new architecture (Virtual Assitant and Skills). Emulator, SMS and DirectLine are working fine. The first step in our project is Sign in. When we click on the Sign-in button, gives the sign-in prompt and after we submit the sign-in, MS Teams channel is not responding.
So, we presume the end of the conversation is not getting ended as expected.

#### What are the steps to reproduce this issue?
Create VA and Skill connection. And then access it from the MS teams channel.

#### What were you expecting to happen?
MS team channel should respond.

#### Can you share any logs, error output, etc.?
Not seeing any error logs.

#### Any screenshots or additional context?
We have also changed changes as per [this ticket](https://github.com/microsoft/botframework-solutions/issues/2722). Please go through this.
Also, tried to send the HandOff instead of End of conversation in error cases. But still the same.

Thanks,
Sreekanth from Ecolab

**Comment by YammanureSreekanth** [comment]
Any update on this.

**Comment by Batta32** [comment]
Hi @SreekanthOAuth! Sorry for the delay.

We will be replicating the issue and get back to you later 😊

**Comment by VictorGrycuk** [comment]
Hi @SreekanthOAuth,

This issue seems duplicated to the issue #2722.
As seeing that it was reopened and replied to, I suggest closing this one.

@lauren-mills do you agree?
