### ISSUE TITLE
Botskill connect is not working properly whether local dev or public hosted

### ISSUE THREAD

**Issue by CurlyBytes** [microsoft/botframework-solutions#2927]
#### What project is affected?
Virtual assistant importing skills in calendar (CLI commands of botskills connect) remoteManifest

#### What language is this in?
C# 

#### What happens?
Botskills connect didn't work as expected

#### What are the steps to reproduce this issue?
* Create project virtual assistant VA
* Create blank solution( i just copy your premade calendar skills and import in the blank solution)
* Build and compile the two projects
* find any tag in cognitve.json, manifest.json and the LU folder from *en* to *en-us* in the skills template
* i go to the root directory of VA and open Powershell V6
* i run this command 'botskills connect --remoteManifest "http://localhost:3980/api/skill/manifest" --cs '
then an error occurs
``` 
there was an error while connecting the Skill to the Assistant:
Error: An error ocurred while updating the Dispatch model:
Error: Path to the Email.lu file leads to a nonexistent file.
Make sure your Skill's .lu file's name matches your Skill's manifest id
```

#### What were you expecting to happen?
It should add the skills to my VA, update the dispatch in VA, update skills.json, etc

#### Any screenshots or additional context?
This is the error occur in the bot connect 
![image](https://user-images.githubusercontent.com/55616292/73283596-4f9f7300-422e-11ea-9eaa-c9c43af05013.png)

My local running skills
![image](https://user-images.githubusercontent.com/55616292/73283793-98572c00-422e-11ea-9427-811e861a4096.png)

The manifest.json of the skills
![image](https://user-images.githubusercontent.com/55616292/73283856-ae64ec80-422e-11ea-8517-5c7c39d9df27.png)

so as you can see the id is the same in the .lu in calendar skills. here is the attached screenshot( i just replace the appid and tokens in this screenshot to xxx for security purpose :D )
![image](https://user-images.githubusercontent.com/55616292/73284149-187d9180-422f-11ea-9cb2-44d15398b9a8.png)

this is my VA directory
![image](https://user-images.githubusercontent.com/55616292/73284292-4fec3e00-422f-11ea-911f-2de21b143456.png)

i even tried to add folder name *Skills* in the VA but still not working

i checked blog and VLog, this is what i found in your msignite 2019
https://www.youtube.com/watch?v=u7Gql-ClcVA
i see there is a script using (she is not using botconnnect)

any advice will do

thanks a lot

**Comment by Batta32** [comment]
Hi @cocoytech, thanks for reporting the issue!

> Error: Path to the Email.lu file leads to a nonexistent file.

Can you check if you have any [utteranceSources](https://github.com/microsoft/botframework-solutions/blob/master/skills/csharp/calendarskill/manifestTemplate.json#L58) with the `Email` source in your `manifest.json`?

The tool is trying to access to the `Email.lu` of the LU folder (where you have the `Calendar.lu` and `General.lu`) and it's failing because it doesn't exist.

The tool reads each `utteranceSource` which contains the `<LU_FILENAME>#<INTENT>` structure as `source` property from the manifest.

I recommend to always execute the tool with the `--verbose` argument so you can check the steps that is executing the tool.

Hope this helps to you 😊!

**Comment by CurlyBytes** [comment]
Yes i have UtteranceSources on my manifest.json

here is the entire 
``` json
{
  "id": "calendar",
  "name": "Calendar Skill",
  "description": "The Calendar skill provides calendaring related capabilities and supports Office and Google calendars.",
  "iconUrl": "calendarSkill.png",
  "authenticationConnections": [
    {
      "id": "Outlook",
      "serviceProviderId": "Azure Active Directory v2",
      "scopes": "Calendars.ReadWrite, People.Read, Contacts.Read, User.Read.All"
    },
    {
      "id": "Google",
      "serviceProviderId": "Google",
      "scopes": "https://www.googleapis.com/auth/calendar, https://www.googleapis.com/auth/contacts"
    }
  ],
  "actions": [
    {
      "id": "calendarskill_createEvent",
      "definition": {
        "description": "Create a new event",
        "slots": [
          {
            "name": "title",
            "types": [ "string" ]
          },
          {
            "name": "content",
            "types": [ "string" ]
          },
          {
            "name": "attendees",
            "types": [ "string" ]
          },
          {
            "name": "startdate",
            "types": [ "string" ]
          },
          {
            "name": "starttime",
            "types": [ "string" ]
          },
          {
            "name": "duration",
            "types": [ "string" ]
          },
					{
						"name": "location",
						"types": [ "string" ]
					},
					{
						"name": "timezone",
						"types": [ "string" ]
					}
        ],
        "triggers": {
          "utteranceSources": [
            {
              "locale": "en-us",
              "source": [
                "Calendar#CreateCalendarEntry",
                "Calendar#FindMeetingRoom"
              ]
            }
          ]
        }
      }
    },
    {
      "id": "calendar_changeEventStatus",
      "definition": {
        "description": "Change the status of an event (accept/decline).",
				"slots": [
					{
						"name": "startdate",
						"types": [ "string" ]
					},
					{
						"name": "starttime",
						"types": [ "string" ]
					},
					{
						"name": "timezone",
						"types": [ "string" ]
					}
				],
        "triggers": {
          "utteranceSources": [
            {
              "locale": "en-us",
              "source": [
                "Calendar#AcceptEventEntry",
                "Calendar#DeleteCalendarEntry"
              ]
            }
          ]
        }
      }
    },
    {
      "id": "calendar_joinEvent",
      "definition": {
        "description": "Join the upcoming meeting",
				"slots": [
					{
						"name": "timezone",
						"types": [ "string" ]
					}
				],
        "triggers": {
          "utteranceSources": [
            {
              "locale": "en-us",
              "source": [
                "Calendar#ConnectToMeeting"
              ]
            }
          ]
        }
      }
    },
    {
      "id": "calendar_summary",
      "definition": {
        "description": "Retrieve a summary of meetings through an event invocation.",
				"slots": [
					{
						"name": "timezone",
						"types": [ "string" ]
					}
				],
        "triggers": {
          "events": [
            {
              "Name": "summaryEvent"
            }
          ]
        }
      }
    },
    {
      "id": "calendar_timeRemaining",
      "definition": {
        "description": "Find out how long until the next event",
				"slots": [
					{
						"name": "timezone",
						"types": [ "string" ]
					}
				],
        "triggers": {
          "utteranceSources": [
            {
              "locale": "en-us",
              "source": [
                "Calendar#TimeRemaining"
              ]
            }
          ]
        }
      }
    },
    {
      "id": "calendar_summary",
      "definition": {
        "description": "Find an upcoming event",
				"slots": [
					{
						"name": "startdate",
						"types": [ "string" ]
					},
					{
						"name": "starttime",
						"types": [ "string" ]
					},
					{
						"name": "enddate",
						"types": [ "string" ]
					},
					{
						"name": "endtime",
						"types": [ "string" ]
					},
					{
						"name": "timezone",
						"types": [ "string" ]
					}
				],
        "triggers": {
          "utteranceSources": [
            {
              "locale": "en-us",
              "source": [
                "Calendar#FindCalendarDetail",
                "Calendar#FindCalendarEntry",
                "Calendar#FindCalendarWhen",
                "Calendar#FindCalendarWhere",
                "Calendar#FindCalendarWho",
                "Calendar#FindDuration"
              ]
            }
          ]
        }
      }
    },
    {
      "id": "calendar_updateEvent",
      "definition": {
        "description": "Update an existing event.",
				"slots": [
					{
						"name": "startdate",
						"types": [ "string" ]
					},
					{
						"name": "starttime",
						"types": [ "string" ]
					},
					{
						"name": "enddate",
						"types": [ "string" ]
					},
					{
						"name": "endtime",
						"types": [ "string" ]
					},
					{
						"name": "newstartdate",
						"types": [ "string" ]
					},
					{
						"name": "newstarttime",
						"types": [ "string" ]
					},
					{
						"name": "timezone",
						"types": [ "string" ]
					}
				],
        "triggers": {
          "utteranceSources": [
            {
              "locale": "en-us",
              "source": [
                "Calendar#ChangeCalendarEntry"
              ]
            }
          ]
        }
      }
    }
  ]
}
```

i added the *--verbose* in the script, still the same

![image](https://user-images.githubusercontent.com/55616292/73322248-72a64300-427f-11ea-829e-2b41075143d8.png)

**Comment by Batta32** [comment]
Thanks @cocoytech. Comparing the screenshots you sent, we noticed that you have the Email Skill running but with the manifest of the Calendar Skill. Can you check if the manifest corresponds to the right skill?

I **successfully** replicated your scenario connecting a [C#] Virtual Assistant to a [C#] Calendar Skill.

### Context
* [[C#] Virtual Assistant Sample](https://github.com/microsoft/botframework-solutions/tree/master/templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample) of master branch
* [[C#] Calendar Skill](https://github.com/microsoft/botframework-solutions/tree/master/skills/csharp/calendarskill) of master branch
* Deploy the Virtual Assistant and Skill with the following command in a terminal being in the root folder of them:
> pwsh.exe -File Deployment\Scripts\deploy.ps1 -name "<BOT_NAME>" -location "<LOCATION>" -appId "<APP_ID>" -appPassword "<APP_PASSWORD>" -luisAuthoringKey "<LUIS_AUTHORING_KEY>" -luisAuthoringRegion "<LUIS_AUTHORING_REGION>"
* [botskills@1.0.10](https://www.npmjs.com/package/botskills/v/1.0.10)
> npm install -g botskills@latest

### Connection Steps
1. Open and run the Calendar Skills' solution (getting http://localhost:3980 endpoint)
1. Connect the Calendar Skill to the Virtual Assistant being in the Virtual Assistant's root folder
> botskills connect --remoteManifest "http://localhost:3980/api/skill/manifest" --luisFolder "<PATH_TO_CALENDARSKILL_LU_FOLDER>" --cs --verbose --languages "en-us"
1. Check that the connection finished successfully

For further information, please read the following documents:
* [Connect Skill to a Virtual Assistant](https://microsoft.github.io/botframework-solutions/skills/tutorials/add-prebuilt-skill/4-connect-skill/)
* Botskills [Connect](https://github.com/microsoft/botframework-solutions/blob/master/tools/botskills/docs/commands/connect.md) command

Please, feel free to compare both contexts and follow the connection steps mentioned above 😊.

### Additional Context
_Folder's structure of Calendar Skill and Virtual Assistant Sample_
![image](https://user-images.githubusercontent.com/11904023/73362892-712c4900-4286-11ea-93e0-1a529dbfc0bd.png)

_Calendar Skill running_
![image](https://user-images.githubusercontent.com/11904023/73362915-7ab5b100-4286-11ea-8582-57b54024c776.png)

_Manifest of the Calendar Skill which contains the Calendar LUIS file (with CreateCalendarEntry and FindMeetingRoom intents) in the utteranceSources property_
![image](https://user-images.githubusercontent.com/11904023/73362932-830dec00-4286-11ea-8416-a42eee297290.png)

_Connection of the Calendar Skill and the Virtual Assistant Sample_
![image](https://user-images.githubusercontent.com/11904023/73362951-8acd9080-4286-11ea-9dc7-45b0bd40473f.png)

**Comment by CurlyBytes** [comment]
As you can see, luis gen is already install
![image](https://user-images.githubusercontent.com/55616292/73406077-86f64880-4330-11ea-84b0-4261268dab0d.png)


But this error display
![image](https://user-images.githubusercontent.com/55616292/73408099-0b979580-4336-11ea-8885-c6a9e70f7891.png)


when i try to install luisgen this error happen
![image](https://user-images.githubusercontent.com/55616292/73408606-b6f51a00-4337-11ea-8153-759448b04502.png)


it seems that i already install luisgen, but when i try luisgen -v it state an error
![image](https://user-images.githubusercontent.com/55616292/73408649-dc822380-4337-11ea-8ddd-b30b1d57bc5c.png)


i try both localManifest and remoteManifest still no luck

**Comment by Batta32** [comment]
@cocoytech, this appears to be an issue related to the `luisgen` installation as it's a `dotnet` tool following the [README](https://www.npmjs.com/package/luisgen).

Can you confirm if you have the following `Enviroments Variables`? If don't, can you add them and try again to execute `luisgen -v`?

Also, you can check if you have  the luisgen correctly installed in `C:\Users\<YOUR_USER>\.dotnet\tools`.

![image](https://user-images.githubusercontent.com/11904023/73411391-f4c85300-42e3-11ea-8999-4dc885407e37.png)

![image](https://user-images.githubusercontent.com/11904023/73411399-fa259d80-42e3-11ea-8019-34ea357ba3d8.png)

**Comment by CurlyBytes** [comment]
This is what happen on luisgen -v , it gives me error
![image](https://user-images.githubusercontent.com/55616292/73416485-faf41900-434f-11ea-9971-863b9f13e291.png)


upon checking the directory, i have already install
![image](https://user-images.githubusercontent.com/55616292/73416581-30006b80-4350-11ea-9c76-318ad0a81337.png)

This is the environment variables, it is already installed too
![image](https://user-images.githubusercontent.com/55616292/73416680-a7ce9600-4350-11ea-8be9-763fe9997a49.png)

**Comment by CurlyBytes** [comment]
i even retried to re install this npm  *npm i bot-cli -g* and  *npm i -g chatdown msbot ludown luis-apis qnamaker botdispatch luisgen*
![image](https://user-images.githubusercontent.com/55616292/73418600-1f9fbf00-4357-11ea-8711-5c4f7b552040.png)

**Comment by CurlyBytes** [comment]
I even tried npm install luisgen -global

![image](https://user-images.githubusercontent.com/55616292/73441563-25fd5d80-438e-11ea-82c1-87d77d06cd26.png)



it says that i have already install,
i try *luisgen -v* in powershell but having an error
![image](https://user-images.githubusercontent.com/55616292/73441753-74aaf780-438e-11ea-9fe5-75a6ea2d0ad9.png)

But i notice something, when im inside in the folder of luisgen.exe, the *luisgen -v* works perfectly based on the suggestion upon running inside the luisgen folder
![image](https://user-images.githubusercontent.com/55616292/73443028-df5d3280-4390-11ea-8341-3446a0d47390.png)
As you can see when i attempt to do *luisgen -v* it still gives me an error, but when i follow the suggestion by *.\luisgen -v*  it can clearly give the result version of the luisgen


so i made a stupid *hack* in the cli stuffs and dll. i copy all the folder name * tools* (the folder name store and luisgen.exe) and its corresponding files and documents insdie the root folder of VA and it works perfectly to any skills

![image](https://user-images.githubusercontent.com/55616292/73443415-8f32a000-4391-11ea-8a80-988f1f797594.png)


i believe this issue is related to CLI or powershell, same story from this ticket https://github.com/microsoft/botframework-solutions/issues/2075
![image](https://user-images.githubusercontent.com/55616292/73443489-b5f0d680-4391-11ea-9341-f821a770a23c.png)
but on this case instead mac os, the issue is on windows 10 pro build 18362

**Comment by darrenj** [comment]
@cocoytech With the move of luisgen into the bf-cli (and thus not a .net tool) this should get resolved. As per the known issue (albeit this time on Windows) can you try adding the path `users/YOUR_USER_NAME/.dotnet/tools` to your path (e.g. PATH=%PATH%;<ToolsPath>) and see if that helps? Best do that within a powershell instance.

**Comment by CurlyBytes** [comment]
Okay i repro on my end and follow the updates but still there are new errors arise

![image](https://user-images.githubusercontent.com/55616292/74448962-ce471200-4eb6-11ea-891f-f7e0ec454833.png)

i already have manifest on the upload
![image](https://user-images.githubusercontent.com/55616292/74449041-ecad0d80-4eb6-11ea-8f8d-435adaadcba7.png)

**Comment by CurlyBytes** [comment]
just an update

still the error is still persistent, i need to do the hacking stuff even i already npm install npm install -g @microsoft/botframework-cli

![image](https://user-images.githubusercontent.com/55616292/74451246-4a8f2480-4eba-11ea-945e-1af8a08b5432.png)

please advise

**Comment by dfavretto** [comment]
Hi @cocoytech, what version of Botskills are you using? I think the error you are facing may be due to an update for using the new Skill Manifests, which requires the latest version of Botskills ([v1.0.12](https://www.npmjs.com/package/botskills/v/1.0.12))

**Comment by CurlyBytes** [comment]
Yes i am using the latest version of the bot skills, still the error occurs

![image](https://user-images.githubusercontent.com/55616292/74661958-f5158900-51d3-11ea-92f4-9ff9eac9f4f1.png)

**Comment by darrenj** [comment]
Ahh - make sure you have a more recent clone of the repo. Then the manifest should be manifest-1.1.json not manifest.json which was removed to reduce confusion.  Then as per the docs need to update manifest-1.1.json with endpoint and appid of your deployment.

**Comment by CurlyBytes** [comment]
As per advise, i tried using the manifest-1.1 but still no luck

without the **hacky** stuff in luisgen inside the root folder of Virtual Assistant, Botskills connect will not work as expected

**Comment by darrenj** [comment]
This seems to be all back to the issue around dotnet tools on some machines, previously just macs. Ahead of running botskills does the following help at all? Assuming that this added path has luisgen in it of course (installing via npm install -g is needed)

PATH=%PATH%;c:\users\YOUR_USER\\.dotnet\tools

**Comment by CurlyBytes** [comment]
i already did npm install on global in , if you check the previous reply https://github.com/microsoft/botframework-solutions/issues/2927#issuecomment-580198453

its already install globally and the path is also correct https://github.com/microsoft/botframework-solutions/issues/2927#issuecomment-580063421

For alternate workaround, i just simply copy the luisgen.exe and .store file inside to my VA
![image](https://user-images.githubusercontent.com/55616292/74835121-aabd1500-5357-11ea-95f3-978559381a9b.png)
just to let botskills work

**Comment by darrenj** [comment]
@Batta32 - can we review how luisgen is invoked by botskills and see if there are any additional options, feels like the system path is being ignored in this situation?

**Comment by darrenj** [comment]
We are tracking an update to botskills which will move to the BF CLI which incorporates luisgen functionality but through a javascript module not a .net tool which should remove this issue moving forward.

**Comment by CurlyBytes** [comment]
So also the documentation(website github docs) steps in installation of VA should be updated too? thanks

**Comment by Batta32** [comment]
Yes @cocoytech! We will move to the BF CLI (as Darren mentioned) updating the documentation of Botskills 😊.

**Comment by darrenj** [comment]
We'll work on the bf cli changes which should address this .net tool path problem on osx (sometimes) and now Windows it seems
