### ISSUE TITLE
Email skill in VA fails to show email details

### ISSUE THREAD

**Issue by emivers8** [microsoft/botframework-solutions#2930]
#### What happens?

![image](https://user-images.githubusercontent.com/55601267/73310163-8ea2d980-41d8-11ea-8479-8ea7072a6a11.png)

#### What are the steps to reproduce this issue?

1. Run VA in test environment (Emulator)
2. Request to "check email", sign in
3. When asked "Do you want more detail about the first email?" respond "yes"
4. Bot says "Apologies, it looks like something went wrong. Try your request again later."

#### Can you share any logs, error output, etc.?

Logs seem to indicate it's interpreting "yes" as a call to the ToDo skill. Similar to other cases where LU is confused by more generic utterances?

![image](https://user-images.githubusercontent.com/55601267/73310327-f0fbda00-41d8-11ea-9eb6-cefa47554931.png)
![image](https://user-images.githubusercontent.com/55601267/73310753-c3636080-41d9-11ea-9526-4364124a07ae.png)
![image](https://user-images.githubusercontent.com/55601267/73310715-b5154480-41d9-11ea-849c-7d5030a9e946.png)

**Comment by lauren-mills** [comment]
Looks like the DispatchLuis.cs file in the project does not have all the intents that the actual dispatch model is trained to handle. So it gets the ToDoSkill intent (Probably in the interruption logic) but then it can't parse it into a result.

**Comment by darrenj** [comment]
@KayMKM any thoughts?
