### ISSUE TITLE
Virtual Assitant Template - Feedback Middleware[Docs]

### ISSUE THREAD

**Issue by brian-smith-ksd** [microsoft/botframework-solutions#2932]
**Please describe your request**
The feedback middleware documentation for the Virtual Assistant template is missing some components, or not presented in a way that I am understanding how to implement it.

I do not know where to include the following line in my code:

FeedbackMiddleware.RequestFeedbackAsync(turnContext, "your-tag")

There are very few locations within the template that use this type of dialog context, and I tried implementing it at all of those locations.

**Is this an issue with current documentation? If yes, please provide the link.**

https://microsoft.github.io/botframework-solutions/virtual-assistant/handbook/feedback/

**Comment by lauren-mills** [comment]
Hi @brian-smith-ksd, you can use this line of code anywhere you would like to request feedback. For instance, you could add it in to the final step of a waterfall dialog or in the MainDialog.CompleteAsync method.

The "turnContext" can also be found at dialogContext.Context, dc.Context, innerDc.Context, stepContext.Context, etc.

We will take an action to update the docs to reflect this.

**Comment by brian-smith-ksd** [comment]
Are you referring to the Enterprise Assistant template or the Virtual Assistant template? I am using the Virtual Assistant template that you can start through Visual Studio. I do not see a MainDialog.CompleteAsync method in the VA template that I am using, and the built-in waterfall dialog is limited. I know in the Enterprise Assistant all of these exist, but it seemed to be a work-in-progress the last time I downloaded it. I know a lot of this stuff is in preview, and the whole MS chatbot seems to be in a transition stage with the move from framework 3 to framework 4. 

Is there an easy way to add it to the VA template, or should I move to the Enterprise template?

**Comment by brian-smith-ksd** [comment]
I apologize if this is all due to my limited understanding of the bot framework

**Comment by brian-smith-ksd** [comment]
Thank you, Lauren! I was able to get the feedback working fairly well after you provided me with this information (using VA template 0.7). I am now having issues getting the same feedback to work in the latest Virtual Assistant template -- version 0.8. Any thoughts? 
I know that the feedback documentation has not been updated in several months, and VA template 0.8 seems to change a lot of the code surrounding how interactions are implemented (QnA specifically). If I just wanted to implement feedback for every QnA -- q_Faq knowledge base response, how would I do that?
