### ISSUE TITLE
Skills show 0 input 0 output in Power Virtual Agent

### ISSUE THREAD

**Issue by arafattehsin** [microsoft/botframework-solutions#2933]
Hello Team! 

I am having an issue in connecting my skills with PVA.

#### What project is affected?
Power Virtual Agent / Skills

#### What language is this in?
C#

#### What happens?
I used this document to create a skill (https://docs.microsoft.com/en-us/azure/bot-service/skill-implement-skill?view=azure-bot-service-4.0&tabs=cs) and it works very well between v4.7 Bot and Skill. However, when the same manifest gets connected with PVA, it gives 0 input 0 output. 

#### What are the steps to reproduce this issue?
Yes, keep the same manifest and you will know. 

#### What were you expecting to happen?
I was expecting to give me n input, n output as I did not define any output or input. Even though I tried to modify my manifest as this and defined definitions in that, then it gave me an error that manifest is wrong.

![image](https://user-images.githubusercontent.com/16351038/73400529-6e405f80-433d-11ea-8edc-5b7229d5aefc.png)

#### Can you share any logs, error output, etc.?

 **Valid Manifest without definitions** 

{
  "$schema": "https://schemas.botframework.com/schemas/skills/skill-manifest-2.0.0.json",
  "$id": "AMABankSkill",
  "name": "AMA Bank Skill bot",
  "version": "1.0",
  "description": "This skill extends the banking operations to facilitate the customer",
  "publisherName": "Arafat Tehsin",
  "privacyUrl": "https://www.arafattehsin.com/blog",
  "copyright": "Copyright (c) Arafat Tehsin. All rights reserved.",
  "license": "",
  "iconUrl": "https://www.arafattehsin.com/wp-content/uploads/2018/09/logo.png",
  "tags": [
    "arafat tehsin",
    "amabank",
    "bank"
  ],
  "endpoints": [
    {
      "name": "default",
      "protocol": "BotFrameworkV3",
      "description": "Default endpoint for the skill",
      "endpointUrl": "https://c2580f5b.ngrok.io/api/messages",
      "msAppId": "<app Id>"
    }
  ],
  "activities": {
    "message": {
      "type": "message",
      "description": "Receives the user's' utterance and attempts to resolve it using the skill's LU models"
    }
  },
  "definitions": {
    "localeValue": {
      "type": "object",
      "properties": {
        "locale": {
          "type": "string",
          "description": "The current user's locale ISO code"
        }
      }
    }
  }
}

Returns me this when I connect:

![image](https://user-images.githubusercontent.com/16351038/73399745-e574f400-433b-11ea-958c-21b4f2b90d16.png)

#### Any screenshots or additional context?

However, when I try to add definitions based upon this: https://github.com/microsoft/botframework-sdk/blob/master/schemas/skills/samples/complex-skillmanifest-2.0.0.json - I get an error:

![image](https://user-images.githubusercontent.com/16351038/73400393-21f51f80-433d-11ea-9e4f-cea4ef5544f9.png)

Is it a correct place where I reported this issue? If not then kindly let me know where should I report this. 

Thank you!

**Comment by lzc850612** [comment]
This seems like a PVA issue. I'm contacting someone from the PVA team to help you with this.

**Comment by lzc850612** [comment]
Please open a ticket in here: https://powerusers.microsoft.com/t5/Power-Virtual-Agents-Forum/bd-p/10292019 

Closing this issue now.

**Comment by darrenj** [comment]
AppId is empty in the manifest - this should be populated with the AppId of your Skill?

**Comment by arafattehsin** [comment]
Hi @darrenj - no, I removed the AppID before posting it here but the problem was something else which @sbacha helped me fix it. All good now, it works like a charm!
