### ISSUE TITLE
I'm getting following error upon executing Deploy.ps1

### ISSUE THREAD

**Issue by gagankohli2000** [microsoft/botframework-solutions#2948]
I'm getting following error upon executing Deploy.ps1
![boterror](https://user-images.githubusercontent.com/14933211/73511879-741c6a80-443b-11ea-8f59-9bd567b250a2.png)

**Comment by darrenj** [comment]
I'll let support team engage but wanted to double check you had all of the pre-requisite CLI tools installed?

`npm install -g @microsoft/botframework-cli botdispatch luis-apis`

**Comment by csnarain** [comment]
Facing the same issue with LUIS deployment

**Comment by darrenj** [comment]
To help diagnose further - can you advise on whether you specified a LUIS authoring key or let the script create an authoring resource for you?

**Comment by csnarain** [comment]
> 
> 
> To help diagnose further - can you advise on whether you specified a LUIS authoring key or let the script create an authoring resource for you?

I provided an authoring key

**Comment by darrenj** [comment]
Looking at the script there might be a problem with your `botframework-cli` installation, to help validate, can you run this from within the root folder of your assistant within a powershell window?

```
 bf luis:convert --name test --in deployment\resources\lu\en-us\general.lu --culture en-us --out test.json
```

**Comment by csnarain** [comment]
@darrenj  - Thanks for offering to help. I reinstalled botframework-cli npm packages and it solved the problem for me.

**Comment by darrenj** [comment]
Thanks for letting us know! @gagankohli2000 - can you confirm if the above helps you too?

**Comment by gagankohli2000** [comment]
@darrenj - My issue got resolved after changing location from Australiaeast to $location="westus2", and $luisAuthoringRegion="westus". See if you are able to reproduce issue.

**Comment by darrenj** [comment]
It looks like you perhaps had some CLI installation issues - glad you resolved it. I've just validate australiaeast deployment

![image](https://user-images.githubusercontent.com/33519520/73939153-b8e34e00-48e0-11ea-86dd-7fdca0a78699.png)

Depending on how long ago you created your project it may also be worth ensuring you have the latest deployment script updates as per `How do I update my local deployment scripts with the latest?` in [this document](https://microsoft.github.io/botframework-solutions/virtual-assistant/handbook/deployment-scripts/)
