### ISSUE TITLE
[Template] simplify code

### ISSUE THREAD

**Issue by xieofxie** [microsoft/botframework-solutions#2969]
## User Story
As ... anyone
I want ... to simplified code
so that ... it is easy to maintain

## Acceptance Criteria 
*List your requirements.*
- [ ] ...  share code in OnBeginDialogAsync and OnContinueDialogAsync
- [ ] ...
- [ ] ...

## Resources
*Provide any screenshots or conversation mockups to support your request.*
*Learn how to mock up bot conversations with [.chat files](http://aka.ms/bfchatfile).*

## Notes
*Provide any additional information.*

**Comment by lauren-mills** [comment]
Hi, we are aware of the duplicate code and made a decision to leave it this way due to some complexities in the Begin/Continue methods around the waterfall dialog. We do not want to overwork the template beyond the default structures of the SDK.
