### ISSUE TITLE
[Docs]Request Feedback code snippet not working with .8 release

### ISSUE THREAD

**Issue by pavolum** [microsoft/botframework-solutions#2979]
/virtual-assistant/handbook/feedback/

The following code snippet provided in the doc for requesting feedback:

FeedbackMiddleware.RequestFeedbackAsync(turnContext, "your-tag") 

will not work with the new waterfall mainDialog.cs as it puts the VA in a strange state in which it is expecting the next waterfall response while simultaneously requesting feedback and expecting a feedback response.

This may be more then a docs issue in that feedbackMiddleware may need to be redesigned (potentially to a dialog) to fit with the new waterfall model

**Comment by pavolum** [comment]
Developing spec now for the new feedback mechanism

**Comment by jiruss** [comment]
Do you guys have any update on this? I am running into this as well as others. [https://github.com/microsoft/botframework-solutions/issues/2932](url)

**Comment by pavolum** [comment]
@jiruss we are working on a more robust feedback mechanism in the long term. In the meantime I have created a short term solution that is in PR now. It should be in the next branch shortly.
https://github.com/microsoft/botframework-solutions/pull/3242
