### ISSUE TITLE
[POI][VA] 'Start' is captured by 'Start Over'

### ISSUE THREAD

**Issue by xieofxie** [microsoft/botframework-solutions#2982]
#### What project is affected?
POI, VA
#### What language is this in?
C#
#### What happens?
'Start' in POI is captured by 'Start Over' in VA
#### What are the steps to reproduce this issue?
1. connect POI in VA
2. find some poi until it shows 'Start' and click
![image](https://user-images.githubusercontent.com/2876650/73804287-40a45c00-47fe-11ea-87de-4a889ec5cc75.png)

3. captured by VA's 'Start Over' interruption
#### Any screenshots or additional context?
One of these?
- Use 'Start navigation' instead of 'Start'
- Add start to None in General

**Comment by xieofxie** [comment]
@ryanlengel what do you think? I prefer the first option. Thanks

**Comment by ryanisgrig** [comment]
I prefer the first option as well. Is this a regression or result of the new Skill & dialog handling that was implemented in the last release?

**Comment by lauren-mills** [comment]
I think both of these changes should be implemented. Adding start to the None intent is good since it shouldn't map to any of the other intents.

**Comment by xieofxie** [comment]
@ryanlengel  I am afraid this bug exists after the start over feature is added to VA.

I have created a pr, should I merge against master or next? Thanks
