### ISSUE TITLE
LUIS giving InternalServerError when transferred from root Bot to skill bot

### ISSUE THREAD

**Issue by rutujlangalia** [microsoft/botframework-solutions#2986]
I am trying to implement ToDo Skill and for that I have one Root Bot from which I am calling Skill bot, but when I am trying to get data from luis using RecognizeAsync method, I am getting InternalServerError.

**Comment by darrenj** [comment]
Can you help try a few things?

- Connect to the Skill directly using Bot Framework Emulator using the AppId/Password for the Skill and validate LUIS works as you would expect
- Connect to the Root Bot (Is this Virtual Assistant or your own Bot?) and validate other LUIS based scenarios work - if it's VA the on-boarding flow will help validate this.
- Share the full exception and any appropriate logs from AppInsights 

Thanks

**Comment by rutujlangalia** [comment]
Hi @darrenj ,

as you suggested please check observations below:
- I connected Skill directly to Bot Framework Emulator and LUIS works exactly fine in that case.

- Root bot is not a virtual assistant, its a v4 Bot. As I checked root bot is working as expected(LUIS based scenarios work).

- Skill was using .NetCore 3.0 and Root bot was using .NetCore 2.1 so i tried making both versions equal but still error exists.

Please check attached file for the exact exception I am getting. Let me know in case you need more info.

Thanks.
[SkillLUISException.txt](https://github.com/microsoft/botframework-solutions/files/4169243/SkillLUISException.txt)
[RootBotException.txt](https://github.com/microsoft/botframework-solutions/files/4169244/RootBotException.txt)

**Comment by darrenj** [comment]
That's great - thank you. I strongly suspect the issue your relating to is covered [here](https://microsoft.github.io/botframework-solutions/help/known-issues/#http-500-error-when-invoking-a-skill). Can you take a look and verify the configuration you have please? 

If for example your Root Bot is on `http://localhost:3978` then `SkillHostEndpoint` will likely need to be set to `http://localhost:3978/api/skills`

**Comment by rutujlangalia** [comment]
Configurations is correct because I am able to transfer control from RootBot to SkillBot.

The issue is LUIS call fails in the image attached in **step 3**, which transfers control to DefaultAdapter.

To reproduce the issue you can follow below steps:
(1) Create a simple Echo bot which will be RootBot which is capable to transfer control to ToDo skill.
(2) Change configuration in **ToDoSkill** bot in **botframework-solutions-master** and run the solution.
![Botframework-solution-master](https://user-images.githubusercontent.com/32361772/74022177-fc15ed80-49c2-11ea-95f8-b979fb7bb687.png)

(3) Put a debugger in **OnInterruptDialogAsync** method.
![OnInterruptDialog](https://user-images.githubusercontent.com/32361772/74021826-55c9e800-49c2-11ea-9027-ed4a3e23b70f.png)

If you follow above steps you'll be getting the error I am getting.
Thanks for the help.

**Comment by darrenj** [comment]
OK - TheSkillException file didn''t make it clear it was a LUIS error. Given the ToDo skill works on it's own  through the emulator there should be no difference when invoking via a Skill. I cannot repro this with a VA base bot.

Can you inspect the `dc.Context.Activity` and check the properties are what you expect (e.g. from.id, Text, etc.?)

**Comment by rutujlangalia** [comment]
Hi @darrenj ,

I checked dc.Context.Activity and the issue is SkillBot is not able to execute '**context.SendActivityAsync**'. While debugging SendActivityAsync gives an issue. Not sure why.

Please check below attached HttpRequest content in below text file.
[HttpRequest_SkillBot.txt](https://github.com/microsoft/botframework-solutions/files/4180108/HttpRequest_SkillBot.txt)

**AbsoluteUri** : http://localhost:3978/api/skills/v3/conversations/emulator%3A5e604cd1-4bd8-11ea-bc55-b1defd7deb93%7Clivechat/activities/32d30770-4beb-11ea-b170-b5fb34ab2cf5

Any suggestions?

**Comment by rutujlangalia** [comment]
Hi @darrenj ,

Any suggestion?

I tried updating all the packages but still InternalServerError exists.

**Comment by darrenj** [comment]
So, the problem appears to lie in the connection from the Skill back to your Bot. Whilst the Bot is talking back to the Skill - it's the reverse connection from Skill to Bot that is causing the issue.

Based on the above it looks like your Parent bot is on localhost:3978 and I'm assuming your Skill is on a different port (e.g. localhost:3980). Given your not using the VA template have you configured the /api/skills route on your root bot? As per [this](https://docs.microsoft.com/en-us/azure/bot-service/skill-implement-consumer?view=azure-bot-service-4.0&tabs=cs#skills-endpoint)

**Comment by rutujlangalia** [comment]
Yes I have configured a skill controller as you mentioned.. but do we need to add any routing to let RootBot understand about the Skill controller?

I guess it's not able to call SkillController back from SkillBot?

Am I missing something?

**Comment by rutujlangalia** [comment]
@darrenj ,

I found the issue..
The issue was with BotFrameworkHttpAdapter.

Thanks for the help.

**Comment by darrenj** [comment]
No problem! Glad you got it working
