### ISSUE TITLE
[Microsoft.bot.solutions]Convert authentication responses to .lg

### ISSUE THREAD

**Issue by pavolum** [microsoft/botframework-solutions#2990]
The responses used for authentication flows in Microsoft.bot.solutions are still running on the .tt method and should be converted to use the .lg method

**Comment by xieofxie** [comment]
Could be converted after #3047

**Comment by xieofxie** [comment]
This is on going now https://github.com/microsoft/botbuilder-dotnet/pull/3752
Once MultiLanguageLG supports passed in parsed Template, we could compile lg files in assembly and when running, read them and then convert them to Templates for use

**Comment by darrenj** [comment]
@pavolum @xieofxie @lzc850612 With this merged in, are we unblocked for this change to go in?

**Comment by peterinnesmsft** [comment]
Moving this to internal backlog for further tracking.
