### ISSUE TITLE
(Contacts) Find A Contact and Take Action

### ISSUE THREAD

**Issue by Dewain27** [microsoft/botframework-solutions#30]
There currently is no skill that will allow a user to find a contact and take action on that Contact.

We would need to add this with the following utterance support:
Find "Contact Name"
Call "Contact Name"
Call "Contact Name" on "Mobile / Home / Cell / Work"
Email "Contact Name" (May already be a function of Email)

**Comment by darrenj** [comment]
tracked with #929
