### ISSUE TITLE
Misplaced Microsoft App Id on deployment

### ISSUE THREAD

**Issue by ivlaevski** [microsoft/botframework-solutions#300]
**Project**
Enterprise Bot Template

**Description**
Infrastructure deployment process is storing wrong Microsoft App Id.

**To Reproduce**
After creating a new project with the Enterprise Bot Template start following the deployment steps.
The default command:
`msbot clone services --name "Angelique" --luisAuthoringKey "..." --folder "DeploymentScripts\msbotClone" --location "westus"`
returns an error for me. So, I use the workaround steps and I create an MS Applicaiton at https://apps.dev.microsoft.com/ first.
Remark: There I can see 'Live SDK application' and 'Converged applications' 
`msbot clone services --name "Angelique" --luisAuthoringKey "..." --folder "DeploymentScripts\msbotClone" --location "westus" --appId "1c147b6e-..." --appSecret "qmn.."`
This way the deployment is completed and a new .bot file is created.
`msbot list --bot Angelique.bot --secret "M14p3s..."`
Decrypts the .bot file and reveals the values. Where you can see the appId is different.
Also in Azure the Web App Bot Settings are showing wrong app Id:
![48444671-40551680-e79d-11e8-9731-41856dea6bb5](https://user-images.githubusercontent.com/3420183/48446987-6c739600-e7a3-11e8-940e-615341ba4ca4.png)
Clicking the 'Manage' link is redirecting to a page with label 'The application was not found'

**Expected behavior**
When using the `--appId` attribute I expect to have that App Id into the .bot file and all corresponding places in Azure deployed infrastructure.

**Additional context**
I searched the AppId in my files, notes and in Azure - nowhere to find a match.

**Comment by lauren-mills** [comment]
@ivlaevski after you ran the msbot clone command the first time, did you run this command?

![image](https://user-images.githubusercontent.com/27976702/48510530-f6a21580-e808-11e8-990b-34437d1e8131.png)

It's possible your bot service was already created with the first appId before you got the error.

**Comment by ivlaevski** [comment]
I did. I waited group to disapear from Azure list before continuing.

Several times I tried to reproduce the issue with different names... Didn't hapaned for second time.

But I found the length of the name is issue (if it's to short the script is crashing befor the end)

**Comment by lauren-mills** [comment]
I will raise this on the botbuilder-tools repo since it's hard to repro on our end. Maybe they have seen it before as well.

**Comment by lauren-mills** [comment]
Closing so conversation can continue in tools repo.
