### ISSUE TITLE
repeated repeat repeats too many messages

### ISSUE THREAD

**Issue by turbozapekanka** [microsoft/botframework-solutions#3003]
#### What project is affected?
Virtual Assistant

#### What language is this in?
C#

#### What happens?
repeats too much

#### What are the steps to reproduce this issue?
see screenshot

#### What were you expecting to happen?
just one message repeated

#### Can you share any logs, error output, etc.?
see screenshot

#### Any screenshots or additional context?
see screenshot
![repeat](https://user-images.githubusercontent.com/20775323/73980869-b55ac180-48f6-11ea-9ab0-797e73356a51.PNG)

**Comment by xieofxie** [comment]
I don't encounter this in current master. What version do you use? Thanks

**Comment by turbozapekanka** [comment]
I think I'm using VA template from December 2019

**Comment by xieofxie** [comment]
Could you use the source code from this repo directly? Fixes could not be updated to template as frequently as this repo.
Migration:https://microsoft.github.io/botframework-solutions/overview/whats-new/0.8-beta/Summary/

**Comment by turbozapekanka** [comment]
My understanding was that the template is a part of this repo: https://github.com/microsoft/botframework-solutions/tree/master/templates/csharp and the changes are somehow (automatically?) get to the visual studio and update it there.

Created a new Virtual Assistant project today the and can no longer reproduce the issue. Looks like this has been fixed in one of the recent changes.
