### ISSUE TITLE
[Music Skill] Unknown event received in VA with registered Skill

### ISSUE THREAD

**Issue by ryanisgrig** [microsoft/botframework-solutions#3010]
#### What project is affected?
Music Skill

#### What language is this in?
C#

#### What happens?
When using a VA <-> Music Skill, it does not recognize the `OpenDefaultApp` event as it did prior. I believe this is due to the new Skills SDK.

#### What were you expecting to happen?
The event activity is returned successfully.

#### Any screenshots or additional context?
![image](https://user-images.githubusercontent.com/43043272/74050234-7fffb380-498a-11ea-8138-d8b5f8a5e37d.png)

**Comment by darrenj** [comment]
@lzc850612 If VA in an utterance triggering scenario receives an event from a Skill it should return it back to the caller and get out of the way - not process it directly? Could you double check if the skill changes have caused this to stop

**Comment by guru98** [comment]
I have the same problem and yes you should return the event to the client: even if the skill is triggered from an utterance you could have some steps inside and someof them could send and receive an event. Events are used, in my case to send service command to the app and not to the client. I have this behaviour in my own skill

**Comment by lzc850612** [comment]
It looks like from the Emulator trace it's working as expected. The Emulator wouldn't know what to do with the event but i think if you are using the Android client it should work? We had the hackathon back in January with this working i remember. @ryanlengel  are you saying this is not working in android client any more?

**Comment by ryanisgrig** [comment]
No this bug was filed because I didn't realize that the emulator handled event activities different now. I am closing this issue, thanks!
