### ISSUE TITLE
[Android Client] Idle client appears to retrigger the greeting card after a while

### ISSUE THREAD

**Issue by ryanisgrig** [microsoft/botframework-solutions#3011]
#### What project is affected?
Virtual Assistant Client
#### What language is this in?
Android
#### What happens?
If left idle for a while, a connected VA re-greets the user over and over again. It appears that there may be a mechanism in the Android app that is sending additional conversationUpdate activities back to the VA **OR** the VA's logic for triggering a greeting on the Direct Line Speech channel is broken.

#### What are the steps to reproduce this issue?
Start a new conversation with a VA on the Android app, leave idle for a little while and observe.
 
#### What were you expecting to happen?
The app should not re-greet the user if left open.

#### Any screenshots or additional context?
![image](https://user-images.githubusercontent.com/43043272/74051776-7a579d00-498d-11ea-9a6a-33fc700374c5.png)

**Comment by bobokids** [comment]
Close the issue for now. we will revisit the issue when we work on Android client app issue after Iron milestone.
