### ISSUE TITLE
ITSM skill not working with teams channel

### ISSUE THREAD

**Issue by gagankohli2000** [microsoft/botframework-solutions#3014]
ITSM skill not working with teams channel. Login button click not working
![image](https://user-images.githubusercontent.com/14933211/74073568-e81fc980-4a5e-11ea-8e3f-ed14456d4d51.png)

**Comment by xieofxie** [comment]
Hi, do you add valid domain as 8 here: https://microsoft.github.io/botframework-solutions/clients-and-channels/tutorials/enable-teams/4-create-app-manifest/? Login in Teams should be a pop up window and you don't need enter code.
