### ISSUE TITLE
Old ITSM still using bot builder version 4.6.1 not working with new VA template

### ISSUE THREAD

**Issue by gagankohli2000** [microsoft/botframework-solutions#3015]
Old ITSM skill which uses bot builder version 4.6.1 not working with new VA template

Skill is not getting invoked from new VA Template

**Comment by xieofxie** [comment]
I am afraid you should update your skill. See this: https://microsoft.github.io/botframework-solutions/overview/whats-new/0.8-beta/Summary/ Thanks.
