### ISSUE TITLE
[Skills] semantic action is missing

### ISSUE THREAD

**Issue by KayMKM** [microsoft/botframework-solutions#3019]
#### What project is affected?
skills

#### What happens?
VA can send some device information to skills with semantic action before. Like timezone and location. The feature seems be removed in the latest version. So how the VA send timezone and location to skills now?

**Comment by darrenj** [comment]
This is a limitation of the SDK skills infrastructure, working on a Skill context proposal as we speak. If urgent, a developer can choose to add code within the Skill calling code (maindialog) to add entities such as timezone, location to the first activity (value property of the activity) passed to the Skill
