### ISSUE TITLE
Error enabling meeting room booking (CalendarSkill)

### ISSUE THREAD

**Issue by gagankohli2000** [microsoft/botframework-solutions#3021]
#### What project is affected?
Calendar Skill

#### What language is this in?
en-us

#### What happens?
Getting error while enabling meeting room booking (CalendarSkill)

#### What are the steps to reproduce this issue?
![meetingroomerror](https://user-images.githubusercontent.com/14933211/74148575-dbb39080-4c59-11ea-9d1b-98ae642500db.png)

#### What were you expecting to happen?
Find a Meeting Room gives error

#### Any screenshots or additional context?
Added

**Comment by darrenj** [comment]
Can you share enable_findmeetingroom_log.txt please?

**Comment by gagankohli2000** [comment]
AZ CLI passes minimum version. Current version is 2.0.81
{
  "error": null,
  "id": "/subscriptions/b54cc8c9-7da7-45ba-a86e-b09fdc4549f6/resourceGroups/CalendarSkill/providers/Microsoft.Resources/deployments/deployment_dry_run",
  "name": "deployment_dry_run",
  "properties": {
    "correlationId": "639a02d4-8c6d-4be2-8899-0f7ad38b19ff",
    "debugSetting": null,
    "dependencies": [],
    "duration": "PT0S",
    "mode": "Incremental",
    "onErrorDeployment": null,
    "outputs": null,
    "parameters": {
      "azureSearchName": {
        "type": "String",
        "value": "CalendarSkill-5orivjc"
      },
      "location": {
        "type": "String",
        "value": "westus2"
      },
      "name": {
        "type": "String",
        "value": "CalendarSkill"
      },
      "suffix": {
        "type": "String",
        "value": "5orivjc"
      },
      "useAzureSearch": {
        "type": "Bool",
        "value": true
      }
    },
    "parametersLink": null,
    "providers": [
      {
        "id": null,
        "namespace": "Microsoft.Search",
        "registrationPolicy": null,
        "registrationState": null,
        "resourceTypes": [
          {
            "aliases": null,
            "apiVersions": null,
            "capabilities": null,
            "locations": [
              "westus2"
            ],
            "properties": null,
            "resourceType": "searchServices"
          }
        ]
      }
    ],
    "provisioningState": "Succeeded",
    "template": null,
    "templateHash": "5022438839856542971",
    "templateLink": null,
    "timestamp": "2020-02-10T12:08:52.324965+00:00",
    "validatedResources": [
      {
        "id": "/subscriptions/b54cc8c9-7da7-45ba-a86e-b09fdc4549f6/resourceGroups/CalendarSkill/providers/Microsoft.Search/searchServices/calendarskill-5orivjc",
        "resourceGroup": "CalendarSkill"
      }
    ]
  },
  "resourceGroup": "CalendarSkill",
  "type": "Microsoft.Resources/deployments"
}
{
  "azureSearch": {
    "type": "Object",
    "value": {
      "apiKey": "2F2B10061406CC4909FBAB1AA3C8BDA9",
      "azureSearchAccount": "calendarskill-5orivjc",
      "collectionId": "azuresearchid",
      "databaseId": "azuresearch"
    }
  }
}
Invoke-RestMethod : {
  "error": {
    "code": "UnknownError",
    "message": "",
    "innerError": {
      "request-id": "6ff60e0d-9d8d-42fc-bcf2-ac61fdb9afce",
      "date": "2020-02-10T12:12:22"
    }
  }
}
At E:\NABBOTv8\calendarskill\Deployment\Scripts\msgraph_functions.ps1:40 char:14
+    $result = Invoke-RestMethod -Uri $url -Headers $headers
+              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (Method: GET, Reques\u2026PowerShell/6.2.4
}:HttpRequestMessage) [Invoke-RestMethod], HttpResponseException
+ FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

**Comment by xhr0804** [comment]
@gagankohli2000 Seems that the step to access meeting room data from MSGraph failed. But I can not reproduce it.
Have your followed the guide about "Meeting Room Booking Support" in https://microsoft.github.io/botframework-solutions/skills/samples/calendar/ and make sure the configuration set correctly (Make sure your account have the admin privileges to access your tenant’s meeting room data). 
If all are correct, could you share more details of your environment such as an screenshot of your configuration of the registered app or just send your account to huanx@microsoft.com so that I can help you to check the error.

**Comment by darrenj** [comment]
@gagankohli2000 Did you manage to resolve this?
