### ISSUE TITLE
QnA KBs are not created "No Endpoint keys found." error

### ISSUE THREAD

**Issue by turbozapekanka** [microsoft/botframework-solutions#3024]
#### What project is affected?
Visual Assistant

#### What language is this in?
C#

#### What happens?
1. Deployment of QnA KBs fails.
2. Retries countdown goes negative.

#### What are the steps to reproduce this issue?
Deploy VA using ./Deployment/Scripts/deploy.ps1 script

#### What were you expecting to happen?
1. Everything is deployed
2. Retries countdown stop at 0

#### Can you share any logs, error output, etc.?
[deploy_cognitive_models_log.txt](https://github.com/microsoft/botframework-solutions/files/4182319/deploy_cognitive_models_log.txt)

#### Any screenshots or additional context?
![Capture](https://user-images.githubusercontent.com/20775323/74175895-551c9600-4bfc-11ea-99ed-85391f8d96bb.PNG)

**Comment by turbozapekanka** [comment]
I found a similar issue but not sure what would be the workaround https://github.com/MicrosoftDocs/azure-docs/issues/44719

**Comment by turbozapekanka** [comment]
It worked for me after I removed old resources and waited for ~1h before redeploying again.

**Comment by lauren-mills** [comment]
According to the QnA Maker team, this error is shown when the QnA Maker service has not finished provisioning. There appear to be service issues QnA Maker right now that are causing the provisioning process to take even longer than the time we wait in the script. 

We can take a look and try to make the script handle this scenario more gracefully.

**Comment by darrenj** [comment]
We've spoken to the QnAMaker team who have confirmed a regression on their side which should be now fixed. Can you let us know if you continue to see the issue on a fresh deployment please? thanks for letting us know

**Comment by Tiger519** [comment]
@darrenj this is still an issue. Can you please reopen?
