### ISSUE TITLE
Hospitality Assistant Solution Accelerator: Support "I'm hungry" to go to hospitality skill 

### ISSUE THREAD

**Issue by fractalcrafter** [microsoft/botframework-solutions#3044]
## User Story
As a user of the hospitality assistant
I want to be taken to the hospitality skill to go through the food ordering skill when I say "I'm hungry". 

Currently "I'm hungry" takes to QnA. We should look into the potential overlap utterances between our chitchat, FAQ, and hospitality skill to solve the general issue. 

![image](https://user-images.githubusercontent.com/25210203/74387303-06622e00-4dad-11ea-9471-ae2599914813.png)

**Comment by xieofxie** [comment]
We could move `## ? I require sustenance` from FAQ to hospitality skill.
