### ISSUE TITLE
ITSM skill login failed error. No login prompt

### ISSUE THREAD

**Issue by gagankohli2000** [microsoft/botframework-solutions#3053]
#### What project is affected?
ITSM skill. Working fine in teams but when access via web channel Im getting login failed error.

#### What language is this in?
cs

#### What happens?
Login failed. No login prompt card.

#### What are the steps to reproduce this issue?
![loginError](https://user-images.githubusercontent.com/14933211/74519386-b1b7e200-4f69-11ea-9b5a-4cc2140083e3.png)

**Comment by xieofxie** [comment]
Hi, I am afraid you pasted the wrong screenshot. Could you provide the conversation and error information?

Have you tried debugging in local via a tunnel like ngrok?

**Comment by gagankohli2000** [comment]
@xieofxie My bad. Uploaded correct screenshot. It's working in teams and bot emulator but getting Login failed error in web chat.

**Comment by gagankohli2000** [comment]
@xieofxie Here is the error i'm getting in webchat. This was working yesterday. I have not made any change and it's still working in teams and emulator but not in web chat.
![Webchat](https://user-images.githubusercontent.com/14933211/74519799-884b8600-4f6a-11ea-8f98-545921c7259e.png)

**Comment by xieofxie** [comment]
Hi @gagankohli2000 for your first issue, the 'Start over' in webchat doesn't change user id while token is linked to user id. So the error 'You failed to log in ..' will be displayed when that user id has a token but is invalid somehow. You could say 'log out' first to clear the token.

For your second issue, I would see the 'Gateway Timeout' when the bot responses slowly (e.g being debugged) and it may not indicate an error in bot. What's happening in the webchat window? Where do you deploy your bot? Thanks

**Comment by darrenj** [comment]
WebChat in the Azure Portal is quite an old version, can you use WebChat directly or the emulator instead to ensure that isn't the underlying issue?

Thanks

**Comment by darrenj** [comment]
Let us know if you need any more help.
