### ISSUE TITLE
[POI] errors in PVA

### ISSUE THREAD

**Issue by xieofxie** [microsoft/botframework-solutions#3055]
## User Story
As ... anyone
I want ... to use POI in PVA
so that ... it is useful

## Acceptance Criteria 
*List your requirements.*
- [ ] ... PVA doesn't support ActionSet
![image](https://user-images.githubusercontent.com/2876650/74505570-7bab3b80-4f32-11ea-84ee-9dd2d84e2016.png)
- [ ] ... PVA has a system topic Escalate which will be triggered by call (note call action is removed)
![image](https://user-images.githubusercontent.com/2876650/74505684-c2993100-4f32-11ea-8959-3a9289186003.png)

## Resources
*Provide any screenshots or conversation mockups to support your request.*
*Learn how to mock up bot conversations with [.chat files](http://aka.ms/bfchatfile).*

## Notes
*Provide any additional information.*

**Comment by xieofxie** [comment]
@darrenj should we modify skills for PVA like Teams? How could we report PVA's bug with faster response? Thanks!

**Comment by darrenj** [comment]
I've sent a mail internally to connect you up with people
