### ISSUE TITLE
Implement package deprecation fix across all VAs and Skills in the repo

### ISSUE THREAD

**Issue by pavolum** [microsoft/botframework-solutions#3064]
This [commit](https://github.com/microsoft/botframework-solutions/commit/e369a099cca1fd2c9fb29a99ac2b559c981eac5e) has fixed the depreciation warnings outlined in this [issue](https://github.com/microsoft/botframework-solutions/issues/2959).

We now need to propagate this change across the remaining skills and VAs within our repo.

**Comment by xieofxie** [comment]
Will be covered by this https://github.com/microsoft/botframework-skills/issues/124
