### ISSUE TITLE
SetLocaleMiddleware question

### ISSUE THREAD

**Issue by turbozapekanka** [microsoft/botframework-solutions#3068]
I assume that LocaleTemplateEngineManager works with conjunction with SetLocaleMiddleware.
How to get/set current locale in the runtime? Example scenario: user wants to change bot language.

**Comment by xieofxie** [comment]
Hi @turbozapekanka, SetLocaleMiddleware https://github.com/microsoft/botframework-solutions/blob/0c37ebd42a5b6c121f30e4a5d869deb8acb8b43c/sdk/csharp/libraries/microsoft.bot.solutions/Middleware/SetLocaleMiddleware.cs#L28 will set CurrentUICulture by Activity.Locale. You could change [CurrentUICulture](https://docs.microsoft.com/en-us/dotnet/api/system.globalization.cultureinfo?view=netframework-4.8#the-current-culture-and-current-ui-culture) again with a preferred locale saved in user's state in a following middleware.

**Comment by turbozapekanka** [comment]
Thanks for the link!
