### ISSUE TITLE
not getting any response after adding hospitality skill

### ISSUE THREAD

**Issue by marutisalunkhe** [microsoft/botframework-solutions#3069]
/skills/handbook/botskills/

**Comment by darrenj** [comment]
Can you share the following please to help investigate

- [ ] Does the hospitality skill work when you talk to it directly using the Emulator? 
- [ ] Did adding the hospitality skill to your VA complete successfully?
- [ ] What utterance you are passing to trigger the hospitality skill
- [ ] Share a Emulator Transcript / Screenshot of the interaction

**Comment by CoHealer** [comment]
@marutisalunkhe do you still require assistance? If so, can you please answer the questions from @darrenj above?

**Comment by dmvtech** [comment]
Closing this as there has been no response from you @marutisalunkhe. Please reopen or respond if you still need assistance with this.
