### ISSUE TITLE
Power BI Report

### ISSUE THREAD

**Issue by CurlyBytes** [microsoft/botframework-solutions#3073]
#### What project is affected?
Power BI report provided

#### What language is this in?
Power BI

#### What happens?
Access denied

#### What are the steps to reproduce this issue?
Just follow the steps in the 
https://microsoft.github.io/botframework-solutions/solution-accelerators/tutorials/view-analytics/2-get-application-insights-application-id/

#### What were you expecting to happen?
All reports will be display

#### Any screenshots or additional context?
![image](https://user-images.githubusercontent.com/55616292/74739900-c90e0c80-5294-11ea-9599-f87bcb805fab.png)

im pretty sure im using app id in app insights, i even tried the secret on it, i am also Global Admin in Azure Tenant

Any feedback wil dot , thanks

**Comment by mdrichardson** [comment]
@cocoytech Are you signed into PowerBI with the same user account that created the App Insights Azure Resource (when you ran `az login` while creating the VA bot)?

Perhaps you need to re-sign into PowerBI. Go to the Menu, and at the bottom is the Sign Out option. Do this, sign back in as the same user you used for `az login` and then try loading the VA Template again.

**Comment by CurlyBytes** [comment]
Hi @mdrichardson , I'm pretty sure that i use corporate account in the azure tenant, power bi and AZ CLI login, here is the attached screenshot as follow

The Power BI login
![image](https://user-images.githubusercontent.com/55616292/74900021-74c07500-53d9-11ea-89fb-1baa0ef6ffb1.png)


The AZ CLI login

![image](https://user-images.githubusercontent.com/55616292/74900076-a3d6e680-53d9-11ea-8a8c-ac51787e06fd.png)



The azure login tenant
![image](https://user-images.githubusercontent.com/55616292/74900095-b2bd9900-53d9-11ea-8640-208b7cb23045.png)


Still forbidden access,
a few days ago, i can see the report, but now  it cannot be seen in the power bi due to the forbidden access error

**Comment by mdrichardson** [comment]
@cocoytech That's odd.

1. I see that you're on a "Microsoft Azure Sponsorship". Is it possible you've hit any [service limits](https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/azure-subscription-service-limits)?
2. If you sign out of all 3 of those services and sign back in, does the problem resolve?
3. Can you confirm that you're using the correct App Insights service and app ID?
4. From the App Insights Service, click Access Control (IAM) > Check Access > then search for yourself and verify that you have the correct access level.

**Comment by CurlyBytes** [comment]
Hello @mdrichardson 

1 -> It wasn't hit limit, im sure of it
2. -> I did signout and relogin all 3 services (AZ cli, powerBi and Azure portal)
3 -> yes there is one app insights on this resource
4. -> I am the GA in the tenant, i did recheck and yes my access is inherent on the subscription, i even did try on setting the resource group as owner, but still no luck

**Comment by mdrichardson** [comment]
@cocoytech Sorry for all the troubleshooting, but this seems to be a difficult one to solve.

1. This is the AppInsights resource that was created by the Deploy.ps1 PowerShell script, right?
2. In your VA's `appsettings.json`, the `instrumentationKey` is the same one you see in the Azure Portal, right (and this is different from the appId you're using to connect to the Template)?
3. One last thing to try: 
    1. Open the Template
    2. File > Options and Settings > Data Source Settings
    3. Click "Global permissions"
    4. Click on anything resembling "api.logalytics.io" and Clear Permissions > Clear Permissions > Delete
    5. Close and Re-open the Template
    6. Paste your AppId
    7. Click Load
    8. *Important*: Select Organizational Account > Sign In > Connect

**Comment by CurlyBytes** [comment]
Hi @mdrichardson  , sure no worries, atleast there is an input, but at your end can you really run the PowerBI template without any problem?

1 -> Yes the deployment is using deploy.ps1, atleast two weeks ago i manage to run the template, but after this week, something is off on the Template itself, it just appear no where

2 -> Yes the appsettings.json of VA template about instrument key is match on the azure portal

3 -> YES! thank you very much it resolve, i think the BI template it self it will store if use different App ID( first one it was run, then when i recreate again the VA template by following the steps - just to make sure the procedure and working as expected) . You may close this ticket, and also kindly add a warning about multiple app id on per BI template running on the same device or either update the BI template itself, thanks!

**Comment by mdrichardson** [comment]
@cocoytech Glad that worked! Yes, I was able to run the template without any difficulties. I'll see if we can add a warning about needing to update authentication for the template.
