### ISSUE TITLE
[Calendar] action support

### ISSUE THREAD

**Issue by xhr0804** [microsoft/botframework-solutions#3074]
## User Story
As ... anyone
I want ... to Calendar supports actions like BookMeeting/AcceptMeeting...
so that ... it could be used in PVA etc.

## Acceptance Criteria 
*List your requirements.*
Actions including
- [ ] Book meeting
- [ ] Accept meeting
- [ ] Delete meeting
- [ ] Join meeting
- [ ] Show meeting
- [ ] Time Remaining
- [ ] Meeting summary

## Resources
*Provide any screenshots or conversation mockups to support your request.*
*Learn how to mock up bot conversations with [.chat files](http://aka.ms/bfchatfile).*

## Notes
*Provide any additional information.*

**Comment by lauren-mills** [comment]
Please add more details into issues like this in the future.
