### ISSUE TITLE
[Skills] handle cancel etc. in skill mode

### ISSUE THREAD

**Issue by xieofxie** [microsoft/botframework-solutions#3084]
## User Story
As ... a PVA + skill user
I want ... to cancel to be properly handled
so that ... it is good experience

## Acceptance Criteria 
*List your requirements.*
- [ ] ... Handle cancel etc. properly in skill mode

## Resources
*Provide any screenshots or conversation mockups to support your request.*
*Learn how to mock up bot conversations with [.chat files](http://aka.ms/bfchatfile).*

When in PVA a user sends cancel, it will be sent to skill and then the skill begin main dialog again which will parse cancel in RouteStepAsync.
This is not desired logic. We should not begin main dialog in skill mode.

## Notes
*Provide any additional information.*

**Comment by lauren-mills** [comment]
We can add the IsSkill check before the cancel logic to only restart maindialog in local mode.

**Comment by xieofxie** [comment]
Also it should a 'action failed' result for PVA scenario

**Comment by darrenj** [comment]
Agreed - @xieofxie can you do a PR for the change including skillsample?

**Comment by xieofxie** [comment]
@darrenj OK
