### ISSUE TITLE
Replaced deprecated LuisPredictionOptions with LuisRecognizerOptionsV3 

### ISSUE THREAD

**Issue by rvallireply** [microsoft/botframework-solutions#3088]
I used the following command to generate the GeneralLuis.cs class from a LUIS app JSON  set to the italian it-it locale:

`bf luis:generate:cs -f -i "C:\users\johndoe\source\repos\myskill\Deployment\Resources\LU\it-it\VMyskillit-it_General_v0.1.json" -o "C:\users\johndoe\source\repos\Myskill\Services\" --className="GeneralLuis"`

ISSUE: when I test the bot with italian language and activities like "apri un ticket" ("open a ticket") an exception is thrown at the following line in Convert function

`var app = JsonConvert.DeserializeObject<GeneralLuis>(JsonConvert.SerializeObject(result, new JsonSerializerSettings { NullValueHandling = NullValueHandling.Ignore }));`

Exception: 
`Newtonsoft.Json.JsonReaderException: 'Could not convert string to double: un. Path 'entities.number[0]', line 1, position 183.'`

If I change "un" to "one" at runtime the exception is not thrown.
It seems LUIS correctly translates "un ticket" (italian article for "a ticket") to "one" and passes it as a number but the resulting serialized JSON keeps the string "un" instead of the number, hence the type mismatch

`{"text\":"apri un ticket","intents":{"Stop":{"score":0.045692727}},"entities":{"$instance":{"number":[{"startIndex":5,"endIndex":7,"text":"un","type":"builtin.number"}]},"number":["un"]}} `

This doesn't happen only for italian indefinite articles "un, uno, una" ("a", "an").
The same of course happens if I tell the bot to "apri due ticket" ("open two tickets") and so on...

**Comment by darrenj** [comment]
Thanks @cleemullins - yes we addressed this a few weeks back and is in our next branch to go out in next release. I'll add a known issue in the docs too

**Comment by darrenj** [comment]
The update away from the deprecated feature was addressed in #3061 however this is still V2. @pavolum could you look into updating to the v3 endpoint addressing this issue and moving us to the latest.

@cleemullins This should probably be covered in BF docs somewhere (i.e. the differences between V2 and V3 and what known issues there are for customers wiring up LUIS themselves? Deprecation warning too perhaps?
