### ISSUE TITLE
msbot clone services fails in southeastasia region 

### ISSUE THREAD

**Issue by NobinJoseRad** [microsoft/botframework-solutions#309]
**Project**
Enterprise Bot Template

**Description**
msbot clone command fails when the region selected in "southeastasia". I managed to create it using eastasia however i wish to have southeastasia support.

**To Reproduce**
run msbot clone services with location "southeastasia"

**Expected behavior**
Should be able to create all azure services needed for bot without error

**Screenshots**
![image](https://user-images.githubusercontent.com/29299856/48529957-8232a980-e8d0-11e8-9116-6d1fe0705a10.png)

**Additional context**

**Comment by lauren-mills** [comment]
Hi @NobinJoseRad what version of the msbot tool do you have installed? (Run `msbot -v` to check)

**Comment by NobinJoseRad** [comment]
HI @lauren-mills 

version is 4.0.7

Thanks!

**Comment by lauren-mills** [comment]
@NobinJoseRad I'm checking on this now. Seems like it is either a bug in the msbot tool, or in the `az bot create` command. I'll route it to the whichever team makes sense and refer back here.

**Comment by NobinJoseRad** [comment]
thanks, i have tried a number of times to ensure this is not working in SEA region.

**Comment by lauren-mills** [comment]
I've raised a bug on the botbuilder-tools repo and linked so you can track its progress.

**Comment by darrenj** [comment]
tracked in botbuilder repo so closing here
