### ISSUE TITLE
RouterDialog Obsoleted by ActivityHandlerDialog which is deprecated

### ISSUE THREAD

**Issue by DavidStrickland0** [microsoft/botframework-solutions#3092]
#### What project is affected?
microsoft.bot.solutions
#### What language is this in?
C#
#### What happens?
If you attempt to use RouterDialog you find it is obsolete and the message provides a link to directions that explain that you should use ActivityHandlerDialog instead https://aka.ms/bfvarouting. 
sdk/csharp/libraries/microsoft.bot.solutions/Dialogs/RouterDialog.cs line 14
```
    [Obsolete("Please use ActivityHandlerDialog instead. For more information, refer to https://aka.ms/bfvarouting.", false)]
    public abstract class RouterDialog : InterruptableDialog
```

if you follow these directions you get a message that ActivityHandlerDialog is deprecated and for more information see: https://aka.ms/bfvarouting ... IE the directions that tell you to use it
sdk/csharp/libraries/microsoft.bot.solutions/Dialogs/ActivityHandlerDialog.cs line 16
```
    [Obsolete("ActivityHandlerDialog is being deprecated. For more information, refer to https://aka.ms/bfvarouting.", false)]
    public abstract class ActivityHandlerDialog : InterruptableDialog
```

**Comment by lauren-mills** [comment]
Thanks for raising this! We have actually changed the VA MainDialog implementation to use WaterfallDialog which you can see [here](https://github.com/microsoft/botframework-solutions/blob/master/samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Dialogs/MainDialog.cs). We will update the documentation to reflect the changes.
