### ISSUE TITLE
Unable to connect to Skill Bot while running VA from Emulator

### ISSUE THREAD

**Issue by manish-95** [microsoft/botframework-solutions#3094]
#### What project is affected?
Virtual Assistant
Skill

#### What language is this in?
C#

#### What happens?
Using the new Virtual Assistant and Skill Template (version 4.7.0.2) based on 0.8 Beta Release, while attempting to access a connected skill from the Bot Framework Emulator (version 4.7.0), the status code returned is 500, with the error message as "Exception Message: Error invoking the skill id: "<skillName>" at "https://<deployed skill endpoint>api/messages" (status is 500).  If I attempt the same from the Azure Portal WebChat interface, the call goes through and I am able to access the relevant Skill Bot.
 

#### What are the steps to reproduce this issue?
1. Deploy VA and Skill Template using the version mentioned above.
2. Connect the deployed VA and Skill Bots.
3. Run the VA project locally in Bot Framework Emulator.
4. Use any utterance to trigger the connected skill.
5. Note the error as mentioned above.

#### What were you expecting to happen?
The VA connects to the deployed skill bot , even while testing locally from the Emulator, and not just through WebChat.

#### Can you share any logs, error output, etc.?
On further examination using App Insights Live Metrics, the following logs were obtained:
[Error_logs.txt](https://github.com/microsoft/botframework-solutions/files/4239577/Error_logs.txt)

**Comment by xieofxie** [comment]
hi @manish-95, when skill replies to VA, it needs a public accessible SkillHostEndpoint in VA's appsettings.json.
So if you would like to test a local VA connecting to a remote skill, use a local tunnel like ngrok for VA and set the value of SkillHostEndpoint like `https://*.ngrok.io/api/skills`.
Thanks

**Comment by darrenj** [comment]
Documented [here](https://microsoft.github.io/botframework-solutions/help/known-issues/#http-500-error-when-invoking-a-skill)

**Comment by darrenj** [comment]
Let us know if you have any other issues/questions
