### ISSUE TITLE
[VA][Skills] SignOut for skills

### ISSUE THREAD

**Issue by xieofxie** [microsoft/botframework-solutions#3100]
## User Story
As ... a VA-skill user
I want ... to sign out skills in VA
so that ... it is easy to manage

## Acceptance Criteria 
*List your requirements.*
- [ ] ... when signout in VA, skills are also signed out

## Resources
*Provide any screenshots or conversation mockups to support your request.*
*Learn how to mock up bot conversations with [.chat files](http://aka.ms/bfchatfile).*

It doesn't work now because we are using skill's credentials for token while using VA's for signing out. 

It seems it is being implemented in SDK?

## Notes
*Provide any additional information.*

**Comment by darrenj** [comment]
This will be handled by the new SSO/Auth work
