### ISSUE TITLE
[Skills] use TeamsActivityHandler

### ISSUE THREAD

**Issue by xieofxie** [microsoft/botframework-solutions#3107]
#### What project is affected?
skills
#### What language is this in?
C#
#### What happens?
Should use TeamsActivityHandler for sign in
#### What are the steps to reproduce this issue?
Sign in Calendar skill directly in Teams
#### What were you expecting to happen?
Sign in successfully
#### Any screenshots or additional context?
* Use https://github.com/microsoft/botframework-solutions/blob/master/skills/csharp/experimental/itsmskill/Bots/DefaultActivityHandler.cs
* Or should we create a common one in solutions library?

**Comment by xieofxie** [comment]
Also update template? Wonder if it is common to use skill directly in Teams

**Comment by bobokids** [comment]
@darrenj , should we use TeamsActivityhandler in skill template? VA template already used it. if we decide to use it we will change all skills accordingly.

**Comment by darrenj** [comment]
Adding a Skill to Teams directly wouldn't be something I'd normally expect users to do. I don't see any downside of adding it apart from unnecessary complexity/confusion. Perhaps we add a known issue instead?

**Comment by xieofxie** [comment]
@darrenj I would like to add it to skill just as VA. Since they are all bots and we should(?) keep as less as difference as possible

**Comment by darrenj** [comment]
I'll discuss with the team!
