### ISSUE TITLE
[Docs] 404 not found: convert an existing v4 Bot to a Bot Framework Skill

### ISSUE THREAD

**Issue by angelacib** [microsoft/botframework-solutions#3108]
When clicking a hyperlink from the FAQ page (https://microsoft.github.io/botframework-solutions/help/faq/) for the question How do I convert an existing v4 Bot to a Bot Framework Skill?, there is a 404 error.

**Comment by xieofxie** [comment]
It should be https://microsoft.github.io/botframework-solutions/overview/whats-new/0.8-beta/migrate-existing-va-to-0.8/. Fix is on the way..

**Comment by darrenj** [comment]
Fixed
