### ISSUE TITLE
Nuget Points to wrong project Url

### ISSUE THREAD

**Issue by DavidStrickland0** [microsoft/botframework-solutions#3109]
The Nuget Definition has the wrong Project Url and wrong source repository
Both point to 
https://github.com/Microsoft/AI
However the owner of https://github.com/Microsoft/AI site does not have any knowledge of this
See:
https://github.com/microsoft/AI/issues/15

**Comment by darrenj** [comment]
Good spot - we renamed the repo a while back and it was then reallocated.

@pavolum Would you be able to do a pass through the repo for any instances of "github.com/Microsoft/AI"?

- Specifically for this - the URL is [here](https://github.com/microsoft/botframework-solutions/blob/6d40fa8ae05f96b0c5e0464e01361a9e1deb696c/sdk/typescript/libraries/botbuilder-solutions/package.json)

**Comment by lauren-mills** [comment]
URL has been updated for Microsoft.Bot.Solutions nuget: https://www.nuget.org/packages/Microsoft.Bot.Solutions/0.8.0-preview2
