### ISSUE TITLE
Unable to install botskills command on Virtual machine

### ISSUE THREAD

**Issue by priyanka-shetty** [microsoft/botframework-solutions#3111]
**Unable to install botskills command on Self-Hosted Azure agent.**

Used following command to install packages get updated but when tried to check using "botskills" command it throws up and error saying botskills not available.

Screenshots

Used " npm install -g botskills@latest " to install the package where the following screenshot infers that the botskill packages have been updated.

![image](https://user-images.githubusercontent.com/46015119/75314637-56012900-5886-11ea-92bd-c752f1eba8bc.png)

But when tried to use the updated package it does not work

![image](https://user-images.githubusercontent.com/46015119/75314776-b7c19300-5886-11ea-89bb-34462c3e960b.png)

All the other supporting packages have been updated.

This issue occurs while using the Self-Hosted agent (Windows agent) only and works with no issue on local.

**Steps to reproduce**
1) Use any of the Microsoft Self-Hosted Agent.
2) Try installing botkskills using following command _npm install -g botskills@latest_
  (Follow the attached screenshots)
3) Try using botskills to verify if the package is available.

**Comment by csnarain** [comment]
> 
> 
> **Unable to install botskills command on Self-Hosted Azure agent.**
> 
> Used following command to install packages get updated but when tried to check using "botskills" command it throws up and error saying botskills not available.
> 
> Screenshots
> 
> Used " npm install -g botskills@latest " to install the package where the following screenshot infers that the botskill packages have been updated.
> 
> ![image](https://user-images.githubusercontent.com/46015119/75314637-56012900-5886-11ea-92bd-c752f1eba8bc.png)
> 
> But when tried to use the updated package it does not work
> 
> ![image](https://user-images.githubusercontent.com/46015119/75314776-b7c19300-5886-11ea-89bb-34462c3e960b.png)
> 
> All the other supporting packages have been updated.
> 
> This issue occurs while using the Self-Hosted agent (Windows agent) only and works with no issue on local.
> 
> **Steps to reproduce**
> 
>     1. Use any of the Microsoft Self-Hosted Agent.
> 
>     2. Try installing botkskills using following command _npm install -g botskills@latest_
>        (Follow the attached screenshots)
> 
>     3. Try using botskills to verify if the package is available.

Did you check your PATH environment variable? May be botskills is not in your PATH

**Comment by dmvtech** [comment]
@priyanka-shetty Were you able to check your path variable?

**Comment by priyanka-shetty** [comment]
@dmvtech @csnarain Thanks for providing the solution it.
It worked!!
