### ISSUE TITLE
[VA][Skills] set CompletedMessage as FinalStepAsync for Cancel/Logout

### ISSUE THREAD

**Issue by xieofxie** [microsoft/botframework-solutions#3112]
## User Story
As ... anyone
I want ... to no duplicate welcome message
so that ... it is good

## Acceptance Criteria 
*List your requirements.*
- [ ] ... Set CompletedMessage in BeginDialogAsync(InitialDialogId); for Cancel/Logout
- [ ] ... Apply to all skills

## Resources
*Provide any screenshots or conversation mockups to support your request.*
*Learn how to mock up bot conversations with [.chat files](http://aka.ms/bfchatfile).*

## Notes
*Provide any additional information.*

**Comment by darrenj** [comment]
Can you provide an example of the the issue and how to repro please?

**Comment by xieofxie** [comment]
In FinalStepAsync, we will use CompletedMessage to indicate next round of conversation
![image](https://user-images.githubusercontent.com/2876650/76606038-80bcd400-654c-11ea-9ac5-347723771c4e.png)

While in Cancel/Logout, we will just begin flow then it will be FirstPromptMessage. They are not consistent.
![image](https://user-images.githubusercontent.com/2876650/76606044-84505b00-654c-11ea-81a7-c21c47f46be5.png)

Very subtle difference..

**Comment by lzc850612** [comment]
I think this is fixed in #3154 correct?

**Comment by xieofxie** [comment]
@lzc850612 No, it is merely a subtle difference between CompletedMessage and FirstPromptMessage.

When an dialog is finished, we use CompletedMessage to reply user

However when user cancels/logs out, we use FirstPromptMessage to reply user

**Comment by darrenj** [comment]
What's the status of this? It currently isn't merged so doesn't make the cut for GA. Do we still need this PR and if so are we taking it for GA?

**Comment by xieofxie** [comment]
no, we don't
