### ISSUE TITLE
[Enterprise] Multi-turn HRBenefits FAQ is not supported in .lu format and not in source code

### ISSUE THREAD

**Issue by xieofxie** [microsoft/botframework-solutions#3113]
#### What project is affected?
Enterprise Assistant
#### What language is this in?
C#
#### What happens?
 HRBenefits is not added when #2641. LOL

**Comment by ryanisgrig** [comment]
Known issue, multiturn FAQ is not supported in .LU files so this is only available in our test environments at the moment.

**Comment by ryanisgrig** [comment]
Closed via #3264
