### ISSUE TITLE
SuppressCompletionMessage does not seem to work

### ISSUE THREAD

**Issue by turbozapekanka** [microsoft/botframework-solutions#3115]
#### What project is affected?
Virtual Assistant

#### What language is this in?
C#

#### What happens?
CompletionMessage is displayed where it is supposed to be suppressed

#### What were you expecting to happen?
CompletionMessage should not be displayed where it is supposed to be suppressed

#### Any screenshots or additional context?
MainDialog:

                else if (dispatchIntent == DispatchLuis.Intent.q_Chitchat)
                {
                    stepContext.SuppressCompletionMessage(true);

                    return await stepContext.BeginDialogAsync("Chitchat");
                }

![image](https://user-images.githubusercontent.com/20775323/75467219-f885de80-5950-11ea-95ba-6a8908b78885.png)

**Comment by xieofxie** [comment]
Hi @turbozapekanka you could follow this pr #3129 to fix this.

**Comment by darrenj** [comment]
@xieofxie Thanks - I don't understand the change as it's been made to `IntroStepAsync` which is not involved in the example shown?
@pavolum - Could you check to see if we have a regression with the recent maindialog change around the supression of the completion message?

**Comment by xieofxie** [comment]
@darrenj Because currently, complete message is displayed in `IntroStepAsync` via https://github.com/microsoft/botframework-solutions/blob/b41b177ef53deeaca6291b2b7ebe73a83a0b5a4f/samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Dialogs/MainDialog.cs#L360
