### ISSUE TITLE
Facing issue while attaching Skills bot to VA

### ISSUE THREAD

**Issue by nijoshi-msft** [microsoft/botframework-solutions#3117]
#### What project is affected?
Bot Development -- where customer wants to use Skills

#### What language is this in?
.Net/C#

#### What happens?
After attaching skills bot to virtual assistant through the below command, all required files are updated except skills.json which is one major file to be updated.
‘botskills connect --remoteManifest "https://<BotWebApp_AppService>.azurewebsites.net/manifest/manifest-1.1.json" --luisFolder "C:\Users\<username>\Documents\projects\bot github\botframework-solutions-master\botframework-solutions-master\skills\csharp\todoskill\Deployment\Resources\LU" --languages "en-us" --cs’

#### What are the steps to reproduce this issue?
Followed the below documentation to proceed:
https://microsoft.github.io/botframework-solutions/skills/tutorials/create-skill/csharp/7-add-your-skill/

#### What were you expecting to happen?
skills.json should be filled with required skill information.

**Comment by Batta32** [comment]
Thanks @nijoshi-msft for reporting the issue! We will be checking the scenario and get back to you later!

**Comment by xieofxie** [comment]
Hi @nijoshi-msft skills.json is not used anymore. Skills are added to 'BotFrameworkSkills' section of appsettings.json of VA. 
Who could update docs here? @Batta32 Thanks

**Comment by Batta32** [comment]
Hi @xieofxie ! We are currently updating the Botskills documentation in order to be consistent with the last version of the tool 😊.

**Comment by nijoshi-msft** [comment]
thanks @xieofxie.. @Batta32 -- can you please share the latest documentation which addresses  how to deploy Skill bot using BotFrameworkSkills section under appsetttings.json? Or should we follow https://microsoft.github.io/botframework-solutions/skills/tutorials/create-skill/csharp/7-add-your-skill/?

**Comment by Batta32** [comment]
Hi @nijoshi-msft , we created the PR #3138 which updates the Botskills documentation with the new manifest schema changes. You attached the correct document which we updated [here](https://github.com/microsoft/botframework-solutions/pull/3138/files#diff-dd200ec38a484ca7e259a3258622e6b2).

If you have any feedback, don't hesitate to point it in the PR 😊.
