### ISSUE TITLE
[Template] self-host webchat

### ISSUE THREAD

**Issue by xieofxie** [microsoft/botframework-solutions#3118]
## User Story
As ... a developer
I want ... to test in webchat easily
so that ... it is easy

## Acceptance Criteria 
*List your requirements.*
- [ ] ... host a webchat inside bot

## Resources
*Provide any screenshots or conversation mockups to support your request.*
*Learn how to mock up bot conversations with [.chat files](http://aka.ms/bfchatfile).*

Example https://github.com/microsoft/botframework-solutions/commit/746e8b505412de977b29c333dab422c2dbf3e1f9

## Notes
*Provide any additional information.*

**Comment by ryanisgrig** [comment]
Hi @xieofxie, I added the needs requirements label for more explanation. This seems like something that should be provided by the botframework-webchat repository rather than ours. Can you give some more background?

**Comment by xieofxie** [comment]
@ryanlengel I saw that we hosted separate web chat services for our internal testing bot and feel they could actually be hosted together with bot itself.

**Comment by ryanisgrig** [comment]
Got it! In that case I'm not sure it's necessary. Our internal testing one is just a wrapper so we can demo off appropriately. As long as we don't have any special customizations that would be a part of the solution it's better to keep those separate and under the ownership of different teams.

Sent from my 📱

________________________________

**Comment by xieofxie** [comment]
OK~
