### ISSUE TITLE
[Docs]Screenshot for Analytics Power BI Tutorial needs to be updated

### ISSUE THREAD

**Issue by fractalcrafter** [microsoft/botframework-solutions#3125]
https://microsoft.github.io/botframework-solutions/solution-accelerators/tutorials/view-analytics/2-get-application-insights-application-id/

The screenshot of this page needs to be updated now. For step 3, Azure Portal UI has changed. Now should be:
![image](https://user-images.githubusercontent.com/25210203/75633336-c70f4c00-5bb8-11ea-823d-e8cad7d876c3.png)

**Comment by darrenj** [comment]
Docs are correct - they are referring to the Application Insights resource not Bot Service!

![image](https://user-images.githubusercontent.com/33519520/83029153-3f57a300-a02a-11ea-9c3a-2d18de64c997.png)
