### ISSUE TITLE
Error in out of box Power BI report after connecting to a VA

### ISSUE THREAD

**Issue by fractalcrafter** [microsoft/botframework-solutions#3126]
https://microsoft.github.io/botframework-solutions/solution-accelerators/tutorials/view-analytics/1-intro/

I followed the tutorial here which connected to the Virtual Assistant analytics template to a VA, but it showed errors in the following  tab:
- User Feedback 
- Conversations Drill Down
- Transcript

![image](https://user-images.githubusercontent.com/25210203/75634193-52d8a680-5bc0-11ea-97eb-6c4dada47250.png)
![image](https://user-images.githubusercontent.com/25210203/75634191-4b190200-5bc0-11ea-9ed4-68f5a74ac2b2.png)

**Comment by jiruss** [comment]
I appear to be running into this issue or at least one very similar. When I open the PowerBI I am getting the following error on the Transcript tab/report.

![vamissingfields](https://user-images.githubusercontent.com/20343098/80225183-b7d8d780-8618-11ea-96a1-253f79e0ef24.png)

I just downloaded the latest pbit from here and it is having the issue: https://microsoft.github.io/botframework-solutions/assets/analytics/virtual-assistant-analytics-sample.pbit

**Comment by VidhyaSanjeevi** [comment]
Issue with type mentioned in power bi query for interactions:

you have to change type value for some of the columns in group by - to text.

Change the query in Power BI advanced editor for interactions to below it will work:
```

let
    Source = #"EventTelemetry",
    #"Added UserUtterance Column" = Table.AddColumn(Source, "UserUtterance", each if [EventName] = "BotMessageReceived" then [Text] else null),
    #"Added UserOriginalUtterance Column" = Table.AddColumn(#"Added UserUtterance Column", "UserOrigUtterance", each if [EventName] = "BotMessageReceived" then [Text] else null),
    #"Added BotMessageSpeakColumn" = Table.AddColumn(#"Added UserOriginalUtterance Column", "BotResponseSpeak", each if [EventName] = "BotMessageSend" then [Speak] else null),
    #"Added OperationID Column" = Table.AddColumn(#"Added BotMessageSpeakColumn", "OperationID", each if [EventName] = "BotMessageSend" then [ReplyActivityId] else [ActivityId]),
    #"Added BotMessageText Column" = Table.AddColumn(#"Added OperationID Column", "BotResponseText", each if [EventName] = "BotMessageSend" then [Text] else null),
    #"Grouped Rows" = Table.Group(#"Added BotMessageText Column", {"OperationID", "ConversationId"}, {{"UserUtterance", each List.Max([UserUtterance]), type text}, {"UserOrigUtterance", each List.Max([UserOrigUtterance]), type text}, {"Time", each List.Min([Time]), type datetimezone}, {"Locale", each List.Max([Locale]), type text}, {"DialogId", each List.Max([DialogId]), type text}, {"DialogStatus", each List.Max([DialogStatus]), type text}, {"DialogStepName", each List.Max([DialogStepName]), type text}, {"DialogInstanceId", each List.Max([DialogInstanceId]), type text}, {"BotResponseSpeak", each List.Max([BotResponseSpeak]), type text}, {"BotResponseText", each List.Max([BotResponseText]), type text}, {"LuisIntent", each List.Max([Luis_Intent]), type text}, {"LuisScore", each List.Max([Luis_IntentScore]), type text}, {"LuisSentimentLabel", each List.Max([Luis_SentimentLabel]), type text}, {"LuisSentimentScore", each List.Max([Luis_SentimentScore]), type text}}),
    #"Changed Type" = Table.TransformColumnTypes(#"Grouped Rows",{{"LuisSentimentScore", type number}})
in
    #"Changed Type"
```


Let me know if it helps someone :)

**Comment by negativeeddy** [comment]
That helps but not all the data is being generated by the default VA template. The content of the conversation messages for the transcripts and conversations drill down is disabled by default. If you want that, you also need to set logPersonalInformation=true in the telemetry middeware.

To enable that, change this line in Startup.cs from this
``` C#
services.AddSingleton<TelemetryLoggerMiddleware>();
```
to this 

``` C#
services.AddSingleton<TelemetryLoggerMiddleware>(s=>new TelemetryLoggerMiddleware(s.GetService<IBotTelemetryClient>(), true));
```

**Comment by darrenj** [comment]
#3428 addresses the above datatype issue introduced by new PowerBI templates. Thanks @SSanjeevi for the pointer!
