### ISSUE TITLE
Default tab for Virtual Assistant Analytics Power BI Template should point to Overall Usage (not Feedback tab)

### ISSUE THREAD

**Issue by fractalcrafter** [microsoft/botframework-solutions#3127]
https://microsoft.github.io/botframework-solutions/solution-accelerators/tutorials/view-analytics/1-intro/

I followed the tutorial here which connected to the Virtual Assistant analytics Power BI template to a VA, but when I opened the template in Power BI Dashboard, it immediately landed in the Feedback tab with an error. We have issue #3126 to track the error in the Feedback tab, but I think we should by default open in the "Overall Usage" tab but not the "Feedback" tab.

**Comment by peterinnesmsft** [comment]
Moving to internal backlog for further tracking.
