### ISSUE TITLE
Design the phone layout for Virtual Assistant Analytics Template

### ISSUE THREAD

**Issue by fractalcrafter** [microsoft/botframework-solutions#3128]
After following the analytics tutorial
https://microsoft.github.io/botframework-solutions/solution-accelerators/tutorials/view-analytics/1-intro/, 
and publish the Power BI dasktop report, it will show a link to recommend optimizing the Power BI report for mobile app. 
https://docs.microsoft.com/en-us/power-bi/desktop-create-phone-report?mobileclient=ios

Following that doc, when I navigate to the Phone layout, it shows empty. The mobile layout for this report will be helpful as many would be interested in accessing their assistant analytics dashboard from mobile apps. 
![image](https://user-images.githubusercontent.com/25210203/75634551-db0c7b00-5bc3-11ea-911c-4e6822285d60.png)

**Comment by peterinnesmsft** [comment]
Moving to internal backlog for further tracking.
