### ISSUE TITLE
[VA] add QnA unit test

### ISSUE THREAD

**Issue by xieofxie** [microsoft/botframework-solutions#3130]
## User Story
As ... a developer
I want ... to unit test QnA
so that ... it work correctly

## Acceptance Criteria 
*List your requirements.*
- [ ] ... unit test QnA in VA

## Resources
*Provide any screenshots or conversation mockups to support your request.*
*Learn how to mock up bot conversations with [.chat files](http://aka.ms/bfchatfile).*

## Notes
*Provide any additional information.*
#3129

**Comment by darrenj** [comment]
Planned in test envrionment testing.
