### ISSUE TITLE
Dispatch refresh issue when running botskills

### ISSUE THREAD

**Issue by darrenj** [microsoft/botframework-solutions#3132]
# Issue 
Customer is running `botskills` to connect a custom skill to their Bot and running into a `shell_integration` error when botskills executes `dispatch refresh`.

Have asked customer to assign themself to this issue and provide an update on CLI versions installed.

# Analysis
![image](https://user-images.githubusercontent.com/33519520/75700725-724bfe00-5caa-11ea-9a69-261eed7a7130.png)

More detailed exception information - seems to point to a shell_integration issue perhaps?
![image](https://user-images.githubusercontent.com/33519520/75700970-d242a480-5caa-11ea-9bc4-7b47b59a509c.png)

**Comment by Batta32** [comment]
@darrenj - can you provide the version of the following libraries in order to validate the error's scenario?
1. Botskills CLI Tool
1. Azure CLI
1. Python

**Comment by jkotiaja** [comment]
Botskills - 1.0.13
Dispatch - 1.6.8
Azure - 2.0.76

**Comment by darrenj** [comment]
Feedback on email that the issue has been resolved.
