### ISSUE TITLE
[Template] disable log personal information by default

### ISSUE THREAD

**Issue by xieofxie** [microsoft/botframework-solutions#3134]
## User Story
As ... a user
I want ... to not break GDPR etc. by accident
so that ... it is good

## Acceptance Criteria 
*List your requirements.*
- [ ] ... disable log personal information by default
- [ ] ... unify the flag

## Resources
*Provide any screenshots or conversation mockups to support your request.*
*Learn how to mock up bot conversations with [.chat files](http://aka.ms/bfchatfile).*

https://github.com/microsoft/botframework-solutions/blob/db272438a89503afc721fd4b5e1f98110edf2c48/samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Services/BotServices.cs#L33

## Notes
*Provide any additional information.*

**Comment by darrenj** [comment]
When we say personal information - all this changes is utterance/userid. This should be the default as the insights it's enabled is key. As for GDPR the customer would make a call on the sensitivity (or not of data) and Log Analytics provides GDPR tooling
