### ISSUE TITLE
Provide a way to specify which intents to include out of an .LU file in the botskills CLI

### ISSUE THREAD

**Issue by marawanshalaby** [microsoft/botframework-solutions#3137]
## User Story
As a user, I want to be able to specify which intents to extract out of an `.lu` file when adding a skill as a dispatch source using `botskills connect`. This functionality is already supported by the `dispatch add` command which is internally being called by the `botskills connect`, but it is not exposed in the interface of `botskills connect`. 

My use case is as follows: I have a skill that I want to connect to, but only consume a limited number of its intents. The skill defines a large number of intents, including Confirm/Cancel/Reject,.... which I don't want to include in my dispatcher. One solution would be to define another `.lu` file with just the intents I want to connect to, but then synchronization between the two `.lu` files would be an issue. 

This picking of intents to extract can be done in one of 2 ways as far as I can see:
- Check which intents are exposed in the manifest
- Add the `--includedIntents` parameter to `botskills connect` and link it to `dispatch add`.

Related Ticket: https://github.com/microsoft/botframework-solutions/issues/2488

**Comment by darrenj** [comment]
Thanks @marawanshalaby 

If you take [this Skill](http://bfcalendarskill.azurewebsites.net/manifest/manifest-1.1.json) as an example. 

Within the intents section we do provide a mapping of what intents are required/needed. @Batta32 could we validate that botskills leverages this collection when deciding which intents to add please? @marawanshalaby would this address your need?

```json
 "intents": {
            "CreateCalendarEntry": "#/activities/message",
            "FindMeetingRoom": "#/activities/message",
            "AcceptEventEntry": "#/activities/message",
            "DeleteCalendarEntry": "#/activities/message",
            "ConnectToMeeting": "#/activities/message",
            "TimeRemaining": "#/activities/message",
            "FindCalendarDetail": "#/activities/message",
            "FindCalendarEntry": "#/activities/message",
            "FindCalendarWhen": "#/activities/message",
            "FindCalendarWhere": "#/activities/message",
            "FindCalendarWho": "#/activities/message",
            "FindDuration": "#/activities/message",
            "ChangeCalendarEntry": "#/activities/message",
            "*": "#/activities/message"
        }
```

**Comment by marawanshalaby** [comment]
@darrenj We had already tried the `botskills connect` with the old manifest schema (the one with the triggers/utteranceSources https://github.com/microsoft/botframework-solutions/blob/90f8ae0de5f8bbe7cbef70419b4a29e7aeccc0e8/templates/csharp/Skill/Skill/manifestTemplate.json), but it didn't work back then. We haven't tried it with the new schema yet. If this now  works with the new schema, then that would be a perfect solution for this issue.

**Comment by Batta32** [comment]
Hi @marawanshalaby, sorry for the delay.
We managed to validate that the last version of [botskills@1.0.14](https://www.npmjs.com/package/botskills/v/1.0.14) **doesn't filter** by the collection of intents specified in the new manifest schema.

We will be implementing this functionality for the new manifest schema and we will communicate the updates in this issue 😊.

**Comment by Batta32** [comment]
@marawanshalaby - there is a **new version** of [botskills@1.0.15](https://www.npmjs.com/package/botskills/v/1.0.15) published which filters by the collection of the intents specified in the new manifest schema 😊.

To install the latest version of the tool execute:
> npm install -g botskills

Finally, we added the `Intent Filtering` section in the [connect](https://github.com/microsoft/botframework-solutions/blob/master/tools/botskills/docs/commands/connect.md#intent-filtering) command document of botskills.

We will be attentive to your answer.

**Comment by darrenj** [comment]
Let us know if you have any further issues with this.
