### ISSUE TITLE
ConnectedService classes are marked obsolete and need to be replaced

### ISSUE THREAD

**Issue by ryanisgrig** [microsoft/botframework-solutions#3139]
#### What project is affected?
Solutions SDK

#### What language is this in?
All

#### What happens?
The `ConnectedService` properties in `CognitiveModelConfiguration` are marked obsolete (except for `LuisService`). These are used for the cognitive model json classes in order for the VA template to work correctly.

I'm following up at microsoft/botbuilder-dotnet#3483 to see if `LuisService` should be obsolete as well. In either case, the Solutions SDK should provide classes that map to the JSON objects for the solution to work as expected.

**Comment by lzc850612** [comment]
It looks like ConnectedService property under CognitiveModelConfiguration class has been removed? do we still have this issue?
