### ISSUE TITLE
I see that the Bing Skill doesn't work, when invoked from Cortana Channel

### ISSUE THREAD

**Issue by AcharyaSubbu** [microsoft/botframework-solutions#3141]
/skills/samples/bing-search

Skill doesn't respond to any questions asked from the Cortana, even thought I am able to invoke the skill. While debugging, found it doesn't touch any break point, not even default activity handler.
Does anyone have any idea what is happening?

**Comment by AcharyaSubbu** [comment]
see that the Bing Skill doesn't work, when invoked from Cortana Channel

**Comment by darrenj** [comment]
Hi,

Can I quickly confirm the scenario. Have you connected an assistant using the Bing Search Skill to the Cortana channel or connected the Bing Search skill directly to the Cortana channel?

Do any exceptions show in the AppInsights log?

**Comment by AcharyaSubbu** [comment]
Hi Darren,

I have connected Bing Search Skill Directly to Cortana. I am able to get the Bing Search Skill work on MS Teams and Bot Emulator, but doesn't work with Cortana. Did not find any exceptions with App Insights either.
Mine is a Enterprise test account. Would that have something to do with this?

**Comment by AcharyaSubbu** [comment]
> Hi,
> 
> Can I quickly confirm the scenario. Have you connected an assistant using the Bing Search Skill to the Cortana channel or connected the Bing Search skill directly to the Cortana channel?
> 
> Do any exceptions show in the AppInsights log?

Hi Darren, 

Thank you for your response.

I have connected Bing Search Skill Directly to Cortana. I am able to get the Bing Search Skill work on MS Teams and Bot Emulator, but doesn't work with Cortana. Did not find any exceptions with App Insights either.
Mine is a Enterprise test account. Would that have something to do with this?

**Comment by anusharr** [comment]
@AcharyaSubbu do you get any issues in the Cortana channel's health tab on Azure? Can you elaborate on the steps or the link to the tutorial you followed to connect Bing Search Skill to Cortana?

**Comment by anusharr** [comment]
Closing the issue. Please feel free to reopen if you still have issues.
