### ISSUE TITLE
BF Skills Cortana Integration

### ISSUE THREAD

**Issue by csnarain** [microsoft/botframework-solutions#3142]
Do BF Skills like Calendar, Email etc., come with Cortana integration out of the box? If not, where can I find documentation for integrating these skills with Cortana? The way these skills are built makes it more temping for a voice conversation than text. Any quick help is much appreciated.

**Comment by csnarain** [comment]
Is there anybody who can help? We're developing this skill for a client and we'd like to impress them with a demo on Cortana integration.

**Comment by csnarain** [comment]
> 
> 
> Do BF Skills like Calendar, Email etc., come with Cortana integration out of the box? If not, where can I find documentation for integrating these skills with Cortana? The way these skills are built makes it more temping for a voice conversation than text. Any quick help is much appreciated.

@xieofxie  - Would you be able to provide some info on this?

**Comment by xieofxie** [comment]
Hi @csnarain, you beat me.. I never tried this before..
You could follow this https://docs.microsoft.com/en-us/cortana/skills/test-debug

**Comment by darrenj** [comment]
There's also been some changes to Cortana's support for Skills announced last week. I don't believe this will be a supported scenario moving forward. If you are seeking to add voice support for your Assistant - we have an android app example that demonstrates this along with a speech test tool to quickly show things working?

**Comment by csnarain** [comment]
@darrenj - That's interesting. Do you have more info about the Android app?

**Comment by csnarain** [comment]
> 
> 
> Hi @csnarain, you beat me.. I never tried this before..
> You could follow this https://docs.microsoft.com/en-us/cortana/skills/test-debug

Thanks @xieofxie. I did check that already but much helpful. In any case thanks for taking a look. I'm always confused with Microsoft's Cortana strategy.

**Comment by darrenj** [comment]
> @darrenj - That's interesting. Do you have more info about the Android app?

https://microsoft.github.io/botframework-solutions/clients-and-channels/clients/virtual-assistant-client/
