### ISSUE TITLE
Incorrect link for Download the Virtual Assistant Client app source code.

### ISSUE THREAD

**Issue by debasisswain2020** [microsoft/botframework-solutions#3143]
/clients-and-channels/clients/virtual-assistant-client/

Try to access the source code of "Virtual Assistant Client app source code".

Download the Virtual Assistant Client app source code.

But the link provided is taking to https://www.microsoft.com/en-in/?ref=aka.

Can you please update  the page with correct link.

**Comment by ryanisgrig** [comment]
Thanks @debasisswain2020, it looks like a typo in that URL. Correct link is https://aka.ms/bfvirtualassistantclient.

**Comment by ryanisgrig** [comment]
Fixed the docs page with correct link. Thank you for reporting!
