### ISSUE TITLE
Adaptive Card Template parsing functionality Changed after switching to 0.8-preview

### ISSUE THREAD

**Issue by DavidStrickland0** [microsoft/botframework-solutions#3144]
Not certain if this got documented anywhere been chasing it for a couple days now not so much a bug with BotFramework.Solution as it is a change with Microsoft.Bot.Builder.LanguageGeneration however given it starts out looking like a BotFrameworkSolution issue figured I'd get it documented here.

Rescently updated my project to use Microsoft.Bot.Solution 0.8 preview.

When I did most of my app broke. Namely things just weren't showing up in the Bot the same way they did before. My Intro Adaptive Card just plain wouldnt show up and other pages wheren't replacing thier content the same way they had before the upgrade.

Pre Upgrade my NewUserIntro Card Looked like this:

```
# NewUserIntroCard
[Activity
    Attachments = {json(NewUserIntroCardJson())}
]

```
post upgrade I had to change it to 

```
# NewUserIntroCard
[Activity
    Attachments = @{json(NewUserIntroCardJson())}
]
```
 Granted it likely should have been thatway all along and I assume its not so much because Bot.Solution changed as much as it is that includes an upgrade of Microsoft.Bot.Builder.LanguageGeneration which is where I assume the change occured. Figured it was worth noting.... Before someone else has to spend a couple days tracking back through thier app to figure it out.

**Comment by DavidStrickland0** [comment]
For what its worth similar change has been made to the text tokens
Pre 0.8 we had
```
            {
              "type": "TextBlock",
              "text": "{Origin}",
              "size": "ExtraLarge",
              "spacing": "None"
            }
```
Post upgrade we have to use
```
            {
              "type": "TextBlock",
              "text": "@{Origin}",
              "size": "ExtraLarge",
              "spacing": "None"
            }
```

**Comment by ryanisgrig** [comment]
Thanks @DavidStrickland0! There's another syntax change we have to make regarding LG that I will track down and update here with a linked issue. Stay tuned.

**Comment by ryanisgrig** [comment]
I don't see doc updates available yet but the new syntax will actually be using `${}` instead of `@{}` per
microsoft/botbuilder-dotnet#3381

**Comment by darrenj** [comment]
@ryanlengel We'll need to make this is documented as part of our known issues / upgrade steps for 1.0

**Comment by ryanisgrig** [comment]
See the release notes for LG at https://github.com/microsoft/BotBuilder-Samples/tree/master/experimental/language-generation#48-preview for breaking changes updating to `v4.8.*`

I'm leaving this open to track as known issue in our docs for the next release.

**Comment by peterinnesmsft** [comment]
I've added to the GA release notes with a link to handling the LG breaking changes. These will be published when we officially release. You can find the changes in the PR I linked above.

Going to close this issue out since I believe this is now ultimately addressed, but feel free to reopen if you think it could be improved.
