### ISSUE TITLE
Command botskills connect --remoteManifest Failed

### ISSUE THREAD

**Issue by igor17400** [microsoft/botframework-solutions#3148]
**####** What project is affected?
Microsoft's Virtual Assistant Sample

#### What language is this in?
C#

#### What happens?
I'm trying to run the following command to add the skill template to an assistant:

botskills connect --remoteManifest "http://<YOUR_SKILL_MANIFEST>.azurewebsites.net/manifest/manifest-1.1.json" --luisFolder "<YOUR-SKILL_PATH>\Deployment\Resources\LU" --languages "en-us" --cs

#### What are the steps to reproduce this issue?
1)Git clone microsoft virtual assistant sample --> https://github.com/microsoft/botframework-solutions/tree/master/samples/csharp/assistants/virtual-assistant/VirtualAssistantSample
2)Git clone microsoft skill sample --> https://github.com/microsoft/botframework-solutions/tree/master/samples/csharp/skill/SkillSample
3) Publish into azure both cloned repositories
4) Update your skill manifest --> https://microsoft.github.io/botframework-solutions/skills/tutorials/create-skill/csharp/5-update-manifest/
5) Try to connect your skill into the virtual assistant. Tutorial: https://microsoft.github.io/botframework-solutions/skills/tutorials/create-skill/csharp/7-add-your-skill/

#### What were you expecting to happen?
To successfully connect the skill into the virtual assistant

#### Can you share any logs, error output, etc.?

```
There was an error while connecting the Skill to the Assistant:
Error: An error ocurred while updating the Dispatch model:
Error: There was an error in the ludown parse command:
Command: ludown parse toluis --in "/Users/igorazevedo/Documents/Estagio/SkillAtendente/Teste/SkillSample/Deployment/Resources/LU/en-us/SkillSample.lu" --luis_culture en-us --out_folder "/Users/igorazevedo/Documents/Estagio/SkillAtendente/Teste/SkillSample/Deployment/Resources/LU/en-us" --out /users/igorazevedo/documents/estagio/skillatendente/teste/skillsample/deployment/resources/lu/en-us/skillsample.luis
Error: The execution of the ludown command failed with the following error:
Unable to write LUIS JSON file - /Users/igorazevedo/Documents/Estagio/SkillAtendente/Teste/SkillSample/Deployment/Resources/LU/en-us/users/igorazevedo/documents/estagio/skillatendente/teste/skillsample/deployment/resources/lu/en-us/skillsample.luis
Stopping further processing. 
```

#### Any screenshots or additional context?
<img width="776" alt="Screen Shot 2020-03-04 at 18 48 44" src="https://user-images.githubusercontent.com/42355184/75926139-c7257b00-5e48-11ea-8c35-1a9d525a52e7.png">

**Comment by csnarain** [comment]
@igor17400 - Could this be permission issue? Can you check if you have permission to write to the target directory mentioned in the error?

**Comment by Batta32** [comment]
Hi @igor17400, thanks for reporting this issue!

We tried to reproduce the scenario you mentioned using the provided `remoteManifest` and we found a differences in the creation of the `ludown parse toluis` command.

Following the documentation of [ludown](https://github.com/microsoft/botbuilder-tools/blob/master/packages/Ludown/docs/commands.md#parse-toluis-command), `--out` argument should be a FILE_NAME and in your screenshot is a PATH.

![image](https://user-images.githubusercontent.com/11904023/75989053-51192680-5ed1-11ea-8069-bf4f309e8321.png)

I need you to give me a full overview of what you're doing in order to figure out what's wrong. Here are some initial questions I'm particularly interested in.
- Which OS are you using?
- Which version of botskills are you using?

**Comment by igor17400** [comment]
Hi @Batta32 and @csnarain  thank you guys for helping me! 

First, I gave writing permissions to all groups and the these error is still happening.

Second. I'm using macOS Catalina version 10.15.3 and my version of botskills is 1.0.14.

**Comment by Batta32** [comment]
Thanks @igor17400! We will be reproducing the issue taking into account the provided information and we will back to you later 😊.

**Comment by Batta32** [comment]
@igor17400, we reproduced the issue with the provided information!
We will check the botskills behavior and get back to you later 😊.

![image](https://user-images.githubusercontent.com/11904023/76094291-25657180-5fa1-11ea-8641-632dd431c1f8.png)

**Comment by Batta32** [comment]
@igor17400, we created PR #3152 solving this issue.

You can validate the PR using botskills locally following these steps and using this [branch](https://github.com/microsoft/botframework-solutions/tree/feature/southworks/fix/connect-mac-issue):
1. Open a terminal and go to the [Botskills](https://github.com/microsoft/botframework-solutions/tree/feature/southworks/fix/connect-mac-issue/tools/botskills) folder
1. Install the dependencies executing `npm install`
1. Build the solution executing `npm run build` 
1. Link the local botskills executing `npm link`. If you have already installed botskills, you should uninstall it executing `npm uninstall -g botskills`
1. Go to your Virtual Assistant Sample
1. Execute botskills connect command
> botskills connect --remoteManifest http://skillsampletest-s3wpno5.azurewebsites.net/manifest/manifest-1.1.json --luisFolder <PATH_LUIS_FOLDER> --languages "en-us" --cs
7. Check that the connect command finished correctly

**Comment by igor17400** [comment]
Hi @Batta32, the link -->  https://github.com/microsoft/botframework-solutions/tree/feature/southworks/fix/connect-mac-issue  is resulting in 404-Page not found. Is something wrong with this link?

**Comment by Batta32** [comment]
Hi @igor17400, as the PR #3152 was merged, the branch was removed. However, you can use [master](https://github.com/microsoft/botframework-solutions) branch and follow the steps specified above 😊.

**Comment by igor17400** [comment]
Ok! Thank you for the support @Batta32! 😊
