### ISSUE TITLE
Unable to connect skill to VA with botskills connect command

### ISSUE THREAD

**Issue by mlipinski** [microsoft/botframework-solutions#3153]
#### What project is affected?
Virtual Assistant and ITSM skill
#### What language is this in?
C#
#### What happens?

I get an undefined:23 },

SyntaxError:  Unexpected token } in JSON at position 943 error

#### What are the steps to reproduce this issue?

Deploy the latest Virtual Assistant and run the following:

botskills connect --remoteManifest "http ://itsmbotskill2020-yoww4ys.azurewebsites.net/manifest/manifest-1.1.   json" --cs

#### What were you expecting to happen?

Was expecting the VA to add the ITSM skill

#### Can you share any logs, error output, etc.?
sure
#### Any screenshots or additional context?
![image](https://user-images.githubusercontent.com/5796298/76120151-e219fb80-5fbe-11ea-881b-cef4ed1fc24a.png)

**Comment by xieofxie** [comment]
Hi, @mlipinski I checked botskills-connect.js:97 and it seems that your appsettings.json for VA is broken
![image](https://user-images.githubusercontent.com/2876650/76184164-cd7b7480-6205-11ea-8ef7-1fec99273656.png)
You should verify if is in UTF-8 format etc.

Also after it is good, you will meet the following error:
`Error: Path to the LU file (*\ITSM.lu) leads to a nonexistent file.`

You should add the following:`
--luisFolder path_to_botframework-solutions\skills\csharp\experimental\itsmskill\Deployment\Resources\LU`

**Comment by mlipinski** [comment]
xieofxie,

I was looking at the latest documentation and it seems to say that you no longer need the --luisFolder to the connect command is that the case or not?

I will double check the the utf format but I swear it was already utf8.

Matt...

**Comment by mlipinski** [comment]
appsettings.json, I was looking at the manifest.json for the utf8.

**Comment by mlipinski** [comment]
Still getting same error and the appsettings.json in the VA solution is UTF-8.

**Comment by dfavretto** [comment]
Hi @mlipinski! Could you share your `appsettings.json` file? **Please be careful** not to share private keys, you can just replace them with `X`.

Also, regarding the `--luisFolder` parameter, it was never mandatory, but [you can still use it](https://github.com/microsoft/botframework-solutions/blob/master/docs/_docs/skills/handbook/add-skills-to-a-virtual-assistant.md#adding-skills-to-your-virtual-assistant) ([connect documentation](https://github.com/microsoft/botframework-solutions/blob/master/tools/botskills/docs/commands/connect.md#options)).

**Comment by mlipinski** [comment]
I am going to close the issue, I figured out what the issue was.  One question for you, if I have provisioned Azure resources because of deploying a previous version of the Virtual Assistant Template but now want to create a new Virtual Assistant template within Visual Studio but want to leverage my existing Azure Resources, is there a PowerShell script or a NPM command I can use to let the new VA leverage the existing Azure resources rather than redeploying them?  This is actually what caused my issue.

**Comment by Batta32** [comment]
Hi @mlipinski, you can **move** the filled `appsettings.json` and `cognitivemodels.json` to your new Virtual Assistant in order to re-use the resources and avoid to re-deploy.

I will close this issue because you mentioned that you solved it. Please, don't hesitate to open a new issue if you find any other problem 😊.

**Comment by mlipinski** [comment]
I did that and when I did I got the error I submitted until I copied over a folder from my old VA to the new one. It takes more than those two files to run the connect skills command from the new VA template.

**Comment by Batta32** [comment]
You are right, the `appsettings.json`, `cognitivemodels.json` and the `.dispatch` file of the Dispatch folder are mandatory to execute Botskills connect. You can find the .dispatch file in `deployment/resources/Dispatch/<LOCALE>/<BOT_NAME>.dispatch`
