### ISSUE TITLE
Support for 3rd party skills

### ISSUE THREAD

**Issue by csnarain** [microsoft/botframework-solutions#3155]
I understand that Is there any planned support for skills from vendors? For eg., if I have an IBM Watson bot, can I integrate it with a Virtual Assistant hosted on Azure? I can currently host a normal bot in IBM cloud and register the same with Azure. I'd like to know if the same things can be done with skills as well.

**Comment by xieofxie** [comment]
Hi @csnarain I'm not sure if we have a plan for this. But you could use a dialog to do so if you have:
* utterances for that skill for dispatcher
* if it is a multi-turn skill, a flag for end of conversation and ability to active cancel the conversation

**Comment by darrenj** [comment]
Thanks both - yes, provided there is an API that enables you to exchange messages and crucially know when the remote party has finished the conversation you can integrate this as a form of skill. I know some customers have done this using Watson - and as @xieofxie mentions you'll also need some example trigger utterances so VA knows when to hand off to that skill.

If you can prototype sending/receiving messages to a Watson Bot you could then write a simple custom dialog that passes these messages onto the remote party and uses state for any state you need to maintain across turns.

Does that help?
