### ISSUE TITLE
[Docs] How do I convert an existing v4 Bot to a Bot Framework Skill?

### ISSUE THREAD

**Issue by nebhagat** [microsoft/botframework-solutions#3156]
/help/faq/

Hi,

Can you please update the answer for FAQ "How do I convert an existing v4 Bot to a Bot Framework Skill?". It redirects to the doc about the other way round ("enable Bot Framework Skills on an existing v4 Bot").

**Comment by ryanisgrig** [comment]
Hi @nebhagat, can you clarify the specific URL it redirects to? For me it goes to https://docs.microsoft.com/en-us/azure/bot-service/skill-implement-skill?view=azure-bot-service-4.0&tabs=cs which would be correct in showing you how to enable skill support on an existing bot.

**Comment by nebhagat** [comment]
Hi @ryanlengel ,

The document it redirects to actually talks about 
1] Echo skill bot (a skill) and 
2] simple root bot (v4 bot which consumes a skill). 

It has information about how a v4 bot can consume a skill. There are framework libraries `SkillHttpClient` which can perform the same. But the documentation does not give clear idea on how an existing v4 bot can be converted to a skill. (a skill which consumes an existing v4 bot).

I actually want to plug multiple existing v4 bots to a Virtual Assistant bot. In order to achieve it, I need to convert existing v4 bots to skills. 

Thanks!

**Comment by ryanisgrig** [comment]
Got it @nebhagat! For starters, you can observe the differences between a normal echo bot and a skill echo bot, then apply the same to our own v4 bot. I think the changes highlighted [here](https://docs.microsoft.com/en-us/azure/bot-service/skill-implement-skill?view=azure-bot-service-4.0&tabs=cs#application-configuration) would be a good start.

Can you please submit this feedback on the bottom of the [official docs page](https://docs.microsoft.com/en-us/azure/bot-service/skill-implement-skill?view=azure-bot-service-4.0&tabs=cs)? Our intention is to direct that frequently asked question to the proper source.
![image](https://user-images.githubusercontent.com/43043272/76467950-06ebe580-63a8-11ea-976e-c3eb2fffd17c.png)
