### ISSUE TITLE
[Power BI] Show all possible dialogs when choosing

### ISSUE THREAD

**Issue by xieofxie** [microsoft/botframework-solutions#3157]
## User Story
As ... a virtual-assistant-analytics-sample user
I want ... to it is easy to use
so that ... it is easy

## Acceptance Criteria 
*List your requirements.*
- [ ] ... Show all dialogs in  Dialog Overview tab, Conversations Drill Down tab

![image](https://user-images.githubusercontent.com/2876650/76195811-1510f900-6224-11ea-9f3c-e741e79d43a7.png)

## Resources
*Provide any screenshots or conversation mockups to support your request.*
*Learn how to mock up bot conversations with [.chat files](http://aka.ms/bfchatfile).*

Use EnvetTelemetry.DialogId instead of Interactions since it will be only the List.Max one.

## Notes
*Provide any additional information.*

It is sad that PowerBi can't be versioned in text

**Comment by ryanisgrig** [comment]
Hi @xieofxie, will there be additional Power BI issues filed? If so, I'd suggest making a master issue that can help us track all of the Power BI suggestions. Then we can better coordinate with the upcoming analytics work being done in the SDK. @elaine-chang what do you think?

**Comment by peterinnesmsft** [comment]
Moving to internal backlog for further tracking.
