### ISSUE TITLE
ARM template seems to be invalid when using the deployment script to deploy the assistant?

### ISSUE THREAD

**Issue by GiorgioJ** [microsoft/botframework-solutions#3161]
#### What project is affected?
Virtual assistant 

#### What language is this in?
TypeScript

#### What happens?
When running the deployment of the needed resources using the ARM template an error message pops up with the message 'The template deployment 'deployment_dry_run' is not valid according to the validation procedure'.

#### What are the steps to reproduce this issue?
Following [this ](https://microsoft.github.io/botframework-solutions/virtual-assistant/tutorials/create-assistant/typescript/4-provision-you-azure-resources/) guide.

1. pwsh -File .\deployment\scripts\deploy.ps1
2. complete prompts

#### What were you expecting to happen?
Having the resource group completed according to the template. 

#### Can you share any logs, error output, etc.?
Error message:
`{'additional_properties': {}, 'code': 'InvalidTemplateDeployment', 'message': "The template deployment 'deployment_dry_run' is not valid according to the validation procedure. The tracking id is '5c12b860-c6dc-450e-b461-98ea5de98816'. See inner errors for details.", 'target': None, 'details': [<azure.mgmt.resource.resources.v2019_07_01.models._models.ErrorResponse object at 0x0529AA10>], 'additional_info': None}`

deploy_log.txt
ERROR: Deployment '03102020103532' could not be found.

**Comment by ryanisgrig** [comment]
Assigning to support.

**Comment by dmvtech** [comment]
Hi @19George97

Can you please ensure that you have the most recent version of AZ CLI? 

Also, you are creating the VA from the yeoman package, correct? Or are you using the [sample from the repo](https://github.com/microsoft/botframework-solutions/blob/master/templates/typescript/samples/sample-assistant/)?

If using yeoman, can you please confirm the version of the package:
`npm -v generator-botbuilder-assistant`

**Comment by GiorgioJ** [comment]
> Hi @19George97
> 
> Can you please ensure that you have the most recent version of AZ CLI?
> 
> Also, you are creating the VA from the yeoman package, correct? Or are you using the [sample from the repo](https://github.com/microsoft/botframework-solutions/blob/master/templates/typescript/samples/sample-assistant/)?
> 
> If using yeoman, can you please confirm the version of the package:
> `npm -v generator-botbuilder-assistant`

@dmvtech 

I am using the lastest version of the AZ CLI indeed: 2.2.0

I am creating the virtual assistant following the typescript tutorial [ steps here](https://microsoft.github.io/botframework-solutions/virtual-assistant/tutorials/create-assistant/typescript/3-create-project/). 

using version 6.13.4 of the generator (using yeoman indeed)

Also relevant to mention: When using the C# tutorial, the provisioning of the resources through the deploy script (ARM templates) works fine.

**Comment by dmvtech** [comment]
Thanks. Seeing if i can reproduce.

**Comment by dmvtech** [comment]
Just touching base. I **_am_** able to reproduce this. Investigating.

**Comment by dmvtech** [comment]
Hi @19George97 

So, this is an issue with using the newer version of the CLI (`2.2.0`). There were commands that were deprecated and we are working to get changes to the script in a release coming soon. 

For now, the options you can use are:
1) use an older cli version (`2.0.n`). You might have to use the C# version of the deployment scripts/templates. See [here](https://github.com/microsoft/botframework-solutions/tree/master/samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Deployment).
2) provision the resources 'by hand' (either with cli or UI).  See [here](url).

Thank you for bringing this to our attention.
