### ISSUE TITLE
End of Skill Conversation not handled by VA

### ISSUE THREAD

**Issue by manish-95** [microsoft/botframework-solutions#3162]
#### What project is affected?
VA, Skills 

#### What language is this in?
C# SDK Bot Builder SDK 4.7.2,  Bot.Solutions 0.8 preview, Beta 0.8 Release

#### What happens?
When a skill dialog is completed successfully, the EndOfConversation activity sent by the Skill has not been handled anywhere in the VA bot. As a result, the bot remains in skill context and is unable to process requests for Chitchat, QnA, etc.

#### What are the steps to reproduce this issue?
1. Deploy a VA Bot.
2. Deploy a Skill Bot
3. Connect the two bots.
4. Trigger a conversation belonging to the Skill Bot.
5. On end of the conversation, type a General/Chitchat command. The response from the VA is of the confused message from the Skill dialog context.

#### What were you expecting to happen?
The VA bot should be able to process the end of conversation activity received from the skill, and pass the control back to the MainDialog of the VA.

#### Any screenshots or additional context?
![image](https://user-images.githubusercontent.com/29098159/76304842-1278d700-62ea-11ea-9cf1-c00c004223b9.png)

**Comment by ryanisgrig** [comment]
Hi @manish-95,

Based on the screenshot it appears that you are testing against the Calendar Skill correct? Have you tried any other Skills, like the SkillSample template? This can help narrow down if it is bot-specific or in the library.

Adding @lzc850612 for awareness

**Comment by manish-95** [comment]
Hi @ryanlengel ,
Yes, I have connected the Calendar, Email and the Skill  Sample. I run into the same issue, in all cases

**Comment by ryanisgrig** [comment]
@xieofxie is this related to the new issue filed #3180?

**Comment by xieofxie** [comment]
@ryanlengel no, my issue is for the new Solution library and SDK.

Since we are going to release, maybe we should wait a little. It is hard to tell whether SDK 4.7.2 and Bot.Solutions 0.8 preview match or not.

**Comment by manish-95** [comment]
@xieofxie @ryanlengel, any new updates on this issue? It would be helpful if a workaround is provided for this situation.

**Comment by xieofxie** [comment]
@manish-95 Oh, here https://github.com/microsoft/botframework-solutions/pull/2972 I think it is the fix you should apply.

I guess your VA is created from VS extension? We often test against code in this repo, so sometimes the fix is applied without updating to VS extension

**Comment by manish-95** [comment]
@xieofxie I've already applied this fix. It did not help. I was unable to get the end of conversation even after applying this.

**Comment by xieofxie** [comment]
Hi @manish-95 I tested VA sample https://github.com/microsoft/botframework-solutions/tree/master/samples/csharp/assistants/virtual-assistant/VirtualAssistantSample and skill sample https://github.com/microsoft/botframework-solutions/tree/master/samples/csharp/skill/SkillSample from the master branch and they work fine. You could use some version software like git and then compare the difference between your codes and ones in this repo. Thanks

**Comment by manish-95** [comment]
@xieofxie I've compared the repo code and my own code. They're the same. Having run the solution again, I still do not see the endOfConversation. Attaching a screenshot below
![image](https://user-images.githubusercontent.com/29098159/76760429-a5ff4b80-67b3-11ea-9525-700de61dcc80.png)

**Comment by xieofxie** [comment]
@manish-95 that's weird.. I tried VA & calendar in master and it is fine.

How about copy your appsettings.json & cognitivemodels.json to VA & calendar in this project directly to see if they will work?
In this way, you only need to modify DispatchLuis.cs of VA. And you also could run them both locally to debug

**Comment by manish-95** [comment]
@xieofxie I tried again on the deployed version of my bot with the changes you had previously suggested, and it seems to work, however, I do not see it working locally.

**Comment by xieofxie** [comment]
@manish-95 Do you set skillHostEndpoint correctly when local? https://microsoft.github.io/botframework-solutions/help/known-issues/

**Comment by manish-95** [comment]
@xieofxie Yes, it was an issue with the skillHostEndpoint. My issue seems to be resolved. 
Thanks for your help!
