### ISSUE TITLE
[SDK] incorrect test case GetResponseWithLanguageGeneration_Spanish?

### ISSUE THREAD

**Issue by xieofxie** [microsoft/botframework-solutions#3170]
#### What project is affected?
Solutions SDK
#### What language is this in?
C#
#### What happens?
In this line https://github.com/microsoft/botframework-solutions/blob/6c45f643718df6b2b52593e1792ab50f7c8bad0e/sdk/csharp/tests/microsoft.bot.solutions.tests/Responses/LanguageGenerationTests.cs#L64

It should be es-es instead of en-us? Since we have es-es in Setup
#### Any screenshots or additional context?
This line should be fixed https://github.com/microsoft/botframework-solutions/blob/6c45f643718df6b2b52593e1792ab50f7c8bad0e/sdk/csharp/libraries/microsoft.bot.solutions/Responses/LocaleTemplateManager.cs#L50

But even if we switch order, it is not a real fallback as we don't check if it is in the keys of localeTemplateFiles. Maybe we should wait until bot sdk's fallback is published

**Comment by lzc850612** [comment]
I've got PR fixing the test

for the second point, the Generate function internally maintains all combination of fallback chains so we don't have to check. Guarding logic is in the SDK level.
