### ISSUE TITLE
[Docs] secure connection issue

### ISSUE THREAD

**Issue by niravmadariya** [microsoft/botframework-solutions#3171]
/docs/_includes/header.html - file which has issue.
has a search box which has below code,
`<form ... action="http://bing.com/search" ...>`
Note the URL, it should be "https://bing.com/search".

Url as "http" makes the browser remove green lock sign on the page, in this case it's every page because this header file is being used in every page.

**Comment by ryanisgrig** [comment]
Thanks @niravmadariya, we will take care of this!
