### ISSUE TITLE
Move Microsoft.Bot.Solutions.Responses.ICardData to the SkillServiceLibrary

### ISSUE THREAD

**Issue by WizX20** [microsoft/botframework-solutions#3183]
## User Story
Currently the SkillServiceLibrary has a refrence to the Microsoft.Bot.Solutions package, just because it uses the (empty) Microsoft.Bot.Solutions.Responses.ICardData interface. I would suggest moving the ICardData interface to the SkillServiceLibrary.

**Comment by lzc850612** [comment]
Good point. Will investigate on changes needed for this. Thanks.

**Comment by lzc850612** [comment]
This class is used by LocaleTemplateManager which cannot be remove/deprecated at this point. We're waiting on an implementation of what this class does as part of SDK so we can deprecate it. When that happens we can then deprecate ICardData and related classes

**Comment by darrenj** [comment]
Skill Service Library removed so no longer an issue. CardData can be deprecated and will be done shortly.
