### ISSUE TITLE
Feature Request: Make Microsoft.Bot.Solutions.BotSettingsBase overridable

### ISSUE THREAD

**Issue by WizX20** [microsoft/botframework-solutions#3186]
## User Story
As a developer I want to use the virtual assistant with docker containers; for example the new [LUIS docker container](https://docs.microsoft.com/en-us/azure/cognitive-services/luis/luis-container-howto?tabs=v3).

This is currently not possible with the OOTB `Microsoft.Bot.Solutions.BotSettingsBase` class for configuration. It a `CognitiveModelConfiguration` class that contains a `public List<LuisService> LanguageModels` property. The `Microsoft.Bot.Configuration.LuisService` class has a `GetEndpoint` method that builds the endpoint based on the configuration settings. This method makes it impossible to connect to a custom endpoint, like for example `localhost:5000`. In order to do so we need to add our own LUIS service class with, for example the property:
```
[JsonProperty("endpoint")]
public string Endpoint { get; set; }
```

We then need a custom `GetEndpoint` implementation that checks the property first:
```
if (!string.IsNullOrEmpty(this.Endpoint))
{
  return this.Endpoint;
}
```

In `MyBotSettingsBase.cs` we could use our own LUIS configuration model:
```
public class CognitiveModelConfiguration
{
  public DispatchService DispatchModel { get; set; }
  public List<OURCUSTOM_LuisService> LanguageModels { get; set; }
  public List<QnAMakerService> Knowledgebases { get; set; }
}
```

Finally we can now use the endpoint in our configuration for example:
```
"luis": {
    "appId": "aaa-aaa",
    "version": "0.1",
    "endpoint":  "http://localhost:5000",
    "region": "local",
    "authoringKey": "",
    "authoringRegion": "local"
  },
```

## Acceptance Criteria 
*List your requirements.*
- [ ] Possibility to extend/override/inherit the BotSettingsBase class
- [ ] Optionally, possibility to extend/override/inherit the LuisService class

**Comment by lzc850612** [comment]
So if we added the extra property and the extra logic on top of LuisService class, we don't have the guarantee that the internals of the LuisService class would always rely on GetEndpoint method to get the endpoint, because it's a Get only method. Essentially LuisService doesn't allow us to Set so us adding the Set logic is not going to be reliable. I would suggest opening a ticket to SDK to ask for support of being able to specify a custom endpoint for LUIS.

**Comment by lzc850612** [comment]
In the meantime you can also create your own class that inherits from LuisService and define everything you mentioned in the ticket and load that class with the luis configuration settings. We couldn't include it in Microsoft.Bot.Solutions lib as it will not reliable.

**Comment by WizX20** [comment]
> So if we added the extra property and the extra logic on top of LuisService class, we don't have the guarantee that the internals of the LuisService class would always rely on GetEndpoint method to get the endpoint, because it's a Get only method. Essentially LuisService doesn't allow us to Set so us adding the Set logic is not going to be reliable. I would suggest opening a ticket to SDK to ask for support of being able to specify a custom endpoint for LUIS.

Created a feature request at the SDK team/repo: [Add a custom endpoint property to the LuisService class](https://github.com/microsoft/botbuilder-dotnet/issues/3583)

**Comment by lauren-mills** [comment]
Closing this issue since it has been raised to the SDK team.
