### ISSUE TITLE
Calendar Skill meeting room booking issue - Error Communicating with AD

### ISSUE THREAD

**Issue by gagankohli2000** [microsoft/botframework-solutions#3187]
#### What project is affected?
Calendar Skill meeting room booking issue

#### What language is this in?
#

#### What happens?

Here is log of enable_findmeetingroom_log

[91mInvoke-RestMethod: \Deployment\Scripts\msgraph_functions.ps1:40
[96mLine |
[96m  40 | [0m    $result = [96mInvoke-RestMethod -Uri $url -Headers $headers[0m
[96m     | [91m              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[91m[96m     | [91m{   "error": {     "code": "UnknownError",     "message": "Error Communicating with AD.",     "innerError": {       "request-id": "ed1f1e08-321c-42e8-a630-06a5a9bc9fc1",
[96m     | [91m"date": "2020-03-13T09:23:32"     }   } }
[0m

**Comment by gagankohli2000** [comment]
It seems to be issue with Graph API. 
Below API works fine
https://graph.microsoft.com/beta/me/findrooms
![API1](https://user-images.githubusercontent.com/14933211/76697224-c4e4db80-66e8-11ea-8720-85703f09aec4.PNG)

But i noticed msgraph_functions.ps1 is using beta version https://graph.microsoft.com/beta/places/microsoft.graph.room which is causing error
![API2](https://user-images.githubusercontent.com/14933211/76697252-0d03fe00-66e9-11ea-9936-29631d7a87d4.PNG)

**Comment by lzc850612** [comment]
Hi,

Can you clarify the detailed steps of reproducing this issue? And can you confirm if you are still experiencing this issue after your last comment/update?

Thanks.

**Comment by darrenj** [comment]
Please see updated documentation in the above Pull Request

**Comment by gagankohli2000** [comment]
@darrenj Graph API https://graph.microsoft.com/beta/places/microsoft.graph.room is not working on our production tenant. Not sure if it's enabled on tenant as this is still in beta. This is where the powershell script is failing.

I'm getting same error when i manually execute Graph API in explorer. I have all the permissions.

**Comment by gagankohli2000** [comment]
Update both the files but still getting same error 

ERROR: Deployment failed. Correlation ID: caa8cbe3-fa97-4127-a22b-f91d86cc2929. {

  "error": {

    "code": "ServiceNameUnavailable",

    "message": "Cannot provision service 'calendarskill-bavmlvv' because a service with this name is already in use, or another request to provision a service with this name is still in progress RequestId: 46efc92e-f56c-4c67-9b82-474dec1a9a93",

    "target": null,

    "details": null

  }

}

[91mInvoke-RestMethod: [0mD:\NABBOTv8\calendarskill\Deployment\Scripts\msgraph_functions.ps1:40
[96mLine |
[96m  40 | [0m    $result = [96mInvoke-RestMethod -Uri $url -Headers $headers[0m
[96m     | [91m              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[91m[96m     | [91m{   "error": {     "code": "UnknownError",     "message": "Error Communicating with AD.",    
[96m     | [91m"innerError": {       "request-id": "0e311405-bdcb-4ebe-9eec-879d7d830ea9",       "date":
[96m     | [91m"2020-03-17T22:34:47"     }   } }

**Comment by xhr0804** [comment]
@gagankohli2000 Hi, have you resolved this problem? I opened a issue to the ms-graph https://github.com/microsoftgraph/microsoft-graph-docs-contrib/issues/5679. They said that they recently updated the code and suggested to retry.
If still getting the same error, feel free to give feedback in that issue direcly.

**Comment by peterinnesmsft** [comment]
No response in almost four weeks, so closing out issue. @gagankohli2000 if you are still experiencing issues and there is something we can actively help you with, feel free to reactivate and we can reengage as necessary.
