### ISSUE TITLE
Skill Manifest Validation issue 

### ISSUE THREAD

**Issue by VladPapacostea-SM** [microsoft/botframework-solutions#3188]
#### What project is affected?
Botskills tool 
#### What language is this in?
Javascript/Typescript 
#### What happens?
The regex on this [line](https://github.com/microsoft/botframework-solutions/blob/5b5328f6329e3f436249454014d15193052edd92/tools/botskills/src/utils/validationUtils.ts#L58) is case sensitive, allowing uppercase characters in the URL only if they are between A-F (inclusive). Anything G-Z in uppercase will cause the command to fail. 

#### What are the steps to reproduce this issue?
https://test-dev.azurewebsites.net/....manifest path...   will work fine 
https://Test-dev.azurewebsites.net/...manifest path.... will fail 
https://test-Stage.azurewebsites.net/...manifest path... will fail 

etc
#### What were you expecting to happen?
Should allow any valid app service name to be part of a manifest url ( so, case invariant ?)
#### Can you share any logs, error output, etc.?
N/A
#### Any screenshots or additional context?
N/A

**Comment by Batta32** [comment]
Thanks @VladPapacostea-SM for reporting this issue! We will be checking it and we will back to you later 😊.

**Comment by DiegoCardozo94** [comment]
@VladPapacostea-SM, we **created** the following PR #3209 which fixes the validation.

Follow these **steps** to validate these changes and using this [branch](https://github.com/microsoft/botframework-solutions/tree/feature/southworks/botskills/fix-regexp-validation):
1. Open a terminal and go to the [Botskills](https://github.com/microsoft/botframework-solutions/tree/feature/southworks/botskills/fix-regexp-validation/tools/botskills) folder
1. Install the dependencies executing `npm install`
1. Build the solution executing `npm run build` 
1. If you have already installed Botskills, you should uninstall it executing `npm uninstall -g botskills`
1. Link the local Botskills executing `npm link`
1. Go to your Virtual Assistant Sample folder
1. Execute Botskills connect command
1. Check that the connect command finished correctly

If you have any feedback, don't hesitate to comment it in the PR 😊.

**Comment by VladPapacostea-SM** [comment]
Hey @DiegoCardozo94, @Batta32 
I just had a look at the PR now and it seems like it will solve the issue I was encountering. Thanks guys
