### ISSUE TITLE
Switching Between VA (QnA model) and Skill not working

### ISSUE THREAD

**Issue by gagankohli2000** [microsoft/botframework-solutions#3191]
#### What project is affected?
Virtual Assistant with QnA and Bot Skill ITSM and Calendar

#### What language is this in?
c#
#### What happens?
QnA works fine but when i switch over to ITSM or Calendar Skill it doesn't return back to QnA model.
How to get back to QnA from Skill?

**Comment by xieofxie** [comment]
I guess your VA is created from vs extension. Here is the possible fix https://github.com/microsoft/botframework-solutions/pull/2972

**Comment by gagankohli2000** [comment]
I'm using release v8 sample VA and skills. Let me know what changes i need to make.

**Comment by xieofxie** [comment]
Hi @gagankohli2000 I tested VA sample https://github.com/microsoft/botframework-solutions/tree/master/samples/csharp/assistants/virtual-assistant/VirtualAssistantSample and ITSM skill https://github.com/microsoft/botframework-solutions/tree/master/skills/csharp/experimental/itsmskill from the master branch and they work fine. You could use some version software like git and then compare the difference between your codes and ones in this repo. Thanks

**Comment by peterinnesmsft** [comment]
Per @xieofxie this appears to be No Repro, so closing out issue. @gagankohli2000 if you need more explicit help for this issue, please reactivate and we can take it from there.
