### ISSUE TITLE
Adaptive Cards are not working in Teams

### ISSUE THREAD

**Issue by gagankohli2000** [microsoft/botframework-solutions#3193]
#### What project is affected?
VA, Calendar Skill, ITSM

#### What language is this in?
c#
#### What happens?
Adaptive Cards are not rendering in Teams

#### What are the steps to reproduce this issue?
Please see attached screenshot
![AdaptiveCard](https://user-images.githubusercontent.com/14933211/76753956-6f3a2d00-67d5-11ea-8194-9e9dca7cd099.PNG)

**Comment by xieofxie** [comment]
Hi @gagankohli2000, please see comments at the end of  https://github.com/microsoft/botframework-solutions/issues/3065

**Comment by peterinnesmsft** [comment]
Sounds like #3605 offers guidance on this issue. Given no updates since March 23rd, going to close this issue out. @gagankohli2000 if you need further assistance, then feel free to reactivate and we can engage.
