### ISSUE TITLE
Remove ArgumentException from SkillDialog constructor on _botId

### ISSUE THREAD

**Issue by WizX20** [microsoft/botframework-solutions#3198]
## User Story
As a developer I want to developer locally using docker containers with the Virtual Assistant.
I want the _.Developer_ configuration files to have empty values for the *microsoftAppId* and *microsoftAppPassword* settings for easy testing with the bot framework emulator.

With the default *Microsoft.Bot.Solutions.Skills.SkillDialog* this is currently not possible. [It will crash the application on an empty *microsoftAppId*](https://github.com/microsoft/botframework-solutions/blob/5b46d73e220bbb4fba86c48be532e495535ca78a/sdk/csharp/libraries/microsoft.bot.solutions/Skills/SkillDialog.cs#L45) .

## Notes
*Provide any additional information.*
To be honest I wonder what the private *_botId* property is currently used for? It seems to me like it is set in constructor, but it is never used.

**Comment by lzc850612** [comment]
In the upcoming release (end of month) we'll remove SkillDialog from Microsoft.Bot.Solutions lib and use the one from the SDK that's about to release. Moving forward please go to https://github.com/microsoft/botframework-sdk to open up an issue to track this.

**Comment by WizX20** [comment]
Clear. Is there an upgrade path?

**Comment by lzc850612** [comment]
We would be providing documentation to clearly describe how to upgrade.
