### ISSUE TITLE
Switching from Calendar skill to ITSM gives error instead of login prompt

### ISSUE THREAD

**Issue by gagankohli2000** [microsoft/botframework-solutions#3205]
#### What project is affected?
VA, Calendar and ITSM

#### What language is this in?
c#
#### What happens?
When i switch from Calendar to ITSM it's not prompting me for login rather give error "Your log in failed. Let's try this again."

![error_teams](https://user-images.githubusercontent.com/14933211/76855338-0621ea80-68a5-11ea-8d81-cef07d841024.PNG)

**Comment by lzc850612** [comment]
Can you tell me what version of VA, Calendar skill and ITSM skill are you using?

Thanks.

**Comment by gagankohli2000** [comment]
I'm using v8 version release code.

**Comment by gagankohli2000** [comment]
@lzc850612 Any idea why we are not getting login prompt? It's working fine in Bot emulator.
Also, directly running in teams works fine but if i run via VA or web chat i get login failure error.

![error-itsm](https://user-images.githubusercontent.com/14933211/77139891-d4d73380-6acb-11ea-994c-6b89a759368f.PNG)

**Comment by Lippy1m1** [comment]
I have seen the same thing using ServiceNow and token auth, when I type "log out" from inside the itsmskill bot, it stops using an old token and reprompts for a new login.

**Comment by gagankohli2000** [comment]
@lzc850612 - Have we found solution for this issue?

**Comment by lzc850612** [comment]
@sidmore  will take a look at this issue.

**Comment by peterinnesmsft** [comment]
Spoke offline with @sidmore - we will be targeting end of this week for resolution of this issue.

**Comment by Lippy1m1** [comment]
Any thought of adding the ITSM login to the SSO enterprise webchat also?

**Comment by sidmore** [comment]
@gagankohli2000: Can you kindly please point me to your repo if its on git? I tried with the latest bits in **botframework-solutions** repo and have not been able to repro the issue.

Any additional information you can provide will be very helpful.

I have tried below scenarios:
1. Calendar to ServiceNow workflow (Emulator, Teams)
a. Invoke calendar intent "accept my meeting"
b. Login into CalendarSkill
c. Complete intent
d. Invoke ITSM skill intent "create ticket"
e. Was prompted to login to "ServiceNow"
f. Create new ticket

2. ServiceNow to Calendar workflow (Emulator, Teams)
a. Invoke ITSM skill intent "create ticket"
b. Login to "ServiceNow" 
c. Create new ticket
d. Invoke CalendarSkill intent "accept my meeting"
e. Complete CalendarSkill intent

3. ITSMSkill Webchat 
a. Invoke ITSM skill intent "create ticket"
b. Login to "ServiceNow"
c. Create ticket
d. Logout
e. Invoke ITSM skill intent "create ticket"
f. Verified i got Login prompt

**Comment by Lippy1m1** [comment]
sidmore,

The issue appears when the token has expired after you log into the Service Now.  Not sure how long you have the tokens expiring but set the expiration really short say 5 minutes.  Never type log out and attempt to do other actions requiring authentication.

try this scenario.

a. Invoke ITSM skill intent "create ticket"
b. Login to "ServiceNow"
c. Create new ticket
d. allow ServiceNow authentication token to expire.
d. Invoke CalendarSkill intent "accept my meeting"
e. Complete CalendarSkill intent

**Comment by sidmore** [comment]
@Lippy1m1 Sounds great. That is a good point on letting token expire. I will update this thread with my findings based on what @Lippy1m1  mentioned.

**Comment by Lippy1m1** [comment]
Once it expires and you haven't updated the Virtual Assistant  LUIS to
route the words log out to the skill, you are essentially stuck.

**Comment by sidmore** [comment]
@Lippy1m1 After setting refreshToken/access token lifespan to 1 minute and doing some other action, noticed the ITSMSkill never prompted to login again.

Repro steps:
Setup: VA =>(Skills: Calendar/ITSM)
a. Set Refresh/AccessToken Lifespan in ServiceNow to 1min
b. Create Ticket successfully
c. Accept calendar meeting
d. Wait a minute
e. Create another ticket

Expected: Login prompt
Actual: Never got a prompt to login instead started with Create Dialog which then fails to post ticket

These were my observations does that sound similar to your repro.

**Comment by Lippy1m1** [comment]
Yes that is the repro

**Comment by darrenj** [comment]
Thanks for raising. Now resolved in https://github.com/microsoft/botframework-skills/pull/231
