### ISSUE TITLE
[skill] sample skill deploy error 

### ISSUE THREAD

**Issue by xhr0804** [microsoft/botframework-solutions#3206]
#### What project is affected?
skills
#### What happens?
When deploy a skill using the new script in sample skill, met some errors.
1. can not deploy luis model
![image](https://user-images.githubusercontent.com/44257569/76861618-d4565700-6897-11ea-881e-e03e6f02e30f.png)
2. an extra place at line 304 for template.json as ""containerId ":
3. Accoding to the doc https://microsoft.github.io/botframework-solutions/skills/tutorials/create-skill/csharp/2-download-and-install/, we use this command to install bf-cli
`npm install -g @microsoft/botframework-cli`
but the latest pulished version seems to be 4.7.0 and it is old for our skill deployment script.
Should we update to latest Nightly build version?

**Comment by lauren-mills** [comment]
Fixed in #3207
