### ISSUE TITLE
Error importing calendar LUIS while running msbot

### ISSUE THREAD

**Issue by gabog** [microsoft/botframework-solutions#321]
**Project**
Assistant

**Description**
I am running msbot to create a new deployment, but I am getting

Command failed: luis import application --region westus --appName "XYZ_Calendar" --in DeploymentScripts\en\calendar.luis --authoringKey XYZ --**msbotCharacter indicies 15,18 do not correspond to the start and end of a token.**

**To Reproduce**
Pull the latest 
run DeploymentScripts\en\update_en.bat
run msbot … and you'll get the error while trying to update the calendar model.

**Comment by gabog** [comment]
+ @Theodosia1005, I think you updated the lu file for calendar last.

**Comment by lauren-mills** [comment]
This will be fixed in an upcoming PR. 

This happens due to some spacing issues in the .lu files and I've already raised a bug for the ludown tool to prevent it in the future: https://github.com/Microsoft/botbuilder-tools/issues/773

**Comment by gabog** [comment]
Thanks, is there an issue with the QnAMaker KB too? I am getting the following error when running the msbot clone script:
Creating QnA Maker KB [FAQ]
Command failed: qnamaker create kb --subscriptionKey XYZ --name "FAQ" --in DeploymentScriptFailed..              Error: {    "operationState": "Failed",    "createdTimestamp": "2018-11-20T01:08:12Z",    "lastActionTimestamp": "2018-11-20T01:08:13Z",    "userId": "XYZ",    "operationId": "bb5d4d48-5fef-4ef2-8fb2-47d3098642fb"}

**Comment by gabog** [comment]
Never mind, the qnamker issue may be something else, I need to narrow this one a bit more. I used a different name and it worked for that one.

**Comment by joalmeid** [comment]
Hit this issue , deploying VirtualAssistant. Can the calendar.luis file be shared for en - while waiting for the PR
?

**Comment by NobinJoseRad** [comment]
will be great if can share the fixed .lu file as its a road block..
