### ISSUE TITLE
[VA] deploy issue when validating

### ISSUE THREAD

**Issue by KayMKM** [microsoft/botframework-solutions#3213]
#### What project is affected?
VA

#### What happens?
When deploy the va sample, it failed when validating:
`> Validating Azure deployment ...This command is implicitly deprecated because command group 'group deployment' is deprecated and will be removed in a future release. Use 'deployment group' instead.
{'additional_properties': {}, 'code': 'InvalidTemplateDeployment', 'message': "The template deployment 'deployment_dry_run' is not valid according to the validation procedure. The tracking id is 'e0287473-b52f-4ee2-b5e4-719ecc2d57e9'. See inner errors for details.", 'target': None, 'details': [<azure.mgmt.resource.resources.v2019_07_01.models._models.ErrorResponse object at 0x059D22B0>], 'additional_info': None}
! Deployment failed. Please refer to the log file for more information.`

the log shows:
`AZ CLI passes minimum version. Current version is 2.2.0
This command is implicitly deprecated because command group 'group deployment' is deprecated and will be removed in a future release. Use 'deployment group' instead.
ERROR: Deployment '03182020164513' could not be found.
This command is implicitly deprecated because command group 'group deployment operation' is deprecated and will be removed in a future release. Use 'deployment operation group' instead.
ERROR: Deployment '03182020164513' could not be found.
`

#### What are the steps to reproduce this issue?
run the deploy script in va sample

#### What were you expecting to happen?
va deployed

**Comment by lzc850612** [comment]
@lauren-mills  can you take a look?

**Comment by lauren-mills** [comment]
Looks like we just need to make the change it mentions in the error to support az cli 2.2. Working on it

**Comment by lauren-mills** [comment]
This should be resolved by #3207
