### ISSUE TITLE
Add a sample MVC Web Chat client using enhanced Direct Line features

### ISSUE THREAD

**Issue by ryanisgrig** [microsoft/botframework-solutions#3215]
## User Story
As ... a developer
I want ... an out of the box web chat app enhanced w
so that ... I don't have to piece together my own web chat implementation

## Acceptance Criteria 
*List your requirements.*
- [ ] Base it off of the .NET MVC app used for the test environment (stored in internal Solutions repo)
- [ ] Enable Direct Line Speech per instructions from botframework-webchat repository: https://github.com/microsoft/BotFramework-WebChat/blob/master/docs/DIRECT_LINE_SPEECH.md
- [ ] Enable the enhanced Direct Line authentication
![image](https://user-images.githubusercontent.com/43043272/77009824-d666f700-6925-11ea-8a81-0f75a481e015.png)
    - Blog post: https://blog.botframework.com/2018/09/25/enhanced-direct-line-authentication-features/
    - Sample: https://github.com/microsoft/BotBuilder-Samples/tree/master/experimental/DirectLineTokenSite
- [ ] Provide documentation to go under the Clients and Channels section on how to run this sample

## Resources
*Provide any screenshots or conversation mockups to support your request.*
*Learn how to mock up bot conversations with [.chat files](http://aka.ms/bfchatfile).*

## Notes
*Provide any additional information.*

**Comment by lzc850612** [comment]
Would documentation be enough? I image the Webchat code would have no difference from the official Webchat.

**Comment by ryanisgrig** [comment]
Not really because if we are going to write the documentation for stringing various pieces together we should include a fully working sample out of the box. We also need this for our test environment anyways so may as well just share the code.

**Comment by lzc850612** [comment]
is the client going to be essentially like this: https://blog.botframework.com/2018/09/01/using-webchat-with-azure-bot-services-authentication/

**Comment by ryanisgrig** [comment]
It will use that and have Direct Line Speech integration

Sent from my 📱

________________________________
