### ISSUE TITLE
botskills tool expects endpointUrl to be lowercase

### ISSUE THREAD

**Issue by lauren-mills** [microsoft/botframework-solutions#3223]
#### What project is affected?
Bot Skills tool

#### What language is this in?
TS

#### What happens?
When trying to connect to a sample skill with an endpoint in the manifest that was sentence cased (e.g. "https://BFCalendarSkill.azurewebsites.net/api/messages") I get the following error:

```
The 'endpointUrl' property contains some characters not allowed at the selected endpoint.
```

#### What are the steps to reproduce this issue?
1. Create and deploy new skill
2. Update manifest endpointUrl with published bot endpoint with camel/sentence casing
3. Run `botskills connect` against skill

#### What were you expecting to happen?
Should be able to support various casing in the endpointUrl

**Comment by dfavretto** [comment]
@lauren-mills this seems similar to the #3188 , which should be fixed in #3209. We modified the RegEx that was validating the endpointUrl, and now it can have upper case letters.
