### ISSUE TITLE
[Docs] how to convert v4 bot to skill link broken

### ISSUE THREAD

**Issue by nebhagat** [microsoft/botframework-solutions#3226]
https://microsoft.github.io/botframework-solutions/howto/skills/skillenablingav4bot/

This link throws 404 not found error.

**Comment by lauren-mills** [comment]
@nebhagat - can you let me know the page you clicked the link from?

**Comment by nebhagat** [comment]
Hi,
found this on https://azure.microsoft.com/en-in/resources/knowledge-center/how-to-convert-a-v4-bot-to-a-skill/ . Was looking for guide to convert existing v4 bot to a skill.

**Comment by peterinnesmsft** [comment]
Hi @nebhagat,

Apologies for the delay in getting to you on this. I've dug into our docs and found what I believe is the corresponding link on helping to convert an existing bot to a skill: https://docs.microsoft.com/en-us/azure/bot-service/skill-implement-skill?view=azure-bot-service-4.0&tabs=cs

Hopefully that should help provide the guidance you need. I will follow up with our Azure support resources and ask them to update the link in the above article accordingly. I'll keep this issue open to track that ask.

**Comment by peterinnesmsft** [comment]
I've submitted a request to the Azure.com engineering owners to update the link, so at this point, I think we've done as much as we can to address the issue. In the interim, you can use the provided link above for further assistance.

**Comment by nebhagat** [comment]
Thanks!
