### ISSUE TITLE
Provide the ability to chose the pricing tier for search service in msbot

### ISSUE THREAD

**Issue by gabog** [microsoft/botframework-solutions#323]
**Is your feature request related to a problem? Please describe.**
By default, msbot create a Standard Search Service which is kind of expensive for dev and local tests. 
If I understand this correctly (https://docs.microsoft.com/en-us/azure/search/search-sku-tier) the search pricing tier can not be changed after its been created.
QnAMaker allows you to select a pricing tier when creating the service but this parameter is not exposed by msbot

**Describe the solution you'd like**
I would like to have a parameter where I can specify the pricing tier to be used by the Search Service used by QnAMaker.

**Describe alternatives you've considered**
I've considered manually recreating QnAMaker and then update the bot files and the dispatcher, but this is time consuming and I will need to do it again if I need to update my environment from a new drop (msbot doesn't support update, you are forced to delete and recreate if you want to get the latest).

**Comment by lauren-mills** [comment]
Raised feature request in Bot Builder Tools repo here: https://github.com/Microsoft/botbuilder-tools/issues/782

**Comment by NobinJoseRad** [comment]
This is a good feature request.

What I am doing is to update the script file with my desired tier in npm modules.

**Comment by NobinJoseRad** [comment]
To me the script path is 

C:\Users\nobin.jose\AppData\Roaming\npm\node_modules\msbot\bin\msbot-clone-services.js

Thank you..

**Comment by darrenj** [comment]
Closing as Tracked in https://github.com/Microsoft/botbuilder-tools/issues/584
