### ISSUE TITLE
[Docs] Unable to load PowerBI Data for Application Insights of Virtual Assistant following documenation

### ISSUE THREAD

**Issue by Lippy1m1** [microsoft/botframework-solutions#3245]
/solution-accelerators/tutorials/view-analytics/3-open-template/

Step 8 is to sign in and use organization account and I got this.

I tried to follow these steps and I got this error when on step 8.  This error was shown whether I was logged into Power BI with my AD credentials or not logged in I got the same error for both.

![image](https://user-images.githubusercontent.com/22352324/77797280-2f7e0b80-7047-11ea-8b02-0214e98af207.png)

**Comment by Lippy1m1** [comment]
Please let me know what needs done so I can load my chatbot analytical data for the Virtual Assistant.

**Comment by dmvtech** [comment]
hi @Lippy1m1 

Did you try clearing the permissions/cache and re-authenticating per the directions after step 2 on [this page](https://microsoft.github.io/botframework-solutions/solution-accelerators/tutorials/view-analytics/3-open-template/)?

**Comment by Lippy1m1** [comment]
Yes, I did.

**Comment by dmvtech** [comment]
And the credentials you are using are for the same subscription that the app insights resource is in?

**Comment by Lippy1m1** [comment]
Absolutely.  I could really use a fix for this so that I can see all the analytics from the VA.

**Comment by dmvtech** [comment]
I'm not quite sure, but this seems as an issue with the permissions than anything. Can you try taking a look at this article:
https://community.powerbi.com/t5/Desktop/We-were-unable-to-connect-because-this-credential-type-isn-t/td-p/37838

And see if any of the tips/tests show anything useful?

**Comment by Lippy1m1** [comment]
Dana,

I reviewed the link above and didn't see anything but just tried again to get the data to show up in PowerBI and it did for some reason.  Just not sure why it loads now and didn't load then.

Matt...

**Comment by dmvtech** [comment]
I hate it when things resolve without knowing why! (i'm sure you do to)

Anyhow, I'm glad it is working for you now!

**Comment by samaea** [comment]
I am having the same issue (even after deleting all the global permissions), I am receiving the error message "credential type" not supported. Unlikely, but wondering if it is linked to this issue https://github.com/microsoft/botframework-solutions/issues/3508?

Worth noting it does not even prompt for credentials.

![image](https://user-images.githubusercontent.com/32162601/87150694-787e6680-c2aa-11ea-8a86-13aa656908b7.png)

**Update**: Further troubleshooting using a Fiddler trace, shows that when clicking on the **"Sign in"** button, it does the following GET request:-

**HTTP Request**

```
GET https://api.loganalytics.io/v1/apps/[APP_ID_KEY_REMOVED]/query HTTP/1.1
Authorization: Bearer
User-Agent: Microsoft.Data.Mashup (https://go.microsoft.com/fwlink/?LinkID=304225)
Host: api.loganalytics.io
```

**Response**

```
HTTP/1.1 404 Not Found
Date: Fri, 10 Jul 2020 11:49:53 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 84
Connection: keep-alive
Strict-Transport-Security: max-age=15724800; includeSubDomains
via: 1.1 draft-oms-6d77f67789-l9qw2
X-Content-Type-Options: nosniff
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: Retry-After,Age,WWW-Authenticate,x-resource-identities,x-ms-status-location

{"error":{"message":"The requested path does not exist","code":"PathNotFoundError"}}
```
