### ISSUE TITLE
OnInterruptDialogAsync Should Handle the Interrupt Event

### ISSUE THREAD

**Issue by DavidStrickland0** [microsoft/botframework-solutions#3246]
## User Story
As a Dialog
I want Execute the OnInterrupt event
so that I can perform any logic needed when an interruption occurs

## Acceptance Criteria 
*List your requirements.*

InterruptableDialog currently has an Abstract Method named OnInterruptDialogAsync. OnInterrupt would imply that this method fires when the dialog is Interrupted and any clean up code you want to execute when the Dialog is interrupted would seem to belong in OnInterruptDialogAsync returning an InteruptResult.
However looking at the code for the other methods (OnBegin and OnContinue) this method is actually intended to Determine if there should be an Interrupt and it thus needs to be called on every execution of the dialog. Its not actually Handling the interrupt event but is instead checking to see if the interrupt event should be handled returning the InterruptionAction that is presumably actually handled by something else.
This logic might better belong in BeforeBeginDialog on OnDialogInit.
Leaving the OnInterruptDialogAsync available for actually handling the InterruptionAction.

## Resources
Interruptable Dialog
https://github.com/microsoft/botframework-solutions/blob/6d40fa8ae05f96b0c5e0464e01361a9e1deb696c/sdk/csharp/libraries/microsoft.bot.solutions/Dialogs/InterruptableDialog.cs

Event Design
"By convention, the name of the method should start with "On" and be followed with the name of the event."
https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/event

## Notes
*Provide any additional information.*

**Comment by lauren-mills** [comment]
Hi @DavidStrickland0 - I agree that the naming is incorrect. However, we are actually marking this dialog as obsolete in our next release, and recommending the approach for interruptions found in the latest MainDialog of the VirtualAssistantSample project [here](https://github.com/microsoft/botframework-solutions/blob/master/samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Dialogs/MainDialog.cs). Please let us know if you have any questions or concerns.

**Comment by marcasmar94** [comment]
@lauren-mills I am currently using the latest VA sample you mentioned above and when we **CancelAllDialogsAsync**() inside of **MainDialog**'s **OnInterruptDialogAsync**
The user will always have to send **2** messages and not **1** for the bot to reply.
This does not happen when we **CancelAllDialogsAsync**()  in **other** dialogs 
( even though i am beginning the dialog  after cancellation --> innerDc.BeginDialogAsync(InitialDialogId);

Am I doing something wrong or should I open this as a new issue ?

**Comment by peterinnesmsft** [comment]
Closing due to lack of further activity and on the basis that the dialog in question is being marked as obsolete in GA release.

**Comment by hansmbakker** [comment]
@lauren-mills @peterinnesmsft 
> we are actually marking this dialog as obsolete in our next release, and recommending the approach for interruptions found in the latest `MainDialog`

Is there any documentation for this? Or any sample where interruption is used in a dialog other than the `MainDialog`?
Should the interruption be checked in every dialog's `OnBeginDialogAsync`  where you want to use interruption, or will the `MainDialog` interrupt logic handle interrupts for all dialogs?
