### ISSUE TITLE
Language concurrency issue

### ISSUE THREAD

**Issue by hhasenauer** [microsoft/botframework-solutions#3254]
#### What project is affected?
Virtual Assistant

#### What language is this in?
C#

#### What happens?
Since the change to initialise a localised QNA Dialog in the constructor of the Dialogs (MainDialog), the following code in BotServices.cs -  `public CognitiveModelSet GetCognitiveModels()` does not provide expected results.
```sharp
var locale = CultureInfo.CurrentUICulture.Name.ToLower();
```
The problem is, since you are calling this in the constructor, the SetLocaleMiddleware has not run and therefore the culture is not correctly set. I think in Windows there will be used some sort of default value? In MacOS this issue manifests by crashing since there does not exist a default value for the CurrentUICulture.
I don't really see a good way to resolve this when I want to use your `QnAMakerDialog`, if I do have multiple languages in my project.

**Comment by lauren-mills** [comment]
Hi @hhasenauer - we have seen similar issues and have modified the QnADialog initialization to resolve this issue in the "next" branch. Please take a look at the implementation [here](https://github.com/microsoft/botframework-solutions/blob/88eae483d3a26397c4d9c9fa09c2d2fbb83d0107/samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Dialogs/MainDialog.cs#L333) and let me know if you have any issues or questions!

**Comment by hhasenauer** [comment]
Hi @lauren-mills thanks for the quick reply. Yea that solution will definitely work. Unfortunately it is not as clean. 
Another idea I had, but also not very clean, would be to still do the initialisation in the constructor, but iterate over all knowledges bases and languages and initialise them all and add the dialogs.
Then you could just begin / continue the according dialog depending on your needed language.
Please let me know what you think of this idea?

**Comment by lauren-mills** [comment]
That was definitely an approach we considered. I decided on the current implementation because it reduces the potential for having multiple QnADialogs in different languages on the stack at once and reduces the complexity around the dialog ids.

**Comment by peterinnesmsft** [comment]
Given that the core issue has been addressed by @lauren-mills, I am going to close this issue since there hasn't been activity in over two weeks. @hhasenauer if you are not satisfied with the solution, then please feel free to reactivate this issue. Alternatively, you are welcome to contribute!
