### ISSUE TITLE
Usage of deprecated tool/command inside Botskills 

### ISSUE THREAD

**Issue by VladPapacostea-SM** [microsoft/botframework-solutions#3261]
#### What project is affected?
Botskills tool

#### What language is this in?
Javascript/Typescript 

#### What happens?
Currently using the depecrated tool "Ludown" (and I think it's the case with 'luisgen" as well) 

We've actually had some issues in the past with ludown before migrating it to bf-cli, as the deprecation message was being outputted with the actual content, and was breaking the format of the file/result. 

#### What are the steps to reproduce this issue?
N/A

#### What were you expecting to happen?
Migrate to the BF-Cli tool - as suggested by the warnings 

#### Can you share any logs, error output, etc.?
N/A
#### Any screenshots or additional context?
N/A

**Comment by dfavretto** [comment]
Hi @VladPapacostea-SM , the internal tools that are executed by Botskills were migrated to BF CLI tools in PR #3174 , which is already merged into branch `next`. There's a Daily Release in MyGet which has this implementation ([botskills@1.0.15-preview171](https://botbuilder.myget.org/feed/aitemplates/package/npm/botskills/1.0.15-preview171)), which you can use with the following steps:
1. If you have Botskills installed, first uninstall it using the command `npm uninstall -g botskills`
1. Install Botskills with the command `npm install -g botskills@1.0.15-preview171 --registry https://botbuilder.myget.org/F/aitemplates/npm`
1. Run `botskills -v` to make sure you have the desired version
  ![image](https://user-images.githubusercontent.com/23645105/78375758-a5ccc180-75a3-11ea-9b54-6aea9ca31f20.png)

Now you can connect a Skill to a VA without the deprecation warnings. If you need anything else, we are here to help 😊.

**Comment by VladPapacostea-SM** [comment]
Thanks @dfavretto . Didn't realise that "master" was not the most up to date. 
Happy to close.

**Comment by VladPapacostea-SM** [comment]
@dfavretto Hi, we were just using that build that you were mentioning there, and ran into some issues. I realise that's a preview build, so I thought there's no point in me creating a separate issue for that. This is just a little FYI:  
That version, on connecting skills, rather than updating the dispatch file ( Dispatch.cs in my case) creates new ones every time a new skill is connected, and names them using the filename of the .dispatch file +(1) (2) .. etc
