### ISSUE TITLE
[Docs] Create Dispatch Model command examples unclear

### ISSUE THREAD

**Issue by WizX20** [microsoft/botframework-solutions#3263]
The steps on the page /virtual-assistant/tutorials/deploy-assistant/cli/7-create-dispatch-model/ do not make sense to me and do not result in a correct dispatch model.

- dispatch add: Requests required parameters even though they have been provided
  - Overwrites existing models in the file
- No clear instructions on how to generate the .json file
- dispatch create: overwrites all previous steps and creates a new, empty, dispatch file

**Comment by anusharr** [comment]
@WizX20 can you elaborate on the steps you ran along with the screenshots of the errors you encountered?

**Comment by anusharr** [comment]
Closing the issue. Please feel free to reopen if your issue is unresolved.
