### ISSUE TITLE
BeginDialogAsync takes longer to execute on first request

### ISSUE THREAD

**Issue by GustavoMoreiraPT** [microsoft/botframework-solutions#3266]
## Version
4.7.0 (Microsoft.Bot.Builder.Dialogs)

## Describe the bug
Hi everyone,
I am developing a webapp based on bot framework using the .Net Core SDK.
I have a direct line channel available and I noticed that be first request is always slower than the following ones.
The majority of the delay happens when calling **BeginDialogAsync** method from **DialogContext** class, from **Microsoft.Bot.Builder.Dialogs** package.
I already tried to do some warm up action to mitigate this problem, by calling method from singletons that are registered through Dependency Injection and are called within the **BeginDialogAsync** method.

Some of warm up tasks done include:

- Dummy call to LUIS Recognizer
- Dummy Bot state call to initialize CosmosDbStorage
- IBotTelemetryClient logging initialization
- IBotFrameworkAdapter initialization by doing a dummy call to ProcessActivityAsync method.

Even with these dummy calls, the first requests takes on average 4 to 6 seconds, while the rest of them takes only 1 second and under.

## To Reproduce
1. From any bot using direct line, call DialogContext.BeginDialogAsync
2. Wait until the bot replies.
3. Measure the 1st request duration time
4. Repeat the above process for the following request and compare the time.

## Expected behavior
The outcome from this issue is to reduce the request duration time when starting the bot.

[bug]

**Comment by EricDahlvang** [comment]
@GustavoMoreiraPT I've transferred this to the botframework-solutions repo, where this package lives: Microsoft.Bot.Builder.Solutions

@solutions team, do you have any other recommendations for GustavoMoreiraPT that might help improve startup time?

**Comment by darrenj** [comment]
A good first step would be to migrate to the newly GA version of Skills which removes teh dependency on Websockets. 

We have some straight forward steps for VA changes [here](https://microsoft.github.io/botframework-solutions/overview/whats-new/0.8-beta/migrate-existing-va-to-0.8) and for any custom skills [here](https://microsoft.github.io/botframework-solutions/overview/whats-new/0.8-beta/migrate-existing-skills-to-0.8/).

GA Skills have a different approach for authentication and I'm not aware of similar performance issues. If you have any issues with updates to your VA please let us know and interested to see how this helps you.

Depending on the changes you've made to VA another approach would be to create a new VA and migrate changes but if you've made a lot of changes the steps above will guide you.

**Comment by GustavoMoreiraPT** [comment]
Hi @darrenj ,

Thanks for the reply.

We've noticed the new version V0.8 and we are already tackling the changes to do the migration, but it's a work in progress.

I'll keep you updated regarding this.

Thanks a lot once again.

**Comment by peterinnesmsft** [comment]
Hi @GustavoMoreiraPT,

Just following up to see if there is anything further that you currently need from us for this particular issue? It sounds based upon your last comment that you have a path forward through migration to v0.8.

If there's no active need for assistance, then I will close the issue for now. If at any point you encounter further issues regarding this, feel free to reactivate and we can jump straight back on to assist.

Let me know if you have any objections or need any help with anything actively!

**Comment by GustavoMoreiraPT** [comment]
Hi @peterinnesmsft ,

Thanks for your reply.
I was waiting to have metrics available to share with you after V0.8 migration, but unfortunately due to time constraints the migration was put on hold.

So currently we basically created a Fake Turn Context provider on initialization time, which forces the get of the token and that really bumped the first request response time.
Although it works, it's not perfect (it is still slower than the following requests), but after all this, we managed to reduce the initial response time from 10/15 seconds to 2/3 seconds.

I will reply to this comment once I have the project migrated to V0.8.
For now I think it can be closed, although the issue seems real.

Thanks for your help and let's speak soon! :)

**Comment by peterinnesmsft** [comment]
Hi @GustavoMoreiraPT,

No worries about the delay in the migration. I'm glad you had some success in cutting down the initial response time, but I agree that we can probably help find ways to lower it further.

I'll close the issue for now, but let's pick this up again when you are able to revisit and we can happily help dig in to see what kind of improvements we can make.

Look forward to hearing back from you soon! :)

**Comment by peterinnesmsft** [comment]
Hi @GustavoMoreiraPT,

No worries about the delay in the migration. I'm glad you had some success in cutting down the initial response time, but I agree that we can probably help find ways to lower it further.

I'll close the issue for now, but let's pick this up again when you are able to revisit and we can happily help dig in to see what kind of improvements we can make.

Look forward to hearing back from you soon! :)
