### ISSUE TITLE
[VA] CancelAllDialogsAsync() inside of MainDialog not starting the dialog again

### ISSUE THREAD

**Issue by marcasmar94** [microsoft/botframework-solutions#3267]
#### What project is affected?
**VirtualAssistantSample** project
#### What language is this in?
**C#**
#### What happens?
when we **CancelAllDialogsAsync**() inside of **MainDialog**'s **OnInterruptDialogAsync**
The user will always have to send **2** messages and not **1** for the bot to reply.
The first message **after** we CancelAllDialogsAsync insisde of MainDialog will go through the 
MainDialog 's OnContinueDialogAsync and nothing happens after that
Even though i am beginning the dialog after cancellation:
```c#                  
await innerDc.Context.SendActivityAsync(_templateEngine.GenerateActivity("CancelledMessage", userProfile, innerDc.Context));
                        await innerDc.CancelAllDialogsAsync();
                        await innerDc.BeginDialogAsync(InitialDialogId);
                        interrupted = true;
```

⚠ This does not happen when we **CancelAllDialogsAsync**()  in **other** dialogs 

#### What are the steps to reproduce this issue?
 **await innerDc.CancelAllDialogsAsync()**; inside of **MainDialog** and try to message the bot right after
#### What were you expecting to happen?
MainDialog's **OnBeginDialogAsync** should be triggered

**Comment by pavolum** [comment]
@marcasmar94 couple additional questions for you:

- what version of the sample are you using?  The reason I ask is that I am unable to reproduce this issue using this [maindialog.cs](https://github.com/microsoft/botframework-solutions/blob/next/samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Dialogs/MainDialog.cs) implementation. 
- Are you running into this issue when using the `` GeneralLuis.Intent.Cancel`` command that is shipped with the template or within custom logic you have added in the interrupt method? If the latter please send over your interrupt method

**Comment by marcasmar94** [comment]
- @pavolum I am using this [Sample](https://github.com/microsoft/botframework-solutions/tree/master/samples/csharp/assistants/virtual-assistant/VirtualAssistantSample) (Master)

- I am using a custom logic
    - I have "Cancel" Buttons all over the bot, I did not want to handle that on each and every dialog, so i am handling it in **InterruptDialogAsync**
    - When a Cancel button is clicked, i receive a "QR_Cancel_Current_Dialog" Payload which is caught in **InterruptDialogAsync** as shown below
```c#
  private async Task<bool> InterruptDialogAsync(DialogContext innerDc, CancellationToken cancellationToken)
        {
            var interrupted = false;
            var activity = innerDc.Context.Activity;
            var userProfile = await _UserStateAccessor.GetAsync(innerDc.Context, () => new MainUserState());

            _state = await _UserStateAccessor.GetAsync(innerDc.Context, () => new MainUserState());

            if (activity.Type == ActivityTypes.Message && !string.IsNullOrEmpty(activity.Text))
            {
                var hasPayload = _payloadProcessor.HasPayload(innerDc.Context.Activity.ChannelId, innerDc.Context);
                if (!hasPayload)
                {
                    var intentInfo = await GetIntentInfo(activity.Text.Trim(), false, innerDc.Context);
                    if (intentInfo.IntentName.Equals("smalltalk.agent.can_you_help", StringComparison.InvariantCultureIgnoreCase))
                    {
                        await innerDc.Context.SendActivityAsync(_templateEngine.GenerateActivity("HelpCard", userProfile, innerDc.Context));
                        await innerDc.RepromptDialogAsync();
                        interrupted = true;
                    }
                }
                else
                {
                    string payload = _payloadProcessor.GetPayload(innerDc.Context.Activity.ChannelId, innerDc.Context);
                    if (payload == nameof(BotEnums.QRPayload.QR_Cancel_Current_Dialog))
                    {
                        await innerDc.Context.SendActivityAsync(_templateEngine.GenerateActivity("CancelledMessage", userProfile, innerDc.Context));
                        await innerDc.CancelAllDialogsAsync();
                        await innerDc.BeginDialogAsync(InitialDialogId);
                        interrupted = true;
                    }
                }
            }
            return interrupted;
        }
```

- InitialDialog Id is set to MainDialog as below
```c#
InitialDialogId = nameof(MainDialog);
```
- And the waterfall dialog is added as below
```c#
  var steps = new WaterfallStep[]
            {
                RouteStepAsync,
                FinalStepAsync,
            };
AddDialog(new WaterfallDialog(nameof(MainDialog), steps));
```

 - My **DefaultActivityHandler** implementation uses **ActivityHandler** and not **TeamsActivityHandler**
   - I have tried both though and same issue occured

**Comment by pavolum** [comment]
Hmmmm ```await innerDc.CancelAllDialogsAsync();``` works within the interrupt function in the maindialog.cs implementation on the master branch as well so the issue is probably in the custom logic you have implemented.

I would recommend looking at the clean maindialog.cs in the master branch and go through the working cancellation flow to get an idea of what may be missing in your implementation. 

One thing that it may be...I notice that you have removed the IntroStepAsync from your mainDialog waterfall steps. When the following code executes in the unaltered mainDialog.cs:
```                        
await innerDc.CancelAllDialogsAsync();
await innerDc.BeginDialogAsync(InitialDialogId);
```
Main dialog is pushed back to the stack and runs IntroStepAsync which prompts the user for a new query and passes the resulting user response to routeStepAsync. Not having that prompt logic and starting maindialog off in with route step may result in unintended behavior. This may also be the case if you altered the overrides for ```OnBeginDialogAsync``` or ```OnContinueDialogAsync```.

If the above doesn't help you pinpoint the issue, feel free to send over your maindialog.cs implementation.

**Comment by marcasmar94** [comment]
@pavolum After adding the IntroStepAsync that contains the prompt, the issue was resolved.
But our bot should not prompt the user when the MainDialog Starts.
How can i handle this scenario when using the current MainDialog ?
When the user first starts the conversation, we will show them a Get Started Menu 
We do not want to keep prompting the user, it's all up to the user to ask or not.
Any recommendation ?
Thank you.

**Comment by pavolum** [comment]
@marcasmar94 glad to hear you were able to resolve the issue.

The prompt is needed on the dialog stack to ensure when the main dialog restarts that the next query is anticipated for and passed to the route function correctly. So you will need to keep IntroStepAsync. 

That being said the prompt in IntroStepAsync does not have to be a prompt that is visible to the user. Something like the below should add a prompt to the dialog stack ensuring correct routing behavior of the next query to come in but also not render any prompt text to the UI enabling you to get the experience you desire.

```
        private async Task<DialogTurnResult> IntroStepAsync(WaterfallStepContext stepContext, CancellationToken cancellationToken)
        {
            var promptOptions = new PromptOptions();

            return await stepContext.PromptAsync(nameof(TextPrompt), promptOptions, cancellationToken);
        }
```

**Comment by marcasmar94** [comment]
@pavolum  Just tried that and worked perfectly! Awesome trick! 🙇‍♂️
Thank you, i think this can be closed
