### ISSUE TITLE
VA 0.8 Deployment error 

### ISSUE THREAD

**Issue by ipraveenMS** [microsoft/botframework-solutions#3280]
#### What project is affected?
VA 0.8
#### What language is this in?
C#
#### What happens?
I get error during https://microsoft.github.io/botframework-solutions/virtual-assistant/tutorials/create-assistant/csharp/4-provision-your-azure-resources/

#### What are the steps to reproduce this issue?
Brand new machine
Follow all steps before https://microsoft.github.io/botframework-solutions/virtual-assistant/tutorials/create-assistant/csharp/4-provision-your-azure-resources/
 az login
./Deployment/Scripts/deploy.ps1
#### What were you expecting to happen?
success
#### Can you share any logs, error output, etc.?
PS C:\Users\prachand\source\repos\VirtualAssistant\VirtualAssistant\VirtualAssistant> ./Deployment/Scripts/deploy.ps1
? Bot Name (used as default name for resource group and deployed resources): ObiPP2
? Azure resource group region: westus
? Password for MSA app registration (must be at least 16 characters long, contain at least 1 special character, and contain at least 1 numeric character): Obi1234567890#$%
? Create a new LUIS Authoring Resource? [y/n]: n
? LUIS Authoring Key: 7dc80faa20e8498c9387b6d0d3b3ccb2
? LUIS Authoring Region (westus, westeurope, or australiaeast): westus
> Creating resource group ...Done.
> Validating Azure deployment ...This command is implicitly deprecated because command group 'group deployment' is deprecated and will be removed in a future release. Use 'deployment group' instead.
{'additional_properties': {}, 'code': 'InvalidTemplateDeployment', 'message': "The template deployment 'deployment_dry_run' is not valid according to the validation procedure. The tracking id is '30edad0e-a103-48eb-bc5d-bcc3b4d2fafe'. See inner errors for details.", 'target': None, 'details': [<azure.mgmt.resource.resources.v2019_07_01.models._models.ErrorResponse object at 0x05BB49D0>], 'additional_info': None}
! Deployment failed. Please refer to the log file for more information.
! Log: C:\Users\prachand\source\repos\VirtualAssistant\VirtualAssistant\VirtualAssistant\Deployment\Scripts\..\deploy_log.txt
[deploy_log.txt](https://github.com/microsoft/botframework-solutions/files/4458078/deploy_log.txt)

**Comment by okulygin** [comment]
I am getting exactly same error

**Comment by ipraveenMS** [comment]
After cleaning the resources, I don't see this error anymore. Its a different error and I will file a bug.
