### ISSUE TITLE
VA Deploy script not working with latest Azure CLI

### ISSUE THREAD

**Issue by pavolum** [microsoft/botframework-solutions#3286]
#### What project is affected?
VA Template
#### What language is this in?
C#
#### What happens?
Deploy blocked due to deprecated Azure-CLI command 
#### What are the steps to reproduce this issue?
Update to latest Azure [azure CLI](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?view=azure-cli-latest) and deploy a VA (I was using [4.8.0 VA VSIX template](https://botbuilder.myget.org/feed/aitemplates/package/vsix/VirtualAssistantTemplate.d2246051-7779-4196-af1f-ae7e2562ec8e/4.8.0.0))
Deployment script will render the following error
```
> Validating Azure deployment ...{'additional_properties': {}, 'code': 'InvalidTemplateDeployment', 'message': "The template deployment 'template' is not valid according to the validation procedure. The tracking id is '116ce896-c260-4da6-a22d-d0f2b019522c'. See inner errors for details.", 'target': None, 'details': [<azure.mgmt.resource.resources.v2019_07_01.models._models.ErrorResponse object at 0x05782C30>], 'additional_info': None}
! Deployment failed. Please refer to the log file for more information.
! Log: C:\Users\pavolum\source\repos\testBotLatest\testBotLatest\Deployment\Scripts\..\deploy_log.txt
+ To delete this resource group, run 'az group delete -g testBotLatest --no-wait'
PS C:\Users\pavolum\source\repos\testBotLatest\testBotLatest> az group delete -g testbotlatest --no-wait
Are you sure you want to perform this operation? (y/n): y
```

and the following logs

```
AZ CLI passes minimum version. Current version is 2.3.1
Deployment '04142020183731' could not be found.
This command is implicitly deprecated because command group 'deployment operation' is deprecated and will be removed in a future release. Use 'deployment operation sub' instead.
Deployment '04142020183731' could not be found.
```
#### Any additional context?
We will need to update the deploy scripts to not use the deprecated command and ensure our bits work with the latest CLI packages. The log indicates that 'deployment operation sub' should be used instead of  'deployment operation' which makes little sense to me. When you run ```az deployment operation sub --help``` you get the following deprecation warning as well

```
Group
    az deployment operation sub : Manage deployment operations at subscription scope.
        This command group is implicitly deprecated because command group 'deployment
        operation' is deprecated and will be removed in a future release. Use 'deployment operation
        sub' instead.

```

**Comment by pavolum** [comment]
@sidmore the error message seems misleading. 

I do not receive this error when I switch to a sub that has not hit its cap of bot resources. When I switch to my personal sub, I am able to deploy :) 

However on my personal sub I do receive this error depending on what I name the bot/RG on deployment. This is due to the logic in the deploy.ps1 script. A resource group can legally have characters like underscores in the name. However we use the RG name in the deploy script to name other resources that cannot have characters like underscores.

So you will receive the same error that is posted above. When you dig a bit deeper into the azure logs, you see this message:
```
{\"error\":{\"code\":\"InvalidTemplateDeployment\",\"message\":\"The template deployment 'template' is not valid according to the validation procedure. The tracking id is 'GUID REMOVED'. See inner errors for details.\",\"details\":[{\"code\":\"CustomDomainInvalid\",\"message\":\"Sub domain name 'TestVA_48-luisruntime-cspaq5k' is not valid.\"}]}}"
```

**Comment by peterinnesmsft** [comment]
Script fix has been made to handle validation results in a more robust manner, and Azure CLI have confirmed fix has been made to handle the JSON parsing issue (https://github.com/Azure/azure-cli/issues/13037).
