### ISSUE TITLE
Deployment script(s) do not allow for different target subscription

### ISSUE THREAD

**Issue by slickmonkey** [microsoft/botframework-solutions#3289]
/skills/tutorials/create-skill/csharp/4-provision-your-azure-resources/
The Skills bot deployment scripts make the foolish assumption that the default subscription context for the current user is the correct one for deploying to. This might be fine for a user who has access to only 1 subscription, but is a terrible assumption to make for the vast majority of users.
Either fix the scripts to allow for the user to SPECIFY a subscription or fix the docs to have the user SET CONTEXT of the correct subscription before executing the deployment!

**Comment by lauren-mills** [comment]
Hi @slickmonkey, the instructions for changing your Azure subscription have been added to the doc. Thanks.
