### ISSUE TITLE
Implement cross-language functional test pipelines for Virtual Assistant and Skill samples

### ISSUE THREAD

**Issue by ryanisgrig** [microsoft/botframework-solutions#3290]
## User Story
As ... a developer
I want ... YAML pipelines available for the Virtual Assistant and Skill Sample
so that ... I can run nightly validation tests against my VA solution

## Acceptance Criteria 
- [ ] Build off of investments in the [Skills Functional Tests](https://github.com/microsoft/BotFramework-FunctionalTests/blob/master/SkillsFunctionalTests/README.md) with YAML files available for the below cross-language scenarios. This should use the same task variables as the source files.

|Virtual Assistant/Skill|C#|TypeScript|
-|-|-
C#|✅|✅|
TypeScript|✅|✅|

### Prepare
* Access Azure Key Vault (AKV) secrets for VA & Skill
* If they exist, cleanup existing test resources groups
* Install dispatch, luis-api
* Install botframework-cli
* Install botskills
    * Optional variable to configure between stable or preview version for above npm packages
* Get BotBuilder version
    * Optional variable to configure between stable or preview version
* Get BotSolutions version
    * Optional variable to configure between stable or preview version

#### Virtual Assistant
* Update to custom package references
* Run dotnet restore
* Run dotnet build

#### Skill
* Update to custom package references
* Run dotnet restore
* Run dotnet build

#### Virtual Assistant
* Run unit tests

#### Skill
* Run unit tests

#### Virtual Assistant
* Run deployment script
    * Languages: en-us,de-de,fr-fr,it-it,es-es,zh-cn

#### Skill
* Run deployment script
    * Languages: en-us, de-de,fr-fr,it-it,es-es,zh-cn

#### Virtual Assistant
* Create Direct Line Channel registration
* Get channel secrets
* Run functional Direct Line tests

### Cleanup
* Delete resource group

- [ ] Update docs with additional overview on how to enable this (can be lifted from existing Skills Functional Tests doc)

## Resources
*Provide any screenshots or conversation mockups to support your request.*
*Learn how to mock up bot conversations with [.chat files](http://aka.ms/bfchatfile).*

## Notes
*Provide any additional information.*

**Comment by peterinnesmsft** [comment]
Closing issue to track in internal backlog going forward.
