### ISSUE TITLE
VA and Skill deploy script not working

### ISSUE THREAD

**Issue by badhonkundu** [microsoft/botframework-solutions#3303]
#### What project is affected?
Deploying VA and/or Skill

#### What language is this in?
C#

#### What happens?
Get below error when deploying:
ConvertFrom-Json : Conversion from JSON failed with error: Unexpected character encountered while parsing value: F. Path '', line 0, position 0.
At ...\Deployment\Scripts\luis_functions.ps1:33 char:28                                                                                                                  +         --wait) 2>> $log | ConvertFrom-Json                                                                           +                            ~~~~~~~~~~~~~~~~                                                                           + CategoryInfo          : NotSpecified: (:) [ConvertFrom-Json], ArgumentException                                       + FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.Commands.ConvertFromJsonCommand                 
! Could not deploy LUIS model. Review the log for more information.
! Log: .....\deploy_cognitive_models_log.txt

#### What are the steps to reproduce this issue?

When running the the below script to deploy a VA/Skill we get the error shown in the screen shot attached.
./Deployment/Scripts/deploy.ps1 -name Company-Skill-Test-DEV -resourceGroup Company_Skill_Test_Dev_ResourceGroup -location "eastus" -appId <APP ID> -appPassword "<APP Password>" -luisAuthoringKey <LUIS Authoring Key> -luisAuthoringRegion "westus" -parametersFile "C:\....\Company-Skill-Test\Company-Skill-Test\Company_Skill_Test\Deployment\Resources\parameters.template.json"

The parameters.template.json has the below settings:
{
  "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentParameters.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
    "useCosmosDb": {
      "value": false
    },
    "useStorage": {
      "value": false
    },
    "appServicePlanSku": {
      "value": {
        "tier": "Free",
        "name": "F1"
      }
    },
    "botServiceSku": {
      "value": "F0"
    },
    "luisRuntimeSku": {
      "value": "S0"
    }
  }
}

Same issue with Azure-CLi v 2.4.0 and 2.3.1

#### What were you expecting to happen?
The VA/Skill should get deployed successfully. We have deployed VA/Skills with this naming convention and scripts even in the last week of March and everything worked fine.

#### Can you share any logs, error output, etc.?
Log from "deploy_cognitive_models_log.txt"
AZ CLI passes minimum version. Current version is 2.4.0
internal/modules/cjs/loader.js:797
    throw err;
    ^

Error: Cannot find module '...\Company-Skill-Test\GP-Skill-Test\Company_Skill_Test\luis.fuse.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
internal/modules/cjs/loader.js:797
    throw err;
    ^

Error: Cannot find module '...\Company-Skill-Test\Company-Skill-Test\Company_Skill_Test\luis.fuse.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

#### Any screenshots or additional context?
![image](https://user-images.githubusercontent.com/63103301/79973543-606e2680-84b5-11ea-83c5-faa16e38e71d.png)

**Comment by peterinnesmsft** [comment]
Hi @badhonkundu,

Can you please provide a couple of additional details to assist investigation of this issue:

- Which version(s) of the VA and Skill templates are you using?
- What version of the following npm packages are installed on your global environment (you can run 'npm list -g' from cmd to verify):
  - @microsoft/botframework-cli
  - botdispatch
  - luis-apis
  - botskills

**Comment by badhonkundu** [comment]
@peterinnesmsft 

VA and Skill templates are 4.7.2

@microsoft/botframework-cli@4.8.0
botdispatch@1.6.9
botskills@1.0.14

@microsoft/bf-luis-cli@4.8.0
@azure/cognitiveservices-luis-authoring@4.0.0-preview.1
@azure/cognitiveservices-luis-runtime@5.0.0
@azure/cognitiveservices-luis-authoring@4.0.0-preview.1 deduped
luis@3.2.13

**Comment by badhonkundu** [comment]
@peterinnesmsft 
Tried with the latest Azure CLI today 2.5.0
Same issue

**Comment by peterinnesmsft** [comment]
@badhonkundu could you try running your script in an elevated host (i.e. Run as Admin)?

**Comment by peterinnesmsft** [comment]
No response in 7 days, so resolving issue. Feel free to reactivate if further support is needed.
