### ISSUE TITLE
Android Virtual Assistant Sample App

### ISSUE THREAD

**Issue by darrenj** [microsoft/botframework-solutions#331]
Android is a popular client of Virtual Assistants especially in the Automotive space. Most customer conversations end up with a demo running on an example Android device/head-unit and require a custom app to be built that interfaces with STT, Direct-Line and TTS, Renders Adaptive Cards, etc. which requires a lot of up-front time delaying initial traction. In comparison a VA solution can be deployed in around 15 minutes.

**Describe the solution you'd like**
A sample that once compiled enables a customer to build, drop an APK onto a device, provide the appropriate configuration (keys, voice names, endpoints) and demonstrate VA right away. This will work against a standard VA deployed straight from our repo codebase and not require any changes.

This then provides the basis for a customer/partner to then iterate for any demo. We'll keep this up to date with planned Speech changes including Edge.

Key features:

- Branding should be "Virtual Assistant"
- No Wake-Words or constant recognition. Interaction is started by pressing a button in the UX. We have a DDK example that shows keyword spotting
- Unified Speech APIs to be used (not CRIS)
- All Speech configuration should be configurable including keys, endpoint, voice names and streaming should be used to improve performance (as per the current codebase)
- DirectLine key should be configurable along with UserId (GUID) ensuring Linked Accounts scenarios work as expected. 
- Adaptive Cards are rendered using the Adaptive Cards Rendering SDK for Android
- App respects InputHints returned from the Bot to control the Microphone
- [Documentation](https://github.com/Microsoft/AI/tree/master/solutions/Virtual-Assistant/docs) detailing the Android SDK/Tools required to build, deploy and configure
- Added to the assistant-android folder within the [testharnesses folder](https://github.com/Microsoft/AI/tree/master/solutions/Virtual-Assistant/src/csharp/testharnesses) folder.
- Custom Events sent by the old app are removed and the client should work against a normal Bot as well as VA. 
- Location event is sent on startup with a latitude/longitude value sent enabling PoI scenarios to work. Other bots can just ignore

**Comment by dwhiteddsoft** [comment]
Do I have commit rights on the repo?
