### ISSUE TITLE
personName entity is removed from GeneralLuis.cs when refreshing local model files

### ISSUE THREAD

**Issue by turbozapekanka** [microsoft/botframework-solutions#3312]
#### What project is affected?
Virtual Assistant

#### What language is this in?
C#

#### What happens?
personName entity is removed from GeneralLuis.cs after updating the local models, resulting in compilation error.
This probably happens because personName is only available for English model and not for Spanish.

#### What are the steps to reproduce this issue?
1. Deploy VA with English and Spanish languages
./Deployment/Scripts/deploy.ps1 -languages "en-us,es-mx"
2. Import back remote models to local files:
https://microsoft.github.io/botframework-solutions/virtual-assistant/tutorials/customize-assistant/csharp/4-edit-your-cognitive-models/
./Deployment/Scripts/update_cognitive_models.ps1 -RemoteToLocal

#### What were you expecting to happen?
1. Local files stay unchanged as there are no changes made to remote models after deployment.

#### Screenshot ####
![image](https://user-images.githubusercontent.com/20775323/80140451-9242c400-856d-11ea-9d22-eea660015807.png)

**Comment by taicchoumsft** [comment]
Hi @turbozapekanka , can I have the version of luisgen you have installed?
```
luisgen --version
```

**Comment by taicchoumsft** [comment]
Hi @turbozapekanka , can we ask some clarifying questions?  Did you deploy with `es-mx` or `es-es`? If you deployed with `es-mx`, did the deploy throw any unexpected errors? Did you create an LU file from scratch?

Can you also try reversing the language order (`es-mx, en-us`), and see whether it resolves this issue for you? 

Looping in @lauren-mills

**Comment by turbozapekanka** [comment]
LUISGen version 2.0.2.0

I deployed with es-mx, but that was sometime ago, and there were no errors.
I didn't try es-es.
Can not redeploy at the moment but I see that language order reversal may help as en-us GeneralLuis.cs file will be generated last and will thus overwrite the "faulty" en-mx version

**Comment by darrenj** [comment]
I would also suggest you update your deployment scripts to the latest version which don’t use luisgen but instead the new bf cli. If you still see issues please reopen
