### ISSUE TITLE
Create Adaptive cards

### ISSUE THREAD

**Issue by ipraveenMS** [microsoft/botframework-solutions#3314]
#### What project is affected?
0.8
#### What language is this in?
C#
#### What happens?
What is the functionality equivalent of CreateAdaptiveCardReply in 0.2 botframework
#### What are the steps to reproduce this issue?
I am migrating from a project that was base on 0.2 BF. Which uses CreateAdaptiveCardReply in ActivityEx.cs and that uses BotResponseBuilder. I dont see these two classes or their replacements in BF 0.8. Looked at the examples skills already.
#### What were you expecting to happen?
Documentation of how to address the above issue with examples

**Comment by ipraveenMS** [comment]
It looks like you have removed the SDK to convert adaptiveCard to Activity. We need to figure out how to address this the best since it looks like a tremendous amount of work to convert all of our adaptive cards to the lg fromat.

**Comment by taicchoumsft** [comment]
Hi @ipraveenMS , unfortunately you are right - we have moved to using LG for all adaptive cards. 

Currently we can only suggest to look up the 0.2 release [source](https://github.com/microsoft/botframework-solutions/tree/0.2) and lift the code you will need to continue supporting your adaptive cards.

**Comment by darrenj** [comment]
@ipraveenMS Could you share an example of one of your adaptive cards that you wish to return using a more up to date VA? There should be no reason to change these Adaptive Cards and I believe there might be an LG mechanism to pull in JSON files as part of evaluation (let me check)

**Comment by darrenj** [comment]
Just double checked, within a LG file you can reference a “child” file which is then evaluated by LG so any templating you have inside the Adaptive Card would be honoured as well. An example of [FromFile](https://github.com/microsoft/BotBuilder-Samples/blob/master/experimental/language-generation/docs/Functions-injected-from-LG.md#fromfile) is here which I think will work well for this scenario.

If you share one of your adaptive cards (or something you find representative) we can give you a LG and code example?

**Comment by darrenj** [comment]
Let us know if you need anymore help.
