### ISSUE TITLE
Fallback between skills over trigger

### ISSUE THREAD

**Issue by DingmaomaoBJTU** [microsoft/botframework-solutions#3319]
#### What project is affected?
VA

#### What language is this in?
en-us

#### What happens?
![image](https://user-images.githubusercontent.com/16643193/80442737-3054d680-8940-11ea-9266-3314909a504f.png)
When input yes in calendar skill, VA ask to switch to todo skill, which is a little bit weird.

#### What are the steps to reproduce this issue?
1. Use VA dev demo env
2. input book a meeting, answer "yes" when confirm meeting booking.
3. VA ask whether to switch to todo skill

#### What were you expecting to happen?
For common answer "yes", should not trigger fallback to other skill.

**Comment by taicchoumsft** [comment]
Thanks for reporting this @DingmaomaoBJTU , we will investigate this asap.

**Comment by taicchoumsft** [comment]
Hi @DingmaomaoBJTU , quick question: What version of the solutions project you are using?

**Comment by DingmaomaoBJTU** [comment]
@taicchoumsft the latest VA dev demo environment (build by ryan), I guess it is the latest VA code in next branch.

**Comment by darrenj** [comment]
I’ve taken a quick look at this, as per [this LU file](https://github.com/microsoft/BotBuilder-Samples/blob/master/experimental/language-generation/docs/Functions-injected-from-LG.md#fromfile) it’s likely down to the LU file incorrectly bringing in overlapping intents from the General model. e.g. **cancel** and **confirm** - for example **confirm** has Yes which is then generating overlap.

This needs removing ASAP - I believe we raised this before.

**Comment by lzc850612** [comment]
I'll fix it.

**Comment by lzc850612** [comment]
#3325 will fix it
