### ISSUE TITLE
Update VA with new Enterprise Bot start logic and Channel behavior

### ISSUE THREAD

**Issue by lauren-mills** [microsoft/botframework-solutions#332]

**Comment by NobinJoseRad** [comment]
Seems like the VA is still not responding in msteams channel..

**Comment by lauren-mills** [comment]
@NobinJoseRad the features needed to support Teams have not been added to VA yet. I'll be starting on it this week and will update this issue with progress.

**Comment by NobinJoseRad** [comment]
@lauren-mills  thank you..
