### ISSUE TITLE
Calendar Skill Problems with Microsoft.Bot.Builder 4.8.0 version

### ISSUE THREAD

**Issue by igor17400** [microsoft/botframework-solutions#3320]
#### What project is affected?
Calendar skill chatbot does not compile due to System.TypeLoadException: Could not load type 'Microsoft.Bot,Builder.LanguageGeneration.TemplateEngine' from Assembly 'Microsoft.Bot.Builder.LanguageGeneration, Version=4.8.0.0, Culture=neutral'

#### What language is this in?
Csharp

#### What happens?
I have cloned the Microsfot 's github reository for the Calendar Skill sample, and I have update the Microsoft.Bot.Builder from 4.7.2 to 4.8.0 version. However, this update seems to have created conflicts in the code. As a result the chatbot does not compile due to an error. 

#### What are the steps to reproduce this issue?
Git clone the botframework-solutions, update Microsoft.BotBuilder version to 4.8.0 and compile the Calendar Skill folder after you have published it to Azure.
**PS**  I have added to the code the references to portuguese Brazil language (pt-br). Nevertheless the chatbot was working fine in the 4.7.2 version, but when I upgraded the version it stoped compiling. 

#### What were you expecting to happen?
After you have followed this steps you should see an error as the screenshot below shows.

#### Can you share any logs, error output, etc.?
![capture](https://user-images.githubusercontent.com/42355184/80488993-94be6880-8935-11ea-9f73-f6398aa5c2b4.PNG)

**Comment by taicchoumsft** [comment]
Hi @igor17400, sincere apologies for the confusion. We are in the midst of moving all our skills to a  skills repo, found [here](https://github.com/microsoft/botframework-skills).  The v0.8 skills will be removed from this repo for the upcoming release.  

The calendar skill found in the skills repo has a dependency on `Microsoft.Bot.Solutions v1.0`, which under the hood takes a dependency on the latest botbuilder and language generation (v4.8.1 and v4.8.1-rc0 respectively). 

Please clone the Calendar skill from that repo and give it a test. Thanks!

**Comment by igor17400** [comment]
Thank you for the support!

**Comment by peterinnesmsft** [comment]
Looks like this has been addressed, so resolving issue. @igor17400 if you run into further issues, feel free to reactivate and we can assist further.
