### ISSUE TITLE
Error when VA is migrated to GA 0.8

### ISSUE THREAD

**Issue by Kumar3010** [microsoft/botframework-solutions#3324]
#### What project is affected?
Virtual assistant

#### What language is this in?
C#

#### What happens?
{"parsedStack":[{"assembly":"Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed","method":"Newtonsoft.Json.Serialization.DefaultSerializationBinder.GetTypeFromTypeNameKey","level":0,"line":0},{"assembly":"System.Collections.Concurrent, Version=4.0.14.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a","method":"System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd","level":1,"line":0},{"assembly":"Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed","method":"Newtonsoft.Json.Utilities.ThreadSafeStore`2.Get","level":2,"line":0},{"assembly":"Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed","method":"Newtonsoft.Json.Serialization.DefaultSerializationBinder.GetTypeByName","level":3,"line":0},{"assembly":"Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed","method":"Newtonsoft.Json.Serialization.DefaultSerializationBinder.BindToType","level":4,"line":0},{"assembly":"Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed","method":"Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolveTypeName","level":5,"line":0}],"outerId":"58006341","message":"Could not load assembly 'Microsoft.Bot.Builder.Skills'.","type":"Newtonsoft.Json.JsonSerializationException","id":"35161074"}

#### What are the steps to reproduce this issue?
We have migrated our existing VA as per the steps in https://microsoft.github.io/botframework-solutions/overview/whats-new/0.8-beta/migrate-existing-va-to-0.8/
our VA is in csharp. we have removed the reference of bot.builder.skills as its mentioned to be removed. rather we get the mentioned exception

#### What were you expecting to happen?
VA should run as expected
#### Can you share any logs, error output, etc.?
{"parsedStack":[{"assembly":"Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed","method":"Newtonsoft.Json.Serialization.DefaultSerializationBinder.GetTypeFromTypeNameKey","level":0,"line":0},{"assembly":"System.Collections.Concurrent, Version=4.0.14.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a","method":"System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd","level":1,"line":0},{"assembly":"Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed","method":"Newtonsoft.Json.Utilities.ThreadSafeStore`2.Get","level":2,"line":0},{"assembly":"Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed","method":"Newtonsoft.Json.Serialization.DefaultSerializationBinder.GetTypeByName","level":3,"line":0},{"assembly":"Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed","method":"Newtonsoft.Json.Serialization.DefaultSerializationBinder.BindToType","level":4,"line":0},{"assembly":"Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed","method":"Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolveTypeName","level":5,"line":0}],"outerId":"58006341","message":"Could not load assembly 'Microsoft.Bot.Builder.Skills'.","type":"Newtonsoft.Json.JsonSerializationException","id":"35161074"}

**Comment by Kumar3010** [comment]
`our package references
<PackageReference Include="AdaptiveCards" Version="1.2.4"/>
    <PackageReference Include="WindowsAzure.Storage" Version="9.3.3"/>
    <PackageReference Include="Microsoft.ApplicationInsights" Version="2.12.0"/>
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.12.0"/>
    <PackageReference Include="Microsoft.ApplicationInsights.DependencyCollector" Version="2.12.0"/>
    
     <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.2.2" />
     <PackageReference Include="Microsoft.AspNetCore.Mvc.Formatters.Json" Version="2.1.0" />
     <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="3.0.0" />
    
    <PackageReference Include="Microsoft.Azure.CognitiveServices.ContentModerator" Version="2.0.0"/>
    <PackageReference Include="Microsoft.Azure.CognitiveServices.Language" Version="1.0.1-preview"/>
    <PackageReference Include="Microsoft.Azure.DocumentDB.Core" Version="2.9.2"/>
    <PackageReference Include="Microsoft.Bot.Builder" Version="4.7.2"/>
    <PackageReference Include="Microsoft.Bot.Builder.AI.Luis" Version="4.7.2"/>
    <PackageReference Include="Microsoft.Bot.Builder.AI.QnA" Version="4.7.2"/>
    <PackageReference Include="Microsoft.Bot.Builder.ApplicationInsights" Version="4.7.2"/>
    <PackageReference Include="Microsoft.Bot.Builder.Azure" Version="4.7.2"/>
    <PackageReference Include="Microsoft.Bot.Builder.Dialogs" Version="4.7.2"/>
    <PackageReference Include="Microsoft.Bot.Builder.Integration.ApplicationInsights.Core" Version="4.7.2"/>
    <PackageReference Include="Microsoft.Bot.Builder.Integration.AspNet.Core" Version="4.7.2"/>
    
    
    <PackageReference Include="Microsoft.Bot.Solutions" Version="0.8.0-preview1" />   
    <PackageReference Include="Microsoft.Bot.Builder.TemplateManager" Version="4.7.2"/>
    <PackageReference Include="Microsoft.Bot.Configuration" Version="4.7.2"/>
    <PackageReference Include="Microsoft.Bot.Connector" Version="4.7.2"/>
    <PackageReference Include="Microsoft.Bot.Schema" Version="4.7.2"/>
    <PackageReference Include="Microsoft.Extensions.Configuration.AzureKeyVault" Version="3.0.1"/>
    <PackageReference Include="Microsoft.Extensions.Logging" Version="3.0.1"/>
    <PackageReference Include="Microsoft.Extensions.Options" Version="3.0.1"/>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.2.3"/>
    <PackageReference Include="Microsoft.Azure.Storage.Blob" Version="11.0.0"/>
     <PackageReference Include="Microsoft.Graph" Version="1.19.0" />
     <PackageReference Include = "AdaptiveCards.Rendering.Html" Version="1.2.2"/>  `

**Comment by taicchoumsft** [comment]
Thanks @Kumar3010 , we are investigating this issue now. Will try to repro this going from 0.6 to 0.8 to see what is missing in documentation

**Comment by Kumar3010** [comment]
@taicchoumsft - thank you for the update. one more thing is that  the code works in local emulator. the error which i have posted is on deployed version. we have cleaned the resources and deployed but no luck too

**Comment by Kumar3010** [comment]
@taicchoumsft - could you please provide an update on this issue?

**Comment by taicchoumsft** [comment]
Apologies for the late response. I've tried repro'ing the migration starting from a 4.6.0 VSIX template, and I'm able to deploy a bot to Azure and get responses back from it.  

The version of Newtonsoft that is packaged with Bot Solutions `0.80-preview` is `Newtonsoft.Json 12.0.3`, so I'm a little surprised that we're getting a stack trace with `v12.0.0` in your output.  It's also surprising to see everything working locally but not on Azure. 

If you haven't already, can you try restarting the bot web app?  If that fails, can you try deploying the bot to a new webapp and see if this works? 

There's also a newer version of the Bot solutions package (`0.8.0-preview2`), that fixes a few other bugs.  Can you also upgrade that dependency?

**Comment by darrenj** [comment]
Any update @Kumar3010 ?

**Comment by Kumar3010** [comment]
Hi Team,

we tried with the steps provided but still get the below error:-


[{"outerId":"0","message":"Error resolving type specified in JSON 'Microsoft.Bot.Builder.Skills.SkillContext, Microsoft.Bot.Builder.Skills'. Path 'SkillContext.$type'.","parsedStack":[{"assembly":"Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed","method":"Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolveTypeName","level":0,"line":0},{"assembly":"Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed","method":"Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadMetadataProperties","level":1,"line":0},{"assembly":"Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed","method":"Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject","level":2,"line":0},{"assembly":"Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed","method":"Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal","level":3,"line":0},{"assembly":"Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed","method":"Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateDictionary","level":4,"line":0},{"assembly":"Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed","method":"Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject","level":5,"line":0},{"assembly":"Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed","method":"Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal","level":6,"line":0},{"assembly":"Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed","method":"Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize","level":7,"line":0},{"assembly":"Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed","method":"Newtonsoft.Json.JsonSerializer.DeserializeInternal","level":8,"line":0},{"assembly":"Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed","method":"Newtonsoft.Json.JsonSerializer.Deserialize","level":9,"line":0},{"assembly":"Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed","method":"Newtonsoft.Json.Linq.JToken.ToObject","level":10,"line":0},{"assembly":"Microsoft.Bot.Builder.Azure, Version=4.7.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35","method":"Microsoft.Bot.Builder.Azure.CosmosDbStorage+<ReadAsync>d__14.MoveNext","level":11,"line":0},{"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw","level":12,"line":0},{"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess","level":13,"line":0},{"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification","level":14,"line":0},{"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter.GetResult","level":15,"line":0},{"assembly":"Microsoft.Bot.Builder, Version=4.7.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35","method":"Microsoft.Bot.Builder.BotState+<LoadAsync>d__4.MoveNext","level":16,"line":0},{"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw","level":17,"line":0},{"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess","level":18,"line":0},{"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification","level":19,"line":0},{"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.CompilerServices.ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.GetResult","level":20,"line":0},{"assembly":"Microsoft.Bot.Builder, Version=4.7.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35","method":"Microsoft.Bot.Builder.BotState+BotStatePropertyAccessor`1+<GetAsync>d__7.MoveNext","level":21,"line":0},{"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw","level":22,"line":0},{"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess","level":23,"line":0},{"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification","level":24,"line":0},{"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.CompilerServices.TaskAwaiter`1.GetResult","level":25,"line":0},{"assembly":"Novtar.Core, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null","method":"SetLocaleMiddleware+<OnTurnAsync>d__5.MoveNext","level":26,"line":35,"fileName":"C:\\Users\\BOMMASA6\\NovartisTAD\\Core\\Novtar.Core\\Novtar.Core\\Utility\\SetLocaleMiddleware.cs"},{"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw","level":27,"line":0},{"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess","level":28,"line":0},{"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification","level":29,"line":0},{"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.CompilerServices.ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.GetResult","level":30,"line":0},{"assembly":"Microsoft.Bot.Builder, Version=4.7.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35","method":"Microsoft.Bot.Builder.ShowTypingMiddleware+<OnTurnAsync>d__3.MoveNext","level":31,"line":0},{"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw","level":32,"line":0},{"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess","level":33,"line":0},{"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification","level":34,"line":0},{"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.CompilerServices.ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.GetResult","level":35,"line":0},{"assembly":"Microsoft.Bot.Builder, Version=4.7.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35","method":"Microsoft.Bot.Builder.TelemetryLoggerMiddleware+<OnTurnAsync>d__7.MoveNext","level":36,"line":0},{"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw","level":37,"line":0},{"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess","level":38,"line":0},{"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification","level":39,"line":0},{"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.CompilerServices.ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.GetResult","level":40,"line":0},{"assembly":"Microsoft.Bot.Builder, Version=4.7.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35","method":"Microsoft.Bot.Builder.BotFrameworkAdapter+TenantIdWorkaroundForTeamsMiddleware+<OnTurnAsync>d__0.MoveNext","level":41,"line":0},{"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw","level":42,"line":0},{"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess","level":43,"line":0},{"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification","level":44,"line":0},{"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.CompilerServices.ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.GetResult","level":45,"line":0},{"assembly":"Microsoft.Bot.Builder, Version=4.7.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35","method":"Microsoft.Bot.Builder.MiddlewareSet+<ReceiveActivityWithStatusAsync>d__3.MoveNext","level":46,"line":0},{"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw","level":47,"line":0},{"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess","level":48,"line":0},{"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification","level":49,"line":0},{"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.CompilerServices.ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.GetResult","level":50,"line":0},{"assembly":"Microsoft.Bot.Builder, Version=4.7.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35","method":"Microsoft.Bot.Builder.BotAdapter+<RunPipelineAsync>d__15.MoveNext","level":51,"line":0}],"type":"Newtonsoft.Json.JsonSerializationException","id":"55412629"},{"outerId":"55412629","message":"Could not load assembly 'Microsoft.Bot.Builder.Skills'.","parsedStack":[{"assembly":"Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed","method":"Newtonsoft.Json.Serialization.DefaultSerializationBinder.GetTypeFromTypeNameKey","level":0,"line":0},{"assembly":"System.Collections.Concurrent, Version=4.0.14.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a","method":"System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd","level":1,"line":0},{"assembly":"Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed","method":"Newtonsoft.Json.Utilities.ThreadSafeStore`2.Get","level":2,"line":0},{"assembly":"Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed","method":"Newtonsoft.Json.Serialization.DefaultSerializationBinder.GetTypeByName","level":3,"line":0},{"assembly":"Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed","method":"Newtonsoft.Json.Serialization.DefaultSerializationBinder.BindToType","level":4,"line":0},{"assembly":"Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed","method":"Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolveTypeName","level":5,"line":0}],"type":"Newtonsoft.Json.JsonSerializationException","id":"166

**Comment by darrenj** [comment]
Is this within a test envrionment? If so, could you go to startup.cs and uncomment memorystorage and comment out the CosmosDB line and see if you can experience the same issue.

I think the issue is with old state records referencing types/libraries that have since changed. Hopefully you have a test envrionment so easy to change and validate this theory. If so, clearing out old state conversation records would be the way forward

```csharp
            // Configure storage
            // Uncomment the following line for local development without Cosmos Db
            // services.AddSingleton<IStorage, MemoryStorage>();
            services.AddSingleton<IStorage>(new CosmosDbPartitionedStorage(settings.CosmosDb));
            services.AddSingleton<UserState>();
            services.AddSingleton<ConversationState>();
```

**Comment by Kumar3010** [comment]
Thank you Darrenj. when cleared the old state it worked. 

thanks a lot

**Comment by darrenj** [comment]
Great - moving forwards we won't have this type of breaking change with the structure as we are GA :-)
