### ISSUE TITLE
[Docs] Adding your skill to an assistant

### ISSUE THREAD

**Issue by simoninnyc** [microsoft/botframework-solutions#3327]
/skills/tutorials/create-skill/csharp/7-add-your-skill/

Tutorial fails to mention LUIS dispatch files and how to generate them. Not sure what to do to get past this error:

"Some of the cultures provided to connect from the Skill are not available or aren't supported by your VA."

![SharedScreenshot](https://user-images.githubusercontent.com/11979816/80840133-99e81580-8bca-11ea-8714-edb8626ec952.jpg)

**Comment by taicchoumsft** [comment]
Hi @simonjonesnyc , thanks for reporting this documentation discrepancy.

For now, here are some suggestions to try to unblock you:

1) Try limiting the language of the Skill to a language that your VA supports by passing in the `--languages` flag to `botskills connect`: [https://microsoft.github.io/botframework-solutions/skills/handbook/multilanguage-functionality/](https://microsoft.github.io/botframework-solutions/skills/handbook/multilanguage-functionality/)

2) The `deploy.ps` /  `update_cognitive_models.ps1` scripts create/update the LUIS dispatch model for you, by running [dispatch](https://microsoft.github.io/botframework-solutions/virtual-assistant/tutorials/deploy-assistant/cli/7-create-dispatch-model/) under the hood.  This creates a Dispatch Luis Model that you can then look at and enhance when you log onto [luis.ai](https://luis.ai).

You can deploy a new bot supporting multiple languages, including a locale that the skill supports. e.g.
```
./Deployment/Scripts/deploy.ps1 -languages "en-us, zh-cn"
```

This creates a LUIS dispatch model for each language defined.

**Comment by simoninnyc** [comment]
Thanks for your swift reply @taicchoumsft! 

I ran update_cognitive_models.ps1 which appeared to update the json files in the Resources/Lu folder. I'm guessing these were created the first time I ran deploy.ps1 in any case so it's unclear what more was done. Running the botskills connect command resulted in the same error as before but I eventually managed to get the connect command to work by manually editing the cognitivemodels.json file adding a dispatchModel section. The first attempt failed because it was looking for a file in the en-us folder with .dispatch extension. I then renamed the json file than had been created to .dispatch and it seemed to work. I wondered if changing "type": "dispatch" to "type": "json" as highlighted in my screenshot might have not needed the filename change but I didn't get chance to test that. Not sure why this section isn't added automatically by the deploy script in the first place. I should also add I had to install ludown and luisgen to get the botskills connect script to run.

One thing I'm confused about is the Luis App. There's no mention in the tutorial of manually creating the Luis App at luis.ai so I wonder should the script automatically create this app?

![SharedScreenshot_3](https://user-images.githubusercontent.com/11979816/80867903-dcf6c700-8c64-11ea-926b-23b9ca61a3ab.jpg)

![SharedScreenshot_2](https://user-images.githubusercontent.com/11979816/80867746-c865ff00-8c63-11ea-8d16-427c08d15d84.jpg)

![SharedScreenshot_1](https://user-images.githubusercontent.com/11979816/80867115-60fa8000-8c60-11ea-84e5-45c35f2824db.jpg)

**Comment by Batta32** [comment]
Hi @simonjonesnyc, we **reproduced** the issue you mentioned.

First of all, we noticed that you are executing the `connect` command inside the Email Skil` folder, however it **should be executed** inside your Virtual Assistant folder.

Also, can you verify the **triangulation** of the following language sources:
- The `Dispatch models` available in the Virtual Assistant
- The `languages for the intents` in the [Skill Manifest](https://microsoft.github.io/botframework-solutions/skills/handbook/manifest/)
- The `--languages` argument of the botskills connect command

The only way to successfully execute the connection would be if the `--languages` argument contains the same or less values than the result of the intersection between the Dispatch models languages and the Skill manifest intents languages. By default, `--languages` value is `en-us`.

We followed these **steps** to accomplish the connection of the bots (only en-us language):
1. Open a terminal and go to the Virtual Assistant folder
2. Deploy the Virtual Assistant
> pwsh.exe -File Deployment\Scripts\deploy.ps1
3. Go to the Email Skill folder 
4. Deploy the Email Skill 
> pwsh.exe -File Deployment\Scripts\deploy.ps1
5. Connect the Virtual Assistant to the EmailSkill being located inside the Virtual Assistant folder
> botskills connect --remoteManifest "<YOUR_MANIFEST>" --cs
6. Verify that the Virtual Assistant's [appsettings.json](https://github.com/microsoft/botframework-solutions/blob/master/samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/appsettings.json) contains the information of the connected Email Skill.

Used environment using the branch `master`:
- [[C#] Virtual Assistant](https://github.com/microsoft/botframework-solutions/tree/master/samples/csharp/assistants/virtual-assistant/VirtualAssistantSample)
- [[C#] Email Skill](https://github.com/microsoft/botframework-solutions/tree/master/skills/csharp/emailskill)
- [botskills@1.0.14](https://www.npmjs.com/package/botskills/v/1.0.14) (latest) 

For further information, please read the following documents:
- [Multilanguage functionality](https://github.com/microsoft/botframework-solutions/blob/master/tools/botskills/docs/multilanguage-functionality.md)
- [Connect command](https://github.com/microsoft/botframework-solutions/blob/master/tools/botskills/docs/commands/connect.md)
- [Adding Skills to your Virtual Assistant](https://microsoft.github.io/botframework-solutions/skills/handbook/add-skills-to-a-virtual-assistant/#adding-skills-to-your-virtual-assistant)

Hope this works for you 😊!

**Comment by darrenj** [comment]
@simonjonesnyc Let us know if you need any more help?
