### ISSUE TITLE
[Docs] "protocol : BotFrameworkV3" for skill-manifest endpoints registration 

### ISSUE THREAD

**Issue by nebhagat** [microsoft/botframework-solutions#3329]
/skills/handbook/manifest/

As per the example from the documentation, "BotFrameworkV3" is assigned to protocol for Endpoints section.

Does it also support "BotFrameworkV4"?

**Comment by ryanisgrig** [comment]
Hi @nebhagat,

The `BotFrameworkV3` protocol is referring to the API protocol between channel and bot, used for skill invocation. This is not the same as the Bot Framework SDK v3 and v4. Does that clear it up?

**Comment by nebhagat** [comment]
yes, thanks!
