### ISSUE TITLE
Would be nice if this worked with Visual Studio Code

### ISSUE THREAD

**Issue by bdlawrence13** [microsoft/botframework-solutions#3348]
## User Story
As ...bot developer
I want ...to  be able to run these tutorials in Visual Studio Code
so that ...I don't have to purchase a full license of Visual Studio.

## Acceptance Criteria 
*List your requirements.*
- [ ] ...The tutorials for bot solutions should work in Visual studio code.
- [ ] ...
- [ ] ...

## Resources
*Provide any screenshots or conversation mockups to support your request.*
*Learn how to mock up bot conversations with [.chat files](http://aka.ms/bfchatfile).*

## Notes
*Provide any additional information.*

**Comment by xieofxie** [comment]
Hi, you could use community version https://visualstudio.microsoft.com/vs/community/

**Comment by bdlawrence13** [comment]
Thank you for the suggestion. I have installed community edition and will try this out.

**Comment by darrenj** [comment]
We also have preview .net core templates on our daily builds server but not had much demand for them, feedback welcome
