### ISSUE TITLE
[Docs] How does a VA skill relate to a Bot Framework skill bot?

### ISSUE THREAD

**Issue by JonathanFingold** [microsoft/botframework-solutions#3350]
We added the concept of a skill or skill bot to the SDK back in R7 or so. We should be explicit here whether VA skills are skill bots or something different.

**Comment by peterinnesmsft** [comment]
This feels like a non-issue - our documentation located [here](https://microsoft.github.io/botframework-solutions/index) very clearly states at the top "Bot Framework Skills", and I don't see any obvious mentions of VA skills.

If there is something in particular that is driving this, then feel free to provide information and we can take a look.
