### ISSUE TITLE
Event not processed in MainDialog RouteStepAsync

### ISSUE THREAD

**Issue by manish-95** [microsoft/botframework-solutions#3354]
#### What project is affected?
VA, Skill (0.8 Beta Release)
#### What language is this in?
C#
#### What happens?
Even though I am handling incoming events in the DefaultActivityHandler, and calling the dialog.RunAsync() in case of an event, the event when passed, is not handled in RouteStepAsync() since the step is triggered by a text prompt in the previous step, and the text prompt by design returns an EndOfTurn in case the new activity is not of type message.
This is preventing me from calling any Actions which I have designed, which is a feature of the VA and Skill Templates.
#### What are the steps to reproduce this issue?
1. Setup event handling in DefaultActivityHandler.cs
2. Send an event from the Emulator.
3. There is no response from the Bot.
#### What were you expecting to happen?
The event has to be processed, in RouteStepAsync() and the appropriate Action defined by the event must be triggered.
#### Any screenshots or additional context?
![image](https://user-images.githubusercontent.com/29098159/81777518-a6dfff80-950e-11ea-8981-9a1659843020.png)

**Comment by peterinnesmsft** [comment]
Will take a look into this and get back to you shortly.

**Comment by manish-95** [comment]
Hi @peterinnesmsft , I have found a way around this by creating my own Prompt, which inherits the ActivityPrompt, and using a prompt validator, which allows Activities of both event as well as message to pass through to the RouteStepAsync() method. Would this be the right solution?

**Comment by manish-95** [comment]
@peterinnesmsft  Any updates regarding this?

**Comment by darrenj** [comment]
Hi Manish,

Events should be processed by the below handler within the ActivityHandler which has a default handler for token events. Have you extended this to include your Event type to ensure it's propagated into MainDialog?

```csharp
  protected override async Task OnEventActivityAsync(ITurnContext<IEventActivity> turnContext, CancellationToken cancellationToken)
        {
```

If you have done that and have an active dialog/prompt - have you verified this is capable of accepting an input. If we can validate first it's coming in and being propagated that's the first area of investigation.

If it is - do you have an active dialog/prompt which your effectively pushing the event activity too?

**Comment by manish-95** [comment]
@darrenj Yep, I've added the handler for my case in the OnEventActivityAsync(). In the Main Dialog, the prompt used to go from the IntroStep, to the RouteStep is a TextPrompt, which accepts only Activities of type Message, whereas I am passing an event. As a result , the event is not acted on.
 
As mentioned, I have created a custom prompt from the ActivityPrompt, which I am using instead of the TextPrompt, to handle activities of any type, and switching based on type of incoming activity in the RouteStepAsync. This has solved my issue, however is this the best way to achieve this?

**Comment by darrenj** [comment]
Indeed - this is a good pattern, we actually created an [EventPrompt](https://github.com/microsoft/botframework-solutions/blob/master/sdk/csharp/libraries/microsoft.bot.solutions/Dialogs/EventPrompt.cs) for a similar type of scenario where we needed to wait for an event to proceed (Device integration).

If you have time to share the overall goal your trying to achieve through events happy to have a think about whether we need better framework support to make it easier!

**Comment by manish-95** [comment]
@darrenj Hi! 
We're using the Bot Framework to build an assistant, that is both reactive as well as proactive. On the reactive side, the VA and Skills are well suited to this, with the initial setup that comes with the template. We're trying to take this same template a step further by having the Bot itself trigger certain Actions, based on different Events that we are monitoring. 

Right now, the entire proactive setup only allows to send a message through the SendActivityAsync() method, but what we're trying to do, is to involve user feedback on the proactive message sent. This is slightly difficult with current setup, since there is no way to trigger a particular dialog in a target conversation, through proactive notifications, as the BeginDialogAsync() method would simply start a new dialog in the new Conversation. So what we're now doing to circumvent this particular problem, is that we're sending back-channel events to the particular conversation by fetching conversation details from the ProactiveState entry in Cosmos DB. 
However, the current VA setup does not process Events in the RouteStepAsync(), since TextPrompt will only proceed if an Activity of type Message is encountered. We have instead replaced the TextPrompt, with an ActivityPrompt , and given it a Validator method that allows it to proceed with execution to the next step, in case of Activity of type Message or Event. We decided on ActivityPrompt over the EventPrompt to allow us this flexibility to process multiple types of Activity.
 We've also added Event processing in the OnContinueDialogAsync() method, so as to allow these proactive events to be processed even if there is already an existing Dialog on the stack, in which case, control would not go to the   RouteStepAsync() method. 

Hope this small description gives you some sort of insight into what we're trying to use the VA and Skill for. Please feel free to check back with any doubts or questions.
