### ISSUE TITLE
When the KWS is enabled the TTS stops working

### ISSUE THREAD

**Issue by raafaelima** [microsoft/botframework-solutions#3378]
Hi Everyone,

#### What happens?

When I say the keyword, The app wake, show the animation, as expected. However do not show any signs of recognising my voice from the wake moment, even when I click on the microfone icon. 

#### What language is this in?
Language: 
> Java/Android

SDK: 
> com.microsoft.cognitiveservices.speech:client-sdk:1.12.0

#### Can you share any logs, error output, etc.?

Here is the code Sample:

```
KeywordRecognizer keywordRecognizer = new KeywordRecognizer(AudioConfig.fromDefaultMicrophoneInput());
final KeywordRecognitionModel model = KeywordRecognitionModel.fromStream(inputStream, keyword, false);
final Future<KeywordRecognitionResult> task = keywordRecognizer.recognizeOnceAsync(model);

keywordRecognizer.recognized.addEventListener((o, speechRecognitionResultEventArgs) -> {
      final KeywordRecognitionResult result = speechRecognitionResultEventArgs.getResult();
      if (result.getReason() == ResultReason.RecognizedKeyword) {
        EventBus.getDefault().post(new BotListening());
        botConnector.listenOnceAsync(); 
     } else {
        LogException("Error: got the wrong sort of recognition.");
    }
});

botConnector.recognized.addEventListener((o, speechRecognitionResultEventArgs) -> {
   final String recognizedSpeech = speechRecognitionResultEventArgs.getResult().getText();
   LogInfo("Final result received: " + recognizedSpeech); //NEVER GET HERE
});
```

**Comment by darrenj** [comment]
@olmidy Any thoughts on this?

**Comment by olmidy** [comment]
Your botConnector object should already have keyword support, and this keyword support is separate from the standalone KeywordRecognizer.  The botConnector would have to be configured and initialized, and then enable KWS with the KeywordRecognitionModel by calling bot.startKeywordRecognitionAsync(model).

What app is being used or built here?  Is there a particular reason you want to use the standalone APIs for KeywordRecognizer?

**Comment by raafaelima** [comment]
I am using the [VAClient] (https://microsoft.github.io/botframework-solutions/clients-and-channels/clients/virtual-assistant-client/) of Microsoft as base implementation, on there I have a method to recognise the keyword, and some callbacks, as showed on the code bellow. The problem is, after say the keyword, instead of getting **Do This**, im getting **Computer, Do This.** as recognized text.

Is there a way to ignore the keyword on the recognized text? 
I Try the implementation that I shown above, with the _KeywordRecognizer_ class, to see if the problem goes away, but is not the case.

```
....

final KeywordRecognitionModel value = KeywordRecognitionModel.fromStream(inputStream, keyword, false);
final Future<Void> task = botConnector.startKeywordRecognitionAsync(value);

....

botConnector.recognized.addEventListener((o, speechRecognitionResultEventArgs) -> {
   final recognitionResult result = speechRecognitionResultEventArgs.getResult();
   final ResultReason reason = result.getReason();
   final String recognizedSpeech = result.getText();
   if (!reason.equals(ResultReason.RecognizedKeyword)) {
       LogDebug("Final result received: " + recognizedSpeech + ", intent: " + intentId); 
    }
});
```

**Comment by olmidy** [comment]
At the current time, Direct Line Speech does not strip the keyword from the recognized text. There is discussion about whether this will be supported in the future, but for the time being you will have to strip the keyword yourself via code.
