### ISSUE TITLE
Deploying a custom skill

### ISSUE THREAD

**Issue by andreas-sommer-engenious** [microsoft/botframework-solutions#3394]
When I deploy my custom skill, using the deployment script, all resources get a postfix "bot-skill-luisauthoring-ulpptwf" f.ex. What does that postfix mean and how can I deploy my custom skill without a postfix?
Thanks
Andreas

**Comment by darrenj** [comment]
Postfix is to ensure uniqueness, we saw lots of issues with generic names being used and deployment failing. You can through the parameters file choose to override `suffix` to control this if you want ([ref](https://github.com/microsoft/botframework-solutions/blob/master/samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Deployment/Resources/template.json#L13)).

More information in [this document](https://microsoft.github.io/botframework-solutions/virtual-assistant/handbook/deployment-scripts/) too.
