### ISSUE TITLE
Unexpected argument: XXX when updating models Remote to Local

### ISSUE THREAD

**Issue by turbozapekanka** [microsoft/botframework-solutions#3395]
#### What project is affected?
Virtual assistant

#### What language is this in?
C#

#### What happens?
I get Unexpected argument: XXX where XXX is my authoringkey when when updating cognitive models Remote to Local
The lu files do not seem to be updated with the changes

#### What are the steps to reproduce this issue?
./Deployment/Scripts/update_cognitive_models.ps1 -RemoteToLocal

#### What were you expecting to happen?
local models (lu/qna files) updated with changed made on portals

#### Any screenshots or additional context?
![image](https://user-images.githubusercontent.com/20775323/82468308-4578dd00-9a88-11ea-9355-39a40e07a6b6.png)

**Comment by turbozapekanka** [comment]
Used wrong (old) script

**Comment by edemehmetcan** [comment]
hello what is the good script ? I got the same error. @turbozapekanka

**Comment by turbozapekanka** [comment]
@edemehmetcan there is a workaround.

use "Out-File -Encoding oem" instead of ">" in update_cognitive_models.ps1:

# Update local LU files based on hosted QnA KBs
        foreach ($kb in $models.knowledgebases) {
            Write-Host "> Updating local $($langCode) $($kb.id).qna file ..." -NoNewline
            bf qnamaker:kb:export `
                --endpoint $qnaEndpoint `
                --environment Prod `
                --kbId $kb.kbId `
                --subscriptionKey $kb.subscriptionKey | Out-File -Encoding oem $(Join-Path $qnaFolder $langCode "$($kb.id).json")


This works but I'd not call this a "solution"
It brings questions and the root cause is not clear.

**Comment by turbozapekanka** [comment]
get the updated scripts from this repository, or from the Virtual assistant VS project template.

**Comment by edemehmetcan** [comment]
Hello,

Thanks for the solution mister.

In my case I got the error when "getting files".

[image: image.png]

Regards
EDE

Le jeu. 16 juil. 2020 à 01:23, turbozapekanka <notifications@github.com> a
écrit :
