### ISSUE TITLE
[Docs] needs to be updated

### ISSUE THREAD

**Issue by turbozapekanka** [microsoft/botframework-solutions#3396]
Information on this page seem to be outdated
1) collectionId has been renamed to containerId in appsettings.json
2) missing deploy ps1 script parameters like $createLuisAuthoring, $luisEndpoint
/virtual-assistant/handbook/deployment-scripts/

**Comment by lauren-mills** [comment]
PR in progress for these doc updates! #3388

**Comment by darrenj** [comment]
Closed with #3388 

Thanks @turbozapekanka !
