### ISSUE TITLE
Deployment fails when deploying without CosmosDB

### ISSUE THREAD

**Issue by turbozapekanka** [microsoft/botframework-solutions#3401]
#### What project is affected?
VA

#### What language is this in?
C#

#### What happens?
Deployment fails when using default  parameters.template.json file which has useCosmosDb = false
Deploy log mentions that  "The Resource 'Microsoft.DocumentDB/databaseAccounts/myassistant1wwe3cge' under resource group 'MyAssistant1' was not found."

#### What are the steps to reproduce this issue?
./Deployment/Scripts/deploy.ps1 -name "MyAssistant1" -location "southcentralus" -appPassword "XXX" -luisAuthoringKey "XXX" -luisAuthoringRegion "westus" -luisEndpoint "https://westus.api.cognitive.microsoft.com/" -parametersFile "./Deployment/Resources/parameters.template.json" -languages "en-us,es-es"

#### What were you expecting to happen?
Deployment succeeded
 
#### Can you share any logs, error output, etc.?
[deploy_log.txt](https://github.com/microsoft/botframework-solutions/files/4658868/deploy_log.txt)

#### Any screenshots or additional context?
![image](https://user-images.githubusercontent.com/20775323/82488558-b4b0fa00-9aa5-11ea-8164-6b13226d36c4.png)

**Comment by turbozapekanka** [comment]
FYI: It does work when useCosmosDb is true.

**Comment by darrenj** [comment]
Thanks @turbozapekanka - great spot. I've reproed the issue and I believe this is a regression triggered by a change in the ComosDbProvider which required this entry to be added recently

```json
 {
      "type": "Microsoft.DocumentDB/databaseAccounts/sqlDatabases",
      "name": "[concat(variables('cosmosDbAccountName'), '/', parameters('cosmosDbDatabaseName'))]",
      "apiVersion": "2019-12-12",
      "dependsOn": [
        "[resourceId('Microsoft.DocumentDB/databaseAccounts', variables('cosmosDbAccountName'))]"
      ],
      "properties": {
        "resource": {
          "id": "[parameters('cosmosDbDatabaseName')]"
        },
        "options": {
          "throughput": "[parameters('cosmosDbDatabaseThroughput')]"
        }
      },
    }
```

This change missed the `condition` on `useCosmosDb` meaning it tries to validate incorrectly. 

I've tested this change to the above section in `template.json` - note the condition that's been added.

```json
 {
      "type": "Microsoft.DocumentDB/databaseAccounts/sqlDatabases",
      "name": "[concat(variables('cosmosDbAccountName'), '/', parameters('cosmosDbDatabaseName'))]",
      "apiVersion": "2019-12-12",
      "dependsOn": [
        "[resourceId('Microsoft.DocumentDB/databaseAccounts', variables('cosmosDbAccountName'))]"
      ],
      "properties": {
        "resource": {
          "id": "[parameters('cosmosDbDatabaseName')]"
        },
        "options": {
          "throughput": "[parameters('cosmosDbDatabaseThroughput')]"
        }
      },
      "condition": "[parameters('useCosmosDb')]"
    }
```

If you get a moment could you validate this change works for you?

**Comment by turbozapekanka** [comment]
@darrenj 
Yes it works now.
Thanks!
