### ISSUE TITLE
All QnaMaker KBs are deployed with the same name, some KBs are not published

### ISSUE THREAD

**Issue by turbozapekanka** [microsoft/botframework-solutions#3402]
#### What project is affected?
VA

#### What language is this in?
C#

#### What happens?
Deployment script deploys QnAmaker KBs with the same name
Some KBs are not published

#### What are the steps to reproduce this issue?
Deploy two languages:
./Deployment/Scripts/deploy.ps1 -name "MyAssistant1" -location "southcentralus" -appPassword "XXX" -luisAuthoringKey "XXX" -luisAuthoringRegion "westus" -luisEndpoint "https://westus.api.cognitive.microsoft.com/" -parametersFile "./Deployment/Resources/parameters.template.json" -languages "en-us,es-es"

#### What were you expecting to happen?
Each KB is deployed with unique name, e.g. MyAssistant1_Faq_en-us, MyAssistant1_Faq_es-es, MyAssistant1_Chitchat_en-us...

All KBs are published

#### Any screenshots or additional context?
![image](https://user-images.githubusercontent.com/20775323/82492099-45d69f80-9aab-11ea-8a2c-57e641918925.png)

**Comment by turbozapekanka** [comment]
Luis does a better job naming the models:
![image](https://user-images.githubusercontent.com/20775323/82492319-a06ffb80-9aab-11ea-8677-18e1ab74ff4d.png)

**Comment by turbozapekanka** [comment]
Not sure but some KBs not published might have something to do with QnaMaker Search sku being free

**Comment by darrenj** [comment]
Good spot - yes the Search SKU is one likely issue. Could you look at the deploy_cognitive_models log file (and perhaps the other logs files) to see if there were any warnings/errors that weren’t made clearer.

We spotted the issue around QnA being the same name which is confusing and working on a change (deployment script only). Will update this issue with the steps (if you want to do now ahead of the PR). @peterinnesmsft could you share the steps you looked at?

**Comment by turbozapekanka** [comment]
Yes the KBs are published successfully when I changed the search sku to "basic"
It uses 5 indexes where "free" tier only allows 3.

**Comment by peterinnesmsft** [comment]
Sorry for the delays here. @turbozapekanka PR is now out with the fix for this. It's a small one-line fix in the qna_functions.ps1 script, so feel free to take a look and update your local script. That should help solve the problem.

**Comment by darrenj** [comment]
Resolved by #3430 

Will be incorporated into a new VSIX release likely next week but you can get from the next branch ahead of that. Thanks for reporting!
