### ISSUE TITLE
update_cognitive_models.ps1 does not work

### ISSUE THREAD

**Issue by turbozapekanka** [microsoft/botframework-solutions#3412]
#### What project is affected?
Virtual assistant

#### What language is this in?
C#

#### What happens?
update_cognitive_models.ps1 script does not update the remote models

#### What are the steps to reproduce this issue?
1. Deploy VA template
2. Change LU/Qna files (e.g. add new utterance)
3. run update_cognitive_models.ps1

#### What were you expecting to happen?
Remote Luis/Qna models updated with local changes

#### Can you share any logs, error output, etc.?
[update_cognitive_models_log.txt](https://github.com/microsoft/botframework-solutions/files/4671065/update_cognitive_models_log.txt)

#### Any screenshots or additional context?
![image](https://user-images.githubusercontent.com/20775323/82720514-f09cb880-9c79-11ea-9c0c-521a6fff7cac.png)

**Comment by darrenj** [comment]
Thanks - I can't repro the issue right away - can you verify the versions of these CLI tools on your machine please?

BF (bf -v)
Dispatch (dispatch -v)

**Comment by turbozapekanka** [comment]
bf -v
@microsoft/botframework-cli/4.9.0 win32-x64 node-v12.16.3

dispatch -v
1.6.9

**Comment by darrenj** [comment]
Hi @turbozapekanka 

I've just deployed a fresh VA and run deployment, then update_cognitive_models

![image](https://user-images.githubusercontent.com/33519520/83006659-7b7b0b80-a00a-11ea-809a-7895df656aec.png)

To rule out anything with older scripts can you double check your scripts look the same [as these](https://github.com/microsoft/botframework-solutions/tree/master/samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Deployment/Scripts)?

**Comment by darrenj** [comment]
Could you also confirm node version too (node -v)

**Comment by turbozapekanka** [comment]
node v12.16.3
PowerShell 7.0.1

the scripts are exactly the same.

I deployed two languages though, en-us and es-es.
here is the deploy command I used:
./Deployment/Scripts/deploy.ps1 -name "MyAssistant1" -location "southcentralus" -appPassword "XXX" -luisAuthoringRegion "westus" -parametersFile "./Deployment/Resources/parameters.template.json" -languages "en-us,es-es"

parameters.template.json:
[parameters.template.json.txt](https://github.com/microsoft/botframework-solutions/files/4689299/parameters.template.json.txt)

**Comment by turbozapekanka** [comment]
Confirming https://github.com/saikumaru/botframework-solutions/commit/70c40e3df6a3f22af01ea367ccbbc3ea21be9260 fixes the issue

**Comment by darrenj** [comment]
Thanks both - good spot, will double check why my repro wasn't working. Commented on the PR
