### ISSUE TITLE
Conversation control is not passed back to VA after skill completes dialog

### ISSUE THREAD

**Issue by okulygin** [microsoft/botframework-solutions#3413]
#### What project is affected?
Virtual Assistant

#### What language is this in?
en-us

#### What happens?
When skill dialog is completed, all subsequent requests are still routed to the skill, instead of being handled by the VA... 
only `cancel` helps to bring control back to VA.

#### What are the steps to reproduce this issue?
1. trigger any skill dialog through VA (show outages)
2. after dialog responded ask `help` 
#### What were you expecting to happen?
**Expected**: VA `help` dialog is triggered
**Actual**: Skill's `help` dialog is triggered, despite that skill has completed the conversation via 
```cs
// EndOfConversation activity should be passed back to indicate that VA should resume control of the conversation
                IEndOfConversationActivity endOfConversation = Activity.CreateEndOfConversationActivity();
                endOfConversation.Code = EndOfConversationCodes.CompletedSuccessfully;
                _ = await stepContext.Context.SendActivityAsync(endOfConversation, cancellationToken: cancellationToken);

                return await stepContext.EndDialogAsync(cancellationToken: cancellationToken);
```
#### Any screenshots or additional context?
Example: ![image](https://user-images.githubusercontent.com/2973503/82736923-f928d980-9ce1-11ea-84d9-9ad88fe5f297.png)

**Comment by xieofxie** [comment]
Hi, 'help' is specially handled here https://github.com/microsoft/botframework-solutions/blob/19249a139d1aaebfa16dde3610d36fd56d0ce301/samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Dialogs/MainDialog.cs#L261

It will be routed to skill in skill mode.
Do you meet other utterances that not work correctly? Thanks

**Comment by darrenj** [comment]
Let us know if you have instances beyond `help` that get routed back after a skill has finished. I've validated that skill termination works OK. Can you also confirm what VA version your on if you still have an issue?
