### ISSUE TITLE
[VA] Handle ITokenExchangeConfig properly

### ISSUE THREAD

**Issue by xieofxie** [microsoft/botframework-solutions#3414]
#### What project is affected?

VA

#### What language is this in?

C#

#### What happens?

Unexpected exception as described below

#### What are the steps to reproduce this issue?

1 in VA's appsettings.json, remove tokenExchangeConfig part
2 run VA and it reports an exception:
![image](https://user-images.githubusercontent.com/2876650/82973079-1c68c700-a009-11ea-8d86-0d47d8f532a8.png)

#### What were you expecting to happen?

Since currently in Startup here, we allow empty ITokenExchangeConfig 
 https://github.com/microsoft/botframework-solutions/blob/19249a139d1aaebfa16dde3610d36fd56d0ce301/samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Startup.cs#L154
Remove that part should not cause any error.

#### Any screenshots or additional context?

In TokenExchangeSkillHandler's constructor, we always require ITokenExchangeConfig here: https://github.com/microsoft/botframework-solutions/blob/19249a139d1aaebfa16dde3610d36fd56d0ce301/samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/TokenExchange/TokenExchangeSkillHandler.cs#L42

Then if ITokenExchangeConfig is not set, there will be the above error.

Should we
1 when ITokenExchangeConfig is empty, not add TokenExchangeSkillHandler
2 do not set ITokenExchangeConfig in constructor and query it in services dynamically in TokenExchangeSkillHandler
3 require to set ITokenExchangeConfig

From my point of view, 2 is the correct fix.

Thanks

**Comment by darrenj** [comment]
Can you please fill out the issue template with more information? i.e. when does this happen, repro, etc? Thanks

**Comment by xieofxie** [comment]
@darrenj OK, I updated for these information

**Comment by darrenj** [comment]
Agree - do you want to submit a PR for option 2? Thanks

**Comment by xieofxie** [comment]
OK
