### ISSUE TITLE
App Insights telemetry missing key fields from dashboards 

### ISSUE THREAD

**Issue by igarcia7** [microsoft/botframework-solutions#3416]
#### What project is affected?
currently on latest GA solution -  4.9.1  and Microsoft.Bot.Solutions(1.0.0) 

#### What language is this in?
English
#### What happens?
Following Analytics documentation to read telemetry from Bot located [https://microsoft.github.io/botframework-solutions/solution-accelerators/tutorials/view-analytics/1-intro/]

Once template is loaded with App insights key, several of the dashboards show error message of missing fields such as Interaction(UserUtterance) and (BotResponseText). Screenshot below. 
If I click "Fix This", it removes the fields above and dashboard does not show data. 

#### What are the steps to reproduce this issue?
To reproduce, follow the steps on the link below. 
[https://microsoft.github.io/botframework-solutions/solution-accelerators/tutorials/view-analytics/1-intro/]

#### What were you expecting to happen?
Either the template needs to be updated to reflect the latest changes on the bot framework or documentation to show correct fields on the telemetry to use. 

#### Can you share any logs, error output, etc.?
error below. 
#### Any screenshots or additional context?

![Powerbierror](https://user-images.githubusercontent.com/52753806/82909168-e8bd6c80-9f36-11ea-8d3a-802e538d7bad.png)

**Comment by darrenj** [comment]
By default the out of the box VA doesn't collect personally identifiable information (a recent change), you need to opt into this. Can you take a look at [this PR for a doc change](https://github.com/microsoft/botframework-solutions/pull/3415) and see if it resolves your problem please?

**Comment by igarcia7** [comment]
Thanks for the quick response Darren. i followed the instructions and changed the telemetry middleware to true, but i am still receiving the error above where is missing several Interactions fields. 

I also changed the interactions query to add text values, but those fields are still showing null. Is this also a step that needs to be done as part of the PII instructions? 
(https://github.com/microsoft/botframework-solutions/issues/3126#issuecomment-623100546)

**Comment by darrenj** [comment]
I wonder if it might be down to older data not having the right information. If this is a dev environment could you try creating a new resource, updating `appsettings.json` to reflect the new instrumentation key and start afresh with a new powerbi template pointing at this?

If this works then I can ask the team to look at a change to the powerbi template to make it more defensive if data is "missing" on some rows.

**Comment by igarcia7** [comment]
I created a new resource, deployed it and changed appsettings to reflect the new instrumentation key, but i am still receiving errors on several tabs. Mainly missing Bot Responses and the user utterances columns from the Interactions table. 

Are you able to reproduce this on your end? 

![image](https://user-images.githubusercontent.com/52753806/83075239-80a77d00-a041-11ea-94a7-e981aaa60d41.png)

**Comment by darrenj** [comment]
Thanks for helping narrow the problem down. I've managed to repro this morning and there seems to be a regression somewhere, Power BI Desktop I think as I can't see anything that has changed. Anyway - I've tweaked the template and attaching a version to see if that helps (with both the new AppInsights key and the old one you had?

[virtual-assistant-analytics-sample-test.zip](https://github.com/microsoft/botframework-solutions/files/4694433/virtual-assistant-analytics-sample-test.zip)

**Comment by igarcia7** [comment]
Thanks for reproducing on your end. I connected AppInsights to the new template you sent over and the fields are now valid due to the datatype change both resources i have. 

There are more issues i am afraid, the data is null for those tables and thus the visuals are empty. 
![image](https://user-images.githubusercontent.com/52753806/83157156-44bbf880-a0d1-11ea-9728-08bf15b640f1.png) Is the Data populating on your end successfully with the changes to the teoplate? 

Another dashboard tab that i noticed changed once we upgraded to the GA version is Word Cloud, the text column under EventTelemetry is empty which is what populates this visual. 

Let me know if you are also seeing this behavior on your end and could be changes made on the Telemetry SDK...

**Comment by darrenj** [comment]
Data is showing for me - if you click on a conversation ID on the top you should see conversations appearing. Important to ensure that TelemetryMiddleware code change is applied to collect the utterance information which I think you've already applied.

![image](https://user-images.githubusercontent.com/33519520/83159993-8c0cae00-a0fe-11ea-9792-378f891c59e9.png)

Also validated Word Cloud tab :)

![image](https://user-images.githubusercontent.com/33519520/83171370-eb25ef00-a10d-11ea-9c34-c745cff60a00.png)

**Comment by igarcia7** [comment]
Unfortunately clicking on the Conversation ID does not display the conversations. 
Are you currently on GA and 1.0.0 for your solution? 
![image](https://user-images.githubusercontent.com/52753806/83172521-b69e3d00-a0e5-11ea-9d06-e03333122dcb.png)

**Comment by igarcia7** [comment]
I noticed the interactions table for those columns are empty, is that normal or is there a query that i am missing to generate values for those fields? 

![image](https://user-images.githubusercontent.com/52753806/83176743-fbc56d80-a0eb-11ea-9645-ced0c4f2a098.png)

**Comment by darrenj** [comment]
Hi - Just checked, this is what I have. User Utterance, Bot Response should all be set providing of course you have the Telemetry middleware configured to collect PII information for VA and/or any skills

![image](https://user-images.githubusercontent.com/33519520/83184051-c38c5200-a120-11ea-90fc-bb2d4860c83c.png)

**Comment by darrenj** [comment]
Could you perhaps share the section of the startup.cs configuration file you have configuring telemetry and confirm the BF SDK version too?

Thanks

**Comment by igarcia7** [comment]
Hey Darren, thanks for the quick response. We did have the PII information set on Startup.cs on both projects, but after reconnecting the template a few times and deleting the global permissions it started working. I am guessing the app IDs were being conflicted. I was able to test with the Bot emulator and generate User Utterance and Bot response data. Thanks!

**Comment by darrenj** [comment]
Woo hoo! Thanks for helping us out!

**Comment by 007-fr** [comment]
Thanks Darrenj !
