### ISSUE TITLE
Need interfaces for TelemetryLuisRecognizer and TelemetryQnAMaker

### ISSUE THREAD

**Issue by gabog** [microsoft/botframework-solutions#343]
In order to implement unit tests, we need interfaces for TelemetryLuisRecognizer and TelemetryQnAMaker so we can wrote mock and fake classes, avoid roundrips to the server and stage the results that the tests expects from the services.

**Describe the solution you'd like**
We would like to have a ITelemetryLuisRecognizer and ITelemetryQnAMaker to use in BotServices that can be replaced by a fake implementation during unit tests.

**Additional context**
Here is a sample of the FakeLuisRecognizer we are using based on IRecognizer, we would like to be able to do the same using an ITelemetryLuisRecognizer and an ITelemetryQnAMaker:

    public class FakeLuisRecognizer : IRecognizer
    {
        private readonly string _defaultIntent;
        private readonly Dictionary<string, Dictionary<string, JObject>> _entityMapping = new Dictionary<string, Dictionary<string, JObject>>();
        private readonly Dictionary<string, string> _intentMapping = new Dictionary<string, string>();

        public FakeLuisRecognizer(string defaultIntent)
        {
            _defaultIntent = defaultIntent;
        }

        public async Task<RecognizerResult> RecognizeAsync(ITurnContext turnContext, CancellationToken cancellationToken)
        {
            var utterance = turnContext.Activity.Text;
            var intentScore = new IntentScore {Score = 1, Properties = new Dictionary<string, object>()};

            var result = new RecognizerResult
            {
                Text = utterance,
                Intents = new Dictionary<string, IntentScore> {{GetIntent(utterance), intentScore}}
            };

            if (!string.IsNullOrEmpty(utterance) && _entityMapping.ContainsKey(utterance))
            {
                result.Entities = BuildEntitiesJObject(_entityMapping[utterance]);
            }

            return await Task.FromResult(result);
        }

        public Task<T> RecognizeAsync<T>(ITurnContext turnContext, CancellationToken cancellationToken) where T : IRecognizerConvert, new()
        {
            throw new NotImplementedException();
        }

        public void AddIntentResult(string utterance, string intent)
        {
            if (!_intentMapping.ContainsKey(utterance))
            {
                _intentMapping.Add(utterance, intent);
            }
        }

        private string GetIntent(string utterance)
        {
            if (!string.IsNullOrEmpty(utterance) && _intentMapping.ContainsKey(utterance))
            {
                return _intentMapping[utterance];
            }

            return _defaultIntent;
        }

        public JObject BuildEntitiesJObject(Dictionary<string, JObject> entities)
        {
            if (entities.Keys.Count == 1)
            {
                return entities.ElementAt(0).Value;
            }

            var jsonString = new StringBuilder("{");
            for (var i = 0; i < entities.Count - 1; i++)
            {
                jsonString.Append(JsonConvert.SerializeObject(entities.ElementAt(i).Value)
                        .Replace("{", "")
                        .Replace("}", ""))
                    .Append(",");
            }

            jsonString.Append(JsonConvert.SerializeObject(entities.ElementAt(entities.Count - 1).Value)
                    .Replace("{", "")
                    .Replace("}", ""))
                .Append("}");

            return JObject.Parse(jsonString.ToString());
        }

        public void AddEntityResult(string utterance, Dictionary<string, JObject> entities)
        {
            _entityMapping.Add(utterance, entities);
        }
    }

**Comment by darrenj** [comment]
Assigning @ryanlengel to consider as part of the telemetry spec/changes we are making for Ent-Template and VA in Titanium.

**Comment by gabog** [comment]
Thanks, FYI, I created the interfaces I need in a fork I have, I will post a PR for your review to see if you can take any of that.

**Comment by ryanisgrig** [comment]
Sounds great, thanks Gabo. I'm tracking all of our telemetry spec/changes at #354

**Comment by gabog** [comment]
Hi Ryan, I added the interfaces I am using to create fakes in unit tests in the PR: https://github.com/Microsoft/AI/pull/362

Let me know what you think.

Gabo

**Comment by darrenj** [comment]
Thanks Gabo, I did some work previously to enable validation of data sent to AppInsights which could be a further option in this space, let's take this and I'll propose additional capabilities in this space.

**Comment by darrenj** [comment]
merged #362
