### ISSUE TITLE
[Docs] Updating a connected skill, errors with example

### ISSUE THREAD

**Issue by saikumaru** [microsoft/botframework-solutions#3432]
/skills/handbook/botskills/

In the given example
`botskills update --botName <YOUR_BOT_NAME> --remoteManifest "https://<YOUR_SKILL_NAME>.azurewebsites.net/manifest/manifest-1.1.json" --luisFolder <YOUR_LUIS_FOLDER_PATH> --cs`

--botName is an invalid parameter, also not mentioned in the document either
https://github.com/microsoft/botframework-solutions/blob/master/tools/botskills/docs/commands/update.md

**Comment by Batta32** [comment]
Thanks @saikumaru for reporting this issue! We will be updating the botskills documentation 😊!

**Comment by Batta32** [comment]
@saikumaru - we created the PR #3438 in order to update the botskills documentation. If you have any feedback, feel free to comment it in the PR 😊
