### ISSUE TITLE
[Doc] _Dispatch.json doesnt get updated with newly added utterances in skill LUIS app

### ISSUE THREAD

**Issue by saikumaru** [microsoft/botframework-solutions#3435]
/virtual-assistant/tutorials/customize-assistant/csharp/4-edit-your-cognitive-models/

upon running
`.\Deployment\Scripts\update_cognitive_models.ps1 -RemoteToLocal`

Expect the file at below path to be updated with newly added intents to the Skill's LUIS model.
but it is not.

Deployment\Resources\Dispatch\en-us\XXXen-us_Dispatch.json

Is this expected? My assumption is that it should update the dispatch module with all the associated  Skill LUIS models' utterances

**Comment by darrenj** [comment]
If you look at the LU files for your assistant - do you see the additional utterances added there? RemoteToLocal is around ensuring updated LU files on disk from changes in the LUIS portal rather than updating the dispatch model JSON file on disk?

**Comment by saikumaru** [comment]
Well, looks I misinterpreted the logs, which say its updating some dispatch files.

.\Deployment\Scripts\update_cognitive_models.ps1 -RemoteToLocal
> Getting config file ...Done.
> Updating local en-us General.lu file ...Done.
> Parsing en-us General LU file ...Done.
> Running LuisGen for General app ...Done.

 Dispatch update for General LUIS
> Adding en-us General app to dispatch model ... Done.
> Updating local en-us Chitchat.qna file ...Done.
> Updating local en-us Faq.qna file ...Done.

 Dispatch update for QnA
> Adding en-us Faq kb to dispatch model ...Done.
> Updating en-us dispatch model ...Done.
> Running LuisGen for Dispatch app...Done.
> Update complete.

and when it does that, was expecting it to pick the Luis of the skill as well for dispatch.

### Real issue
But infact, would it be the below command, to add the skill's modified Luis to the dispatch?
`botskills update --botName <YOUR_BOT_NAME> --remoteManifest "https://<YOUR_SKILL_NAME>.azurewebsites.net/manifest/manifest-1.1.json" --luisFolder <YOUR_LUIS_FOLDER_PATH> --cs`

I guess thats where the problem is, this command is actually building a file with below name, in the skill's Luis folder
`<YOUR_SKILL_NAME>(1).luis'
note the "(1)" included in the file name

but again down the line, the script seems to refer the older version with name
`<YOUR_SKILL_NAME>.luis'
without the "(1)" in the file name

eventually not updating the dispatch. Infact everytime you run the update it increments to a new file, but should have actually replaced the .luis file?

**Comment by saikumaru** [comment]
@darrenj any advice please?

The botskills version is
1.0.15

**Comment by saikumaru** [comment]
hi @pavolum is there a workaround for this till it is fixed please?

**Comment by pavolum** [comment]
@saikumaru excuse the delay in getting back to you. I have reproduced your issue and can confirm this erroneous  behavior. I am in touch with the folks who manage the botskills CLI tool to work on a fix. In the short term, I believe this is a bug in the .15 release so you may be able to downgrade for a quick and dirty fix. 
I will reach out tomorrow with more info and a potential work around.

**Comment by pavolum** [comment]
@saikumaru the botSkills tool will have a fix for this shortly and are tracking the issue [here]
(https://github.com/microsoft/botframework-solutions/issues/3480)
In the meantime there are a couple workarounds you can employ. The main ones being disconnecting and reconnecting the skill which will trigger the correct dispatch file to generate or downgrading your botskills cli version. This is not an ideal workaround but should unblock you for the time being while we wait on the botskills fix which should be in shortly.
