### ISSUE TITLE
appName updates to luis_functions.ps1 didn't get added to template

### ISSUE THREAD

**Issue by ericchansen** [microsoft/botframework-solutions#3439]
#### What project is affected?

The template files.

#### What language is this in?

C#

#### What happens?

`update_cognitive_models.ps1` doesn't work. This is because `$appName` is missing.

It's missing here.

https://github.com/microsoft/botframework-solutions/blob/5166ed97d85a307bc7c840c498509a1309e5970d/templates/csharp/VA/VA/Deployment/Scripts/luis_functions.ps1#L56-L76

And here.

https://github.com/microsoft/botframework-solutions/blob/5166ed97d85a307bc7c840c498509a1309e5970d/templates/csharp/Skill/Skill/Deployment/Scripts/luis_functions.ps1#L56-L76

Note that this was addressed in the samples in commit 7055299349d6483.

#### What are the steps to reproduce this issue?

Try to use `update_cognitive_models.ps1`.

#### What were you expecting to happen?

It works.

#### Can you share any logs, error output, etc.?

Not necessary.

#### Any screenshots or additional context?

Commit 7055299349d64 didn't update the template files.

**Comment by ericchansen** [comment]
This is more evidence for how I wish that

1. The scripts were all located in one place, and that there weren't 5 or so copies of them in this repo.
2. Each sample was its own repo, such that I could easily create my bot projects NOT from a template, but from simply a git fork. This would allow me to easily pull your upstream changes.

**Comment by darrenj** [comment]
Resolved last week in #3419. Feel free to pull the latest script from the `next` branch - e.g. [here](https://github.com/microsoft/botframework-solutions/blob/next/samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Deployment/Scripts/luis_functions.ps1)

Whilst we have explored options to have one version of the script and copy them around this isn't possible without post build steps which cause their own issues.
