### ISSUE TITLE
Linked accounts is no longer working

### ISSUE THREAD

**Issue by xieofxie** [microsoft/botframework-solutions#3444]
#### What project is affected?
Linked accounts in master
#### What language is this in?
C#
#### What happens?
It is no longer working
#### What are the steps to reproduce this issue?
* Setup according to document https://microsoft.github.io/botframework-solutions/solution-accelerators/samples/linked-accounts/
* When opening, 'An IIdentity is required in TurnState for this operation.' error https://github.com/microsoft/botbuilder-dotnet/blob/03a51e1e09d36cd8c4e8f1dcde6263e5d62e806e/libraries/Microsoft.Bot.Builder/BotFrameworkAdapter.cs#L1585
* After setting IIdentity, it will be 'bad request' because 'user id is incorrect'. It seems the server has high security for generating sign in url now.

**Comment by KayMKM** [comment]
I met the "bad request" issue again.

**Comment by lauren-mills** [comment]
Resolved by linked PR #3540
