### ISSUE TITLE
Batch files used for deployment are a blocker on OSX platforms

### ISSUE THREAD

**Issue by darrenj** [microsoft/botframework-solutions#345]
**Project**
Virtual Assistant, Enterprise Bot Template

**Description**
The Virtual Assistant and ET have moved to a batch file to automate calls to ludown (e.g.  update_all_deployment_scripts) simplifying deployment. However .bat files are not supported on OSX

**To Reproduce**
Run a batch file on OSX

**Expected behavior**
All scripts work across key platforms .e.g Linux, windows, osx

**Suggested resolution**
Create an initial powershell version to share with the customer then we can explore:

- Moving to PowerShell although this increases deployment complexity as these scripts won't be signed requiring [further steps](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.security/set-executionpolicy?view=powershell-6).
- Provide both
- I'll sync with the SDK team to see if they have a strategy for this that we can align to too

**Comment by lauren-mills** [comment]
closed by #389 

Deployment moved to powershell scripts
