### ISSUE TITLE
[Docs] Manifest docs

### ISSUE THREAD

**Issue by esoler-sage** [microsoft/botframework-solutions#3456]
In Manifest (/skills/handbook/manifest/) the manifest points to 
> https://schemas.botframework.com/schemas/skills/skill-manifest-2.0.0.json
but should point to
> https://schemas.botframework.com/schemas/skills/v2.0/skill-manifest.json
isn't it?
Even there's some reference to `dispatchModels` that only exists on
> https://schemas.botframework.com/schemas/skills/v2.1/skill-manifest.json

Which one is the proper one?

Thanks

**Comment by sidmore** [comment]
@lauren-mills can you please help me with this. I dont have enough context to respond.

**Comment by lauren-mills** [comment]
@esoler-sage I'm working with the Bot Builder SDK team to get more clarity around the latest schemas. I will follow up as soon as I hear back.

**Comment by gabog** [comment]
Hi, we updated the folder structure in https://github.com/microsoft/botframework-sdk/tree/master/schemas/skills/ to be simplify naming and organize samples a bit better. So

- [skill-manifest-2.0.0.json](https://schemas.botframework.com/schemas/skills/skill-manifest-2.0.0.json) and [skill-manifest-2.1.preview-1.json](https://schemas.botframework.com/schemas/skills/skill-manifest-2.1.preview-1.json) are left there for backward compat and should not be used. You should use [skills/v2.0/skill-manifest.json](https://schemas.botframework.com/schemas/skills/v2.0/skill-manifest.json) or [v2.1/skill-manifest.json](https://schemas.botframework.com/schemas/skills/v2.1/skill-manifest.json) instead.
- I need to confirm but I think that as of now, PVA only works with [skills/v2.0/skill-manifest.json](https://schemas.botframework.com/schemas/skills/v2.0/skill-manifest.json)
- [v2.1/skill-manifest.json](https://schemas.botframework.com/schemas/skills/v2.1/skill-manifest.json) is the latest and that is the one you should use if you need to support language models and dispatch. 
- The files in the [v2.1.preview-1](https://github.com/microsoft/botframework-sdk/tree/master/schemas/skills/v2.1.preview-1) is also there for backward compat, 2.1 shouln't be used instead. 

Makes sense?
