### ISSUE TITLE
Issue while running the botconnect command

### ISSUE THREAD

**Issue by DishaAgarwal** [microsoft/botframework-solutions#3462]
####  I get an error message every time I try to deploy azure resources by using the following command:
./Deployment/Scripts/deploy.ps1 

#### Screenshots:
<img width="1440" alt="Screenshot 2020-06-10 at 6 05 25 PM" src="https://user-images.githubusercontent.com/11506427/84398105-256ab280-ac1d-11ea-9796-cea1d6e96775.png">

**Comment by sidmore** [comment]
@DishaAgarwal i did retry provisioning a new VA today and did not see the issue. Can you please let me know the repo url you used to clone?

**Comment by DishaAgarwal** [comment]
I managed to create a VA. The issue i was running into was creating a resource with the same name as my bot. I used a pre-existing resource as Botname to make it work.
However, when I am trying to connect a skill to my VA I get the following error: 

The 'endpointUrl' property of the selected endpoint contains invalid characters or does not comply with the URL format. If you didn't select any endpoint, the first one is taken by default.

Could you please advise what I should do to solve for it. I am running the following command:
botskills connect --remoteManifest "https://<YOUR_SKILL_NAME>.azurewebsites.net/manifest/manifest-1.1.json" --cs

**Comment by siddimore** [comment]
@DishaAgarwal Can you please let me know which skill are you trying to connect with VA. The error most likely mean you are running the botskills connect command possibly from Skill directory rather than VA directory.

**Comment by DishaAgarwal** [comment]
I am confident that I am running the command within the VirtualAssistantSample. I deployed the SkillSample and then ran the botconnect command within the VirtualAssistantSample

Is there any other skill repo that I can work with?

**Comment by DishaAgarwal** [comment]
PFA, the screenshot with the error related to endpointUrl
![endpointUrl_error](https://user-images.githubusercontent.com/11506427/85841101-37bb2380-b7bb-11ea-97e5-746b49702d3d.png)

**Comment by DishaAgarwal** [comment]
@siddimore, I think there was an issue with the URL requiring lowercase characters. I temporarily down-cased the URL to move ahead. Let me know if there is an update.

**Comment by lauren-mills** [comment]
@DishaAgarwal - Can you confirm you had to make the endpoint URL in the manifest lowercase for this to work? Or was it the URL in the connect command itself?

**Comment by DishaAgarwal** [comment]
@lauren-mills Hi, I had to make the endpoint URL in the manifest to lowercase.

**Comment by lauren-mills** [comment]
Ok, thanks. Can you run "botskills -v" and let me know the version?

**Comment by peterinnesmsft** [comment]
Change has been checked into our next branch, and will be released as part of our next release. We will aim for early-mid September to do so.
