### ISSUE TITLE
es-es General Luis model is deployed with no utterances in ExtractName intent

### ISSUE THREAD

**Issue by turbozapekanka** [microsoft/botframework-solutions#3464]
#### What project is affected?
VA

#### What language is this in?
C#

#### What happens?
es-es General Luis model is deployed with no utterances in ExtractName intent making it impossible to train the model.
Same issue with es-mx. en-us is fine. Did not check other languages.

#### What are the steps to reproduce this issue?
Deploy VA with es-es language

#### What were you expecting to happen?
Utterances are deployed

#### Any screenshots or additional context?
![image](https://user-images.githubusercontent.com/20775323/84545676-44248400-acc5-11ea-9232-1316767ae448.png)

**Comment by turbozapekanka** [comment]
It looks like the lost utterances are still stored in "Patterns" and correctly used by prediction but the "Train" button is grayed out.

**Comment by taicchoumsft** [comment]
Thank you for reporting this @turbozapekanka .  I am able to repro, this appears to be a LUIS portal issue, and applies to any intent which only contains patterns.  

If one navigates from the `Patterns` tab back to  `Intents`, the Train button is clickable again, and training works fine. Hope this means at least you're unblocked for now. 

I'll find the right owner to transfer this issue to.

**Comment by turbozapekanka** [comment]
@taicchoumsft 
There is a case 120061821000266 open with support and they're already working on the fix

**Comment by lauren-mills** [comment]
This issue should now be resolved according to the support issue. Will retest and confirm.

**Comment by lauren-mills** [comment]
Verified I was able to deploy the VA in es-es and train in the LUIS portal with 0 utterances labeled for the ExtractName intent.
