### ISSUE TITLE
Updating models -RemoteToLocal corrupts QNA files (regression)

### ISSUE THREAD

**Issue by turbozapekanka** [microsoft/botframework-solutions#3465]
#### What project is affected?
VA

#### What language is this in?
C#

#### What happens?
Some chars in QNA files gets corrupted upon updating the files from remote models
Regression after 1.0 Release, it has been fixed in 0.8-preview  https://github.com/microsoft/botframework-cli/issues/591
Note LU files are ok this time. Only QNA files gets corrupted

#### What are the steps to reproduce this issue?
1. Deploy VA with English and Spanish languages
./Deployment/Scripts/deploy.ps1 -languages "en-us,es-es"
2. Follow these instructions to update the local files with changes made to the remote models:
https://microsoft.github.io/botframework-solutions/virtual-assistant/tutorials/customize-assistant/csharp/4-edit-your-cognitive-models/
./Deployment/Scripts/update_cognitive_models.ps1 -RemoteToLocal

I'm using latest versions of everything including PowerShell 7.0.2

#### What were you expecting to happen?
The models are imported back without any corrupted characters.

#### Any screenshots or additional context?
![image](https://user-images.githubusercontent.com/20775323/84549254-2b1fd100-accd-11ea-900b-d84249cf851c.png)

**Comment by vipeketi** [comment]
@vishwacsena  Can you please suggest.

**Comment by taicchoumsft** [comment]
@lauren-mills, wondering if you have any insight as to what might have happened here, looks like the fix was merged in #3133, but looking at the `update_cognitive_models.ps1` script history, we appear to have lost this change.

**Comment by lauren-mills** [comment]
This is resolved in the next branch.
