### ISSUE TITLE
Can't add a new skill to an assistant by following the tutorial step by step.

### ISSUE THREAD

**Issue by YunnyChung** [microsoft/botframework-solutions#3467]
Hello, I am following the create skill tutorial on the Bot Framework solution website. 
[Link to the tutoral](https://microsoft.github.io/botframework-solutions/skills/tutorials/create-skill/csharp/2-download-and-install/)

I am having a hard time to connect a new skill to my bot. 
I ran the given command, 
`botskills connect --remoteManifest "https://<YOUR_SKILL_NAME>.azurewebsites.net/manifest/manifest-1.1.json" --cs --luisFolder "path-to-lu-folder".`

But I hit the two errors. 
1. 

> The 'endpointUrl' property of the selected endpoint contains invalid characters or does not comply with the URL format. If you didn't select any endpoint, the first one is taken by default.
> There was an error while connecting the Skill to the Assistant:
> Error: One or more properties are missing from your Skill Manifest

2. 

> Error: Some of the cultures provided to connect from the Skill are not available or aren't supported by your VA.
> Make sure you have a Dispatch for the cultures you are trying to connect, and that your Skill has a LUIS model for that culture

I found out the first error happened because the manifest endURL should be all lowercase. 
It seemed the issue was fixed for ts, not for cs. ([related old ticket: ](https://github.com/microsoft/botframework-solutions/issues/3223). After I changed my endUrl to be all lowercase, I could move on. (SideNote: could you fix the issue in cs as well?)

But I hit the second error that I cannot figure out the root cause. 
I have the latest botskills CLI tool, and I provided the correct path to the LU folder. Do I need to run other scripts related to cognitive models (ex: deploy_cognitive_models.ps1 or update_cognitive_models.ps1) before I run `botskills connect`? Or are there any other missing steps that I need to do before I run `botskills connect`?

Let me know what information I can provide from my end to debug this issue further.
Thanks!

**Comment by sidmore** [comment]
Connected with Yunny. She was trying to run botskills connect command from skill to connect with itself. It appears to me the documentation needs to be improved
