### ISSUE TITLE
Customizing VA using TypeScript

### ISSUE THREAD

**Issue by csnarain** [microsoft/botframework-solutions#3468]
/virtual-assistant/tutorials/customize-assistant/typescript/2-edit-your-greeting/

I installed the bot virtual assistant template using the yo bot-virtualassistant command but could not find either src/content or src/locales directories. Are these directory structures generated by yo's VA template? I tried to run yo's VA generator but couldn't find src/content or src/locate directories in it. Looks to be a bug with either the template or the documentation

**Comment by csnarain** [comment]
Is this a bug in the documentation or am I doing something wrong? Can anyone comment?

**Comment by Batta32** [comment]
Hi @csnarain, thanks for reporting this issue! As soon as we have any update we will back to you 😊.

**Comment by Batta32** [comment]
@csnarain - we confirmed that the [typescript/2-edit-your-greeting](https://microsoft.github.io/botframework-solutions/virtual-assistant/tutorials/customize-assistant/typescript/2-edit-your-greeting/) is **outdated**.

Meanwhile, you can check the [csharp/2-edit-your-greeting](https://microsoft.github.io/botframework-solutions/virtual-assistant/tutorials/customize-assistant/csharp/2-edit-your-greeting/) that contains similar steps to edit your greeting response.

The folders `src/content` and `src/locales` are not present in the TypeScript Virtual Assistant as the implementation was migrated to the `LanguageGeneration` functionality.

We will update the entire generator's documentation and we will back to you as soon as possible 😊.

**Comment by Batta32** [comment]
@csnarain - we created PR #3472 updating the entire documentation of the generator for the Skill and Virtual Assistant.

You can see the updated [typescript/2-edit-your-greeting](https://github.com/microsoft/botframework-solutions/pull/3472/files#diff-3cb7defbb9d34a7c40558f85a0d4f8a8).

Feel free to comment/ideas/feedback in the Pull Request!
