### ISSUE TITLE
Feedback Options not Triggered on Custom Dialogs

### ISSUE THREAD

**Issue by samueljohnpaul** [microsoft/botframework-solutions#3469]
I implemented the Feedback feature following the steps on https://microsoft.github.io/botframework-solutions/virtual-assistant/handbook/feedback/#steps-to-implement-feedback

The Feedback is only triggered on the built in dialogs within the VA like QnA Maker or Log Out and does not work on dialogs that I created. As what I understood on the documentation, you only have specify the Feedback on Main Dialog and when any dialog ends on your VA it should be triggered. Do we have to specify the Feedback options within the custom dialog too?

**Comment by pavolum** [comment]
@samueljohnpaul when the custom dialog you created ends does it land back in the MainDialog of your VA? The current feedback implementation only allows for feedback requests when a dialog triggered from ``RouteStepAsync`` within ``MainDialog.cs`` ends. I suppose the simpler question to ask is... **Where do you begin the custom dialog you created? Do you start it from MainDialog or start it from some other dialog?** 

If you can see feedback after the built in dialogs then it sounds like you implemented the feedback correctly.

**Comment by samueljohnpaul** [comment]
Hi @pavolum I start the custom dialog from MainDialog and returns to MainDialog when its finished. I was able to accomplish what I need by calling FeedbackOptions within the custom dialog. This can be closed out. Thank you!
