### ISSUE TITLE
[Docs]

### ISSUE THREAD

**Issue by jimblizzard** [microsoft/botframework-solutions#3473]
/virtual-assistant/tutorials/customize-assistant/csharp/2-edit-your-greeting/

This link in the JSON results in a 404 page in GitHub: https://aka.ms/botframeworkskills

**Comment by taicchoumsft** [comment]
Thanks for reporting this @JimBlizzard. 

@ryanlengel, looks like you're one of the link owners at https://aka.ms. Can you help to fix the redirect to point to the docs page? https://microsoft.github.io/botframework-solutions/overview/skills/

Thanks Ryan.

**Comment by ryanisgrig** [comment]
Thanks - this link now points to the Bot Framework Skills repository: https://github.com/microsoft/botframework-skills.
