### ISSUE TITLE
Virtual Assistant Project listening on the wrong port

### ISSUE THREAD

**Issue by manish-95** [microsoft/botframework-solutions#3477]
#### What project is affected?
Virtual Assistant Template (Bot Framework Solutions 1.0.1, Bot SDK 4.9.3)
#### What language is this in?
C#
#### What happens?
On the Virtual Assistant, my launch profile is set to the profile which has its application URL configured as http://localhost:1205. However, when I attempt to run the project locally, the debug window shows me that it is listening on http://localhost:5000 and https://localhost:5001. I also do not get the browser popup with the default screen.
I have also tested with the VA Sample available on this repository, with the same results.
The Skill, on the other hand, correctly launches localhost:1205, as before.
Is this the desired behaviour in the new version of the VA?

#### What are the steps to reproduce this issue?
1. Deploy VA Template 
2. Run the project locally with the launch profile set to alternative of IIS Express.
3. Note the above described result.

#### What were you expecting to happen?
Like previous versions of the VA, the application should launch on port 1205, at the address http://localhost:1205
#### Can you share any logs, error output, etc.?
```
Microsoft.Hosting.Lifetime: Information: Now listening on: http://localhost:5000
Microsoft.Hosting.Lifetime: Information: Now listening on: https://localhost:5001
Microsoft.Hosting.Lifetime: Information: Application started. Press Ctrl+C to shut down.
Microsoft.Hosting.Lifetime: Information: Hosting environment: Development
Microsoft.Hosting.Lifetime: Information: Content root path: C:\workspace\MBV-MC-COLLECTIONS\ConversationIntelligence\Dev_Emcee\Emcee_DevBot
```
#### Any screenshots or additional context?
![image](https://user-images.githubusercontent.com/29098159/84917490-08caf080-b0dd-11ea-8fd5-9735903cb708.png)

As seen above, the profiles have been set correctly and the project launched with the required profile. However, the connection is listening on port 5000 and 5001, and not the set port of 1205.

**Comment by manish-95** [comment]
Hi, can you please provide an update on this?
Thank you.

**Comment by taicchoumsft** [comment]
Hi @manish-95, 

Thanks for reporting this issue, and apologies for the delay in getting back to you. 

It looks like we have to do some investigation to see what has changed in previous versions, however, an easy fix for now is to 
add the `ASPNETCORE_` prefix to your configuration builder in `Startup.cs`:
```csharp
        public Startup(IWebHostEnvironment env)
        {
            var builder = new ConfigurationBuilder()
                .SetBasePath(env.ContentRootPath)
                .AddJsonFile("appsettings.json", optional: true, reloadOnChange: true)
                .AddJsonFile($"appsettings.{env.EnvironmentName}.json", optional: true)
                .AddJsonFile("cognitivemodels.json", optional: true)
                .AddJsonFile($"cognitivemodels.{env.EnvironmentName}.json", optional: true)
                .AddEnvironmentVariables(prefix: "ASPNETCORE_");

            Configuration = builder.Build();
        }
```

Can you see if this works for you? 

Thanks.

**Comment by manish-95** [comment]
Hi @taicchoumsft , a very random thing happened where I just removed the profile and re-added it to launchSettings.json, and it worked correctly for me. I doubt that fixes the issue though, so I'd like to keep this open and track updates , if that sounds good to you?

**Comment by taicchoumsft** [comment]
Of course. Please feel free to share any interesting discoveries. Thanks!

**Comment by lauren-mills** [comment]
Hi @manish-95, since we were unable to repro the original issue you raised and it's working for you now I am going to close this issue. If you encounter it again, or have any additional comments in the future feel free to reopen as needed. Thanks.
