### ISSUE TITLE
Typo (possessive "it's")

### ISSUE THREAD

**Issue by lancehilliard** [microsoft/botframework-solutions#3478]
/overview/virtual-assistant-solution/ says:

> At it’s core the Virtual Assistant (available in C# and TypeScript) is a project template with the best practices for developing a bot on the Microsoft Azure platform.

"it's" should be "its", as it is possessive.

( a comma after "At its core" might help readability, too )

**Comment by taicchoumsft** [comment]
Thanks for pointing this out @lancehilliard , this will be fixed shortly.
