### ISSUE TITLE
Virtual Agent Deployment error

### ISSUE THREAD

**Issue by chhamso** [microsoft/botframework-solutions#3479]
I’m trying to deploy the Virtual Assistant using the github instructions here. I’ve got it to work multiple times in the past; now It’s failing at the “Provision your Azure resources” step and I’m getting an error. 

When I run the powershell deployment script, the error I get is
> Setting LUIS subscription key ...! Could not assign subscription key automatically. Review the log for more information.
! Log: C:\Users\chhamso\source\repos\Baker3\Baker3\Deployment\Scripts\..\deploy_cognitive_models_log.txt
+ Please assign your subscription key manually in the LUIS portal.

In the log I see:
baker3en-us_Dispatch.dispatch created
┬╗   Error: command luis:application:assignazureaccount not found

After I build, run, in visual studio, which happens without error, I then try  to test in the bot emulator
The bot emulator gives me a “Send failed,” error, with a retry option that just gives me the same error again.

Then visual studio breaks and gives me the following error:
Exception caught: ‘System.ArgumentException’ in Microsoft.Bot.Builder.AI.Luis.dll (“””is not a valid LUIS application id.”)

I think we’ve changed something and maybe I need a manual step after resource deployment?

**Comment by manish-95** [comment]
Hi @chhamso , I faced the same issue, was able to fix it by upgrading my version of the botframework-cli.
Do let me know if this works for you as well.

**Comment by bradrlaw** [comment]
Running into same issue.  Uninstalled and re-installed botframework-cli and received the same error.

**Comment by bradrlaw** [comment]
I created a new project, updated to the nightly build of the botframework-cli and that combined resolved the issue.

With the default version of the cli, it fails.  Tested it on another machine with same results.

**Comment by peterinnesmsft** [comment]
@bradrlaw and @manish-95, can you confirm which non-nightly version of the CLI you were using when you were running into this issue? As I understand it, this API should have been added in 4.9 - are you saying that this error was being returned even for that version of the CLI?

**Comment by bradrlaw** [comment]
The non-nightly version I had that did not work was:

@microsoft/botframework-cli/4.9.1 win32-x64 node-v10.16.3

The nightly is reporting:

@microsoft/botframework-cli/4.10.0-preview.138415 win32-x64 node-v10.16.3

**Comment by peterinnesmsft** [comment]
Thanks for the additional info. Looking into it just now, will try to get a repro and respond back to you shortly.

**Comment by peterinnesmsft** [comment]
Tried doing a few repros on our side and are unable to reproduce the issue.

@bradrlaw @manish-95 @chhamso Are you able to confirm the current version of any other development dependencies, i.e. VSIX version installed, other CLI versions, PowerShell version that you are using, etc?

**Comment by manish-95** [comment]
Hi @peterinnesmsft 
The VSIX version is 4.9.1.1, as found [here](https://marketplace.visualstudio.com/items?itemName=BotBuilder.VirtualAssistantTemplate). 
Powershell version: 6.2.2
BF CLI version: @microsoft/botframework-cli/4.9.1 win32-x64

Hope this helps!

**Comment by chhamso** [comment]
I was able to get it to work by following @manish-95 suggestion above. I re-ran the following two commands in powershell:
npm install -g botdispatch @microsoft/botframework-cli
npm install -g botskills@latest

My next step was going to be to repeat all the steps from "Download and install" in order:
https://microsoft.github.io/botframework-solutions/virtual-assistant/tutorials/create-assistant/csharp/2-download-and-install/

**Comment by peterinnesmsft** [comment]
Hey folks,

We attempted to repro this numerous times and we couldn't do so successfully. Since there has not been further activity in this issue, I'm going to close out. I would recommend ensuring all dependencies etc are updated to the latest version.

If this continues to be an issue with all of the latest versions of all dependencies, then let us know. Thanks!
