### ISSUE TITLE
Unable to use line breaks in adaptive cards in the Virtual Assistant

### ISSUE THREAD

**Issue by tomSauret847** [microsoft/botframework-solutions#3484]
#### What are the steps to reproduce this issue? Generate a Virtual Assistant. Modify the intro card to include line breaks. 
Change 
Now that I'm up and running, explore the links here to learn what I can do.

To 
Now that 'm up and running. \n1. you can customize the greeting. \n2. You can add skills to extend the capabilities.

#### What were you expecting to happen?
Expecting a ordered list to be displayed

**Comment by Batta32** [comment]
Thanks @tomSauret847 for reporting this issue! We will be reviewing this and we will back to you asap.

**Comment by Batta32** [comment]
Hi @tomSauret847 - sorry for the delay. You should replace `\n` for `\\n` in the JSON text as you need to **escape** the `\` in your JSON string.

Repro steps:
1. Open the LG file
1. Look for the `text` property of the adaptive card you want to edit
1. Add `\\n` to introduce a line break (e.g. Now that 'm up and running. \\n1. you can customize the greeting. \\n2. You can add skills to extend the capabilities.)
1. Run the bot and see the results

We will be attentive to your answer 😊.

![image](https://user-images.githubusercontent.com/11904023/86033126-d7242480-ba0e-11ea-8578-e68184ad7eb4.png)

**Comment by tomSauret847** [comment]
@Batta32 Yes, that did resolve the issue with the line breaks. That you for getting back to me on this!

**Comment by Batta32** [comment]
@tomSauret847 - Awesome! I'll close this issue!
