### ISSUE TITLE
Request to add documentation on using script to add a new culture after deployment

### ISSUE THREAD

**Issue by saikumaru** [microsoft/botframework-solutions#3485]
## User Story
We started off supporting en-us and now want to extend our bot and LUIS to handle more languages, please can you suggest here what are the scripts and parameters that are to be used to successfully pick the .lu files from respective culture folders, build .json files and publish them to luis.ai portal?

And eventually add it to the documentation.

## Acceptance Criteria 
*List your requirements.*
-which Power shell script, amongst deploy.ps1, deploy_cognitive_models.ps1 , update_cognitive_models.ps1
-what parameters

## Notes
There are steps on adding a new QnA here https://microsoft.github.io/botframework-solutions/virtual-assistant/tutorials/customize-assistant/csharp/4-edit-your-cognitive-models/

similarly need steps to add a new culture

**Comment by dmvtech** [comment]
@saikumaru I don't have an answer right away. I am having to do some research and am looking into this. It might take a little bit of time to figure this out.

**Comment by dmvtech** [comment]
My guess is that it is using `deploy_cognitive_models.ps1 -languages "<culture>"`

I tried a test to deploy de-de, but I haven't got it working yet.

**Comment by dmvtech** [comment]
Confirmed that is the correct script. More info here:
https://microsoft.github.io/botframework-solutions/virtual-assistant/handbook/deployment-scripts/#scripts

Please give that a shot and let me know how it goes.

**Comment by dmvtech** [comment]
HI @saikumaru Any luck?

**Comment by saikumaru** [comment]
@dmvtech thanks for the help, that part partially worked.

But however the generated classes(General and Dispatch services) are all defunct, can you please check the related issue
https://github.com/microsoft/botframework-solutions/issues/3615

**Comment by peterinnesmsft** [comment]
@saikumaru you are indeed correct in the linked issue - there is a bug in our script and we will need to fix it. The intention I believe should be that using the specified parameters should produce the desired outcome, just that we have the bug. Given the documentation ask has been handled, I'm going to close this issue. Let's track the bug in the other open issue and we can go from there. Thanks!
