### ISSUE TITLE
Unable to find skills.json as mentioned in the doc[Docs]

### ISSUE THREAD

**Issue by saikumaru** [microsoft/botframework-solutions#3488]
/skills/handbook/botskills/

The document says:

>Commands
For all of this commands, the tool assumes that you are running the CLI within the Virtual Assistant project directory and have created your Bot through the template, and therefore have a skills.json file present in the working folder which contains the connected skills.

However skills.json is not found in the VA project. Please advise.

**Comment by Batta32** [comment]
Thanks @saikumaru for reporting this issue. We will be reviewing this and we will back to you ASAP!

**Comment by Batta32** [comment]
This issue is solved with the PR #3565 as we updated the botskills documentation with the requested information.
