### ISSUE TITLE
[Docs] The code snippet to add multiple resources is wrong

### ISSUE THREAD

**Issue by saivennelakanti** [microsoft/botframework-solutions#3490]
/virtual-assistant/tutorials/customize-assistant/csharp/3-edit-responses/

the first parameter of LocaleTemplateManager is Dictionary<string, string> so if you define localizedTemplates as DIctionary<string, List<string>> then this piece of code doesn't compile.
![error_add_addtional_responses](https://user-images.githubusercontent.com/51310192/85694637-ee080580-b6f4-11ea-9926-8944087faaac.PNG)

**Comment by taicchoumsft** [comment]
Thanks for pointing this out @saivennelakanti , this will be fixed shortly.
