### ISSUE TITLE
Error in adding a custom .qna file to VA

### ISSUE THREAD

**Issue by DishaAgarwal** [microsoft/botframework-solutions#3491]
#### I tried adding a .qna file to the qna folder (within resources) in the VA Sample. On deploying Azure Resources for the VA, a KB is created for the concerned .qna file and QnA extraction works as expected. The cognitivemodels.json file also gets updated, however I get an error when I try to trigger the KB thus created from the VA.

PFA, screenshot of the trace on trying to trigger the concerned QnA KB via VA using the bot emulator.

![NewKB](https://user-images.githubusercontent.com/11506427/85844012-b31ed400-b7bf-11ea-91d7-7a0f321e63dd.png)

**Comment by darrenj** [comment]
Hi,

Are you testing the Bot locally or deployed into Azure, not clear from the screenshot? If deployed into Azure please make sure you re-publish your Bot back to Azure. I think this hasn't been done which is generating this error.

**Comment by DishaAgarwal** [comment]
Hi, I am testing the bot locally.

**Comment by peterinnesmsft** [comment]
MainDialog::RouteStepAsync performs a call to IsSkillIntent, which determines whether the recognized dispatch intent from the user utterance is for a skill, or whether it aligns to a KB/None. The knoweldgebase intents to check against are hard-coded, so with the addition of another KB with a separate identifier, this logic breaks.

Short-term mitigation would be to add an additional condition to the check in IsSkillIntent for the new KB's intent identifier. Will work offline with the team to identify a suitable fix to handle this more flexibly going forward.

**Comment by peterinnesmsft** [comment]
Revisiting this - we have a path forward in which we can meaningfully fix this.

A number of the configuration classes previously depended upon within Microsoft.Bot.Configuration have been marked as obsolete in the SDK, and so we are intending to move them to Microsoft.Bot.Solutions. This is dependent on completion of #3617.

In doing so, this allows us to update the configuration classes to expose the parameter for the knowledgebase information, such that we can dynamically route this in MainDialog.
