### ISSUE TITLE
[Docs] the approach provided on this page doesn't work

### ISSUE THREAD

**Issue by saivennelakanti** [microsoft/botframework-solutions#3495]
/virtual-assistant/tutorials/customize-assistant/csharp/4-edit-your-cognitive-models/.

When I do all the steps provided in this webpage there is no change to the VirtualAssistant. Due to which I couldn't submit to the AzureHeros challenge. I looked at these steps multiple times and reverified but the changes done by me to the existing knowledgebase are not picked by the BOT. the Intents/questions are unrecognized by the BOT. so fix this page to reflect the right steps.

**Comment by ryanisgrig** [comment]
Thanks for the feedback! I will follow up with this after investigating.

**Comment by ryanisgrig** [comment]
I have validated that this flow works with the following steps.

1. Test query on existing FAQ KB
![image](https://user-images.githubusercontent.com/43043272/86850937-f81bf380-c066-11ea-920b-b93e48453b51.png)

2. Make change in portal to existing FAQ KB by adding new QnA pair
![image](https://user-images.githubusercontent.com/43043272/86850686-952a5c80-c066-11ea-86e3-574bd2536d07.png)

3. Select **Save and Train**

4. Select **Publish**

5. Run `.\Deployment\Scripts\update_cognitive_models.ps1 -RemoteToLocal`
![image](https://user-images.githubusercontent.com/43043272/86851517-f4d53780-c067-11ea-92f5-8ee5477bfafe.png)

6. Validate that query works
![image](https://user-images.githubusercontent.com/43043272/86851457-da9b5980-c067-11ea-9c61-d8ea23f3db9c.png)


I will make a change to the docs to reflect that you should save, train, and publish your changes before running the script.
