### ISSUE TITLE
The cognitiveModels.json misses endpoint property

### ISSUE THREAD

**Issue by dawwa** [microsoft/botframework-solutions#3498]
$luisApp.endpoint is being used in the [update_cognitive_models.ps1](https://github.com/microsoft/botframework-solutions/blob/master/samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Deployment/Scripts/update_cognitive_models.ps1), however, the [cognitiveModels.json](https://github.com/microsoft/botframework-solutions/blob/master/samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/cognitivemodels.json) does not seem to have this property.

```powershell
UpdateLUIS `
                -luFile $lu `
                -appId $luisApp.appid `
                -endpoint $luisApp.endpoint `
                -subscriptionKey $luisApp.authoringKey `
                -culture $langCode `
                -version $luisApp.version `
                -log $logFile
```

**Comment by ryanisgrig** [comment]
Thanks for the feedback! We will investigate and follow up.

**Comment by lauren-mills** [comment]
This has been updated in the next branch and will be available in our next release.
