### ISSUE TITLE
Generate *.lg output *.cs file 

### ISSUE THREAD

**Issue by ipraveenMS** [microsoft/botframework-solutions#3503]
#### What project is affected?
local project modeled after the ones at  https://github.com/microsoft/botframework-skills
#### What language is this in?
c#
#### What happens?
I wanna generate the c# output file like how its done at botframework-skills\skills\csharp\experimental\hospitalityskill\Responses\Shared\HospitalityStrings.lg which has HospitalityStrings.cs file. Its not clear how this file is created. I checked the file property of *.lg file and also checked the link at  HospitalityStrings.cs https://docs.microsoft.com/en-us/visualstudio/modeling/t4-include-directive?view=vs-2017 which did not help. Is this file manually generated?
#### What are the steps to reproduce this issue?
Create your own skills project like some of them at https://github.com/microsoft/botframework-skills and have the lg file in them. Now how do I create the corresponding *.cs file for it?
#### What were you expecting to happen?
Steps clearly stated how to generate the *.cs file
#### Can you share any logs, error output, etc.?
Enough info above.

**Comment by xieofxie** [comment]
Hi @ipraveenMS There used to be these files https://github.com/microsoft/botframework-skills/commit/01290f5d50f8658be0bf88771421509c38bd6fb5
But we remove them as we expected they should be part of sdk/lg cli.
You could follow the `LgIdCollection.t4` and `FindArticlesResponses.tt`.
Thanks

**Comment by ipraveenMS** [comment]
Hi @xieofxie its not clear from your answer how the  *.lg files should be processed. I see the *.lg files in the latest BF code downloaded from https://github.com/microsoft/botframework-solutions at \latestbf\botframework-solutions\samples\csharp\skill\SkillSample\Responses and  latestbf\botframework-solutions\samples\csharp\assistants\virtual-assistant\VirtualAssistantSample\Responses among other places. How are these supposed to be processes to generate *.cs file?
How the text and speech strings used in code?

**Comment by xieofxie** [comment]
Hi @ipraveenMS I assume you already understood how lg work https://docs.microsoft.com/en-us/azure/bot-service/file-format/bot-builder-lg-file-format?view=azure-bot-service-4.0

The files I mentioned are a temporary solution for generating cs files for **names** in lg files. I created a demo here https://github.com/microsoft/botframework-skills/blob/hualxie/t4_demo/skills/csharp/pointofinterestskill/Responses/CancelRoute/CancelRouteResponses.tt For each lg file that is an entrance, create a tt file to generate a cs file automatically for being used in code.

**Comment by ipraveenMS** [comment]
This works fine. Thanks @xieofxie. Only problem is,
We have older version of the response files in json format. Its laborious to convert them to lg files. Do have guys have any tools\scripts for that?

json format:
{
  "Incident": {
    "replies": [
      {
        "text": "blah blah",
        "speak": "blah2 blah2"
      }
    ]
  },
  "NotSupported": {
    "replies": [
      {
        "text": "I'm sorry, blah1",
        "speak": "I'm sorry, blah2."
      }
    ]
  }
}

**Comment by xieofxie** [comment]
@ipraveenMS Hmm.. We used to have a tool to convert a well-formatted `json` skill to `lg` https://github.com/microsoft/botframework-solutions/tree/skills/lg_migration_tool/tools/JsonConverter

I am not sure if it will help you or not. You could refer to this file https://github.com/microsoft/botframework-solutions/blob/skills/lg_migration_tool/tools/JsonConverter/JsonConverter/Program.ConvertJsonFilesToLG.cs

**Comment by ipraveenMS** [comment]
Thanks a lot @xieofxie
