### ISSUE TITLE
Poor documentation. Please add step by step impletementation of Linked Account

### ISSUE THREAD

**Issue by ashoksamal6363** [microsoft/botframework-solutions#3506]
/solution-accelerators/samples/linked-accounts/

Poor documentation. Please add step by step implementation of Linked Account. A standard scenario could be, When a user talks to the virtual assistant then it asks for the authentication and on successful authentication, virtual assistant ll show the welcome message

**Comment by ryanisgrig** [comment]
Thanks for the feedback! I will follow up with this after investigating.

**Comment by ryanisgrig** [comment]
Hi @ashoksaaml6363, the Virtual Assistant template does not come with authentication enabled but you can learn how to do so when adding one of the authenticated Skills by following https://microsoft.github.io/botframework-solutions/skills/handbook/authentication/. I will update the documentation to reference this resource first before following along on configuring a Linked Accounts web app.

**Comment by ashoksamal6363** [comment]
I followed the above doc. I added google auth. Even the test connection on
Bot setting works fine.

But after adding the details in appsetings.json it didn't work. There is no
error but the bot is not asking for any authentication.
Any way to fix it?
