### ISSUE TITLE
[Docs]404 - Page not found Hmm, we couldn't find this link, but here are some related search results that may be helpful.

### ISSUE THREAD

**Issue by ashoksamal6363** [microsoft/botframework-solutions#3507]
/clients-and-channels/tutorials/enable-speech/6-next-steps/

404 - Page not found
Hmm, we couldn't find this link, but here are some related search results that may be helpful.

My previous code was working fine. But seems like this repo has been removed and my local code is not working too.

**Comment by ryanisgrig** [comment]
Thanks for the feedback! I will follow up with this after investigating.

**Comment by ryanisgrig** [comment]
Hi, you can refer to these resources and I will update the documentation accordingly.

[Create a Voice Assistant with the Speech SDK in C# UWP](https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart/csharp/uwp/virtual-assistant)
[Using Voice Assistant in Java on Windows or Linux](https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart/java/jre/virtual-assistant)
[Virtual Assistant Client on Android](https://microsoft.github.io/botframework-solutions/clients-and-channels/clients/virtual-assistant-client/)
