### ISSUE TITLE
Refine experience spec template

### ISSUE THREAD

**Issue by mareekuh** [microsoft/botframework-solutions#3516]
Refine experience spec template

https://microsoft.sharepoint.com/:w:/r/teams/ConversationalAI785/_layouts/15/Doc.aspx?sourcedoc=%7B9367714A-2D0F-43A3-9648-21E64D7C1C86%7D&file=Spec%20Template_june2020.docx&wdLOR=c5A9017A7-2643-234B-85A5-0759AB78A956&nav=eyJjIjo5ODA0MTAzNzh9&action=default&mobileredirect=true&cid=f17c8327-0f84-4954-a050-e26b1f7036f7

**Comment by oneemo95** [comment]
Duplicate of #
