### ISSUE TITLE
Exception when adding authentication to a skill (due to missing default)

### ISSUE THREAD

**Issue by GitDruid** [microsoft/botframework-solutions#3528]
#### What project is affected?
Skill template

#### What language is this in?
C#

#### What happens?
An exception happens in AfterGetAuthTokenAsync()

#### What are the steps to reproduce this issue?

1. Create an empty skill from template
2. Follow the steps to enable authentication on skill and on sample dialog (both on azure and on the code)
3. Execute the skill

#### What were you expecting to happen?
The OAuth card appearing
The token retrieved 
The sample dialog start

#### Can you share any logs, error output, etc.?
In AfterGetAuthTokenAsync() the line:
`var state = await StateAccessor.GetAsync(sc.Context, cancellationToken: cancellationToken);`
should be replaced by:
`var state = await StateAccessor.GetAsync(sc.Context, () => new SkillState(), cancellationToken);`

**Comment by ryanisgrig** [comment]
Thanks for the feedback! We will follow up with this after investigating.

**Comment by lauren-mills** [comment]
I made this change in our next branch to go into the templates in the next release. Thanks!
