### ISSUE TITLE
[TypeScript][Skill] Skill tests fails if the Skill is not named sample-skill

### ISSUE THREAD

**Issue by VictorGrycuk** [microsoft/botframework-solutions#3529]
#### What project is affected?
-   [generator-bot-virtualassistant@1.0.1](https://www.npmjs.com/package/generator-bot-virtualassistant/v/1.0.1)
-   TypeScript Skill Template

#### What language is this in?
TypeScript

#### What happens?
There are 5 tests that fails if the skill is not named `skill-sample` because the cognitivemodels mock is using a placeholder in the Skill template.

#### What are the steps to reproduce this issue?
1.  Run  `npm install -g yo generator-bot-virtualassistant` to install the Generator Bot Virtual Assistant
2.  Run `yo bot-virtualassistant:skill -n bf-skill-ts -d "skill testing" -l "en-us" --noPrompt` to create the skill
3.  Run `npm run test` from the root of the generated skill
4.  5 tests will fail

#### What were you expecting to happen?
All the test should be correctly executed

#### Any screenshots or additional context?
![image](https://user-images.githubusercontent.com/39467613/86797264-da8a6200-c045-11ea-84bb-8703d747823d.png)

**Comment by Batta32** [comment]
This issue is solved with the PR #3532 as we updated the `cognitivemodels.json` used as a mock in the unit tests of the TypeScript Skill.

**Comment by Batta32** [comment]
This issue is solved with PR #3642.
