### ISSUE TITLE
[Generator] A Generator test fails because it expects a folder that doesn't exist any more

### ISSUE THREAD

**Issue by VictorGrycuk** [microsoft/botframework-solutions#3530]
#### What project is affected?
[generator-bot-virtualassistant@1.0.1](https://www.npmjs.com/package/generator-bot-virtualassistant/v/1.0.1)

#### What language is this in?
TypeScript

#### What happens?
When running the Generator's tests, the [test](https://github.com/microsoft/botframework-solutions/blob/next/templates/typescript/generator-bot-virtualassistant/test/generator-bot-virtualassistant.test.suite.js#L106-L115) to create the `src\locales` folder fails as those folders were removed in the [0.8 migration](https://github.com/microsoft/botframework-solutions/pull/3363/files).

#### What are the steps to reproduce this issue?
1.  Checkout the `master` branch
2.  Open a command line at [\templates\typescript\generator-bot-virtualassistant\\](https://github.com/microsoft/botframework-solutions/tree/master/templates/typescript/generator-bot-virtualassistant)
3.  Run `npm i` to install the dependencies
4.  Run `npm run test`
5.  The test `The generator-bot-virtualassistant tests should create the folders src\locales folder` will **fail**

#### What were you expecting to happen?
The test for the removed folders should be removed.

#### Any screenshots or additional context?
![image](https://user-images.githubusercontent.com/39467613/86799493-61d8d500-c048-11ea-8512-4dd9bde09fd1.png)

**Comment by Batta32** [comment]
This issue is solved with the PR #3531 as we fixed the broken tests of the `generator-bot-virtualassistant`.

**Comment by Batta32** [comment]
This issue is solved with PR #3641.
