### ISSUE TITLE
[Docs] Confusing qnaEndpoint semantics in deploy.ps1 script

### ISSUE THREAD

**Issue by GitDruid** [microsoft/botframework-solutions#3544]
**Please describe your request**

Provisioning of the QnA resource does not set the region based on the $location parameter. West US Endpoint is hardcoded:
$qnaEndpoint = "https://westus.api.cognitive.microsoft.com/qnamaker/v4.0"
So, if you don't provide it, you will not be able to create the resource in westeurope, for instance.

**Is this an issue with current documentation? If yes, please provide the link.**

Current documentation here:
https://microsoft.github.io/botframework-solutions/virtual-assistant/handbook/deployment-scripts/
reports that endpoint for deploying QnA Maker knowledge bases is **only required for Azure Gov deployments**.

**Comment by ryanisgrig** [comment]
Thanks for the feedback! We will follow up with this after investigating.

**Comment by lauren-mills** [comment]
Hi @GitDruid, when QnA Maker is deployed, it creates three resources in Azure, the QnA Maker Cognitive Service, the QnA Maker web app, and the Azure Search Service. The QnA Maker Cognitive Service resource is only deployable in West US, but the search service and QnA Web Host app service can be deployed in other regions. So, the endpoint is always the westus endpoint except for Azure Government deployments. 

Here is an example of what is created when I provision a new QnA Maker resource in the Azure Portal:
![image](https://user-images.githubusercontent.com/27976702/87486379-0f6f5980-c5f0-11ea-9bb5-12c51ce12abc.png)

**Comment by GitDruid** [comment]
> Hi @GitDruid, when QnA Maker is deployed, it creates three resources in Azure, the QnA Maker Cognitive Service, the QnA 

Thank you @lauren-mills. 
I've just started working with Botframework and it was not clear to me that "The QnA Maker Cognitive Service resource is only deployable in West US" (also looking here, it seems that there are more region then just West US: https://azure.microsoft.com/en-us/global-infrastructure/services/?products=cognitive-services).
It could be the case to add a small note/reference about it in the script doc?

**Comment by lauren-mills** [comment]
I've added the note about QnA regions in the next branch for our next release. Thanks!
