### ISSUE TITLE
[Botskills] wrap path with quotes

### ISSUE THREAD

**Issue by xieofxie** [microsoft/botframework-solutions#3545]
#### What project is affected?

Botskills

#### What language is this in?

Typescript

#### What happens?

Not all parameters are wrapped with quotes

Like here https://github.com/microsoft/botframework-solutions/blob/96db93b187d838e978d6502827bf8f92169ee28f/tools/botskills/src/functionality/connectSkill.ts#L124, https://github.com/microsoft/botframework-solutions/blob/96db93b187d838e978d6502827bf8f92169ee28f/tools/botskills/src/functionality/refreshSkill.ts#L96 etc.

#### What are the steps to reproduce this issue?

See this https://github.com/microsoft/botframework-skills/issues/279

**Comment by Batta32** [comment]
Thanks @xieofxie for reporting this issue. We will be reviewing it and as soon as we have any update we will back to you 😊.

**Comment by Batta32** [comment]
Hi @xieofxie - sorry for the delay.

We successfully **reproduced** the mentioned scenario using a path with whitespaces on it. We will be analyzing the solution for the issue and back to you later 😊.

![image](https://user-images.githubusercontent.com/11904023/88319431-87c1d300-ccf2-11ea-8bf2-d5c501fe69e6.png)

**Comment by Batta32** [comment]
Hi @xieofxie - we created the PR #3587 fixing this issue.

You can validate the changes following these steps:
1. Checkout to the branch [`southworks:feature/southworks/fix-path-botskills-error`](https://github.com/southworks/botframework-solutions/tree/feature/southworks/fix-path-botskills-error)
1. Go to the [botskills](https://github.com/southworks/botframework-solutions/tree/feature/southworks/fix-path-botskills-error/tools/botskills) tool
1. Execute `npm install` to install the depedencies
1. Execute `npm run build` to compile the solution
1. Execute `npm link` to link the tool. If you have installed botskills, you should execute `npm uninstall -g botskills` to uninstall the tool.
1. Check that the values are wrapped between quotes using the botskills' commands

We will be attentive to your answer 😊!

**Comment by xieofxie** [comment]
Hi @Batta32, I would suggest we wrap values with quotes in `runCommand` function https://github.com/southworks/botframework-solutions/blob/646de1572e2ff3038c07cbc6d6dcdc4960a52db7/tools/botskills/src/functionality/connectSkill.ts#L154, https://github.com/southworks/botframework-solutions/blob/646de1572e2ff3038c07cbc6d6dcdc4960a52db7/tools/botskills/src/functionality/refreshSkill.ts#L22

Or we will lack the wrapping of executeDispatchAdd, refresh skill.
Thanks

**Comment by Batta32** [comment]
@xieofxie - we **successfully** wrapped the values with quotes in the `bf luis:convert` and `bf luis:generate` commands too. After these changes, we **confirmed** that if any argument's values contains whitespaces, the tool will correctly work. You can see the new [changes](https://github.com/microsoft/botframework-solutions/pull/3587/commits/9e02a05ff99dd6a9fa0322364c7d37ed654ec1ce) in the PR #3587.

Also, we identified that if we wrap the values with quotes in the `dispatch add`  and `dispatch refresh` commands, botskills fails, so we can't update the mentioned `runCommand`.

Finally, you can validate the changes following the mentioned [repro steps](https://github.com/microsoft/botframework-solutions/issues/3545#issuecomment-664465411).
