### ISSUE TITLE
[Docs]where to find "APP_CENTER_ID"

### ISSUE THREAD

**Issue by ashoksamal6363** [microsoft/botframework-solutions#3546]
/clients-and-channels/clients/virtual-assistant-client/
where to find "APP_CENTER_ID"
"app_center_id": "APP_CENTER_ID" // Replace with your Visual Studio App Center id

**Comment by ryanisgrig** [comment]
Hi @ashoksamal6363, you can find your Visual Studio App Center id by following the instructions at Prerequisites Step 5:https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/android
