### ISSUE TITLE
Direct line speech channel doesn't work with VA and Calendar Skill

### ISSUE THREAD

**Issue by dingjianrui** [microsoft/botframework-solutions#3547]
While i tested the VA with CalendarSkill by the direct line speech channel(English), the VA encountered an error as below:
**(Note: Everything works well if i chat with VA+CalendarSkill in text in the bot emulator.)**

> Microsoft.AspNetCore.Hosting.Diagnostics: Information: Request starting HTTP/1.1 POST http://localhost:3978/api/skills/v3/conversations/92139285-2454-4fd3-afb0-237397c4feff-CalendarSkill-directlinespeech-skillconvo/activities/646b8186-a730-4060-b5b9-1a9bd0ea8347 application/json; charset=utf-8 1051
Microsoft.AspNetCore.Routing.EndpointMiddleware: Information: Executing endpoint 'WDAssistant.Controllers.SkillController.ReplyToActivityAsync (WDAssistant)'
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker: Information: Route matched with {action = "ReplyToActivity", controller = "Skill"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] ReplyToActivityAsync(System.String, System.String, Microsoft.Bot.Schema.Activity) on controller WDAssistant.Controllers.SkillController (WDAssistant).
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker: Information: Executing action method WDAssistant.Controllers.SkillController.ReplyToActivityAsync (WDAssistant) - Validation state: Valid
**_Exception thrown: 'System.ArgumentNullException' in System.Private.CoreLib.dll_**
Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor: Information: Executing ObjectResult, writing value of type 'Microsoft.AspNetCore.Mvc.ProblemDetails'.

This happens when the Calendar Skill post the result back to VA Skill Controller, and it only happen when i use the direct line speech channel,  if i use the Bot emulator and chat with the VA in text, both the CalendarSkill and VA worked very well.

When the VA encounter this issue, a HTTP 500 internal server error returned to the CalendarSkill as below:
![WeChat Screenshot_20200710113755](https://user-images.githubusercontent.com/1256355/87113925-effbc800-c2a1-11ea-82f5-285d22adf068.png)

Here are packages used:
![ppp](https://user-images.githubusercontent.com/1256355/87114637-a57b4b00-c2a3-11ea-9990-69142a6fa3e9.png)

**Comment by xieofxie** [comment]
Hi, we also met this. I created an issue here https://github.com/microsoft/botbuilder-dotnet/issues/4254 and we are working on a temporary solution.

**Comment by xieofxie** [comment]
A temporary solution (add the following code in VA's DefaultActivityHandler:
```
public override async Task OnTurnAsync(ITurnContext turnContext, CancellationToken cancellationToken = default)        {
    if (!turnContext.TurnState.ContainsKey(BotAdapter.OAuthScopeKey))
    {
        ClaimsIdentity claimsIdentity = turnContext.TurnState.Get<IIdentity>(BotAdapter.BotIdentityKey) as ClaimsIdentity;
        var scope = SkillValidation.IsSkillClaim(claimsIdentity.Claims) ? JwtTokenValidation.GetAppIdFromClaims(claimsIdentity.Claims) : AuthenticationConstants.ToChannelFromBotOAuthScope;
        turnContext.TurnState.Add(BotAdapter.OAuthScopeKey, scope);
    }
```

**Comment by xieofxie** [comment]
The fix in SDK will be shipped in November.
