### ISSUE TITLE
directline.web sampe project, not working anymore in Chrome

### ISSUE THREAD

**Issue by velebyte** [microsoft/botframework-solutions#3549]
#### What project is affected?
directline.web

#### What language is this in?
C#/JS

#### What happens?
WebChat client not working in Chrome, in Edge it is fine.

#### What are the steps to reproduce this issue?
Just download and rund the directline.web project and insert you azure keys

#### Can you share any logs, error output, etc.?
![Screenshot_110](https://user-images.githubusercontent.com/17783229/87228737-6c2a0480-c3a3-11ea-902e-5bd9b04ec033.png)

**Comment by lauren-mills** [comment]
For support team, this is the project that is causing issues: https://github.com/microsoft/botframework-solutions/tree/master/samples/csharp/clients

**Comment by stevkan** [comment]
Hi @velebyte, I'm unable to repro the issue. Can you answer a these questions so I can get a complete picture?

- Which version of Chrome are you running?
- Is this a recent copy of the directline.web client sample? If not, could you update and try again?
- Does the error occur immediately or only after user input via Web Chat?
- Are you using Direct Line Speech or are you using only Direct Line?
- Do you have Direct Line 'Enhanced Authentication' enabled in the Direct Line channel in Azure? If so, does the value in the 'appSettings.json' file match (i.e. true or false)?
- Can you tell me the source of the values you have entered in your appSettings.json file? For instance, where you copied the BotName, DirectLineSecret, etc.
- What is the SpeechServiceRegionIdentifier value (i.e. 'westus')?
- Are you using a VA bot or a standard BotFramework bot?
- Can you include the code from your bot that generates the first response to the user?

**Comment by anusharr** [comment]
Closing the issue due to no response. Please feel free to reopen it if the issue persists.
