### ISSUE TITLE
Issue with user logout when using VA and skill that requires authentication

### ISSUE THREAD

**Issue by davidmcgowan** [microsoft/botframework-solutions#3550]
#### What project is affected?
VA Sample

#### What language is this in?
C#

#### What happens?
Unable to logout. Possible issue with VA auth flow

#### What are the steps to reproduce this issue?
VA setup with skill requiring authentication linked

#### What were you expecting to happen?
User is logged out

#### Any screenshots or additional context?
We are using Virtual Assistant with two skills linked which both require authentication (We are using the Calendar skill sample and a custom skill of our own) and it does not seem possible to log the user out.

In the MainDialog.cs the Logout intent is invoked as expected however in the LogUserOutAsync method a call to GetTokenStatusAsync returns an empty TokenStatus.

If we use the skills independently of the VA then it is possible the logout as the response from GetTokenStatusAsync method includes the TokenStatus.

We have our OAuth connections setup on the skills and not the VA as described in the documentation for the calendar skill. Are there any known issues around authentication flow between VA and skills that might be related?

**Comment by lauren-mills** [comment]
Hi @davidmcgowan, I expect this is a bug caused by us moving the authentication from the VA into the Skill itself. It may take a bit of time to implement the fix, but essentially we need to forward the logout request to the skill so that it can execute on its end. I'm looking into it.

**Comment by davidmcgowan** [comment]
Hi @lauren-mills, that's great thank you.

Something that is slightly related, since the switch of authentication to the skills if you were to have two skills which have the same authentication provider but require different scopes then the EVA will prompt for login for each skill. Previously, with the authentication on the VA we were able to combine the scopes using one AD app. Is this worth me raising a separate issue?

Thanks again.

**Comment by lauren-mills** [comment]
We do actually have a way to enable the skills to use a single shared app registration for this scenario (where all the skills are trusted, as in an Enterprise VA). You can find the instructions for enabling it here: https://microsoft.github.io/botframework-solutions/overview/whats-new/1.0/enable-sso-with-skills-using-oauthcredentials-setting/

Essentially, you provide an additional setting in each of the skills that points to the app that should be used. Please let me know if it helps.

**Comment by lauren-mills** [comment]
In fact, this may also work around the original logging out issue as well.

**Comment by davidmcgowan** [comment]
We did previously try to configure SSO but could never get it to work the same way it does in the [sample](https://github.com/microsoft/BotBuilder-Samples/tree/master/experimental/sso-with-skills). The skills still look to be trying to use the token created by the VA. 

When that happens we get a `InvalidAuthenticationToken` exception caused by the token having an invalid audience (expected ms graph aud but token contains VA appId).

I have looked at the code in the TokenExchangeSkillHandler and tried to debug but I have not been able to get a breakpoint hit on any of the method overrides in this class. In appsettings.json we have populated the `tokenExchangeConfig` with same  connection name and provider used when setting up auth in azure portal e.g **Outlook** and **Azure Active Directory v2**.

Happy to share with you examples of our code/configuration if required.

Once again, if you wish for me to raise a separate issue please let me know.

Thanks
David

**Comment by peterinnesmsft** [comment]
Hey @davidmcgowan, closing out this issue due to inactivity. If you still want assistance on the SSO item, please file a new issue and we can track there - thanks!
