### ISSUE TITLE
Linked account not working when Virtual Assistant Client(Android) connect to AV and Calendar Skill with direct line speech

### ISSUE THREAD

**Issue by dingjianrui** [microsoft/botframework-solutions#3553]
#### What project is affected?
1. Virtual Assistant Client (Android)
2. Virtual Assistant Project(Created by template)
3. Calendar Skill
4. Linked Account Web
#### What language is this in?
English
#### What happens?
Virtual Assistant Client(Android) doesn't work properly when i use the direct line speech channel, But direct line speech channel worked very well with other clients such as Voice Assistant Client(Windows).
Technically the OAuthCard should not popup since i have already linked account for the Calendar Skill, this can work when i use the Voice assistant client(windows), not OAuthcard displayed, the calendar skill can get the token directly from the token service and query the O365 calendar without any problem. 
But when i used the virtual assistant client(Android), i detected that the Calendar Skill forward the OAuthCard to the VA, the linked account not working. and this only happen when i use speech.
If i use text chat on the virtual assistant client(Android), it also can work, no OAuthCard popup.
#### What are the steps to reproduce this issue?

1. Deploy the VA and Calendar Skill.
2. Configure the linked account for the Calendar Skill, and get the user id from the linked account web.
3. Set speech subscription key, speech region and user id the virtual assistant client(android).

#### What were you expecting to happen?
Since i linked account for the CalendarSkill, Calendar Skill should be able to query the O365 calendar directly without any OAuthCard popup.
#### Can you share any logs, error output, etc.?
Here is the message from Calendar Skill to VA, i only happen when i use speech on virtual assistant client(Android). if i use text chat with the bot, no OAuthCard displayed, it can get the token directly from the token service.
**### Most important: the recipient id is not the user id i specified in the client config.**
The User Id i configured in the client is: 8e7e3833b1054de9818#########
The User Id in the Calendar Skill message is: _936219e7-ce36-4bd3-87f1-3fb1ea4cd877|0000_
`{
    "type": "message",
    "serviceUrl": "http://bcfa9a09c1d0.ngrok.io/api/skills",
    "channelId": "directlinespeech",
    "from": {
        "id": "xxxxx-ht3ebmw",
        "name": "xxxxx-ht3ebmw"
    },
    "conversation": {
        "isGroup": false,
        "id": "936219e7-ce36-4bd3-87f1-3fb1ea4cd877-CalendarSkill-directlinespeech-skillconvo"
    },
    "recipient": {
        "id": "_936219e7-ce36-4bd3-87f1-3fb1ea4cd877|0000_",
        "role": "user"
    },
    "locale": "en-US",
    "inputHint": "acceptingInput",
    "attachments": [
        {
            "contentType": "application/vnd.microsoft.card.oauth",
            "content": {
                "text": "Sign in to your O365 account",
                "connectionName": "O365",
                "buttons": [
                    {
                        "type": "signin",
                        "title": "Login",
                        "text": "Sign in to your O365 account",
                        "value": "https://token.botframework.com/api/oauth/signin?signin=88499424893c41c3bb30f70c4d06a0b8"
                    }
                ]
            }
        }
    ],
    "entities": [],
    "replyToId": "B30645BD-841B-EC54-88BB-52356522842C"
}`
#### Any screenshots or additional context?
As you can see, the Voice Assistant Client(Windows) and Virtual Assistant Client(Android) actually use the same configuration, but worked in different way.
![fdafdsafdas](https://user-images.githubusercontent.com/1256355/87396871-12fde300-c5e6-11ea-91c8-917e2e3f516e.png)

**Comment by mrivera-ms** [comment]
@KayMKM seems like there are two PRs that would resolve this issue. Could you please update this item with any progress? Thank you.

**Comment by KayMKM** [comment]
fixed
