### ISSUE TITLE
[Docs]Virtual Assistant Skill | Document has incomplete command 

### ISSUE THREAD

**Issue by MeenakshiBalekar** [microsoft/botframework-solutions#3554]
While we create a skill to be added to virtual assistant bot using link :
https://microsoft.github.io/botframework-solutions/skills/tutorials/create-skill/csharp/7-add-your-skill/

While adding the skill bot to VA, the command mentioned is :
botskills connect --remoteManifest "https://<YOUR_SKILL_NAME>.azurewebsites.net/manifest/manifest-1.1.json" --cs

which is incomplete and this needs to be with the LU folder location of the skill bot as follows :

botskills connect --remoteManifest "https://<YOUR_SKILL_NAME>.azurewebsites.net/manifest/manifest-1.1.json" --cs --luisFolder "Path to LU folder from Skill bot"

**Comment by Batta32** [comment]
Thanks @MeenakshiBalekar for reporting this issue! We will back to you as soon as we have any update 😊.

**Comment by Batta32** [comment]
Hi @MeenakshiBalekar, these changes are implemented in the PR #3565, which updates several documentation adding the missing parameter. Once that pull request is merged, the documentation will be updated.

Please feel free to add any feedback in the PR 😊.
