### ISSUE TITLE
Add Google OAuth settings to BFVirtualAssistant demo site

### ISSUE THREAD

**Issue by darrenj** [microsoft/botframework-solutions#356]
**Project**
Virtual Assistant

**Description**
Google OAuth isn't shown in linked accounts in our demo environment meaning Google Calendar scenarios couldn't be shown.

**To Reproduce**
Go to https://aka.ms/bfvirtualassistant and browse to Linked Accounts. Only Microsoft is shown

![image](https://user-images.githubusercontent.com/33519520/49086185-ccf6de80-f24b-11e8-859c-76787d69aa0b.png)

**Expected behaviour**

- Add Google Services Provider so it shows up in linked accounts.
![image](https://user-images.githubusercontent.com/33519520/49086271-0c252f80-f24c-11e8-8a1b-a3c914b9902f.png)
- Add simple documentation steps on how to add Google once proven ;-)

**Additional context**
- You can get Google oAuth information from [here](https://console.developers.google.com/)
- Test by unlinking microsoft, link a (test) google calendar account with calendar items for today and ask a calendar question.

**Comment by ryanisgrig** [comment]
Part of #346 work

**Comment by ryanisgrig** [comment]
Completed
