### ISSUE TITLE
[Docs] Power BI Template Error

### ISSUE THREAD

**Issue by tmcclell** [microsoft/botframework-solutions#3575]
![Annotation 2020-07-21 133303](https://user-images.githubusercontent.com/53481728/88087463-f36f3900-cb56-11ea-97c5-780f8e45d1d2.png)
**Please describe your request**

**Is this an issue with current documentation? If yes, please provide the link.**

When navigating to https://microsoft.github.io/botframework-solutions/solution-accelerators/tutorials/view-analytics/3-open-template/ and opening the template in Power Bi, I am presented with the attached error.

**Comment by lauren-mills** [comment]
Hi @tmcclell - there is an issue when opening the dashboard from the Microsoft App version of Power BI, but the desktop app should still work.

Here is another issue where more details have been discussed on the workaround: https://github.com/microsoft/botframework-solutions/issues/3508#issuecomment-656346440

**Comment by tmcclell** [comment]
Thanks for that – here is my version info.

[cid:image001.png@01D65F74.8AD41C10]

**Comment by lauren-mills** [comment]
This issue has been resolved. Please refer to #3591 for more information on the fix.
