### ISSUE TITLE
[Docs] Wrong image in SSO docs?

### ISSUE THREAD

**Issue by GitDruid** [microsoft/botframework-solutions#3578]
/overview/whats-new/1.0/enable-sso-with-skills-using-oauthcredentials-setting/

Is the coverlet.msbuild image related to "Add Setting to add an OAuth connection" ?

![add-nuget](https://user-images.githubusercontent.com/4527837/88192072-69010500-cc3c-11ea-9e36-78733c4ae877.png)

**Comment by lauren-mills** [comment]
Thanks for reporting! Looks like an oversight.
