### ISSUE TITLE
feedbacks on deploy.ps1

### ISSUE THREAD

**Issue by dawwa** [microsoft/botframework-solutions#3582]
here are some notes for sharing about the feedback of deploy.ps1
- Bug
  - Add useCosmosDb to all the resources and output sections that are dependent on cosmos DB, otherwise set it to false fail the deployment.
  - $outputs.qnaMaker.value.key is not valid for skill template output and missing null check in deploy.ps1
  - publish.ps1 encounters unexpected termination if invoked from another wrapper ps1, not root cause yet, most likely due to the `2>&1` of the `Invoke-Expression` for the `az webapp deployment` step.

- Multi-Regional Deployment Support
  - Support splitting templates for Global/Regional resource groups, e.g., cosmos db, bot service, global app insights for bot service in a global resource group, and storage, web app, cognitive service, app insights for web app host, etc.

- Parameters
  - `suffix` is used as Prefix for the created LUIS apps, which is not consistent for its purpose. Propose to use `name`+`suffix`+`locale`+`luisAppName`, e.g., `MyProjectName-Suffix_en-us_General`
  - Add support for specifying template file path as well, currently it assumes template.json always at a fixed relative path with the script root, e.g., `$PSScriptRoot '..' 'Resources' 'template.json'`
  - Add support for custom output file name for cognitiveModels.json, so that we can generate environment-specific config json, e.g., _`cognitiveModels.<EnvironmentName>.json`_
  - Add support for environment-specific appsettings.json, so the script will be able to update e.g., _`appsettings.<EnvironmentName>.json`_
  - Add support for publishing to LUIS staging, e.g., an option with `[switch]$publishToStaging` in UpdateLUIS method of luis_functions.ps1, to allow implementing no downtime deployment scenario.

- Logs
  - Seems like the log file is constructed in a form of json, if that's the intention, consider to ensure the content is valid and parsable for further consumption after the script completion.
  - Add support for custom output location for log file
  - Error message in a dedicate property rather than appending to the file end, which invalidates the json body and breaks the json parser
    ![image](https://user-images.githubusercontent.com/44714043/88219368-55db3e80-cc16-11ea-87a2-e97261e906f9.png)

- Dev Ex
  - Is it feasible to have single set of scripts compatible with both VA and Skill template? Concerning about potential diverge with more difference comparing to current state - so far looks like they just have a few lines of differences.
- Doc
  - luisServiceLocation at [deployment-scripts doc](https://microsoft.github.io/botframework-solutions/virtual-assistant/handbook/deployment-scripts/) is actually supposed to be luisRuntimeLocation

**Comment by peterinnesmsft** [comment]
Hi @dawwa,

Spoke offline with @lauren-mills - as I understand it, it sounds like we are in the middle of drafting feedback around these issues. Are there any more issues you are looking to collect here, or are these ready to be reviewed?

Thanks,
Peter

**Comment by dawwa** [comment]
Hi @peterinnesmsft, I'm collecting more, the list would grow for about another 1 or 2 weeks.

**Comment by pavolum** [comment]
@dawwa are we still gathering feedback?

**Comment by peterinnesmsft** [comment]
@dawwa what is the status of this? Is this the final list of items you would like to present to us for addressing? If we don't hear back in the next 48 hours, I'll assume that to be case and we'll consider this list locked.

**Comment by peterinnesmsft** [comment]
Hi @dawwa,

The team triaged this issue today, and so we are considering this issue locked. After reviewing, we agreed that it is reasonable for us to address the identified bugs.

For the other items, we anticipate that we will have a number of upcoming workstreams to help standardize our approach to provisioning and publishing, as well as CI/CD operations overall, across the various product offerings in the Bot Framework suite of products, such as Composer, Virtual Assistant, etc. We anticipate that we would address many of the suggestions you offer as part of these investments. Given such, we will not be taking on any of the other suggestions at this time to our existing PowerShell scripts beyond bug fixes and simple maintenance.

I will create separate issues to track the individual bugs captured here and ensure they are linked to this issue for visibility, then I will close out this one afterwards. We can then use the new issues to track progress against the individual bugs.

**Comment by dawwa** [comment]
yep, these are pretty much all of them, thanks for reviewing and set up plans for addressing these 👍,  looking forward to getting rid of most of my workaround and customization on the original-offered scripts after these are addressed. I'll file separate bugs if any more discovered.  @peterinnesmsft  @lauren-mills
