### ISSUE TITLE
Update Cognitive Service powershell script (qnamaker:kb:export) qna export mangles special characters

### ISSUE THREAD

**Issue by edemehmetcan** [microsoft/botframework-solutions#3586]
#### What project is affected?

Deployment script 

#### What happens?

Special characters : 
**Prompts:**
- [Plus d'information sur la lettre re├ºu des ├⌐l├⌐ctions ?](#66)

are exported like this

it needs to be - [Plus d'information sur la lettre reçu des éléctions ?](#66)

#### What are the steps to reproduce this issue?

Create a knowledge base
Use the special characters in the Question or Answer field
Export using the update_cognitive_services.ps1 script 
Inspect the resultant in Deployment/Resources/Qna/{language}/nameofknowledgebase.qna

#### What were you expecting to happen?

Support special characters such as é, ç, ë, à, etc.

**Comment by lauren-mills** [comment]
Hi @edemehmetcan, we have an updated version of the script in our next branch [here](https://github.com/microsoft/botframework-solutions/blob/next/samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Deployment/Scripts/update_cognitive_models.ps1). Can you test it out and see if it resolves this for you?

**Comment by edemehmetcan** [comment]
Just tried and works perfectly. Nice to have a quick answer @lauren-mills. Need to close the thread ?

**Comment by edemehmetcan** [comment]
I am reopening this issue, I have the same problem right now even if I have put "-encoding oem $($outJson)"

![image](https://user-images.githubusercontent.com/28989498/100215532-66c3f580-2f11-11eb-99e8-0070b7a24299.png)
