### ISSUE TITLE
Botskills list command gives "No Skills connected " message 

### ISSUE THREAD

**Issue by manish-95** [microsoft/botframework-solutions#3588]
#### What project is affected?
Botskills 1.0.16

#### What happens?
Even though the appsettings file contains entries for the Skill bots connected, the botskills command gives the message "There are no Skills connected to the assistant."
#### What are the steps to reproduce this issue?
1. Connect skills to VA.
2. Run botskills list
3. Note the error
#### What were you expecting to happen?
The botskills list scans appsettings.json and gives a list of skills connected to the VA.
#### Can you share any logs, error output, etc.?
![image](https://user-images.githubusercontent.com/29098159/88516021-3ffcbd80-d00a-11ea-8413-0c2652e5c11f.png)

#### Any screenshots or additional context?
![image](https://user-images.githubusercontent.com/29098159/88515983-2c515700-d00a-11ea-8cda-dffd836e0a82.png)

**Comment by Batta32** [comment]
Thanks @manish-95 for reporting this issue! We will back to you as soon as we have any update 😊.

**Comment by manish-95** [comment]
@Batta32 I notice that the latest version of the botskills tool adds the skill details under the key "**botFrameworkSkills**" whereas the older version I was using before added the skill under the key "**BotFrameworkSkills**"
I think this should be gracefully handled, since it causes a lot of confusion, and also provides almost no backward compatibility. Maybe a case neutral condition check for the key would be useful.

**Comment by Batta32** [comment]
@manish-95 - you are right, we are going to review this in order to avoid these kind of issues.

Meanwhile, as a **workaround**, you can follow these steps:
1. Open your Virtual Assistant's `appsettings.json` file
1. Change the _UpperCamelCase_ keys to _lowerCamelCase_ as follows:

```json
   "botFrameworkSkills": [
      {
         "id": "CalendarSkill",
         "appId": "xxx-xxx-xxxxxxx",
         "skillEndpoint": "https://webapp-endpoint/api/messages",
         "name": "Calendar Skill",
         "description": "Calendar Skill"
      },
      {
        "id": "EmailSkill",
        "appId": "xxx-xxx-xxxxxxx",
        "skillEndpoint": "https://webapp-endpoint/api/messages",
        "name": "Email Skill",
        "description": "Email Skill"
      },
      {
        "id": "EmceeSkillDev",
        "appId": "xxx-xxx-xxxxxxx",
        "skillEndpoint": "https://webapp-endpoint/api/messages",
        "name": "EmceeSkillDev",
        "description": "EmceeSkillDev"
      }
   ],
   "skillHostEndpoint": "<VA_SKILL_ENDPOINT>"
```

We will be attentive to your answer.

**Comment by Batta32** [comment]
Hi @manish-95 - we created the PR #3596 fixing this issue.

You can validate the changes following these steps:
1. Checkout to the branch [`southworks:feature/southworks/fix-botskills-list-retrocompat`](https://github.com/southworks/botframework-solutions/tree/feature/southworks/fix-botskills-list-retrocompat)
1. Go to the [botskills](https://github.com/southworks/botframework-solutions/tree/feature/southworks/fix-botskills-list-retrocompat/tools/botskills) tool
1. Execute `npm install` to install the depedencies
1. Execute `npm run build` to compile the solution
1. Execute `npm link` to link the tool. If you have installed botskills, you should execute `npm uninstall -g botskills` to uninstall the tool
1. Execute `botskills list` command to check that the connected skills are correctly listed

We will be attentive to your answer 😊!

**Comment by manish-95** [comment]
Hi @Batta32 , just validated the changes from your fix, and it works. Thank you for the prompt response and quick fix. 😄
