### ISSUE TITLE
Power BI Template does not work with latest PowerBI desktop

### ISSUE THREAD

**Issue by parshuramnaik** [microsoft/botframework-solutions#3593]
/solution-accelerators/tutorials/view-analytics/1-intro/

Hi,

The Analytics PowerBI template does not work with the PowerBI Desktop Update July 2020.
Can you please change the same?

Regards,
Parshuram Naik

**Comment by pavolum** [comment]
I am going to close this issue as it is being tracked here https://github.com/microsoft/botframework-solutions/issues/3591

**Comment by pavolum** [comment]
Hmm it seems I am not able
