### ISSUE TITLE
[C#][VA & Skill] Replace AzureBlobTranscriptStore references to BlobsTranscriptStore

### ISSUE THREAD

**Issue by Batta32** [microsoft/botframework-solutions#3613]
## User Story
As SDK R10 dotnet release was published
I want to rename the `AzureBlobTranscriptStore` with the new `BlobsTranscripStore` in C# bots

## Acceptance Criteria 
*List your requirements.*
- [X] Update the references of `AzureBlobTranscriptStore` to `BlobsTranscripStore` in the [DefaultAdapter](https://github.com/microsoft/botframework-solutions/blob/master/samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Adapters/DefaultAdapter.cs) of Virtual Assistant Sample
- [X] Update the references of `AzureBlobTranscriptStore` to `BlobsTranscripStore` in the [DefaultAdapter](https://github.com/microsoft/botframework-solutions/blob/master/samples/csharp/skill/SkillSample/Adapters/DefaultAdapter.cs) of Skill Sample
- [X] Validate the behavior of `BlobsTranscripStore`
- [X] Replicate the changes to templates

## Resources
*Provide any screenshots or conversation mockups to support your request.*
*Learn how to mock up bot conversations with [.chat files](http://aka.ms/bfchatfile).*
- Use [Microsoft.Bot.Builder@4.10.0](https://www.nuget.org/packages/Microsoft.Bot.Builder/4.10.0)
- Use [BlobsTranscriptStore](https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder.Azure.Blobs/BlobsTranscriptStore.cs)

## Notes
*Provide any additional information.*
\-

**Comment by Batta32** [comment]
@peterinnesmsft - as discussed, we created this issue for tracking purpose of the AzureBlobTranscriptStore's replacement to BlobsTranscriptStore in C# bots.

We will be updating this issue as soon as we have any update. Let me know if we should change anything on this 😊!

**Comment by Batta32** [comment]
Hi @peterinnesmsft - we created the PR #3616 updating the references of `AzureBlobTranscriptStore` references to `BlobsTranscriptStore` pointed to _next_ branch.

**Comment by Batta32** [comment]
This issue is solved with PR #3616.

**Comment by mrivera-ms** [comment]
@Batta32, what is the status of this issue? Could you please update this issue? Thank you.

**Comment by Batta32** [comment]
Hi @mrivera-ms , this issue is solved with the PR #3616 and its already approved. As soon as it's merged, this issue will be closed 😊.
