### ISSUE TITLE
[C#][Bot-Solutions] Avoid use of the Deprecated LuisServices class

### ISSUE THREAD

**Issue by Batta32** [microsoft/botframework-solutions#3617]
## User Story
As SDK R10 dotnet release was published
I want to avoid the _"LuisService is obsolete: This class is deprecated"_ error doing a rehome of the dependencies of [Microsoft.Bot.Configuration](https://www.nuget.org/packages/Microsoft.Bot.Configuration/) used in [BotSettingsBase](https://github.com/microsoft/botframework-solutions/blob/master/sdk/csharp/libraries/microsoft.bot.solutions/BotSettingsBase.cs)

## Acceptance Criteria 
*List your requirements.*
- [X] Migrate [LuisService](https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Configuration/Services/LuisService.cs), [QnAMakerService](https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Configuration/Services/QnAMakerService.cs), [ConnectedService](https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Configuration/Services/ConnectedService.cs), [ServiceTypes](https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Configuration/ServiceTypes.cs) to Microsoft.Bot.Solutions
- [X] Validate that the error is solved

## Resources
- Use [Microsoft.Bot.Builder@4.10.0](https://www.nuget.org/packages/Microsoft.Bot.Builder/4.10.0)

## Notes
*Provide any additional information.*
_BotSettingsBase.cs file with error_
![image](https://user-images.githubusercontent.com/11904023/90177738-58e2ce00-dd81-11ea-90b3-e953574cb94b.png)

**Comment by peterinnesmsft** [comment]
Hi @Batta32,

I did some further digging around and spoke to some folks on our team as well as in the SDK team. As I understand it, the dependencies that we have in Microsoft.Bot.Configuration that we use today (such as LuisService) are holdovers from the .bot file days, and the official recommendation from the SDK team appears to be that we should move away from depending on the SDK for these definitions in favor of customers defining their own.

Having discussed with the team, I think the right path forward for now is that we should take copies of any of the dependencies we have here on Microsoft.Bot.Configuration, and rehome them within Microsoft.Bot.Solutions. That way we can ensure we fully support this to our customers without them potentially being deprecated and removed from the SDK in the future.

Let's touch base tomorrow and we can figure out how to fit this into the backlog.

**Comment by Batta32** [comment]
Sure @peterinnesmsft ! We will review the used dependencies of `Microsoft.Bot.Configuration` in order to rehome them within `Microsoft.Bot.Solutions`.

We added this task in this iteration as top prior with the end-to-end test of R10 and we can review it today 😊.

**Comment by Batta32** [comment]
We've updated the description of this issue adding the necessary information to do the rehome of the `Microsoft.Bot.Configuration` dependencies to a new folder `Services` of `Microsoft.Bot.Solutions`

**Comment by Batta32** [comment]
This issue is solved with PR #3618.
