### ISSUE TITLE
[Docs] A sentence that may interrupt reading flow

### ISSUE THREAD

**Issue by qduyhoang** [microsoft/botframework-solutions#3619]
/overview/virtual-assistant-template/
In the following sentence, the phrase “bear in mind” being repeated twice interrupts my reading flow to stop and think whether if this was used intentionally or not.

> You are free to restructure this as necessary but bear in mind that the provided deployment scripts expect some files to be in a consistent location so bear this in mind.

**Comment by peterinnesmsft** [comment]
@qduyhoang thanks for raising this issue and submitting a PR to fix the documentation! I've taken a look and signed off on the PR. Will follow up with the rest of the team to get a second review so we can push this through.
