### ISSUE TITLE
[Docs] Incorrect headers for resource table in Virtual assistant template

### ISSUE THREAD

**Issue by qduyhoang** [microsoft/botframework-solutions#3620]
/overview/virtual-assistant-template/
Link: https://microsoft.github.io/botframework-solutions/overview/virtual-assistant-template/

In the Azure Resource Deployment section, a table with the names of the resources required is provided with two header columns “Resource” and “Description”. However, the table contains all names of resources and not their description.
![6284BAC5-EACD-46B9-B980-F5856C0E2ADF](https://user-images.githubusercontent.com/28582749/90333793-a421fa00-df96-11ea-9fbd-c5b3ae111798.png)

**Comment by peterinnesmsft** [comment]
@qduyhoang thanks for raising this issue and submitting a PR to fix the documentation! I've taken a look and signed off on the PR. Will follow up with the rest of the team to get a second review so we can push this through.
