### ISSUE TITLE
[Docs] Testing doc has outdated language / confusing references to skills projects

### ISSUE THREAD

**Issue by lauren-mills** [microsoft/botframework-solutions#3622]
/virtual-assistant/handbook/testing/

This doc seems to have some outdated references to .bot files and also seems to imply that connecting a skill to the VA is required for unit testing.

**Comment by peterinnesmsft** [comment]
@Batta32 adding this one to your team's backlog.

**Comment by Batta32** [comment]
Thanks @peterinnesmsft, we will be working on this!

**Comment by Batta32** [comment]
This issue is fixed by PR #3650.
