### ISSUE TITLE
Botskills "update" command creates a copy of the .luis file

### ISSUE THREAD

**Issue by manish-95** [microsoft/botframework-solutions#3623]
#### What project is affected?
botskills CLI tool version 1.0.16

#### What language is this in?
C#
#### What happens?
On running  `botskills update --localManifest "<path to manifest>" --luisFolder "<path to lu folder>" --languages "en-us" --cs --noRefresh true`, a copy of the .luis file is created in the Deployment/Resources/LU/en-us folder, while the existing .luis file remains unchanged. 
#### What are the steps to reproduce this issue?
1. Run the botskills update command as given above
2. Note the copy of the .luis file created
#### What were you expecting to happen?
The existing .luis file has to be updated with the latest changes, instead of a copy of the file created with the changes.

**Comment by Batta32** [comment]
Hi @manish-95, thanks for reporting this issue. We will be reviewing it and we will back to you soon 😊.

**Comment by Batta32** [comment]
@manish-95 - we confirmed that this issue is solved with the PR #3483 adding the `--force` for `bf luis:convert` method and will be fixed as soon as a new release of botskills is published.

**Comment by manish-95** [comment]
Hi @Batta32 , thanks for the quick update! When will the new release be out?

**Comment by Batta32** [comment]
@peterinnesmsft - I'm mentioning you here to review the comment of @manish-95 as we discussed in the meeting 😊.

**Comment by peterinnesmsft** [comment]
Hi @manish-95,

We have yet to target a specific date for our next release, but ideally we should be able to target early-mid September. I am currently looking to determine specifics and get outstanding items aligned before we lock on an exact date.

Let me know if you have any questions otherwise in the meantime.

**Comment by tdurnford** [comment]
@peterinnesmsft Any updates on this?

**Comment by Batta32** [comment]
This issue is **fixed** with the merged PR #3483 and the next botskills version will contain these changes.

@peterinnesmsft - should we keep this issue open until the new botskills version is published?
