### ISSUE TITLE
[Docs] The Azure resource deployment section contains incorrect column headers

### ISSUE THREAD

**Issue by VidhyaSanjeevi** [microsoft/botframework-solutions#3624]
/overview/virtual-assistant-template/
The Azure resource deployment section contains incorrect column headers as highlighted in the image below, please correct it.

![image](https://user-images.githubusercontent.com/24915474/90516994-6bdf0f00-e182-11ea-827e-0537df74603b.png)

Thanks.

**Comment by peterinnesmsft** [comment]
Hi @SSanjeevi,

This issue appears to be a dupe of #3620, which has a PR out to address this issue. As a result, I'm going to close out this issue. Please refer to the other issue and linked PR to track progress towards resolution of this issue.

Thanks!
