### ISSUE TITLE
BotFrameworkAdapter should be a singleton

### ISSUE THREAD

**Issue by sgellock** [microsoft/botframework-solutions#3627]
#### What project is affected?
SkillSample

#### What language is this in?
C#

#### What happens?
We're incorrectly setting up the BotFrameworkAdapter, which is causing auth token caching to be disabled.

Refer to:
https://github.com/microsoft/botframework-solutions/blob/970aaf144f06b6695bbf77ad5707344f825b92e6/samples/csharp/skill/SkillSample/Startup.cs#L124

**Comment by peterinnesmsft** [comment]
Keeping this issue open until we have successfully verified updated patch release for our VSIX template.

**Comment by peterinnesmsft** [comment]
Updated VSIX has been published and verified: https://marketplace.visualstudio.com/items?itemName=BotBuilder.VirtualAssistantTemplate
