### ISSUE TITLE
Virtual Assistant Template for Python

### ISSUE THREAD

**Issue by Adityagrao** [microsoft/botframework-solutions#3636]
## User Story
I have seen the assistant template for C# and Typescript, would the team consider adding a python template too? something with cookie-cutter maybe?

Can quickly bootstrap python bot development with a Virtual assistant template

## Acceptance Criteria 
- Add Template for VA Python codebase with deployment scripts
- Provide skill bot with calendar and email

**Comment by peterinnesmsft** [comment]
Hi @Adityagrao,

Thank you for submitting this ask. This is not currently on our team roadmap, and unfortunately we do not have the bandwidth to take on this item for the foreseeable future.

We can continue to evaluate whether we will take this on as part of our future roadmap, and if so will make sure it is tracked here so we can provide visibility to our customers. In the meantime, I am going to close this issue as it is unlikely we will get to this any time soon.
