### ISSUE TITLE
   Operation returned an invalid status code 'NotImplemented' when  Microsoft.Bot.Connector.ConversationsExtnsions.UpdateActivityAsync is called

### ISSUE THREAD

**Issue by ipraveenMS** [microsoft/botframework-solutions#3644]
#### What project is affected?
Skills
#### What language is this in?
c#
#### What happens?
I call UpdateActivityAsync and above error is thrown
#### What are the steps to reproduce this issue?
Call updateActivity function
#### What were you expecting to happen?
Success
#### Can you share any logs, error output, etc.?
 
   
   Operation returned an invalid status code 'NotImplemented'
   at Microsoft.Bot.Connector.Conversations.<UpdateActivityWithHttpMessagesAsync>d__9.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Bot.Connector.ConversationsExtensions.<UpdateActivityAsync>d__16.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
    	Obi.Skills.Common.dll!Microsoft.Obi.Skills.Common.Extensions.TurnContextEx.UpdateActivityAsync(Microsoft.Bot.Builder.ITurnContext turnContext, Microsoft.Bot.Schema.IMessageActivity activity, Microsoft.Bot.Schema.ConversationReference conversationReference, Microsoft.Bot.Solutions.Models.State.ActivityReference activityReference, System.Threading.CancellationToken cancellationToken) Line 69	C#

**Comment by Batta32** [comment]
Thanks @ipraveenMS for reporting this issue. We will be reviewing this and we will back to you as soon as we can 😊.

**Comment by peterinnesmsft** [comment]
Hi @ipraveenMS,

Thanks for creating this issue. In order to be able to investigate, we require some additional information:

- Can you confirm which version of the SDK libraries you are using?
- Can you also confirm which implementation of the BotAdapter class you are using? Typically this would be some utilization or implementation over BotFrameworkHttpAdapter/BotFrameworkHttpAdapterBase.
- Can you share any of the implementation for Microsoft.Obi.Skills.Common.Extensions.TurnContextEx.UpdateActivityAsync? Feel free to contact me offline with this information if it is sensitive.

If you can let us know then we can do some more digging. Thank you!

**Comment by ipraveenMS** [comment]
Thanks for the response. We will get back to you with the details.

**Comment by ipraveenMS** [comment]
@peterinnesmsft 

Here is the info.

>>>Can you confirm which version of the SDK libraries you are using?

Bot Framework SDK v4
Assembly Microsoft.Bot.Connector, Version=4.9.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35

>>>Can you also confirm which implementation of the BotAdapter class you are using? Typically this would be some utilization or implementation over BotFrameworkHttpAdapter/BotFrameworkHttpAdapterBase.

We are using   DefaultAdapter : BotFrameworkHttpAdapter

>>>Can you share any of the implementation for Microsoft.Obi.Skills.Common.Extensions.TurnContextEx.UpdateActivityAsync? Feel free to contact me offline with this information if it is sensitive.

Below is the code (made sure it does not have anything sensitive)

public static async Task<ActivityReference> UpdateActivityAsync(
            this ITurnContext turnContext,
            IMessageActivity activity,
            ConversationReference conversationReference,
            ActivityReference activityReference,
            CancellationToken cancellationToken)
        {
            activity.OnBeforeUpdateActivity();

            if (string.IsNullOrEmpty(activityReference?.ActivityId))
            {
                throw new InvalidOperationException(
                    $"{nameof(UpdateActivityAsync)}: Failed to update activity in channel {conversationReference.ChannelId}." +
                    $" Activity should have ActivityId defined.");
            }

            var connectorClient = turnContext.TurnState.Get<IConnectorClient>();           

            await connectorClient.Conversations.UpdateActivityAsync(
                conversationReference.Conversation.Id,
                activityReference.ActivityId,
                (Activity)activity,
                cancellationToken);

            return activityReference;
        }

**Comment by ipraveenMS** [comment]
I found some new clues now.. let me update this thread soon.

**Comment by ipraveenMS** [comment]
Upon further investigation, the UpdateActivityAsync call hits the ngrok end point and goes to the https://myVAName.ngrok.io\api/skills (VA uses the BF SDK similar to above, it also uses DefaultAdapter similar to above)

there it is routed to 
[Route("api/skills")]
    [ApiController]
    public class SkillController : ChannelServiceController

from that class uses the below base class implementation. here is its signature.
	
   [HttpPut("v3/conversations/{conversationId}/activities/{activityId}")]
   ChannelServiceController
        public async Task<IActionResult> UpdateActivityAsync(string conversationId, string activityId, [FromBody] Microsoft.Bot.Schema.Activity activity)

the value of   conversationId param above: 19:71c2eb2bace04ca1b67d185bbb0f6055@thread.tacv2;messageid=1599156698606-IcM-msteams-skillconvo
   
   This is the error thrown (I uses a override of the base class implementation function to catch the exception)

   {"The method or operation is not implemented."}
      at Microsoft.Bot.Builder.ChannelServiceHandler.OnUpdateActivityAsync(ClaimsIdentity claimsIdentity, String conversationId, String activityId, Activity activity, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.ChannelServiceHandler.<HandleUpdateActivityAsync>d__8.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Bot.Builder.Integration.AspNet.Core.ChannelServiceController.<UpdateActivityAsync>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Obi.VirtualAssistant.Controllers.SkillController.<UpdateActivityAsync>d__1.MoveNext() in C:\<path>\VirtualAssistant\Controllers\SkillController.cs:line 47

**Comment by GeoffCoxMSFT** [comment]
@ipraveenMS - Hello.  We assumed you are a Microsoft employee because your alias ends in MS.  If you are a Microsoft employee, I highly recommend joining the Microsoft organization on GitHub.  It helps teams distinguish between customer and internal reporting of issues.

https://docs.opensource.microsoft.com/tools/github/accounts/linking.html

**Comment by ipraveenMS** [comment]
Hi My acc is already linked. Will provide more details in private message.

**Comment by ipraveenMS** [comment]
@peterinnesmsft its been many days this issue is open. We need help

**Comment by peterinnesmsft** [comment]
Hi @ipraveenMS,

Can you confirm what version of the ChannelServiceHandler class is being registered with your IServiceCollection container as part of your virtual assistant's startup logic?

Based on what you're presenting, it sounds like the issue is that it's resolving the base class type, which by default doesn't implement OnUpdateActivityAsync. ChannelServiceHandler seems to be a little confusing reading it - I get the sense that it ought to be an abstract class, but instead it is instantiable with virtual implementations of most functions that throw NotImplementedException.

Per the default VA project template that we provide, we provide a class called [TokenExchangeSkillHandler](https://github.com/microsoft/botframework-solutions/blob/master/templates/csharp/VA/VA/TokenExchange/TokenExchangeSkillHandler.cs) that looks to provide an implementation for this particular type. I would recommend using this, and ensuring it is registered as part of your Startup implementation, as for example seen [here](https://github.com/microsoft/botframework-solutions/blob/4d23f882776d4a730770e3576f660d629ee92360/templates/csharp/VA/VA/Startup.cs#L121).

If for whatever reason you are unable to use that class, then the SkillHandler class defined in the SDK should be usable, otherwise you may provide your own implementation.

Let me know if you have any success with that.

**Comment by ipraveenMS** [comment]
Hi @peterinnesmsft thanks for the reply. I was able to repro with simple code also. Details at https://github.com/microsoft/botframework-solutions/issues/3676 this issue was closed but I didnt get an answer there. I will take a look at your answer and post a reply soon (about a week )

**Comment by ipraveenMS** [comment]
@peterinnesmsft    TokenExchangeSkillHandler does not implement UpdateActivityAsync and parent of its base is
   https://github.com/gridgentoo/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder/ChannelServiceHandler.cs which does not have UpdateActivityAsync implemented
   
   TokenExchangeSkillHandler is present in VA and is registered during the startup. When UpdateActivityAsync is called from skill, it calls UpdateActivityAsync of SkillController which is derived from ChannelServiceController. ChannelServiceController calls UpdateActivityAsync of TokenExchangeSkillHandler which calls the implementation in base class chain ChannelServiceHandler which throws Not implemented exception.
   
   So we need an implementation in TokenExchangeSkillHandler which is not provided by the bot framework team.
   
   Below is the stacktrace of the Not implemented exception on the VA side.
   
    at Microsoft.Bot.Builder.ChannelServiceHandler.OnUpdateActivityAsync(ClaimsIdentity claimsIdentity, String conversationId, String activityId, Activity activity, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.ChannelServiceHandler.<HandleUpdateActivityAsync>d__8.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Bot.Builder.Integration.AspNet.Core.ChannelServiceController.<UpdateActivityAsync>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

**Comment by Aavi2105** [comment]
Hi @ipraveenMS :- I came across similar issue where I am using updateactivity method from skill for replacing existing adaptive card activity with another card. Below is the code snippet which have written in my skill bot, but when it tries to call updateactivity method then it throws  out same error "Operation returned an invalid status code 'NotImplemented'. Please suggest if you found any solution to resolve it. 

protected override async Task<DialogTurnResult> OnContinueDialogAsync(DialogContext innerDc, CancellationToken cancellationToken = default)
{
    var activity = innerDc.Context.Activity;

    if (innerDc.ActiveDialog.State.ContainsKey("adaptivecardactivityid"))
    {
        object card = new AdaptiveCard("1.0")
        {
            Body = new List<AdaptiveElement>
            {
                new AdaptiveTextBlock
                {
                    Text = "Cards library demo",
                    Size = AdaptiveTextSize.ExtraLarge,
                    Weight = AdaptiveTextWeight.Bolder,
                    Wrap = true,
                },
                new AdaptiveTextBlock
                {
                    Text = "Adaptive Card translation",
                    Size = AdaptiveTextSize.Large,
                    Weight = AdaptiveTextWeight.Bolder,
                    Wrap = true,
                },
                new AdaptiveTextInput
                {
                    Id = IdText,
                    Placeholder = "Text",
                },
                new AdaptiveNumberInput
                {
                    Id = IdNumber,
                    Placeholder = "Number",
                },
                new AdaptiveDateInput
                {
                    Id = IdDate,
                    Placeholder = "Date",
                },
                new AdaptiveTextBlock
                {
                    Text = "Fill in the inputs and then click a button to see if the values are preserved."
                            + " (This demo only applies to Microsoft Teams)",
                    Wrap = true,
                },
            },
            Actions = new List<AdaptiveAction>
            {
                new AdaptiveSubmitAction
                {
                    Title = "Submit normally",
                    Data = new
                    {
                        behavior = BehaviorSubmit,
                    },
                },
                new AdaptiveSubmitAction
                {
                    Title = "Submit and preserve",
                    Data = new
                    {
                        behavior = BehaviorPreserve,
                    },
                },
            },
        };

        var attachment = new Attachment()
        {
            ContentType = AdaptiveCard.ContentType,
            Content = card,
        };

        await innerDc.Context.SendActivityAsync(activity.ChannelId);  // I get this as msteams channel in omnichannl customer chat visit.

        var update = innerDc.Context.Activity.CreateReply(activity.Text);

        update.Attachments = new List<Attachment> { attachment };
        update.Id = innerDc.ActiveDialog.State["adaptivecardactivityid"].ToString();

        await innerDc.Context.SendActivityAsync(innerDc.ActiveDialog.State["adaptivecardactivityid"].ToString()); // For Print
        await innerDc.Context.UpdateActivityAsync(update, cancellationToken);
        await innerDc.Context.SendActivityAsync("Update Successfully"); // For Print

        var actionResponse = new SampleActionOutput
        {
            CustomerId = activity.Conversation.Id,
            CustmerResponse = "ABC",
            CustmerResponseId = "DummyId"
            //val.selectedId

        }

        return await innerDc.EndDialogAsync(actionResponse, cancellationToken);
    }

    return await base.OnContinueDialogAsync(innerDc, cancellationToken);
}

**Comment by ipraveenMS** [comment]
@Aavi2105 file a new issue. This might be something different. To get more insight, you can download the binaries and code and debug. This calls the functionality of the VA side
