### ISSUE TITLE
[Docs] "Connect to a sample" docs do not include the step to update the manifest

### ISSUE THREAD

**Issue by lauren-mills** [microsoft/botframework-solutions#3645]
/skills/tutorials/add-prebuilt-skill/3-deploy-skill-project/

This tutorial is missing the step to update the skill manifest after deployment. Otherwise it will not be able to be connected to a VA

**Comment by peterinnesmsft** [comment]
@Batta32 adding this one to your team's backlog.

**Comment by Batta32** [comment]
Thanks @peterinnesmsft, we will be working on this!

**Comment by Batta32** [comment]
This issue is fixed by PR #3651.
