### ISSUE TITLE
Need more clarity on this documentation - updateCogintiveModels[Docs]

### ISSUE THREAD

**Issue by saikumaru** [microsoft/botframework-solutions#3656]
/virtual-assistant/handbook/deployment-scripts/

This part 
Run the following command from your project directory to export the .lu schema of your LUIS model and update your Dispatch model and DispatchLuis.cs file:
` .\Deployment\Scripts\update_cognitive_model.ps1 -RemoteToLocal`

 Do you mean "import the .lu schema"? because with -RemoteToLocal we arent exporting anything.

Please advice

**Comment by Batta32** [comment]
Thanks @saikumaru for reporting this issue!
Reviewing the [/virtual-assistant/handbook/deployment-scripts](https://microsoft.github.io/botframework-solutions/virtual-assistant/handbook/deployment-scripts/) document, the `RemoteToLocal` is a flag to indicate that local files should be updated based on hosted models. Basically, to **import** the hosted models updating the local LU files.

As soon as we have any update related to the documentation, we will let you know 😊.

_RemoteToLocal definition_
![image](https://user-images.githubusercontent.com/11904023/93086767-fd507c80-f66d-11ea-8668-8bca49ded371.png)

**Comment by Batta32** [comment]
Hi @saikumaru , we created the PR #3661 fixing the definition of `RemoteToLocal` argument.

Feel free to add your feedback in the Pull Request!

**Comment by Batta32** [comment]
This issue is fixed with PR #3661
