### ISSUE TITLE
[MS Teams] Unable to upload attachments to bot

### ISSUE THREAD

**Issue by mrakn** [microsoft/botframework-solutions#3657]
Hi,

We have 1v1 bot available to our users through MS Teams. Since roughly this week, it is no longer possible to upload attachments to the bot - it fails with error (see below).

The uploading itself is done simply by opening up chat window with bot, clicking on paperclip icon, clicking on _Upload from my computer_ and finally choosing the file to upload:
![att01](https://user-images.githubusercontent.com/64434438/93337320-4862bf00-f829-11ea-9fbc-2043a1d96ab4.png)

The progress bar then appears:
![att03](https://user-images.githubusercontent.com/64434438/93337465-75af6d00-f829-11ea-913e-77375f2612a1.png)

After uploading completes, the following error popup is displayed and attachment is not sent over:
![att02](https://user-images.githubusercontent.com/64434438/93337211-1d786b00-f829-11ea-9a2c-3786461cc77c.png)

Additional notes:
* Choosing _Onedrive_ option does not show the error popup, but no file is sent - nothing happens.
* The file type and size does not matter. But all the tests were done with png and txt file with no more than few kilobytes.
* The error happens in both the desktop and web version of Teams client.
* Same error happens for all of our Teams enabled bots, including one that was set up just last week.
* The error does not happen if inline image is pasted and sent over.
* The Teams tenant is based in Europe.
* This should be irrelevant, but the bot itself is powered by .NET SDK of MS Bot Framework v4 and hosted in Azure with MS Teams enabled as one of its channels.

For the reference, here is Teams package manifest:
```
{
    "$schema": "https://developer.microsoft.com/en-us/json-schemas/teams/v1.7/MicrosoftTeams.schema.json",
    "manifestVersion": "1.7",
    "version": "0.0.1",
    "id": "<removed>",
    "packageName": "<removed>",
    "developer": {
        "name": "<removed>",
        "websiteUrl": "<removed>",
        "privacyUrl": "<removed>",
        "termsOfUseUrl": "<removed>"
    },
    "icons": {
        "color": "color.png",
        "outline": "outline.png"
    },
    "name": {
        "short": "<removed>",
        "full": "<removed>"
    },
    "description": {
        "short": "<removed>",
        "full": "<removed>"
    },
    "accentColor": "#761092",
    "bots": [
        {
            "botId": "<removed>",
            "scopes": [
                "personal"
            ],
            "supportsFiles": true,
            "isNotificationOnly": false
        }
    ],
    "permissions": [
        "identity",
        "messageTeamMembers"
    ],
    "validDomains": []
}
```

Will appreciate any ideas, thanks.

**Comment by Batta32** [comment]
Thanks @mrakn for reporting this issue! We have some questions in order to validate the environment that you are using:
1. What do you mean with "_1v1 bot_"?
1. Are you using a Virtual Assistant or a Skill?
1. Are you using C# or TypeScript?
1. Can you check the version of the BF SDK that you are using? A week ago, the BF SDK@4.10.3 was released in [TypeScript](https://www.npmjs.com/package/botbuilder/v/4.10.3) and [C#](https://www.nuget.org/packages/Microsoft.Bot.Builder/4.10.3)

As soon as we have any update, we will back to you 😊.

**Comment by mrakn** [comment]
Hi @Batta32, strangely I tried it again just 2 days after I opened this issue and everything is working now. The attachment uploading now works. We did not do any code changes or app manifest publishes to none of our bots.

Closing.

**Comment by Batta32** [comment]
Great @mrakn! If you have another problem just feel free to open a new issue 😊.
