### ISSUE TITLE
luis.endpoint in the generated appsettings.json is assigned with authoring endpoint

### ISSUE THREAD

**Issue by dawwa** [microsoft/botframework-solutions#3659]
CLI Version: @microsoft/botframework-cli/4.9.1 win32-x64 node-v12.16.3

This is what gets generated for the luis section in the appsettings.json for both VA and Skill Projects.
Or is endpoint meaning authoringEndpoint instead of runtime endpoint?

Actual:
https://dawwavatest-luisauthoring-xca4duu.cognitiveservices.azure.com/

Expected: 
https://dawwavatest-luisruntime-xca4duu.cognitiveservices.azure.com/

```json
  "luis": {
    "accountName": "dawwaVaTest-luisruntime-xca4duu",
    "authoringKey": "XXXXXXXXXXXXXXXXXXXXXXXXX",
    "authoringRegion": "WestUS",
    "endpoint": "https://dawwavatest-luisauthoring-xca4duu.cognitiveservices.azure.com/",
    "key": "XXXXXXXXXXXXXXXXX",
    "region": "westus"
  },
```

**Comment by Batta32** [comment]
Thanks @dawwa for reporting this issue, we will be reviewing the use and meaning of `endpoint` in the luis section after the deployment of a bot.
As soon as we have any update, we will back to you 😊.

**Comment by Batta32** [comment]
Hi @dawwa, sorry for the delay. We successfully **reproduced** this issue and **found** inconsistencies in the deployment of the bots. However, the `luis` section **doesn't affect** to the functionality of the bots.

By default, the deployed one should be `luisauthoring` following this [document](https://microsoft.github.io/botframework-solutions/virtual-assistant/handbook/deployment-scripts/) (check `useLuisAuthoring` property of `How do I customize my Azure resource deployment?` section set in true) but it's deploying the `luisruntime`.

### Problem
We found that deploying the bots, the `luis` section of the `appsettings.json` is not correctly populated. The `endpoint` and the `authoringKey` are empty.

![image](https://user-images.githubusercontent.com/11904023/94687196-4f4a0100-0302-11eb-9ec6-fcbcf30dba58.png)

### Workaround
Change the [luis](https://github.com/microsoft/botframework-solutions/blob/master/samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Deployment/Resources/template.json#L488) section of the `template.json` as follows (check the `endpoint` property)

```JSON
  "luis": {
    "type": "object",
    "value": {
      "accountName": "[parameters('luisRuntimeName')]",
      "region": "[parameters('luisRuntimeLocation')]",
      "key": "[listKeys(resourceId('Microsoft.CognitiveServices/accounts', parameters('luisRuntimeName')),'2016-02-01-preview').key1]",
      "authoringRegion": "[parameters('luisAuthoringLocation')]",
      "authoringKey": "[if(parameters('useLuisAuthoring'), listKeys(resourceId('Microsoft.CognitiveServices/accounts', parameters('luisAuthoringName')),'2016-02-01-preview').key1, '']",
      "endpoint": "[if(parameters('useLuisAuthoring'), reference(resourceId('Microsoft.CognitiveServices/accounts', parameters('luisAuthoringName')),'2016-02-01-preview').endpoint, reference(resourceId('Microsoft.CognitiveServices/accounts', parameters('luisRuntimeName')),'2016-02-01-preview').endpoint)]"
    }
  },
```

### Cause
The [template.json](https://github.com/microsoft/botframework-solutions/blob/master/samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Deployment/Resources/template.json#L496) searches for the `luisauthoring` cognitive service, but the deployed one is the `luisruntime` by default.

![image](https://user-images.githubusercontent.com/11904023/94687220-5a049600-0302-11eb-8965-78f630eeee36.png)

### Repro steps:
1. Go to the [C# Virtual Assistant Sample](https://github.com/microsoft/botframework-solutions/tree/master/samples/csharp/assistants/virtual-assistant/VirtualAssistantSample) of master branch
1. Deploy the Virtual Assistant using the `deploy.ps1` script
1. Check that in the `luis` section of the `appsettings.json` is missing the `endpoint` and `authoringKey` values

We will back to you as soon as we have any update 😊.

**Comment by Batta32** [comment]
Hi @dawwa, sorry for the delay. After more research, we found that the **correct endpoint** of the luis section in the `appsettings.json` file is the **authoringEndpoint** as it's right now.

`luisRuntime` and `luisAuthoring` were introduced in the PR #2790 fixing the issue #2496 updating the ARM templates to deploy the Luis Authoring resource and remove the need for acquiring Authoring Key manually from [luis.ai](https://www.luis.ai/).

Before this change, `luisRuntime` was called [luisService](https://github.com/microsoft/botframework-solutions/blame/6e8bd214e7a38e0eb0510a9a036aeff8f8aa4dd5/templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Deployment/Resources/template.json#L86) which doesn't contain authoring properties in the [luis](https://github.com/microsoft/botframework-solutions/blame/6e8bd214e7a38e0eb0510a9a036aeff8f8aa4dd5/templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Deployment/Resources/template.json#L377) section.

Following this [documentation](https://docs.microsoft.com/en-us/azure/cognitive-services/luis/luis-how-to-azure-subscription), we identified that LUIS allows the Authoring Resource and Prediction Resource:
- _Authoring Resource_: allows to create, manage, train, test and publish applications. There is one tier available for the LUIS Authoring Resource (F0). The kind of this Cognitive service is LUIS.Authoring.
- _Prediction Resource_: allows to query prediction endpoint requests. There are two tiers available for the prediction resource (F0 and S0). The kind of this Cognitive service is LUIS.

Having in that in mind, we noticed that the deployed `luisAuthoring` is the Authoring Resource as contains [F0](https://github.com/microsoft/botframework-solutions/blob/master/samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Deployment/Resources/template.json#L116) and the kind is [LUIS.Authoring](https://github.com/microsoft/botframework-solutions/blob/master/samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Deployment/Resources/template.json#L350).
Also, the `luisRuntime` is the Prediction Resource as contains [S0](https://github.com/microsoft/botframework-solutions/blob/master/samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Deployment/Resources/template.json#L100) and the kind is [LUIS](https://github.com/microsoft/botframework-solutions/blob/master/samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Deployment/Resources/template.json#L334).

Let us know if this helps 😊.

**Comment by Batta32** [comment]
Hi @dawwa, we created the PR #3682 that clarifies the `luis` section and updates the documentation.

Feel free to add your feedback on the Pull Request!
