### ISSUE TITLE
There was an error while connecting the Skill to the Assistant

### ISSUE THREAD

**Issue by vkansal01** [microsoft/botframework-solutions#3660]
**There was an error while connecting the Skill to the Assistant: SyntaxError: Unexpected token / in JSON at position 49.**

when i tried to use bot skills connect.

 botskills connect --remoteManifest "/manifest/manifest1.json" --cs --luisFolder  "D:\VirtualAssistantexample\VirtualAssistantexample\VirtualAssistantexample\Deployment\Resources" 
i am getting below error what json i have to check and where?

There was an error while connecting the Skill to the Assistant: SyntaxError: Unexpected token / in JSON at position 49.

**Comment by Batta32** [comment]
Thanks @vkansal01 for reporting this issue! Can you check if the Virtual Assistant `cognitivemodels.json` file contains a correct JSON structure?


Also, we have some questions in order to validate your environment:
1. Which version of botskills are you using?
1. Are you executing the botskills connect command in the Virtual Assistant location?
1. Is the path to the remote `manifest1.json` correct?
1. Have you deployed the Virtual Assistant and the Skill using the `deploy.ps1`?

As soon as we have any update, we will back to you 😊.

**Comment by vkansal01** [comment]
Right now i am getting  below error i.e.
**There was an error while connecting the Skill to the Assistant:
SyntaxError: Unexpected string in JSON at position 337**
 i am using Calendar skill _**_skill-manifest-2.1.preview-0_**_ 
Are you executing the botskills connect command in the Virtual Assistant location? YEs
Is the path to the remote manifest1.json correct? Yes
Have you deployed the Virtual Assistant and the Skill using the deploy.ps1?No we have deployed using Web deployment.
its showing 337 json position unexpected string error where i have to check.

**Comment by Batta32** [comment]
Thanks for your reply @vkansal01, this issue is related to one of the JSON file that botskills is consuming when botskills connect is executed.

Taking into account you mentioned that you have deployed the bots using Web deployment, can you confirm if the structure of the `cognitivemodels.json` and the `appsettings.json` of your Virtual Assistant is correct?

You can find the following **documents** to deploy your bots:
* Using the web deployment: [/virtual-assistant/tutorials/deploy-assistant/web/1-intro/](https://microsoft.github.io/botframework-solutions/virtual-assistant/tutorials/deploy-assistant/web/1-intro/)
* Using the CLI Tool that we provide to simplify the deployment process: [/virtual-assistant/tutorials/deploy-assistant/cli/1-intro/](https://microsoft.github.io/botframework-solutions/virtual-assistant/tutorials/deploy-assistant/cli/1-intro/)

Let me know if this helps to you 😊

**Comment by vkansal01** [comment]
We are using both file cognitivemodels.json and the appsettings.json. i am sending you my file content

**Comment by vkansal01** [comment]
Skill file.
{
  "$schema": "https://schemas.botframework.com/schemas/skills/skill-manifest-2.1.preview-0.json",
  "$id": "EmailSkill",
  "name": "Email Skill",
  "description": "The Email skill provides email related capabilities and supports Office and Google calendars.",
  "publisherName": "Microsoft",
  "version": "1.1",
  "iconUrl": "https://{YOUR_SKILL_URL}/images/EmailSkill.png",
  "copyright": "Copyright (c) Microsoft Corporation. All rights reserved.",
  "license": "",
  "privacyUrl": "https://{YOUR_SKILL_URL}/privacy.html",
  "tags": [
    "email",
    "skill"
  ],
  "endpoints": [
    {
      "name": "production",
      "protocol": "BotFrameworkV3",
      "description": "Production endpoint for the Email Skill",
      "endpointUrl": "https://{YOUR_SKILL_URL}/api/messages",
      "msAppId": "{YOUR_SKILL_APPID}"
    }
  ],
  "dispatchModels": {
    "languages": {
      "en-us": [
        {
          "id": "EmailLuModel-en",
          "name": "EmailSkill LU (English)",
          "contentType": "application/lu",
          "url": "file://Email.lu",
          "description": "English language model for the skill"
        }
      ],
      "de-de": [
        {
          "id": "EmailLuModel-de",
          "name": "EmailSkill LU (German)",
          "contentType": "application/lu",
          "url": "file://Email.lu",
          "description": "German language model for the skill"
        }
      ],
      "es-es": [
        {
          "id": "EmailLuModel-es",
          "name": "EmailSkill LU (Spanish)",
          "contentType": "application/lu",
          "url": "file://Email.lu",
          "description": "Spanish language model for the skill"
        }
      ],
      "fr-fr": [
        {
          "id": "EmailLuModel-fr",
          "name": "EmailSkill LU (French)",
          "contentType": "application/lu",
          "url": "file://Email.lu",
          "description": "French language model for the skill"
        }
      ],
      "it-it": [
        {
          "id": "EmailLuModel-it",
          "name": "EmailSkill LU (Italian)",
          "contentType": "application/lu",
          "url": "file://Email.lu",
          "description": "Italian language model for the skill"
        }
      ],
      "zh-cn": [
        {
          "id": "EmailLuModel-zh",
          "name": "EmailSkill LU (Chinese)",
          "contentType": "application/lu",
          "url": "file://Email.lu",
          "description": "Chinese language model for the skill"
        }
      ]
    },
    "intents": {
      "SendEmail": "#/activities/message",
      "Forward": "#/activities/message",
      "Reply": "#/activities/message",
      "SearchMessages": "#/activities/message",
      "CheckMessages": "#/activities/message",
      "ReadAloud": "#/activities/message",
      "QueryLastText": "#/activities/message",
      "Delete": "#/activities/message",
      "*": "#/activities/message"
    }
  },
  "activities": {
    "message": {
      "type": "message",
      "description": "Receives the users utterance and attempts to resolve it using the skill's LU models"
    },
    "sendEmail": {
      "description": "Send an Email",
      "type": "event",
      "name": "SendEmail",
      "value": {
        "$ref": "#/definitions/emailInfo"
      },
      "resultValue": {
        "$ref": "#/definitions/actionResult"
      }
    },
    "deleteEmail": {
      "description": "Delete an Email",
      "type": "event",
      "name": "DeleteEmail",
      "value": {},
      "resultValue": {
        "$ref": "#/definitions/actionResult"
      }
    },
    "replyEmail": {
      "description": "Reply to an Email",
      "type": "event",
      "name": "ReplyEmail",
      "value": {
        "$ref": "#/definitions/replyEmailInfo"
      },
      "resultValue": {
        "$ref": "#/definitions/actionResult"
      }
    },
    "forwardEmail": {
      "description": "Forward an Email",
      "type": "event",
      "name": "ForwardEmail",
      "value": {
        "$ref": "#/definitions/forwardEmailInfo"
      },
      "resultValue": {
        "$ref": "#/definitions/actionResult"
      }
    },
    "summary": {
      "description": "Summary of recent emails",
      "type": "event",
      "name": "EmailSummary",
      "value": {},
      "resultValue": {
        "$ref": "#/definitions/summaryResult"
      }
    }
  },
  "definitions": {
    "emailInfo": {
      "type": "object",
      "properties": {
        "subject": {
          "type": "string",
          "description": "Subject of the email"
        },
        "content": {
          "type": "string",
          "description": "Content of the email"
        },
        "sender": {
          "type": "string",
          "description": "Email address of email sender"
        },
        "recipients": {
          "type": "array",
          "description": "List of email addresses to send to",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "replyEmailInfo": {
      "type": "object",
      "properties": {
        "replyMessage": {
          "type": "string",
          "description": "The reply message"
        }
      }
    },
    "forwardEmailInfo": {
      "type": "object",
      "properties": {
        "forwardRecipients": {
          "type": "array",
          "description": "List of email addresses to forward to",
          "items": {
            "type": "string"
          }
        },
        "forwardMessage": {
          "type": "string",
          "description": "The message to forward"
        }
      }
    },
    "actionResult": {
      "type": "object",
      "properties": {
        "actionSuccess": {
          "type": "boolean",
          "description": "result of action"
        }
      }
    },
    "summaryResult": {
      "type": "object",
      "properties": {
        "actionSuccess": {
          "type": "boolean",
          "description": "result of action"
        },
        "emailList": {
          "type": "array",
          "description": "List of recent emails",
          "items": {
            "$ref": "#/definitions/emailInfo"
          }
        }
      }
    }
  }
}

**Comment by vkansal01** [comment]
Cognitivemodel.json

{
  "cognitiveModels": {
    "en-us": {
      "languageModels": [
        {
          "authoringRegion": "southcentralus",
          "type": "luis",
          "appId": "",
          "authoringKey": "",
          "id": "VirtualAssistantSkillen_Calendar",
          "name": "VirtualAssistantSkillen_Calendar",
          "region": "southcentralus",
          "subscriptionKey": "",
          "version": "0.1"
        },
        {
          "type": "luis",
          "id": "VirtualAssistantSkillen_General",
          "name": "VirtualAssistantSkillen_General",
          "appId": "",
          "authoringKey": "",
          "authoringRegion": "",
          "subscriptionKey": "",
          "version": "0.1",
          "region": "southcentralus"
        }
      ]
    }
  },
  "defaultLocale": "en-us"
}

**Comment by vkansal01** [comment]
Appsetting.json

{
  "microsoftAppId": "",
  "microsoftAppPassword": "",
  "botWebAppName": "VirtualAssistantCalendarBot",
  "translatorKey": ""
  "oauthConnections": [
    {
      "name": "",
      "provider": "",
      "type": "openUrl"
    }
  ],
  "ApplicationInsights": {
    "InstrumentationKey": ""
  },
  "blobStorage": {
    "type": "",
    "connectionString": "",
    "container": "calendarbotlog",
    "storageAccountName": "",
    "id": "",
    "name": "BlobStorage"
  },
  "cosmosDb": {
     "type": "cosmosdb",
    "collectionId": "",
    "databaseId": "",
    "cosmosDBEndpoint": "",
    "authKey": "",
    "id": "",
    "name": ""
  },
  "luis": {
    "type": "luis",
    "id": "VirtualAssistantSkillen_General",
    "name": "VirtualAssistantSkillen_General",
    "appId": "",
    "authoringKey": "",
    "authoringRegion": "",
    "subscriptionKey": "",
    "version": "0.1",
    "region": ""
  },
  "googleAppName": "",
  "googleClientId": "",
  "googleClientSecret": "",
  "googleScopes": "https://www.googleapis.com/auth/calendar, https://www.googleapis.com/auth/contacts",
  "DisplaySize": 3,
  "defaultValue": {
    "createMeeting": [
      {
        "name": "EventTitle",
        "isSkipByDefault": false
      },
      {
        "name": "EventContent",
        "isSkipByDefault": false
      },
      {
        "name": "EventStartDate",
        "isSkipByDefault": false,
        "defaultValue": ""
      },
      {
        "name": "EventDuration",
        "isSkipByDefault": false,
        "defaultValue": ""
      },
      {
        "name": "EventLocation",
        "isSkipByDefault": false
      }
    ]
  },
  "restrictedValue": {
    "meetingTime": [
      {
        "name": "WorkTimeStart",
        "isRestricted": true,
        "value": "8:00:00"
      },
      {
        "name": "WorkTimeEnd",
        "isRestricted": true,
        "value": "17:00:00"
      }
    ]
  },
  "azureMapsKey": "",
  "bingSpellCheckSubscriptionKey": ""
}

**Comment by Batta32** [comment]
Thanks @vkansal01 for attaching those files! We will be reviewing this issue and as soon as we have any update, we will back to you 😊.

**Comment by Batta32** [comment]
Hi @vkansal01, we succesfully **reproduced**, **identified** and **solved** the issue.

### Cause
1. We noticed that the Virtual Assistant `appsettings.json` you [attached](https://github.com/microsoft/botframework-solutions/issues/3660#issuecomment-694318489) presents a wrong JSON structure as it's missing a comma between `translatorKey` and `oauthConnections` properties.
1. Also, we identified that the Virtual Assistant `cognitivemodels.json` you [attached](https://github.com/microsoft/botframework-solutions/issues/3660#issuecomment-694316979) doesn't contain the Dispatch model so the tool will fail updating the hosted Virtual Assistant dispatch.

### Solution
1. **Fix** Virtual Assistant's appsettings.json adding a comma between the translatorKey and oauthConnections property (check [appsettings.txt](https://github.com/microsoft/botframework-solutions/files/5268671/appsettings.txt))
1. **Add** a dispatch model to the Virtual Assistant cognitivemodels.json (check [cognitivemodels.txt](https://github.com/microsoft/botframework-solutions/files/5268675/cognitivemodels.txt))

After those changes, execute the botskills connect command and check that the command is correctly executed.

Last but not least, we recommend to use the provided [deploy.ps1](https://github.com/microsoft/botframework-solutions/blob/master/samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Deployment/Scripts/deploy.ps1) to simplify the [deployment process](https://microsoft.github.io/botframework-solutions/virtual-assistant/tutorials/deploy-assistant/cli/1-intro/).

Let us know if this helps to you 😊.

_Wrong JSON structure in the Virtual Assistant appsettings.json_
![image](https://user-images.githubusercontent.com/11904023/94023358-83667480-fd8c-11ea-811a-047d823cccb5.png)

_Missing dispatchModel in the Virtual Assistant cognitivemodels.json_
![image](https://user-images.githubusercontent.com/11904023/94023368-86f9fb80-fd8c-11ea-9baf-d8a308fbede5.png)

_Successful connection after the changes_
![image](https://user-images.githubusercontent.com/11904023/94023415-8e210980-fd8c-11ea-9e96-2ecb176c403f.png)

**Comment by lzc850612** [comment]
@vkansal01 can you please take a look at the above solution to see if it fixes your issue? Thanks.

**Comment by stevengum** [comment]
Closing as @Batta32 provided a fix with the customer's provided information.
