### ISSUE TITLE
Virtual assistant User Greet message is not triggering in webchat iframe

### ISSUE THREAD

**Issue by VidhyaSanjeevi** [microsoft/botframework-solutions#3664]
#### What project is affected?

Virtual Assistant

#### What language is this in?
C#

#### What happens?
Virtual assistant User Greet message is not triggering in webchat iframe.

#### What are the steps to reproduce this issue?
Deploy the basic virtual assistant bot and use iframe as the channel in website, on loading of the iframe welcome message is not triggerred.

#### What were you expecting to happen?

Greet Message should show on user is added.

#### Can you share any logs, error output, etc.?
no message is shown till user types in any message.

**Comment by VidhyaSanjeevi** [comment]
This issue seems to have answer for old version of bot framework: https://github.com/microsoft/botframework-sdk/issues/2098, but for latest version of virtual assistant - i see the implementation already there on MemberAdded method - but still it's not triggering.

**Comment by Batta32** [comment]
Thanks @SSanjeevi for reporting this issue. We came up with some **questions** to understand your environment:
1. What do you mean with `Webchat iframe` channel? Is the [BotFramework-WebChat](https://github.com/Microsoft/BotFramework-WebChat)?
1. Are you using the [C# Virtual Assistant Sample](https://github.com/microsoft/botframework-solutions/tree/master/samples/csharp/assistants/virtual-assistant)?
1. Which version of the BF SDK are you using?
1. Have you deployed the Virtual Assistant using `deploy.ps1`?

We will be reviewing this issue and as soon as we have any update, we will back to you 😊.

**Comment by VidhyaSanjeevi** [comment]
1. In bot channel registration iframe embed in website channel.
2. Yes C# Virtual Assistant.
3. BF. 4.7 i think.. the one which comes with 1.0 of Virtual Assistant
4. yes deployed

**Comment by lzc850612** [comment]
@Batta32 do you have any update for this issue? Thanks.

**Comment by Batta32** [comment]
@lzc850612 - we are going to take this issue this week! As soon as we have any update we will post it here 😊.

**Comment by VictorGrycuk** [comment]
Hi @SSanjeevi, we were able to **reproduce** this issue, however, we found that the behaviour is not related to the bot themselves but to how the webchat channel works.

We found the issue [microsoft/BotFramework-WebChat#2625](https://github.com/microsoft/BotFramework-WebChat/issues/2625), which leads to a [comment](https://github.com/microsoft/BotFramework-WebChat/issues/2120#issuecomment-516056614) by TJ Durnford. TJ explains that most channels send two events when a conversation is started:

1.  Event for the bot
2.  Event for the user: one that triggers the welcome card, however, the webchat channel does not send this even until the user sends a message first

TJ describes that one **workaround** is to send a backchannel event when the direct channel connection is detected, therefore simulating the welcome event. Please check his comment for code snippets and further info.

As discussed with @peterinnesmsft, this is related to the [BotFramework-WebChat](https://github.com/microsoft/BotFramework-WebChat) repository.

**Comment by VidhyaSanjeevi** [comment]
Thanks for the link and suggestion that worked for me.
