### ISSUE TITLE
Error While connecting Skill to VA

### ISSUE THREAD

**Issue by pdesai-icims** [microsoft/botframework-solutions#3669]
Getting Error while added the skill to the VA. Below is the error

π Virtual-Assistant-ibot-test/MyAssistant1/MyAssistant1/MyAssistant1 master ✗ ❯ botskills connect --remoteManifest "https://rg-eu2-va-emailskill-test-xqvnn6q.azurewebsites.net/manifest/manifest-1.1.json" --cs --luisFolder "VA - Emailskill - test/VA---Emailskill---Test/Email_skill/Email_skill/Deployment/Resources/LU/en-us/Email_skill.lu"
Updating Dispatch
Adding skill to Dispatch
There was an error while connecting the Skill to the Assistant:
Error: An error occurred while updating the Dispatch model:
Error: Path to the LUIS folder (VA - Emailskill - test/VA---Emailskill---Test/Email_skill/Email_skill/Deployment/Resources/LU/en-us/Email_skill.lu) leads to a nonexistent folder.
Remember to use the argument '--luisFolder' for your Skill's LUIS folder.

Also, tried different ways but always get the same error : 
π Virtual-Assistant-ibot-test/MyAssistant1/MyAssistant1/MyAssistant1 master ✗ ❯ botskills connect --remoteManifest "https://rg-eu2-va-emailskill-test-xqvnn6q.azurewebsites.net/manifest/manifest-1.1.json" --cs --luisFolder "/Users/pdesai/OneDrive - Icims, Inc/GIT/VA - Emailskill - test/VA---Emailskill---Test/Email_skill/Email_skill/Deployment/Resources/LU/en-us/Email_skill.lu"
Updating Dispatch
Adding skill to Dispatch
There was an error while connecting the Skill to the Assistant:
Error: An error ocurred while updating the Dispatch model:
Error: Path to the LU file (/Users/pdesai/OneDrive - Icims, Inc/GIT/VA - Emailskill - test/VA---Emailskill---Test/Email_skill/Email_skill/Deployment/Resources/LU/en-us/Email_skill.lu/en-us/Email_skill.lu) leads to a nonexistent file.

 π Virtual-Assistant-ibot-test/MyAssistant1/MyAssistant1/MyAssistant1 master ✗ ❯ botskills connect --remoteManifest "https://rg-eu2-va-emailskill-test-xqvnn6q.azurewebsites.net/manifest/manifest-1.1.json" --cs --luisFolder "VA - Emailskill - test/VA---Emailskill---Test/Email_skill/Email_skill/Deployment/Resources/LU"
Updating Dispatch
Adding skill to Dispatch
There was an error while connecting the Skill to the Assistant:
Error: An error ocurred while updating the Dispatch model:
Error: Path to the LUIS folder (VA - Emailskill - test/VA---Emailskill---Test/Email_skill/Email_skill/Deployment/Resources/LU) leads to a nonexistent folder.
Remember to use the argument '--luisFolder' for your Skill's LUIS folder.

**Comment by Batta32** [comment]
Hi @parasdesaicims, thanks for reporting this issue. We will show you the problem of each attempt that you attached, also with the necessary fix so can accomplish the connection of the Virtual Assistant to the Email Skill.

Attempts:
* The problem of the attempts 1 and 2 is that you are using a path to the luis file instead of pointing to the LU folder as `--luisFolder` [requests](https://github.com/microsoft/botframework-solutions/blob/master/tools/botskills/docs/commands/connect.md#options)
* The problem of the attempt 3 is that you are using a wrong path structure to the LU folder

Fix:
* Following the 3 attempt, try to point to the LU folder using an absolute path or a relative

Examples:
Using **absolute** path:
> botskills connect --remoteManifest "https://rg-eu2-va-emailskill-test-xqvnn6q.azurewebsites.net/manifest/manifest-1.1.json" --cs --luisFolder "C:\Users\\<YOUR_USER>\Desktop\VA - Emailskill - test\VA---Emailskill---Test\Email_skill\Email_skill\Deployment\Resources\LU"

Using **relative** path:
> botskills connect --remoteManifest "https://rg-eu2-va-emailskill-test-xqvnn6q.azurewebsites.net/manifest/manifest-1.1.json" --cs --luisFolder "..\VA - Emailskill - test\VA---Emailskill---Test\Email_skill\Email_skill\Deployment\Resources\LU"

Let us know if this helps to you 😊

**Comment by pdesai-icims** [comment]
I think, I tried that already but giving it a try again. Now there is a new error message : 

π Virtual-Assistant-ibot-test/MyAssistant1/MyAssistant1/MyAssistant1 master ✗ ❯ **botskills connect --remoteManifest "https://rg-eu2-va-emailskill-test-xqvnn6q.azurewebsites.net/manifest/manifest-1.1.json" --cs --luisFolder "/Users/pdesai/OneDrive - Icims, Inc/GIT/VA - Emailskill - test/VA---Emailskill---Test/Email_skill/Email_skill/Deployment/Resources/LU"**
Updating Dispatch
Adding skill to Dispatch
Found intent with name '*'. Adding all intents.
Parsing en-us Email_skillLuModel-en LU file
There was an error while connecting the Skill to the Assistant:
Error: An error ocurred while updating the Dispatch model:
Error: There was an error in the bf luis:convert command:
Command: bf luis:convert --in "/Users/pdesai/OneDrive - Icims, Inc/GIT/VA - Emailskill - test/VA---Emailskill---Test/Email_skill/Email_skill/Deployment/Resources/LU/en-us/Email_skill.lu" --culture en-us --out /Users/pdesai/OneDrive - Icims, Inc/GIT/VA - Emailskill - test/VA---Emailskill---Test/Email_skill/Email_skill/Deployment/Resources/LU/en-us/users/pdesai/onedrive - icims, inc/git/va - emailskill - test/va---emailskill---test/email_skill/email_skill/deployment/resources/lu/en-us/email_skill.luis --name Email_skill
Error: Path to /users/pdesai/onedrive - icims, inc/git/va - emailskill - test/va---emailskill---test/email_skill/email_skill/deployment/resources/lu/en-us/email_skill.luis (/Users/pdesai/OneDrive - Icims, Inc/GIT/VA - Emailskill - test/VA---Emailskill---Test/Email_skill/Email_skill/Deployment/Resources/LU/en-us/users/pdesai/onedrive - icims, inc/git/va - emailskill - test/va---emailskill---test/email_skill/email_skill/deployment/resources/lu/en-us/email_skill.luis) leads to a nonexistent file. 

While trying on my Windows VM, get this error : 
PS C:\Users\admpdesai\OneDrive - Icims, Inc\GIT\Virtual-Assistant-iBot-test\Virtual-Assistant-ibot-test\MyAssistant1\MyAssistant1\MyAssistant1> npm install -g botdispatch @microsoft/botframework-cli
npm WARN deprecated @types/moment-timezone@0.5.30: This is a stub types definition. moment-timezone provides its own type definitions, so you do not need this installed.

> yarn@1.22.10 preinstall C:\Users\admpdesai\AppData\Roaming\npm\node_modules\@microsoft\botframework-cli\node_modules\yarn
> :; (node ./preinstall.js > /dev/null 2>&1 || true)

C:\Users\admpdesai\AppData\Roaming\npm\bf -> C:\Users\admpdesai\AppData\Roaming\npm\node_modules\@microsoft\botframework-cli\bin\run
C:\Users\admpdesai\AppData\Roaming\npm\dispatch -> C:\Users\admpdesai\AppData\Roaming\npm\node_modules\botdispatch\bin\dispatch.js

> @microsoft/botframework-cli@4.10.1 postinstall C:\Users\admpdesai\AppData\Roaming\npm\node_modules\@microsoft\botframework-cli
> node scripts/postinstall.js

+ botdispatch@1.7.1
+ @microsoft/botframework-cli@4.10.1
updated 3 packages in 27.864s
PS C:\Users\admpdesai\OneDrive - Icims, Inc\GIT\Virtual-Assistant-iBot-test\Virtual-Assistant-ibot-test\MyAssistant1\MyAssistant1\MyAssistant1> botskills connect --remotemanifest "https://rg-eu2-va-emailskill-test-xqvnn6q.azurewebsites.net/manifest/manifest-1.1.json" --luisFolder "C:\Users\admpdesai\OneDrive - Icims, Inc\GIT\VA - Emailskill - test\VA---Emailskill---Test\Email_skill\Email_skill\Deployment\Resources"
botskills: The term 'botskills' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

**Comment by Batta32** [comment]
Thanks @parasdesaicims for your reply, we will be reviewing your comment and as soon as we have any update, we will back to you 😊.

**Comment by pdesai-icims** [comment]
@Batta32 looking to see if you have any update on this. Thanks,

**Comment by Batta32** [comment]
Hi @parasdesaicims! We will try to reproduce your scenario in our side in order to find the best approach for you, as soon as we have any update for this we will back to you in this issue 😊! 

Last but not least, the issue is related to the path that the `--luisFolder` argument is receiving for the connect command.

**Comment by pdesai-icims** [comment]
Yes, I think that is the issue. Also, tried to replicate the issue on Mac and windows but getting the same error.


-Thanks & Best Regards,
Paras Desai | Infrastructure Engineer | iCIMS
t: .. e: Paras.Desai@icims.com<mailto:Paras.Desai@icims.com>

​ [signature_1235736572] <https://www.icims.com/>

**Comment by Batta32** [comment]
Hi @parasdesaicims, we separated the scenarios in the environments you have tested the `botskills connect`.

### Using possible Linux OS
We came up with some **questions**:
1. What OS are you using?
1. What command line are you using to run botskills?
1. Which version of botskills are you using?

### Using Windows OS
We reviewed the attached error messages and found the following:
1. Execute `npm install -g botskills@latest` to install botskills in your Windows VM as it's not recognized
1. Point to the folder where `EmailSkill.lu` is contained for the `--luisFolder` argument for the botskills connect (unless the `EmailSkill.lu` file is inside the Resources folder)
1. Specify the language of your Virtual Assistant `--cs` (C#) or `--ts` (TypeScript) for the botskills connect


![image](https://user-images.githubusercontent.com/11904023/95256896-d82cd500-07f9-11eb-912e-ab567aab26a2.png)

Let us know if the mentioned for the Windows OS works and we will be attentive to your answer so we can replicate your first environment 😊.

Thanks.

**Comment by pdesai-icims** [comment]
Yes, it did work after redoing everything Though only have to point it to LU folder.

**Comment by pdesai-icims** [comment]
@Batta32  - While redeploying worked, but when I am adding skill to another virtual assistant it is giving below error.
PS C:\Users\pdesai1\OneDrive - Icims, Inc (1)\GIT\MyAssistant5\MyAssistant5\MyAssistant2\MyAssistant2> botskills connect --remoteManifest "https://mycalendarskill2-wgxyceo.azurewebsites.net/manifest/manifest-1.1.json" --cs --luisFolder "C:\Users\pdesai1\OneDrive - Icims, Inc (1)\GIT\AllSkills\calendarskill\Deployment\Resources\LU"
Updating Dispatch
Adding skill to Dispatch
Found intent with name '*'. Adding all intents.
Parsing en-us CalendarLuModel-en LU file
There was an error while connecting the Skill to the Assistant:
Error: An error ocurred while updating the Dispatch model:
Error: There was an error in the bf luis:convert command:
Command: bf luis:convert --in "C:\Users\pdesai1\OneDrive - Icims, Inc (1)\GIT\AllSkills\calendarskill\Deployment\Resources\LU\en-us\Calendar.lu" --culture en-us --out C:\Users\pdesai1\OneDrive - Icims, Inc (1)\GIT\AllSkills\calendarskill\Deployment\Resources\LU\en-us\calendar.luis --name CalendarSkill
Error: The execution of the bf command failed with the following error:
Unexpected arguments: -, Icims,, Inc, (1)\GIT\AllSkills\calendarskill\Deployment\Resources\LU\en-us\calendar.luis
See more help with --help

**Comment by Batta32** [comment]
Thanks @parasdesaicims, we will try to reproduce the issue in our side and let you know any update as soon as possible!

**Comment by Batta32** [comment]
Hi @parasdesaicims, we managed to **reproduced** the issue you mentioned.

We used the following **environment**:
- [botskills@1.0.16](https://www.npmjs.com/package/botskills/v/1.0.16)
- [C# Virtual Assistant Sample](https://github.com/microsoft/botframework-solutions/tree/master/samples/csharp/assistants/virtual-assistant)
- [C# Calendar Skill](https://github.com/microsoft/botframework-skills/tree/master/skills/csharp/calendarskill)

We followed these **steps**:
1. Use the same folder structure as you [attached](https://github.com/microsoft/botframework-solutions/issues/3669#issuecomment-709514340)
1. Deploy the C# Virtual Assistant Sample using the `deploy.ps1` file
1. Deploy the C# Calendar Skill using the `deploy.ps1` file
1. Open a terminal in Virtual Assistant's location
1. Execute the botskills connect command as follows
   > botskills connect --remoteManifest "<LINK_TO_SKILL_MANIFEST>" --cs --luisFolder "<PATH_TO_LU_FOLDER>"
1. Check the connection error

We will continue working on this and we will back to you as soon as we have any update.

![image](https://user-images.githubusercontent.com/11904023/96453976-9a647f00-11f1-11eb-8497-d5538e3fc7b6.png)

**Comment by Batta32** [comment]
@parasdesaicims - we found **2 workarounds** for this issue. The problem is that [botskills@1.0.16](https://www.npmjs.com/package/botskills/v/1.0.16) doesn't wrap the paths that contains whitespace which is solved in the merged PR #3587 and it will be fixed in the **next release** of the botskills tool.

#### Workaround 1 - Use local path without spaces
1. Change the folder structure removing the spaces
    > e.g. C:\Users\pdesai1\OneDrive-Icims,Inc(1)\GIT\MyAssistant5\MyAssistant5\MyAssistant2\MyAssistant2
1. Check that botskills connect works correctly

#### Workaround 2 - Link Botskills CLI Tool using master branch
1. Checkout to the branch [master](https://github.com/microsoft/botframework-solutions)
1. Go to the [botskills](https://github.com/microsoft/botframework-solutions/tree/master/tools/botskills) tool
1. Execute `npm install` to install the depedencies
1. Execute `npm run build` to compile the solution
1. Execute `npm link` to link the tool. If you have installed botskills, you should execute `npm uninstall -g botskills` to uninstall the tool.
1. Check that botskills connect works correctly

Related documentation:
- Issue microsoft/botframework-skills#279
- Issue #3545
- PR #3587

We will be attentive to your answer.

**Comment by chrimc62** [comment]
Closed due to inactivity

**Comment by pdesai-icims** [comment]
Workaround 1 is not working : 
PS /Users/pdesai/OneDrive - Icims, Inc/iBOTs/VirtualAssitant6/VirtualAssistantSample> botskills connect --remoteManifest "https://todoskill-t573s6h.azurewebsites.net/manifest/manifest-1.1.json" --cs --luisFolder "/Users/pdesai/OneDrive - Icims, Inc/iBOTs/MyAssistant6/MyAssistant6/MyAssistant6/Deployment/Resources/LU"
Updating Dispatch
Adding skill to Dispatch
There was an error while connecting the Skill to the Assistant:
Error: An error ocurred while updating the Dispatch model:
Error: Path to the LU file (/Users/pdesai/OneDrive - Icims, Inc/iBOTs/MyAssistant6/MyAssistant6/MyAssistant6/Deployment/Resources/LU/en-us/ToDo.lu) leads to a nonexistent file.
PS /Users/pdesai/OneDrive - Icims, Inc/iBOTs/VirtualAssitant6/VirtualAssistantSample> botskills connect --remoteManifest "https://todoskill-t573s6h.azurewebsites.net/manifest/manifest-1.1.json" --cs --luisFolder "/Users/pdesai/OneDrive-Icims,Inc/iBOTs/MyAssistant6/MyAssistant6/MyAssistant6/Deployment/Resources/LU"
Updating Dispatch
Adding skill to Dispatch
There was an error while connecting the Skill to the Assistant:
Error: An error ocurred while updating the Dispatch model:
Error: Path to the LUIS folder (/Users/pdesai/OneDrive-Icims,Inc/iBOTs/MyAssistant6/MyAssistant6/MyAssistant6/Deployment/Resources/LU) leads to a nonexistent folder.
Remember to use the argument '--luisFolder' for your Skill's LUIS folder.
PS /Users/pdesai/OneDrive - Icims, Inc/iBOTs/VirtualAssitant6/VirtualAssistantSample> botskills connect --remoteManifest "https://todoskill-t573s6h.azurewebsites.net/manifest/manifest-1.1.json" --cs --luisFolder "/Users/pdesai/OneDrive-Icims,Inc/iBOTs/MyAssistant6/MyAssistant6/MyAssistant6/Deployment/Resources/LU"
Updating Dispatch
Adding skill to Dispatch
There was an error while connecting the Skill to the Assistant:
Error: An error ocurred while updating the Dispatch model:
Error: Path to the LUIS folder (/Users/pdesai/OneDrive-Icims,Inc/iBOTs/MyAssistant6/MyAssistant6/MyAssistant6/Deployment/Resources/LU) leads to a nonexistent folder.
Remember to use the argument '--luisFolder' for your Skill's LUIS folder.

will have to try workaround 2.

**Comment by pdesai-icims** [comment]
Here tried Workaround 2, but getting the same error.

On Windows 

**PS C:\Users\pdesai1\OneDrive - Icims, Inc (1)\iBOTs\MyAssistant6\MyAssistant6\MyAssistant6> botskills connect --remoteManifest "https://todoskill-t573s6h.azurewebsites.net/manifest/manifest-1.1.json" --cs --luisFolder "C:\Users\pdesai1\OneDrive - Icims, Inc (1)\iBOTs\TOdoSkill\todoskill\Deployment\Resources\LU"**
Updating Dispatch
Adding skill to Dispatch
Found intent with name '*'. Adding all intents.
Parsing en-us ToDoLuModel-en LU file
There was an error while connecting the Skill to the Assistant:
Error: An error ocurred while updating the Dispatch model:
Error: There was an error in the bf luis:convert command:
Command: bf luis:convert --in "C:\Users\pdesai1\OneDrive - Icims, Inc (1)\iBOTs\TOdoSkill\todoskill\Deployment\Resources\LU\en-us\ToDo.lu" --culture en-us --out C:\Users\pdesai1\OneDrive - Icims, Inc (1)\iBOTs\TOdoSkill\todoskill\Deployment\Resources\LU\en-us\todo.luis --name ToDoSkill
Error: The execution of the bf command failed with the following error:
Unexpected arguments: -, Icims,, Inc, (1)\iBOTs\TOdoSkill\todoskill\Deployment\Resources\LU\en-us\todo.luis
See more help with --help

**PS C:\Users\pdesai1\OneDrive - Icims, Inc (1)\iBOTs\MyAssistant6\MyAssistant6\MyAssistant6> botskills connect --remoteManifest "https://todoskill-t573s6h.azurewebsites.net/manifest/manifest-1.1.json" --cs --luisFolder "C:\Users\pdesai1\OneDrive-Icims,Inc(1)\iBOTs\TOdoSkill\todoskill\Deployment\Resources\LU"**
Updating Dispatch
Adding skill to Dispatch
There was an error while connecting the Skill to the Assistant:
Error: An error ocurred while updating the Dispatch model:
Error: Path to the LUIS folder (C:\Users\pdesai1\OneDrive-Icims,Inc(1)\iBOTs\TOdoSkill\todoskill\Deployment\Resources\LU) leads to a nonexistent folder.
Remember to use the argument '--luisFolder' for your Skill's LUIS folder.
PS C:\Users\pdesai1\OneDrive - Icims, Inc (1)\iBOTs\MyAssistant6\MyAssistant6\MyAssistant6> botskills connect --remoteManifest "https://todoskill-t573s6h.azurewebsites.net/manifest/manifest-1.1.json" --cs --luisFolder "C:\Users\pdesai1\OneDrive-Icims,Inc(1)\iBOTs\TOdoSkill\todoskill\Deployment\Resources\LU\en-us"
Updating Dispatch
Adding skill to Dispatch
There was an error while connecting the Skill to the Assistant:
Error: An error ocurred while updating the Dispatch model:
Error: Path to the LUIS folder (C:\Users\pdesai1\OneDrive-Icims,Inc(1)\iBOTs\TOdoSkill\todoskill\Deployment\Resources\LU\en-us) leads to a nonexistent folder.
Remember to use the argument '--luisFolder' for your Skill's LUIS folder.

On MAC 
**PS /Users/pdesai/OneDrive - Icims, Inc/iBOTs/MyAssistant6/MyAssistant6/MyAssistant6> botskills connect --remoteManifest "https://todoskill-t573s6h.azurewebsites.net/manifest/manifest-1.1.json" --cs --luisFolder "/Users/pdesai/OneDrive - Icims, Inc/iBOTs/TOdoSkill/todoskill/Deployment/Resources/LU"**
Updating Dispatch
Adding skill to Dispatch
Found intent with name '*'. Adding all intents.
Parsing en-us ToDoLuModel-en LU file
There was an error while connecting the Skill to the Assistant:
Error: An error ocurred while updating the Dispatch model:
Error: There was an error in the bf luis:convert command:
Command: bf luis:convert --in "/Users/pdesai/OneDrive - Icims, Inc/iBOTs/TOdoSkill/todoskill/Deployment/Resources/LU/en-us/ToDo.lu" --culture en-us --out /Users/pdesai/OneDrive - Icims, Inc/iBOTs/TOdoSkill/todoskill/Deployment/Resources/LU/en-us/users/pdesai/onedrive - icims, inc/ibots/todoskill/todoskill/deployment/resources/lu/en-us/todo.luis --name ToDoSkill
Error: Path to /users/pdesai/onedrive - icims, inc/ibots/todoskill/todoskill/deployment/resources/lu/en-us/todo.luis (/Users/pdesai/OneDrive - Icims, Inc/iBOTs/TOdoSkill/todoskill/Deployment/Resources/LU/en-us/users/pdesai/onedrive - icims, inc/ibots/todoskill/todoskill/deployment/resources/lu/en-us/todo.luis) leads to a nonexistent file.
**PS /Users/pdesai/OneDrive - Icims, Inc/iBOTs/MyAssistant6/MyAssistant6/MyAssistant6> botskills connect --remoteManifest "https://todoskill-t573s6h.azurewebsites.net/manifest/manifest-1.1.json" --cs --luisFolder "/Users/pdesai/OneDrive-Icims,Inc/iBOTs/TOdoSkill/todoskill/Deployment/Resources/LU"**
Updating Dispatch
Adding skill to Dispatch
There was an error while connecting the Skill to the Assistant:
Error: An error ocurred while updating the Dispatch model:
Error: Path to the LUIS folder (/Users/pdesai/OneDrive-Icims,Inc/iBOTs/TOdoSkill/todoskill/Deployment/Resources/LU) leads to a nonexistent folder.
Remember to use the argument '--luisFolder' for your Skill's LUIS folder.

**Comment by Batta32** [comment]
Thanks @parasdesaicims , can you reopen the issue so our team can review the issue?

We will start to review your comments in order to search the best approach for you 😊.

**Comment by pdesai-icims** [comment]
@Batta32  I do not think I have permissions to reopen this issue or if you mean I should open a new issue and link this one?

**Comment by Batta32** [comment]
Not necessary! We can continue working on this issue as it's the same problem.

@peterinnesmsft - can you or anyone of the team reopen this issue 😊?

**Comment by VictorGrycuk** [comment]
Hi @parasdesaicims, we confirmed that the [workaround 2](https://github.com/microsoft/botframework-solutions/issues/3669#issuecomment-712233415) **works**, so we prepared a step-by-step guide on how to apply it, having a Virtual Assistant and Skill deployed.

> Currently, botskills is compatible **only on Windows**, so these steps won't work on Mac or Linux environments. We plan to release a compatible version in the future that contains the PR #3684.

We reviewed your logs, and we think that workarounds didn't work because the `luisFolder` doesn't contain spaces but the root folder does.

### 1. Install the master version of Botskills
1. Run `npm uninstall -g botskills` to remove your installed botskills
2. Go to [botskills](https://github.com/microsoft/botframework-solutions/tree/master/tools/botskills)' folder using [master](https://github.com/microsoft/botframework-solutions) branch
3. Execute `npm install` to install the dependencies
4. Execute `npm run build` to compile the solution
5. Execute `npm link` to link the tool
6. Run `npm list -g --depth 0` to validate that the local version of botskills has been successfully linked. It should point to the botskills' folder

_Validating the current installed version of Botskills and uninstalling it_
![02](https://user-images.githubusercontent.com/39467613/98289314-bf454a00-1f86-11eb-905a-4ede8ff6d892.gif)

_Installing, building, linking, and validating the master branch version of Botskills_
![03](https://user-images.githubusercontent.com/39467613/98289575-1f3bf080-1f87-11eb-9a94-2e54c3aea719.gif)

### 2. Validating that the workaround 2 solves the issue

1. Run your botskills connect command:
   >  `botskills connect --remoteManifest "https://todoskill-t573s6h.azurewebsites.net/manifest/manifest-1.1.json" --cs --luisFolder "C:\Users\pdesai1\OneDrive - Icims, Inc (1)\iBOTs\TOdoSkill\todoskill\Deployment\Resources\LU"`

1. The Skill is successfully connected to the Virtual Assistant

![04](https://user-images.githubusercontent.com/39467613/98289892-9bcecf00-1f87-11eb-8a1b-883fcba45e1e.gif)

We will be attentive to your comments. 🙂

**Comment by pdesai-icims** [comment]
I was able to add the skill to the bot by moving it to a path without space. Also, in manifest-1.1, changed dispatch models.languages.en-us.id to ToDo. 

Thanks, I am now testing the skills via VA and will keep posted if any issues/errors.

**Comment by Batta32** [comment]
Great @parasdesaicims! If you agree, we can close this issue as you managed to make it work!

If you find any other problem, don't hesitate to open a new issue and we will review it 😊.

**Comment by pdesai-icims** [comment]
Yes, please. Thank you.
