### ISSUE TITLE
[Docs] Broken links and documentation to be updated.

### ISSUE THREAD

**Issue by GitDruid** [microsoft/botframework-solutions#3672]
/overview/virtual-assistant-template/

Many links are broken and also some sentences appear to be referring to old implementation (e.g. "The MainDialog dialog provided in the template derives from a base class called RouterDialog").

**Comment by Batta32** [comment]
Thanks @GitDruid for reporting this issue, we confirmed that [/overview/virtual-assistant-template/](https://microsoft.github.io/botframework-solutions/overview/virtual-assistant-template/) has broken links and is outdated.

We will be reviewing this and as soon as we have any update, we will back to you 😊.

**Comment by Batta32** [comment]
Hi @GitDruid, we created the PR #3680 updating the documentation and fixing the broken links. Feel free to add your feedback!
