### ISSUE TITLE
[C#] Template placeholder not replaced.

### ISSUE THREAD

**Issue by GitDruid** [microsoft/botframework-solutions#3673]
When creating a skill project in C# from "VA and Skills Template", inside the ci-cd file ./Pipeline/[SkillSample].yml, the variable $safeprojectname$ is not replaced with the actual value.

**Comment by Batta32** [comment]
Thanks @GitDruid for reporting this issue. Which version of the VSIX are you using?

We will be reviewing the [Pipeline/SkillSample.yml](https://github.com/microsoft/botframework-solutions/blob/master/templates/csharp/Skill/Skill/Pipeline/SkillSample.yml) in order to reproduce this issue and we will back to you as soon as we have any update 😊.

**Comment by GitDruid** [comment]
Template 4.9.1.2 (see screenshot)

![VAAST](https://user-images.githubusercontent.com/4527837/94922817-21f48300-04bb-11eb-90c9-2d302f7cc98d.png)

**Comment by Batta32** [comment]
Thanks @GitDruid for your quick reply, we will have that in mind to replicate the issue!

**Comment by Batta32** [comment]
Hi @GitDruid, sorry for the delay. We successfully **reproduced** the mentioned issue. We confirmed that the variable `$safeprojectname$` is not replaced with the actual value using [VSIX@4.9.1.2](https://marketplace.visualstudio.com/items?itemName=BotBuilder.VirtualAssistantTemplate).

Repro Steps:
1. Install [VSIX@4.9.1.2](https://marketplace.visualstudio.com/items?itemName=BotBuilder.VirtualAssistantTemplate)
1. Create a new Skill using the installed Virtual Assistant and Skill Templates
1. Check that the `$safeprojectname$` placeholder is not replaced in the `.yml` file

As soon as we have any update, we will back to you 😊.

![image](https://user-images.githubusercontent.com/11904023/95461220-56998c00-094c-11eb-9ef8-02b1f04f3324.png)

**Comment by Batta32** [comment]
@GitDruid - we created the PR #3679 **fixing** the replacement of the `$safeprojectname$` placeholder with the actual value.

To validate the changes of the PR you can follow these steps using the [branch](https://github.com/southworks/botframework-solutions/tree/feature/southworks/fix-template-placeholder-not-replaced)(feature/southworks/fix-template-placeholder-not-replaced):
1. Uninstall your current VSIX version
1. Open the [Template.sln](https://github.com/southworks/botframework-solutions/blob/feature/southworks/fix-template-placeholder-not-replaced/templates/csharp/Templates.sln) in a Visual Studio
1. Build the solution
1. Go to the generated `/templates/csharp/VSIX/bin/debug`
1. Execute the generated `BotTemplatesVSIX.vsix`
1. Create a new Skill using the executed VSIX
1. Check that the `$safeprojectname$` placeholder is replaced in the `.yml` file

Feel free to add your feedback in the Pull Request 😊.

_Before changes made_
![image](https://user-images.githubusercontent.com/11904023/95500752-aa709900-097d-11eb-8536-64b44a7ad369.png)

_After changes made_
![image](https://user-images.githubusercontent.com/11904023/95500752-aa709900-097d-11eb-8536-64b44a7ad369.png)

_Changes made in the SkillProjectTemplate.vstemplate_
![image](https://user-images.githubusercontent.com/11904023/95500743-a775a880-097d-11eb-8fae-1ee56a634b0a.png)
