### ISSUE TITLE
The link to the Automotive Assistant is incorrect [Docs]

### ISSUE THREAD

**Issue by simonthurman** [microsoft/botframework-solutions#3674]
/overview/virtual-assistant-solution/

**Comment by Batta32** [comment]
Thanks @simonthurman, we confirmed that the [/overview/virtual-assistant-solution/](https://microsoft.github.io/botframework-solutions/overview/virtual-assistant-solution/) contains some incorrect links.

We will update the documentation and as soon as we have any update, we will back to you 😊.

**Comment by Batta32** [comment]
Hi @simonthurman, sorry for the delay. We created the PR #3678 which removes the Automotive Assistant bullet from  [/overview/virtual-assistant-solution/](https://microsoft.github.io/botframework-solutions/overview/virtual-assistant-solution/) as it's not present in the [samples](https://github.com/microsoft/botframework-solutions/tree/master/samples/csharp/assistants) folder.

As soon as the Automotive Assistant sample is incorporated in the repository, we will add the bullet with the correct reference.

Feel free to add any feedback in the PR 😊.
