### ISSUE TITLE
Not implemented error thrown from UpdateActivityAsync

### ISSUE THREAD

**Issue by ipraveenMS** [microsoft/botframework-solutions#3676]
#### What project is affected?
Latest Virtual agent and latest skills

#### What language is this in?
c#
#### What happens?
I call UpdateActivityAsync which throws a Not implemented exception
#### What are the steps to reproduce this issue?
1. Copy the sample Virtual agent and sample skills, deploy both to azure and register skills with VA
2. Modify GreentUserAgent in sampledialog.cs in skill to add these 2 lines
 response.Text = "modified " + response.Text;
  await stepContext.Context.UpdateActivityAsync(response);
3. Add below function to skillcontroller.cs in VA (to catch the exception)
public override async Task<IActionResult> UpdateActivityAsync(string conversationId, string activityId, [FromBody] Activity activity)
    {
      try
      {
        return await base.UpdateActivityAsync(conversationId, activityId, activity);
      }
      catch(Exception e)
      {
        throw e;
      }
      return null;
    }
4. Run emulator and invoke sample dialog.
#### What were you expecting to happen?
Success. 
#### Can you share any logs, error output, etc.?
The method or operation is not implemented.
   at Microsoft.Bot.Builder.ChannelServiceHandler.OnUpdateActivityAsync(ClaimsIdentity claimsIdentity, String conversationId, String activityId, Activity activity, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.ChannelServiceHandler.<HandleUpdateActivityAsync>d__8.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Bot.Builder.Integration.AspNet.Core.ChannelServiceController.<UpdateActivityAsync>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at VirtualAssistantSample.Controllers.SkillController.<UpdateActivityAsync>d__1.MoveNext() in C:\sample\virtual-assistant\VirtualAssistantSample\Controllers\SkillController.cs:line 33

**Comment by ipraveenMS** [comment]
BTW, I tested this with bot framework emulator AND with teams and I get same "Not implemented" error

**Comment by ipraveenMS** [comment]
Update:

Tried the below steps to reuse the message Id as well (as per https://stackoverflow.com/questions/55165282/updating-an-activity-in-botframework-v4-on-teams-platform?noredirect=1&lq=1) . The GreetUserAsync is existing function in skill sample modified (which posts a adaptive card to teams) UpdateActivityAsync is a new function added to the waterfall which uses the same activity id as the return value from GreetUserAsync to do the update to the posted adaptive card. This function results in "Not implemented" error and adaptive card is not updated.

private async Task<DialogTurnResult> GreetUserAsync(WaterfallStepContext stepContext, CancellationToken cancellationToken)
    {
          dynamic data = new { Name = stepContext.Result.ToString() };
          Activity response = stepContext.Context.Activity.CreateReply();

          var card = GetCardFromJson("Dialogs/Sample1.json");
         response.Attachments.Add(new Attachment()
          {
            Content = card,
            ContentType = AdaptiveCard.ContentType,
            Name = "Card"
          });

          var response2 = await stepContext.Context.SendActivityAsync(response);
          messageId = response2.Id;

          return await stepContext.NextAsync(cancellationToken: cancellationToken);
        }

    private string messageId = "";

      private async Task<DialogTurnResult> UpdateActivityAsync(WaterfallStepContext stepContext, CancellationToken cancellationToken)
      {
      Activity response = stepContext.Context.Activity.CreateReply();

      var card = GetCardFromJson("Dialogs/Sample2.json");
      response.Attachments.Add(new Attachment()
      {
        Content = card,
        ContentType = AdaptiveCard.ContentType,
        Name = "Card"
      });
      response.Id = messageId;

      await stepContext.Context.UpdateActivityAsync(response);

      return await stepContext.NextAsync(cancellationToken: cancellationToken);
    }

**Comment by jwiley84** [comment]
It means just what it says. `UpdateActivityAsync` isn't implemented where it can be accessed. `return await base.UpdateActivityAsync(conversationId, activityId, activity);`  means it's going to look in SkillDialogBase, but there's no matching method there by that name. If you've added it to a waterfall in GreetUserAsync, it will only be accessible in that waterfall.

**Comment by ipraveenMS** [comment]
@jwiley84 the exception thrown is from VA, not from skills project. The call get routed to the VA and the stack trace from above is from VA project.

**Comment by jwiley84** [comment]
It might just be that it's bubbling up. Let me try a full repro of  your example and see if I  can trigger it.

**Comment by jwiley84** [comment]
I'm still repro'ing this. My apologies for the delay. I should have an answer for you by this afternoon.

**Comment by jwiley84** [comment]
My apologies for the delay, i'm having some issues running my Virtual Assistant.

**Comment by cleemullins** [comment]
This should be resolved in the R11 release of the SDK coming out shortly.

**Comment by ipraveenMS** [comment]
Hi @cleemullins  we are blocked by this issue at the moment for 2 months. What is the timeline for R11 SDK? Can we get a private fix for this till SDK is released?
