### ISSUE TITLE
[Docs] Virtual Assistant Client on Android link not working

### ISSUE THREAD

**Issue by KiranPrism** [microsoft/botframework-solutions#3698]
/clients-and-channels/tutorials/enable-speech/6-next-steps/

**Comment by Batta32** [comment]
Thanks @PaperProjects for reporting this issue, we confirmed what you mentioned for the document [/clients-and-channels/tutorials/enable-speech/6-next-steps/](https://microsoft.github.io/botframework-solutions/clients-and-channels/tutorials/enable-speech/6-next-steps/) and we will fix those links.

We will back to you as soon as we have any update 😊

**Comment by Batta32** [comment]
@PaperProjects - the **correct link** is [/clients-and-channels/clients/virtual-assistant-client/](https://microsoft.github.io/botframework-solutions/clients-and-channels/clients/virtual-assistant-client/).

Also, the document [/clients-and-channels/tutorials/enable-speech/6-next-steps/](https://microsoft.github.io/botframework-solutions/clients-and-channels/tutorials/enable-speech/6-next-steps/) is already **covered** in the issue #3689.

If you agree, we can close this issue so we can track the changes in #3689 😊.

**Comment by KiranPrism** [comment]
Yes. Please close the issue.  Thank you.
