### ISSUE TITLE
Book a Meeting utterance goes to show meetings

### ISSUE THREAD

**Issue by darrenj** [microsoft/botframework-solutions#370]
**Project**
Skills

**Description**
"book a meeting with toby tomorrow at 8pm" appears to trigger the flow to show meetings not book meetings.

**To Reproduce**
![image](https://user-images.githubusercontent.com/33519520/49218131-8928e400-f3c7-11e8-9cd5-06310c74eeb8.png)

**Expected behavior**
Book a meeting flow

**Comment by lauren-mills** [comment]
Closed by #402
