### ISSUE TITLE
[Botskills] support Linux environment

### ISSUE THREAD

**Issue by xieofxie** [microsoft/botframework-solutions#3701]
## User Story
We have some hard coded path logic for windows like https://github.com/microsoft/botframework-solutions/blob/4d23f882776d4a730770e3576f660d629ee92360/tools/botskills/src/functionality/connectSkill.ts#L111 and https://github.com/microsoft/botframework-solutions/blob/4d23f882776d4a730770e3576f660d629ee92360/tools/botskills/src/utils/sanitizationUtils.ts#L8

(could be more)
Should we review these cases and make sure botskills runs correctly in linux environment?

## Acceptance Criteria 
*List your requirements.*
- [ ] ...
- [ ] ...
- [ ] ...

## Resources
*Provide any screenshots or conversation mockups to support your request.*
*Learn how to mock up bot conversations with [.chat files](http://aka.ms/bfchatfile).*

## Notes
*Provide any additional information.*

**Comment by Batta32** [comment]
Hi @xieofxie ! We already have the PR #3684 which fixes botskills cli tool compatiblity with Unix and fixes the unit tests.

To test it you can follow these steps using [feature/southworks/fix-botskills-linux-tests](https://github.com/southworks/botframework-solutions/tree/feature/southworks/fix-botskills-linux-tests) branch:
1. Go to [botskills](https://github.com/southworks/botframework-solutions/tree/feature/southworks/fix-botskills-linux-tests/tools/botskills) folder
1. Execute `npm install` to install the dependencies
1. Execute `npm run build` to compile the solution
1. Execute `npm run test` to check that the tests are correctly passing
1. Execute `npm link` to link the local tool. If you already have a previous botskills package installed, you should uninstall it with `npm uninstall -g botskills`
1. Use the tool in UNIX/Windows OS

We linked this issue to that PR so this issue can be closed automatically.

We will be attentive to your reply 😊.

**Comment by xieofxie** [comment]
Thanks! I didn't notice next branch. Look forward to the release of next branch!
