### ISSUE TITLE
Answering NO on skill switch prompt fails to restart skill

### ISSUE THREAD

**Issue by Bots4life** [microsoft/botframework-solutions#3703]
#### What project is affected?
Virtual Assistant and Skills

#### What language is this in?
Typescript

#### What happens?
When skill switch prompt is triggered and the user answers "No" it fails to invoke the skill.

#### What are the steps to reproduce this issue?
Go into a skill from the VA, type interrupt to switch to another skill and enter no to the skill switch prompt. 

#### What were you expecting to happen?
The current skill to restart. 

#### Can you share any logs, error output, etc.?
The error is: Error: Error invoking the skill id: "myfavoriteskill" at "https://******.azurewebsites.net/api/messages" (status is 500). ReferenceError: err is not defined at SkillDialog. (D:\home\site\wwwroot\nodemodules\botbuilder-dialogs\lib\skillDialog.js:160:23) at Generator.next () at fulfilled (D:\home\site\wwwroot\nodemodules\botbuilder-dialogs\lib\skillDialog.js:11:58) at process.tickCallback (internal/process/nexttick.js:68:7)

#### Any screenshots or additional context?
No

**Comment by Batta32** [comment]
Thanks @Bots4life for reporting this issue! Are you using the TypeScript [samples](https://github.com/microsoft/botframework-solutions/tree/master/templates/typescript/samples/sample-assistant) or creating the bots using [generator-bot-virtualassistant@1.0.1](https://www.npmjs.com/package/generator-bot-virtualassistant/v/1.0.1)?

As soon as we have any update, we will back to you here 😊.

**Comment by Bots4life** [comment]
Thanks for the reply @Batta32
We are using the TypeScript samples

**Comment by Bots4life** [comment]
Adding in a screenshot for context
![Screenshot 2020-11-06 144655](https://user-images.githubusercontent.com/70543658/98413955-2a068c00-2040-11eb-8807-e5d4b328bd12.png)

**Comment by mrivera-ms** [comment]
@Batta32 could you please take a look at the customer's answer? Thank you.

**Comment by VictorGrycuk** [comment]
Hi @Bots4life & @mrivera-ms, sorry for the delay. We replicated the scenario but the error was not reproduced.

To help us understand and reproduce the issue, we have some **questions**:

1. Have you tried to test the Skill running on its own?
2. Which files have you modified when customizing the sample skill? How?
3. What version of BotBuilder SDK are you using in the VA & Skill? You can check this on your [package-lock.json](https://github.com/microsoft/botframework-solutions/blob/master/templates/typescript/samples/sample-assistant/package-lock.json)
4. Is the method [repromptDialog](https://github.com/microsoft/botbuilder-js/blob/main/libraries/botbuilder-dialogs/src/skillDialog.ts#L169-L181) of your skill called? This method is executed after the switchSkillDialog prompt
5. Does this issue also happens on the [BotFramework Emulator](https://github.com/microsoft/BotFramework-Emulator)?

Our environment:

- [Virtual Assistant Sample](https://github.com/microsoft/botframework-solutions/tree/master/templates/typescript/samples/sample-assistant)
- [Sample Skill](https://github.com/microsoft/botframework-solutions/tree/master/templates/typescript/samples/sample-skill) x2
- MS Teams
- [BotFramework Emulator](https://github.com/microsoft/BotFramework-Emulator)

To test the scenario we followed these steps:

1. Connect both Skills to the Virtual Assistant
2. Add the Virtual Assistant to MS Teams
3. Call the first Skill
4. Call the second Skill in the middle of the conversation of the first Skill
5. Send "no" when asked to switch Skill
6. The first Skill dialog was reprompt as normal

We tested the scenario both in MS Teams and in BotFramework Emulator, in both cases we had the same result.

We will be attentive to your comments 🙂.

![image](https://user-images.githubusercontent.com/39467613/98727724-25f7a880-2377-11eb-958c-7b764020b618.png)

**Comment by Bots4life** [comment]
@Batta32 @VictorGrycuk @mrivera-ms 
Thank you for the help and quick responses everyone, we found the issue was with a modification we made to the defaultActivityHandler. Inside of onEndOfConversationActivity() we added a sendEoCToParent() to help with an issue we were having with another customization. Removing this line allows the skill to be restarted properly. 

Thanks again!
