### ISSUE TITLE
[C# & TypeScript] Update BF SDK versions to 4.11.0 

### ISSUE THREAD

**Issue by matiasroldan6** [microsoft/botframework-solutions#3706]
## User Story

As BF SDK 4.11 versions were published for [JavaScript](https://github.com/microsoft/botbuilder-js/releases/tag/4.11.0) and [C#](https://github.com/microsoft/botbuilder-dotnet/releases/tag/4.11.0)
 I want to have the C# and TypeScript solutions updated
 so that the C# and TypeScript solutions uses the latest SDK version published

## Acceptance Criteria

*List your requirements.*

- [x] Update the `.csproj` files of the C# solutions to use BF SDK version 4.11.0
- [x] Update the `package.json` and `package-lock.json` files of the TypeScript solutions to use BF SDK version 4.11.0
- [x] Replicate changes to the templates
- [x] Validate the changes

## Resources

*Provide any screenshots or conversation mockups to support your request.*
 *Learn how to mock up bot conversations with [.chat files](http://aka.ms/bfchatfile).*

- [C# Release](https://github.com/microsoft/botbuilder-dotnet/releases/tag/4.11.0)
- [JS Release](https://github.com/microsoft/botbuilder-js/releases/tag/4.11.0)

## Notes

**Comment by axelsrz** [comment]
@lauren-mills Could you take a look at this please?

**Comment by lauren-mills** [comment]
@peterinnesmsft, @Batta32 - I think I saw that this work is already underway or planned. Please add a comment if there's an update.

**Comment by Batta32** [comment]
Hi @lauren-mills, we created the PR #3707 which contains the updates of the SDK version to 4.11 so this is already done and solved as soon as the PR is merged 😊.

**Comment by Batta32** [comment]
This issue is solved with PR #3707
