### ISSUE TITLE
Chitchat.qna: Inconsistent character "’" vs "'"

### ISSUE THREAD

**Issue by dawwa** [microsoft/botframework-solutions#3711]
This is causing an encoding issue in our automation script.
Please bulk correct it in the official asset, thanks.

The issue exists in the generated assets across all locales, here is an example for en-us.

![image](https://user-images.githubusercontent.com/44714043/99719390-16581e00-2a61-11eb-8fc6-272bd9db179f.png)

**Comment by Batta32** [comment]
Thanks @dawwa for reporting this issue, we confirmed what you mentioned in the cognitive models files so we will be reviewing this in order to have consistency between all the files.

As soon as we have any update, we will back to you here 😊.

**Comment by Batta32** [comment]
Hi @dawwa, we created the PR #3724 that replaces the `’` to `'` in `.qna` and `.lu` files.
Feel free to add your feedback in the PR!

**Comment by Batta32** [comment]
This issue is solved with the PR #3724.
