### ISSUE TITLE
Teams Command Lists not working on phone

### ISSUE THREAD

**Issue by amoyalan20** [microsoft/botframework-solutions#3715]
As i implemented teams command list ,but its only working in the desktop view not in mobile.
![image](https://user-images.githubusercontent.com/73281779/99822664-84900400-2b79-11eb-85f0-8696674b8dee.png)
The desktop view is attached in screenshot. Could you please provide the changes to be updated for working in mobile view?

**Comment by Batta32** [comment]
Hi @amoyalan20, thanks for reporting this issue. Can you add a detailed information of your **Environment**, **Repro Steps** and **Expected Behavior**?

As soon as we have your reply, we will start working on this issue and let you know any update that we have for you 😊.

**Comment by amoyalan20** [comment]
In teams Manifest we have added command list, its working as expected in desktop. but while checking teams in phone those command list are not working.

"commandLists": [
        {
          "scopes": [
            "team",
            "groupchat"
          ],
          "commands": [
            {
              "title": "Command 1",
              "description": "Description of Command 1"
            }
          ]
        },
        {
          "scopes": [
            "personal",
            "groupchat"
          ],
          "commands": [
            {
              "title": "Personal command 1",
              "description": "Description of Personal command 1"
            }
          ]
        }
      ]

**Comment by Batta32** [comment]
Thanks @amoyalan20 for the information, we will start reviewing this issue and we will let you know any update 😊.

**Comment by Batta32** [comment]
Hi @amoyalan20, sorry for the delay. We successfully **reproduced** the mentioned issue using Teams Command List in Mobile. Also, we confirmed that in Desktop is working.

We used the following **environment**:
- Android version: 10
- Teams mobile app version: 1416/1.0.0.2020111001

As soon as we have any update, we will back to you here 😊.

_Teams Command List is not working in Mobile_
![image](https://user-images.githubusercontent.com/11904023/100622496-ad459580-32ff-11eb-91d4-a3319fc50db7.png)

_Teams Command List working in Desktop_
![image](https://user-images.githubusercontent.com/11904023/100622510-b0408600-32ff-11eb-9552-3ce0b226cbd4.png)

**Comment by clearab** [comment]
Hello - as is [documented here](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/create-a-bot-commands-menu?tabs=dotnet) command lists do not appear on mobile clients. My apologies for the confusion.

As far as I'm aware, the Teams team doesn't have any plans to implement support for them on mobile.
