### ISSUE TITLE
Delete email utterance reports as being not supported

### ISSUE THREAD

**Issue by darrenj** [microsoft/botframework-solutions#372]
**Project**
Skills

**Description**
Asking to delete an email results in a message that the email skill doesn't support this. The skill does but only part of the show email flow. 

**To Reproduce**
ask "delete email"

**Expected behavior**
Work with Quirine/Rachel on a conversational flow for this. Perhaps we follow something like this:
- Sure, I can help you tidy up your email. Let's start with finding the email(s) you want to delete
- Do you want to show email first or if you already know let me know the subject or sender name.

**Additional context**
- Not entirely sure on how valid this scenario is - how often will people ask to delete email so it might be something we just direct the user to find email and delete from there?

**Comment by DingmaomaoBJTU** [comment]
Fixed by https://github.com/Microsoft/AI/pull/348.
