### ISSUE TITLE
BotTelemetry not storing any details in Application Insights

### ISSUE THREAD

**Issue by UtkarshSinghal17** [microsoft/botframework-solutions#3725]
#### What project is affected?
Virtual Assistant Template
#### What language is this in?
C#
#### What happens?
I have added telemetry to my bot and I am using the power BI template given by Microsoft but In data, everything is showing as null. and for directline, facebook channel nothing is storing.
I have enabled telemetry using the below line of code in the startup file.

            services.AddApplicationInsightsTelemetry();
           services.AddSingleton<IBotTelemetryClient, BotTelemetryClient>();
            services.AddSingleton<ITelemetryInitializer, OperationCorrelationTelemetryInitializer>();
            services.AddSingleton<ITelemetryInitializer, TelemetryBotIdInitializer>();
            services.AddSingleton<TelemetryInitializerMiddleware>();
            services.AddSingleton<TelemetryLoggerMiddleware>(s => new TelemetryLoggerMiddleware(s.GetService<IBotTelemetryClient>(), true));

I am using the power bi template given by the Microsoft from below link.
https://microsoft.github.io/botframework-solutions/solution-accelerators/tutorials/view-analytics/3-open-template/

#### What are the steps to reproduce this issue?
Create a new project using the Virtual Assistant template and enable directline channel.
Do some conversations through chatbot using directline/webchat.
Create a power bi report using a power bi template.

#### What were you expecting to happen?
Telemetry should store every field value so it will help to create the dashboard.

#### Any screenshots or additional context?
![image](https://user-images.githubusercontent.com/44197601/100247151-06a87000-2f60-11eb-9b81-ab1139d2ae26.png)
![image](https://user-images.githubusercontent.com/44197601/100247220-1e7ff400-2f60-11eb-96e5-ee6a43de54f0.png)

**Comment by Batta32** [comment]
Hi @UtkarshSinghal17, thanks for reporting this issue.

We will be reviewing the problem and we will let you know any update in this thread 😊.

**Comment by UtkarshSinghal17** [comment]
@Batta32 Please find additional information.
I am using Microsoft.Bot.Solution 1.0.1 version.

**Comment by dawwa** [comment]
@UtkarshSinghal17 ,
Not necessarily the root cause of your issue, but one thing that might be worthy to check is the version of the Microsoft.ApplicationInsights.* series nuget packages, try 2.12.0 if this is not what you have and see if that works, as I recently observed the Telemetry is not flowing with any higher version.

**Comment by UtkarshSinghal17** [comment]
@dawwa I already have the same version.

**Comment by tonyanziano** [comment]
@peterinnesmsft / @Batta32 please provide an update if possible.

**Comment by Batta32** [comment]
Hi @tonyanziano, we are currently working on this issue trying to reproduce the problem. As soon as we have any update, we will back here with the new information 😊.

**Comment by Batta32** [comment]
Hi @UtkarshSinghal17, we **were not able** to reproduce the issue.

We came up with some **questions**:
1. What version of Power BI are you using? We recommend to use the latest version [2.87.1061.0 32-bit (November 2020)](https://www.microsoft.com/en-us/download/details.aspx?id=58494)
1. Are you using the `application-insights id` as this [document](https://microsoft.github.io/botframework-solutions/solution-accelerators/tutorials/view-analytics/2-get-application-insights-application-id/) describes?

Our environment:
- C# Virtual Assistant
- Direct Line Channel Enabled
- Power BI Desktop version 2.87.1061.0 32-bit (November 2020)
- [Direct Line Sample](https://github.com/microsoft/botframework-solutions/tree/master/samples/csharp/clients/directline.web)

We followed these steps:
1. Apply code lines you [provided](https://github.com/microsoft/botframework-solutions/issues/3725#issue-750912754)
1. Deploy the bot using `deploy.ps1` script
1. Enable Direct Line Channel in the bot
1. Open the Power BI report
1. Provide the application-insights id
1. Talk with the bot in the Direct Line Channel
1. Refresh the Power BI report
1. See the results in the Power BI report

Furthermore, we followed these documents as guide:
- [Intro: View analytics with Power BI](https://microsoft.github.io/botframework-solutions/solution-accelerators/tutorials/view-analytics/1-intro/)
- [Get your Application Insights Application ID](https://microsoft.github.io/botframework-solutions/solution-accelerators/tutorials/view-analytics/2-get-application-insights-application-id/)
- [Open the Power BI template](https://microsoft.github.io/botframework-solutions/solution-accelerators/tutorials/view-analytics/3-open-template/)

We will be attentive to your answer 🙂.

_Telemetry showing in Power BI report_
![image](https://user-images.githubusercontent.com/11904023/100888407-d77c8c00-3494-11eb-8e77-2f69afd08e2d.png)

**Comment by UtkarshSinghal17** [comment]
Hello @Batta32 Please find screenshots for my power bi version and also I have used application-insight same as described in the document. 

![image008](https://user-images.githubusercontent.com/44197601/100899597-0839e100-34e8-11eb-94f5-6ca34b4e0f3f.jpg)
![image009](https://user-images.githubusercontent.com/44197601/100899613-0a9c3b00-34e8-11eb-9907-8a81368b91fd.jpg)
![Power BI version](https://user-images.githubusercontent.com/44197601/100899847-420ae780-34e8-11eb-831e-289d54fe2528.jpg)

**Comment by Batta32** [comment]
Hi @UtkarshSinghal17, we successfully **reproduced** the issue filtering the `ConversationId` column by the blank value as you appear to have filtered [here](https://github.com/microsoft/botframework-solutions/issues/3727#issuecomment-734336099).

Can you verify if you have any **active filter** in your query? We have attached the [query.txt](https://github.com/microsoft/botframework-solutions/files/5631821/query.txt)
that you can use in your Power BI which is the one of the template.

Finally, we noticed that you correctly **received** data in your report as you have _11 Users and 197 Messages_ [here](https://user-images.githubusercontent.com/44197601/100247151-06a87000-2f60-11eb-9b81-ab1139d2ae26.png).

We will be attentive to your answer 🙂.

_Issue reproduced_
![image](https://user-images.githubusercontent.com/11904023/100926667-90a58b00-34c2-11eb-95b3-b5a5d2a32437.png)

_Before/After of the query with the applied filter_
![image](https://user-images.githubusercontent.com/11904023/100926472-458b7800-34c2-11eb-80a2-a12086a11421.png)

**Comment by UtkarshSinghal17** [comment]
I have deployed chatbot to different app service and pointing to different application Insights Now I am able to retrieve all data except Hero Card, Adaptive Card text. Is it any way I can get text/title/button values in the power bi report?

**Comment by Batta32** [comment]
Great @UtkarshSinghal17 ! We will be reviewing the scenario of populating the values of a card in the Power BI report and as soon as we have any update, we will back to you here 😊.

**Comment by Batta32** [comment]
Hi @UtkarshSinghal17, there is a **way** to do what you need and we found the same issue described in #3447 (check [comment](https://github.com/microsoft/botframework-solutions/issues/3447#issuecomment-649634587)). However, it's not ideal and hopefully you can adapt it to better suit your needs.

Follow these **steps**:
1. In the Power BI report, click on `Transform Data` from the Home tab
1. Click on `EventTelemetry`, and then click on `Advanced Editor`
1. Add this line to the query, and click Done
    ```
    Card_Text = (parse_json(tostring(parse_json(customDimensions.attachments))))[0].content['text']
    ```
    ![image](https://user-images.githubusercontent.com/11904023/102130020-0993d380-3e2f-11eb-9c94-54f60adc7a4c.png)

1. Now go to the `Interactions` table, and change line 7:
   ```
   #"Added BotMessageText Column" = Table.AddColumn(#"Added OperationID Column", "BotResponseText", each if [EventName] = "BotMessageSend" then (if [Card_Text]<>null then [Card_Text] else [Title]) else null)
    ```
    ![image](https://user-images.githubusercontent.com/11904023/102129931-e701ba80-3e2e-11eb-96b2-2884f2fa6211.png)

1. Click Done. A new column Card_Text should appears as follows:
    ![image](https://user-images.githubusercontent.com/11904023/102129915-e10bd980-3e2e-11eb-8d3c-c5c842fb137e.png)

Let us know if this helps you 😊

**Comment by UtkarshSinghal17** [comment]
Thanks @Batta32 .

It is really helpful. I am able to get all the data that I required.
