### ISSUE TITLE
[Docs]

### ISSUE THREAD

**Issue by wang-piaoliang** [microsoft/botframework-solutions#3728]
/solution-accelerators/tutorials/view-analytics/1-intro/

Unable to load pbi due to data issue, thanks.

![image](https://user-images.githubusercontent.com/52517818/100575399-f6551400-3316-11eb-9e3a-7eb0eabe2754.png)

**Comment by Batta32** [comment]
Hi @wang-piaoliang, thanks for reporting this issue. We came up with some questions for you in order to start working on this issue:
1. Can you attach the information of the `Copy Details` present in that dialog?
1. Which version of PowerBI have you installed?

**Comment by VictorGrycuk** [comment]
Hi @wang-piaoliang, we were **not** able to reproduce the error you are having. We tested and confirmed the correct functionality of the template using with the following versions:

- **Microsoft Store:** Version: 2.87.1061.0 64-bit (November 2020)
- **MSI Installer:** Version: 2.87.1061.0 64-bit (November 2020)
- **MSI Installer:** Version: 2.87.1061.0 32-bit (November 2020)



We **suggest** you to update your Power BI to the latest version, and see if the issue persists.



We will be attentive to your comments and the answer of the [mentioned](https://github.com/microsoft/botframework-solutions/issues/3728#issuecomment-735758856) questions 🙂.
