### ISSUE TITLE
In Facebook channel, Hero card button title is truncated

### ISSUE THREAD

**Issue by UtkarshSinghal17** [microsoft/botframework-solutions#3737]
#### What language is this in?
C# .Net
#### What happens?
I have used hero card to show some message so that user can click on it but In Facebook Channel, hero card button text is truncated 
#### What are the steps to reproduce this issue?
Create a hero card with 3 buttons. Enable facebook channel.

#### What were you expecting to happen?
Hero card button title should show the full text.
#### Any screenshots or additional context?
![image](https://user-images.githubusercontent.com/44197601/101882787-591e9900-3bbc-11eb-97cb-050825842081.png)

**Comment by tonyanziano** [comment]
@Batta32 can you please comment on this?

**Comment by Batta32** [comment]
Sure @tonyanziano!

Thanks for reporting the issue @UtkarshSinghal17 and for the provided information. We will start working on this issue and as soon as we have any update for you we will back here 😊.

**Comment by UtkarshSinghal17** [comment]
Hello @Batta32  Do you have any update on this.

**Comment by Batta32** [comment]
Hi @UtkarshSinghal17, we are currently reviewing this issue so you will have an update this week 😊.

**Comment by matiasroldan6** [comment]
Hi @UtkarshSinghal17, we could reproduce this issue following the steps you detailed.

We will be working on finding what's causing this, and a possible solution.

![image](https://user-images.githubusercontent.com/20074735/102264765-d6b41300-3ef4-11eb-9d6d-5692b4180afb.png)

**Comment by matiasroldan6** [comment]
Hi @UtkarshSinghal17, we found that this is not related to the bot, and in fact it's most likely a **Facebook limitation** as they control how a card is rendered on the messenger platform.

As far as we researched, there is **no workaround** for this, other than maybe, setting the options in plain text for the user to choose, or cutting down the text in the buttons.

We found some related issues that you can read:
- microsoft/botframework-sdk#3958
- microsoft/botframework-sdk#1431
- microsoft/botframework-sdk#4803
- [Facebook buttons best practices about text length](https://developers.facebook.com/docs/messenger-platform/send-messages/buttons#best_practices)

Finally, we validated the suggestion of this [comment](https://github.com/microsoft/botframework-sdk/issues/3958#issuecomment-353195263) to use adaptive cards, still without success.

_Test using adaptive cards_
![image](https://user-images.githubusercontent.com/20074735/102535623-393d1880-4087-11eb-8d77-a812009e8a8b.png)
