### ISSUE TITLE
[Docs] Describe how to get the value for serviceNowNamespaceId

### ISSUE THREAD

**Issue by sachabruttin** [microsoft/botframework-solutions#3738]
The IT Service Managment (ITSM) Skill documentation page provide information about how to configure the skill, but it lacks information on how to retrieve the value `serviceNowNamespaceId` on the `appsetting.json` file. 

https://microsoft.github.io/botframework-solutions/skills/samples/itsm/

**Comment by lauren-mills** [comment]
Hi, this screenshot shows where to find the namespace Id in the New Scripted REST API form:
![image](https://user-images.githubusercontent.com/27976702/101953859-fcb57c80-3baf-11eb-93d6-2aa974322978.png)

I'll make an update to the docs to show this.
