### ISSUE TITLE
Proactive Notification in Teams

### ISSUE THREAD

**Issue by amoyalan20** [microsoft/botframework-solutions#3746]
Here are our queries on proactive notification in Teams bot. Kindly suggest some recommendations/known limitations. 

•	Is it possible to trigger automated proactive notification to only few people – not all people with bot – How to alert only selected people samples?
•	Can we do the proactive push using a WebJob / Logic app? what's the Best recommendation?
•	Any limitations or known issues with proactive notification

**Comment by EricDahlvang** [comment]
Hi @amoyalan20 

Some information regarding Teams rate limits can be found here:
https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/rate-limit

- Yes, it is possible to alert only select people.  This sample demonstrates sending a message to every member of a conversation: https://github.com/microsoft/BotBuilder-Samples/blob/main/samples/csharp_dotnetcore/57.teams-conversation-bot/Bots/TeamsConversationBot.cs But, the members list could come from a database or other source of previously stored or filtered members.

- Yes, webjob or Logic app will work for proactive messaging.  This doc demonstrates using an Azure Function: https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-long-operations-guidance

- Limitations, please see Teams rate limiting documentation: https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/rate-limit

**Comment by amoyalan20** [comment]
@EricDahlvang Thanks for your valuable information, it was much helpful. Have an additional queries on the same :

- We have a specific set of people to be notified with proactive message because of their due in submitting a feature. 
Do you have any link for this requirement other than the generic reference link that you shared previously?

**Comment by EricDahlvang** [comment]
@amoyalan20 _a specific set of people ... due in submitting a feature_ is business logic very specific to your application, and how this is accomplished would depend on other application requirements.  Where are you planning to store the ConversationReferences (using what data store)?  While they are retrieved, the query to the store should contain a filter, finding only those specific set of people due in submitting a feature. 

This example bot uses CosmosDb to store conversation references:
https://github.com/EricDahlvang/TimeoutConversation/blob/master/TimeoutConversationBot/TimeoutConversationService.cs

Then, this Azure Function queries the CosmosDb container and filters based on the LastAccessed field:
https://github.com/EricDahlvang/TimeoutConversation/blob/master/ClearStateTrigger/run.csx#L74

Hope this helps. 👍

**Comment by amoyalan20** [comment]
@EricDahlvang Thanks for your information. Is there any feasibility of sending  proactive message to specific  user without storing conversation details to table storage/CosmosDb?
