### ISSUE TITLE
Proactive Notification in Teams

### ISSUE THREAD

**Issue by amoyalan20** [microsoft/botframework-solutions#3749]
We have a specific set of people to be notified with proactive message because of their due in submitting a feature.
Do you have any link for this requirement other than the generic reference link( https://github.com/microsoft/BotBuilder-Samples/blob/main/samples/csharp_dotnetcore/57.teams-conversation-bot/Bots/TeamsConversationBot.cs )?

**Comment by anusharr** [comment]
@amoyalan20, just to clarify, you want to send a proactive message to each user in the team(specific set of people) or send a proactive message to the team channel?

**Comment by amoyalan20** [comment]
@anusharavindrar we are looking for a proactive message for a specific set of people.

**Comment by anusharr** [comment]
@amoyalan20, as of now we only have the official documentation https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/send-proactive-messages?tabs=dotnet which explains in detail about how to send proactive messages to users, but it follows the same sample 57. teams-conversation-bot. Your use case is very specific.

Closing this issue as I see an ongoing conversation in 3746
