### ISSUE TITLE
QnA Maker without Azure Search

### ISSUE THREAD

**Issue by NobinJoseRad** [microsoft/botframework-solutions#375]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Is it possible to provision the QnA Maker without Azure Search for Enterprise Template? 

**Describe alternatives you've considered**

**Additional context**

**Comment by lauren-mills** [comment]
Hi @NobinJoseRad, as of today Azure Search is a requirement for using QnA Maker since it is the backend which surfaces the answers. https://docs.microsoft.com/en-us/azure/cognitive-services/qnamaker/overview/overview
