### ISSUE TITLE
Oauth Connection - The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.

### ISSUE THREAD

**Issue by michaeljdresser** [microsoft/botframework-solutions#3750]
## Version
Not applicable

## Describe the bug
After signing into the 3rd party provider (OAuth2 Generic Provider) the following message is displayed in the sign in page and the authentication process fails. 
"The resource you are looking for has been removed, had its name changed, or is temporarily unavailable."

## To Reproduce
Created an application using the Bot Framework Solutions Skill template.
Define an "OAuth 2 Generic Provider" in the "Web App Bot" using a third party provider.
Uncomment the following lines in the WaterFallStep:

                // NOTE: Uncomment these lines to include authentication steps to this dialog
                GetAuthTokenAsync,
                AfterGetAuthTokenAsync,

**Note:**
To replicate the issue the "Redirect with the authorisation code  query string" returned by the 3rd party OAuth provider has to be greater than 2048 in length.

Connect to the Bot, and Sign into the 3rd party provider. After signing in successfully the error "The resource you are looking for has been removed, had its name changed, or is temporarily unavailable." is displayed.

## Expected behavior
The sign in page should disappear and the authentication should compete irrespective of the length of the "Redirect with the authorisation code  query string".

## Screenshots
![image](https://user-images.githubusercontent.com/28652742/103663826-74858580-4f69-11eb-9f8f-93fbd1c74174.png)

## Additional context
We believe that the problem is caused by the "Redirect with the authorisation code  query string" being greater than 2048. With this particular provider the authorisation code was 4230 characters in length. Hence we believe the problem lies in the handling of the "https://token.botframework.com/.auth/web/redirect" Url.

I think the following was a similar issue for Functions:
https://github.com/Azure/azure-functions-host/issues/3023

**Comment by stevkan** [comment]
@michaeljdresser, thank you for your patience while I researched this. I believe this to be a Service issue (vs SDK) and have reached out to a colleague on that team. Once I have some guidance and a possible next step I will post an update.

**Comment by Jeffders** [comment]
Hello. Currently the maximum allowable lengths are closer to 2048 characters. 

What we've recommended to others in cases where an identity provider is doing something more unique or outside the boundaries of what we support is for you to create an "OAuth Proxy" (with the token and authorize methods). Then, you'd point your Bot Service OAuth Connection setting at this proxy, and inside the implementations of your token and authorize methods, you handle the intricacies of the particular identity provider you are implementing.   

The proxy can be very simple and has a signature like this:

```
[HttpGet("authorize")]
public ActionResult<string> Authorize(string response_type, string client_id, string state, string redirect_uri)
{
    // don't actually do only this...you should call the identity provider with the passed parameters            
    return this.Redirect($"{redirect_uri}?code={Guid.NewGuid().ToString("D")}&state={state}");
}

[HttpPost("token")]
public async Task<ActionResult> Token()
{
    // look in the body for the token
}
```
