### ISSUE TITLE
[Docs] Power BI Report is not working for Adaptive Dialogs

### ISSUE THREAD

**Issue by cxbuilders** [microsoft/botframework-solutions#3756]
/solution-accelerators/tutorials/view-analytics/1-intro/

Checked the report and it is build for Waterfall dialogs not for adaptive dialogs. Another report for adaptive would be great

**Comment by a-b-r-o-w-n** [comment]
@garypretty have you had a chance to look into this yet?

**Comment by garypretty** [comment]
Thanks @cxbuilders.  Right now we have no plans in the short term to update the Power BI dashboard.  However, we do have analytics as a broader point on our roadmap and will likely see progress here later this year.  This may include updates to the Power BI dashboard, but we are going to look at analytics all up and decide on an appropriate approach.

I'm going to close this issue as we are tracking this elsewhere.

**Comment by cxbuilders** [comment]
@garypretty Could you maybe specify 'elsewhere'? Than we can track along

**Comment by garypretty** [comment]
@cxbuilders Not at this time - we have a broad planning item on our backlog / roadmap to enable analytics in some form, but the exact details of this are not in a place where you would be able to track them, as we have not yet agreed the specifics of what will be delivered. All I can suggest for now would be to keep an eye on our announcements / releases.
