### ISSUE TITLE
[Docs]

### ISSUE THREAD

**Issue by rslavey** [microsoft/botframework-solutions#3761]
/skills/tutorials/create-skill/csharp/5-update-manifest/

this command:

    .\Deployment\Scripts\publish.ps1 -botWebAppName {YOUR_SKILL_BOTWEBAPP_NAME} -resourceGroup {YOUR_RESOURCEGROUP_NAME}

is incorrect. The script is expecting `-name` not `-botWebAppName`

**Comment by lauren-mills** [comment]
Hi @rslavey, thank you for reporting. [This doc](https://microsoft.github.io/botframework-solutions/skills/tutorials/create-skill/csharp/5-update-manifest/) has been updated accordingly.
