### ISSUE TITLE
Bot-Solutions Library missing dependencies in package.json

### ISSUE THREAD

**Issue by 01** [microsoft/botframework-solutions#3791]
#### What project is affected?
Bot-Solutions SDK

#### What language is this in?
Typescript

#### What happens?
SDK package.json missing dependency botframework-schema, botbuilder-core, 

#### What are the steps to reproduce this issue?
Attempt to use/install library without botframework-schema being installed explicitly or available through other dependencies flattening node modules. 

#### What were you expecting to happen?
Using library would not require explicitly installing top level dependency 

#### Can you share any logs, error output, etc.?
![image](https://user-images.githubusercontent.com/17934292/116304259-5dfd7700-a770-11eb-9efd-7d3cedef384c.png)
![image](https://user-images.githubusercontent.com/17934292/116304535-ac127a80-a770-11eb-8a01-41a23a05648f.png)

**Comment by Batta32** [comment]
Thanks @01 for reporting this issue. Can you attach the detailed repro steps that you are following in order to generate the error?

We will be reviewing this issue and as soon as we have any update, we will back to you here 😊.

**Comment by 01** [comment]
> Thanks @01 for reporting this issue. Can you attach the detailed repro steps that you are following in order to generate the error?
> 
> We will be reviewing this issue and as soon as we have any update, we will back to you here 😊.

Its simply installing bot-solutions module and importing it anywhere in application. As you can see in error log bot-solutions uses both botbuilder-core and botframework-schema however does not include them in the dependency list

 https://github.com/microsoft/botframework-solutions/blob/master/sdk/typescript/libraries/bot-solutions/package.json

**Comment by Batta32** [comment]
Thanks @01 for the explanation, we detected the issue and we created the PR #3793 which fixes this issue.

**Comment by Batta32** [comment]
We are closing this issue as it's fixed with the PR #3793 and as soon as the PR is merged, the changes will be present in `master` branch.

**Comment by 01** [comment]
> We are closing this issue as it's fixed with the PR #3793 and as soon as the PR is merged, the changes will be present in `master` branch.

Will a release to npmjs.org occur as well. Would prefer to be using a stable release and not a daily build as utilizing the library in a production environment

**Comment by Batta32** [comment]
Hi @01, as soon as the PR is merged and a new release is published, we will let you know 😊.
