### ISSUE TITLE
Not Proper Layout in Small Screen Sizes

### ISSUE THREAD

**Issue by SahilFruitwala** [microsoft/botframework-solutions#3795]
/virtual-assistant/tutorials/create-assistant/typescript/4-provision-you-azure-resources/

Found this issue when width was approximate 350px.
Tested this issue in Chrome and Edge both.
![image](https://user-images.githubusercontent.com/31241901/117140743-1edcb080-ad84-11eb-9c5a-20265f572bdf.png)

**Comment by darrenj** [comment]
Thanks for letting us now Sahil, we are in the process of migrating the core documentation into main docs as part of our upcoming Build release at this point we'll redirect from this doc location to the new one which shouldn't suffer from the same issue.
