### ISSUE TITLE
Layout Issues

### ISSUE THREAD

**Issue by SahilFruitwala** [microsoft/botframework-solutions#3796]
Page Link: https://microsoft.github.io/botframework-solutions/virtual-assistant/handbook/localization/

Getting toggle button(Hamburger button) for left side menu as shown in first image. But when try to increase width, for some width sizes it is not showing toggle button(Hamburger button) or side menu as shown in second image.

Not sure issue is in only this page or all the pages. I was using Microsoft Edge.

![image](https://user-images.githubusercontent.com/31241901/117170566-8274d700-ada0-11eb-81e7-b5877cc6d324.png)

![image](https://user-images.githubusercontent.com/31241901/117170357-55282900-ada0-11eb-8581-8cdaa548875d.png)

**Comment by darrenj** [comment]
Thanks for letting us now Sahil, we are in the process of migrating the core documentation into main docs as part of our upcoming Build release at this point we'll redirect from this doc location to the new one which shouldn't suffer from the same issue.
