### ISSUE TITLE
Testing Virtual Assistant after adding skills Doesn't Work In Web App Bot 

### ISSUE THREAD

**Issue by ShwethaVenkatesh-wq** [microsoft/botframework-solutions#3798]
What project is affected?

A demo for a Virtual Assistant and Hospitality Skill.

What language is this in?
C#

What happens?

Unable to test my VA even after following all the steps. I am getting an Issue testing VA locally and VA works separately and skills  works separately. After adding skills it has to show hospitality skill in VA and that doesn't work.

What are the steps to reproduce this issue?

Open a terminal and go to the Virtual Assistant folder
Deploy the Virtual Assistant executing the deploy.ps1 file
pwsh.exe -File Deployment\Scripts\deploy.ps1

Go to the Hospitality Skill folder
Deploy the Hospitality Skill executing the deploy.ps1 file
pwsh.exe -File Deployment\Scripts\deploy.ps1

Connect the Virtual Assistant, using the attached manifest
botskills connect --remoteManifest "http://skillbot.azurewebsites.net/manifest/manifest-1.1.json" --cs --luisFolder "<LU_FOLDER>"

Verify that the Virtual Assistant's appsettings.json contains the information of the connected Hospitality Skill - Yes it is connect 

If I test my VA with hosted URL my Virtual Assistance does not work with hospitality responds

Any screenshots or additional context?

![image](https://user-images.githubusercontent.com/75416361/117447856-a6c8e300-af5b-11eb-99bc-f335ae97af78.png)

**Comment by tdurnford** [comment]
@stevkan @anusharavindrar any updates on this?

**Comment by anusharr** [comment]
@ShwethaVenkatesh-wq, can you elaborate more on where your bot is hosted and if the bot and the emulator are on the same machine? Also, can you try configuring ngrok in the Emulator's application settings page and give it a go? 

When the bot receives a message, it looks through the received activity for a service URL -- where it will send the response to. If your bot is hosted somewhere not on your local machine, then it will not be able to send a message back to the Emulator without configuring ngrok, because the Emulator will have a `localhost` service url.

**Comment by ShwethaVenkatesh-wq** [comment]
@anusharavindrar, I can't configure ngrok, which is blocked in our company. I am unable to test in web chat
Can you help me to test in web chat.
I was testing with hosted URL and not localhost.

**Comment by anusharr** [comment]
@ShwethaVenkatesh-wq,  can you please explain more about where your bot is hosted and how are you trying to get connected to the WebChat channel? Also, is your bot hosted behind a firewall? Do you get any specific error while testing the VA on the WebChat channel? Can you share some screenshots of the error?

**Comment by anusharr** [comment]
Closing the issue. Please feel free to re-open if issue persists.
