### ISSUE TITLE
Token Refresh not available during any productivity flow which causes skill to fail

### ISSUE THREAD

**Issue by pvmraghunandan** [microsoft/botframework-solutions#380]
**Project**
Virtual Assistant Calendar skill

**Description**
During Productivity Flow for example create Event, there are multiple dialogs that initiates to the user. There are cases where by the time we collect all info and at the last tried to create event, the token is expired. Since the token is retrieved only during starting of dialog and there is no callback or retry handler, the exception causes to send unhandled exception and dialogs are disposed. Due to this user has to restart whole flow

**To Reproduce**
Try to create event and sometimes we get unhandled exception due to token expiry. 

**Expected behavior**
Catch the Service Exception and Monitor for status code. If it is un authorized, may be possible retry (or) some mechanism so that user doesn't need to restart the flow.

**Comment by darrenj** [comment]
@pvmraghunandan Thanks, to clarify this is where you start a "create event" flow and then "go away" for a while come back and try to continue the conversation to find the token has expired?

**Comment by pvmraghunandan** [comment]
@darrenj Yes that's correct.

**Comment by darrenj** [comment]
Thanks. Your right we should capture a token expiration error and request a new token using the mechanism that Skills use to get a token at the beginning. Should be a simple change and we'll get this looked at first thing in our next sprint (starting January).  Appreciate you raising it.

@lauren-mills , @lzc850612 - Suggest we repeat the token/request, token/response flow when a skill hits a token expiration error and we silently refresh the token and carry on. Once we have a pattern we can ask the Skills team to update across the other skills.

**Comment by darrenj** [comment]
Feed this into skill spec design to resolve

**Comment by darrenj** [comment]
Resolved as part of new skill implementation for Build
