### ISSUE TITLE
Update Nuget dependencies 

### ISSUE THREAD

**Issue by tomSauret847** [microsoft/botframework-solutions#3803]
#### What project is affected?
Virtual Assistant and Skill

#### What language is this in?
.Net
#### What happens?
The current version of the bot framework packages is 4.13.1 this library still uses version 4.9.3 As a developer I would like to keep dependencies on the latest stable version
#### What are the steps to reproduce this issue?
When updating to the latest version there is dependency errors
#### What were you expecting to happen?
U[grading to the newer versions will not cause errors

**Comment by ninggao** [comment]
@lauren-mills Could you please take a look at this issue?

**Comment by lauren-mills** [comment]
@batta32 - can you evaluate what it will take for us to update to the latest SDK? It will depend on other decisions whether we want to release a new version or not, but would like to understand what would be required if we do.

**Comment by Batta32** [comment]
Sure @lauren-mills, we will evaluate what it's necessary to do in order to consume the latest SDK version!

As soon as we have any update, we will get back here 😊.

**Comment by Batta32** [comment]
Hi @lauren-mills, we came up with the considerations that are necessary to consume the latest SDK version ([4.13.2](https://www.nuget.org/packages/Microsoft.Bot.Builder/4.13.2))

### Bot-Solutions
1. Cherry pick the PR #3618
1. Fix ambiguity issue with SetSpeakMiddleware
    a. Keep [SetSpeakMiddleware](https://github.com/microsoft/botframework-solutions/blob/master/sdk/csharp/libraries/microsoft.bot.solutions/Middleware/SetSpeakMiddleware.cs) of Bot-Solutions
    b. Use [SetSpeakMiddleware](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder/SetSpeakMiddleware.cs) of Bot-Builder (added in microsoft/botbuilder-dotnet#5343)

### Virtual Assistant
1. Consume new release of Bot-Solutions
1. Fix ambiguity issue with SetSpeakMiddleware
    a. Keep [SetSpeakMiddleware](https://github.com/microsoft/botframework-solutions/blob/master/sdk/csharp/libraries/microsoft.bot.solutions/Middleware/SetSpeakMiddleware.cs) of Bot-Solutions
    b. Use [SetSpeakMiddleware](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder/SetSpeakMiddleware.cs) of Bot-Builder (added in microsoft/botbuilder-dotnet#5343)
1. Fix ambiguity issue with AllowedCallersClaimsValidator
    a. Keep [AllowedCallerClaimsValidator](https://github.com/microsoft/botframework-solutions/blob/master/samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Authentication/AllowedCallersClaimsValidator.cs) of Virtual Assistant
    b. Use [AllowedCallerClaimsValidator](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Connector/Authentication/AllowedCallersClaimsValidator.cs) of Bot-Connector (added in microsoft/botbuilder-dotnet#5286)
1. Fix ambiguity issue with SkillConversationIdFactory
    a. Keep [SkillConversationIdFactory](https://github.com/microsoft/botframework-solutions/blob/master/sdk/csharp/libraries/microsoft.bot.solutions/Skills/SkillConversationIdFactory.cs) of Bot-Solutions
    b. Use [SkillConversationIdFactory](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder/Skills/SkillConversationIdFactory.cs) of Bot-Builder (added in microsoft/botbuilder-dotnet#3076)
1. Fix obsolote warning of AzureBlobTranscriptStore
    a. Keep [AzureBlobTranscriptStore](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder.Azure/AzureBlobTranscriptStore.cs) (deprecated in microsoft/botbuilder-dotnet#4735)
    b. Use [BlobTranscriptStore](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder.Azure.Blobs/BlobsTranscriptStore.cs)
1. Replicate changes in Virtual Assistant Template

### Skill
1. Consume new release of Bot-Solutions
1. Fix ambiguity issue with SetSpeakMiddleware
    a. Keep [SetSpeakMiddleware](https://github.com/microsoft/botframework-solutions/blob/master/sdk/csharp/libraries/microsoft.bot.solutions/Middleware/SetSpeakMiddleware.cs) of Bot-Solutions
    b. Use [SetSpeakMiddleware](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder/SetSpeakMiddleware.cs) of Bot-Builder (added in microsoft/botbuilder-dotnet#5343)
1. Fix ambiguity issue with AllowedCallersClaimsValidator
    a. Keep [AllowedCallerClaimsValidator](https://github.com/microsoft/botframework-solutions/blob/master/samples/csharp/skill/SkillSample/Authentication/AllowedCallersClaimsValidator.cs) of Skill
    b. Use [AllowedCallerClaimsValidator](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Connector/Authentication/AllowedCallersClaimsValidator.cs) of Bot-Connector (added in microsoft/botbuilder-dotnet#5286)
1. Fix obsolote warning of AzureBlobTranscriptStore
    a. Keep [AzureBlobTranscriptStore](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder.Azure/AzureBlobTranscriptStore.cs) (deprecated in microsoft/botbuilder-dotnet#4735)
    b. Use [BlobTranscriptStore](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder.Azure.Blobs/BlobsTranscriptStore.cs)
1. Replicate changes in Skill Template

Let us know if you want us to apply these changes as soon as it's decided 😊.

**Comment by johnataylor** [comment]
@lauren-mills can you comment? thanks

**Comment by lauren-mills** [comment]
We will be updating the templates for R14. Will update once progress has been made.

**Comment by lauren-mills** [comment]
@Batta32 - we do want to go ahead with these changes. I'm emailing with some other questions I have first.
