### ISSUE TITLE
The Java Android app needs to handle connection/authentication errors better

### ISSUE THREAD

**Issue by dargilco** [microsoft/botframework-solutions#3804]
#### What project is affected?
Java/Android sample in https://github.com/microsoft/botframework-solutions/tree/master/samples/android/clients/VirtualAssistantClient

#### What language is this in?
Java

#### What happens?
The application does not handle well the case where you configure it with a bad (invalid) speech key, or when there is no network connection. It endlessly tries to re-establish the connection, and the UI experience is bad as a result.  I suggest updating the application to not retry on these types of failures.

#### What are the steps to reproduce this issue?
Compile the app using a valid speech key and speech key-region and run the application on your phone when it's on airplane mode. Or, better yet, compile the app using some junk speech key value and key-region, and run the application on your phone.
Important: Please upgrade the app to use Speech SDK 1.17 that just came out, as there were improvements in how it handles connection/authentication errors.

#### What were you expecting to happen?
The application should display the error message it got from Speech SDK. Instead, it's stuck in an endless loop of retrying to connect and that freezes the UI (if I remember correctly)

**Comment by lauren-mills** [comment]
Closed by #3811
