### ISSUE TITLE
Automatic update of teams users list(Teams bot issue) 

### ISSUE THREAD

**Issue by amoyalan20** [microsoft/botframework-solutions#3805]
We have wrote a code in OnMembersAddedAsync activity to get all users who all are accessing the teams bot. But we are only getting users who are newly accessing the teams bot. Is there any way to refresh and start new conversation in MS Teams, so that its gets hit on on-members added activity.

We have tried an “Auto Deploy” method for the existing teams bot. Still not able to get the user information in OnMembersAddedAsync for existing users. Can you please help us to resolve this issue?

**Comment by ninggao** [comment]
Hi @stevkan , could you please take a look at this issue?

**Comment by stevkan** [comment]
Closing as duplicate of #[6294](https://github.com/microsoft/botframework-sdk/issues/6294). Please refer to the other issue as I have included an additional comment there.
