### ISSUE TITLE
Error while connecting skill

### ISSUE THREAD

**Issue by pdesai-icims** [microsoft/botframework-solutions#3808]
#### What project is affected?
Virtual Assistant/ Skills
#### What language is this in?
C#
#### What happens?
When trying to add the skill to the bot, the script errors out while creating dispatch LUIS model JSON. 
![Screen Shot 2021-05-20 at 4 45 06 PM](https://user-images.githubusercontent.com/56562244/119048209-ebf20980-b98c-11eb-9c0d-118eee4b332b.png)
It also doesn't update all the dispatch files it should, plus deletes the folder structure under dispatch as well. Here are before and after screenshots of the bot, skills connect deleting the folders.
_Before_
![Screen Shot 2021-05-20 at 5 02 12 PM](https://user-images.githubusercontent.com/56562244/119048823-c3b6da80-b98d-11eb-9791-d8447c467343.png)
_After_
_![Screen Shot 2021-05-20 at 5 03 25 PM](https://user-images.githubusercontent.com/56562244/119048653-85212000-b98d-11eb-911e-c3875627a3ef.png)_ 
#### What are the steps to reproduce this issue?
Add skill to VA using the command : 
_botskills connect --remoteManifest "https://<YOUR_SKILL_NAME>.azurewebsites.net/manifest/manifest-1.1.json" --cs --luisFolder "<PATH_TO_LU_FOLDER>"_
#### What were you expecting to happen?
Skill to connect to VA
#### Can you share any logs, error output, etc.?
attached
#### Any screenshots or additional context?
attached.

**Comment by ninggao** [comment]
@stevkan  Could you please route it to anyone who can help the customer?

**Comment by Batta32** [comment]
Hi @parasdesaicims, thanks for reporting the issue. The next week we will start working on this issue, as soon as we have any update, we will let you know 😊.

**Comment by cgero-msft** [comment]
Commenting to track progress @parasdesaicims

**Comment by Batta32** [comment]
Hi @parasdesaicims, sorry for the delay. We successfully **found the solution** for your problem but also we **reproduced the issue** on our side.

To **solve the issue**, check in `MyVirtualAssistant9en-us_Dispatch.dispatch` file if the .LUIS file located in `"C:\Users\Paras Desai\Documents\LM-Skill1\LMSkill_1\Deployment\Resources\LU\en-us\lmskill_1.luis"` exists or not.
That resource seems to be an old skill that you have connected (not the one you are trying to connect) and the **LUIS file is not present in that folder**.

Here you have **2 alternatives**:
1. Keep that resource:
    1. Execute the [bf luis:convert](https://www.npmjs.com/package/@microsoft/botframework-cli/v/4.7.0#bf-luisconvert) command to convert the .lu file to a LUIS application
        ```bash
        bf luis:convert --in "C:\Users\Paras Desai\Documents\LM-Skill1\LMSkill_1\Deployment\Resources\LU\en-us\lmskill_1.lu" --culture "en-us" --out "C:\Users\Paras Desai\Documents\LM-Skill1\LMSkill_1\Deployment\Resources\LU\en-us\lmskill_1.luis" --name "LMSkill_1"
        ```
    1. Connect the new Skill
        ```bash
        botskills connect --remoteManifest "https://eu2-lmskill-1-efx4ell.azurewebsites.net/manifest/manifest-1.1.json" --cs --luisFolder "C:\Users\Paras Desai\Documents\Github\LM skill\License-Provisioning-Skill\LMSkill_1\Deployment\Resources\LU"
        ```
1. Remove that resource:
    1. Obtain the ID of the incorrect resource
        ```bash
        botskills list --cs
        ```
    1. Disconnect the incorrect resource
        ```bash
        botskills disconnect --i "<OBTAINED_ID>" --cs
        ```
    1. Connect the new Skill
        ```bash
        botskills connect --remoteManifest "https://eu2-lmskill-1-efx4ell.azurewebsites.net/manifest/manifest-1.1.json" --cs --luisFolder "C:\Users\Paras Desai\Documents\Github\LM skill\License-Provisioning-Skill\LMSkill_1\Deployment\Resources\LU"
        ```

We followed these steps to reproduce the issue:
1. Connect first skill to the Virtual Assistant
1. Delete generated .luis file of the first skill
1. Connect second skill to the Virtual Assistant
1. See error during the dispatch refresh

Hope this helps 😊.

_.dispatch with the incorrect (removed) and correct LUIS files_
![image](https://user-images.githubusercontent.com/11904023/119850313-cfe9ed00-bee3-11eb-8a68-8cf38d4a1f33.png)

_Issue reproduced_
![image](https://user-images.githubusercontent.com/11904023/119850305-ce202980-bee3-11eb-8614-05334f3ff67f.png)

**Comment by pdesai-icims** [comment]
yes. @Batta32 after doing the above steps, I was able to add the skill. Though one more step to follow would be the refresh of the cognitive models from Local to remote (or w/o -Remotetolocal tag) would make sure the Bot gets pushed to the teams correctly.

One issue I am facing, and I feel it's a bug. I have added authentication to the skill, while everything runs smoothly in the skill itself when I am trying to run the same auth with VA it doesn't take the clicks on the login button(shows the link correctly) in teams even though there is an activity handler set up in the class. Please let me know if you need more information or shall I open another request. Attaching the screenshot here. 
![Screen Shot 2021-06-07 at 2 51 52 PM](https://user-images.githubusercontent.com/56562244/121194689-f93c3e80-c83c-11eb-9926-2c49d50cd085.png)

**Comment by Batta32** [comment]
Great @parasdesaicims! Glad to hear that the connection worked now, we will close this issue 😊.

About the authentication's problem, can you raise a new issue in the repository explaining the step by step and environment that you are following?
