### ISSUE TITLE
[Docs] Missing " in dispatch add --type "qna" --name "kb-name `

### ISSUE THREAD

**Issue by lukashoferdev** [microsoft/botframework-solutions#3809]
**Missing " in dispatch add  --type "qna" --name "kb-name `**

**https://microsoft.github.io/botframework-solutions/virtual-assistant/tutorials/deploy-assistant/cli/7-create-dispatch-model/**

**Comment by ryanisgrig** [comment]
Thank you for your contribution @lukashoferdev, we are assessing all of our pull requests in the near future and I will review this PR then.
