### ISSUE TITLE
Can we have more examples in TypeScript

### ISSUE THREAD

**Issue by SahilFruitwala** [microsoft/botframework-solutions#3812]
I was trying to change the feedback options but could not understand codebase very well. I tried to find documentation but it was available in C# only. There are many cases where I could not find the proper documentation for TypeScript.

URL of C# example: [Link](https://microsoft.github.io/botframework-solutions/virtual-assistant/handbook/feedback/)

**Comment by SahilFruitwala** [comment]
Great! Thank you for your help.

**Comment by johnataylor** [comment]
We are not planning to add any more stand alone code samples, in terms of samples, our focus is on extending the Composer experience.
