### ISSUE TITLE
Store Transcript and Logging in CosmosDB

### ISSUE THREAD

**Issue by SahilFruitwala** [microsoft/botframework-solutions#3813]
I was exploring the Virtual Assistant and wanted to use one DB only. I don't want to use Blob storage for transcript and telemetry data. I could not find any out of box way to store this data in CosmosDB. 

Is there any way to use the CosmosDB for storing this data?

**Comment by mdrichardson** [comment]
@SahilFruitwala I don't believe we can do anything like this out-of-the-box, currently. I've opened a [feature request for it](https://github.com/microsoft/botframework-sdk/issues/6303) and it may be considered for v5 of the Bot Framework. We'd prioritize it higher, but as far as I know, you're the first user to ask for this so it's going to fall a bit lower on the priority list.

You're welcome to implement it yourself, if you'd like. You'd need to create a class that implements [ITranscriptStore](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder/ITranscriptStore.cs). You could use [BlobsTranscriptStore](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder.Azure.Blobs/BlobsTranscriptStore.cs) as an example.

Bear in mind, though, that Cosmos is more expensive than Blob storage. Cosmos' main advantage is that it is significantly more performant, which _generally_ isn't needed for transcripts.

I'll be closing this issue in favor of the Feature Request I opened, above. Feel free to comment, though, as I'll monitor this one still.

**Comment by SahilFruitwala** [comment]
Great! Thank you for your help.
