### ISSUE TITLE
Oauth Card Login button not working in MS teams

### ISSUE THREAD

**Issue by pdesai-icims** [microsoft/botframework-solutions#3824]
#### What project is affected?
Virtual Assistant/ Skills
#### What language is this in?
C#
#### What happens?
Oauth in skill works fine, but after attaching the skill to VA the login doesn't work in the VA.
*Login Via skill :* 
![Screen Shot 2021-06-08 at 3 08 52 PM](https://user-images.githubusercontent.com/56562244/121243628-e9881e80-c86b-11eb-9dd2-576fd0568bd8.png)
![Screen Shot 2021-06-08 at 3 10 20 PM](https://user-images.githubusercontent.com/56562244/121243632-eb51e200-c86b-11eb-9bd1-c93f65e59fb8.png)

Login After connecting to VA : 
_![Screen Shot 2021-06-07 at 2 51 52 PM](https://user-images.githubusercontent.com/56562244/121243703-06bced00-c86c-11eb-8f64-607a3df4bfc2.png)_ 

#### What are the steps to reproduce this issue?
Similar steps on above to reproduce, whenever the intent is identified for the skill, Waterfall steps, first step is to get the access token and get user details.

#### What were you expecting to happen?
Expecting to get prompted for the login screen and user to be logged in. Since that same behavior works fine in the skill.

#### Can you share any logs, error output, etc.? & #### Any screenshots or additional context?
Attached the screenshots & details above.

**Comment by lauren-mills** [comment]
Hi @parasdesaicims, did you follow the instructions to create a Teams Manifest and  set up the authentication URL here? https://microsoft.github.io/botframework-solutions/clients-and-channels/tutorials/enable-teams/1-intro/

**Comment by pdesai-icims** [comment]
I actually followed that process for my skill but not for the main Virtual assistant, it does work now after adding the bot to our tenant. 

Thank you for the help @lauren-mills . This issue can be closed.
