### ISSUE TITLE
VA + Skill Template Bots do not start up when hosted Out-Of-Process

### ISSUE THREAD

**Issue by msomanathan** [microsoft/botframework-solutions#3828]
#### What project is affected?
VA + Skill templates.

#### What language is this in?
C#

#### What happens?
To enable DL-ASE channel to talk to a bot, one of the requirements is for the bot to be hosted out-of-process. More info about that is here: https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/aspnet-core-module?view=aspnetcore-3.1&preserve-view=true#out-of-process-hosting-model.

However, if this setting is enabled on bots created by the VA + Skill templates, the bot fails to start up.

#### What are the steps to reproduce this issue?
- Update csproj of the VA/Skill bot to add: `<AspNetCoreHostingModel>OutOfProcess</AspNetCoreHostingModel>`
- F5 to start the bot locally
- Bot does not start up, and the bot landing page keeps spinning indefinitely.

#### What were you expecting to happen?
- Bot starts up with no issues and the landing page shown successfully.

#### Any screenshots or additional context?
@lauren-mills identified that the root cause for this issue is a .NET version mismatch between the VA bot and the Microsoft.Bot.Solutions package. That package needs to be updated to fix this issue.

**Comment by lauren-mills** [comment]
New versions of the templates VSIX and the microsoft.bot.solutions package have been released to resolve this issue. Please test and let us know how it works for you.
