### ISSUE TITLE
Bot works in Test in Web Chat & Emulator but not in Microsoft Teams

### ISSUE THREAD

**Issue by watercooleradmin** [microsoft/botframework-solutions#3838]
Hi,

I have created a custom bot for Teams which works when I Test in Web Chat or with the Bot Framework Emulator. When I go to Teams ( I have done both Open in Teams from the Bot Channels and uploading a custom app in Teams) I cannot get the bot to work at all. Neither the welcome prompt loads nor does it respond to any of its commands. 

I have tried fixes mentioned in previous issue threads such as signing out of Teams, closing the app, and signing back in as mentioned in https://github.com/microsoft/botframework-sdk/issues/5478#issuecomment-514797321, but none of that has worked so far.

Thank you

**Comment by joshgummersall** [comment]
Are you seeing any errors in the Azure Portal Channels blade?

<img width="1325" alt="Screen Shot 2021-08-17 at 12 14 33 PM" src="https://user-images.githubusercontent.com/1235378/129786759-a0a281ae-aef6-4f13-988c-0c0d32d2449a.png">

**Comment by LeeParrishMSFT** [comment]
Closed due to no customer response.
