### ISSUE TITLE
[Docs] Download and install the Virtual Assistant and Skill Templates. - Requested page not found

### ISSUE THREAD

**Issue by michaeljdresser** [microsoft/botframework-solutions#3846]
/virtual-assistant/tutorials/create-assistant/csharp/2-download-and-install/

Clicking the link in step 2, takes you to a page which says the page cannot be found.

Where is the Virtual Assistant and Skill template now kept?

**Comment by ryanisgrig** [comment]
Hi @michaeljdresser,

The templates have been deprecated and removed from the marketplace. Thank you for highlighting the docs issue, we will follow up and update those to reflect this. 

I recommend creating any new bots using [Bot Framework Composer](https://docs.microsoft.com/en-us/composer/), these are built on the current Adaptive dialog stack. 

If you would prefer to use the Virtual Assistant and Skill templates, you can clone the repository and use the following samples to align with the doc:
- [VirtualAssistantSample](https://github.com/microsoft/botframework-solutions/tree/1.1.0/samples/csharp/assistants/virtual-assistant)
- [SkillSample](https://github.com/microsoft/botframework-solutions/tree/1.1.0/samples/csharp/skill)
