### ISSUE TITLE
Cannot use checkbox in to do list

### ISSUE THREAD

**Issue by feich-ms** [microsoft/botframework-solutions#385]
**Project**
Skills

**Description**
Users can not mark the to do items done by checkbox

**To Reproduce**
create to do task
Have bot show to do list
check off a box
have bot show to do list
The checked box shows up as unchecked once again

**Expected behavior**
The checked box shows up as checked

**Screenshots**

**Additional context**

**Comment by bobokids** [comment]
Fixed.
