### ISSUE TITLE
QNA Maker

### ISSUE THREAD

**Issue by robertomenciasoftwareone** [microsoft/botframework-solutions#3850]
/overview/virtual-assistant-solution/

I add a file with questions and answers but the bot doesn't find it if you don't put the exact question. The dispatcher is not updated.

**Comment by EricDahlvang** [comment]
Hi @robertomenciasoftwareone 

Have you also updated and republished the QnAMaker Knowledge base and dispatcher models?

https://github.com/microsoft/botframework-cli/blob/main/packages/qnamaker/README.md
https://github.com/microsoft/botframework-cli/blob/main/packages/dispatcher/README.md

**Comment by carlosscastro** [comment]
Closing this one due to inactivity. @robertomenciasoftwareone if Eric's recommendation did not work for you, feel free to reactivate, thanks!
