### ISSUE TITLE
Add Custom Commands application as a skill in Bot framework composer application

### ISSUE THREAD

**Issue by ridasaleem0** [microsoft/botframework-solutions#3876]
The documentation (https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-custom-commands-integrate-remote-skills) gives an idea about how to export the Custom Commands application as a skill, however, there is no skills tab available in the Speech studio under Custom commands settings.

Is there a way to export our commands app as a skill inside the bot framework application?

**Comment by gabog** [comment]
Hi @ridasaleem0, I don't think this issue belongs to this repo, the solutions has been deprecated and this feature is not supported.
