### ISSUE TITLE
Developer Defined List Type in To Do Skill

### ISSUE THREAD

**Issue by Dewain27** [microsoft/botframework-solutions#39]
Give the developer the ability to add custom list types to the skill and the language model.

**Comment by bobokids** [comment]
Currently developer can add new list type by modifying the LUIS model, resource file (for list type name), and several code file that handle the specific list type. We can tune the code to make the code logic neutral to new list types, that developer only need to modify luis model and resource file. Dewain, is this behavior this bug expected?
Furthermore, we may refactoring to remove the dependency to resource file, but that's relatively big change and need more investigation.

**Comment by Dewain27** [comment]
I think making the logic neutral to new list types would be fine, but we will need to document how to do this with an example to ensure that developers know how to add additional ones.

**Comment by bobokids** [comment]
Fixed in https://github.com/microsoft/botframework-solutions/pull/1521
