### ISSUE TITLE
Login fails when deployed to teams

### ISSUE THREAD

**Issue by kendomen** [microsoft/botframework-solutions#390]
**Project**

Calendar Skill 

**Description**

When asking "what's my schedule like in teams, the oauth card appears but the Login button doesn't respond.

**To Reproduce**

@vassist "What's my schedule like"

**Expected behavior**

Just like the emulator, it should pop up a browser for me to log in

**Screenshots**

![nothing](https://user-images.githubusercontent.com/8027762/49470757-cc1bfa80-f7bf-11e8-980f-b3083358779d.png)

**Additional context**

**Comment by NobinJoseRad** [comment]
I also encountered the same issue. Login button is not prompted in Teams.

**Comment by kendomen** [comment]
The exact same code on a direct channel on the web works just fine but I'd like for it to work on teams.

![signin](https://user-images.githubusercontent.com/8027762/49591669-ef5fba80-f923-11e8-80a0-7a0b532f566b.png)

**Comment by lauren-mills** [comment]
Looks like this is related to this bug: https://github.com/Microsoft/BotBuilder/issues/4768

It contains a work around, and I'll try to add it in to our codebase this week.

**Comment by kendomen** [comment]
I have verified that it works with the TeamsAuthWorkaroundMiddleware added.

thanks you!

<img width="756" alt="works" src="https://user-images.githubusercontent.com/8027762/49663402-6324c480-fa03-11e8-8f10-dac0072a745b.png">
