### ISSUE TITLE
Skills Template

### ISSUE THREAD

**Issue by darrenj** [microsoft/botframework-solutions#394]
**Project**
Virtual Assistant

**Description**
The first pass at a Skill Template to help our internal work needs formalising into a formal Skill Template to allow someone to create a new Skill and enable an "F5" experience to have this working out of the box so they can plug into the VA without having to worry about Skill specifics enabling them to focus on their own skill code.

- [ ] Ensure project is .NET Core 2.2 (or latest) out of the box
- [x] Rationalise ISkillConfiguration and SkillConfiguration on constructor and ensure template represents our preferred direction. Some of our skills seems to use ISkillConfiguration now (so we should align too). Also requires changes to Startup.cs
```
var supportedProviders = Configuration.GetSection("SupportedProviders")?.Get<string[]>();
ISkillConfiguration connectedServices = new SkillConfiguration(botConfig, supportedProviders, parameters, configuration);
services.AddSingleton(sp => connectedServices);
```
- [x] Update to new DeploymentScripts approach
- [x] CognitiveModels/LUIS/en folder not created, perhaps add a skill.lu file placeholder?
- [x] Add Actions.cs file to Shared folder
- [x] Starter LU file for a ExampleDialog and wire intent into RouteAsync/MainDialog
- [x] Starter Dialog which is wired up ready to go - e.g. ExampleDialog
- [x] Update to reflect new auth approach for multiple providers
- [x] Remove News Nuget package reference
- [x] Template created csproj has lamillsbot-insights references which need to be removed
- [x] OnLogout handler in MainDialog refers to old AuthConnectionName
- [x] {SkillName}Dialog constructor has old oAuthPrompt/AuthConnectionName code
- [x] Add stylecop analyzer nuget
- [x] Ensure the MainResponses have the right InputHint - e.g. acceptingInput rather than expectingInput for greeting
- [x] End to End Test
- [x] VSIX
- [x] Documentation guiding the user on how to add a LUIS model and Dialog and wire up
- [x] Documentation guiding the user on how to take a skill and add to VA
- [x] Skill development guide (best practice)

**Comment by lauren-mills** [comment]
I'm removing the 2.2 dependency because our build pipeline doesn't support it yet. Once the build and release pipelines support 2.2 we will update all the projects at the same time.
