### ISSUE TITLE
How about change the default locale from Chinese to English?

### ISSUE THREAD

**Issue by angie4u** [microsoft/botframework-solutions#396]
**Is your feature request related to a problem? Please describe.**
When an user use VA bot without setting default locale, the VA bot will reply you using Chinese.
https://github.com/Microsoft/AI/blob/0ca01245e4b0c790b236a1510740d02789c825a5/solutions/Virtual-Assistant/src/csharp/microsoft.bot.solutions/Skills/SkillDialog.cs#L173

**Describe the solution you'd like**
change the default locale from "zh-cn" to "en-us"

**Comment by lzc850612** [comment]
I'll fix it
