### ISSUE TITLE
As a developer, I would like to have an ITelemetryClient interface so I can write logging tests and decouple my logging from AppInsights

### ISSUE THREAD

**Issue by gabog** [microsoft/botframework-solutions#398]
Currently, TelemetryLoggerMiddleware, TelemetryLuisRecognizer, TelemetryQnAMaker, and SkillConfiguration use Microsoft.ApplicationInsights.TelemetryClient (which doesn't provide an interface).

We need an interface that decouples logging from AppInsights so we can write TelemetryClients that:

- Can be used in unit tests to validate the telemetry is written during the tests.
- Be able to provide a custom implementation for TelemetryClient that uses business rules to determine where to log and what to log (for example, GDPR requires that some data gets stored in a separate storage containers based on user privacy opt-in and opt-out settings).
- Be able to log telemetry to other sources other than app insights (we don't need this but is a nice to have).

**Describe the solution you'd like**
I'd like to have an interface and provide the instance of the client I want to use through dependency injection at runtime and per turn (so I can evaluate rules based on the current user).

Here is an example of the ITelemetryLogger we are using (wich replicates the signature of the AppInisghts methods we use):

    /// <summary>
    /// Defines the operations available to log telemetry for the bot.
    /// </summary>
    public interface ITelemetryLogger
    {
        Task LogActivity(string eventName, ITurnContext context, Activity activity, Dictionary<string, string> additionalProperties = null, IDictionary<string, double> additionalMetrics = null);
        Task LogActivity(Activity activity, ITurnContext context, Dictionary<string, string> additionalProperties = null, IDictionary<string, double> additionalMetrics = null);
        Task LogEvent(string eventName, ITurnContext context, Dictionary<string, string> additionalProperties = null, IDictionary<string, double> additionalMetrics = null);
        Task LogException(Exception exception, ITurnContext context, Dictionary<string, string> properties = null, IDictionary<string, double> metrics = null);
        Task LogMetric(string metricName, double metricValue, ITurnContext context, Dictionary<string, string> properties = null);
        Task LogTrace(string message, ITurnContext context, SeverityLevel severityLevel = SeverityLevel.Information, Dictionary<string, string> properties = null);
        Task LogQnAMakerResult(string question, string qnaMakerAppId, QueryResult[] results, ITurnContext context, Dictionary<string, string> additionalProperties = null, IDictionary<string, double> additionalMetrics = null);
        Task LogLuisIntent(string luisAppId, ITurnContext context, string recognizerStateKey, Dictionary<string, string> additionalProperties = null, IDictionary<string, double> additionalMetrics = null);
        Task LogSentimentAnalysisResult(float? sentimentScore, SentimentResponse sentimentResponse, ITurnContext context);
        Task LogKeyPhrasesResult(string keyPhrases, ITurnContext context);
    }

With this approach, the TelemetryLoggerMiddleware would look something like this:

        public TelemetryLoggerMiddleware(ITelemetryLogger)
        {
            ...
        }

And the decision of what to log and where to log would be deferred to the concrete implementation.

**Comment by darrenj** [comment]
Resolved in most recent checkin
