### ISSUE TITLE
Enterprise Bot Project Template is not building if we use the name of the project with dot (".") 

### ISSUE THREAD

**Issue by sowsan** [microsoft/botframework-solutions#399]
## Tool
Name: Enterprise Bot Project Template is not building if we use the name of the project with dot (".") , eg"something.ai.bot"
Version: *VS 2017 15.9.3*
OS: *Windows 10 , Version 10.0.17763*

## To Reproduce
1. Create project using the "Enterprise Bot Template"
2. Give the name of the project with dots (e.g, mybot.ai)
3. Build the project , it fails with bunch of errors.

## Expected behavior
A clean build without any errors if the project name has "."

## Error Details
1>------ Build started: Project: mybot.ai, Configuration: Debug Any CPU ------
1>mybot.ai.cs(17,23,17,24): error CS1514: { expected
1>mybot.ai.cs(17,23,17,24): error CS1513: } expected
1>mybot.ai.cs(17,23,17,24): error CS1022: Type or namespace definition, or end-of-file expected
1>mybot.ai.cs(17,24,17,26): error CS0116: A namespace cannot directly contain members such as fields or methods
1>mybot.ai.cs(17,27,17,28): error CS1022: Type or namespace definition, or end-of-file expected
1>mybot.ai.cs(17,29,17,33): error CS0116: A namespace cannot directly contain members such as fields or methods
1>mybot.ai.cs(18,5,18,6): error CS1022: Type or namespace definition, or end-of-file expected
1>mybot.ai.cs(30,18,30,20): error CS0116: A namespace cannot directly contain members such as fields or methods
1>mybot.ai.cs(30,102,30,103): error CS0116: A namespace cannot directly contain members such as fields or methods
1>mybot.ai.cs(31,9,31,10): error CS1022: Type or namespace definition, or end-of-file expected
1>mybot.ai.cs(32,13,32,31): error CS0116: A namespace cannot directly contain members such as fields or methods
1>mybot.ai.cs(32,32,32,33): error CS1022: Type or namespace definition, or end-of-file expected
1>mybot.ai.cs(32,34,32,51): error CS0116: A namespace cannot directly contain members such as fields or methods
1>mybot.ai.cs(32,52,32,54): error CS1022: Type or namespace definition, or end-of-file expected
1>mybot.ai.cs(32,93,32,94): error CS1001: Identifier expected
1>mybot.ai.cs(32,93,32,94): error CS1003: Syntax error, ',' expected
1>mybot.ai.cs(32,111,32,112): error CS8124: Tuple must contain at least two elements.
1>mybot.ai.cs(32,112,32,113): error CS1001: Identifier expected
1>mybot.ai.cs(33,5,33,15): error CS0116: A namespace cannot directly contain members such as fields or methods
1>mybot.ai.cs(33,16,33,17): error CS1022: Type or namespace definition, or end-of-file expected
1>mybot.ai.cs(33,18,33,27): error CS0116: A namespace cannot directly contain members such as fields or methods
1>mybot.ai.cs(33,28,33,30): error CS1022: Type or namespace definition, or end-of-file expected
1>mybot.ai.cs(33,69,33,70): error CS1001: Identifier expected
1>mybot.ai.cs(33,69,33,70): error CS1003: Syntax error, ',' expected
1>mybot.ai.cs(33,79,33,80): error CS8124: Tuple must contain at least two elements.
1>mybot.ai.cs(33,80,33,81): error CS1001: Identifier expected
1>mybot.ai.cs(34,5,34,14): error CS0116: A namespace cannot directly contain members such as fields or methods
1>mybot.ai.cs(34,15,34,16): error CS1022: Type or namespace definition, or end-of-file expected
1>mybot.ai.cs(34,17,34,28): error CS0116: A namespace cannot directly contain members such as fields or methods
1>mybot.ai.cs(34,29,34,31): error CS1022: Type or namespace definition, or end-of-file expected
1>mybot.ai.cs(34,70,34,71): error CS1001: Identifier expected
1>mybot.ai.cs(34,70,34,71): error CS1003: Syntax error, ',' expected
1>mybot.ai.cs(34,82,34,83): error CS8124: Tuple must contain at least two elements.
1>mybot.ai.cs(34,83,34,84): error CS1001: Identifier expected
1>mybot.ai.cs(36,5,36,13): error CS0116: A namespace cannot directly contain members such as fields or methods
1>mybot.ai.cs(36,14,36,15): error CS1022: Type or namespace definition, or end-of-file expected
1>mybot.ai.cs(36,76,36,77): error CS1001: Identifier expected
1>mybot.ai.cs(36,76,36,77): error CS1003: Syntax error, ',' expected
1>mybot.ai.cs(36,83,36,84): error CS8124: Tuple must contain at least two elements.
1>mybot.ai.cs(36,83,36,84): error CS1026: ) expected
1>mybot.ai.cs(36,83,36,84): error CS1001: Identifier expected
1>mybot.ai.cs(36,83,36,84): error CS1003: Syntax error, ',' expected
1>mybot.ai.cs(36,92,36,93): error CS8124: Tuple must contain at least two elements.
1>mybot.ai.cs(36,93,36,94): error CS1001: Identifier expected
1>mybot.ai.cs(36,94,36,95): error CS1002: ; expected
1>mybot.ai.cs(36,94,36,95): error CS1022: Type or namespace definition, or end-of-file expected
1>mybot.ai.cs(37,22,37,25): error CS0116: A namespace cannot directly contain members such as fields or methods
1>mybot.ai.cs(37,26,37,29): error CS1031: Type expected
1>mybot.ai.cs(37,26,37,29): error CS8124: Tuple must contain at least two elements.
1>mybot.ai.cs(37,26,37,29): error CS1026: ) expected
1>mybot.ai.cs(37,50,37,51): error CS1001: Identifier expected
1>mybot.ai.cs(37,70,37,71): error CS1001: Identifier expected
1>mybot.ai.cs(37,82,37,83): error CS1001: Identifier expected
1>mybot.ai.cs(37,83,37,84): error CS1002: ; expected
1>mybot.ai.cs(37,83,37,84): error CS1022: Type or namespace definition, or end-of-file expected
1>mybot.ai.cs(66,5,66,6): error CS1022: Type or namespace definition, or end-of-file expected
1>mybot.ai.cs(67,1,67,2): error CS1022: Type or namespace definition, or end-of-file expected
1>mybot.aiState.cs(8,23,8,24): error CS1514: { expected
1>mybot.aiState.cs(8,23,8,24): error CS1513: } expected
1>mybot.aiState.cs(8,23,8,24): error CS1022: Type or namespace definition, or end-of-file expected
1>mybot.aiState.cs(8,24,8,31): error CS0116: A namespace cannot directly contain members such as fields or methods
1>mybot.aiState.cs(8,32,8,33): error CS1022: Type or namespace definition, or end-of-file expected
1>mybot.aiState.cs(8,34,8,45): error CS0116: A namespace cannot directly contain members such as fields or methods
1>mybot.aiState.cs(9,5,9,6): error CS1022: Type or namespace definition, or end-of-file expected
1>mybot.aiState.cs(11,1,11,2): error CS1022: Type or namespace definition, or end-of-file expected
1>Done building project "mybot.ai.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by lauren-mills** [comment]
Hi @sowsan, this is because the project name is used by the vsix template for the [your-project-name]State.cs class. If you change the name of that class you should be fine. I'll take this note and we'll decide if we want to make a change to that state class in future versions.
