### ISSUE TITLE
VA: User Preferences Store for prefered account for skill actions

### ISSUE THREAD

**Issue by Dewain27** [microsoft/botframework-solutions#40]
The Virtual Assistant needs to have through Onboarding / First time use/ and/or Companion App the ability to allow the user to determine which linked account should be used for a determined skill.

Example:

User can chose to store their ToDos in Outlook Tasks / ToDoist / OneNote

User can chose to use work Email in Office365 and Personal Email in GMail

As linked accounts are added, there should be a dialog that verifies the skills that the user wants to leverage with that linked account to allow the user to change accordingly or to leave them alone.

Example:

User adds a GMail account, they are asked if they want to add this as a work or personal email address default.

User adds a O365 account and user is asked if they want to add as default for ToDos / Email / Work Calendar / Contacts / etc.

**Comment by lauren-mills** [comment]
Aligns with #54

**Comment by lauren-mills** [comment]
Closing to track in #54
