### ISSUE TITLE
Email skill doesn't support sending to addresses with "."

### ISSUE THREAD

**Issue by artakerman** [microsoft/botframework-solutions#406]
**Description**

When trying to send email an email to an address with "." in the address, for example, art.akerman@outlook.com, the code truncates the first word before ".". 

**To Reproduce**

User: send email
Bot: who's email going to?
User: art.akerman@outlook.com
Bot: Alright, I will send this to akerman@outlook.com. What is the email subject?

**Expected behavior**

The solution should keep the same email address as entered. 

**Additional context**

The work-around is to create a contact for this type of email address and use contact name to send emails.

**Comment by DingmaomaoBJTU** [comment]
Please retry with the latest code. This bug should be fixed by change: https://github.com/Microsoft/AI/pull/383
