### ISSUE TITLE
Dynamics 365 business central AL extension development questions

### ISSUE THREAD

**Issue by jackyxu75** [microsoft/botframework-solutions#408]
This question is for check stub report, we want to print check signature to the check with MICR font at bottom (this is a RDLC report). We add field to store check signature file (Blob field in cside) and other fields for MICR information. But looks like the AL disallow me to add Blob field in the page directly, it always show me the error and cannot compile the extension package. Second is related with MICR font file. The MICR font file is an additional file, I don’t think the Dynamics business central online can print the MICR information without the font file installed. 

**Describe the solution you'd like**
Do you have any solution or sample codes for page and table to store picture to bolb field and print rdlc report with special font file?

**Comment by lauren-mills** [comment]
Hi @jackyxu75, it looks like you might have the wrong repository!
