### ISSUE TITLE
Enterprise Template Localization

### ISSUE THREAD

**Issue by hhasenauer** [microsoft/botframework-solutions#423]
**Project**
Enterprise Bot Template

**Description**
The correct Intro.json or MainString.resx is not chosen based on the given locale.

**To Reproduce**
Set the locale in the activity to "de" or "de-DE" with the botframework emulator.
The adaptive card and all texts are still in English.

**Expected behavior**
The correct language is chosen depending on the locale defined in the activity.

**Comment by lauren-mills** [comment]
Checking this out now.

**Comment by lauren-mills** [comment]
Hi @hhasenauer, I'm looking into this now. Which verison of the emulator are you using?

**Comment by hhasenauer** [comment]
I am using version 4.1.0
![image](https://user-images.githubusercontent.com/16212806/49786878-7a2a2600-fd25-11e8-953c-53c96804b310.png)
