### ISSUE TITLE
P0: New adaptive cards for each skill

### ISSUE THREAD

**Issue by lauren-mills** [microsoft/botframework-solutions#43]
- [x] Calendar
- [x] Email
- [x] To Do
- [x] Point of interest
- [x] Virtual Assistant

**Nice to have:** Enable a user to unzip a card "personality pack" into the Virtual Assistant source and have it reflect in the VA's branding. The card assets follow uniform image names & an Adaptive Card host config to enable developers to plug into web chat and show a theme.

**Comment by ryanisgrig** [comment]
Duplicate of #645  - I'm working with Marc on determining assets necessary and finding a uniform layout/style that can be swapped between themes.

**Comment by ryanisgrig** [comment]
Closing - mockups are completed & am tracking progress at #916
