### ISSUE TITLE
Deploy issues.

### ISSUE THREAD

**Issue by jamescarr1988** [microsoft/botframework-solutions#433]
Hi,

I have tried to build the VA bot but it fails. Do I need to build and deploy the enterprise BOT and then deploy the Virtual Assistant over the tp of the Enterprise App,

**Comment by lauren-mills** [comment]
Hi @jamescarr1988 it is not necessary to use the enterprise template first. Can you explain or send a screenshot of the deployment issues you have with Virtual Assistant? Thanks!

**Comment by jamescarr1988** [comment]
Hi Lauren,

i get the error - 

Command failed: luis import application --region westus --appName "Dispatch" --in DeploymentScripts\en\dispatch.luis --a
uthoringKey XXXXX --msbotThe pattern { add a task to shop {ShopContent} } already exists.

Resources exist in Azure but the BOT is not created.

**Comment by jamescarr1988** [comment]
Also, It doesnt seem to be creating all of the resources,

![image](https://user-images.githubusercontent.com/42234236/49935861-1e4cd200-feca-11e8-85cd-4dc89702127b.png)

Thanks for all your help so far.

**Comment by lauren-mills** [comment]
Can you pull the latest and try again? There were some updates to the msbot and ludown tools in the past few days that required some changes on our end to fix this error. 

Also, make sure you’re using the deploy_bot.ps1 script instead of msbot clone on its own.

**Comment by jamescarr1988** [comment]
Ok. I have done the following,
Cloned the repo
Loaded the AI\solutions\Virtual-Assistant\src\csharp\VirtualAssistant.sln in Visual Studio 2017 and built the solutions. 
I then, using powershell navigated to AI\solutions\Virtual-Assistant\src\csharp\assistant\DeploymentScripts and ran the Deploy_Bot.ps1
This ran and then I got the following error 

az bot create -g CorpBot --name CorpBot --kind webapp --location westus --insights-location "West US 2" --subscription 3
XXXXXXXXXXXXXXXXX --version v4 --lang CSharp exit code: 1
WARNING: To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code XXXXXXX t
o authenticate.
ERROR: Unable to provision Microsoft Application automatically. To manually provision a Microsoft Application, go to the
 Application Registration Portal at https://apps.dev.microsoft.com/. Once you manually create you application, pass the
application Id and password as parameters for bot creation.

I then tried to run deploy_bot.ps1 --appId"xxxxxx" --appSecret "xxxxxx" and this fails

**Comment by lauren-mills** [comment]
This is probably due to the name of your bot not being unique. Please try with a different name and let me know how it goes.

**Comment by jamescarr1988** [comment]
So shall I name the bot something totally random?

**Comment by lauren-mills** [comment]
It doesn't have to be random. What I typically do is pick something descriptive like "VirtualAssistant" and then append something specific like a company acronym, or my initials, or a date. Something like "MSFTVirtualAssistant1218" as an example.

**Comment by lauren-mills** [comment]
You can change the display name of your bot after it's created as well.

**Comment by jamescarr1988** [comment]
Ah ok. Shall I name the the app under https://apps.dev.microsoft.com the same?

**Comment by lauren-mills** [comment]
That app registration doesn't have to be unique, so you can use the one you created earlier.

**Comment by jamescarr1988** [comment]
Im really sorry but still getting this error,

ERROR: Unable to provision Microsoft Application automatically. To manually provision a Microsoft Application, go to the
 Application Registration Portal at https://apps.dev.microsoft.com/. Once you manually create you application, pass the
application Id and password as parameters for bot creation.

**Comment by lauren-mills** [comment]
And you're passing in the -appId and -appSecret still?

**Comment by jamescarr1988** [comment]
I did try by running from the following location - AI\solutions\Virtual-Assistant\src\csharp\assistant\DeploymentScripts>

The ran .\deploy_bot.ps1\ --appId "XXXX" -- appSecret "xxxxx"

I then get a region not recognised error as its passing the App id as region

then this error

Invoke-Expression : At line:1 char:169
+ ... ripts\generate_deployment_scripts.ps1 -locale xnbdRHTP8726!pbrWXF3({~
+                                                                        ~
Missing closing '}' in statement block or type definition.
At line:1 char:171
+ ... ripts\generate_deployment_scripts.ps1 -locale xnbdRHTP8726!pbrWXF3({~
+                                                                          ~
Missing closing ')' in expression.
At C:\Users\james.carr\source\repos\BOT\AI\solutions\Virtual-Assistant\src\csharp\assistant\DeploymentScripts\deploy_bo
t.ps1:36 char:2
+     Invoke-Expression "$($PSScriptRoot)\generate_deployment_scripts.p ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ParserError: (:) [Invoke-Expression], ParseException
    + FullyQualifiedErrorId : MissingEndCurlyBrace,Microsoft.PowerShell.Commands.InvokeExpressionCommand

**Comment by lauren-mills** [comment]
A few things I'm seeing: 
- You should only use one hyphen for the parameters since this is a powershell script. (i.e. "-appId" instead of "--appId")
- It looks like your secret may have special characters that need to be escaped. Try adding `  in front of the curly brace and parenthesis and see if it will accept it.

**Comment by darrenj** [comment]
Thanks @jamescarr1988 for working through this, let us know if you have managed to complete. We've just undergone a big deployment tooling change to enable multi-language support ahead of our release next week.

**Comment by jamescarr1988** [comment]
Thank you so much for all you help, its up and running.
