### ISSUE TITLE
Virtual Assistant Error: The given key 'iv' was not present in the dictionary.

### ISSUE THREAD

**Issue by kendomen** [microsoft/botframework-solutions#442]
**Project**

VirtualAssistant

**Description**

After a clean deployment, CultureInfo returns "iv" and then blows.

**To Reproduce**

Rebuild and deploy latest.

**Expected behavior**

It shouldn't blow

**Screenshots**

**Additional context**

**Comment by lauren-mills** [comment]
Hi @kendomen, which channel are you using? If this is in the emulator, which version are you using so I can try to repro?

**Comment by lauren-mills** [comment]
Looks like this happens when the locale field is empty in the emulator. "iv" is for invariant culture so when we get this we should fall back to the defaultLocale in appsettings

**Comment by kendomen** [comment]
I'm using the emulator 4.2.0.  

Default local is specified in appsettings.json
 "defaultLocale": "en-us",

and this still happens
