### ISSUE TITLE
some LUIS intent results are not accurate

### ISSUE THREAD

**Issue by KayMKM** [microsoft/botframework-solutions#45]
**Description**
As designed, the user input "more" should be recognized as "ShowNext" intent. But now it is "Confirm" intent. So users can't see the next page meetings by inputting "more".

**To Reproduce**
1. input "what are my meetings today?"
2. input "no"
3. input "more"

**Expected behavior**
Bot will show the next page meetings.

**Comment by lauren-mills** [comment]
@darrenj This is feedback for the pre-built domain models.

**Comment by lauren-mills** [comment]
This should be closed by the #170  .

Feel free to reopen if not.
