### ISSUE TITLE
As a developer, I would like to have a class library for Productivity skills that I can reference so I don't have to dupicate the logic for accessing mail, contacts, appointments, etc.

### ISSUE THREAD

**Issue by gabog** [microsoft/botframework-solutions#450]
**Describe the solution you'd like**
When the user says, "What can I do in the car while driving" I would like to create an adaptive card that shows the user's meetings, todos and also some other custom things the user can do (based on some other services, like do an oil change for example). 

The Calenar and To Do skills provide this infromation in isloation. 

In order to build this aggregate, I will need to duplicate the services code used to access the configured email, calendar and to do providers.

**Describe alternatives you've considered**
Copying and pasting skills code in my agregated skill.
Write my own version of the services code.
I could avoid this if f the ServicesClients namespace in each skill was provided as a separate dll that I can reference to create custom agregations.

**Comment by lzc850612** [comment]
This is a feature we do not support now. 

The right approach should be VA sends a message (an event) to all skills asking for response for particular scenarios, in this case something the customer can do in the car while driving. It should be up to the skill to decide what the skill wants to support, depending on different scenario (events).

**Comment by darrenj** [comment]
tracked
