### ISSUE TITLE
As a PowerBI developer, I would like TelemetryLuisRecognizer to log the LUIS AppId so I can write reports that I can segment intents per LUIS model

### ISSUE THREAD

**Issue by gabog** [microsoft/botframework-solutions#452]
**Describe the solution you'd like**
In addition to the the existing properties being logged by TelemetryLuisRecognizer, I need an additional property for the LUIS APP ID so I can segment my reports by LUIS App.

**Describe alternatives you've considered**
None

**Comment by lzc850612** [comment]
This seems to be a reasonable ask. I'll add it

**Comment by gabog** [comment]
Thanks Ted, I have a very similar request for QnAMaker, do you want me to create another feature request? or can it be addressed as part of this one?

Thanks again.

**Comment by lzc850612** [comment]
Please create another feature request so they are tracked separately. I might still put them in the same PR.

**Comment by gabog** [comment]
Done
