### ISSUE TITLE
Is there specific design purpose for the local folder of lu file being language code only vs full LCID string?

### ISSUE THREAD

**Issue by dawwa** [microsoft/botframework-solutions#457]
Wondering if there is case we concern about the full LCID string, e.g., "us" part of "en-us"

So far, all the code seems only concerning the language code.

For example: 

- The *.lu files container folder is "en" instead of "en-us".
`https://github.com/Microsoft/AI/tree/master/solutions/Virtual-Assistant/src/csharp/assistant/CognitiveModels/LUIS`**/en**

- And the tool scripts seems always only concerning about the language code.
[https://github.com/Microsoft/AI/blob/master/solutions/Virtual-Assistant/src/csharp/assistant/DeploymentScripts/generate_deployment_scripts.ps1](generate_deployment_scripts.ps1)
**$langCode = ($locale -split "-")[0]**

- The bot file generated also only uses language code part.
[https://github.com/Microsoft/AI/blob/master/solutions/Virtual-Assistant/src/csharp/assistant/DeploymentScripts/update_published_models.ps1](update_published_models.ps1)
**$langCode = $botFileName.Substring($botFileName.Length - 2, 2)**

**Comment by lauren-mills** [comment]
Hi @dawwa, the main reason for using only the language code is for cases when different locales map to the same language. For instance, en-gb and en-us would both be using the same English services and responses in our current implementation. That being said, for a more complicated scenario you could use the full string to have different behavior/responses depending on the country code. It’s simpler at this point to use one configuration per language.
