### ISSUE TITLE
PowerBI Dashboard - No conversation details

### ISSUE THREAD

**Issue by ghost** [microsoft/botframework-solutions#475]
Hello,

if I open the template with the actual Desktop PowerBI and enter the AppInsight AppID, I can see data in Overall Usage and Demographics, but e.g. in Conversations Drill Down I get not the messages. What should I do to get as well the detailed messages?
<img width="480" alt="capture" src="https://user-images.githubusercontent.com/24620337/50238299-499a5a00-03bf-11e9-8e20-104f98dd7507.PNG">

**Comment by ryanisgrig** [comment]
Hi David, is this using the Enterprise Template? What version of the Bot Builder SDK is it using?
We have an updated being published shortly, which should have the correct telemetry configured to work with the Power BI sample.

**Comment by ghost** [comment]
Hello, Ryan, 

I use the Virtual Assistant Template: https://github.com/Microsoft/AI/tree/master/solutions/Virtual-Assistant

Bot Builder SDK is 4.1.15.

In Azure it seems that the detailed messages are available.

<img width="709" alt="captureacitvity" src="https://user-images.githubusercontent.com/24620337/50239992-e5c66000-03c3-11e9-9038-c8cc37ba6718.PNG">


<img width="169" alt="capturebotbuilder" src="https://user-images.githubusercontent.com/24620337/50239975-de06bb80-03c3-11e9-9b01-4f1b1a809b6b.PNG">

**Comment by ghost** [comment]
I dont't know if it helps, but I'm located in Germany. But I have EN set-uped in Windows 10.  Further, I get DataFormatErrors for the field  Data.

<img width="518" alt="capturedataerrors" src="https://user-images.githubusercontent.com/24620337/50274899-7477c300-043e-11e9-822e-3f0840fa4b12.PNG">

**Comment by ghost** [comment]
I think the label "question" is wrong. i think it could be a bug or the documentation (HowTo set-up with Virtual Assistant) is missing.

**Comment by ryanisgrig** [comment]
The Power BI sample is released with Virtual Assistant updates in the 4.2 SDK (see #438 for details and #448 for latest fixes). Try testing with that.

You may still see a problem with the conversationalai date problem (`en-gb` is reported as well), but the EventTelemetry table will be populated using the schema from 4.2.

**Comment by ghost** [comment]
Hello @ryanlengel I deployed the newest VA at my private (Pay-As-To-Go) Azure subscription. But now I get an error message. (I works with the subscription of my company.) So I assume I need to do with my private Azure subscription to use PowerBI to collect the AppInsight Data, right? What? Thank you.
<img width="377" alt="capture" src="https://user-images.githubusercontent.com/24620337/52128110-581d9780-2634-11e9-8004-55dd0324bda0.PNG">
