### ISSUE TITLE
As an Azure admin, I would like to consolidate cosmosDb state collections for the inproc skills in my assistant to optimize resources and save $

### ISSUE THREAD

**Issue by gabog** [microsoft/botframework-solutions#482]
Each skill creates its own CosmosDb collection based on the skillDefinition.Name attribute. on an OOTB assistant, this results in 5 different collections (the screenshot below includes my own custom reciepsSkill so ignore that one)

![image](https://user-images.githubusercontent.com/12264946/50298943-5ca83b00-044e-11e9-9a99-5ec2273ec3aa.png)

By default, each collections is created using 1000 RU/S which translates roughly to $288 a month in storage cost (1.92 * 30 * 5), or $57.6 a month per skill.

![image](https://user-images.githubusercontent.com/12264946/50299072-ad1f9880-044e-11e9-814e-d886a39d1a72.png)

**Describe the solution you'd like**
Ideally, we would like for all the skills that are running in proc to use the same cosmos DB collection so we can only use one and reduce my TCO.

**Describe alternatives you've considered**
We considered forcing the skills to use the same collection but it seems this is set in code inside SkillDialog and we don't have access to that. 
We also don't know if the different skills are namespacing the state properties they use so there may be collisions if they are not.

**Comment by darrenj** [comment]
Addressed with remote skills
