### ISSUE TITLE
[Web Test] Onboarding dialog is triggered on each new conversation with same user id

### ISSUE THREAD

**Issue by ryanisgrig** [microsoft/botframework-solutions#484]
**Project**

Virtual Assistant

**Description**

In Direct Line scenarios (web chat, speech), the onboarding dialog is triggered each new conversation. This is because the Direct Line `conversationUpdate` uses a different ID as `from.Id`, rather than the user id passed in. In demo scenarios, this requires the user to have to follow this dialog each time.

**To Reproduce**

https://aka.ms/bfvirtualassistant 
Log in with an MSA account and go to Web Chat. Answer the onboarding questions and refresh the page. The onboarding dialog will be triggered again, even though the user has been passed via Direct Line.

**Expected behavior**

The onboarding dialog should only be triggered the first time, in the same way it works in the emulator.

**Screenshots**

**Additional context**

We should check for other channels that may exhibit similar behavior.

**Comment by darrenj** [comment]
We've changed onboarding dialog logic
