### ISSUE TITLE
Unable to add generic connection to bot file

### ISSUE THREAD

**Issue by gabog** [microsoft/botframework-solutions#485]
**Project**
Virtual Assistant

**Description**
Hi, I am trying to add the AAD connection to my bot file from powershell and I am getting "SyntaxError: Unexpected token \ in JSON at position 1".

I am running the following command (that I copied and pasted from https://github.com/Microsoft/AI/blob/master/solutions/Virtual-Assistant/docs/virtualassistant-createvirtualassistant.md and just updated the connection name)

    msbot connect generic --name "Authentication" --keys "{\"Azure Active Directory v2\":\"Azure Active Directory v2\"}" --bot GGVADevMaster.bot --url "portal.azure.net"

**To Reproduce**
1. Ensure your bot file is unencrypted and it doesn't contain the generic connection for authentication.
2. Run the command specified above from powershell and you'll get:
![image](https://user-images.githubusercontent.com/12264946/50311081-f59c7d80-0471-11e9-8cf4-39b9ac8937e5.png)

**Expected behavior**
I would like to be able to add the connection from the command line as described in the documentation.

**Additional context**
As a workaround, I manually edited the bot file and added the following json fragment:

    {
      "type": "generic",
      "configuration": { "Azure Active Directory v2": "Azure Active Directory v2" },
      "name": "Authentication",
      "url": "portal.azure.net"
    }

Is this a bug? or am I doing something wrong?

**Comment by lauren-mills** [comment]
I think the key here might be Powershell having different escape characters. I usually use command prompt. I'll try it out and see if I can repro.

**Comment by lauren-mills** [comment]
I am able to repro. It works correctly in command prompt and gives the error in PS. I tried the string several different ways and haven’t gotten it working yet in PowerShell.

**Comment by gabog** [comment]
K, thanks, it does also work for me from command prompt (I normally use PS).

Regarding PS, I tried the PS option (with variables) and I get "Missing URL" (probably something with the quotes also)

![image](https://user-images.githubusercontent.com/12264946/50315181-ad845780-047f-11e9-971d-4d6d03358aa5.png)

**Comment by lauren-mills** [comment]
This issue provides a workaround for PS #191 

I'll add this to known issues in the meantime.

**Comment by progutskyi** [comment]
Mentioned workaround didn't work for me. After messing with this for a few hours I've found the working solution:

`msbot connect generic --bot MyBot.bot --url https://westeurope.api.cognitive.microsoft.com --keys '{\"subscriptionKey\":\"some_key\"}' --name Name`

Json should be wrapped in `''` and all properties should have `""` properly escaped with `\` and **no spaces in JSON if used from cmd**

**Comment by lauren-mills** [comment]
This works for me in PowerShell:

```
msbot connect generic --name Authentication --url portal.azure.com  --% --keys "{\"O365\":\"Azure Active Directory v2\"}"
```
