### ISSUE TITLE
Unable to create ToDo skill from VA

### ISSUE THREAD

**Issue by gabog** [microsoft/botframework-solutions#491]
**Project**
Virtual Assistant, Skills (ToDo)

**Description**
I am getting a "Constructor on type 'ToDoSkill.ToDoSkill' not found." exception when trying to create a ToDo item from the main VA bot.

From looking the source, it seems that @feich-ms  added MailService to the ToDoSkill constructor and the activator from SkillDialog is failing.

        public ToDoSkill(ISkillConfiguration services, ConversationState conversationState, UserState userState, IBotTelemetryClient telemetryClient, ITaskService serviceManager = null, IMailService mailService = null, bool skillMode = false)

**To Reproduce**
1. Pull the latest from master.
2. Start the emulator and say "add milk to my to do list"
You'll get a "Sorry, something went wrong." message.

**Expected behavior**
I would like to be able to add To Dos from the Virtual Assistant.

**Screenshots**
Exception in SkillDialog
![image](https://user-images.githubusercontent.com/12264946/50349423-bf124180-0509-11e9-8089-a536da551ff8.png)

Error en emulator
![image](https://user-images.githubusercontent.com/12264946/50349454-d2251180-0509-11e9-8cc3-50df4c8683e5.png)

**Comment by lauren-mills** [comment]
Closed by #492
