### ISSUE TITLE
Update Enterprise Bot documentation for latest msbot prereqs

### ISSUE THREAD

**Issue by lauren-mills** [microsoft/botframework-solutions#516]
**Project**

Enterprise Bot Template

**Description**

Latest msbot no longer requires the botservice extension to az cli. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by lauren-mills** [comment]
Updated in public docs

**Comment by hansmbakker** [comment]
@lauren-mills this is still on lines 20-22 in https://github.com/Microsoft/AI/blob/master/templates/Enterprise-Template/src/csharp/EnterpriseBotTemplate/Bot%20Framework/readme.md and in https://github.com/Microsoft/AI/blob/master/templates/Enterprise-Template/src/csharp/EnterpriseBotSample/readme.md
