### ISSUE TITLE
LUIS Intent Information within Power BI dashboard

### ISSUE THREAD

**Issue by garypretty** [microsoft/botframework-solutions#517]
I was sure the Power BI dashboard previously included LUIS telemetry information - e.g. popular intents triggered, scores etc.  Has this been removed?  I have just looked at the latest template but can only see QnA Maker info?

**Comment by ryanisgrig** [comment]
I checked the previous Power BI template and it does not have LUIS telemetry, but we will look into providing LUIS insights.
