### ISSUE TITLE
Update the projects to .Net Core 2.2

### ISSUE THREAD

**Issue by pvmraghunandan** [microsoft/botframework-solutions#526]
**Is your feature request related to a problem? Please describe.**
Update the projects to .Net Core 2.2 so that we can leverage new features like Health Monitoring. https://docs.microsoft.com/en-in/aspnet/core/host-and-deploy/health-checks?view=aspnetcore-2.2 

**Describe alternatives you've considered**
Upgrade manually

**Additional context**
We are planning to use Health Checks for validating endpoints we are dependent on. Need an upgrade to projects and all dependent Nugets

**Comment by lauren-mills** [comment]
We will be making this update to all projects as soon as there is support from the Azure DevOps pipelines. https://github.com/Microsoft/azure-pipelines-image-generation/issues/512
