### ISSUE TITLE
General Issues after Updating Virtual Assistant

### ISSUE THREAD

**Issue by ghost** [microsoft/botframework-solutions#535]
**Project**
Virtual Assistant, Skills

**Description**
This project is amazing for me. It helps me a lot to build a bot. 

After my first try out of Virtual Assistant of version December, I was able to run the bot fully. 

Yesterday I tried to deploy from scratch with a fresh clone of the repository but it failed.

The reasons for failing were very different. Some were releated to not yet updated documentation and others were related to changes within Azure like application registration which seems to be replaced by another workflow in the azure Portal, and the documentation doesn't point out exactly on how do it there. On the other Hand there is issue Access Tokens which means the bot itself is not able to receive an access token stated by an error Code 401. 

I was able to run the new bot locally, by removing the application ID and secret from the bot file. The remote bot never worked, nor by removing appID and secret then by publishing it.

One important feature, adding a new skill using the delivered Skill template did also not work. After adding to the solution VirtualAssistant ensuring all dependencies are set I was never able to built it due to several different differences between necessary configurations and so on.

**To Reproduce**
Clone the repository and start with a clean resource group and new App ID and a clean LUIS following the install guideline.

**Expected behavior**
Bot should remotely with a new added skill.

**Comment by lauren-mills** [comment]
HI @David201406 can you give any more specifics on the steps or docs you followed that were incorrect? Any error messages you received or stack traces will also help us to fix the issues.

As for the skill template, it is in the process of being updates. You can track the progress here: #394

**Comment by Zerryth** [comment]
@David201406, could you please answer Lauren's question with regards to what docs you're following?

I was able to successfully follow the documentation on getting started [here ](https://github.com/Microsoft/AI/blob/master/solutions/Virtual-Assistant/docs/virtualassistant-createvirtualassistant.md)and deployed the bot without problem of having to "remov[e] the application ID and secret from the bot file" as you described.

In fact, I had _added_ the `secret` to the  and `instrumentation key` to the `appsettings.json` file and _added_ the correct path for the 2nd `.bot` file that contains references to your language models used--not remove

**Comment by ghost** [comment]
@Zerryth, I followed the documentation started [here](https://github.com/Microsoft/AI/blob/master/solutions/Virtual-Assistant/docs/virtualassistant-createvirtualassistant.md).

**My actions**:
+ I run Windows 10 client
+ Node.js has version 10.13.0
+ I updated Visual Studio to 15.9.5
+ I updated .Net Core to 2.2.103
+ I installed Azure Bot Service to msbot 4.3.2 and luisgen 2.0.2
+ I installed Azure CLI 2.0.55
+ I cloned Virtual Assistant with git clone git clone https://github.com/Microsoft/AI.git
+ I got the LUIS AuthoringKey from www.luis.ai
+ I registered an app at https://github.com/Microsoft/AI/blob/master/solutions/Virtual-Assistant/docs/virtualassistant-createvirtualassistant.md and get and saved appID and AppSecret
+ I opened VisualAssistant.snl in Virtual-Assistant\src\cscharp and build solution without error
+ I executed following commands in CMD, not Powershell) in Virtual-Assistant\src\csharp\assistant:
    - az login (I have only one subscription)
    - PowerShell.exe -ExecutionPolicy Bypass -File DeploymentScripts\deploy_bot.ps1 -appId     "d92ac???????????????52b13cd" -appSecret "jdji????????????????YZV)=#"
- I entered west us as location and a unique name ZAAE009AF

**Part of the output**:
cmdlet deploy_bot.ps1 at command pipeline position 1
Supply values for the following parameters:
name: ZAAE009AF
location: westus
luisAuthoringKey: 839762??????????????11ac
Changing to project directory ...
Deploying common resources...
' --force' is not recognized as an internal or external command,
operable program or batch file.
Generating en-us General script ...
Generating en-us Calendar script ...
Generating en-us Email script ...
Generating en-us ToDo script ...
Generating en-us PointOfInterest script ...
Generating en-us FAQ script ...
WARNING: 17 duplicate utterances found in
C:\Projects\ZAAE008\AI\solutions\Virtual-Assistant\src\csharp\assistant\DeploymentScripts\..\CognitiveModels\QnA\en\faq.lu. This could cause
issues in your model accuracy.
Generating en-us Dispatch script ...
Deploying en-us resources...

**Result**:
- deploy_bot.ps1 goes though but do not show "secret in purple text"
- it creates LUIS apps but only following azure services:
ZAAE009AFen | App Service plan | West US |  
ZAAE009AFen-LUIS | Cognitive Services | West US |  
ZAAE009AFen-qnahost | App Service | West US |  
ZAAE009AFen-QnAMaker | Cognitive Services | West US |  
zaae009afen-search

**Comment by lauren-mills** [comment]
Hi @David201406, these issues are likely caused by the appId and secret containing special characters that need to be escaped. The '#' is a comment character in PowerShell and should be escaped with a '`' (backtick). Please try this out and let us know. This will help us to update the docs

**Comment by Zerryth** [comment]
What @lauren-mills says is true regarding escaping characters

However you should actually be able to do follow through with getting the "secret in purple text" but only just running the PowerShell script, skipping the "I registered an app at https://github.com/Microsoft/AI/blob/master/solutions/Virtual-Assistant/docs/virtualassistant-createvirtualassistant.md and get and saved appID and AppSecret" you described
___
So, if you want to start _completely_ from scratch as you have implied in your original post, you can also try these following steps (make sure you don't have any remnant LUIS services that had been created from previously trying to go through deployment)

1. **clone** the repo `https://github.com/Microsoft/AI.git`
2. In CMD terminal, **navigate** down to the folder, `AI\solutions\Virtual-Assistant\src\csharp\assistant`
    * this folder should contain the `VirtualAssistant.csproj` file
3. **Login** (`az login`) or check that you've logged in (`az account show`), since you've already done this step previously
4. Inside the `assistant` folder you've navigated to, run the command to provision the required services and deploy your Virtual Assistant to a resource group in Azure portal
    **`PowerShell.exe -ExecutionPolicy Bypass -File DeploymentScripts\deploy_bot.ps1`**
    
    * This command will guide you via prompts to enter a unique `name` of your bot and resource group, `location` (e.g. "westus"), and LUIS `Authoring Key`.
    * Also note that this will prompt you to **log in via web browser**

5. **Continue following instructions** in https://github.com/Microsoft/AI/blob/master/solutions/Virtual-Assistant/docs/virtualassistant-createvirtualassistant.md regarding `.bot` files and `appsettings.json`
___
Try the steps above, and let us know the results

**Comment by ghost** [comment]
Hi @lauren-mills , which special characters should  I avoid or escape? It seems that not only # is problematic.

**Comment by ghost** [comment]
Hi @Zerryth , if I do not give appId and appSecret I get Message ‚ERROR: Unable to provision MSA id automatically. Please pass them in as parameters and try ‘

**Comment by Zerryth** [comment]
Hmm..that seems more like a problem with the `az bot create` command to me. I'll try updating to `2.0.55` as you have done to try to repro your issue (I'm using `az cli 2.0.54`)

**Comment by ghost** [comment]
@Zerryth ‚ERROR: Unable to provision MSA id automatically. Please pass them in as parameters and try’ seems to be old Problem, because i got it as well in December.

**Comment by Zerryth** [comment]
@David201406 still looking into the matter as to why it's giving you an error when you try to run the PowerShell.exe command without them, but I'm curious if you see the following when you ran the command _with_ the `appId` and `appSecret` parameters:

 In [Azure portal](https://ms.portal.azure.com/#)  > Resource Group of your Virtual Assistant > Deployments (left-hand side of menu under Settings)

Do you see anything in the **Deployments** section? 
* if so, click on the deployment name > Inputs > BOTFILEENCRYPTIONKEY

![image](https://user-images.githubusercontent.com/35248895/51557994-3aca1b80-1e33-11e9-8a7e-b74909edd9d4.png)


This is another way to find your bot file secret, if you are not getting the purple text output in your terminal, assuming it actually deployed...

**Comment by lauren-mills** [comment]
@David201406 try adding this before your secret "--%"

Like this:

`.... --% --appSecret "YOUR_SECRET"`

**Comment by ghost** [comment]
.... --% --appSecret "YOUR_SECRET" fixed appSecret issue. 

Entering EN_US in the local field of the emulator fixed as well the issue with missing onboarding message.

Thank you a lot.

**Comment by Zerryth** [comment]
Lauren closed this issue, as David has gotten passed the issue.

To track progress on the other issue regarding not being able to provision MSA id automatically, see botbuilder-tools repo issue here: https://github.com/Microsoft/botbuilder-tools/issues/813
