### ISSUE TITLE
P1: User Profile store

### ISSUE THREAD

**Issue by lauren-mills** [microsoft/botframework-solutions#54]
Move User Profile Information (timezone, name, email, news topics, etc.) out of the BF state work. We can likely use the same cosmosdb but a different section

**Comment by hansmbakker** [comment]
Is this also applicable to Enterprise Bot Template?

I noticed that the Dialog's state is stored in a part of the UserState using
```csharp
_userState.CreateProperty<OnboardingState>(nameof(OnboardingState))
```
(example from https://github.com/Microsoft/AI/blob/master/templates/Enterprise-Template/src/csharp/EnterpriseBotSample/Dialogs/Main/MainDialog.cs#L33).

However I want to be able to access this state in other contexts, too. What is the recommended way to do this?

Just adding the `OnboardingState` to all other Dialogs feels not the best option.

**Comment by lauren-mills** [comment]
From #40

>The Virtual Assistant needs to have through Onboarding / First time use/ and/or Companion App the ability to allow the user to determine which linked account should be used for a determined skill.
>Example:
>User can chose to store their ToDos in Outlook Tasks / ToDoist / OneNote
>User can chose to use work Email in Office365 and Personal Email in GMail
>As linked accounts are added, there should be a dialog that verifies the skills that the user wants to leverage with that linked account to allow the user to change accordingly or to leave them alone.
>Example:
>User adds a GMail account, they are asked if they want to add this as a work or personal email address default.
>User adds a O365 account and user is asked if they want to add as default for ToDos / Email / Work Calendar / Contacts / etc.

**Comment by lauren-mills** [comment]
@hansmbakker There are no plans as of now to add a user store to the enterprise bot beyond the state implementation, because customers would likely already have another user store for their users. 

That being said, the OnboardingState is just an example of how to use state, and you could modify it to instead be UserProfile and update it in the onboarding dialog but access it anywhere you want from UserState.
