### ISSUE TITLE
[POI] Provide radius value to GeoSpatialProvider to limit results

### ISSUE THREAD

**Issue by ryanisgrig** [microsoft/botframework-solutions#576]
**Is your feature request related to a problem? Please describe.**
When using fuzzy search, sometimes results may be outrageously away from the current location.

**Describe the solution you'd like**
Developers can enable the radius with an optional configuration setting. This value is in meters and will be passed on in the radius URL parameter to Azure Maps. Results will now be limited to POIs X meters away.

**Additional context**
Related to #449

**Comment by darrenj** [comment]
Also means we can remove country from search addressing #449
