### ISSUE TITLE
[Virtual Assistant]Provide a way to inject external dependencies while intializing Skill

### ISSUE THREAD

**Issue by vvaibhav-msft** [microsoft/botframework-solutions#579]
**Is your feature request related to a problem? Please describe.**
In VirtualAssistant.sln -> Microsoft.Bot.Solutions -> SkillDialog.cs
the skills are initialized using reflection as follows
_activatedSkill = (IBot)Activator.CreateInstance(skillType, skillConfiguration, conversationState, userState, _telemetryClient, null, true);

If I have any external dependencies which I want to resolve and use inside my skill, currently I am having to pass **IServiceProvider** container as follows.

_activatedSkill = (IBot)Activator.CreateInstance(skillType, skillConfiguration, conversationState, userState, _telemetryClient, null, true, **_serviceProvider**); 

**Describe the solution you'd like**
Please provide a mechanism to inject external dependencies into the Virtual Assistant framework so that I can use it to pass all my external dependencies into skill.

@gabog FYI
**Describe alternatives you've considered**

**Additional context**

**Comment by lzc850612** [comment]
Thanks for raising this issue. Can you elaborate on what types of dependencies you are trying to pass over to skills?

**Comment by vvaibhav-msft** [comment]
For ex. we are passing ILogger, IUrlResolver, IUserService.

**Comment by lzc850612** [comment]
The second parameter in the reflection call skillConfiguration is the configuration objects that contains various services needed for skills:

_activatedSkill = (IBot)Activator.CreateInstance(skillType, skillConfiguration, conversationState, userState, _telemetryClient, null, true);

You can extend the implementation of type SkillConfiguration to include the types of services you want to pass on to the skills. You also need to configure the settings you need for those dependencies accordingly in appsettings.json for different skills. Please refer to the current shape of appsettings.json. we use this approach to pass configuration/dependencies needed to the skills. 

For your requirements, you should be able to configure the necessary settings in appsettings.json, and then extend the SkillConfiguration type to include logic to instantiate different dependencies using the configurations and pass that over so the skills can get them and use them

**Comment by vvaibhav-msft** [comment]
Thanks Ted, let me try that out.

**Comment by gabog** [comment]
I need to think more about this one but I believe it would be good to provide a way of resolving services through dependency injection rather than relying on specialized types and having to recast them to the desired type inside the skills, I think that adding more DI support would also simplify testing.

**Comment by hansmbakker** [comment]
@gabog I believe this is an issue in the Bot Framework SDK itself; I added a reference to https://github.com/Microsoft/botbuilder-dotnet/issues/1188.

**Comment by darrenj** [comment]
New template and skill approach moves to DI fully and skills are remoted too
