### ISSUE TITLE
[Enterprise Bot Template][C#] Feedback on readme.md

### ISSUE THREAD

**Issue by hansmbakker** [microsoft/botframework-solutions#587]
Feedback:

- [ ] `az botservice` is not needed anymore, it is already removed from the docs (https://github.com/Microsoft/AI/pull/542) but not from the readme in https://github.com/Microsoft/AI/blob/master/templates/Enterprise-Template/src/csharp/EnterpriseBotTemplate/Bot%20Framework/readme.md and in https://github.com/Microsoft/AI/blob/master/templates/Enterprise-Template/src/csharp/EnterpriseBotSample/readme.md
- [ ] The reference to the LUIS portal does not mention that there are multiple portals and that you should use the portal that belongs to your region. Otherwise you get issues with your authoring keys (see https://github.com/Microsoft/AI/blob/87c033bde9dd1e7b55cc03fa7ec7474acd36ed29/solutions/Virtual-Assistant/docs/virtualassistant-createvirtualassistant.md#L76)
- [ ] The readme seems to assumes that people use `cmd.exe`. When using e.g. PowerShell, passing the `appSecret` in `msbot clone services` results in an error.

**Comment by lauren-mills** [comment]
1. Update the readme in the Enterprise Bot template and Enterprise Bot Sample to point to the public docs site for one source of docs.
2. I will add this to the backlog
3. This is likely causes by characters in the secret needing to be escaped for Powershell. I will check it out and add to known issues.

**Comment by hansmbakker** [comment]
1. I noticed that it also applies to Customer Service Bot
2. Thanks!
3. Please see the bottom of https://github.com/Microsoft/botbuilder-tools/blob/master/packages/MSBot/docs/export-clone.md for the solution.

**Comment by lauren-mills** [comment]
Enterprise Docs PR: https://github.com/MicrosoftDocs/bot-docs-pr/pull/1287

**Comment by lauren-mills** [comment]
Closing. 

1. The readmes in the project have been updated to refer to the public docs
2. Public docs include info about different LUIS portals for different regions (https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-enterprise-template-deployment?view=azure-bot-service-4.0#configuration)
3. Docs are updated to include details on using different command line tools (https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-enterprise-template-deployment?view=azure-bot-service-4.0#deployment)
