### ISSUE TITLE
[Enterprise Bot Template][C#] VSIX uses project name for bot class name

### ISSUE THREAD

**Issue by hansmbakker** [microsoft/botframework-solutions#596]
The Enterprise Bot Template extension uses the project name as the bot class name.

If you are used to use dots (`.`) in your project name, then the generated code will not compile.

Imagine your project name is something like `CompanyName.DepartmentName.BotName` then the bot class name will also be `CompanyName.DepartmentName.BotName` which is not allowed.

**Comment by lauren-mills** [comment]
We will not be changing this as of right now. If you have a specific need beyond wanting to have the dots in the name please give more background or propose the exact changes you would like.

**Comment by hansmbakker** [comment]
Well, it is common to prefix C# projects at least with a company name (like CompanyName.ProjectName), and it is common to have multiple projects in a solution share a prefix separated with a dot.

Also see the names of nuget packages for example (NewtonSoft.Json, etc).

This results in uncompilable code now as explained above.

**Comment by lauren-mills** [comment]
I'll add it as a line item for our next round of updates

**Comment by hansmbakker** [comment]
Thank you!
