### ISSUE TITLE
[Enterprise Bot Template] Several QnA Maker instances created while it can be hosted in one?

### ISSUE THREAD

**Issue by hansmbakker** [microsoft/botframework-solutions#612]
In the Enterprise Bot Template I see that now several instances of Cognitive Services and QnA Maker are provisioned when running `msbot clone services`, including one Azure Search (Standard) instance per QnA Maker instance.

I believe this would not be needed if you use one QnA maker instance with multiple knowledge bases rather than multiple QnA maker instances.

Is there a rationale behind this choice? The costs of having multiple Azure Search (Standard) instances are high, and I do not believe those costs are justified well - does chitchat functionality really need to be served by a separate instance???

**Comment by lauren-mills** [comment]
This is due to constraints in the current tools. Current issue reported here: https://github.com/Microsoft/botbuilder-tools/issues/826

**Comment by lauren-mills** [comment]
Completely agree with your concerns, and there is work underway that should help us in upcoming releases. There are other options if you want to move away from using the tools in your code today, including ARM templates combined with the qnamaker CLI.

**Comment by lauren-mills** [comment]
ARM template deployment is coming soon.
