### ISSUE TITLE
Authentication flow sometimes results in a null reference

### ISSUE THREAD

**Issue by ryanisgrig** [microsoft/botframework-solutions#622]
**Project**

Virtual Assistant

**Description**

In `MultiProviderAuthDialog.cs`, line 136, sometimes the result is null even with the correct value submitted. This causes the following error:
```
Virtual Assistant Error: Object reference not set to an instance of an object. |    
at Microsoft.Bot.Solutions.Authentication.MultiProviderAuthDialog.<>c__DisplayClass6_0.<CreateProviderTokenResponse>b__0(TokenStatus t) 
in C:\\chatbot\\VirtualAssistant\\solutions\\Virtual-Assistant\\src\\csharp\\Microsoft.Bot.Solutions\\Authentication\\MultiProviderAuthDialog.cs:line 145   
``` 

**To Reproduce**

Use a skill requiring authentication, this bug does not reproduce every time.

**Expected behavior**

Authentication token should not have a null reference.

**Screenshots**

![image](https://user-images.githubusercontent.com/43043272/51709016-2f652480-1fda-11e9-816b-beb0dacc7b8b.png)

**Additional context**

**Comment by lzc850612** [comment]
I thought I have fixed this issue. Are you on the latest master branch?

**Comment by ryanisgrig** [comment]
@angie4u will follow up with additional context.

**Comment by angie4u** [comment]
Hello team, I experienced this situation with [this release](https://github.com/Microsoft/AI/releases).

**Comment by lzc850612** [comment]
Yes it's been fixed in the latest master
