### ISSUE TITLE
Introduction Message is not working

### ISSUE THREAD

**Issue by Gariantroll** [microsoft/botframework-solutions#627]
**Project**

**Description**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Gariantroll** [comment]
I can not seem to get an introduction message to work.  Is anyone else having this issue?  And just to clear my mind,  is a default message supposed to be active?

**Comment by lzc850612** [comment]
What are you using to test? The Emulator or the 'Test in Webchat' page from azure portal?

**Comment by Gariantroll** [comment]
I tried both, but no luck.  I tried implementing the tutorial for the welcome message, but no dice there either.

**Comment by CoHealer** [comment]
Fix for the issue has been merged into master to be ship with the next release.
