### ISSUE TITLE
Enterprise BOT Template - CompleteAsync is never called when single turn dialogs end

### ISSUE THREAD

**Issue by mekinney** [microsoft/botframework-solutions#643]
**Project**
Enterprise Bot Template

**Description**
Single turn dialogs currently don't properly notify the parent dialog of end of dialog.

CompleteAsync is never called in the parent dialog.  MainDialog in this case.

**To Reproduce**
Create a simple single turn dialog.  This fails for a single step waterfall also.

    var SimpleWaterfall = new WaterfallStep[]
    {
        SimpleStep1,
        SimpleStep2,
    };

    AddDialog(new WaterfallDialog(InitialDialogId, SimpleWaterfall));

    public async Task<DialogTurnResult> SimpleStep1(WaterfallStepContext stepContext, CancellationToken cancellationToken)
    {
        await stepContext.Context.SendActivityAsync(string.Format("SimpleStep1: Count {0}",stepContext.Stack.Count));
        return await stepContext.NextAsync();
    }
    public async Task<DialogTurnResult> SimpleStep2(WaterfallStepContext stepContext, CancellationToken cancellationToken)
    {
        await stepContext.Context.SendActivityAsync(string.Format("SimpleStep2: Count {0}", stepContext.Stack.Count));
        return await stepContext.EndDialogAsync();
    }

**Expected behavior**
Expect the dialog to end properly with EndDialog notification to the parent dialog.

**Fix**
In RouterDialog.cs, execute EndDialog notification in DialogTurnStatus.Empty case where the stack size is 0.
The following code shows the modified Empty case and existing Complete case where the code is duplicated from.

    case DialogTurnStatus.Empty:
        {
            await RouteAsync(innerDc);
            // For trivial cases where the response is single turn.
            // Call the dialog complete functions.
            if (innerDc.Stack.Count == 0)
            {
                await CompleteAsync(innerDc);

                // End active dialog
                await innerDc.EndDialogAsync();
            }
            break;
        }

    case DialogTurnStatus.Complete:
        {
            await CompleteAsync(innerDc);

            // End active dialog
            await innerDc.EndDialogAsync();
            break;
        }

**Comment by hansmbakker** [comment]
@lauren-mills this fix is not applied in [RouterDialog in the nuget package](https://github.com/microsoft/botframework-solutions/blob/master/lib/csharp/microsoft.bot.builder.solutions/microsoft.bot.builder.solutions/Dialogs/RouterDialog.cs) and therefore the bug exists in Virtual Assistant.

Can you please reopen this issue?
