### ISSUE TITLE
[POI] Language Understanding model

### ISSUE THREAD

**Issue by ryanisgrig** [microsoft/botframework-solutions#650]
**Spec Title**
Language Understanding in the Point of Interest Skill

**Area**
Virtual Assistant: Point of Interest

**Spec Content**

Entity | Type | Description | Comments
-- | -- | -- | --
ADDRESS | Simple |   |  
KEYWORD | Simple |   | 
ROUTE_TYPE | List | These are entities that can be used for Azure Maps    to specify a route type. Azure Maps supports the following values:Eco/Fastest/Shortest/Thrilling | Refactor
TRAVEL_MODE | List | The mode of travel for the requested route, it may    not be available for the entire route. Azure Maps supports the following    values:         Bicycle/Bus/Car/Motorcycle/Pedestrian/Taxi/Truck/Van | New
RATING | Simple | Capture the rating as an entity, the data is   already available in some sample queries. Examples: 5/4/3/2/1 stars, top   rated, worst, etc. | New
PRICE | Simple | Capture the price as an entity, the data is already   available in some sample queries. The number entity can be captured, but   without also capturing a currency we cannot discern that it is related to   price. Use  Examples: 5 quid, 10   dollars, "show me restaurants with [2 dollar signs], etc. | New
COMMON_LOCATION | List | Names for common locations that the Point of   Interest Skill references. Office/Home/Destination/Here | New

It would be ideal   to capture both "origin" and "destination"   KEYWORD/ADDRESS/COMMON_LOCATION entities. This requires significant refactoring of the existing language model and related skill code.

Examples:
_find an Italian Restaurant near Golden Gate Park_
_how far is the pharmacy from my office?_

**Links**

**Comment by ryanisgrig** [comment]
Updated status to On Hold as this needs more design

**Comment by Dewain27** [comment]
@ryanlengel  is this still something we need?

**Comment by ryanisgrig** [comment]
I'm going to close this - needs design or feedback from customers on what the POI Skill should offer
