### ISSUE TITLE
Show important emails in O365

### ISSUE THREAD

**Issue by artakerman** [microsoft/botframework-solutions#651]
**Project**
Virtual Assistant, Skills

**Description**
When I search for important emails in O365 tenant using utterances such as "show important emails", I don't get the emails back. However, this functionality works with Outlook.com account

**To Reproduce**
Type: show important emails

**Expected behavior**
Return a list of emails with high priority

**Screenshots**

**Additional context**

Other email functions do work with this tenant

**Comment by lauren-mills** [comment]
@DingmaomaoBJTU can you take a look at this when you get a chance?

**Comment by DingmaomaoBJTU** [comment]
@artakerman Hi, sorry for the late reply. Could you provide more information on how to get an O365 tenant email? I only have outlook email address qiowutest@outlook.com and ms email address qiowu@microsoft.com, could you show me what is O365 tenant email so I can repro?

**Comment by lauren-mills** [comment]
Hey @DingmaomaoBJTU I think he's referring to an Azure AD account, like a microsoft.com address but for another company. Did this work for you with your microsoft email? If so it might be a configuration or feature that needs to be enabled by the company admin on the tenant or something.

**Comment by artakerman** [comment]
@lauren, I do refer to an enterprise email account on O364 tenant. In order to reproduce the bug, I setup a test tenant.

Thanks!

Art
________________________________
