### ISSUE TITLE
Suggested Actions don't show up in Teams

### ISSUE THREAD

**Issue by artakerman** [microsoft/botframework-solutions#654]
**Project**
Virtual Assistant

**Description**
Due to Teams limitations, Suggested Actions don't show up.

**To Reproduce**
Example is running Help command

**Expected behavior**
Need to have the same UX as in Web control

**Screenshots**

**Additional context**
Can Suggested Actions be replaced with Buttons via Middleware?

**Comment by lauren-mills** [comment]
Yes, we could probably make middleware work here. I'll look into it.

**Comment by darrenj** [comment]
Doesn't appear Teams supports suggested actions as suspected: https://microsoftteams.uservoice.com/forums/555103-public/suggestions/36025015-bot-support-for-suggested-actions

**Comment by darrenj** [comment]
@artakerman Can you share a screenshot example of how a reply/card with suggested actions renders for you? If you can grab the activity contents (from the emulator too) that would be great as we think about middleware workarounds and ideally team channel changes

**Comment by lauren-mills** [comment]
I'm not going to have time to work on this right away, but I would start with the TeamsAuthMiddleware from this [PR](https://github.com/Microsoft/AI/pull/410) and modify it to look for any suggested actions on the message and add a hero card or adaptive card based on the buttons.

**Comment by garypretty** [comment]
@lauren-mills @darrenj This seems to be a hot topic at the moment, I picked up some work with related issues on the SDK side and I have a PR open to implement HeroCards as a option for ChoicePrompt which might help if / when merged https://github.com/Microsoft/botbuilder-dotnet/pull/1339

**Comment by darrenj** [comment]
[That](https://github.com/Microsoft/botbuilder-dotnet/pull/1339/files) is very cool, would be nice if we could leverage this approach somewhere (in our teams middleware workaround) to leverage this feature automatically so the developer doesn't have to the "if IsTeams() {....}" logic themselves.

Thanks @garypretty!

**Comment by garypretty** [comment]
@darrenj I am actually having a parallel discussion at the moment about updating the SDK to automatically switch to HeroCards for Teams (when liststyle is set to Auto). Please feel free to drop a comment on the PR if you would like to see this - anything we can do to get around having custom middleware for this would be good.  Comments are on the PR https://github.com/Microsoft/botbuilder-dotnet/pull/1339

**Comment by garypretty** [comment]
@darrenj @lauren-mills The PR was just accepted, which also included the automatic fallback for Teams - this will ship with 4.3 I believe.

**Comment by darrenj** [comment]
Thanks Gary - setting to unblocked as there is a proposed way forward
