### ISSUE TITLE
As a developer, I would like to have a VS template to create a new Skill dialog so I can get started sooner

### ISSUE THREAD

**Issue by gabog** [microsoft/botframework-solutions#656]
**Describe the solution you'd like**
Similar to having templates for Skills, it would be nice if we had a template for a Skill Dialog that: 

- Inherits from SkillTemplateDialog
- Creates the project constructor
- Creates the response files and adds the t4 template
- Creates simple multiprompt dialog (similar to the one created by the Skills template)

**Describe alternatives you've considered**
We manually create new dialogs today.

**Comment by lauren-mills** [comment]
Already in the works!

**Comment by darrenj** [comment]
You can have this in the typescript version right now :-)

**Comment by lauren-mills** [comment]
The SkillDialog item template is included in the latest skill template vsix. The docs for how to use the template can be found here: https://github.com/Microsoft/AI/blob/master/solutions/Virtual-Assistant/docs/virtualassistant-skillenablement.md
