### ISSUE TITLE
HowTo Register an App via portal.azure.com

### ISSUE THREAD

**Issue by ghost** [microsoft/botframework-solutions#659]
**Project**
Virtual Assistant

**Description**
In the documentation it is explained to create new app via https://apps.dev.microsoft.com. But I get message "Insufficient privileges to complete the operation." when I try to create registration for an app. It seems that I need to be Global Administrator. Another possibility is to create the registration via portal.azure.com -Azure AD - Register (Preview).

But there is no documentation how to do it right for Virtual Assistant.

**Expected behavior**
Documentation how to register an app via portal.azure.com for Virtual Assistant.

Thank you.

**Comment by darrenj** [comment]
Hi David,

The Azure Portal route is the new approach for creating this (in preview), have you tried that route to see if you can create the application? I'm assuming you ran into the automatic creation issue hence your trying to do manually?

**Comment by ghost** [comment]
Hello @darrenj 

Yes, I tried. But I'm not sure what are the exact setting, e.g. what to take for 'Supported account types' and where is now 'Leave Allow Implicit Flow checked'?

The consequence is that the deployment seems do not work completely. When testing with Emulator I get the message error Code 401.  So assume that perhabs the registration of the app is not completly correct.

Please advice which settings I should normally take if I use the new route.

Thank you.

**Comment by lauren-mills** [comment]
The Azure Portal method of creating an app registration has been documented here: https://github.com/Microsoft/AI/blob/master/solutions/Virtual-Assistant/docs/virtualassistant-createvirtualassistant.md#skill-authentication
