### ISSUE TITLE
Automated testing of QnAMaker using LU files as the test cases

### ISSUE THREAD

**Issue by darrenj** [microsoft/botframework-solutions#691]
## User Story
As ... a bot developer
I want ... to run automated tests of my QnA  Maker instance using LU files
so that ... I can bulk/batch test my instance and validate that it is returning the correct responses for a given set of questions

## Acceptance Criteria 
*List your requirements.*
- [ ] ...
- [ ] ...
- [ ] ...

## Resources
*Provide any screenshots or conversation mockups to support your request.*
*Learn how to mock up bot conversations with [.chat files](http://aka.ms/bfchatfile).*

## Notes
*Provide any additional information.*
How can a customer/partner perform validation that their QnAMaker instance is returning expected answers for a given test-set of questions and that changes do not materially change results for core questions.
CLI or Unit Test type approach that demonstrates how a file (LU?) could be used to bulk/batch test QnA like with LUIS today
- QnAMaker CLI has a query feature

**Comment by Dewain27** [comment]
@darrenj is there any update on this or should we close?

**Comment by darrenj** [comment]
Not needed with updated testing approach.
