### ISSUE TITLE
POST 404 with Enterprise Bot

### ISSUE THREAD

**Issue by mdrichardson** [microsoft/botframework-solutions#695]
This is a copy/paste issue to move it out of the Emulator repo: 
https://github.com/Microsoft/BotFramework-Emulator/issues/1295

@pendraggon87 (OP)

## Version
4.2.1

## Describe the bug
I am trying to test the Enterprise Bot.  I created the project, followed the command line instructions, and hit Run.  While running, I opened the emulator but when I try to send a message, I get the following:

```
[14:05:51]Emulator listening on http://localhost:60465
[14:05:51]ngrok listening on https://fbeb5ffe.ngrok.io
[14:05:51]ngrok traffic inspector:http://127.0.0.1:4040
[14:05:51]Will bypass ngrok for local addresses
[14:05:51]POST201directline.startConversation
[14:05:53]->messagefdg
[14:05:53]POST404directline.postActivity
```

[bug]
POST 404 with Enterprise Bot

**Comment by pendraggon87** [comment]
Some further clarification after testing:

By default, when creating a new project, IISExpress is selected by default.  Switch that to the name of the project, which will open a command prompt window when run.  Before running, you need to change the launchsettings to also use port 3978 (it is by defualt configured to use a different port).

**Comment by mdrichardson** [comment]
Did this fix your issue, then, and the template just needs to be updated with the correct port?

**Comment by pendraggon87** [comment]
Yes.  Here is what I had to do:

- Open launchSettings.json
- Find the profile for your project, in this case let's say "BotProject"
- Set the port to 3978
- Set the default profile to BotProject instead of IISExpress, as that by default just shows the web page but doesn't expose /api/messages

```
    "BotProject": {
      "commandName": "Project",
      "launchBrowser": true,
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      },
      "applicationUrl": "http://localhost:3978/"
    }
```

**Comment by mdrichardson** [comment]
Thanks. Just to make sure I get the right things updated, what "command line instructions" did you follow? Was it from [this tutorial](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-enterprise-template-create-project?view=azure-bot-service-4.0)? Or was it the `readme.md` within the template after downloading it? Or was it something else?

Typically, an endpoint is created in your .bot file that looks like this:

```
{
            "type": "endpoint",
            "endpoint": "http://localhost:3978/api/messages",
            "name": "development",
            "id": "75"
        },
```

This would make it so you can run with IIS Express. I was able to get a fresh sample up and running just fine. If you can point me to the documentation that you used, I can submit a PR to make it more explicit about adding the endpoint to the .bot file after running `msbot clone services`.

**Comment by mdrichardson** [comment]
I am closing this issue as it doesn't seem to be a blocking issue. Feel free to reopen if you have need to get this resolved.
