### ISSUE TITLE
P3: (POI) Multi-stop

### ISSUE THREAD

**Issue by lauren-mills** [microsoft/botframework-solutions#70]
## User Story
As ...
I want ...
so that ...

## Acceptance Criteria 
*List your requirements.*
- [ ] ...
- [ ] ...
- [ ] ...

## Resources
*Provide any screenshots or conversation mockups to support your request.*
*Learn how to mock up bot conversations with [.chat files](http://aka.ms/bfchatfile).*

## Notes
*Provide any additional information.*

**Comment by Dewain27** [comment]
@darrenj  or @stepknees can we determine if this is something that is still needed.

**Comment by darrenj** [comment]
Not needed given PoI skill usage at this time
