### ISSUE TITLE
bot file generated by "deploy_bot.ps1" contains two production endpoints

### ISSUE THREAD

**Issue by gabog** [microsoft/botframework-solutions#702]
**Project**
Virtual Assistant

**Description**
When I execute a new deployment of VA, the bot file ends up with two production endpoints:
![image](https://user-images.githubusercontent.com/12264946/52288246-d7171680-2939-11e9-87c9-97a86a746c37.png)

**To Reproduce**
Run a full deployment of VA using deploy_bot.ps1 and check the generated bot file. 
I am using master from 2/5/2019.

**Expected behavior**
I assume we should only have one production endpoint in the bot file.

**Comment by lauren-mills** [comment]
I think we just need to remove the production endpoint in the bot.recipe because the new version of msbot clone adds one. Need to verify.
