### ISSUE TITLE
Error when trying to create AADV2 Connection from Powershell with Az Bot authsetting

### ISSUE THREAD

**Issue by awaemmanuel** [microsoft/botframework-solutions#703]
**Project**
Virtual Assistant

**Description**
Using the az bot command to create authsettings, I have a related issue when I try to create the AADv2 connection. It doesn't run for me. I get the error below

**To Reproduce**

1. Key in this command:- `az bot authsetting create --resource-group YOUR_BOT_NAME --name YOUR_BOT_NAME --setting-name "YOUR_AUTH_CONNECTION_NAME" --client-id "YOUR_APPLICATION_ID" --client-secret "YOUR_APPLICATION_PASSWORD" --provider-scope-string "Calendars.ReadWrite Mail.Read Mail.Send Notes.ReadWrite People.Read User.Read" --service Aadv2`
2. Command doesn't work. I end up with error below. 

```
az bot authsetting create: error: the following arguments are required: --provider-scope-string, --service
usage: az bot authsetting create [-h] [--verbose] [--debug]
                                 [--output {json,jsonc,table,tsv,yaml,none}]
                                 [--query JMESPATH] --resource-group
                                 RESOURCE_GROUP_NAME --name NAME
                                 --setting-name CONNECTION_NAME --client-id
                                 CLIENT_ID --client-secret CLIENT_SECRET
                                 --provider-scope-string SCOPES --service
                                 SERVICE_PROVIDER_NAME
                                 [--parameters PARAMETERS [PARAMETERS ...]]
                                 [--subscription _SUBSCRIPTION]
```
**Expected behavior**
The aadv2 connection should be created and oauth settings fields populated.

**Comment by lauren-mills** [comment]
See comment on issue #233

**Comment by lauren-mills** [comment]
Closing this due to age. I think the issue it resolved, but feel free to reopen if not!
