### ISSUE TITLE
email skill doesn't support sending to addresses with "_"

### ISSUE THREAD

**Issue by artakerman** [microsoft/botframework-solutions#705]
**Description**

When trying to send email an email to an address with "_" in the address, for example, art_akerman@outlook.com the code truncates the first word before "_".
**To Reproduce**

User: send email
Bot: who's email going to?
User: art_akerman@outlook.com
Bot: Alright, I will send this to akerman@jabil. What is the email subject?
**Expected behavior**

The solution should keep the same email address as entered.
**Additional context**

The work-around is to create a contact for this type of email address and use contact name to send emails. I submitted similar bug for addresses with ".", it this has been fixed (I tested it in my current build).

**Comment by DingmaomaoBJTU** [comment]
This one is already fixed in latest master branch.
