### ISSUE TITLE
Show calendar for tomorrow - response says "your events for today", can't see multiple events

### ISSUE THREAD

**Issue by artakerman** [microsoft/botframework-solutions#710]
**Project**

**Description**
"Show my calendar for <date>" returns the right event, but the message says "I found event for today". Also, the first card doesn't have the date, so it is hard to tell if this is the right result. If I say "yes" to hear more appointments, the second card does have the date. Also, I can only see one event, even when I have multiple on the calendar.

**To Reproduce**
Show my calendar for Friday

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by KayMKM** [comment]
fixed.
