### ISSUE TITLE
Check all bot files do not exist before running deployment scripts

### ISSUE THREAD

**Issue by garypretty** [microsoft/botframework-solutions#712]
**Project**
Virtual Assistant

**Description**
I have just blown away an existing VA deployment and ran the deployment scripts to deploy to Azure.  I remembered to delete my main bot file, but forgot to delete the locale bot files.  Deployment ran through and configured all my services, but then right at the end threw an error due to my en bot file already existing, meaning I need to start again (I think).  It would be great to check that no conflicting bot files exist before starting the deployment.  Or maybe even provide an option to overwrite?

**Comment by lauren-mills** [comment]
Hi @garypretty, the good news is you don't actually have to start over. Two options are available for this scenario today. You can rerun the deploy_bot.ps1 script with the `-languagesOnly` flag to just deploy the localized services (LUIS, QNA, Dispatch) or you can run the update_published_models.ps1 script to update the existing deployments. 

I'll see if I can also add a way to overwrite existing files with the same name in the script.

**Comment by darrenj** [comment]
Bot files have now been removed :)
