### ISSUE TITLE
[Analytics] Unused fields in PowerBI report

### ISSUE THREAD

**Issue by gabog** [microsoft/botframework-solutions#723]
**Project**
Virtual Assistant, Skills

**Description**
There are several fields in the AppInsights query used by the PowerBI template that don't seem to logged by code:

- FoundInKnowledgeSource = customDimensions.QnAItemFound,
- UserAcceptedAnswer = customDimensions.UserAcceptedAnswer,
- QnAFeedbackScore=customDimensions.FeedbackScore, 
- KnowledgeItemsDiscarded = customDimensions.KnowledgeItemsDiscarded,

**To Reproduce**
Search the source for the customDimensions detailed above and you won't find any references to them.

**Expected behavior**
I expect the fieds to be populated or not in the query if they are not used.

**Comment by ryanisgrig** [comment]
Will modify template to only use the following QnA properties:

- QnAResponse=customDimensions.answer, 
- QnAFeedbackScore=customDimensions.feedbackScore
- QnAConfidenceScore=customDimensions.confidenceScore
- QnAQuery=customDimensions.question
