### ISSUE TITLE
[Point of Interest] If user is missing a location event, they have to explicitly cancel to exit POI skill

### ISSUE THREAD

**Issue by ryanisgrig** [microsoft/botframework-solutions#724]
**Project**
Skills

**Description**
If a user triggers the POI skill without a location event, it will error and be stuck in the POI skill. Any further queries throw the same "missing location" exception until the user cancels out of the dialog.

**To Reproduce**
* Ask the bot for a POI without sending a location event
    * Bot will error
* Ask a question for another skill
    * Bot is stuck in POI skill 

**Expected behavior**

The bot should throw an error and then step back out of the POI skill.

**Screenshots**

**Additional context**

**Comment by lauren-mills** [comment]
Is there a way we can configure a default starting location in the configuration for the skill in appsettings and only throw an error if its not configured? It might help us with demos

**Comment by ryanisgrig** [comment]
That was a suggestion from the bug bash in December, to default back to a message like "I don't know where you are, but I'll use Microsoft HQ as an example." This morning I opened up #755 which would ask a user for a location and extract the coordinates from it, this would get around this issue and avoid the confusion during demos of sending the `IPA.Location` event.

**Comment by ryanisgrig** [comment]
Resolved in #836
