### ISSUE TITLE
Calendar Skill - "between 2 and 3" not being used when booking a meeting

### ISSUE THREAD

**Issue by darrenj** [microsoft/botframework-solutions#725]
## User Story
As ...
I want ...
so that ...

## Acceptance Criteria 
*List your requirements.*
- [ ] ...
- [ ] ...
- [ ] ...

## Resources
*Provide any screenshots or conversation mockups to support your request.*
*Learn how to mock up bot conversations with [.chat files](http://aka.ms/bfchatfile).*

## Notes
*Provide any additional information.*

**Project**
Calendar Skills

**Description**
When booking a meeting with a time range, e.g. between 2 and 3 the LUIS model correctly extracts a datetimerange but the calendar skill doesn't use it and goes on to prompt for this.

**To Reproduce**
- "book a meeting with toby between 2 and 3 tomorrow"

**Expected behavior**
- A datetime of tomorrow and a start of 2pm and a endtime of 3pm

**Screenshots**

![image](https://user-images.githubusercontent.com/33519520/52436998-97cbff80-2aca-11e9-9466-7943bee3ce5c.png)

**Additional context**
```
{
  "luisResponse": {
    "alteredQuery": null,
    "compositeEntities": null,
    "entities": [
      {
        "endIndex": 48,
        "entity": "between 2 and 3 tomorrow",
        "resolution": {
          "values": [
            {
              "end": "2019-02-08 03:00:00",
              "start": "2019-02-08 02:00:00",
              "timex": "(2019-02-08T02,2019-02-08T03,PT1H)",
              "type": "datetimerange"
            },
            {
              "end": "2019-02-08 15:00:00",
              "start": "2019-02-08 14:00:00",
              "timex": "(2019-02-08T14,2019-02-08T15,PT1H)",
              "type": "datetimerange"
            }
          ]
        },
        "startIndex": 25,
        "type": "builtin.datetimeV2.datetimerange"
      },
      {
        "endIndex": 33,
        "entity": "2",
        "resolution": {
          "subtype": "integer",
          "value": "2"
        },
        "startIndex": 33,
        "type": "builtin.number"
      },
      {
        "endIndex": 39,
        "entity": "3",
        "resolution": {
          "subtype": "integer",
          "value": "3"
        },
        "startIndex": 39,
        "type": "builtin.number"
      }
    ],
    "intents": null,
    "query": "book a meeting with toby between 2 and 3 tomorrow",   
    }
  }
}
```

**Comment by KayMKM** [comment]
fixed the exact number can't be recognized issue. but in this case the "3" can't be labelled as ToTime in LUIS. will fix in next version of LUIS model.

**Comment by darrenj** [comment]
@KayMKM Did this get fixed with the latest LUIS models from the pre-built team?

**Comment by lauren-mills** [comment]
Closing, because this seems have been resolved.
