### ISSUE TITLE
Deploy issues

### ISSUE THREAD

**Issue by jamescarr1988** [microsoft/botframework-solutions#732]
Hi,

I have run through all pre-recs and when I deploy, I get the following error,

: az bot publish --resource-group Name -n Name--subscription 11111111111111111111111111111 -v v4 --proj-name "VirtualAssistant.csproj" ERROR: az: error: unrecognized arguments: --proj-name VirtualAssistant.cs          {bot} ... {json,jsonc,table,tsv,yaml,none}] [--query JMESPATH]

It then continues and when I go to the test the bot in the Azure portal, I get -

conversationUpdate event detected

Any ideas?

**Comment by darrenj** [comment]
Hi James - strange. Can you confirm the version of msbot and az bot publish please?

```
az bot --version
msbot -v
```

Do you see your resource group created with all resources? If so, it's worth going to VS and publishing to the created app-service and see if that works?

**Comment by jamescarr1988** [comment]
Hi Darren,
Yeah it's really strange. I recently updated all of the pre-reqs on my computer and have since deleted the BOT and Azure instance. I have tried to re-deploy but I get the same issue. The msbot version is 4.3.2.
When I do deploy I get all of the resources built in Azure and LUIS gets all of its entries but get the error. I then updated the appsettings with the required information and published the app directly from within VS and then get a dot net error.

I then open the BOT using the web app and either get conversationUpdate event detected or error sending.
It's all really strange.
Thanks for your help so far.

**Comment by darrenj** [comment]
Could you share the publishing error in VS – it’s probably more helpful than the CLI tools.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by jamescarr1988** [comment]
Hi Darren,

I will run back through the steps now.

Just to confirm the steps,

Clone Repo

Build solutions in VS

Run the following command from and elevated CMD PowerShell.exe -ExecutionPolicy Bypass -File DeploymentScripts\deploy_bot.ps1 -appId "0000" -appSecret “00000”   within \solutions\Virtual-Assistant\src\csharp\assistant

Update the Bot name, secret and locale name in Appsettings in the solution.

Then within VS, right hand click the VirtualAssitant and create profile and publish to Azure

I hope this is correct.

**Comment by darrenj** [comment]
Yep that looks about right.

**Comment by v-kydela** [comment]
Hello @jamescarr1988

Do you have a publishing error for us?

**Comment by jamescarr1988** [comment]
Hi Kyle,

Sorry for the delayed reply. I redeployed this weekend and after a few attempts, it all seems to be working now. 

Thank you all for your help.

**Comment by v-kydela** [comment]
Glad to hear it! Closing now.
