### ISSUE TITLE
"What's my schedule?" (with question mark at the end) doesn't work

### ISSUE THREAD

**Issue by gabog** [microsoft/botframework-solutions#736]
**Project**
Skills (calendar)

**Description**
When you use speech, the STT adds a question mark to the end of the utterance when you say "what's my schedule" and it seems the dispatcher doesn't recognize that intent as a calendar intent. 

**To Reproduce**
Have the assistant connected to your o365 account.
1. Say "what's my schedule" using speech or type "what's my schedule?" (make sure you add a question mark at the end.
2. The assistant will not do anything.
3. Try typing "what's my schedule" (without the question mark), and you'll trigger the calendar skill.

**Expected behavior**
I would expect the calendar skill to be triggered regardless of me adding the question mark or not.
I would also expect the dispatcher to be smarter than what it is now and I shouldn't be training with or without "?" or "." at the end of the utterances. 

**Additional context**
This seems to be a major issue with dispatcher, a "?" or a "." at the end of a sentence may make the difference between an intent triggering or not. 
This bug is just an example, I've noticed similar things with the new Azure speech where text normalization may add a "." and the end of the utterance and that would cause the skill not to be triggered.

**Comment by darrenj** [comment]
@gabog Yes, Dispatch tool over indexes on utterances with question marks as most stuff in qna has question marks, a tactical fix has been applied to dispatch tool but we don't use on initial deployment. Would be worth a 'dispatch refresh --bot' to see if that addresses the issues. There are new luis models coming too.

**Comment by gabog** [comment]
@darrenj, I don't think the dispatch tool is being used by VA to generate the dispatch model at the moment, dispatch refresh will not generate the same model that the OOTB build generates.

**Comment by darrenj** [comment]
Yes, thats potentially the root of this. We will move back to this tool shortly

Sent from Outlook Mobile<https://aka.ms/sdimjr>
________________________________

**Comment by darrenj** [comment]
Closing, proven to be because the first creation of dispatch isn't being done my botdispatch tool.
