### ISSUE TITLE
Assistant gets stuck after failing to resolve contant name in calendar twice

### ISSUE THREAD

**Issue by gabog** [microsoft/botframework-solutions#737]
**Project**
Virtual Assistant, Skills, Calendar

**Description**
If the calendar skill tries to resolve a contact name twice and it can't find a good much, the calendar flow exists but the assistant ends up in bad state and is unable to resume any other flows.

**To Reproduce**
Ensure you have the assistant configured with your o365 account.
1. Open assistant and say "Schedule a meeting" 
2. Say "bananas" (it won't find it)
3. Say "cacao" (it won't find it and it will exit the calendar skill saying "what else I can help you with")
4. Say "Schedule a meeting" (it will not start the flow and will just say what else i can help you with)

**Expected behavior**
I would expect to be able to use the calendar skill again after I get kicked out from the flow.

**Screenshots**
![image](https://user-images.githubusercontent.com/12264946/52491584-74ba5200-2b95-11e9-97a6-c684d832dcf7.png)

**Additional context**
The wording on the messages of the flow is kind of odd two, that may need reviewing.
It seems that just the Calendar skill hangs, I was able to invoke the email skill after the previous steps in the same session but trying calendar kept failing.

**Comment by darrenj** [comment]
Perhaps a state cleardown issue?

**Comment by gabog** [comment]
Tested this on the latest version of master and it works now. 
Thanks
