### ISSUE TITLE
[CalendarSkill] Calendar fails if the user tries to sign out in the middle of a flow

### ISSUE THREAD

**Issue by gabog** [microsoft/botframework-solutions#738]
**Project**
Virtual Assistant, Skills

**Description**
An internal exception is thrown in SkillDialog when the user tries to sign out in the middle the calendar flow (it may affect other multi turn flows in other skills based on OAuth).

**To Reproduce**
Start a session with the assistant with a user that has o365 linked account
1. Say "schedule a meeting" (you'll be prompted for participants)
2. Say "sign out" 
3. You'll get "sorry something went wrong"

**Expected behavior**
Highest priority I would expect the skill not to crash.
If we allow the user to sign out in the middle of a flow, then the flow should end.
If we don't , then we should tell the user that we didn't understand or that they can't do that at the moment.

**Screenshots**
Exception inside SkillDialog
![image](https://user-images.githubusercontent.com/12264946/52493323-26a74d80-2b99-11e9-8242-0365b3bc025f.png)
Session:
![image](https://user-images.githubusercontent.com/12264946/52493346-32930f80-2b99-11e9-9cac-f88c7ec28c2f.png)

**Additional context**
The exception is thrown inside SkillDialog so this may be affecting other multi-turn skills based on o365,

**Comment by darrenj** [comment]
Check with design but default behaviour should be top level intents can interrupt
