### ISSUE TITLE
[TodoSkill] To Do pagination shows first page twice

### ISSUE THREAD

**Issue by gabog** [microsoft/botframework-solutions#741]
**Project**
Skills, TodoSkill

**Description**
The first page shows twice when paginating over the a list.

**To Reproduce**
1. Create a list with more items than the ones that can be displayed on a page. In this version the page size is items so I created a To Do list with 8 items
2. Say show my to do (and the first 6 items will show up)
3. Say yes when prompted to see more. The same page is repeated

**Expected behavior**
I would expect pagination to work.

**Screenshots**

![image](https://user-images.githubusercontent.com/12264946/52502541-071c1f00-2bb1-11e9-86c1-eb6694c49d2c.png)

**Additional context**
Also the text in the chat window says "Do you want to **hear** more from your list?" In the text window it should say "Do you want to **see** more from your list?" or "Do you want to **read** more from your list?" not "hear", hear is fine for the Speak response but not for text.

**Comment by feich-ms** [comment]
Current design from Quirine is that it will display 6 items but only read the first 3. And then it will read next 3 items but keep the same card if you answer "yes" to "Do you want to hear more from your list?". Let's discuss with Quirine about the experience here

**Comment by gabog** [comment]
I think that what is read aloud shows match what's on the screen. Otherwise is confusing and doesn't make sense in a bot that doesn't have speech.
