### ISSUE TITLE
[Assistant] Bot should use default locale bot file if .bot file for the specified locale is not found

### ISSUE THREAD

**Issue by gabog** [microsoft/botframework-solutions#743]
**Project**
Virtual Assistant

**Description**
VA uses the locale parameter in the activity to locate and use the LocaleConfigurations bot file. In some cases a bot file for that locale doesn't exist and the bot crashes. 

**To Reproduce**
1. Change the emulator settings to send a locale that doesn't have a LocaleConfigurations bot file (I used pt for Portuguese in my repro)
![image](https://user-images.githubusercontent.com/12264946/52503376-5cf1c680-2bb3-11e9-9f83-29779f44b992.png)
2. Start a conversation with the bot and say "hi"
3. You will get it looks like something went wrong
![image](https://user-images.githubusercontent.com/12264946/52503364-55cab880-2bb3-11e9-830e-c5bcd572b552.png)

**Expected behavior**
I would expect for the framework to use the locale configuration bot file for the defaultLocale setting in appSettings.json if a bot file for the given locale can not be found (similar to how the response files work).

**Comment by gabog** [comment]
More info on this one.
This issue is aggravate by the latest version of webchat. At the moment, the webchat doesn't allow you to set the locale parameter and take's it from the OS, we have devs in Holland and Germany that had to change the browser to English to be able to test, they get a "Something went wrong" message if they don't because the bot can find the .bot file for the unsupported language.

**Comment by ctstone** [comment]
Should this not be a bug? The VA is crashing when using the default BF Emulator locale (default = not set, which results in .NET assigning the "iv" or invariant culture). Related to #534

**Comment by darrenj** [comment]
@ctstone The emulator bug is now fixed

**Comment by darrenj** [comment]
@lauren-mills - we should implement fallback to the default locale in VA and then incorporate that thinking into ET

**Comment by darrenj** [comment]
Resolved as part of new template
