### ISSUE TITLE
Azure CLI configure json output as default

### ISSUE THREAD

**Issue by richross** [microsoft/botframework-solutions#752]
**Project**
Virtual Assistant

**Description**
Deploying the Virtual Assistant.  Running the powershell command for installation resulted in an error if azure cli configure is set to output *table* format.  The configuration needs to be *json* format output

**To Reproduce**
az configure -> choose *table* output
run the powershell deploy_bot.ps1 command
displays error stating the subscriptionId is not available.

**Expected behavior**
installation commands will run regardless of the user's az configuration for json v table output.

**Screenshots**
none

**Additional context**
I recall seeing this bug reported elsewhere, which was how I originally did a deployment at the beginning of Jan 2019.  This is still an issue with CLI 2.0.57 and capturing it here so others doing this deployment are aware.

**Comment by darrenj** [comment]
Thanks Rich should be addressed in The new deployment work for Build
