### ISSUE TITLE
As a a developer I would like to pass my own BotTelemetryClient instance to the ServiceCollectionExtensions.AddBotApplicationInsights extension method so I can provide a custom instance of botTelemetryClient that implement by business rules and logging

### ISSUE THREAD

**Issue by gabog** [microsoft/botframework-solutions#764]
**Describe the solution you'd like**
I would like to be able to call services.AddBotApplicationInsights(myBotTelemetry); with my own instance of BotTelemetryClient, right now the class is instantiated in the AddBotApplicationInsights and I have no way of providing my own.

**Describe alternatives you've considered**
duplicating the AddBotApplicationInsights code and using my own class but that would duplicate framework code and may break in future releases.

**Comment by ryanisgrig** [comment]
This is available now, I will pull documentation from [here](https://github.com/daveta/analytics/blob/master/appinsights_blog_42/bot_application_insights.md#overriding-the-telemetry-client-option-2-of-2) to official analytics docs.

**Comment by gabog** [comment]
I missed that options, thanks @ryanlengel. This should work for us.
