### ISSUE TITLE
Expand Linked Accounts / Productivity Skills to support user specified Service mapping

### ISSUE THREAD

**Issue by darrenj** [microsoft/botframework-solutions#774]
## User Story
**As** bot user
**I want** to be able to save account preferences for specific skills
**so that** I don't have to select a provider each time I log in

## Acceptance Criteria 
*List your requirements.*
- [ ] Linked Accounts
     - [ ] Should enable users to configure different account providers per skill per scope (i.e. Work, Personal)
- [ ] Conversation
    - [ ] When you log in with a provider, should have the option to save that setting for that skill
- [ ] ...

## Resources
*Provide any screenshots or conversation mockups to support your request.*
*Learn how to mock up bot conversations with [.chat files](http://aka.ms/bfchatfile).*

## Notes
*Provide any additional information.*
Dependent on #1362 

End users of Virtual Assistants will have a mixed set of services for their digital life. For example in the table below I may use Outlook/Hotmail for my Personal Email/Calendar and Tasks, for Work I use O365 for Email/Calendar and Tasks. 

|          | Personal       |       | Work           |       |
|----------|----------------|-------|----------------|-------|
| Provider | Email/Calendar | Tasks | Email/Calendar | Tasks |
| O365     |                |       | x              | x     |
| MSA      |  x              | x     |                |       |
| Google   |                |       |                |       |
| Todoist  |                |       |                |       |

For example linked Accounts would need "Link Accounts" buttons for each Provider and then for Personal and Work, enabling users to:
  - Select O365 for Work Email/Calendar
  - Select Todoist for Work Tasks
  - Select MSA for personal Email/Calendar and Tasks

Validation rules will need to be available that describe which "class" a skill has implemented - e.g. Tasks for todoist but not email/calendar thus ensuring users cannot select Todoist for Calendar.

Tokens would be stored as we do today but the per-user mapping of preferences will need to be persisted into a user profile store.

Productivity skill dialogs would need design changes to prompt for Work or Personal if the user doesn't provide. e.g. `book a work meeting with Joe` versus `book a meeting with Joe`

**Comment by darrenj** [comment]
Evolution of the Linked Accounts UX to have available token

![image](https://user-images.githubusercontent.com/33519520/54955496-72c90a00-4f1b-11e9-9b94-45428ff7b25a.png)

**Comment by Dewain27** [comment]
We should align this work to the same developer as #1362
