### ISSUE TITLE
[POI] POI skill cannot get list for some utterance 

### ISSUE THREAD

**Issue by angie4u** [microsoft/botframework-solutions#783]
**Description**
Example) **find asian restaurant** - is not working

**To Reproduce**
![image](https://user-images.githubusercontent.com/16282358/52759490-5e0d7280-304f-11e9-8e90-25b56bd24edc.png)

**Expected behavior**
Have to show asian restaurant list near location

**Comment by angie4u** [comment]
I still have the issue with the same input! Is there any update on this bug?

**Comment by darrenj** [comment]
@ryanlengel can you take a look?
