### ISSUE TITLE
[POI] POI skill give wrong result when KEYWORD entity isn't detected in LUIS.

### ISSUE THREAD

**Issue by jongyeop2** [microsoft/botframework-solutions#785]
**Project**

**Description**

User requested POI search using wrong keyword(ex. ssssss), then POI skill give wrong searched result.

**To Reproduce**

in Emulator
/event:{ "Name": "IPA.Location", "Value": "47.614256, -122.328301" }
Find ssssss

then POI skill provide Taylor Shelfish Farms, Homegrown and Elliot Bay Book Company by searched result.  

**Expected behavior**

Have to return "no result"

**Screenshots**

**Additional context**

**Comment by angie4u** [comment]
> **Project**
> 
> **Description**
> 
> User requested POI search using wrong keyword(ex. ssssss), then POI skill give wrong searched result.
> 
> **To Reproduce**
> 
> in Emulator
> /event:{ "Name": "IPA.Location", "Value": "47.614256, -122.328301" }
> Find ssssss
> 
> then POI skill provide Taylor Shelfish Farms, Homegrown and Elliot Bay Book Company by searched result.
> 
> **Expected behavior**
> 
> Have to return "no result"
> 
> **Screenshots**
> ![image](https://user-images.githubusercontent.com/16282358/52764539-f9a8de00-3063-11e9-966c-fa08e207f0a6.png)
> **Additional context**

**Comment by ryanisgrig** [comment]
Do you know what API was called with this? I am guessing the **Whats Nearby** scenario. In this case, we are following the logic that the user has said something that matches the POI intent and if no entities are found it looks up POIS nearby.

I think this is an issue with the POI language model as "find X" is too short and that query could easily be used for other skills as well (find meeting, find email, etc.).

**Comment by ryanisgrig** [comment]
![image](https://user-images.githubusercontent.com/43043272/52888448-891bc300-3130-11e9-9a8c-45099c9ae377.png)

**Comment by angie4u** [comment]
Thanks for the reply! Is there any case exist "pointOfInterestList" returns null or empty?
Or it will always return some value?
For example) Find ssssss -> display poiList which names related to ssssss

**Comment by ryanisgrig** [comment]
In this case, it used the "find nearby" API which returns any APIs near the coordinates. The POI's None intent needs to be strengthened to prevent erroneous lookups like this.
