### ISSUE TITLE
Quota limit on you subscription to the LUIS API

### ISSUE THREAD

**Issue by ghost** [microsoft/botframework-solutions#794]
**Project**
Virtual Assistant,

**Description**
I reached the quota limit for my LUIS subscription. Therefore, the VA does not work anymore.

**Question**
Which key should I enter in which files?

**Comment by garypretty** [comment]
You need to assign an appropriate subscription resource within your LUIS portal. I.e. The paid instance of LUIS (you can do this in the Manage -> Endpoints in the LUIS dashboard).  When you do this you will see two keys available to copy. Take one of these keys and replace the subscription key setting in your locale bot config file for each luis instance.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by lauren-mills** [comment]
We can add a note to the docs for this.

**Comment by ghost** [comment]
@garypretty Thank you for the fast reply. I work on a version of 04.12.2018. There is no LocalConfiguration. But there is the .bot AND _Dispatch.dispatch files. Should I replace in both files the subscriptionKey for the LUIS services?

**Comment by garypretty** [comment]
It's a bot file in a sub folder, which I think from memory it is called something like "locales" (but I might be wrong as I'm not in front of the solution. This folder contains bit files for each configured locale. E.g. YourassistentEN.bot. This is where the LUIS configs for your models will be and that's where you replace the subscription key for each LUIS model.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ghost** [comment]
I have a version of 4.12.2018. There is no such locale  .bot file.

**Comment by lauren-mills** [comment]
@David201406 you need to update the subscription keys in whichever bot file they are configured.

**Comment by ghost** [comment]
@lauren-mills If I replace the subscription key in the .bot file, I get following compiler expection: "System.ArgumentException: 'EncryptedText is not properly formatted'". 

Is there any possibility to reset the quoata of the Starter_Key in LUIS? I have to present at monday the VA before IT Management.

**Comment by lauren-mills** [comment]
You can’t reset your starter key. You need to run “msbot secret — clear — secret YOURBOTFILESECRET” first before trying to change your keys.

**Comment by garypretty** [comment]
@David201406 Just to double check that you are talking about the Virtual Assistant and not the Enterprise Template?  

In the VA, there should be no LUIS configuration in your main bot file (which is encrypted with your secret). There should be a folder called LocaleConfigurations generated when you first deploy your solution, which contains a .bot file for each locale you have.  In my case that is just a single file for en.  In that file should be a LUIS model config for each of the VA OOTB skills (e.g. calendar, email etc).  This is where you would need to change your subscription key and this file should not be encrypted so you should just be able to change it.

As far as I know the LocaleConfigurations folder isn't something recent, but @lauren-mills might be able to confirm this?

In the case you are talking about the Ent Template, then you would need to decrypt your main .bot file and then amend your value (alternatively you could just do this within the emulator which will do this for you).
  
<img width="539" alt="va_solution" src="https://user-images.githubusercontent.com/3900649/52957824-8fa57700-338a-11e9-9f00-0efb0277c91e.png">

**Comment by garypretty** [comment]
@David201406 Just occurred to me that you might be using the TypeScript version, which may not have the locale folders. If so then I would imagine you will need to follow the aforementioned advice from @lauren-mills. My advice was based on the C# VA.
