### ISSUE TITLE
Adding automotive skill with default script hit LUIS limit of 15000 utterances

### ISSUE THREAD

**Issue by Johnson-Zhou** [microsoft/botframework-solutions#799]
**Project**

Virtual Assistant with new skill template
**Description**

Followed instruction from 
https://github.com/Microsoft/AI/blob/master/solutions/Virtual-Assistant/docs/virtualassistant-skills-automotive.md， run command: PowerShell.exe -ExecutionPolicy Bypass -File DeploymentScripts\update_published_models.ps1 -locales "en-us",  it produced error information said limit exceed 15000 utterances.

**To Reproduce**

https://github.com/Microsoft/AI/blob/master/solutions/Virtual-Assistant/docs/virtualassistant-skills-automotive.md

**Expected behavior**

Run without error.

**Screenshots**

output error information can be provided. also the lu and bot.recipe file.
[output.txt](https://github.com/Microsoft/AI/files/2867750/output.txt)
[dispatch.lu.txt](https://github.com/Microsoft/AI/files/2867751/dispatch.lu.txt)
[bot.recipe.txt](https://github.com/Microsoft/AI/files/2867752/bot.recipe.txt)

**Additional context**

**Comment by Johnson-Zhou** [comment]
Darren, have you met the problem when you initially load the auto skill data? I have tried several times and it could be a repeatable issue for me.

**Comment by lauren-mills** [comment]
@outofthecave Is there any chance you've run across this? Darren is out this week.

**Comment by outofthecave** [comment]
Sorry, I just saw this now.  Yes, this is a known issue.  The LUIS training data for the Automotive skill is very large and therefore not meant to be fed into the dispatcher.  We have a second, smaller dataset with Automotive queries that can be used for the dispatcher, but that would not achieve the desired accuracy when used for the Automotive skill itself.  I suggest we add this smaller dataset to the repo and document how to use it for the dispatcher.  @lauren-mills and @darrenj, let's take this offline to discuss how exactly we'll do that.

**Comment by darrenj** [comment]
This is already resolved, there is a separate settings-dispatch model which we use for dispatcher, the full model should not be used. Hence the documentation uses the reduced model for dispatch:

https://github.com/Microsoft/AI/blob/master/solutions/Virtual-Assistant/docs/virtualassistant-skills-automotive.md

Specifically:

- [VEHICLE_SETTINGS_CHANGE](../../../../skills/automotiveskill/automotiveskill/CognitiveModels/LUIS/en/settings_dispatch.lu#VEHICLE_SETTINGS_CHANGE)
