### ISSUE TITLE
[Enterprise Bot Template][C#] QnA Maker Telemetry Middleware sends articleFound=true when no questions matched

### ISSUE THREAD

**Issue by hansmbakker** [microsoft/botframework-solutions#801]
**Project**
Enterprise Bot Template

**Description**
`TelemetryQnAMaker` class sends articleFound=true to Application Insights when no questions matched:

Please see:
https://github.com/Microsoft/AI/blob/master/templates/Enterprise-Template/src/csharp/EnterpriseBotTemplate/Bot%20Framework/Middleware/Telemetry/TelemetryQnAMaker.cs#L83-L96

This does not look correct to me.

**Comment by ryanisgrig** [comment]
Related to #808

**Comment by ryanisgrig** [comment]
Resolved in #868
