### ISSUE TITLE
[ToDoSkill] "Remember to buy milk" triggers POI SKill

### ISSUE THREAD

**Issue by gabog** [microsoft/botframework-solutions#804]
**Project**
Skills, ToDoSkill

**Description**
If I say "Remember to buy milk" the bot things is a POI intent.

**To Reproduce**
1. Set the location of the bot using the Location event.
2. Say "remember to buy milk"
3. The bot will trigger a POI skill
![image](https://user-images.githubusercontent.com/12264946/52878023-b1ec8a00-3129-11e9-8191-041d70b115b1.png)

**Expected behavior**
I would expect VA to understand this is a ToDoSkill intent.

**Comment by ryanisgrig** [comment]
![image](https://user-images.githubusercontent.com/43043272/52972430-bd30f700-336f-11e9-8332-8d3d3c8ed4f5.png)

![image](https://user-images.githubusercontent.com/43043272/52972455-cde16d00-336f-11e9-9e25-c14fb878dec6.png)
