### ISSUE TITLE
[TodoSkill] Mark X complete doesn't detect the entity

### ISSUE THREAD

**Issue by gabog** [microsoft/botframework-solutions#805]
**Project**
Skills

**Description**
When I say "mark *xTask* completed* the bot prompts me for the task name, it doesn't detect the entity.

**To Reproduce**
1. Add meat to your grocery list
2. The bot will prompt you for the task name, it should have inferred that from the utterance.
![image](https://user-images.githubusercontent.com/12264946/52878742-5fac6880-312b-11e9-8088-8f3f330b2f1a.png)
![image](https://user-images.githubusercontent.com/12264946/52878782-7ce13700-312b-11e9-80a7-e6b968c01a5d.png)

**Expected behavior**
I would expect the bot to mark meat as completed and be done with it.

**Comment by feich-ms** [comment]
updated the en luis model to recognize "Mark X complete/done/finished".
