### ISSUE TITLE
Testing newly added skill crashes with (intermediate value).map is not a function

### ISSUE THREAD

**Issue by awaemmanuel** [microsoft/botframework-solutions#812]
**Project**

Virtual Assistant

**Description**

Testing newly added skill crashes with (intermediate value).map is not a function

**To Reproduce**

1. I deployed a new skill and followed the instructions to test it out. 
1. Testing out the sample skill using the default utterance "sample dialog" I see that dispatcher gets the right intent, the bot shows three dots like it's trying to respond and then I get the following error
`[LUIS] (intermediate value).map is not a function`
1. I've added break points in MySkill.cs but it never hits that. 

**Expected behavior**

I should get a response from my skill as the documentation describes

**Screenshots**

**Additional context**

**Comment by darrenj** [comment]
Hi,

The LUIS aspect I think might be unrelated. Sounds like it's not able to match the dispatch intent (using l_ prefixed) to a skill in your configuration. Sometimes a capitalisation issue. Can you check your app.config skill entries have an entry with a dispatchIntent that matches the name? Stick a breakpoint in maindialog.cs line 175 to double check too.

**Comment by lauren-mills** [comment]
` [LUIS] (intermediate value).map is not a function` is an emulator error, not a bot error. If you notice, it will pop up in the log window every time you click the link to view a LUIS trace. 

In addition to checking your appsettings.json as @darrenj mentioned, make sure you have added a project reference in the VirtualAssistant solution to your skill project. That is what usually causes this behavior for me.

**Comment by awaemmanuel** [comment]
@lauren-mills @darrenj Thank you for your inputs It helped unblock me. It was a naming disparity between the LUIS model, dispatch. I can close this ticket now.
