### ISSUE TITLE
Deploy a skill as a separate bot (remote skill invocation)

### ISSUE THREAD

**Issue by artakerman** [microsoft/botframework-solutions#814]
**Problem description**
We have several customers, who already developed bots using different versions of Bot Framework SDK (v.3, v4). They would like to invoke these bots via Virtual Assistant as skills based on intent. We also have customers, who would like to have each new skill deployed as a separate bot to enable different teams tp work on them independently.

Right now, a skill is invoked via in-process method. The solution should allow remote skill invocation while also allowing for low latency and high throughput.

**Comment by darrenj** [comment]
Skills today are Bots themselves with some light change to enable a skill-mode of invocation so all good there. In Vanadium we do plan on enabling remote invocation which would enable the scenario you touch on here.

**Comment by darrenj** [comment]
# tracked with #892
