### ISSUE TITLE
Misleading trace from QnAMaker in the emulator

### ISSUE THREAD

**Issue by gabog** [microsoft/botframework-solutions#827]
**Project**
Virtual Assistant

**Description**
When an utterance is routed to QnAMaker, the emulator shows a trace message stating "Unable to find a QnA Maker service with Knowledge Base ID MyQnAMakerKBId. Please add a QnA Maker service to your bot." but the response comes back fine. 

I tried looking at the code and couldn't find where that message is coming from.

**To Reproduce**
1. Deploy and configure a full VA
2. Open the emulator and say Hi
3. The bot will respond Hello but you'll also see a strange trace in the Log pane:
![image](https://user-images.githubusercontent.com/12264946/53018320-135d7300-3420-11e9-803b-4fec3f3c5a94.png)

**Expected behavior**
I wouldn't expect to see this error in the log since QnAMaker seems to be working fine (or maybe there's something else that is wrong?).

**Comment by lauren-mills** [comment]
This might be related to how we're doing the locale configurations in a different .bot file from the one we're loading in the emulator. Might be a bit before I can look at it.

**Comment by gabog** [comment]
Thanks, it is not critical because QnAMaker works, it is worth researching when we get a chance just in case we are creating unnecessary roundtrips. QnAMaker seems to take a while when is "cold" and I'm still trying to find out why (my app service is always on and a search query should normally be fast).

**Comment by darrenj** [comment]
No extra round-trips, just a side effect of multi locale support. This will "go away" with the changes away from .bot files in the not too distant future.

**Comment by xtianus79** [comment]
@darrenj @lauren-mills this is still an issue.  I was wondering the same thing as the op as I thought it was making a service call in correctly.  

Here is more information from the emulator's response.  Could you reopen this issue until it is resolved? 

I know it is working correctly because I can make changes to the QA service and it actively responds with the updated information.  

> [21:43:08][QnAMaker] Access denied due to invalid subscription key or wrong API endpoint. Make sure to provide a valid key for an active subscription and use a correct regional API endpoint for your resource.

**Comment by lauren-mills** [comment]
@xtianus79 This is an issue for the bot frameowrk emulator. Please raise your issue on their repo: https://github.com/Microsoft/BotFramework-Emulator
