### ISSUE TITLE
Speech reads out QnAMaker markdown symbols

### ISSUE THREAD

**Issue by gabog** [microsoft/botframework-solutions#828]
**Project**
Virtual Assistant

**Description**
VA reads the markdown symbols aloud when an answer in QnAMaker has markdown.

**To Reproduce**
1. Using the emulator, hit the microphone button and say "What can the calendar skill do?"
2. VA will show the response and start saying "hashtag hashtag Overview..." etc.

![image](https://user-images.githubusercontent.com/12264946/53022147-971b5d80-3428-11e9-9e0b-8f6c5904f731.png)

**Expected behavior**
I would expect the assistant to strip out (or have a speech version) of the response and not to read aloud the markdown symbols.

**Additional context**
Here is the lu portion for faq for the example above:
> Source: Editorial
## ? What can the Calendar Skill do?

```markdown
## Overview
The Calendar Skill provides Calendar related capabilities to a Virtual Assistant. The most common scenarios have been implemented in this first release with additional scenarios in development.
## Supported Scenarios
The following scenarios are currently supported by the Skill:
- Show meeting summary - e.g **What's in my calendar** 
- Next Meeting - e.g. **what's my next meeting** 
- Create a meeting - e.g. Book a meeting
- Update a meeting - e.g. Update meeting
- Delete a meeting - e.g. Delete a meeting

**Comment by lauren-mills** [comment]
Seems like these special characters should be stripped from all messages by the SDK, since any message can contain markdown. What do you think, @gabog? Is there any scenario you can think of where you'd want them?

**Comment by gabog** [comment]
For this particular scenario, the response comes as text from QnAMaker and contains markdown, the "Text" property of the activity should preserve the markdown, but the "Speak" property should have a version of the string with markdown stripped out. 

Looking at the response in the emulator Text is set but Speak is not and webchat defaults to the Text property if speech is enabled and the Speak property is not set.

![image](https://user-images.githubusercontent.com/12264946/53035786-3bf76400-3444-11e9-94e9-8ce38a869cbe.png)

@{'text':'The text with **markdown**, 'speak': 'the text without markdown'}

There may be a way of stripping markdown programmatically and autopopulate speak if not provided but I'm pretty bad at regex and not sure if that's easy or hard.

**Comment by lauren-mills** [comment]
We can definitely strip everything using regex, but I was thinking about how speech works more broadly across the service. Seems like we shouldn't have to do custom stripping of these characters on the speak property of the activity every time.

**Comment by gabog** [comment]
If the Speak propery is not specified, then it may be good to let the framework assume the Speak property is a stripped down version of the Text property, but if Speak is specified it should not try to change it and use what the dev specified. I think that will work consistently accross channels.
I wouldn't let WebChat make that call because speech could work different in other channels.
