### ISSUE TITLE
update_published_models.ps1 fails if the LUIS subscription key is not in westus

### ISSUE THREAD

**Issue by gabog** [microsoft/botframework-solutions#837]
**Project**
Virtual Assistant

**Description**
update_published_models.ps1 is update LUIS models if the subscription key is not in westus.

**To Reproduce**
1. Create a VA in eastus, by default the first bot in localeconfigurations file will have your authoring key set in authoringKey and subscriptionKey, and westus as the region for the bot file.
2. Update your LUIS apps in luis.ai with the eastus key that was created by the deployment script.
3. Update the bot file in localeconfigruations and set the LUIS subscriptionKey to the one you associated with the LUIS apps
4. Update the region in the bot file to "eastus"
5. At this point, your LUIS entries should look like:

        {
            "type": "luis",
            "name": "YourBorNameen_Calendar",
            "appId": "YourAppId",
            "authoringKey": "YourAuthoringKey",
            "subscriptionKey": "YourEastUsSubscriptionKey",
            "version": "0.1",
            "region": "eastus",
            "id": "calendar"
        },
6. Try to run update_published_models.ps1 "en-us", you'll get an error saying "*eastus* is not a valid authoring region.  Valid values are [westus|westeuerope|australiaest]"

![image](https://user-images.githubusercontent.com/12264946/53142868-8c191800-3563-11e9-81fc-9d0b989256e3.png)

**Expected behavior**
I would expect to be able to update my LUIS models without getting this error. Maybe we need an authoringRegion parameter in the bot file?

**Comment by lauren-mills** [comment]
I think the region in the bot file is the authoring region... Did you change it manually, or was it changed by the script?

**Comment by gabog** [comment]
I changed it manually once I had to switch to the real LUIS Subscription key instead of the authoring key that is used by default. Region is used at runtime by the recognizer to connect to the LUIS service and it should match the key that you are using or you'll get access denied, makes sense?

**Comment by lauren-mills** [comment]
So it gave you an error when you used westus with the eastus subscription key?

**Comment by lauren-mills** [comment]
We might be able to add a map to the correct region in the script, but it might need to be an SDK change. Or I could prompt for the correct region in the script if it isn't one of the three authoring regions.

**Comment by gabog** [comment]
That would help, but I think the script may need to be updated whenever we light up a new region (doesn't happen often but it might). 

Regarding your other question, if I try to use an East US subscription key and the bot file has westus as the region, I get an acces denied runtime error.
