### ISSUE TITLE
Calendar Skill - Some recipients cause an exception when processing

### ISSUE THREAD

**Issue by darrenj** [microsoft/botframework-solutions#839]
**Project**
Skills

**Description**

Null exception thrown in some instances where the recipient being processed to book a meeting doesn't appear to have something that we expect.

```
{
  "channelId": "emulator",
  "conversation": {
    "id": "4e454920-35bf-11e9-b3d1-03e8d5aee87a|livechat"
  },
  "from": {
    "id": "240",
    "name": "Bot",
    "role": "bot"
  },
  "id": "63fe59f0-35bf-11e9-88ae-ef6c05586202",
  "localTimestamp": "2019-02-21T09:59:34+00:00",
  "locale": "en-us",
  "recipient": {
    "id": "21a9cf48-5093-4a4a-8b0f-24aa7f0de436",
    "role": "user"
  },
  "replyToId": "60bb3ce0-35bf-11e9-88ae-ef6c05586202",
  "serviceUrl": "https://865b47ea.ngrok.io",
  "text": "DialogException: Object reference not set to an instance of an object., StackTrace:    at CalendarSkill.Dialogs.Shared.CalendarSkillDialog.FormatRecipientList(List`1 personList, List`1 userList) in E:\\enlistments\\AI\\solutions\\Virtual-Assistant\\src\\csharp\\skills\\calendarskill\\calendarskill\\Dialogs\\Shared\\CalendarSkillDialog.cs:line 954\r\n   at CalendarSkill.Dialogs.FindContact.FindContactDialog.ConfirmName(WaterfallStepContext sc, CancellationToken cancellationToken) in E:\\enlistments\\AI\\solutions\\Virtual-Assistant\\src\\csharp\\skills\\calendarskill\\calendarskill\\Dialogs\\FindContact\\FindContactDialog.cs:line 259",
  "timestamp": "2019-02-21T09:59:34.415Z",
  "type": "trace"
}
```

**To Reproduce**
I can repro at will using my outlook.com MSA account - e.g. "book a meeting with julieann". I suspect it's because I have multiple matches, some of which don't have a email address set or perhaps some other fields too.

**Expected behavior**
Skill should be more resilient, I suspect I have multiple people matching the first name provided and perhaps one of the recipients doesn't have an email address set thus causing the issue? If so, we should consider skipping over these gracefully?

**Comment by darrenj** [comment]
@garypretty - I think this might be related to the issue you ran into too?

**Comment by DingmaomaoBJTU** [comment]
Re-assign to yue. This is a calendar skill issue.

**Comment by garypretty** [comment]
@darrenj yes, sounds like the same issue.  I think we just need to ensure that the find contact dialog essentially ignores contacts found that don't have email addresses.  Looked like a one line change would resolve this if I remember correctly.
