### ISSUE TITLE
[Telemetry] [Enterprise Template] Dialogs showing as abandoned

### ISSUE THREAD

**Issue by garypretty** [microsoft/botframework-solutions#840]
**Project**
Enterprise Bot Template

**Description**
I am looking at the telemetry gathered by the Telemetry Middleware in the PowerBI dashboard.  A lot of my dialogs are showing as abandoned at the moment, with very few showing as completed.  Right now I am using Begin / ReplaceDialogAsync to move to another dialog within a waterfall, does this then show the calling dialog as abandoned?  

In my case, even though the waterfall hasn't fully completed, the fact that I am sending the user elsewhere means that the dialog in my eyes has completed - is there any way to send this signal to the telemetry?

Would be great to get a steer on this as this is for a significant customer project and they are pushing for a demo of the analytics and right now the data just isn't stacking up so I need to figure out what is happening.

Any guidance appreciated.

**Comment by ryanisgrig** [comment]
The Power BI template looks at all events with the same DialogId, if the most recent status is `WaterfallStep` then it is assumed as "Abandoned." It seems like we should consider another type for the case of transferring over with ReplaceDialogAsync.

Looking into it with @daveta

**Comment by ryanisgrig** [comment]
Closing #840 by Microsoft/botbuilder-dotnet#1555
