### ISSUE TITLE
Enterprise Bot cannot find correct CosmosDB resource from config

### ISSUE THREAD

**Issue by ctstone** [microsoft/botframework-solutions#841]
**Project**
Enterprise Bot Template

**Description**
After creating my bot resources in Azure with `msbot clone services` and configuring my `.env.development` file, I am trying to start the bot locally. After fixing a missing `APPINSIGHTS_INSTRUMENTATIONKEY` config parameter (not documented), I get a new error message

```js
/my-bot/node_modules/botbuilder-azure/lib/cosmosDbStorage.js:36
            throw new Error('The settings service Endpoint is required.');
            ^

Error: The settings service Endpoint is required.
    at new CosmosDbStorage (/my-bot/node_modules/botbuilder-azure/lib/cosmosDbStorage.js:36:19)
    at Object.<anonymous> (/my-bot/lib/index.js:88:17)
    <snip>
```

**To Reproduce**
1. `yo botbuilder-enterprise` with default options
1. `cd {name}`
1. `npm install`
1. `npm run build`
1. `msbot clone services --name "{name}" --luisAuthoringKey "<snip>" --folder deploymentScripts/en/ --location eastus`
1. Copy resources names to `.env.development`
1. `npm start`

**Expected behavior**
The bot reads my development configuration and starts successfully

**Screenshots**
When I debug the bot in `src/index.ts`, I can see that the value of `COSMOS_CONFIG` is actually of type "abs" (Azure Bot Service?) and not "cosmosdb". Both have the same name because they were auto-generated, so it is probably not surprising that the output of `BOT_CONFIG.findServiceByNameOrId(STORAGE_CONFIGURATION)` ([src](https://github.com/Microsoft/AI/blob/master/templates/Enterprise-Template/src/typescript/enterprise-bot/src/index.ts#L105)) returns the "wrong" resource.

**Additional context**
Currently using the `generator-botbuilder-enterprise` yeoman template associated with git branch `master e6a906e5`

**Comment by ctstone** [comment]
Workaround: using the `id` from the .bot file instead of the resource name fixes this issue

Excerpt from `.env.development`:
```ini
APPINSIGHTS_NAME=3
STORAGE_NAME=8
BLOB_NAME=2
LUIS_GENERAL=general
```

**Comment by ctstone** [comment]
This is a problem with the `copy-files` npm script, which is not finding the json files under `src/dialogs/main/resources/`

Current behavior (with --verbose added):

```
copyfiles --verbose --up 1 ./src/**/*.json ./lib

unglobed path: ./src/locales/de.json
unglobed path: ./src/locales/en.json
unglobed path: ./src/locales/es.json
copy from: ./src/locales/de.json
copy to: lib/locales/de.json
unglobed path: ./src/locales/fr.json
unglobed path: ./src/locales/it.json
unglobed path: ./src/locales/zh.json
copy from: ./src/locales/en.json
copy to: lib/locales/en.json
copy from: ./src/locales/es.json
copy to: lib/locales/es.json
copy from: ./src/locales/fr.json
copy to: lib/locales/fr.json
copy from: ./src/locales/it.json
copy to: lib/locales/it.json
copy from: ./src/locales/zh.json
copy to: lib/locales/zh.json
```

And here is the result after changing the glob:

```
> copyfiles --verbose --up 1 ./src/**/**/*.json ./lib

unglobed path: ./src/dialogs/main/resources/Intro.de.json
unglobed path: ./src/dialogs/main/resources/Intro.es.json
unglobed path: ./src/dialogs/main/resources/Intro.fr.json
unglobed path: ./src/dialogs/main/resources/Intro.it.json
unglobed path: ./src/dialogs/main/resources/Intro.json
unglobed path: ./src/dialogs/main/resources/Intro.zh.json
unglobed path: ./src/locales/de.json
unglobed path: ./src/locales/en.json
unglobed path: ./src/locales/es.json
unglobed path: ./src/locales/fr.json
unglobed path: ./src/locales/it.json
unglobed path: ./src/locales/zh.json
copy from: ./src/dialogs/main/resources/Intro.de.json
copy to: lib/dialogs/main/resources/Intro.de.json
copy from: ./src/dialogs/main/resources/Intro.es.json
copy to: lib/dialogs/main/resources/Intro.es.json
copy from: ./src/dialogs/main/resources/Intro.fr.json
copy to: lib/dialogs/main/resources/Intro.fr.json
copy from: ./src/dialogs/main/resources/Intro.it.json
copy to: lib/dialogs/main/resources/Intro.it.json
copy from: ./src/dialogs/main/resources/Intro.json
copy to: lib/dialogs/main/resources/Intro.json
copy from: ./src/dialogs/main/resources/Intro.zh.json
copy to: lib/dialogs/main/resources/Intro.zh.json
copy from: ./src/locales/de.json
copy to: lib/locales/de.json
copy from: ./src/locales/en.json
copy to: lib/locales/en.json
copy from: ./src/locales/es.json
copy to: lib/locales/es.json
copy from: ./src/locales/fr.json
copy to: lib/locales/fr.json
copy from: ./src/locales/it.json
copy to: lib/locales/it.json
copy from: ./src/locales/zh.json
copy to: lib/locales/zh.json
```

**Comment by enzocano** [comment]
Hi @ctstone, thanks for using the new generator!

Actually, the [bot.recipe](https://github.com/Microsoft/AI/blob/master/templates/Enterprise-Template/src/typescript/enterprise-bot/deploymentScripts/en/bot.recipe#L35) used in the generator has different names for each service, however, the `msbot clone service` command ends cropping the `CosmosDB` name.

We'll update the code to filter by services first, and then perform the search by name.

**Comment by ctstone** [comment]
Correction to the above workaround: LUIS_GENERAL should be:

```ini
LUIS_GENERAL={name}_General
```
