### ISSUE TITLE
[POI] Clarify which matched address POI to use if multiple are found

### ISSUE THREAD

**Issue by ryanisgrig** [microsoft/botframework-solutions#845]
**Is your feature request related to a problem? Please describe.**

Street addresses may be the same between cities, if user doesn't clarify the city the skill selects the first found option.

**Describe the solution you'd like**

When multiple addresses are found, clarifiy with the user rather than assume the first is a match.

**Comment by Dewain27** [comment]
@ryanlengel should this be closed?

**Comment by ryanisgrig** [comment]
Yes this is done
