### ISSUE TITLE
copy-templates script for TypeScript Enterprise Bot Generator doesn't work on mac

### ISSUE THREAD

**Issue by galenguilbert** [microsoft/botframework-solutions#847]
**Project**
TypeScript Enterprise Bot Template

**Description**
The script for copying *.json files in the copy-templates script in generators/app/templates/enterprise-bot/_package.json does not work on OSX - refer to https://www.npmjs.com/package/copyfiles to verify behavior.

**To Reproduce**
npm run copy-templates after generating the bot with yeoman

**Expected behavior**
lib/dialogs/main/resources/\*.json and
lib/locales/\*.json files will have been copied from source

**Screenshots**

**Additional context**
I've fixed this locally by escaping quotations around the glob argument for file discovery
```"copy-templates": "copyfiles --up 1 \"./src/**/*.json\" ./lib",```

**Comment by dfavretto** [comment]
Hi @galenguilbert ! This issue relates to #843, and we are working on it; we are making some tests in order to adapt the `copy-templates` script to work in OSX.
