### ISSUE TITLE
Virtual Assistant test and deploy scripts only run on Windows

### ISSUE THREAD

**Issue by ctstone** [microsoft/botframework-solutions#859]
**Project**
Virtual Assistant

**Description**
.NET Core and PowerShell both have good cross-platform support, however this project has a few minor instances where a Windows environment is assumed. Specifically:
* `AutomotiveSkillTest.csproj` uses `xcopy`in a PostBuild exec.
* All of the PowerShell scripts hardcode the use of `\` as a path separator, instead of using `Join-Path`
* the `INTRO_PATH` resource string is hardcoded to use `\` as a path separator which fails at runtime

**To Reproduce**
1. Get a Mac or Linux host that is running .NET Core 2.2 with PowerShell installed
1. Try to build the solution -> fails because `xcopy` does not exist
1. Try to run `deploy_bot.ps1` -> fails because path separators are not correct for the platform
1. Start the bot after successful build and connect a client -> fails because `INTRO_PATH` json cannot be found

**Expected behavior**
* The solution should build on all .NET supported platforms
* Supporting scripts should run anywhere that PowerShell can run
* The bot should be able to load supporting files on all .NET supported platforms

**Screenshots**
N/A

**Additional context**
I'll submit a PR shortly that addresses these

**Comment by ctstone** [comment]
Reopening this issue to address some bug fixes and PowerShell version discrepancies

**Comment by lauren-mills** [comment]
I was able to test the latest changes using PS6 on windows and they worked for me.
