### ISSUE TITLE
P3: LG experimentation

### ISSUE THREAD

**Issue by lauren-mills** [microsoft/botframework-solutions#86]
Once we have the new LG capabilities we need to move all Bot responses into the new LG file format and explore firstly if the LG files provide all of the capabilities (including localisation) that we need and if multiple responses are now needed to train. We can then provide feedback ahead of a wholescale migration to LG

**Comment by lzc850612** [comment]
Changing to Vanadium since we're currently blocked by the LG package depending on an older version of BotBuilder SDK
