### ISSUE TITLE
LUIS dispatch model is sensitive to punctuation

### ISSUE THREAD

**Issue by ctstone** [microsoft/botframework-solutions#861]
**Project**
Virtual Assistant

**Description**
The default LUIS Dispatch training set gives different results for `what's my schedule` and `what's my schedule?`. The former gets correctly routed to the Calendar Skill, but the latter gets routed to QnAMaker. This is significant because the very first suggested action in the "help" menu is `What's my schedule?` which currently yields no response from the bot. FWIW, in the latter case, the correct intent is a very close second (.99 vs .82)

**To Reproduce**
1. Start the VA
1. Ask "help"
1. Click "What's my schedule?" -> no response, but a QnA trace is logged

**Expected behavior**
The bot should route to the Calendar Skill and prompt me to login

**Screenshots**
<img width="299" alt="screen shot 2019-02-23 at 2 48 10 pm" src="https://user-images.githubusercontent.com/3091067/53291012-89444000-377a-11e9-9345-5acc03af7f0d.png">
<img width="275" alt="screen shot 2019-02-23 at 3 06 17 pm" src="https://user-images.githubusercontent.com/3091067/53291156-aed24900-377c-11e9-8222-c0a7b0d04c54.png">

**Additional context**
According to LUIS docs, punctuation is [treated as a separate token](https://docs.microsoft.com/en-us/azure/cognitive-services/luis/luis-concept-prediction-score#punctuation), so the QnA utterances, which almost all contain `?` are probably skewing the model. Maybe strip punctuation from training? Or add the "help" phrases explicitly to the dispatch model?

**Comment by darrenj** [comment]
Can you run `dispatch refresh --bot YOURBOTFILE.bot`. This will resolve the issue, deployment (right now) can't use dispatch CLI which means you don't out of box get the benefit of this recent change. This should fix it for you.

**Comment by ctstone** [comment]
This appears to have fixed the issue, thanks
