### ISSUE TITLE
Skill template uses incorrect TelemetryLoggerMiddleware parameters in Startup.cs

### ISSUE THREAD

**Issue by ctstone** [microsoft/botframework-solutions#865]
**Project**
Skills

**Description**
As reported by @dipanjan77 in #858, the current skill project template is using incorrect parameters to instantiate `TelemetryLoggerMiddleware`. Compile fails with `Error	CS1739	The best overload for 'TelemetryLoggerMiddleware' does not have a parameter named 'logUserName'`

**To Reproduce**
1. Create new project from Skill Template (tested using template version 4.0.5.38)
1. Add `Microsoft.Bot.Solutions` project reference to new skill
1. Run `Update-Package -ProjectName {SkillProjectName}` so that skill dependencies match the rest of the solution (see #858)
1. Compile the new project
1. Compile fails with error above

**Expected behavior**
The project should compile

**Screenshots**
N/A

**Additional context**
It looks like there was a change in the parameters and the code needs to be updated to:
```cs
var appInsightsLogger = new TelemetryLoggerMiddleware(telemetryClient, logPersonalInformation: true);
```

**Comment by ryanisgrig** [comment]
Thanks @ctstone, assuming this is on the Master branch that is our "in-progress" work. This will be resolved for our next release.

**Comment by ctstone** [comment]
@ryanlengel, the VA host solution is using latest master branch, but the template was installed from myget (4.0.5.38 -- not sure which branch/commit that correlates with). Happy to hear there is a fix in the pipeline
