### ISSUE TITLE
[VA] Deployment Updates

### ISSUE THREAD

**Issue by lauren-mills** [microsoft/botframework-solutions#884]
For tracking needed deployment/service updates for 4.4 release.

Deployment
- [ ] Deploy all Azure services from scratch using ARM template
       - [ ] Auto-provisioning of msa appId and pw - pending next az cli release
- [ ] Enable use of existing services
- [ ] Deploy LUIS and QnA Maker models
- [ ] Create Dispatch based on created models

Updates
- [ ] Enable update of published models based on local .lu file updates
- [ ] Enable update of local .lu files based on published models
- [ ] Use dispatch refresh to update dispatch based on changes 

Related issues:
#827
#837 
#790
#752 
#702 
#324
#117

**Comment by darrenj** [comment]
Fairly minor but could we look to echo some progress along the way as it takes quite a while. The suppression of logging can lead to people thinking it's stopped..
