### ISSUE TITLE
Calendar end Email don't compile after running update_published_models.ps1

### ISSUE THREAD

**Issue by gabog** [microsoft/botframework-solutions#898]
**Project**
Virtual Assistant, Skills, Email, Calendar

**Description**
I did a pull from master and executed update_published_models.ps1, this script runs LUISGen and regenerates the C# files for the skills. Once the script completes, the VA solution doesn't compile anymore.

**To Reproduce**
1. On a full version of VA, pull the latest and run update_published_models.ps1 "en-us"
2. Once the scripts complete, try to compile the solution, you'll get a bunch of compiling errors
![image](https://user-images.githubusercontent.com/12264946/53646459-85616380-3c3b-11e9-89fa-72cf8728e33f.png)

**Expected behavior**
I would expect the generated EmailLU, CalendarLU and Dispatch to match what's in the LUIS models.

**Additional context**
I had to revert CalendarLU.cs and EmailLU.cs to the git copy to be able to use the solution. 

The generated dispatch file doesn't match what was in the repo but it doesn't throw any compilation errors, I am not sure if it may be generating runtime errors.

FYI: @bobokids, @KayMKM

**Comment by lauren-mills** [comment]
Have fixes for this ready, pulling in master now
