### ISSUE TITLE
Adaptive Virtual Assistant

### ISSUE THREAD

**Issue by lauren-mills** [microsoft/botframework-solutions#903]
## User Story
As ... bot developer
I want ... a version of Virtual Assistant built using Adaptive Dialogs
so that ... I can take advantage of new conversation features.

## Acceptance Criteria 
*List your requirements.*
- [ ] Convert existing VA functionality to Adaptive Dialogs
- [ ] Convert 1 existing skill to Adaptive Dialogs
- [ ] Connect skill to VA and validate conversation flows

## Resources
*Provide any screenshots or conversation mockups to support your request.*
*Learn how to mock up bot conversations with [.chat files](http://aka.ms/bfchatfile).*

## Notes
*Provide any additional information.*

**Comment by Dewain27** [comment]
Moved to blocked until release of Adaptive Dialogs.
