### ISSUE TITLE
Migrate templates to LanguageGen (LG) responses

### ISSUE THREAD

**Issue by lauren-mills** [microsoft/botframework-solutions#909]
## User Story
As ... a bot developer
I want ... to use Language Generation resources to render my responses
so that ... I can benefit from using all of it's features

## Acceptance Criteria 
*List your requirements.*
- [x] Convert VA Template responses to LG
- [x] Convert Skill Template responses to LG
- [x] Verify localization works correctly
- [x] Verify all adaptive cards work correctly
- [x] Verify all attachments work correctly

## Resources
*Provide any screenshots or conversation mockups to support your request.*
*Learn how to mock up bot conversations with [.chat files](http://aka.ms/bfchatfile).*
N/A

## Notes
*Provide any additional information.*
**Dependent on LG preview NuGet availability

**Comment by Dewain27** [comment]
Moved out of In Progress until Blocker is removed.

**Comment by lauren-mills** [comment]
Blocked by need for helper methods in SDK:
- Need further support in SDK for multi-language support
- Need further support in SDK for helper methods and resource explorer integration
- Need further support in SDK for inline JSON hero cards

**Comment by darrenj** [comment]
Closed by #2552
