### ISSUE TITLE
Adaptive Card designs for Virtual Assistant & Skills

### ISSUE THREAD

**Issue by ryanisgrig** [microsoft/botframework-solutions#916]
# Adaptive Cards & Themes Spec

|Area|
|-|
|Virtual Assistant|

### Design

* The default **Fabric** theme uses UI elements that match the out-of-the-box Web Chat and Adaptive Card design.
    * Additional themes can be provides with replacement image assets, card JSONs, and host config JSON (for a custom Web Chat).
* Cards will be used as supplemental UX to speech and text scenarios. They should avoid interactive UI elements as this requires additional data processing that may not have cross-channel coverage.

### Development
* Developers can unpack a zipped file of image assets and an Adaptive Card host JSON.
* Image assets should maintain consistent names between design packs to enable easy asset replacement.
* When deployed with a Virtual Assistant, assets from individual skills should surface up to the root web app.
* Developers should be able to easily deploy new asset packs into an existing Virtual Assistant & Skills.
    * Card resources should be in a standard location for Skills.
* Store image assets as base64 when possible

### Icons
Every Skill will require a unique icon to identify itself.

### Header
Every card will have a header identifying itself with a Skill icon. Since the current version of Adaptive Cards only supports a single background image, those images should account for the header space to remain unchanged.
The preferred solution would be to assign background images to individual containers, this is on the Adaptive Cards 1.2 *tentative* feature list (Microsoft/AdaptiveCards#2444).

### Users
User avatars should be displayed when possible, and default to a user's initials if one is unavailable (see [UI Avatars](https://ui-avatars.com/) for a sample solution).

|User Avatar|Initials Avatar|
|-|-|
|![User Avatar](https://github.com/ryanlengel/adaptivecards/blob/master/assets/user_avatar.png?raw=true)|![Initials Avatar](https://github.com/ryanlengel/adaptivecards/blob/master/assets/initials_avatar.png?raw=true)|

When displaying a list of users in a meeting or mail, if the count is:
 * 5 or less: display up to 5 user icons
![image](https://user-images.githubusercontent.com/43043272/54848439-7c920980-4c9e-11e9-99fe-6e134618e3e0.png)
 * More than 5: display 4 user icons & a text block with "+ #"
![image](https://user-images.githubusercontent.com/43043272/54848192-e9f16a80-4c9d-11e9-80aa-27900a104b9d.png)

Order them with sender, then alphabetical order.

### Text
Elements should have the appropriate color assigned based on their data status. For example, conflicting calendar appointments should use the alert or warning color.

### Speak
Speak property should give a summary of the card. Keep in mind if the card may be displayed in a carousel; in this case it a Virtual Assistant should read out each card.

### Footer
Show a footer container at the bottom of overview cards to attribute data sources (i.e. Powered by **Microsoft Graph**)

### Virtual Assistant

|[Introduction to a new user](https://raw.githubusercontent.com/ryanlengel/adaptivecards/master/virtualassistant/newuserintroduction.json)|
|-|
|![image](https://user-images.githubusercontent.com/43043272/55245287-0e01fe00-5200-11e9-8709-4d24c0f45502.png)|

|[Introduction to a returning user](https://raw.githubusercontent.com/ryanlengel/adaptivecards/master/virtualassistant/returninguserintroduction.json)|
|-|
|![image](https://user-images.githubusercontent.com/43043272/55244987-769cab00-51ff-11e9-910c-cf7c0831d382.png)|
* When a user is returning to the bot, the VA should show a different card for welcoming back.
* This sample uses a column set of 4 columns that map to enabled skills. Each column has an ImBack submit action that will trigger that skill with a sample query (what's on my calendar today, show my to do list, etc.)

### Calendar Skill

|[Schedule (single day)](https://github.com/ryanlengel/adaptivecards/tree/master/calendar/schedule.json)|
|-|
|![image](https://user-images.githubusercontent.com/43043272/55698229-c571df80-5979-11e9-8f0c-e8282832ac8c.png)|
* Header: Show count of all events that day and overlapping events, user avatar, date
* Show MAX 5 items
* Related meeting data is split between 2 columns: time, event name & location.
    * If meetings are tentative/unaccepted - `isSubtle`:`true`
* If there are meeting conflicts, use the `attention` color on the overlapping time text blocks.

| [Show Meetings per User,Location, and Subject](https://github.com/ryanlengel/adaptivecards/tree/master/calendar/meetings_by_user.json)|
|-|
|![image](https://user-images.githubusercontent.com/43043272/55697686-51363c80-5977-11e9-97ad-9b77208d558b.png)![image](https://user-images.githubusercontent.com/43043272/55697941-7ecfb580-5978-11e9-8276-ace090cfed0f.png)![image](https://user-images.githubusercontent.com/43043272/55697964-9b6bed80-5978-11e9-9fd8-8efbc6defc20.png)|
* Use variant of Schedule Overview with header related to user.
* Paginate through top 3 items and show total count.

|[Meeting](https://github.com/ryanlengel/adaptivecards/blob/master/calendar/meeting.json)|
|-|
|![image](https://user-images.githubusercontent.com/43043272/55427350-a4555d00-553b-11e9-80c9-96288895e6d5.png)![image](https://user-images.githubusercontent.com/43043272/55427360-ae775b80-553b-11e9-8140-bda5278dbb8a.png)![image](https://user-images.githubusercontent.com/43043272/55427378-bb944a80-553b-11e9-9e12-74607384d66a.png)| 
* Show maximum 2 lines of the subject.
* Show maximum 2 lines of location.
* Show maximum 5 lines of body.

### Email Skill
|[Overview](https://github.com/ryanlengel/adaptivecards/tree/master/email/overview.json)|
|-|
|![image](https://user-images.githubusercontent.com/43043272/55698167-7fb51700-5979-11e9-9aab-f2b4b686fd77.png)|

* Header: show count of all unread messages & high priority messages, user avatar, date. 
* Show 5 MAX most recent email items. 
* Related email data is shared in the same container: from user avatar and name, subject, attachment/importance icons, timestamp.
* Timestamp formatting: For the day of, show `HH:mm AM/PM`. For previous days, show `day MM:dd`.
* Show powered by textblock

|[Show Messages per User & Subject](https://github.com/ryanlengel/adaptivecards/tree/master/email/messages_by_user.json)|
|-|
|![image](https://user-images.githubusercontent.com/43043272/55257733-094c4280-521e-11e9-8b42-54986e9f314e.png)|
* Paginate through top 3 items and show total count.

|[Message](https://github.com/ryanlengel/adaptivecards/tree/master/email/message.json)|
|-|
|![Message](https://github.com/ryanlengel/adaptivecards/blob/master/email/message.png?raw=true)|
* Header: Subject, from user avatar and name, datetime with format `day MM/dd HH:mm AM/PM`
* Use maximum 5 lines to display message preview

|[Confirm Whole Email](https://raw.githubusercontent.com/ryanlengel/adaptivecards/master/email/whole_email_confirm.json)|
|-|
|![Confirm Whole Email](https://github.com/ryanlengel/adaptivecards/blob/master/email/whole_email_confirm.png?raw=true)|
* Show the subject, contacts, and message when confirming

|[Confirm Message Content](https://raw.githubusercontent.com/ryanlengel/adaptivecards/master/email/message_confirmation.json)|
|-|
|![Confirm Message Content](https://github.com/ryanlengel/adaptivecards/blob/master/email/message_confirmation.png?raw=true)|
* Only show a title and the message content.

### To Do Skill

|[Show To Do](https://github.com/ryanlengel/adaptivecards/tree/master/todo/show.json)|
|-|
|![image](https://user-images.githubusercontent.com/43043272/55250551-a81b7380-520b-11e9-9388-6e2a5d0f5324.png)
![image](https://user-images.githubusercontent.com/43043272/55250612-d39e5e00-520b-11e9-9dde-d4d2f566539c.png)|
* One task per line
* Investigate if API allows to check for user setting if they prefer to show "checked off" tasks or not.
* Max is 4 to read out.
* When removed, delete.
* When completed, mark as complete.

### Point of Interest Skill

|[Details](https://github.com/ryanlengel/adaptivecards/tree/master/pointofinterest/details.json)|
|-|
|![Details](https://github.com/ryanlengel/adaptivecards/blob/master/pointofinterest/details.png?raw=true)|

|[Route Details](https://github.com/ryanlengel/adaptivecards/tree/master/pointofinterest/routedetails.json)| 
|-|
|![Route details](https://github.com/ryanlengel/adaptivecards/blob/master/pointofinterest/routedetails.png?raw=true)|
* Use status color for route info dependent on delay
    * No/light delay: good (green)
    * Medium delay: warning (yellow)
    * Heavy delay: attention (red)

**Comment by ryanisgrig** [comment]
Should backend APIs be attributed on the card somewhere? i.e. "Provided by X"?
How would this work if cards have data from multiple sources? For example, POI cards using Azure Maps for geolocation and Foursquare for location details.

**Comment by darrenj** [comment]
> Should backend APIs be attributed on the card somewhere? i.e. "Provided by X"?
> How would this work if cards have data from multiple sources? For example, POI cards using Azure Maps for geolocation and Foursquare for location details.

I think this would be a great thing to add into here, "Powered by Microsoft Graph", this will also help on other scenarios where we have data that does need to be attributed. This however is more around highlighting what is powering it (and customers could remove if they wanted to)

**Comment by Quirinevwm** [comment]
+ For the adaptive cards, can we make sure we show 5 max (UX guideline) for the overview of your upcoming events/inbox emails. 
+ for tasks the list is 4 max to read out and remember a task in a list (UX test), the adaptive card should match this. 
+ Paginate through top 3 items and show total count - this option is a bit confusing, it can come across like the date/month format.
