### ISSUE TITLE
SSO authentication - Webchat example, channelData

### ISSUE THREAD

**Issue by darrenj** [microsoft/botframework-solutions#924]
As an enterprise developer I want to make a Bot available to users through WebChat and as it's deployed in the intranet have it single-signon so if the user asks something that requires a token it's already passed seamlessly and doesn't prompt the user to authenticate again.

**Comment by KiranKumar516** [comment]
Any Update regarding the issue. I am also facing the same issue.

**Comment by Dewain27** [comment]
@darrenj is there an update on this item?

**Comment by darrenj** [comment]
Being resolved by WebChat directly
