### ISSUE TITLE
Explore WorkDay/ServiceNow/SalesForce API integration app integration

### ISSUE THREAD

**Issue by darrenj** [microsoft/botframework-solutions#925]
## User Story
As ...
I want ...
so that ...

## Acceptance Criteria 
*List your requirements.*
- [ ] ...
- [ ] ...
- [ ] ...

## Resources
*Provide any screenshots or conversation mockups to support your request.*
*Learn how to mock up bot conversations with [.chat files](http://aka.ms/bfchatfile).*

## Notes
*Provide any additional information.*

Common enterprise integration scenarios shoud be easier, WorkDay/ServiceNow/SalesForce are all common integration targets - a focus on dialogs/integration/luis models would ease this work

**Comment by mlipinski** [comment]
That is a good idea, same vendors are used by a good majority of enterprises.

**Comment by Dewain27** [comment]
@darrenj how do we handle this when a customer has an abstraction layer in front of these services?  Should we put an abstraction layer in place?

**Comment by darrenj** [comment]
The Skill will be the abstraction - we'll provide "pluggable" ways of plugging different providers in but we'll keep it simple.

**Comment by Dewain27** [comment]
Met with Workday and they have informed us that currently there is no Public API for Workday that is currently supported.  Working with their Dev team to determine proper approach.  Until resolved this will be blocked.

**Comment by darrenj** [comment]
ServiceNow initial integration performed
