### ISSUE TITLE
Explore Device Graph integration concept

### ISSUE THREAD

**Issue by darrenj** [microsoft/botframework-solutions#927]
## User Story
As ... a bot user who gets notifications from a Virtual Assistant
I want ... to be able to ask it to "let me continue that later" and shelve it for when I'm on another device
so that ... I can have the samw conversation with my Virtual Assistant over multiple devices

## Acceptance Criteria 
*List your requirements.*
- [ ] ...
- [ ] ...
- [ ] ...

## Resources
*Provide any screenshots or conversation mockups to support your request.*
*Learn how to mock up bot conversations with [.chat files](http://aka.ms/bfchatfile).*

```
bot: You have a new email from Harry.
user: Let me continue that later.
bot: OK.

* user returns to desktop later * 
bot: Here's that email you wanted to be reminded of.
```

## Notes
*Provide any additional information.*
As a user I may be notified about a new email or news article and want to read it in more depth when I next get back to a keyboard therefore I should be able to ask "let me continue that later" and it's surfaced on a keyboard-based device at a latter point

This is dependent on a deployed Enterprise Notifications solution.

**Comment by Dewain27** [comment]
@darrenj we can look at this past #1378

**Comment by ryanisgrig** [comment]
This appears unblocked by the enterprise notifications work

**Comment by darrenj** [comment]
Windows has a different approach for this now.
