### ISSUE TITLE
Phone Skill (Expand Automotive Domain)

### ISSUE THREAD

**Issue by darrenj** [microsoft/botframework-solutions#929]
## User Story
As ...
I want ...
so that ...

## Acceptance Criteria 
*List your requirements.*
- [ ] ...
- [ ] ...
- [ ] ...

## Resources
*Provide any screenshots or conversation mockups to support your request.*
*Learn how to mock up bot conversations with [.chat files](http://aka.ms/bfchatfile).*

## Notes
*Provide any additional information.*

## Phone Skill

In pull request (#1659) and will provide a separate skill for calling scenarios including telephone number and lookup from Google/Email calendars as per the Email skill approach

**Comment by outofthecave** [comment]
Shouldn't Phone, Media, and Tuner be separate skills?  I think they might also be useful outside of an automotive scenario.

Looks good to me otherwise.

**Comment by darrenj** [comment]
Delivered
