### ISSUE TITLE
Enterprise Assistant Focused Skills

### ISSUE THREAD

**Issue by darrenj** [microsoft/botframework-solutions#931]
# Enterprise Assistant Focused Skills

## Overview
Enterprise focused Skills (e.g. Content/Skills) informed through Enterprise customers feedback.. Deliver first iterations of Enterprise focused skills providing core implementations of features every Enterprise builds. e.g. IT/HR.

### Overview

A skill for IT Service Management scenarios focused initially on Tickets. ServiceNow to be the first integration but the skill should be implemented in such a way that you can plug in other IT service providers moving forward.

### Initial Scenarios 
- Raise a Ticket (Fields of default incident template shown below). Customers can and will add their own fields so we should make this easy for them to update as appropriate. Longer term can we retrieve template metadata and be a bit more dynamic?

![image](https://user-images.githubusercontent.com/33519520/62367799-8536fe00-b522-11e9-84d7-fb7a6eee864c.png)

Whilst raising a ticket take the description (as the website does) and perform a search of matching knowledge-base entries and prompt the user before raising the ticket to avoid tickets being raised unnecessarily.

- Update Ticket (change any combination of the fields)
- Show my tickets
- Show Ticket Status
- Close Ticket (with reason)
- Proactive Ticket Status Updates (if possible within the API?)
- Search Knowledgebase (enable the user to search for knowledgebase articles)

### ServiceNow API Integration
- Target London version
- [Free Developer Instance](https://developer.servicenow.com/app.do#!/program/developer) which enables you to create incidents and has example knowledgebase items added.
- [Service Now API](https://developer.servicenow.com/app.do#!/rest_api_doc?v=madrid&id=r_TableAPI-GET)
- [Test Tool](http://wiki.servicenow.com/index.php?title=REST_API_Explorer)
- [Retrieve Incidents Example](https://developer.servicenow.com/app.do#!/document/content/app_store_doc_rest_integrate_madrid_t_GetStartedRetrieveExisting?v=madrid)
- [Create Incident Example](https://developer.servicenow.com/app.do#!/document/content/app_store_doc_rest_integrate_madrid_t_GetStartedCreateInt?v=madrid)
- [Update Incident Example](https://developer.servicenow.com/app.do#!/document/content/app_store_doc_rest_integrate_madrid_t_GetStartedUpdateInt?v=madrid)
- Knowledge Base Search - Same table API can be used across the knowledgebase table

### Adaptive Cards
- Adaptive Card summary of incident and status used for confirmation before creation and when showing ticket status
- Adaptive Card for ticket overview for use when showing tickets
- Adaptive Card for knowledgebase summary and link to knowledgebase item

### LUIS Model
- Intents for CreateTicket, UpdateTicket, CloseTicket, CheckTicketStatus, SearchKnowledgeBase
- EN and ZH only to start and we will replace with a prebuilt domain when ready.

**Comment by bobokids** [comment]
Closed this issue as ITSM focused one. For other enterprise scenario like HR skill, let us open other issue to track.
