### ISSUE TITLE
Provide build pipelines (YAML)

### ISSUE THREAD

**Issue by darrenj** [microsoft/botframework-solutions#932]
As a developer I can create an Azure DevOps pipeline "out of the box" for a Base Bot template created bot which builds/deploys my bot and runs tests

**Comment by srinivasnarula** [comment]
@darrenj - Is there any update on this request?

**Comment by Dewain27** [comment]
@lzc850612 has this been completed yet?

**Comment by darrenj** [comment]
Southworks are working on this as we speak. Typescript is first up with c# to follow. @enzocanoo
