### ISSUE TITLE
[Calendar] Meeting Room Booking

### ISSUE THREAD

**Issue by darrenj** [microsoft/botframework-solutions#934]
## User Story
As ...
I want ...
so that ...

## Acceptance Criteria 
*List your requirements.*
- [ ] ...
- [ ] ...
- [ ] ...

## Resources
*Provide any screenshots or conversation mockups to support your request.*
*Learn how to mock up bot conversations with [.chat files](http://aka.ms/bfchatfile).*

## Notes
*Provide any additional information.*

Prioritise key scenarios with partner teams then design support for flows.

- Meeting Room Booking: Enable meeting room availablity to be identified and booked, along with integration into meeting room booking flow.
"I'm running late": Check the next meeting and offer to let people know. Detect if online meeting if not offer to add skype/teams so the user can dial in

**Comment by ryanisgrig** [comment]
Consider Skill enhancement for mobility travel time (cc: @Quirinevwm)

**Comment by Dewain27** [comment]
@elaine-chang we should determine if best to break this into multiple Issues.

**Comment by fractalcrafter** [comment]
Created a new issue #2429 to track the email skill indicating attachments feature request, and updated the current issue title to focus on calendar skill - meeting room booking feature

**Comment by darrenj** [comment]
Addressed in PR
