### ISSUE TITLE
Productivity Skills - Proactive Scenarios

### ISSUE THREAD

**Issue by darrenj** [microsoft/botframework-solutions#935]
## User Story
As ...
I want ...
so that ...

## Acceptance Criteria 
*List your requirements.*
- [ ] ...
- [ ] ...
- [ ] ...

## Resources
*Provide any screenshots or conversation mockups to support your request.*
*Learn how to mock up bot conversations with [.chat files](http://aka.ms/bfchatfile).*

## Notes
*Provide any additional information.*

Prioritise key scenarios with partner teams then design support for flows.

- [ ] Upcoming meeting
- [ ] Proactive new mail from your team

**Comment by Dewain27** [comment]
Will require #1378 #1362

**Comment by darrenj** [comment]
Addressed in summary skill and manganese
