### ISSUE TITLE
The Power BI report queries are throwing 404 errors

### ISSUE THREAD

**Issue by joelhulen** [microsoft/botframework-solutions#946]
## Project

**Name**: Virtual Assistant, Automotive Skill

**Language**: C# (Power BI report)

## Description

I have deployed and tested the Automotive skill locally. I did not deploy the Virtual Assistant because I only needed this one skill. Application Insights is successfully collecting telemetry data captured while using the Bot Framework Emulator.

When I open the sample Power BI dashboard (`ConversationalAnalyticsSample_02132019.pbit`) and enter the Application Insights telemetry value, I receive the following error while the queries attempt to load the data:

```
DataSource.Error: Web.Contents failed to get contents from 'https://api.loganalytics.io/v1/apps/8986e69b-f11f-4c3f-a801-fe85413aa638/query?query=customEvents%0A%7C%20project%20timestamp%2C%20name%2C%20%0AConversationID%3Dsession_Id%2C%20%0AChannel%3DcustomDimensions.channelId%2C%20%0ALanguage%20%3D%20customDimensions.locale%2C%0AText%20%3D%20customDimensions.text%2C%20%0AQuestion%20%3D%20customDimensions.question%2C%0AFoundInKnowledgeSource%20%3D%20customDimensions.articleFound%2C%0AUserAcceptedAnswer%20%3D%20customDimensions.userAcceptedAnswer%2C%0AKnowledgeItemsDiscarded%20%3D%20customDimensions.knowledgeItemsDiscarded%2C%0AFromName%20%3D%20customDimensions.fromName%2C%0AScore%20%3D%20customDimensions.intentScore%2C%20%0ASentiment%20%3D%20customDimensions.sentimentScore%2C%0Aclient_Type%2C%0Aclient_City%2C%20%0Aclient_StateOrProvince%2C%20client_CountryOrRegion%2C%0AQnAResponse%3DcustomDimensions.answer%2C%20%0AQnAFeedbackScore%3DcustomDimensions.feedbackScore%2C%20%0AQnAConfidenceScore%3DcustomDimensions.confidenceScore%2C%0AQnAQuery%3DcustomDimensions.question%0A%7C%20where%20timestamp%20%3E%20ago%2830d%29%0A%7C%20order%20by%20timestamp%20desc%20%0A&x-ms-app=AAPBI' (404): Not Found
```

Some of the custom dimensions I see in the URL parameters above do not exist as custom properties in Application Insights, as seen in the screenshot below:

![image](https://user-images.githubusercontent.com/5950304/53963664-b9190f00-40bb-11e9-9f94-20088b323794.png)

## To Reproduce

1. Start from a fresh copy of the solution, then generate the bot only for the Automotive skill.
2. Open the generated bot file in the Bot Framework Emulator and send several commands.
3. Open the `ConversationalAnalyticsSample_02132019.pbit` file and paste the Application Insights telemetry key when prompted.

## Expected behavior

The Power BI dashboard should successfully load.

**Comment by ryanisgrig** [comment]
I'm unable to reproduce this - are you using the app insights API key or instrumentation key?
