### ISSUE TITLE
Enterprise Template should include direct line implementation and ADauth

### ISSUE THREAD

**Issue by mlipinski** [microsoft/botframework-solutions#949]
The enterprise template should include direct line built in since the only way to use AD authentication is with direct line.  So that means that the full webchat should be included into the enterprise template as well.

The ability to do Azure AD auth should be built into the Enterprise Template. As it stands, the template has a dialog but you can't run it unless I am mistaken without installing direct line package, installing webchat and customizing the code to use the token properly which should be included in this template by default.

What am I missing here?

**Comment by 01** [comment]
Authentication with AD doesnt require direct line, I am currently using it with direct line web chat and ms teams and have no problem testing it with emulator. The bot framework has code to utilize the token without developer needing to worry about it.  The authentication documentation goes through it.
https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-authentication?view=azure-bot-service-4.0&tabs=csharp

Why are you under impression you need direct line webchat to run the dialog. Have you been unable to run the dialog? Does the authentication card not get sent?

**Comment by mlipinski** [comment]
The documentation in this link is not the same code in use within the enterprise template.  Also, why not include the json to add to the .bot by default instead of having to add it?

The link you sent shows an example of using the AuthenticationBot :IBot class and the enterprise template has a class of AuthenticationDialog :ComponentDialog class in use.

How does this documentation help to configure the enterprise template AD auth properly?

**Comment by 01** [comment]
Its doing the same thing. Have you registered the application and AD connection settings on azure. It wont work out of the box. AD authentication process in the bot framework doesnt differ if you do the check manually for the token or the way its done in Enterprise template which is the dialog. The OAuthPrompt is essentially doing everything you see in the documentation code. 

If you follow the directions for everything other then the code aspect from the documentation for bot authetnication, the Authentication Dialog in the enterprise template should work. 

Have you registered the application and set up permissions you are asking for https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-authentication?view=azure-bot-service-4.0&tabs=csharp#to-create-an-azure-ad-v2-application


What exactly is the issue you are having when running the dialog? What exactly do you think requires direct line? If authentication required direct line, AD authentication would only work with Web chat bots and not any of the other chatting protocols.
