### ISSUE TITLE
Join-Path problematic in generate_deployment_scripts.ps1 

### ISSUE THREAD

**Issue by stepknees** [microsoft/botframework-solutions#954]
## Project

Virtual Assistant

**Language**: 
C#

## Description
Looks like there have been recent changes to how paths are built inside generate_deployment_scripts.ps1, and it's now failing for me. As a result, the LocaleConfigurations folder and locale-specific bots don't get created. 

## Additional context
I resolved by reverting to a previous version of the script.

**Comment by mekinney** [comment]
I have the same issue.  I'm not sure the intention of the changes but replacing:

    $outputPath = Join-Path $basePath "DeploymentScripts" $langCode
    $recipePath = Join-Path $basePath "DeploymentScripts" $langCode "bot.recipe"

with

    $outputPath = Join-Path $PSScriptRoot $langCode
    $recipePath = Join-Path $outputPath "bot.recipe"

fixes the issue for me.

**Comment by lauren-mills** [comment]
Hi everyone, these changes were made to allow the scripts to run on non-Windows environments. In order to run the scripts today, you need to install [PowerShell 6](https://devblogs.microsoft.com/powershell/powershell-core-6-0-generally-available-ga-and-supported/) as is listed in the most up-to-date docs.

**Comment by lauren-mills** [comment]
I'm testing the latest changes, and will get a Mac user to test as well to verify it fixes the issues.

**Comment by mekinney** [comment]
Upgrading to PowerShell 6 worked for me.  FYI...

**Comment by darrenj** [comment]
Great thanks @mekinney. The docs are updated, this was done to support cross platform deployment (osx).
