### ISSUE TITLE
VA: cancel dialog issues

### ISSUE THREAD

**Issue by daveta** [microsoft/botframework-solutions#962]
## Project

**Name**: Virtual Assistant

**Language**: C#

## Description
When I request to go to a location, it provides several options of places it found.  If I cancel out of that prompt, and request to go to a location, the state isn't cleared and it goes back to the same dialog.  This is fine, but it auto-selects the first location.

## To Reproduce
Me: Take me somewhere
Bot: What address are you at?
Me : city center, bellevue
Me: Select City Center
Bot: Here are some options..
Me: Cancel

..
Me: Take me somewhere
Bot: I found a route (which points at the previous dialog invocation, and I did not select a destination)

## Expected behavior
Cancel might clear previous dialog state.  Or at a minimum, when cancel occurs, it shouldn't fill in the current prompt.

**Comment by darrenj** [comment]
Agrred, if the dialog doesn't complete we should drop the state, if it does however, remembering the location is a potentially desirable situation. Would have to work this through with design flows.

Prompting for location (in many situations) is not something we expect will happen as under the covers location of the user will be passed through an event, see [here](https://github.com/Microsoft/AI/blob/master/docs/virtual-assistant/events.md). Sendind some like the below pre-fills the location removing the need to prompt. We used to not prompt at all but this caused first use problems for people.

/event:{ "Name": "IPA.Location", "Value": "47.639620,-122.130610" }

**Comment by ryanisgrig** [comment]
@daveta I've tested this with our latest build and cannot reproduce (I can share transcript). Closing this now, we can reopen if a new case is found.
