### ISSUE TITLE
[VirtualAssistant][TodoSkill]Implement the feature to query for today's tasks when receiving DeviceStart event

### ISSUE THREAD

**Issue by lzc850612** [microsoft/botframework-solutions#969]
## User Story
As ...
I want ...
so that ...

## Acceptance Criteria 
*List your requirements.*
- [ ] ...
- [ ] ...
- [ ] ...

## Resources
*Provide any screenshots or conversation mockups to support your request.*
*Learn how to mock up bot conversations with [.chat files](http://aka.ms/bfchatfile).*

## Notes
*Provide any additional information.*

**Is your feature request related to a problem? Please describe.**
When receiving a DeviceStart event, VA (via todo skill) should query for today's tasks and send a summary to the user proactively

**Describe the solution you'd like**
Use the newly introduced BackgroundTask component to query task storage when receiving DeviceStart event

**Describe alternatives you've considered**

**Additional context**

**Comment by Dewain27** [comment]
Will require #1378 #1362

**Comment by darrenj** [comment]
Addressed by recent summary skill example
