### ISSUE TITLE
[VA][POI]Implement the feature to send a list of places for servicing when receiving engine light on event

### ISSUE THREAD

**Issue by lzc850612** [microsoft/botframework-solutions#973]
**Is your feature request related to a problem? Please describe.**
VA (via POI skill) should prompt user with a list of places for servicing for the car when receiving engine light on event

**Describe the solution you'd like**
When receiving the engine light on event, POI skill does a query for car servicing and send back the list of places to the user

**Describe alternatives you've considered**

**Additional context**

**Comment by ryanisgrig** [comment]
This seems like a demo scenario more than feature, closing.
