### ISSUE TITLE
Virtual Assistant: new task/to do routes to overview

### ISSUE THREAD

**Issue by Quirinevwm** [microsoft/botframework-solutions#995]
## Project

**Name**: VA 

**Language**: C# 

## Description
When I ask shortly to "create" to do/task or "new" to do/task, VA does not help me to set-up a new task but shows the overview of my to do list 

## To Reproduce
User: new task, VA: You have 6 tasks on your To Do list:

## Expected behavior
VA picks up my intent to create a new to do / task quickly. Then responds: Sure. What do you want to put on the list?

**Comment by feich-ms** [comment]
Adding "create task/to do", "new task/to do" to the luis model can make "new task" work, but "create/new" keywords will not work as they are general works which can also trigger email/calendar skills.

**Comment by darrenj** [comment]
Makes sense, can you close the issue once added Please? Thanks.
