### ISSUE TITLE
Virtual Assistant: change order of info in adaptive card for calendar

### ISSUE THREAD

**Issue by Quirinevwm** [microsoft/botframework-solutions#996]
## Project

**Name**: VA

**Language**: 

## Description
Calendar Skill: request to change the order of information shown to user visually in adaptive card (not in speech). 

## Expected behavior
After testing with users on calendar for * overview ("what is on my calendar/what meetings do I have today"), * next meeting ("what/when is my next meeting"), *
New order is:
1. Time range [9.00 AM - 9.30 AM]
2. Subject
3. Participants
4. Location / Skype Meeting

For * create new meeting when VA shows the overview of the appointment for confirmation:
New order in card includes the date in first line:
1. 9.00 AM - 9.30 AM **on [12/3/2019]**
2. Subject
3. Participants
4. Location / Skype Meeting

To conclude, Subject and Time Range need to be switched around and for confirmation of new appointment the date is included in the first line.

**Comment by darrenj** [comment]
@ryanlengel can you review to see if this is needed/applies with the new cards?

**Comment by ryanisgrig** [comment]
@Quirinevwm I think our overview cards follow a different idea of an "overview" vs what you've described here.
![image](https://user-images.githubusercontent.com/43043272/55426569-f4cbbb00-5539-11e9-9d6a-3465f0563aab.png)
![image](https://user-images.githubusercontent.com/43043272/55426582-fe552300-5539-11e9-9799-d1aac3930031.png)

Are these acceptable?

I will follow up and provide updated mockups for the individual meeting card

**Comment by ryanisgrig** [comment]
And here's the meeting sample...
![image](https://user-images.githubusercontent.com/43043272/55427556-1332b600-553c-11e9-9f2a-128afee86b5e.png)
 In this case, the order is:
* Subject
* Time/Duration
* Date
* Participants
* Location

The thinking here was to highlight the subject as a changing title, rather than keep a consistent "Your meeting" as the title.

**Comment by Quirinevwm** [comment]
@darrenj synced with ryan on some changes last week. @ryanlengel I think for the general overview of "your schedule" this fits with showing the time first (+range), subject, location and not showing participants. So the logic after the overview when the user wants to see the details, VA reads out the attendees and the content. Sounds alright and customers can adapt the order of the values for the device they want to use it in.

Was just thinking, users are quite used to seeing time ranges in format XX:XX - XX:XX and then see themselves how long it takes. So, its a better experience to read out from the speech screen (card) of the duration what we discussed the 30min/1hr. But need to do some testing on certain devices for that probably. 

Oh and yes I thought the "Your meeting" was a placeholder for the actual title :)
+ additional is we say "your schedule" (contains events/meetings) should we then also name email "your inbox" (containing emails).

**Comment by KayMKM** [comment]
@Quirinevwm @ryanlengel , should I do any change on these cards now?

**Comment by Quirinevwm** [comment]
@KayMKM I believe @ryanlengel made these changes, double check with him :)

**Comment by ryanisgrig** [comment]
I think this is good for now, the card is renamed to "your inbox."

Time formatting is not implemented but we can take that into consideration in the future.
