### ISSUE TITLE
Virtual Assistant: speech read out of all participants in confirmation message for new meeting and email

### ISSUE THREAD

**Issue by Quirinevwm** [microsoft/botframework-solutions#997]
## Project

**Name**: VA 

**Language**: C#

## Description

 User needs confirmation when sending new email or calendar invite to all participants in speech. 

## Expected behavior
Read out the display names of the alias of all participant that are included in new meeting/email. 
	
! Idea: to think about a maximum read out 3 minimal + #more, then prompt if user wants to hear the full read out of all participants or not. 
! Idea: maximum of participants that can be added in general via VA: up to 20 (needs to be tested in real scenario)

**Comment by bobokids** [comment]
Logic change for showing participants:

!Read out the display names of the alias of all participant the email will be send to.
1-5 participants: read out all alias names. 
 
Rule if >5 participant, add this prompt… 

Add an extra prompt:
Bot: I'm ready to create the event/send the email. The event is on [date] at [time start] till [time end], with [contact person + # more]. The subject of the event is [subject]. Do you want to go through the whole list of participants?
User: Yes
Bot: [List of recipients].
Bot: [After list of recipients or user says “No"] Can you confirm this event/email?
User: Yes
Bot: Okay, I have added the event to your calendar, named [subject].
.

**Comment by Quirinevwm** [comment]
Change part of the prompt. Old = Do you want to go through the whole list of participants?
New = Do you want to go through the rest of the participants?
