### ISSUE TITLE
Virtual Assistant: change "send" utterance when adding participant for new meeting and email

### ISSUE THREAD

**Issue by Quirinevwm** [microsoft/botframework-solutions#998]
## Project

**Name**: VA

**Language**: C#

## Description

Testing shows users feel confused when adding participant(s) and utterance back from VA is "send", they did not include enough info yet for completion. 
Utterance: _Alright, I will **send this** **to** [contact name + email adress] and [contact name + email adress]. What is the subject of the event?_

## Expected behavior

New utterance, change "send" into "add"
_Alright, I will **add** [contact name + email adress] and [contact name + email adress]. What is the subject of the event?_

**Comment by bobokids** [comment]
Logic change for showing participants:

!Read out the display names of the alias of all participant the email will be send to. 
1-5 participants: read out all alias names. 
 
Rule if >5 participant, add this prompt… 
1) Add an extra prompt:
Bot: I'm ready to create the event/send the email. The event is on [date] at [time start] till [time end], with [contact person + # more]. The subject of the event is [subject]. Do you want to go through the whole list of participants?
User: Yes
Bot: [List of recipients]. 
Bot: [After list of recipients or user says “No"] Can you confirm this event/email?
User: Yes
Bot: Okay, I have added the event to your calendar, named [subject].
.
